### PR TITLE
Copy SVG files with samples

### PR DESCRIPTION
**Pull request by PBfordev**
Add few recently added SVG files used for bitmap bundles in samples also to bakefiles and CMakeLists.

**Possible issue** I have replaced _icon.svg_ in the taskbar sample with the one returned by `wxArtProvider::GetBitmapBundle(wxART_WX_LOGO,...)`. However, as I have already mentioned several times, this icon is much smaller (has large margins around) than the original one.  So I am not sure if this change is for the better. OTOH, perhaps the icon art should be made larger...

### CODE REVIEW

**Comment by vadz** [comment]
Thanks, will merge soon!

Concerning the taskbar icon, I don't think it really matters that much, so I'm perfectly ready to just do what you think would be best.

**Comment by PBfordev** [comment]
> Concerning the taskbar icon, I don't think it really matters that much, so I'm perfectly ready to just do what you think would be best.

IMO, it would be for the best to decrease the gap around the picture for the `wxART_WX_LOGO` SVG. The art is now used in taskbar as well as webview sample. 

The toolbar sample uses embedded SVG for that, that looks a bit different, but that is probably by design...

**Comment by vadz** [comment]
> IMO, it would be for the best to decrease the gap around the picture for the `wxART_WX_LOGO` SVG. The art is now used in taskbar as well as webview sample.

Would you please do it? And, if so, should I still merge this PR or will you add this change to it?

Thanks again!

**Comment by PBfordev** [comment]
> > IMO, it would be for the best to decrease the gap around the picture for the `wxART_WX_LOGO` SVG. 
> 
> Would you please do it? 


Sorry, I failed to do that. My intention was to decrease margins from 22 to 5 and adjust the page size accordingly. However, whenever I tried to move the three squares or copy them to another file, their colors changed: They got much lighter. I could not figure out why, I did not see any other objects or layers besides the 3-square group. I even tried upgrading Inkscape from 1.1.2 to 1.2 alpha, still no luck.

TBH, I don't think the art change should be the part of this PR anyway.

**Comment by MaartenBent** [comment]
Hi. I had a look at it and it should be as simple as just changing the viewport.
But the SVG and derived C file are quite bloated, with an online optimizer the size is less than half.

I can create a PR to fix the image.

**Comment by vadz** [comment]
Thanks, I'll merge this one already then and the other one a bit later if there are no objections there.

**Pull request closed without merging**
