### PR TITLE
wxGTK test fixes

### PR DESCRIPTION
**Pull request by vadz**
@paulcor Could you please have a look at 67a9346cc592c7694f46c6a69d65f0046fff207c? This does suppress the warnings (of which there are quite a few in the tests), but I'd like to be sure that it doesn't break something. TIA!

### CODE REVIEW

**Comment by paulcor** [comment]
VZ wrote:
> @paulcor Could you please have a look at
> 67a9346cc592c7694f46c6a69d65f0046fff207c?

I don't see a problem with it. It doesn't stop all the pixman errors
though. I think the real problem is code that sets the size of a window
to less than the widget's requested minimum. GTK3 seems intolerant of
that.

**Comment by vadz** [comment]
Thanks for checking, I'm going to merge it then.

I agree that the real problem is probably elsewhere but it's difficult to see where exactly because we get this "invalid layout" signal (I had no idea such a thing existed...) from idle time callback, so I don't know where exactly does this happen.

**Comment by paulcor** [comment]
VZ wrote:
> I agree that the real problem is probably elsewhere but it's
> difficult to see where exactly because we get this "invalid layout"
> signal

Don't know what you're talking about here. Did you mean 'invalid
"layout" signal'? Why is it invalid? And why would it matter?

**Comment by vadz** [comment]
If you look at the backtrace in [the ticket](http://trac.wxwidgets.org/ticket/16996) you can see that this all happens in response to a signal emitted by `gdk_frame_clock_paint_idle()` (frame `#60`). I didn't know it did this and it matters because it makes it difficult to find the original source of the problem.

**Pull request closed without merging**
