### PR TITLE
Fix `wxPropertyGrid` row height in high DPI

### LINKED ISSUE #24607: Height of properties in a `wxPropertyGrid` is too large at high DPI
This issue can also be seen in the propgrid sample.

#### To Reproduce:

1. Start the propgrid sample.
2. Click on 'File' and 'Run minimal sample' in the menu.

At a DPI scaling of 200%, the properties in the `wxPropertyGridManager` have the correct height, but not those in the `wxPropertyGrid`.
propGrid-vs-propGridManager-dpi-scale-200

### Platform and version information

- wxWidgets version  you use: 3.2.5
- wxWidgets port  you use: wxMSW
- OS  and its version: Windows 10

### PR DESCRIPTION
**Pull request by taler21**
Fixes #24607.

### CODE REVIEW

**Comment by vadz** [comment]
Sorry, could you please explain why is this the right thing to do? AFAICS this should scale with the DPI and the changes of a1c3fa0468 (Fix wxPropertyGrid row height on DPI change, 2019-01-13) done by @MaartenBent look correct to me...

**Comment by taler21** [comment]
First `m_vspacing` isn't a pixel size

https://github.com/wxWidgets/wxWidgets/blob/3737245c5195d84f0c788e650c6ad7992eec03d7/include/wx/propgrid/propgrid.h#L1060-L1065

and second, it should not be reset when moving the window to another screen with a different DPI scaling.
A value set via `SetVerticalSpacing()` should be respected.

**Comment by vadz** [comment]
> First `m_vspacing` isn't a pixel size

Oops, I had no idea about this. It's a really weird API but the PR is obviously correct in the light of this, sorry for missing it.

I'll apply this soon, thanks!

**Comment by taler21** [comment]
Please also backport this fix to 3.2. TIA!

**Pull request closed without merging**
