### PR TITLE
BUG FIX - Windows menu potentially multiple times added to menu bar

### PR DESCRIPTION
**Pull request by hwiesmann**
As the windows menu was not known two wxWidgets' menu structure two problems arose:
 - the wrong search algorithm was used to find the windows menu (actually it could never be found);
 - user were not able to detect whether a windows menu existed or not.

Furthermore, as the windows menu was not cleared from menu items when reusing it OS X added multiple times the names of the existing windows to the menu.

Solving the first issue required a re-write of two methods the second problem was solved at the same time.

### CODE REVIEW

**Comment by vadz** [comment]
I'm not qualified to review this, so I hope Stefan can look at this.

Other than, I wonder if there is any way to get the standard items from the OS somehow instead of recreating them ourselves?

**Comment by csomor** [comment]
Thanks Hartwig, can you reproduce the problem in any of the samples ?

**Comment by csomor** [comment]
never mind, found it with the docview

**Comment by csomor** [comment]
thanks, I'll apply a version along this idea

**Pull request closed without merging**
