### PR TITLE
OSX file dialog extensions

### PR DESCRIPTION
**Pull request by csomor**
will be based on https://github.com/wxWidgets/wxWidgets/pull/2591 combined with old reactivated delegate code

### CODE REVIEW

**Comment by jey5nd6** [comment]
FYI: I had to change the place where it checks `respondsToSelector:@selector(isAccessoryViewDisclosed)` to have it check `setAccessoryViewDisclosed` to prevent a crash.

**Comment by csomor** [comment]
> FYI: I had to change the place where it checks `respondsToSelector:@selector(isAccessoryViewDisclosed)` to have it check `setAccessoryViewDisclosed` to prevent a crash.

@jey5nd6 wow, thanks a lot, now that's very interesting, I first was using a property access for this, that's why I was testing the getter not the setter, both should be available from 10.11 on, so are you getting a crash under 10.10 ?

**Comment by jey5nd6** [comment]
No, that's what's really weird: we're seeing the crash on 10.14 and 10.15.

**Comment by jey5nd6** [comment]
(Sadly I haven't figured out how to tell CLion where my wxwidgets source is after we re-jiggered the build system a while back, so I couldn't debug into it.)

**Comment by csomor** [comment]
> No, that's what's really weird: we're seeing the crash on 10.14 and 10.15.

and when saving or when opening ? as NSOpenPanel derives from NSSavePanel, and these properties are only documented on NSOpenPanel ...

anyway is your fix the same line as I just commited ?

**Comment by jey5nd6** [comment]
Save panel.  And yes, your fix is the same I made.

**Comment by csomor** [comment]
> Save panel. And yes, your fix is the same I made.

thanks, then it is an undocumented property that also can exist on a save panel, but there's not setter there ...

**Pull request merged**
