### PR TITLE
Install pkg-config to fix Travis build for macOS

### PR DESCRIPTION
**Pull request by swt2c**

### CODE REVIEW

**Comment by swt2c** [comment]
Didn't work.  Don't merge.

**Comment by vadz** [comment]
This definitely looks like the right thing to do to me (I have no idea how could we make the mistake which must surely be *the* most common one when using `PKG_CHECK_MODULES`, it's even specifically mentioned in [the book](https://autotools.io/pkgconfig/pkg_check_modules.html)) and the build has passed, so why exactly shouldn't this be merged?

**Comment by swt2c** [comment]
That comment was for one of my earlier attempts at changing .travis.yml.  :-)

The latest commit is good to merge IMO.

**Comment by vadz** [comment]
Ah, sorry for misunderstanding, I'll merge it then, thanks! BYW, in the meanwhile, I thought what could possibly be wrong with this change and decided that perhaps we shouldn't be using `PKG_PROG_PKG_CONFIG()` when using MSW. But then I'm not even sure about this, I've never used `pkg-config` there, but maybe it does work with MSys? Anyhow, this is a minor enhancement at best.

**Comment by swt2c** [comment]
> Ah, sorry for misunderstanding, I'll merge it then, thanks! BYW, in the meanwhile, I thought what could possibly be wrong with this change and decided that perhaps we shouldn't be using PKG_PROG_PKG_CONFIG() when using MSW. But then I'm not even sure about this, I've never used pkg-config there, but maybe it does work with MSys? Anyhow, this is a minor enhancement at best.

I kind of wondered about that too, but you can see in the MSys build log from the PR that it finds `pkg-config` just fine:
https://ci.appveyor.com/project/wxWidgets/wxwidgets/build/1694/job/5pvfa2kxujwjq0iq

**Pull request merged**
