### PR TITLE
Add CMake build with MSVC to GitHub Action CI workflow

### PR DESCRIPTION
**Pull request by vadz**
This is #2459 rebased on master.

### CODE REVIEW

**Comment by vadz** [comment]
Ugh, this doesn't work because CMake selects clang compiler. @Be-ing or @MaartenBent do you know how to tell it to use MSVC? I only know how to use it with MSVC generator but not ninja.

**Comment by Be-ing** [comment]
Run this action before CMake: https://github.com/seanmiddleditch/gha-setup-vsdevenv

**Comment by vadz** [comment]
Sorry but you do run this already (just in case you've missed it, this PR starts with your own commit) and it clearly doesn't help.

**Comment by Be-ing** [comment]
Oh right, that's what I stumbled on in my original PR... :/ Sorry, I'm not sure what the problem is.

**Comment by Be-ing** [comment]
Ah, right, I've had to set the `CC` and `CXX` environment variables in other projects' GitHub Actions workflows.

**Comment by vadz** [comment]
Thanks Maarten! This (almost) worked, now there is just a [failing test](https://github.com/wxWidgets/wxWidgets/runs/4476823977?check_suite_focus=true#step:9:210) but this might happen just because the file `..\mkinstalldirs` doesn't exist because the test seems to be run from `D:\a\wxWidgets\wxWidgets\build_cmake\lib\vc_x64_dll` directory (where `test_base.exe` itself is found) and not `tests` subdirectory.

Can we tell CMake to copy the file to the parent directory of this one? Or should we change the test to make it smarter?

**Comment by MaartenBent** [comment]
Does it matter that the file does not exist? To me it looks like it fails because there is a slash mismatch:
`"..\mkinstalldirs" == "..\\mkinstalldirs"`

**Comment by vadz** [comment]
> Does it matter that the file does not exist?

Yes, I'm almost sure it does.

> To me it looks like it fails because there is a slash mismatch: `"..\mkinstalldirs" == "..\\mkinstalldirs"`

No, I think it's just CATCH not printing the value and the expression in the macro in the same way. Also, if it were due to this, the test would fail in non-CMake CI runs too, but it passes.

**Comment by MaartenBent** [comment]
Then the easiest would be to copy `mkinstalldirs` to the build directory and make the test a bit smarter to check both the current directory and the directory above.

Add `../mkinstalldirs:mkinstalldirs` to `TEST_DATA` in `build/cmake/tests/base/CMakeLists.txt`.

(It would also work with just adding `../mkinstalldirs` to `TEST_DATA` and not modifying the test, but I don't like to clutter the `lib` folder with unneeded files)

**Comment by vadz** [comment]
I've finally updated the test to use another test file, which should already be there, after renaming it to have a "long" name (which also made me realize that this test was actually almost never executed, it's quite strange that the GitHub Actions machines use non-default value for this registry parameter).

**Comment by vadz** [comment]
I see some warnings (`Policy CMP0043 is not set: Ignore COMPILE_DEFINITIONS_<Config> properties.`), but the build passes, so I'm going to merge this, finally.

**Pull request merged**
