### PR TITLE
Try to fix WebRequest::Put test in AppVeyor

### PR DESCRIPTION
**Pull request by MaartenBent**
Lets see if AppVeyor decides to fail, and if it will have an useful error code.

### CODE REVIEW

**Comment by PBfordev** [comment]
I am not sure I understand the purpose of this PR,  I assume you know about it but just to be sure: There is `wxLogLastError()` function, which can provide more information about the reason why these API calls fail, logging also information provided by `GetLastError()`.

**Comment by MaartenBent** [comment]
I'm trying to figure out why the `WebRequest::Put` sometimes fails in AppVeyor.  `wxLogError` will put the info in the AppVeyor output.

**Comment by MaartenBent** [comment]
The output of [this](https://ci.appveyor.com/project/wxWidgets/wxwidgets/builds/37526757/job/sn7r94ssexs016un#L1696) test shows that the number of bytes being written is incorrect. It tries to write 65536 bytes two times, while the second time it should only be 3316 bytes. So it seems the callback is already called before `WinHttpWriteData` has updated the number of bytes written.
I tried to improve this by setting the number of bytes written in the callback. Lets see if this resolves the problem.

**Comment by vadz** [comment]
Wow, great, thanks a lot for finding this! I thought I had read this code carefully by I still failed to notice that we could get called back from `::WinHttpWriteData()` immediately, before updating the number of bytes written -- which I think is what happens here, right?

Anyhow, thanks again, this would have been a very unpleasant bug to hit in production (I'm not implying it was pleasant fixing it in the tests...)!

**Comment by vadz** [comment]
Thanks again for fixing this!

**Pull request merged**
