### PR TITLE
ABI check improvements

### PR DESCRIPTION
**Pull request by vadz**
Both of these commits should probably be backported to 3.0 too.

### CODE REVIEW

**Comment by swt2c** [comment]
Any chance you would be willing to consider making a compile time option for disabling the ABI check?

Debian and Fedora (probably others too) are continuing to patch it downstream as it causes more trouble than it finds:
https://salsa.debian.org/freewx-team/wx/blob/wx3.0-debian/debian/patches/warn-for-compiler-abi-mismatch.patch
https://src.fedoraproject.org/rpms/wxGTK3/blob/master/f/wxGTK3-3.0.3-abicheck.patch

**Comment by vadz** [comment]
I am against having an option, but I'd be fine with disabling this warning if it's really more harmful than useful. One simple thing we could do would be to handle all g++ versions with ABI `>= 1002` as compatible with it by default.

What do people think about it (@ojwb any thoughts?)?

**Comment by ojwb** [comment]
The situation is that GCC changed to defaulting the the latest C++ ABI revision that the version in use supports a while back (GCC5 maybe?) and since has had a series of C++ ABI revisions, but these only ever affect obscure corner cases so very little code is affected.  So the current reality is that these checks cause a lot of unnecessary build failure since then, and that probably does more harm than good (at least for GCC - I've little idea what the situation is with MSVC, except for a vague recollection that you can't mix code built with debug and non-debug).

In Debian we've been patching out the hard-fail part of this code since shortly after GCC switched.  There's been pressure from some people for us to drop the check entirely, which I'm somewhat sympathetic to but reluctant to do without upstream agreement because upstream inevitably ends up having to deal with users running distro packages (looks like I then failed to actually raise this issue though).

I suspect that for GCC this check has never really been very useful because it happens at runtime not compile time.  Back in the GCC3 era there were several significantly incompatible changes to the C++ ABI.  It was ~15 years ago so memory is a little hazy, but my recollection is that these always manifested as link errors (but with no obvious sign that the cause was mixing compiler versions).  These were a problem because they confused people who had inadvertently mixed code compiled with different compiler versions (e.g. because they had upgraded their distro g++ package), but a run-time check wouldn't help when there was a link failure.

Back in the GCC3 era, in Xapian we actually added a compile-time check in a specially generated library API header to give a clearer error in this situation (and also meant that the affected user got an error on the first application source file compiled, rather than completing a build and only hitting the problem when they tried to run it).  We relaxed that check to a warning with the GCC C++ ABI default change, and that's worked fairly well - you get a build-time warning which means there's some warning in case something is up, but end users don't get needlessly non-functioning applications, or a scary sounding message on start-up.

I don't think it's worthwhile trying to copy that approach for wx at this point though.  Fundamentally it's not really a library's job to try to ensure a sane tool-chain.  If there are common cases that cause user confusion and can reliably be checked for that's one thing, but it feels we're into a reverse yak-shaving exercise here (much like standard yak-shaving, except things get hairier the longer you work).

I think it's worth considering simply giving up on a C++ ABI check for GCC.  Presumably it was motivated by the same GCC C++ ABI changes that motivated Xapian's check, but we are in a very different era of GCC C++ ABI stability now.

**Comment by vadz** [comment]
The intention of the ABI check is to catch incompatible builds of wx from a program using it if the incompatibilities do _not_ result in link errors. I don't really know if the compiler and compiler version checks actually help with this or not, to be honest. But I do think that it is nice to check for wx ABI differences, such as using STL containers or not -- assuming this doesn't result in link errors (right now it seems to actually do, but can we rely on this always happening?).

The original intention was to also embed the values of `wxUSE_XXX` options that affect ABI into the build description string, and, again, I think it would be useful -- but considering that this hasn't been done since 15+ years, I don't know how realistic is it to expect it to happen any time soon...

Anyhow, pragmatically speaking, I think freezing `wxGXX_EFFECTIVE_ABI_VERSION` at 1002 value should avoid any problems with it in practice right now. And we could make it more useful later... Or do you still think it should be removed completely?

**Comment by ojwb** [comment]
To be clear, I was only suggesting the checks on the GCC C++ ABI version should go - i.e. stop looking at `__GXX_ABI_VERSION`.

In practice, using `std::min(__GXX_ABI_VERSION, 1002)` for the check pretty much achieves that, though it seems fairly pointless to keep this machinery - it only helps people mixing GCC < 3.4 and more recent versions.

(FWIW, I'm not really convinced that most of the other checks make much sense as run-time checks because I just can't see how mismatched combinations would get that far, but they don't seem to result in any false positives so aren't problematic in the same way the checks on `__GXX_ABI_VERSION` now are.)

> The original intention was to also embed the values of wxUSE_XXX options that affect ABI into the build description string, and, again, I think it would be useful -- but considering that this hasn't been done since 15+ years, I don't know how realistic is it to expect it to happen any time soon...

That would probably be something else packagers would end up having to patch out - e.g. when the debian packaging disabled the webview library a while back (because the GTK2 webkit library was very old and unmaintained and slated for removal from debian) `wxUSE_WEBVIEW_WEBKIT` was no longer defined when wxwidgets was built, and suddenly all applications would fail because it was defined when they were built.  But those applications actually still all worked fine, except for boinc (only package using webview) and I can't see how you could realistically create a situation where boinc would get as far as the ABI check code.  (Scott's now added a GTK3 flavour and the webview library is back for that).

Anything which requires distros to do an otherwise unnecessary rebuild of all dependent packages is something that's very likely to get patched out.

**Comment by vadz** [comment]
I've finally done the smallest possible change in 7f1d08d5bd, hopefully it should solve the problem for both @swt2c and @ojwb in practice -- but please let me know if it doesn't.

**Comment by ojwb** [comment]
@vadz Yes, that looks like it should mean we can drop the Debian patch once we package 3.2 - thanks.

**Pull request closed without merging**
