### PR TITLE
Fixed for undocked AUI window constantly growing under wxQT

### PR DESCRIPTION
**Pull request by ffa-grahamdawes**
This PR allows a pane to be undocked, moved around and redocked when using wxQT without the window constantly growing with each drag.

### CODE REVIEW

**Comment by vadz** [comment]
Do we have any idea why we can't use `isMouseDown()` under Qt?

Also, the code in `DoMoveWindow()` is a bit weird: if `resize()` takes client size already, why do we implement `DoSetClientSize()` using `setGeometry()` instead of `resize()`? Are they one and the same?

**Comment by ffa-grahamdawes** [comment]
Sorry, thought I'd already replied to this.  The `isMouseDown()` is unreliable under QT as it doesn't report that a mouse button is pressed if the user clicks in the non client area (in other words it can't detect the user is dragging the title bar).

The DoMoveWindow is a bit odd.  I agree it would better implemented using `setGeometry`

**Comment by liamtreacy** [comment]
> The DoMoveWindow is a bit odd. I agree it would better implemented using `setGeometry`

The latest commit contains this change and a way to check for invalid '-1' values for the width and height, and correct them.

**Comment by ffa-grahamdawes** [comment]
Closing as there is a more complete fix available.

**Pull request closed without merging**
