### PR TITLE
3.2.5 backports 202403

### PR DESCRIPTION
**Pull request by vadz**

### CODE REVIEW

**Comment by lanurmi** [comment]
How about PR #23113

**Comment by jolz** [comment]
Please include https://github.com/wxWidgets/wxWidgets/commit/92649ca2e6f982d80314eb8dd758941a6894910a in 3.2.5 too. Thank you. (std::string_view fix)

**Comment by vadz** [comment]
> Please include [92649ca](https://github.com/wxWidgets/wxWidgets/commit/92649ca2e6f982d80314eb8dd758941a6894910a) in 3.2.5 too. Thank you. (std::string_view fix)

I'm not sure if this one is ABI-compatible unfortunately.

**Comment by mcorino** [comment]
@vadz Is the 3.2.5 release still imminent?

**Comment by vadz** [comment]
> @vadz Is the 3.2.5 release still imminent?

Sorry, I had several (not wx-related) problems last week and so couldn't do anything at all and we'll have to postpone this release. To keep up with our release dates convention, let's make it on 5/5 now.

**Pull request merged**
