### PR TITLE
MSW: Fix decimal point assert with unknown win32 locales

### PR DESCRIPTION
**Pull request by vslavik**
This is a deceptively simple patch that requires careful review — I am *far* from sure it is the right thing to do. In fact it contains two commits, showing my first fix, and then its replacement by what I think is a correct one (i.e. commit one shouldn't be merged), which I realized in the process of writing this description.

I am sure *something* needs to be done, though.

I started getting unexpected assert from `GetInfoFromLCID()` on Windows 10 (20H2) here:
```cpp
// As we get our decimal point separator from Win32 and not the
// CRT there is a possibility of mismatch between them and this
// can easily happen if the user code called setlocale()
// instead of using wxLocale to change the locale. And this can
// result in very strange bugs elsewhere in the code as the
// assumptions that formatted strings do use the decimal
// separator actually fail, so check for it here.
wxASSERT_MSG
(
    wxString::Format("%.3f", 1.23).find(str) != wxString::npos,
    "Decimal separator mismatch -- did you use setlocale()?"
    "If so, use wxLocale to change the locale instead."
);
```

The app sets locale at launch to user's default one. Which in my case was English, so this was confusing. Turns out, it was a special kind of English, namely en-AT ("English as spoken in Austria"), which, uh, a weird choice of thing to explicitly support in latest Windows 10 builds. At some point, I must have configured this locale during setup - as a way to get European time and date formatting with US English texts… and also "," for decimal point. Presumably that's common enough need that MS added en-AT.

Crucially, wx doesn't know about en-AT. [It doesn't  even have LCID assigned.](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-lcid/926e694f-1797-4418-a922-343d1c5e91a6) So what happens is that `GetInfo()` searches the languages database and finds en-US as the best match and runs with it…

…until it hits the above assert.

I think it is wrong on rely on the languages database in this direction. It was meant to be used in the other direction, as API input only, to allow wx users to easily specify the language. It shouldn't be used internally for anything else.

This is something similar to a situation that led to introduction of `GetOSInfo()` in 9fc78c81679274d08ae4c956e652df7a4bfec3e5. But this situation is a third exception where GetOSInfo() and GetInfo() differ: wx doesn't know native locale, which was set using `wxLANGUAGE_DEFAULT`.

I *think* the second commit, ce2aabb, fixes it correctly: it handles the "nobody called wxSetLocale" exception as before, but otherwise behaves as `GetOSInfo`. I think this is correct because if `wSetLocale` didn't fail, then it had set both CRT and win32 thread locales to the same thing, no? And the other exception where GetOSInfo and GetInfo could differ, i.e. locale unsupported by the OS, would result in neither CRT locale nor win32 locale being changed, no? 

Also: isn't this assert in fact fundamentally wrong, because it assumes the `lcid` always corresponds to CRT locale — but the whole point of having `GetInfo()` and `GetOSInfo()` is that there may be subtle differences, and if they are, it is bound to assert when called from one of the two?

### CODE REVIEW

**Comment by vadz** [comment]
I think we really need to discuss deprecating `wxLocale` and replacing it with some `wxUILocale` (a better name would be welcome...), but I need a bit more time to think about this before I can formulate what I really mean.

This doesn't explain why did this broke the tests under AppVeyor, however...

**Comment by vslavik** [comment]
> I think we really need to discuss deprecating wxLocale and replacing it with some wxUILocale 

Hence wxTranslations, but yes, there's more to UI localization than translations.

But I'm not sure if this problem is related to that, setting both win32 and CRT locales at the same time still makes sense to me, and the assert suggests it is necessary to do so...

> This doesn't explain why did this broke the tests under AppVeyor, however…

The change uncovered a bug in `wxLocale` destructor, which didn't restore win32 side of what `Init()` to its original state. I added a fix for that in 77d0b52.

**Comment by vadz** [comment]
> But I'm not sure if this problem is related to that, setting both win32 and CRT locales at the same time still makes sense to me,

To me too, but we can't do it on all platforms because macOS simply doesn't care about C/POSIX and macOS 11 just [doesn't work](https://trac.wxwidgets.org/ticket/19023) in any locale using comma as decimal separator (also #2124).

> and the assert suggests it is necessary to do so...

We're going to have to change this. I.e. we will have to support the scenario in which the OS and CRT use different locales, just because macOS doesn't leave us any choice. So we'll have to very clearly document which functions use which locale and remove this assert.
 
> > This doesn't explain why did this broke the tests under AppVeyor, however…
> 
> The change uncovered a bug in `wxLocale` destructor, which didn't restore win32 side of what `Init()` to its original state. I added a fix for that in [77d0b52](https://github.com/wxWidgets/wxWidgets/commit/77d0b52b86c599cf66d1ad189e07edeef55caa06).

I see, thanks!

This looks like the right thing to do to me and this probably should be merged and refactored when we add `wxUILocale` or whatever it's going to be called later (`wxLocale` will either inherit from the new class or contain it).

**Comment by vslavik** [comment]
> We're going to have to change this.

I see...

> This looks like the right thing to do to me and this probably should be merged

OK, I force-pushed without the unused commit so that the branch is clean.

**Comment by vadz** [comment]
If you haven't seen it yet, I'd appreciate your thoughts about [this post](https://groups.google.com/g/wx-dev/c/a24Usdb73WM/m/dOarN7LkAAAJ)

**Pull request merged**
