### PR TITLE
Updated to Scintilla 3.7.6.

### PR DESCRIPTION
**Pull request by pkulchenko**
I've updated all the files according to the README and compiled on Windows 8.1 using gcc 5.1. The only thing I didn't do in the PR was to regenerate XCode files as was done in cb08b32f, as I'm not setup to do this.

I haven't found any issues related to wxSTC upgrade, but I did notice couple of issues that didn't exist with the previous version. First, the size of the DLL I'm building for my app increased from 8472KB to 9421KB on the current master and to 9621KB on the current master with the wxSTC upgrade. Also, I had an issue with my script hanging after exiting, but I tested on the current master branch (without the changes in this PR) and the effect is the same, so it's caused by something else. I'll try to bisect it.

### CODE REVIEW

**Comment by vadz** [comment]
Sorry, I think we should switch to using a submodule for this library too before updating it again.

@MaartenBent already did some (all?) work on this, see [this post](https://groups.google.com/d/msg/wx-dev/qBIpwMa0ZyY/bn6rg8khAAAJ) so it hopefully shouldn't be hard to finish it and I'd prefer to do this first and then update it.

In the meanwhile, the build errors in this PR CI builds may still be worth investigating (except the Cygwin one which is a problem with Cygwin installation on AppVeyor).

**Comment by pkulchenko** [comment]
> Sorry, I think we should switch to using a submodule for this library too before updating it again.
> @MaartenBent already did some (all?) work on this, see this post so it hopefully shouldn't be hard to finish it and I'd prefer to do this first and then update it.

I wish I knew this before making changes, but I'd argue that it may be worthwhile merging the changes as is, as 3.7.6 is the last feature release before Scintilla redesign for 4.x. There was a large number of changes, some of them incompatible with how things are currently done, so will require restructuring the project anyway, which would be a good time to switch to submodules (after Scintilla 4.1 version is out).

> In the meanwhile, the build errors in this PR CI builds may still be worth investigating (except the Cygwin one which is a problem with Cygwin installation on AppVeyor).

I did reviewed those and of all the failures, only `Environment: TOOLSET=cmake, GENERATOR=Visual Studio 12, SHARED=ON, CONFIGURATION=Release` seems to be the legitimate one as it fails with `error C2280: 'std::unique_ptr<const char [],std::default_delete<_Ty>>::unique_ptr<char*>(_Ptr2)' : attempting to reference a deleted function [C:\projects\wxwidgets\build_cmake\libs\stc\wxscintilla.vcxproj]`, which usually points to missing C++ support; I'll check on that.

The other AppVeyor errors don't seem to be related to the PR changes: `Environment: TOOLSET=nmake, VS=9.0, BUILD=release, ARCH=x86, wxUSE_STL=0` failed with `LINK : fatal error LNK1181: cannot open input file 'wxbase31u_net.lib'` and `Environment: TOOLSET=mingw, wxUSE_STL=0` failed with `c:/mingw/bin/../lib/gcc/mingw32/5.3.0/../../../../mingw32/bin/ld.exe: cannot find -lwxmsw31ud_core` (and bunch of other core libraries missing). I'm not sure we can make VS9-based build to work as Scintilla now requires C++11 support and VS9 doesn't have that as far as I can tell.

For Travis builds, those that enable C++11 support (`$ export wxCONFIGURE_FLAGS="--enable-cxx11 --enable-stl" $ export wxMAKEFILE_FLAGS="CXXFLAGS=-std=c++11"`) pass and those that do not, obviously fail.

Starting from 3.7.4, Scintilla requires C++11 support: `Requires a C++11 compiler. GCC 4.8 and MSVC 2015 are supported. `; in 3.7.5: `Support dropped for Microsoft Visual C++ 2013 due to increased use of C++11 features.`

Given these changes, I think it would make sense to add a check to configure that if `wxUSE_STC` is enabled, then `wxWITH_CXX=11` and `wxWITH_CXX_IS_OPTIONAL=0` are set. I'll update the pull request and will undo the changes to the bake-/makefiles, as they no longer be needed.

Assuming this works as expected, my suggestion is to postpone the conversion to submodules until Scintilla 4.1 is out and merge these changes with the current structure.

**Comment by vadz** [comment]
I don't think we can just update to a version dropping support for all non-C++11 compilers like this. We don't plan to drop support for C++98 in wx 3.2, so we'll probably have to stay with 3.7.2 for quite some time (are there any important changes in 3.7.3?).

Perhaps we could include newer versions for the build that do use C++11 in parallel... I really don't see any good solution here, but we definitely won't be changing this for 3.1.1, otherwise we'll never release it at all.

**Comment by pkulchenko** [comment]
> I don't think we can just update to a version dropping support for all non-C++11 compilers like this.

I agree; I think it was unfortunate that the requirements changed like that for Scintilla.

> We don't plan to drop support for C++98 in wx 3.2, so we'll probably have to stay with 3.7.2 for quite some time (are there any important changes in 3.7.3?).

Here is the list of relevant changes in 3.7.3:

```
Display block caret over the character at the end of a selection to be similar to other editors.
The Diff lexer recognizes deleted lines that start with "--- ".
The Lua lexer requires the first line to start with "#!" to be treated as a shebang comment, not just "#". Bug #1900.
The Matlab lexer requires block comment start and end to be alone on a line. Bug #1902.
The Python lexer supports f-strings with new styles, allows Unicode identifiers, and no longer allows @1 to be a decorator. Bug #1848.
Fix folding inconsistency when fold header added above a folded part. Avoid unnecessary unfolding when a deletion does not include a line end. Bug #1896.
Fix finalization crash on Cocoa. Bug #1909.
Fix display of autocompletion lists and calltips on GTK+ 3.22 on Wayland. Newer APIs used on GTK+ 3.22 as older APIs were deprecated.
Fix crash in accessibility code on GTK+ due to signal receipt after destruction. Bug #1907.
Make trackpad scrolling work on Wayland. Bug #1901. 
```

I can probably prepare this update if needed, as it does fix some issues on GTK and Cocoa, but not much in terms of new functionality.

> Perhaps we could include newer versions for the build that do use C++11 in parallel... I really don't see any good solution here, but we definitely won't be changing this for 3.1.1, otherwise we'll never release it at all.

I'll still push the changes for configure, as I think it will address some of the build failures and will keep the branch valid in case someone wants to test the upgrade, but I agree, that changing the requirements to C++11 is not good for a minor release.

**Comment by vadz** [comment]
In the 3.7.3 changes list, Cocoa crash fix looks important, but I don't know how critical is it in practice.

**Comment by NewPagodi** [comment]
I think the GTK+ and Cocoa changes in 3.73 were in the platform files and wouldn't be used by wxSTC.  Here are the changes from 3.72 to 3.73 for the include and src folders in the Scintilla source file archives.  (This excludes changed files in the lexer folder and the various platform folders)

```
--- include/SciLexer.h	Thu Dec 29 21:38:24 2016
+++ include/SciLexer.h	Mon Feb 20 15:25:33 2017
@@ -151,6 +151,10 @@
 #define SCE_P_STRINGEOL 13
 #define SCE_P_WORD2 14
 #define SCE_P_DECORATOR 15
+#define SCE_P_FSTRING 16
+#define SCE_P_FCHARACTER 17
+#define SCE_P_FTRIPLE 18
+#define SCE_P_FTRIPLEDOUBLE 19
 #define SCE_C_DEFAULT 0
 #define SCE_C_COMMENT 1
 #define SCE_C_COMMENTLINE 2
--- include/Scintilla.iface	Thu Dec 29 21:38:24 2016
+++ include/Scintilla.iface	Mon Feb 20 15:25:33 2017
@@ -2354,10 +2354,10 @@
 fun void ClearSelections=2571(,)
 
 # Set a simple selection
-fun int SetSelection=2572(position caret, position anchor)
+fun void SetSelection=2572(position caret, position anchor)
 
 # Add a selection
-fun int AddSelection=2573(position caret, position anchor)
+fun void AddSelection=2573(position caret, position anchor)
 
 # Drop one selection
 fun void DropSelectionN=2671(int selection,)
@@ -2914,6 +2914,10 @@
 val SCE_P_STRINGEOL=13
 val SCE_P_WORD2=14
 val SCE_P_DECORATOR=15
+val SCE_P_FSTRING=16
+val SCE_P_FCHARACTER=17
+val SCE_P_FTRIPLE=18
+val SCE_P_FTRIPLEDOUBLE=19
 # Lexical states for SCLEX_CPP, SCLEX_BULLANT, SCLEX_COBOL, SCLEX_TACL, SCLEX_TAL
 lex Cpp=SCLEX_CPP SCE_C_
 lex BullAnt=SCLEX_BULLANT SCE_C_
--- src/Document.cxx	Thu Dec 29 21:38:24 2016
+++ src/Document.cxx	Mon Feb 20 15:25:34 2017
@@ -1805,7 +1805,7 @@
 			(wordStart && IsWordStartAt(pos));
 }
 
-bool Document::HasCaseFolder(void) const {
+bool Document::HasCaseFolder() const {
 	return pcf != 0;
 }
 
--- src/Document.h	Thu Dec 29 21:38:24 2016
+++ src/Document.h	Mon Feb 20 15:25:34 2017
@@ -400,7 +400,7 @@
 	bool IsWordAt(int start, int end) const;
 
 	bool MatchesWordOptions(bool word, bool wordStart, int pos, int length) const;
-	bool HasCaseFolder(void) const;
+	bool HasCaseFolder() const;
 	void SetCaseFolder(CaseFolder *pcf_);
 	long FindText(int minPos, int maxPos, const char *search, int flags, int *length);
 	const char *SubstituteByPosition(const char *text, int *length);
--- src/Editor.cxx	Thu Dec 29 21:38:24 2016
+++ src/Editor.cxx	Mon Feb 20 15:25:34 2017
@@ -2611,10 +2611,10 @@
 				if (pdoc->ContainsLineEnd(mh.text, mh.length) && (mh.position != pdoc->LineStart(lineOfPos)))
 					endNeedShown = pdoc->LineStart(lineOfPos+1);
 			} else if (mh.modificationType & SC_MOD_BEFOREDELETE) {
-				// Extend the need shown area over any folded lines
+				// If the deletion includes any EOL then we extend the need shown area.
 				endNeedShown = mh.position + mh.length;
 				int lineLast = pdoc->LineFromPosition(mh.position+mh.length);
-				for (int line = lineOfPos; line <= lineLast; line++) {
+				for (int line = lineOfPos + 1; line <= lineLast; line++) {
 					const int lineMaxSubord = pdoc->GetLastChild(line, -1, -1);
 					if (lineLast < lineMaxSubord) {
 						lineLast = lineMaxSubord;
@@ -5500,7 +5500,7 @@
 	if (!(levelNow & SC_FOLDLEVELWHITEFLAG) && (LevelNumber(levelPrev) < LevelNumber(levelNow))) {
 		if (cs.HiddenLines()) {
 			const int parentLine = pdoc->GetFoldParent(line);
-			if (!cs.GetExpanded(parentLine) && cs.GetExpanded(line))
+			if (!cs.GetExpanded(parentLine) && cs.GetVisible(line))
 				FoldLine(parentLine, SC_FOLDACTION_EXPAND);
 		}
 	}
--- src/EditView.cxx	Thu Dec 29 21:38:24 2016
+++ src/EditView.cxx	Mon Feb 20 15:25:34 2017
@@ -1288,7 +1288,13 @@
 	// For each selection draw
 	for (size_t r = 0; (r<model.sel.Count()) || drawDrag; r++) {
 		const bool mainCaret = r == model.sel.Main();
-		const SelectionPosition posCaret = (drawDrag ? model.posDrag : model.sel.Range(r).caret);
+		SelectionPosition posCaret = (drawDrag ? model.posDrag : model.sel.Range(r).caret);
+		if (vsDraw.caretStyle == CARETSTYLE_BLOCK && !drawDrag && posCaret > model.sel.Range(r).anchor) {
+			if (posCaret.VirtualSpace() > 0)
+				posCaret.SetVirtualSpace(posCaret.VirtualSpace() - 1);
+			else
+				posCaret.SetPosition(model.pdoc->MovePositionOutsideChar(posCaret.Position()-1, -1));
+		}
 		const int offset = posCaret.Position() - posLineStart;
 		const XYPOSITION spaceWidth = vsDraw.styles[ll->EndLineStyle()].spaceWidth;
 		const XYPOSITION virtualOffset = posCaret.VirtualSpace() * spaceWidth;
@@ -2085,7 +2091,7 @@
 }
 
 void EditView::FillLineRemainder(Surface *surface, const EditModel &model, const ViewStyle &vsDraw, const LineLayout *ll,
-	int line, PRectangle rcArea, int subLine) {
+	int line, PRectangle rcArea, int subLine) const {
 		int eolInSelection = 0;
 		int alpha = SC_ALPHA_NOALPHA;
 		if (!hideSelection) {
--- src/EditView.h	Thu Dec 29 21:38:24 2016
+++ src/EditView.h	Mon Feb 20 15:25:34 2017
@@ -143,7 +143,7 @@
 	void PaintText(Surface *surfaceWindow, const EditModel &model, PRectangle rcArea, PRectangle rcClient,
 		const ViewStyle &vsDraw);
 	void FillLineRemainder(Surface *surface, const EditModel &model, const ViewStyle &vsDraw, const LineLayout *ll,
-		int line, PRectangle rcArea, int subLine);
+		int line, PRectangle rcArea, int subLine) const;
 	long FormatRange(bool draw, Sci_RangeToFormat *pfr, Surface *surface, Surface *surfaceMeasure,
 		const EditModel &model, const ViewStyle &vs);
 };
--- src/ScintillaBase.cxx	Thu Dec 29 21:38:24 2016
+++ src/ScintillaBase.cxx	Mon Feb 20 15:25:35 2017
@@ -202,7 +202,7 @@
 }
 
 void ScintillaBase::AutoCompleteDoubleClick(void *p) {
-	ScintillaBase *sci = reinterpret_cast<ScintillaBase *>(p);
+	ScintillaBase *sci = static_cast<ScintillaBase *>(p);
 	sci->AutoCompleteCompleted(0, SC_AC_DOUBLECLICK);
 }
 
--- src/XPM.cxx	Thu Dec 29 21:38:24 2016
+++ src/XPM.cxx	Mon Feb 20 15:25:35 2017
@@ -46,7 +46,7 @@
 	return colourCodeTable[ch];
 }
 
-void XPM::FillRun(Surface *surface, int code, int startX, int y, int x) {
+void XPM::FillRun(Surface *surface, int code, int startX, int y, int x) const {
 	if ((code != codeTransparent) && (startX != x)) {
 		PRectangle rc = PRectangle::FromInts(startX, y, x, y + 1);
 		surface->FillRectangle(rc, ColourFromCode(code));
--- src/XPM.h	Thu Dec 29 21:38:24 2016
+++ src/XPM.h	Mon Feb 20 15:25:35 2017
@@ -23,7 +23,7 @@
 	ColourDesired colourCodeTable[256];
 	char codeTransparent;
 	ColourDesired ColourFromCode(int ch) const;
-	void FillRun(Surface *surface, int code, int startX, int y, int x);
+	void FillRun(Surface *surface, int code, int startX, int y, int x) const;
 public:
 	explicit XPM(const char *textForm);
 	explicit XPM(const char *const *linesForm);
```

Sorry if this isn't the most helpful format.

**Comment by pkulchenko** [comment]
These changes don't look too critical to upgrade.

**Comment by pkulchenko** [comment]
Just a brief update on the size increase I mentioned earlier. I think it's related more to the fact that I moved to gcc 5.1 from gcc 4.8.1, than to the changes in wxwidgets. I remember I observed a similar jump with the libraries I built using the same version and the two compilers.

**Comment by pkulchenko** [comment]
@vadz, I'd like to come back to this, as there is a [long term branch of Scintilla](https://scintilla.sourceforge.io/LongTermDownload.html), that doesn't have C++14+ dependency, but still supports "old" compiles, like GCC 4.8, MSVC 2015, and Clang 3.4. I think it may be worthwhile to upgrade to support its requirements, as it's going to stay more or less in sync with Scintilla upgrades. Here is its history: https://scintilla.sourceforge.io/ScintillaHistory.html.

The other option is to stay forever on 3.7.2, but it's not really a viable option.

**Comment by vadz** [comment]
Sorry, I don't know what are we supposed to do. This long term branch still requires MSVS 2015 under MSW which is vastly different from our current requirements which are, admittedly, very lax, but I still know of plenty of people stuck at MSVS 2010 or thereabouts, so I don't think we're going to require 2015 in 3.2.

Alternatively, we could use modern Scintilla but disable it if not building in C++14 mode, but I'm not really sure if it's such a great idea neither.

The best would arguably be to allow using "system" Scintilla libraries, i.e. people who need latest version would need to build it yourself and let wx know about it, while the old version would still be available out of the box. But this probably would require quite some work.

**Comment by pkulchenko** [comment]
Another option is to stick with the long-term branch, but if the current compiler doesn't support C++11, then checkout the current version from the scintilla submodule (since it's going to be frozen at 3.7.2 for those anyway). This way we provide a smooth transition for those users who have compilers with C++11 support and fallback for those who don't without restricting everyone to the "frozen" scintilla version. This will only require a couple of tweaks to the configure script, but will allow for continuous updates based on longterm branch support.

**Comment by MaartenBent** [comment]
I don't think configure should modify the source tree. This also won't work with downloaded packages.

What about adding a second scintilla directory (`scintilla4`) to `src/stc` with the latest scintilla version. Based on compiler support and user preference one of the two will be used. This will increase the size a bit (especially when using a submodule) but it allows to have the latest version, while still supporting old compilers.

**Comment by pkulchenko** [comment]
> I thought about the scintilla4 idea too but I'm not sure how workable is it. In principle, I don't have any objections to this, i.e. it would be fine to have some wxSTC methods only available when using the new version as long as the existing methods continue to work in any case.

I think the compatibility is largely to be preserved (as the changes are mostly in adding new capabilities to the existing methods), but I recommend using the longterm branch instead of scintilla4 for two main reasons:

1. The gap between compiler requirements for the current version and scintilla4 is too large and those using anything between compilers with C++11 and C++17 (required for scintilla4) will be stuck with the current (frozen) version.
2. The longterm branch includes scintillua component that supports dynamic lexers. It won't be available in scintilla4 because of those compiler requirements and it was one of the reasons behind maintaining the longterm branch.

I can take a stab at moving the current /src/stc folder to /src/stc-frozen and getting the new one associated with /src/stc. I'll need some help with `configure` updates to switch to /src/stc-frozen if the compiler support is not there.

@vadz, was the submodule work discussed in https://groups.google.com/d/msg/wx-dev/qBIpwMa0ZyY/bn6rg8khAAAJ ever finished? It's not going to work with what we are discussing, as it's using an unofficial Scintilla mirror that doesn't include the longterm branch. It's available from sf, which is the original scintilla repository: https://sourceforge.net/p/scintilla/code/ci/LongTerm3/tree/

**Comment by MaartenBent** [comment]
The mirror I used for subversion also has the LTS releases, at least the tags are there: https://github.com/mirror/scintilla/releases/tag/rel-3-10-1
In my opinion the new scintilla should also be added as a submodule (when possible).

The current version was never replaced with a submodule and I think it is not worth doing, as it will not be updated anymore (or only to 3.7.3).

**Comment by pkulchenko** [comment]
> The mirror I used for submodules also has the LTS releases, at least the tags are there: https://github.com/mirror/scintilla/releases/tag/rel-3-10-1

Interesting; the tag is there, but there is no other branch than `master` (or at least I don't see how to switch to it); not sure where in the history the commit points to.

> In my opinion the new scintilla should also be added as a submodule (when possible).
> The current version was never replaced with a submodule and I think it is not worth doing, as it will not be updated anymore (or only to 3.7.3).

I agree with both of these points. I don't think it's worth upgrading to 3.7.3, as the changes are minor.

I'll take a stab at upgrading to the longterm3 branch using the submodule referencing `tag/rel-3-10-1` and see what issues I run into.

**Comment by mtangoo** [comment]
Hi,
late to the party but I wanted to table one more option. Scintilla4 can start its life as wxStyledTextCtrl library independent of wxWidgets for now but officially supported, and hence under wxWidgets org on github. 

That way developers will have more freedom. When time comes to Upgrade it will simply be merged back to wxWidgets official and not much will change. At that moment, old scintilla will be refactored into a separate wxCode library for those who will wish to support it (via PR of course)

My 2 cents!

**Pull request closed without merging**
