### PR TITLE
Support bitmaps in sizers

### PR DESCRIPTION
**Pull request by catalinr**
_[This is not supposed to be merged (well, not yet), but making the PR might trigger some testing and receiving some needed help.]_

The goal here was to allow `wxSizer`s to contain `wxBitmap`s, so that the latter can be easily embedded into layouts and painted automatically, without any user code.
A `wxSizerItem` containing a `wxBitmap` will behave like a `spacer` when no painting will be performed.
And it works surprisingly well so far. The only problem is when the window is resized after it has been scrolled. For the life of me I can't understand what is different after a resize of a scrolled window. Any help with this would be great.

Another question would be, what is the best way to trigger the painting? My test class in the minimal sample is working, and something like that could be added to wxW, but there should probably be a more user-friendly way to do it, and not restricted to inheriting from `wxScrolled<>`.

Other considerents:
- A `wxSizer[Item]` will take a `wxSharedPtr<wxBitmap>`. This is inconsistent with other overloads taking `wxWindow *` and `wxSizer *`, but those are managed by wxW, while the bitmap pointers would be in the user's hands, so why not make them use more modern technique. Another reason in favor of the shared pointer is that the same bitmap can be reused in multiple sizers.
- I thought about having implementations of `wxSizer` that use either `wxBitmap` or `wxWindow`. It was easier like this, and it might not be a bad thing in the end, as excluding each other would only help with painting.
- Testing this is really simple: just build this branch, and run `minimal` sample.

### CODE REVIEW

**Comment by vadz** [comment]
Sorry, but I really don't understand what is the benefit compared to just using `wxStaticBitmap` justifying doing this.

**Comment by catalinr** [comment]
Oh, the idea was to have an easy way of showing images without actually using a wxWindow for each one of them -- see the DWM issues with a scrolled window and a long list of children. The initial idea was to have some bitmap-only sizer, but it was not easy to separate the useful logic from wxSizer[Item] and reuse it later...

**Comment by catalinr** [comment]
p.s. Another benefit of this is the automatic stretching / resizing of an image (which is not a feature of `wxStaticBitmap` AFAIR). That might not sound very appealing, considering visible pixels, but for example in this way there can be a monochrome area covered by a stretched bitmap of only 1 pixel.
..And again, reusing the same `wxBitmap`, i.e. one normal painting and another as a thumbnail.

**Comment by vadz** [comment]
Sorry, I'm really not convinced by this. IMO a situation in which you need to have many bitmaps, but not any other controls is so specific that we really don't need to add a special API just to support this.

I'd suggest solving this by implementing the long-standing proposal of allowing to assign names to sizers and spaces (and not only windows) in XRC/API, then you could implement this entirely in your own code by using named spacers.

But unless someone else or even several someone elses enthusiastically back this addition, I'm not going to apply it because it just doesn't seem worth it, sorry.

**Comment by catalinr** [comment]
> I'd suggest solving this by implementing the long-standing proposal of allowing to assign names to sizers and spaces (and not only windows) in XRC/API, then you could implement this entirely in your own code by using named spacers.

Sorry, I know nothing about that proposal. Where can I read about it? Using a sort of "payload" for spacers did cross my mind...

> I'm not going to apply it because it just doesn't seem worth it, sorry.

That is not all that big of a problem.
Reusing the many sizer options and already implemented logic was very tempting for applying them to images. But if there is a better way then all the better.

One thing would still be useful: some feedback from others that have run the minimal sample in this branch, whether the actual functionality is useful or not, regardless of the way it would be implemented.

**Comment by vadz** [comment]
I couldn't find any ticket about this (which doesn't mean there is none because the search terms "name" and "sizer" are so generic that it's difficult to search using them), but it was definitely brought up a couple of times in the past on the mailing list. The basic idea was to allow finding sizers by name in the same way as you can find windows by name and perhaps it could be combined/extended with finding sizer items, including spacers, by name.

**Comment by TcT2k** [comment]
> p.s. Another benefit of this is the automatic stretching / resizing of an image (which is not a feature of `wxStaticBitmap` AFAIR). 

Just wanted to add that `wxStaticBitmap` can scale the bitmap on some platforms (and `wxGenericStaticBitmap` can be used elsewhere) see [wxStaticBitmap::SetScaleMode()](https://docs.wxwidgets.org/trunk/classwx_static_bitmap.html#ab8a6f1057e0c15549c1c32bc533bcdb3)

**Comment by vadz** [comment]
As previously mentioned, I don't think it's worth adding this, so I'll close it. Any PRs adding sizer/spacer names as discussed above would still be welcome, of course. TIA!

**Pull request closed without merging**
