### PR TITLE
 Fix ZIP64 creation with individual files larger 4GB and new archive sample

### PR DESCRIPTION
**Pull request by TcT2k**
If single files larger than 4GB where added the recorded file sizes
in the local file header where not updated correctly. Additionally
recorded file sizes in the central directory where in the wrong order
making it impossible to extract.

To enable adding files with unknown size which might be larger than 4GB
the new method wxZipOutputStream::SetFormat() is added.

Additionally a check has been added in case a file larger 4GB has been
written without ZIP64 info.

I've also created a new sample _archive_ to show using _wxArchiveStreams_

Additionally potential issue when reading ZIP64 files is fixed.

### CODE REVIEW

**Comment by MaartenBent** [comment]
The archive sample fails to build (with `makefile.gcc`) because it tries to link with `core` instead of `base`.

**Comment by TcT2k** [comment]
@MaartenBent thanks for testing, I've corrected the linked libs

**Comment by MaartenBent** [comment]
There are still some link errors, but a lot less. I think you need to use
```xml
template="wx_sample_console" template_append="wx_append_base"
```
like the `console` and `secretstore` samples.


(`secretstore` does not use `wx_append_base`, but all other console samples do. Is this an errror @vadz ?)

**Comment by TcT2k** [comment]
Changed the bkl to use `wx_sample_console` template

**Comment by MaartenBent** [comment]
Yes, now it works 👍.
It has the following build warning:
```bash
g++ -c -o gcc_mswu64\archive_archive.o  -O2 -mthreads  -DHAVE_W32API_H -D__WXMSW__   -DNDEBUG    -D_UNICODE -I.\..\..\lib\gcc_lib64\mswu -I.\..\..\include  -W -Wall -I.  -DwxUSE_GUI=0   -Wno-ctor-dtor-privacy -m64 -std=c++11 -MTgcc_mswu64\archive_archive.o -MFgcc_mswu64\archive_archive.o.d -MD -MP archive.cpp
archive.cpp:77:1: warning: missing initializer for member 'ArchiveApp::ArchiveCommandDesc::id' [-Wmissing-field-initializers]
 };
 ^
archive.cpp:77:1: warning: missing initializer for member 'ArchiveApp::ArchiveCommandDesc::desc' [-Wmissing-field-initializers]
```

Creating a zip with a 6gb file using the sample correctly enables zip64 and 7zip does not complain.

When I use `--force-zip64` option and create a zip file of a small file (110KB), zip64 is not enabled. 7zip shows the same archive info with or without the option (both version 20).
It seems `z64Required` results in false in `wxZipEntry::WriteCentral`, and `wxZipEndRec::Write` also does not go into zip64 specific code. Is this intended?

**Comment by TcT2k** [comment]
@MaartenBent 
I've fixed the warning in the sample.

Regarding the info 7-zip shows: it uses version to extract from the central directory but other infos from local. But just to be sure I've changed the version in the central directory too. Which I think shouldn't matter much, but just seems right. `--force-zip64` does not change anything in the central directory but only in the local file info.

**Comment by vadz** [comment]
I'm a bit afraid of adding a new sample, which might fail to compile in some untested build configuration, just before 3.1.1, but OTOH I definitely do want to fix ZIP64 support before it. So I'd rather merge the first 2 commits right now, but leave the sample until after 3.1.1, or do you think it's absolutely and totally safe to merge the commit adding the sample right now as well?

**Comment by TcT2k** [comment]
I wouldn't expect any issues with the sample. but I think it's reasonable to postpone it to after 3.1.1 and just include the fixes just to be on the safe side.

**Comment by vadz** [comment]
Thanks, I'm merging the first 2 commits with some minor fixes to the documentation (please review them if possible to check if I misunderstood anything) and will merge the commit adding the sample after 3.1.1.

**Comment by TcT2k** [comment]
@vadz your documentation changes in a3673be1559a60870379f9c87a757ae698f6aa2f seem good too me.

**Comment by TcT2k** [comment]
@vadz On issue in a3673be1559a60870379f9c87a757ae698f6aa2f is an open comment which would probably fail with doxygen

**Comment by vadz** [comment]
Oops, thanks for noticing this, will fix (no idea how did it happen...).

**Comment by vadz** [comment]
I've added the commit adding the sample too now, so there should be nothing left here. Thanks again!

**Pull request closed without merging**
