### PR TITLE
Assorted macOS fixes to be applied before 3.1.3

### PR DESCRIPTION
**Pull request by vadz**
Nothing here is perfect, but still better than nothing.

### CODE REVIEW

**Review by csomor — COMMENTED** [review]
While the popup is not as visible anymore, it still is very much in function, even worse, without clicking on the option button people may not be aware why the can only select certain types. If there is a wildcard option for any files, then the behavior is fine, but if not, it only shows what's allowed in the current selection of the invisible (!) popup

**Comment by vadz** [comment]
I don't really see how is it different/worse than under the other platforms and I think it's reasonable to expect people to understand that only some files can be selected because the program requires only the files of these types... FWIW I hate the "Options" button too, but there is nothing we can do about it.

Anyhow, if you're really against it, I can drop this commit, of course, but IMHO this is still better than the current state in which filters are just not taken into account at all.

**Comment by csomor** [comment]
I try to explain where I see the difference: If a graphics program could open eg jpeg or png files, then under other platforms the type popup is at least visible, and either pngs or jpegs are selectable, depending on the visible selection of the popup. Under macOS - with the current implementation - both pngs and jpegs are selectable, with the suggested forced popup change, either pngs OR jpegs are selectable - and unless when clicking on 'Other' the user would not know why.

**Comment by vadz** [comment]
I think the graphics program should always default to "All images" wildcard. If the user changes the wildcard to something more restrictive, presumably they know what they're doing and would know to change it back.

Anyhow, I don't what to waste your time on this, it's not that important (compared to the overlay problem, for example...), so I'll revert this commit, I just regret that you had never reacted in the [ticket discussion](http://trac.wxwidgets.org/ticket/12429) as I could have avoided making it in the first place.

**Comment by csomor** [comment]
actually I wrote more or less exactly that 4 months ago in the ticket, but if apps tend to use the wildcard, then this change should not be a problem either

I'm fine with all the other changes anyway

**Comment by vadz** [comment]
Sorry, I misunderstood you then because I read that Trac answer as being much more ambivalent.

Anyhow, I'm merging this without that commit, but `wxFileDialog` seems broken to me: even for the dialogs that don't use "All files" wildcard, as the multi-selection dialog in the sample, it still allows to select any files. I.e. you don't ever see any files greyed out at all. This looks like just a bug to me, but I'm not even sure any more. All I can say is that with `wx_osx_openfiledialog_always_show_types=1` only the specified files can be selected, even though in practice it will still be all the files in 99% of cases, as the programs almost invariably include this catch-all filter.

**Comment by vadz** [comment]
Merged as 8b95467256689eaeb8e9fb3b91be951986c4a784, fa3c0b1808257db880996b68a589dc1e6eafd2fa and 235e61c311ee1cc3c74a637984ca40b4ed773ae2

**Comment by csomor** [comment]
Strange. I'm not sure I understand this correctly: In the dialogs sample, when changing the filter in the single file selection to
`"C++ Source (*.cpp)|*.cpp|C++ Header (*.h)|*.h|"`
then only these can be selected.
The FilesOpen method resolves to a wildcard filter in my version, if I change this to the same filter as above, only the two types can be selected.

**Comment by csomor** [comment]
I've spend considerable time trying to fix overlay btw. but I haven't found an angle yet.

**Comment by vadz** [comment]
> Strange. I'm not sure I understand this correctly: In the dialogs sample, when changing the filter in the single file selection to
> `"C++ Source (*.cpp)|*.cpp|C++ Header (*.h)|*.h|"`

Sorry but how do you do this without the filter being shown? Just to be clear, I'm speaking of the default behaviour, for me the system options might just as well not exist.

> then only these can be selected.

Yes, I see it _if_ I force showing the type selector. But not without it.

> I've spend considerable time trying to fix overlay btw. but I haven't found an angle yet.

Thanks for looking at this! I could only find examples of overlay-like drawing using layers, which is why I thought that perhaps we need to change it to use that. But I really have no idea about how this stuff was supposed to work in the first place, let alone why did it stop working.

**Comment by csomor** [comment]
Sorry I meant changing the filter in the source code, so that there's no wildcard, not changing the selection. The filter is processed when no popup is shown, but in a way that all extensions are added and then passed as NSArray of extensions to `setAllowedFileTypes`: 

```
(lldb) po types
<__NSArrayM 0x608000049000>(
cpp,
h
)

```

**Comment by vadz** [comment]
Oops, sorry, I didn't notice that all dialogs in the sample did have the "*" filter (I thought that one of them didn't, for some reason). Still, in practice, this is always going to be the case, so you could just as well say that filters are completely ignored under Mac.

Again, I don't want to waste too much time on this, but I think that perhaps using all the types _except_ for "*" by default would be more useful. Of course, we would still need to show the file type selector in this case, to allow the user to enable "*" if they really need it.

I wonder how do the native Mac applications deal with this. Do they really just always show all the files?

**Pull request closed without merging**
