### PR TITLE
Improve enter handling in both wxTextCtrl and wxComboBox on macOS

### PR DESCRIPTION
**Pull request by obfuscated**
This pull request is an attempt to fix the problems depicted in https://trac.wxwidgets.org/ticket/18273
The issue that is still opened, but has worse description is here: https://trac.wxwidgets.org/ticket/15680

I've also implemented some useful key shortcuts for wxComboBox which were missing (ctrl-a, ctrl-c/x/v).

The last commit is just temporary way to experiment with the modified text and combo controls. It must not be pushed.

There is a lot of code duplication, I'd be happy if someone can suggest where to place it, so it could be common for both wxTextCtrl and wxComboBox.

### CODE REVIEW

**Comment by vadz** [comment]
@csomor Could you please have a look at these changes and say whether you think this is the right thing to do? TIA!

**Comment by csomor** [comment]
ok, I'll try to find some time over the weekend

**Comment by obfuscated** [comment]
@csomor Any progress with the review?

**Comment by csomor** [comment]
no, unfortunately not yet, but I hope the next weekend will be less busy

**Comment by obfuscated** [comment]
@csomor  Ping?

**Comment by csomor** [comment]
Could you please explain, why the change on textctrl is needed,  what bug does it solve and why the else must be added. I’ve compared the implementation with gtk and x11 and it seems to follow the same path and I don’t want to have a different sequence of events and behaviors. Thanks.

**Comment by obfuscated** [comment]
If you're talking about bedd435 then see https://trac.wxwidgets.org/ticket/18273
This commit fixes enter handling for the second text ctrl in the repro. The repro is provided in the last commit. If you revert the commit pressing enter while the focus is on the second control would close the test dialog. With the commit it won't.

This is what I expect to happen after reading the documentation of wxTE_PROCESS_ENTER.

**Comment by csomor** [comment]
Yes, that's what I meant, thanks, the thing is that since wxEVT_TEXT_ENTER is not handled, it does not return, and falls through, IMHO the code for gtk1 behaves exactly the same, triggering the default widget (gtk1/textctrl.cpp line 980), did you have the time to test how MSW behaves ?

**Comment by obfuscated** [comment]
Ticket https://trac.wxwidgets.org/ticket/18273 describes the behaviour before the patch on msw, gtk2 and macos, see the description. To me the gtk2 behaviour looks the most correct, so this is what I'm trying to achieve with this change. The last comment in the ticket by @vadz hints that we have to have the same behaviour everywhere, but doesn't tell if the current msw one is correct or not.

@vadz What do you think? Is msw correct?

**Comment by csomor** [comment]
Thanks, sorry, I didn't read this properly. Exactly, we must have the same everywhere, and when in doubt usually we model after msw, because most apps start there and might be dependent on these details. So I'll leave this out at the moment and concentrate on the combobox

**Comment by vadz** [comment]
I've updated [the ticket](https://trac.wxwidgets.org/ticket/18273) to explain how I think things should behave. In particular, `wxComboBox` does _not_ behave correctly in wxMSW right now, but I'll try to change this soon.

**Comment by csomor** [comment]
ok, I've cherry-picked the combobox changes and applied a follow-up change according to the desired behaviour. Thanks a lot for your efforts :-)

**Pull request closed without merging**
