### PR TITLE
Fix mouse Aux2 not properly handled on msw

### PR DESCRIPTION
**Pull request by Trylz**
Fix the mouse Aux2 not properly handled. Currently a bitwise AND is applied to the message wParam to determine if the current event is an Aux2 event. But this is only valid when the button is pressed.
https://msdn.microsoft.com/en-us/library/windows/desktop/gg153548(v=vs.85).aspx

### CODE REVIEW

**Comment by MaartenBent** [comment]
Thanks. I can confirm this fixes click events with aux2.
In the text sample, with mouse logging enabled:

Without fix:
```
12:25:16: Aux2 mouse button clicked at (97, 187) at position 354 [Flags: ----X----]
12:25:17: Aux1 mouse button released at (97, 187) at position 354 [Flags: ---------]
12:25:17: Aux1 mouse button clicked at (97, 183) at position 354 [Flags: ---x-----]
12:25:17: Aux1 mouse button released at (98, 166) at position 318 [Flags: ---------]
```
With fix:
```
12:24:51: Aux2 mouse button clicked at (60, 191) at position 346 [Flags: ----X----]
12:24:51: Aux2 mouse button released at (62, 188) at position 347 [Flags: ---------]
12:24:51: Aux1 mouse button clicked at (62, 188) at position 347 [Flags: ---x-----]
12:24:52: Aux1 mouse button released at (62, 188) at position 347 [Flags: ---------]
```

This might also be useful for 3.0 branch.

**Comment by vadz** [comment]
Thanks, but a couple of comments/questions:

1. There is a very similar use of `MK_XBUTTONn` in `InitMouseEvent()` above, shouldn't it be corrected too? I don't have a mouse with aux button (can this be emulated somehow?) to test it, but it would be nice if someone could please check that the state of "down" flags for aux button events is consistent with the normal ones.
1. The CI failure is real, MinGW headers don't define `GET_XBUTTON_WPARAM()`. We should either do it ourselves or use `HIWORD()` directly (as this is what it is is, in fact).
1. This is not really a problem, as I can just cherry-pick the relevant commit, but something strange seems to have happened with your branch, you shouldn't have the 2 merges in it.

Could you please try to fix this? TIA!

**Comment by Trylz** [comment]
1) The InitMouseEvent  case seems valid since the button is down.  
For the consistency of  the "down" flags i will check too.

2) Will do. But i don't have a MinGW environment to test :(

3) Will do

**Comment by vadz** [comment]
Thanks for checking (1) and fixing (2)! I'll merge this in soon.

**Pull request closed without merging**
