### PR TITLE
CMake build fixes and improvements

### PR DESCRIPTION
**Pull request by MaartenBent**
Here are some fixes and improvements for the CMake build system.
I tested them with Visual Studio 2017, shared and static libraries.

@vadz the fix for the help sample should also be applied to its `Makefile.in` (you accidentally re-added some files in 5d134711). Could you do this (as it requires rebaking)?

@TcT2k can you have a look?

Thanks

### CODE REVIEW

**Comment by vadz** [comment]
Thanks, I've fixed the problem with the help file in 6bd8cb964bd625d7f974621cc9883ba52b58600a.

I'll let Tobias review this otherwise.

**Review by TcT2k — APPROVED** [review]
If only these 3 files are used is definitely makes sense. I just used ExternalProject because I wasn't sure and wanted to use third party CMakeLists.txt where possible

**Review by TcT2k — COMMENTED** [review]
Is it really necesarry to copy the data files?
Shouldn't the tests run with the working directory in the tests folder so they can pick up these files?

**Review by TcT2k — APPROVED** [review]

**Comment by TcT2k** [comment]
First of all I'm glad to see improvements to CMake apart from my work and @vadz contributions and I hope that the overall structure was structured to be easily understandable.

I've not tested your changes but they all seem reasonable to me looking at the code.
But please see my comment about ada7cea (the tests) as I'm not sure the data files need to be copied if the working directory is correct.

**Comment by MaartenBent** [comment]
The test data files do not need to be copied, I can also set the working directory to `${wxSOURCE_DIR}/tests`. When running the executable directly, they have to be started from that directory as well.

I've also updated cotire.

**Review by TcT2k — APPROVED** [review]
Looks good to me

**Pull request merged**
