### PR TITLE
Change default GTK version for configure from 2 to 3

### PR DESCRIPTION
**Pull request by paulcor**

### CODE REVIEW

**Comment by MaartenBent** [comment]
Maybe do the same for CMake?
https://github.com/wxWidgets/wxWidgets/blob/master/build/cmake/toolkit.cmake#L30

**Comment by vadz** [comment]
`.travis.yml` also needs to be updated to use `wxGTK_VERSION=2` for some build (maybe the one under Ubuntu Precise, which is the oldest?) and removing `wxGTK_VERSION=3` which is useless now.

**Comment by paulcor** [comment]
> `.travis.yml` also needs to be updated to use `wxGTK_VERSION=2` for some build (maybe the one under Ubuntu Precise, which is the oldest?) and removing `wxGTK_VERSION=3` which is useless now.

I think it might be better if they all used `wxGTK_VERSION` to make it explicit which one they are supposed to be using.

**Comment by vadz** [comment]
Why not, we don't change default GTK version often enough for this to be a problem.

BTW, please rebase on master before changing this file as otherwise you'll have conflicts for all the changes as I've added names to the matrix elements there.

**Pull request closed without merging**
