### PR TITLE
Improve code examples in wxDataViewModel documentation

### PR DESCRIPTION
**Pull request by PBfordev**
Fix variable name for the model.

Make the code using wxObjectDataPtr have the same flow as the
code using a raw pointer.

Format the code to be in accordance with the official guidelines.

Closes #18924.

### CODE REVIEW

**Comment by vadz** [comment]
Thanks for fixing this!

**Comment by PBfordev** [comment]
This PR somewhat stays open despite the commits having been merged, closing.

**Comment by PBfordev** [comment]
This PR somewhat stayed open despite the commits having been merged, closing.

**Comment by vadz** [comment]
Oops, this is because I've cherry-picked the commit instead of merging it and forgot to close it by adding the corresponding `Closes https://...` line to the commit message, sorry (and thanks for closing).

**Pull request closed without merging**
