### PR TITLE
Random crash fix

### PR DESCRIPTION
**Pull request by warniaha**
Fix random crash between window destruction and calling class destructor

### CODE REVIEW

**Comment by vadz** [comment]
Please correct me if I'm wrong, but there is nothing random here, is there? If `UnInit()` is called twice, it crashes -- right? Fixing this is, of course, a good idea, although I could also see adding an assert (or `wxCHECK` to be precise) if we believe that this is an error in the code.

OTOH calling `UnInit()` from `wxEVT_DESTROY` would seem to be a new feature, allowing to not call it explicitly from the user code. This is probably a good idea as well, but if we do this, it should be documented and `UnInit()` called removed from aui sample.

**Comment by vadz** [comment]
Sorry, we need to understand what's going on here better than that. Before your changes, there were no calls to `UnInit()` in wx code itself, so it couldn't be called twice (because it couldn't be called even once!) from there and had to be called from your own code. Which means that either there is a bug in your code (which should be fixed in it and, maybe, made easier to debug by adding an assert to `UnInit()`) or there is some _other_ bug in wxWidgets leading to the code which calls `UnInit()` to be called twice. In the latter case we really must find and fix that bug, instead of just applying this change.

And, almost independently of this, there is the second change, with calling `UnInit()` automatically. I'm not necessarily against it but, first, it's a different thing and so should be done in a separate commit and, second, this requires documentation and sample updates.

Please let's deal with the first problem first. Can you reproduce it in the aui sample under Mac? If not, can you please debug it in your program and check how does `UnInit()` end up being called twice? TIA!

For now I'm afraid I can't apply this PR, we need more information about what's going on first.

**Comment by warniaha** [comment]
Its not a bug in calling UnInit.  The bug is that one of the messages processed after window destruction, is attempting to utilize the window after its been destroyed.  The object is no longer valid.  Mac doesn’t perform error checking within the system APIs and return an error like Windows does.  Mac just crashes when attempting to utilize resources that have already disappeared.

 

The fix is to remove the event handler at an earlier time than the invocation of the class destructor.

 

I have no problem updating the documentation and adding the assertion you suggested, but I do need to understand where to update the docs.  I can’t find where to change it.

**Comment by vadz** [comment]
> Its not a bug in calling UnInit. The bug is that one of the messages processed after window destruction, is attempting to utilize the window after its been destroyed. The object is no longer valid. Mac doesn’t perform error checking within the system APIs and return an error like Windows does. Mac just crashes when attempting to utilize resources that have already disappeared.

But it's _this_ bug that needs to be fixed. Unfortunately I still have no idea what it is. As usual, the best would be to have a simple way to reproduce it. If it can't be found, we need at least the backtrace from your application to have a fighting chance to understand why is the window used after being destroyed.

> The fix is to remove the event handler at an earlier time than the invocation of the class destructor.

No, this is not a fix at all but at most a workaround. The event handler should never be called after the destructor.

> I do need to understand where to update the docs. I can’t find where to change it.

Reference documentation is under `interface/wx`, and there are also overviews and other higher level pages under `docs/doxygen`.

**Comment by warniaha** [comment]
I think you are confusing the order of whats happening.

1. Events are added to the queue.  The UI thread continues executing without waiting
2. The window is closed, the handler is now referencing code that executes against a closed window
3. The queued events are processed (crash occurs here)
4. the class destructor removes the event handler

With the fix, the queued events in step 3 never reference the code that uses the closed window and ultimately get ignored.

I didn't save the stack trace since I knew how to solve it.  I'll need to go back and attempt to reproduce it again.  It may take me some time.

I'll update the docs as well

**Comment by vadz** [comment]
I think I understand relatively well the order of things that happen, but it's true that I don't understand at all the scenario you're describing: when you say "the window is closed" in (2), do you mean that it is destroyed? Because if you don't, then I don't understand the real reason for the crash in (3): as long as the window object exists, it should be safe to process the events. If you do, then I don't understand how can it be destroyed once again in (4).

Could you please explain more precisely what happens at each step? Notably, which window are the events queued for? What is meant exactly by closing the window (and is it the same one or different)? Why exactly does it crash? Whose class dtor removes the event handler? I.e. something like this:

1. Event `wxEVT_XXX` is posted to the window `w` of class (derived from) `wxFrame`.
2. `w->Destroy()` is called.
3. `wxFrame` is destroyed.
4. `wxFrame::OnXXX()` is called and crashes because the frame had been already destroyed.

(I don't think this can actually happen, because any pending events are supposed to be dispatched before (3), not after, this is just an example of a detailed description of the problem I'd like to have).

Thanks again!

**Pull request closed without merging**
