### PR TITLE
Restore correct translation language lookup (3.2)

### PR DESCRIPTION
**Pull request by vslavik**
As requested, here's #24297 backported to the 3.2 branch.

The one non-trivially different commit is e1b644341dc2347786e3519b3aa3c6c4fea0bc43 — I hope I got the ABI compatibility things mostly right.

### CODE REVIEW

**Comment by vslavik** [comment]
> The one non-trivially different commit is [e1b6443](https://github.com/wxWidgets/wxWidgets/commit/e1b644341dc2347786e3519b3aa3c6c4fea0bc43) — I hope I got the ABI compatibility things mostly right.

Replaced by a740a012 after force-pushing fix to avoid C++11 syntax.

**Review by vadz — APPROVED** [review]
Everything looks good to me, thanks for taking time to do this!

Would you have a brief description of this change for the changelog (i.e. `docs/changes.txt`) by chance? I'm not really sure how to summarize this myself.

**Comment by vslavik** [comment]
> Would you have a brief description of this change for the changelog (i.e. `docs/changes.txt`) by chance?

How about b2c1c54f ?

**Comment by vadz** [comment]
This is part of #24706 now, so closing. Thanks again!

**Pull request closed without merging**
