### PR TITLE
MediaCtrl SetPosition does not update image.

### PR DESCRIPTION
**Pull request by ashishmore**
show image when mediactrl is paused

### CODE REVIEW

**Comment by vadz** [comment]
This really merits some comment, the change is quite surprising at a first glance: why do we need to rewind and then step forward like this? Could you please explain it (maybe by adding a comment explaining this in the sources)?

Also, please use some meaningful commit message and check the indentation in the new lines you've added, as it seems to be inconsistent with the rest of the file.

**Comment by ashishmore** [comment]
I have added some comments to the changes, explaining why I have to go to a previous position and then step forward.

**Comment by vadz** [comment]
Thanks for the update, I'd like to wait a little bit more just to see if anybody with any experience of working with `wxMediaCtrl` and the underlying MSW interfaces might chime in.

If there are no objections relatively soon, I'm going to merge this. Thanks again!

**Comment by ashishmore** [comment]
If you try to set the position of the video to a particular time, it does
not refresh the image.
Pausing works, and the code modification does not affect the pause
functionality.

-Ashish

Ashish More
*iWorx Systems, Inc.*
603-742 2492 x12

**Comment by vadz** [comment]
Would it be possible for you to update the sample to add a way to call `SetPosition()` from it? I'd really like to see the problem (and the fix), but I have no simple way of testing it currently.

E.g. maybe add a button to skip 1/10 of the video ahead or something like this? TIA!

**Comment by ashishmore** [comment]
You can test this with the existing mediactrl sample.

1) open any video file.
2) Stop the playback.
3) Show the interface
4)  Drag the slider to any position
5) The image does not update, it will stay blank.


-Ashish

Ashish More
*iWorx Systems, Inc.*
603-742 2492 x12

**Comment by DaGiHu** [comment]
Hi there,

I'm working on a simple Windows video editor (MinGW) idea and using MediaCtrl (WMP10 backend) I ran into the aforementioned issue. I've compiled a small Windows program showing this issue (url at the end of message. Executable file and 5 seconds length videoclip included).

Seeking while playing runs fine but loading the videoclip from pause or seeking while in pause mode, renders the screen blank (seeking is actually accomplished, press play to check it out). I include a code snippet showing the simple operation of this example. I hope it helps. Thank you.

p.s.: This is my first post in GitHub, I've hope not to look so noob.

https://drive.google.com/open?id=1L9HdWW7AlyFvetMp3r8WUV8c2EN_CR-B

**Comment by vadz** [comment]
@DaGiHu Just to be clear, do you also confirm that applying this PR fixes the problem?

**Comment by DaGiHu** [comment]
@vadz, I just sent a simple example to clearly demonstrate the issue, not a solution. Sorry.

**Comment by vadz** [comment]
But this PR does contain a solution, I just didn't have time to test it yet. It would be appreciated if you could confirm that it does indeed solve the problem.

**Comment by DaGiHu** [comment]
@vadz, it's not working on my system (Win8, WinMediaPlayer 12.0.9600, compiled using wxWidgets 3.1.0/MinGW).

Does it works on your setup?. In my computer, when I click Load, it shows the first frame in a flash and immediately goes black. If I play it runs normally and then, if I click Pause, subsequent Seek button clicks doesn't update into the new frame. It just keeps showing the frame where Stop button was first clicked.

I also tried in another pc (Win7) and it fails the same way.

I'm sorry I delete my original message by mistake. The URL with my example is at:
https://drive.google.com/open?id=1L9HdWW7AlyFvetMp3r8WUV8c2EN_CR-B

**Comment by vadz** [comment]
No, as I said, I didn't have time to test it yet, sorry.

**Comment by ashishmore** [comment]
Hi,
 have you tried it with the mediactrl sample?.

-Ashish

Ashish More
*iWorx Systems, Inc.*
603-742 2492 x12

**Comment by DaGiHu** [comment]
Hi @ashishmore 

Yes, I've tried MediaPlayer sample code and it also renders the screen black when video is paused. 
Seeking works but no video update, just blank screen. Playing again shows the video normally.

Thank you.

**Comment by ashishmore** [comment]
Have you tried the mediasample with the patch?.
The patch fixed the video update after seeking.


-Ashish

Ashish More
*iWorx Systems, Inc.*
603-742 2492 x12

**Comment by DaGiHu** [comment]
@ashishmore, I guess I'm surely missing something. I've downloaded 3.1.1 and replaced the patched source file _mediactrl_wmp10.cpp_. I've built it like this:

mingw32-make -f makefile.gcc USE_XRC=1 SHARED=1 MONOLITHIC=1 BUILD=release UNICODE=1 USE_OPENGL=1 VENDOR=cb CXXFLAGS="-fno-keep-inline-dllexport -enable-mediactrl"

I compile MediaPlayer sample (using C::B, MinGw) with no errors but I still have blank screen in paused mode.

p.s.: Using that build command I get errors from patched _mediactrl_wmp10.cpp_ building wx3.0.4 or wx3.1.0.

**Comment by DaGiHu** [comment]
@ashishmore , I finally was able to compile your fix properly into the library. It works nicely and the blank screen is no longer there on seeking. Thank you for patching this.

What I miss now is MediaCtrl to show the first frame when the videoclip is loaded (I guess after loading it is in STOPPED state) instead of a blank screen.

**Comment by ashishmore** [comment]
try SetPosition(0)  after loading the file,

-Ashish

Ashish More
*iWorx Systems, Inc.*
603-742 2492 x12

**Comment by vadz** [comment]
Sorry for delay, but I'm finally applying this (with some minor formatting/style changes), thanks!

**Pull request closed without merging**
