### PR TITLE
Fix wxNativeFontInfo::InitFromFont() when using Pango

### PR DESCRIPTION
**Pull request by swt2c**

### CODE REVIEW

**Comment by vadz** [comment]
Couldn't we just use [pango_font_description_copy()](https://developer.gnome.org/pango/stable/pango-Fonts.html#pango-font-description-copy) in `wxUSE_PANGO`-specific function instead? We'd still have to handle underline/strikethrough separately, but it seems like this should be more reliable and definitely simpler.

Also, we try (and AFAIK, succeed) to avoid including platform headers from wx public headers to avoid name clashes, so it would be best to implement `InitFromFont()` for Pango in `src/unix/fontutil.cpp`.

TIA!

**Comment by swt2c** [comment]
> Also, we try (and AFAIK, succeed) to avoid including platform headers from wx public headers to avoid name clashes, so it would be best to implement InitFromFont() for Pango in src/unix/fontutil.cpp.

Fair enough, but there's a counterexample of a Qt header being included just above.  :-)

**Comment by vadz** [comment]
Yes, it's a pity that wxQt includes quite a few of Qt headers from the public ones. But OTOH it's not the most urgent problem with wxQt, so it's less important than (not) doing it with wxGTK,,,

**Comment by swt2c** [comment]
OK, what do you think about this instead?  I'd rather avoid adding `InitFromFont()` to `src/unix/fontutil.cpp` as that would be an ABI change, wouldn't it?  I'd prefer to see this fixed in 3.0 also.  Of course, applications will have to recompile anyway to see the fix as it's a header change.

**Comment by vadz** [comment]
This looks fine, thanks! But if we're to backport this to 3.0, I'd like to understand what actual problem does this fix? Admittedly, I don't see how could this break anything but it's a not completely trivial change and I'm not sure it's not going to change the new font family, for example...

**Comment by swt2c** [comment]
> This looks fine, thanks! But if we're to backport this to 3.0, I'd like to understand what actual problem does this fix? Admittedly, I don't see how could this break anything but it's a not completely trivial change and I'm not sure it's not going to change the new font family, for example...

The problem that this fixes is that `InitFromFont()` is completely broken when using Pango.  You get a bunch of GTK errors because the PangoFontDescription is NULL, and then you get an assert because `SetEncoding()` isn't implemented for Pango.

Isn't the font family copied as part of the PangoFontDescription?

**Comment by vadz** [comment]
Huh, I thought there was just some loss of information, not that it didn't work at all.

And while this patch still looks good to me, I think there is another problem here that needs to be fixed: all `SetXXX()` functions need to allocate `description` if it doesn't exist yet.

**Comment by swt2c** [comment]
> And while this patch still looks good to me, I think there is another problem here that needs to be fixed: all SetXXX() functions need to allocate description if it doesn't exist yet.

Good point - I suppose we could have also just fixed this particular issue by fixing those functions and just skipping the `SetEncoding()` for Pango.

**Pull request closed without merging**
