### PR TITLE
Improve wxCollapsiblePane generic implementation

### PR DESCRIPTION
**Pull request by TcT2k**
The generic `wxCollapisblePane` implementation (used in OSX and MSW) used a generic button. This PR adds a new `wxCollapsibleHeaderCtrl` which is now used by the generic implementation. This gives a much more native look on Windows (especially Vista+) and also improves look on OS X which previously used a low resolution bitmap and looked bad on high resolution displays. Implementation is based on new renderer method `wRendererNative::DrawCollapseButton()` which might also be useful elsewhere.

I've attached 2 screenshots comparing new and old implementation on Windows 7 with dialogs sample:

New Style:
wxwidgets_collpane_new
Old Style:
wxwidgets_collpane_old

### CODE REVIEW

**Comment by vadz** [comment]
Very nice, thanks a lot! I wanted to do it since a long time but didn't know how to draw this button natively under MSW (how did you find the correct theme part?). The only possible improvement I see would be to provide native implementation for OS X using `NSButtonCell` if possible.

Thanks again!

**Comment by TcT2k** [comment]
Finding the correct theme part was indeed a little bit tricky, because I've searched for a specific button type or state of a button. But it was part of `TASKDIALOG` theme and [this](https://github.com/mity/theme-explorer/releases) theme explorer is very helpful finding the correct theme parts.

`NSButtonCell` would required bitmaps drawn by `wxRendererNative::DrawCollapseButton()` or does it have a property that would give the desired look natively?

**Comment by vadz** [comment]
Thanks for the link, this is going to be useful in the future (although I actually wrote something like this (albeit much more primitive) myself, but it didn't help me as I just didn't think to look at the "TASKDIALOG" class...).

As for `NSButtonCell`, it supports `NSDisclosureBezelStyle`, so presumably we could just draw it on a memory DC to get the image?

**Comment by TcT2k** [comment]
That is the style I didn't find.
I'll look into that, definitely makes sense to use the native control.

**Pull request merged**
