### PR TITLE
Add wxBitmap(const wxCursor &cursor) constructor in wxOSX

### PR DESCRIPTION
**Pull request by MaartenBent**
Some additions to #2005.

### CODE REVIEW

**Comment by oneeyeman1** [comment]
@MaartenBent ,
Thank you for doing it.

But its already failing it - at least n GTK2, because of some permissions.

Any idea what is this about? Should it be restarted?

It is probably too late to include it in 3.1.5, but hopefully it will be in the next one.

Thank you for doing it once again.

**Comment by MaartenBent** [comment]
It fails because I removed the `if( bitmap.IsOk() )` check. I thought is should not be necessary anymore.
I'll try to find out why the bitmap is invalid, maybe it is a `XVFB` thing...

**Comment by MaartenBent** [comment]
It also fails in my VM, because [gdk_cursor_get_image ](https://developer.gnome.org/gdk3/stable/gdk3-Cursors.html#gdk-cursor-get-image) returns `NULL`. I guess I'll restore the `IsOk()` check, but only for GTK.

Note to self: run `test_gui` on macOS since CI does not do this.

**Comment by oneeyeman1** [comment]
@MaartenBent ,
That's exactly why I put the call to IsOk().
If you look at my PR I gave a link to the GNOME discussion board with the explanation.
GTK devs says that the call can fail and if we want - we can use Xcursor library.

However, I think this will work on X only and not Wayland.

Read the thread I mentioned - you will understand the reasoning behind it.

Thank you.

**Comment by oneeyeman1** [comment]
@MaartenBent ,

Here is the link for the reference: https://discourse.gnome.org/t/get-image-from-cursor/4648/4..

Thank you.

**Comment by MaartenBent** [comment]
I tested it on macOS and there are two problems. The resulting image size is twice is large (due to DPI?).

When I scale it to the original image size and compare, the images are a bit different and `RGBASimilarTo` is not able to compare them:
macos_difference

**Comment by MaartenBent** [comment]
Here is an clearer example using `wx.png`. It seems rescaling changes the alpha around the edges. So I suppose this test will pass on a non-retina display where no scaling is needed.
created image | original upscaled | diff
wx1 wx2 diff

**Comment by oneeyeman1** [comment]
@csomor ,
Any idea?

Thank you.

**Comment by oneeyeman1** [comment]
@MaartenBent ,
Are you using 32x32 png (or 16+x16 one? ) ? Or any other size?

Thank you.

**Comment by MaartenBent** [comment]
I used `tests/image/wx.png`, it is 32x32 px, to create the `wxCursor`. After converting from `wxCursor` to `wxBitmap`, the size of the bitmap is 64x64 px. I would expect it to be 32x32 px.

**Comment by MaartenBent** [comment]
I tried some things and get the correct size when I provide scaleFactor `2` (second argument) to `wxOSXGetImageFromCGImage` in `wxMacCocoaCreateCursorFromCGImage`:
https://github.com/wxWidgets/wxWidgets/blob/5f33a52f49014dea31f925c072a0d0a5b740c21d/src/osx/carbon/utilscocoa.mm#L592
I'd appreciate any help in creating a correct solution for this. Thanks.

**Comment by csomor** [comment]
I'll check it out and try to see where we loose the correct scaling factor

**Comment by MaartenBent** [comment]
Thanks. I did notice that with my scaleFactor modification, the actual cursor is only half the size. So maybe the image is wrongfully scaled again when converting from cursor to bitmap?

**Comment by MaartenBent** [comment]
What do you think of the following patch?
```diff
 include/wx/osx/core/private.h | 2 +-
 src/osx/carbon/utilscocoa.mm  | 5 +++--
 src/osx/core/bitmap.cpp       | 4 +++-
 3 files changed, 7 insertions(+), 4 deletions(-)

diff --git a/include/wx/osx/core/private.h b/include/wx/osx/core/private.h
index 1c21fae66c..dce18f8d97 100644
--- a/include/wx/osx/core/private.h
+++ b/include/wx/osx/core/private.h
@@ -124,7 +124,7 @@ WXDLLIMPEXP_CORE double wxOSXGetMainScreenContentScaleFactor();
 CGSize WXDLLIMPEXP_CORE wxOSXGetImageSize(WXImage image);
 CGImageRef WXDLLIMPEXP_CORE wxOSXCreateCGImageFromImage( WXImage nsimage, double *scale = NULL );
 CGImageRef WXDLLIMPEXP_CORE wxOSXGetCGImageFromImage( WXImage nsimage, CGRect* r, CGContextRef cg);
-CGContextRef WXDLLIMPEXP_CORE wxOSXCreateBitmapContextFromImage( WXImage nsimage, bool *isTemplate = NULL);
+CGContextRef WXDLLIMPEXP_CORE wxOSXCreateBitmapContextFromImage( WXImage nsimage, bool *isTemplate = NULL, double scale = -1);
 WXImage WXDLLIMPEXP_CORE wxOSXGetImageFromCGImage( CGImageRef image, double scale = 1.0, bool isTemplate = false);
 double WXDLLIMPEXP_CORE wxOSXGetImageScaleFactor(WXImage image);
 
diff --git a/src/osx/carbon/utilscocoa.mm b/src/osx/carbon/utilscocoa.mm
index 7e27bb21ac..3e0ac74784 100644
--- a/src/osx/carbon/utilscocoa.mm
+++ b/src/osx/carbon/utilscocoa.mm
@@ -256,14 +256,15 @@ CGImageRef WXDLLIMPEXP_CORE wxOSXGetCGImageFromImage( WXImage nsimage, CGRect* r
 #endif
 }
 
-CGContextRef WXDLLIMPEXP_CORE wxOSXCreateBitmapContextFromImage( WXImage nsimage, bool *isTemplate)
+CGContextRef WXDLLIMPEXP_CORE wxOSXCreateBitmapContextFromImage( WXImage nsimage, bool *isTemplate, double scale = -1)
 {
     // based on http://www.mail-archive.com/cocoa-dev@lists.apple.com/msg18065.html
 
     CGContextRef hbitmap = NULL;
     if (nsimage != nil)
     {
-        double scale = wxOSXGetMainScreenContentScaleFactor();
+        if (scale <= 0)
+            scale = wxOSXGetMainScreenContentScaleFactor();
 
         CGSize imageSize = wxOSXGetImageSize(nsimage);
 
diff --git a/src/osx/core/bitmap.cpp b/src/osx/core/bitmap.cpp
index cb9f2163e3..e7df8a4723 100644
--- a/src/osx/core/bitmap.cpp
+++ b/src/osx/core/bitmap.cpp
@@ -922,7 +922,9 @@ wxBitmap::wxBitmap(WXImage image)
 #if wxOSX_USE_COCOA
 wxBitmap::wxBitmap(const wxCursor &cursor)
 {
-    m_refData = new wxBitmapRefData( wxOSXGetNSImageFromNSCursor( cursor.GetHCURSOR() ) );
+    WXImage img = wxOSXGetNSImageFromNSCursor( cursor.GetHCURSOR() );
+    CGContextRef cgcRef = wxOSXCreateBitmapContextFromImage(img, NULL, 1.0);
+    m_refData = new wxBitmapRefData(cgcRef);
 }
 #endif

```

**Comment by csomor** [comment]
ok, the problem is that the system basically is lying to us about the image representation in wxOSXGetImageScaleFactor

```
(lldb) po rep
<NSCGImageSnapshotRep:0x60000211ef30 cgImage=<CGImage 0x102b18810> (DP)
	<<CGColorSpace 0x600002614a80> (kCGColorSpaceICCBased; kCGColorSpaceModelRGB; sRGB IEC61966-2.1)>
		width = 32, height = 32, bpc = 8, bpp = 32, row bytes = 128 
		kCGImageAlphaPremultipliedFirst | 0 (default byte order)  | kCGImagePixelFormatPacked 
		is mask? No, has masking color? No, has soft mask? No, has matte? No, should interpolate? Yes sig:<NSSnapshotContextSignature:0x600002c2a180 logicalRect={{0, 0}, {64, 64}} drawingRect={{0, 0}, {64, 64}} colorSpace=<CGColorSpace 0x6000026172a0> (kCGColorSpaceICCBased; kCGColorSpaceModelRGB; Farb-LCD) imageInterpolation=0>>

(lldb) po [rep pixelsWide]
64
```

so while it physically still is a 32x32 image, it tries to soothe us by pretending it's a 64x64 pixel for a 32x32 point cursor ...

**Comment by csomor** [comment]
since this subclass `NSCGImageSnapshotRep` is private, I'm not allowed to directly get the CGImageRef and ask it about its true dimensions which still are 32x32 ...

**Comment by csomor** [comment]
> What do you think of the following patch?

we would lose high-res support and suddenly high-res images would be blown up to 2x but lose their retina resolution info. While it would fix this problem, it would certainly introduce others ... and having a 32x32 bitmap which is internally 64x64 but knows about scale 2x is not really that wrong ...

**Comment by oneeyeman1** [comment]
Hi, guys,
One stupid question - does it work correctly on a regular (non-Retina) display?

Thank you.

**Comment by oneeyeman1** [comment]
@csomor 
> ok, the problem is that the system basically is lying to us about the image representation in wxOSXGetImageScaleFactor
> 
> ```
> (lldb) po rep
> <NSCGImageSnapshotRep:0x60000211ef30 cgImage=<CGImage 0x102b18810> (DP)
> 	<<CGColorSpace 0x600002614a80> (kCGColorSpaceICCBased; kCGColorSpaceModelRGB; sRGB IEC61966-2.1)>
> 		width = 32, height = 32, bpc = 8, bpp = 32, row bytes = 128 
> 		kCGImageAlphaPremultipliedFirst | 0 (default byte order)  | kCGImagePixelFormatPacked 
> 		is mask? No, has masking color? No, has soft mask? No, has matte? No, should interpolate? Yes sig:<NSSnapshotContextSignature:0x600002c2a180 logicalRect={{0, 0}, {64, 64}} drawingRect={{0, 0}, {64, 64}} colorSpace=<CGColorSpace 0x6000026172a0> (kCGColorSpaceICCBased; kCGColorSpaceModelRGB; Farb-LCD) imageInterpolation=0>>
> 
> (lldb) po [rep pixelsWide]
> 64
> ```
> 
> I'm on a retina display here, so while it physically still is a 32x32 image, it tries to soothe us by pretending it's a 64x64 pixel for a 32x32 point cursor, ready to use ...

Maybe thats how it should be?
I mean the image itself is not changed - it is still 32x32, only visible representation is changing.

And so we should just convert it 1->1 without taking anything into account. The resolution will be taken care of when we will try to display the wxBitmap.

Am I missing something?

**Comment by csomor** [comment]
the NSImageRep instances should return their true pixel dimensions in pixelsWide, that's how we can retrieve the best matching resolution and determine its scale. So the fact that in this instance the OS is scaling up the 32x32 image is not something we are supposed to know .. and that mechanism works perfectly with true high-res images ...

**Comment by MaartenBent** [comment]
So if I understand correctly, the image is already represented scaled, and when converting to `CGContextRef` in `wxOSXCreateBitmapContextFromImage` it is scaled again.

Should we account for this, for example like this. With this patch the original image and image->icon->bitmap->image have the same size, and the test passes.

```diff
 src/osx/carbon/utilscocoa.mm | 4 +++-
 1 file changed, 3 insertions(+), 1 deletion(-)

diff --git a/src/osx/carbon/utilscocoa.mm b/src/osx/carbon/utilscocoa.mm
index 7e27bb21ac..99dd5d87ee 100644
--- a/src/osx/carbon/utilscocoa.mm
+++ b/src/osx/carbon/utilscocoa.mm
@@ -263,7 +263,9 @@ CGContextRef WXDLLIMPEXP_CORE wxOSXCreateBitmapContextFromImage( WXImage nsimage
     CGContextRef hbitmap = NULL;
     if (nsimage != nil)
     {
-        double scale = wxOSXGetMainScreenContentScaleFactor();
+        double imageScale = wxOSXGetImageScaleFactor(nsimage);
+        double screenScale = wxOSXGetMainScreenContentScaleFactor();
+        double scale = screenScale / imageScale;
 
         CGSize imageSize = wxOSXGetImageSize(nsimage);
 

```

**Comment by csomor** [comment]
> So if I understand correctly, the `NSImage` is already represented scaled, and when converting to `CGContextRef` in `wxOSXCreateBitmapContextFromImage` it is scaled again.

It's not scaled again usually, it is converted to a CGBitmapContext with the same scale as the display, so that we don't loose precision in case the. Which is perfect if the NSImage has the same high resolution as well. Which is the case for eg OS artwork, such as native cursors eg. IMHO all current code is correct. The only situation we run into a up-down conversion that is when the OS itself is scaling our image 1x image to a 2x image on a retina display machine. And still the rendered size is correct, but the underlying bitmap is twice as big as it would have to be (only in this usage with our image, in the other cases it must be that big). So the only way to avoid this IMHO would be to eliminate the NSCursor roundtrip for the image data, storing a CGImageRef at the CGCursorRefData level as well. But I think since this is only an effect and not a really visibly incorrect behaviour I wouldn't think this to be a priority. But maybe I don't really see the real world implication of it.

**Comment by MaartenBent** [comment]
Ok, thanks for looking in to this.
I've now modified the test so it used `wx.png`. And if the resulting `wxImage` has a different size, it only checks if some specific coordinates have the same RGBA values.

**Comment by vadz** [comment]
Thanks!

Unless there are any objections soon, I'm going to merge this in time for 3.1.5, as it looks like a pure addition and so unlikely to break anything. Please let me know if I'm missing anything here.

**Pull request merged**
