### PR TITLE
[Qt] Ensure that wxListCtrl::HitTest finds correct index under qt

### PR DESCRIPTION
**Pull request by matthew-griffin**
Discovered that HitTest was not returning the correct index for positions relative to the wxListCtrl, as the underlying qt indexAt function expected the position to be relative to the sub widget that contains the actual items, which excludes the column headers.

I've added a report of the item index that was hit when an item is right clicked to the listctrl sample to demonstrate the issue.

### CODE REVIEW

**Comment by matthew-griffin** [comment]
Found that the same was true for calls to visualRect on the qt tree widget - not sure if this is a QT bug as it seems like it should take the header into account but this now gives the correct results.

**Review by catalinr — COMMENTED** [review]
Generally speaking, the changes to `wxListCtrl` should be the right thing to do. I only wonder about 2 things:
- should the changes to the sample be applied?
- at least in theory, `m_qtTreeWidget->header()` can return `NULL`; is it worth a check there or it will never happen?

**Comment by matthew-griffin** [comment]
I think that while generally `header()` can return `NULL`, it will never happen the way that it is set up for use with a `wxListCtrl`. I don't think it's possible to have a list control without a header but it would need to be considered if that is possible. It might be tidier putting it into a `GetHeaderHeight()` function anyway, which would return 0 if the header was `NULL`.

**Comment by catalinr** [comment]
> It might be tidier putting it into a `GetHeaderHeight()` function anyway, which would return 0 if the header was `NULL`.

Sounds good.

**Comment by vadz** [comment]
I've merged this into qt-listctrl branch (see #1551), please check if it works as intended there. TIA!

**Pull request merged**
