### PR TITLE
wxImage::Paste: add alpha blending and tests (ticket 12458)

### PR DESCRIPTION
**Pull request by epra74**
See http://trac.wxwidgets.org/ticket/12458, from which this change originates.

This change finishes the implementation started in http://trac.wxwidgets.org/ticket/12458.
I added tests that should cover most of the implementation.

### CODE REVIEW

**Comment by oneeyeman1** [comment]
@epra74 ,

Could you please check that my PR (2005 - Implement missing constructor for OSX) will now work correctly?

Thank you.

**Comment by andyburke** [comment]
Just gonna say it'd be great to see this finally land. :smile:

**Comment by kramdar** [comment]
Just gonna say, it's been over 10 years since I submitted that bug and I can hardly follow the conversation in the ticket. Truth be told I don't even write software anymore, now I make stop-motion puppets for a living. But thanks for the update, good luck!

**Comment by vadz** [comment]
Thanks Eric (and thanks again Rachel) for your work, I'm definitely going to merge this soon, I just need to reread the Trac discussion to remind me what all this was about.

**Comment by vadz** [comment]
Thanks again for the PR, it's nearly perfect (the tests changes are great!), I've just squashed the commits and added Rachel as coauthor and made one tiny change in the docs and merged it, thanks again!

**Pull request closed without merging**
