### PR TITLE
Aui sample upgrade

### PR DESCRIPTION
**Pull request by rozmansi**
This PR wipes the dust off the `sample\aui` project. It adds Visual Studio 2019 project files and adds all the wxWidgets library projects wxAUI sample depends on indirectly. This allows easy rebuilding and testing wxAUI.

### CODE REVIEW

**Comment by vadz** [comment]
Sorry but I don't think it makes sense to have MSBuild projects for just this sample but not all the other ones. We need to have them for all or none, IMO, and currently it is none, unfortunately, as we don't have any way to generate/update these files automatically and maintaining them manually is just impossible for us.

If you'd like to help with this, please consider devising some (really, any) way (would do) to generate the MSBuild files from the existing `.bkl` files or some other kind of input.

**Comment by rozmansi** [comment]
> Sorry but I don't think it makes sense to have MSBuild projects for just this sample but not all the other ones. We need to have them for all or none, IMO, and currently it is none, unfortunately, as we don't have any way to generate/update these files automatically and maintaining them manually is just impossible for us.

Makes sense.

**Comment by PBfordev** [comment]
@vadz  wrote
> If you'd like to help with this, please consider devising some (really, any) way (would do) to generate the MSBuild files from the existing `.bkl` files or some other kind of input.

Would this be welcome? I thought bakefile is to be retired and thus the .bkl files not going to be updated anymore? 

TBH, it would be interesting to know what is the future of build systems used with wxWidgets.

**Comment by vadz** [comment]
Yes, we will drop bakefile (at least 0.x, but we're probably not going to migrate to 1.x neither) after 3.2, but as long as we still have it, we could use it to generate MSVS projects from it in some ad hoc way, this would be simple enough to do and would be genuinely useful even if clearly not ideal long term solution.

We could also use `<samples>.files` akin to `build/files` to just list the files used by the sample that could probably be created with a shell one-liner from the existing samples bakefiles and generate from those, as hopefully any build system we could use in the future could reuse them.

But I just don't have time/bandwidth to do anything, or even think properly about it, right now, sorry...

**Comment by PBfordev** [comment]
I see, thanks for the quick reply.

**Pull request closed without merging**
