### PR TITLE
CMake: Keep empty adv library for backwards compatibility

### PR DESCRIPTION
**Pull request by MaartenBent**
Create an empty advanced library when using CMake, just like configure and the VS solutions.

### CODE REVIEW

**Comment by vadz** [comment]
Apparently you also need to disable PCH use for this one (sorry, no idea how to do it).

**Comment by MaartenBent** [comment]
Its a different problem. `dummy.cpp` is added twice. The first one, that is used as trigger to generate the PCH, is replaced with the second one. As a result the PCH is not generated. I''ll fix it later.

**Comment by vadz** [comment]
What I mean is that we really shouldn't create PCH for this empty library, it's just a waste of disk space (and time).

**Comment by MaartenBent** [comment]
It will be automatically disabled because it has only 1 source file. The default minimum is 2.

**Comment by vadz** [comment]
Ah, this is smart, thanks for explaining it.

**Pull request merged**
