### PR TITLE
wxGenericListCtrl fixes

### PR DESCRIPTION
**Pull request by AliKet**
Replacement for #2016

Notice that this hack eff6d23 is left out in this PR and a proper fix is still wanted!

Also, i should let you know that the added test pass successfully on my development machine
(using X srever as well as Xvfb), but refuses to pass on Travis CI and i'm still don't know why!

### CODE REVIEW

**Comment by AliKet** [comment]
Ticket [#18780](https://trac.wxwidgets.org/ticket/18780) should be fixed by ce5bc01

**Comment by oneeyeman1** [comment]
@AliKet ,
My ticket (18648) is still fixed as well, right

**Comment by AliKet** [comment]
> @AliKet ,
> My ticket (18648) is still fixed as well, right

Yes, and sorry for not mentioning it above!

**Comment by vadz** [comment]
Thanks a lot for the updates and sorry for the long delay before looking at them, but I've finally done it and everything looks good to me, so I'm merging this (as a single squashed commit).

Of course, it would be great to find and fix the Travis CI problem, but this can be done later.

Thanks again for all your work on this!

**Pull request closed without merging**
