### PR TITLE
Many, mostly MSW-specific, wxLocale fixes

### PR DESCRIPTION
**Pull request by vadz**
The most important commits are the first and the last one.

### CODE REVIEW

**Comment by kivadiu** [comment]
Hi Vadim,
How do I get all these commits into my own copy of wxWidgets repository?
Frédéric

**Comment by kivadiu** [comment]
OK, I got it:
git remote add vadz https://github.com/vadz/wxWidgets
git fetch vadz

**Comment by vadz** [comment]
@kivadiu Even simpler for once-only use: `git fetch https://github.com/vadz/wxWidgets.git msw-locale`, then you have this branch available as `FETCH_HEAD` (until the next fetch only, of course, so to use it long term you should create your own local branch based on it, i.e. `git checkout -b my-msw-locale FETCH_HEAD`).

**Comment by kivadiu** [comment]
The code now goes to line intl.cpp:562:
wxGetANSICodePageForLocale(LOCALE_USER_DEFAULT).empty()
with LOCAL_USER_DEFAULT=1024
It returns L"1252" so that line intl.cpp:566 is not called:
retloc = "C";
and retloc is still 0x0.

Then line intl.cpp:588 is called
return DoCommonPostInit
and the error message appears (intl.cpp:360)
wxLogWarning(_("Cannot set locale to language \"%s\"."), name);

**Comment by vadz** [comment]
I don't understand what's going on here :-( There must be a bug in `TrySetLocale()`, but I don't see what is it. It should fail to set locale to the result of `LOCALE_SNAME` with your MinGW, but it should succeed setting it to the result of `LOCALE_SENGLANGUAGE` combined with `LOCALE_SENGCOUNTRY` and the code page because otherwise how could [your patch](https://groups.google.com/d/msg/wx-users/duTOQm_jPk4/MaEhBGsFAgAJ) work?

Could you please check what's going on inside this function?

**Comment by kivadiu** [comment]
Hi Vadim,

Thanks for you inquiry.

Note that I have this in TrySetLocale():
LOCALE_SENGLANGUAGE == 4097
LOCALE_SENGCOUNTRY == 4098
LOCALE_SNAME == 92

Then from src/common/intl.cpp:148
const LCID lcid = GetLCID(); // lcid == 1036
if ( wxGetWinVersion() >= wxWinVersion_Vista ) // wxGetWinVersion() == wxWinVersion_10
if ( ::GetLocaleInfo(lcid, LOCALE_SNAME, buffer, WXSIZEOF(buffer)) ) // true
locale << buffer; // locale == L"fr-FR", buffer == L"fr-FR"
const char* const retloc = wxSetlocale(LC_ALL, locale); // retloc == 0x0
if ( !::GetLocaleInfo(lcid, LOCALE_SENGLANGUAGE, buffer, WXSIZEOF(buffer)) ) // false
// buffer == L"French"
locale << buffer; // locale == L"fr-FRFrench" , this looks quite strange? should it be just L"French"?
if ( ::GetLocaleInfo(lcid, LOCALE_SENGCOUNTRY, buffer, WXSIZEOF(buffer)) > 0 ) // true
// buffer == L"France"
locale << wxT('_') << buffer; // locale == L"fr-FRFrench_France"
const wxString cp = wxGetANSICodePageForLocale(lcid); // cp==L"1252"
locale << wxT('.') << cp; // locale == L"fr-FRFrench_France.1252"
return wxSetlocale(LC_ALL, locale); // 0x0

**Comment by vadz** [comment]
Damn, I'm really sorry for making a so stupid mistake, thanks for finding it. Should be really fixed by the latest commit.

**Comment by kivadiu** [comment]
Hi Vadim,
It works :-) Congratulations.
TrySetLocale() now returns retloc=="French_France.1252" and I do not get anymore the warning.
However I cannot compile anymore the library for OSX but this is probably totally unrelated and related to another commit on master. Will try the master branch to see if I have the same issue so that we can confirm this PR is fine and can be merged.
Frédéric

**Comment by kivadiu** [comment]
OK, no need to recompile master. I see were the problem seems to come (will send a mail to the list). You can merge this PR. Thanks again, Frédéric

**Comment by kivadiu** [comment]
Question: should we revert Julian's commit?
f14d702e4aa2fd28cdbef7c60c8dbe9cda82bed1

**Comment by vadz** [comment]
I did revert this commit because I think it's better to do the check during run-time than try to find all the compiler/CRT versions that support or don't support the new locale names. The overhead of the check should be negligible and the code is simpler like this.

Thanks for testing!

**Pull request merged**
