### PR TITLE
grid.h: add missing <memory>

### PR DESCRIPTION
**Pull request by barracuda156**
At least gcc-14 needs this.

### CODE REVIEW

**Comment by barracuda156** [comment]
Error:
```
/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_graphics_wxgtk-3.2/wxgtk-3.2/work/wxWidgets-a8b6fdb7a7d518258a56b6a88262bf8281ddd26e/include/wx/generic/grid.h: At global scope:
/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_graphics_wxgtk-3.2/wxgtk-3.2/work/wxWidgets-a8b6fdb7a7d518258a56b6a88262bf8281ddd26e/include/wx/generic/grid.h:2994:10: error: 'unique_ptr' in namespace 'std' does not name a template type
 2994 |     std::unique_ptr<wxGridOperations> DoGetOperationsFromCursorMode(void);
      |          ^~~~~~~~~~
/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_graphics_wxgtk-3.2/wxgtk-3.2/work/wxWidgets-a8b6fdb7a7d518258a56b6a88262bf8281ddd26e/include/wx/generic/grid.h:23:1: note: 'std::unique_ptr' is defined in header '<memory>'; this is probably fixable by adding '#include <memory>'
   22 | #include <unordered_set>
  +++ |+#include <memory>
   23 | 
```

**Comment by vadz** [comment]
No, sorry, this is wrong. 3.2 still supports C++98 and so doesn't use `unique_ptr` at all. I don't know where does it come from, but the official 3.2 branch doesn't have it in `grid.h`.

**Comment by barracuda156** [comment]
> No, sorry, this is wrong. 3.2 still supports C++98 and so doesn't use `unique_ptr` at all. I don't know where does it come from, but the official 3.2 branch doesn't have it in `grid.h`.

@vadz The master uses it: https://github.com/wxWidgets/wxWidgets/blob/a8b6fdb7a7d518258a56b6a88262bf8281ddd26e/include/wx/generic/grid.h#L2994

The PR is against the master, not 3.2.5.

Whether it should be used or not is another question, but it is there.

**Comment by vadz** [comment]
Sorry, I got confused because your error messages have 3.2.5 in them.

Master does need it, thanks.

**Comment by barracuda156** [comment]
> Sorry, I got confused because your error messages have 3.2.5 in them.
> 
> Master does need it, thanks.

Ah, that is because I switched to building from the master due to uilocale-related fixes (it was a pain to backport, patches did not apply cleanly), but retained version number in the portfile.
This is orthogonal as such to GTK issue.

**Pull request closed without merging**
