### PR TITLE
Use PCRE for wxRegEx

### PR DESCRIPTION
**Pull request by vadz**
Unfortunately allowing to choose between using the current library and PCRE proved to be too difficult. It's easy enough to do it when using configure, but after spending a couple of hours on trying to make it work with bakefile and makefiles, I gave up. If anybody can see a way to do it or if people think that we really, really need to preserve the possibility of turning PCRE off, I might return to it later, but I'd very much prefer not to do it. In any case, I think that either PCRE compatibility with TCL syntax is good enough, in which case we don't really need to have this option, or it isn't, in which case we can't switch to it by default anyhow.

Also, if we merge this as is, we should simplify the code in `src/common/regex.cpp`:

1. Remove everything in `#else` branch of `#if wxUSE_PCRE`.
2. Stop emulating POSIX API using PCRE API and just use the latter directly.

### CODE REVIEW

**Comment by vadz** [comment]
Seems to finally build/work in all configurations, only ASAN tests failure remains.

**Comment by MaartenBent** [comment]
I don't really use regex so no comments on that.

I suppose `pcre2` is also available as system library, should CMake try to find it? Currently it always forces the builtin version.

**Comment by vadz** [comment]
> I suppose `pcre2` is also available as system library, should CMake try to find it? Currently it always forces the builtin version.

Oops, I completely forgot that I wanted to do this, thanks for the reminder. It would indeed be better to use the system version if available and, of course, if you could do this, it would be great. Note that the exact version to use depends on the build options, see `pcre_suffix` [determination in configure](https://github.com/wxWidgets/wxWidgets/pull/2438/files#diff-bb21aa33a3f69ccb36c68b220f40ad08f29b9cd2c05dfedae7b9e3d5d4d08f6b).

**Comment by MaartenBent** [comment]
Sure, I'll try to add it. I can create a PR later, or do you want it before you merge this?

**Comment by vadz** [comment]
Ideal would be to do it before merging this PR, so I guess the best would be to:

1. Merge #2440 in order to enable the tests (I'm just waiting for your green light before doing this).
2. Rebase/fixup the changes here.
3. Make a PR against vadz/regex-pcre.

Thanks again!

**Comment by vadz** [comment]
(1) and (2) from the previous comment are done now.

**Pull request merged**
