### PR TITLE
Add options for Setting and Getting focus acceptance without the need…

### PR DESCRIPTION
**Pull request by tomay3000**
… of subclassing the associated virtual functions.

### CODE REVIEW

**Comment by vadz** [comment]
I've just closed [#8153](http://trac.wxwidgets.org/ticket/8153) yesterday because, as I wrote there, we already have (too?) many focus-related functions. So I'd need a very good argument to apply this because it complicates things even more and I don't want to do it without real need.

Why do you need to do this at all and why is it a problem to do it in the derived class?

**Comment by tomay3000** [comment]
> I've just closed [#8153](http://trac.wxwidgets.org/ticket/8153) yesterday because, as I wrote there, we already have (too?) many focus-related functions. So I'd need a very good argument to apply this because it complicates things even more and I don't want to do it without real need.
> 
> Why do you need to do this at all and why is it a problem to do it in the derived class?

It is just because it would be simple and easy to do :
`wxButton *pMyButton = new wxButton(m_pTransferts_ScrldWnd, wxID_ANY, wxEmptyString, wxDefaultPosition, wxDefaultSize, 0);
pMyButton->SetAcceptsFocusFromKeyboard(false);`
rather than :
`// ----------------------------------------------------------------------------
// wxButtonEx
// ----------------------------------------------------------------------------

class wxButtonEx : public wxButton
{
public:
    wxButtonEx() : wxButton()
    {
    }

    wxButtonEx(wxWindow *pWndParent, wxWindowID id,
               const wxString& strLabel = wxEmptyString,
               const wxPoint& ptPos = wxDefaultPosition,
               const wxSize& size = wxDefaultSize, long lStyle = 0,
               const wxValidator& validator = wxDefaultValidator,
               const wxString& strName = wxButtonNameStr)
        : wxButton(pWndParent, id, strLabel, ptPos, size, lStyle,
                   validator, strName)
    {
    }

    virtual ~wxButtonEx() {}

private:
    virtual bool AcceptsFocusFromKeyboard() const wxOVERRIDE
    {
        return false;
    }
};

wxButtonEx *pMyButtonEx = new wxButtonEx(m_pTransferts_ScrldWnd, wxID_ANY, wxEmptyString, wxDefaultPosition, wxDefaultSize, 0);
`

**Comment by vadz** [comment]
The question is, why on earth would you want to have an enabled button not taking focus? Does this have any other purpose than confusing the user?

My reasoning is that if you really need a control which is enabled but doesn't take focus, it must be something so exotic that you surely implement it in a separate class anyhow, and in this case overriding `AcceptsFocus()` is hardly a burden. Of course this is less convenient for a standard control, but IMO you're not supposed to do this for the standard controls in the first place.

Do you have any better examples of when would this be useful?

**Comment by tomay3000** [comment]
> The question is, why on earth would you want to have an enabled button not taking focus? Does this have any other purpose than confusing the user?
hhh, no, of course not.
For this one the main purpose is used when for example you want to implement a **Visual Keyboard** for touch screens for example, or simply a **Visual Keyboard Application**, where the focus won't be lost from where it was before (a `wxTextCtrl` for example), and only handle `wxEVT_LEFT_DOWN` in this case to do the key press action, and simulate a button down and up drawing if necessary to make the user feel that he actually clicked on that button. This way yould be better (I think!) of saving the last focus window and restoring it to that window after the click.

> My reasoning is that if you really need a control which is enabled but doesn't take focus, it must be something so exotic that you surely implement it in a separate class anyhow, and in this case overriding `AcceptsFocus()` is hardly a burden. Of course this is less convenient for a standard control, but IMO you're not supposed to do this for the standard controls in the first place.
> 
> Do you have any better examples of when would this be useful?
As for `AcceptsFocusFromKeyboard`, the main purpose of it is **excluding** that control from **TAB navigation** by keyboard, of course it would be possible to click on it by mouse.

Take a look at the illustrated screenshot:
Untitled

**Comment by vadz** [comment]
Sorry, I don't really find this very convincing -- you're not really going to use standard buttons for this, are you. So it clearly falls into the "non-standard window" case in which you already have a class representing the window.

**Comment by tomay3000** [comment]
> Sorry, I don't really find this very convincing -- you're not really going to use standard buttons for this, are you.

No, I am not using standard buttons, I have used subclassed ones for this.

> So it clearly falls into the "non-standard window" case in which you already have a class representing the window.

You are right about this one.

But only for `AcceptsFocusFromKeyboard`, I have situations where I don't have to subclass the window at all, I only need to **exclude** it from the **tab order**.
the parent `wxWindow` has two functions `MoveAfterInTabOrder()` and `MoveBeforeInTabOrder()`, but unfortunately doesn't have a `(Delete|Remove|Exclude)FromTabOrder`
which is at least supported by Win32 Api Dilog resource, and called: **Tab Stop**
Untitled2

**Comment by vadz** [comment]
I think perhaps we could live with just a `SetAcceptsFocusFromKeyboard()` and returning `m_acceptsFocusFromKeyboard` from `AcceptsFocusFromKeyboard()`. But even then it's an additional complication creating further questions. For example, you've modified `wxTextCtrl::AcceptsFocusFromKeyboard()` to return false if this flag is reset, which makes sense. But wouldn't somebody who called `SetAcceptsFocusFromKeyboard(true)` expect the control to accept focus from keyboard even when it's read-only and single-line?

Providing both the flag and the possibility to override `AcceptsFocusFromKeyboard()` doesn't look like a good idea. Perhaps it would have been better to not make the latter virtual in the first place, but it's too late for it.

**Comment by tomay3000** [comment]
> I think perhaps we could live with just a `SetAcceptsFocusFromKeyboard()` and returning `m_acceptsFocusFromKeyboard` from `AcceptsFocusFromKeyboard()`. But even then it's an additional complication creating further questions. For example, you've modified `wxTextCtrl::AcceptsFocusFromKeyboard()` to return false if this flag is reset, which makes sense. But wouldn't somebody who called `SetAcceptsFocusFromKeyboard(true)` expect the control to accept focus from keyboard even when it's read-only and single-line?

About `wxTextCtrl::AcceptsFocusFromKeyboard()`, by default it is set to `true` in the constructor in the toolkit, `m_bAcceptsFocusFromKeyboard = true;`, and only set to `false` by the application developer, and if he set it to `false`, then that's what he wants, right!

> Providing both the flag and the possibility to override `AcceptsFocusFromKeyboard()` doesn't look like a good idea. Perhaps it would have been better to not make the latter virtual in the first place, but it's too late for it.

You are right it is too late for compatibility, because these problems are only discovered when you try to achieve something that you have done in the native Api, because I was an MFC developer before I catch-up wxWidgets v2.9.5 in 2013.

I suggest that we implement a `(Delete|Remove|Exclude)FromTabOrder()` function like the ones already existing `MoveAfterInTabOrder()`, `MoveBeforeInTabOrder()`, which are not virtual :)
and do the latter ones include it back to the tab order if they were called, and/or add another function `(Add|Insert|Include)(To|In)TabOrder()` to include it back to the tab order navigation, and we should keep track of the position of it before its exclusion from the tab order.

What your your suggestions?

Thank you.

**Comment by vadz** [comment]
I think adding `ExcludeFromTabOrder()` should indeed be fine. We probably want to do the same thing as for `MoveXXXInTabOrder()` functions, i.e. make the public function non-virtual, but have a virtual `DoExcludeFromTabOrder()` that could be implemented in a platform-specific way (e.g. under MSW it could just reset `WS_TABSTOP`, right?).

**Comment by tomay3000** [comment]
> I think adding `ExcludeFromTabOrder()` should indeed be fine. We probably want to do the same thing as for `MoveXXXInTabOrder()` functions, i.e. make the public function non-virtual, but have a virtual `DoExcludeFromTabOrder()` that could be implemented in a platform-specific way (e.g. under MSW it could just reset `WS_TABSTOP`, right?).

digging a little bit into the MSW code [HERE](https://github.com/wxWidgets/wxWidgets/blob/master/src/msw/control.cpp), I found this:
```cpp
WXDWORD wxControl::MSWGetStyle(long style, WXDWORD *exstyle) const
{
    long msStyle = wxWindow::MSWGetStyle(style, exstyle);

    if ( AcceptsFocusFromKeyboard() )
    {
        msStyle |= WS_TABSTOP;
    }

    return msStyle;
}
```
The style stranslation from wxWidgets to MSW is relating to `AcceptsFocusFromKeyboard()`.
wxWidgets never had its own style like: `wxTAB_STOP` for `wxControls`, but rather uses `AcceptsFocusFromKeyboard()` direcly to Set/Clear the tab-stop flag, thus we fall back to the previous case were we should define a new function called `SetAcceptsFocusFromKeyboard()` with a member variable: `m_bAcceptsFocusFromKeyboard`, and optionally adding:
```cpp
void IncludeInTabOrder()
{
    m_bAcceptsFocusFromKeyboard = true;
}

void ExcludeFromTabOrder()
{
    m_bAcceptsFocusFromKeyboard = false;
}
```
Because adding a new style: `wxTAB_STOP` would result in altering many files and many ports.

What do you think?

**Comment by vadz** [comment]
OK, let's add `DisableFocusFromKeyboard()` that would set `m_acceptsFocusFromKeyboard` to `false` and implement `AcceptsFocusFromKeyboard()` like this:

```cpp
bool AcceptsFocusFromKeyboard() const
{
    return AcceptsFocus() && m_acceptsFocusFromKeyboard;
}
```

Could you please update the PR to do just this?

**Comment by tomay3000** [comment]
> OK, let's add `DisableFocusFromKeyboard()` that would set `m_acceptsFocusFromKeyboard` to `false` and implement `AcceptsFocusFromKeyboard()` like this:
> 
> ```c++
> bool AcceptsFocusFromKeyboard() const
> {
>     return AcceptsFocus() && m_acceptsFocusFromKeyboard;
> }
> ```
> 
> Could you please update the PR to do just this?

Sure, but how to enable it back if desired!?
That would imply adding `EnableFocusFromKeyboard()`.
Or simply `EnableFocusFromKeyboard(const bool& bEnable)`

**Comment by vadz** [comment]
> 
> 
> > OK, let's add `DisableFocusFromKeyboard()` that would set `m_acceptsFocusFromKeyboard` to `false` and implement `AcceptsFocusFromKeyboard()` like this:
> > ```c++
> > bool AcceptsFocusFromKeyboard() const
> > {
> >     return AcceptsFocus() && m_acceptsFocusFromKeyboard;
> > }
> > ```
> > 
> > 
> > Could you please update the PR to do just this?
> 
> Sure, but how to enable it back if desired!?

Do we really need to enable it back?

> That would imply adding `EnableFocusFromKeyboard()`.

If we do, we should add it, but I'd call it `ReenableFocusFromKeyboard()` to make it more clear that this function only undoes a previous call to `DisableFocusFromKeyboard()` and does _not_ magically make the control focusable from keyboard if it's not focusable for some other reason (e.g. because its `AcceptsFocus()` returns false).

But I'd still prefer not to provide it at all, do we really have any realistic example when you'd need to toggle this dynamically?

> Or simply only `EnableFocusFromKeyboard(const bool& bEnable)`

BTW, there is definitely no need to pass something as small as `bool` by const reference.

**Comment by tomay3000** [comment]
> Do we really need to enable it back?
I don't know for now.

> do we really have any realistic example when you'd need to toggle this dynamically?
not for the moment, I mean I haven't faced one yet.

> BTW, there is definitely no need to pass something as small as `bool` by const reference.
OK, good to know, making the compiler produce an asm that do copy 1 byte doesn't hurt or affect performance.

**Comment by tomay3000** [comment]
I have done it, but you need to to delete the commit history by squashing'em I think.

**Comment by vadz** [comment]
Thanks for the update, I've finally added the documentation and merged this in time for 3.1.4.

**Pull request closed without merging**
