### PR TITLE
Assorted macOS fixes

### PR DESCRIPTION
**Pull request by vadz**
It would be great if someone having a better idea of how this stuff works could review the patches that I applied as I mostly apply them on trust alone.

And while I'm reasonably certain that the scale factor commit is correct, I'd still very much welcome your comments about it. TIA!

### CODE REVIEW

**Review by vslavik — COMMENTED** [review]
I'm afraid I'm worse than useless for reviewing this — the best I can say is ok, let's try what happens :(

With the exception of d44738c (which is trivial and fine), I just lack understanding of the issue or the code involved to have any certainty about the changed. They *look* reasonable and I assume you tested them with the specific tickets they address, so they should be fine, but I feel like I don't really know what I'm talking about with them.

I understand the logic behind 14468065ab759619bdd64c6cdeb20f8ef6aa8d05 and it looks good to me (so I guess that's 2 exceptions).

I am however skeptical of 8280820f79c4986f136d153e0b7e6609cda277f7 — but again without being able to provide any *useful* criticism; I'm just *afraid* of it. I agree, of course, than less code is good, and less meddling with Cocoa's internals is even more so. But after having suffered through so many focus related issues (as discussed in http://trac.wxwidgets.org/ticket/17149 and in linked tickets and commits), I'm afraid that this will break something unexpected. OTOH if this code removal *can* be done, it absolutely should.

**Comment by bigjohnr** [comment]
On 7 December 2017 00:26:53 GMT+08:00, "Václav Slavík" <notifications@github.com> wrote:
>vslavik commented on this pull request.
>
>I am however skeptical of 8280820f79c4986f136d153e0b7e6609cda277f7 —
>but again without being able to provide any *useful* criticism; I'm
>just *afraid* of it.

It continues to work for me. My code contains other modifications but they should be irrelevant to this issue. Being responsible for this means there will be two of us in need of anxiolytics. :)
John

**Comment by bigjohnr** [comment]
On 7 December 2017 08:48:32 GMT+08:00, John Roberts <notifications@github.com> wrote:
>On 7 December 2017 00:26:53 GMT+08:00, "Václav Slavík"
><notifications@github.com> wrote:
>>vslavik commented on this pull request.
>>
>>I am however skeptical of 8280820f79c4986f136d153e0b7e6609cda277f7 —
>>but again without being able to provide any *useful* criticism; I'm
>>just *afraid* of it.
>
>It continues to work for me. My code contains other modifications but
>they should be irrelevant to this issue. Being responsible for this
>means there will be two of us in need of anxiolytics. :)
>John

I am not going to be home and near an osx box for another week so I can't test but I remember now that there was an issue with the wxRichtextCtrl cursor not becoming visible and this should be checked.
John

**Comment by csomor** [comment]
Unfortunately I'm rather busy at the moment, I look at the wxSTC patches, and there I lack the understanding of scintilla to really have a useful comment. But for the other ones I first have to dive into the history to understand how things were before and why I might have done something the other way. Especially the scale factor code was delegating responsibility to refdata, but now things are the other way round and I'll have to think things through...

**Comment by csomor** [comment]
#2bbcf2d seems to be missing a setLevel call the way it has been rewritten, on the other hand it adds a indirect (via restoreWindowLevel) on the parent, so I'd like to apply it with some modifications

**Comment by vadz** [comment]
@csomor Thanks for having a look at this nevertheless! I realize that you're busy (if you think you might have take more time in the future, please let me know as I'd prefer to wait with committing this rather than doing it blindly -- but I do want to take a decision before 3.1.1), but any input whatsoever from you is very welcome. I should have mentioned that I'm especially interested in the comments on [focus handling](8280820f79c4986f136d153e0b7e6609cda277f7), [freezing](14468065ab759619bdd64c6cdeb20f8ef6aa8d05) and, most of all, [window level](2bbcf2dcade24f1851bb5147d9d090c54e0653cb) changes -- the last one is the most important because I'm quite sure that it is wrong by now, but I'm still not sure what is the best way to fix it. BTW, please notice that this one is also continuing to be discussed on [wxTrac](http://trac.wxwidgets.org/ticket/17406) and I'd appreciate if you could have a look at the comments there as I'm totally out of my depth.

**Comment by csomor** [comment]
Thanks, yes, the next 10 days will be intense, but then things should cool down a little bit

**Comment by vadz** [comment]
I've committed the fixes that, I think, have a reasonable chance of being correct and created #672 for the remaining ones, related to window level changes.

**Pull request closed without merging**
