### PR TITLE
Fix wxTE_PROCESS_ENTER logic for wxMSW and wxGTK too

### PR DESCRIPTION
**Pull request by vadz**
See [this ticket](https://trac.wxwidgets.org/ticket/18273) and the new unit test for the logic of these changes.

@csomor Could you please check if the new test passes under Mac too? I think it should, after your latest changes, but I won't be able to test this today any more.

@paulcor Any comments about GTK part of the changes would be welcome, as always. TIA!

### CODE REVIEW

**Comment by vadz** [comment]
@csomor I've tried running the test under Mac myself (by just doing `./tests/test_gui wxTextCtrl::ProcessEnter`), but unfortunately it doesn't work at all there and I couldn't understand why: I'm getting asserts from `wxCFEventLoop::DoProcessEvents()` because it doesn't dispatch any events during 1s interval, even though `m_shouldWaitForEvent` is correctly set to true by `wxUIActionSimulatorOSXImpl::DoKey()` and the event seems to be injected, at least I got the system message box telling me that `test_gui` wants to manipulate the computer and telling me to allow it in the System Preferences (and I don't get this message box after doing this). But somehow it just disappears and is never dispatched... Would you have any idea why? It's really a pity that our GUI unit test suite is completely unusable under Mac :-(

**Comment by csomor** [comment]
does not work for me under 10.14, even after allowing the security parts. On which system are you testing ?
I'm trying different ways of posting the key event, no avail ...

**Comment by vadz** [comment]
I also tested under 10.14. The uiaction sample does work partially, however...

Thanks for looking at this!

**Comment by csomor** [comment]
same on 10.13, now trying to find my old MBP 17" for testing under older systems ...

**Comment by vadz** [comment]
> same on 10.13, now trying to find my old MBP 17" for testing under older systems ...

I don't think it's going to be very useful if it works only on some old macOS version that we're not going to be able to use for running the tests anyhow, so I'm not sure if it's worth spending time on this... My question is why does it work in the uiaction sample (although it is buggy, it does show at least something in the text control when you run the simulation), but not in the test. Do you have any idea about what could be different between their event loops?

**Comment by csomor** [comment]
the test fails on 10.9 as well, so I'll look at uiaction sample more closely ...

**Comment by vadz** [comment]
I've tested things under Mac manually for now, so merging this, but having automated tests working would still be very, very valuable.

**Comment by csomor** [comment]
Yes, I absolutely agree … what are the other problems we have with GUI testing under mac ? there *IS* a framework now for GUI testing, but it works at a quite high level of the UIElement, don't know whether it would be worth the effort ...

**Comment by vadz** [comment]
Running the GUI test suite gave quite a few errors the last time I tried. Of course, running it with `WX_UI_TESTS=1` results in even more of them (as this enables the use of `wxUIActionSimulator`, disabled by default under Mac). And then there are all `#ifndef __WXMAC__` in the tests code...

**Comment by csomor** [comment]
what is the current state of cppunit / catch ? I'm looking at integrating into XCTest, now is it enough to map the cppunit macros or do I need more ?

**Comment by vadz** [comment]
We don't use CppUnit any more, the macros are redefined in terms of Catch ones. I have no idea what's the advantage of integrating it into XCTest nor what needs to be done for this, sorry. I just build the test suite (`make -C tests test_gui`) and run it normally, from the terminal.

**Comment by csomor** [comment]
I need to integrate into this, if I want to be able to use the UI Test framework, so I first try to find out how to run console tests within the xcode testbed

**Comment by vadz** [comment]
Is UI Test framework only available from Xcode? I'm sorry, I'm completely ignorant of all this stuff, but I just don't understand why would it be _required_ to integrate our tests into Xcode. I guess it can be nice and I definitely have no objections to it (provided they can still be run outside of it), but it just doesn't look especially critical to me...

**Comment by csomor** [comment]
yes, you can run things from the command line, but it needs the Xcode environment

**Pull request merged**
