### PR TITLE
Windows vc14 fixes

### PR DESCRIPTION
**Pull request by es0m**
- vc14 supports snprintf
- removed redefine of _snprintf to snprintf in libtiff
- added vs14 solution file

### CODE REVIEW

**Comment by tierra** [comment]
Thank you for your contribution but we don't actually use Github
pull requests for this mirror of wxWidgets repository.

Please submit your changes to [our Trac](http://trac.wxwidgets.org) as explained [here](http://trac.wxwidgets.org/wiki/HowToSubmitTicket) instead.

Thanks in advance!

**Comment by es0m** [comment]
http://trac.wxwidgets.org/moderator/201

**Comment by shuffle2** [comment]
My projects using wxw will require this too (well, at least the `compiler.h` changes). Looking at http://trac.wxwidgets.org/browser/svn-wx/wxWidgets/trunk/include/wx/compiler.h , it seems like it's not supported yet. I can't find anything about this on the trac. What is up?

**Comment by vadz** [comment]
There is a [corresponding Trac ticket](http://trac.wxwidgets.org/ticket/16854) but I didn't have time to merge it yet. It will be done by the time VC14 is officially released.

**Comment by vdm113** [comment]
vadz> It will be done by the time VC14 is officially released.

I prefer this way as well, since I am using Intel C++ compiler as a plug-in into MSVC, and Intel refuses port their compiler to beta or RC releases of MSVC.

**Comment by tierra** [comment]
This is no longer necessary as Microsoft reverted changes, see [#16854](http://trac.wxwidgets.org/ticket/16854).

**Comment by discnl** [comment]
At least the compiler.h change would still be useful to have?

**Comment by vadz** [comment]
Let's add it once VC14 final is released and we can at least check that our unit tests pass with it.

**Pull request closed without merging**
