### PR TITLE
Update submodules

### PR DESCRIPTION
**Pull request by MaartenBent**
Update the submodules.

I changed the submodule repo to my own so I can test if CI succeeds before creating PRs for the submodules. Once the PRs of the submodules are merged, this PR should be updated with the correct repo and hashes.

- [x] expat 2.2.5 to 2.2.6
- [x] png 1.6.34 to 1.6.35
- [x] tiff 4.0.9+ to 4.0.10
- [x] catch2 1.11.0 to 1.12.2

### CODE REVIEW

**Comment by vadz** [comment]
Looks good to me, thanks! Should this be merged in the current state (checkbox haven't been checked, but expat, png and tiff seem to be done) or wait for CATCH update too? I wouldn't mind merging this already as CATCH is a bit different.

Thanks again!

**Comment by MaartenBent** [comment]
I first want to check if CI succeeds. But somehow AppVeyor isn't triggered. And Travis already fails.

In addition, I first have to create PRs for all the submodules.

**Comment by vadz** [comment]
Sorry, I meant "after CI passes". Unfortunately I don't know what's going on with AppVeyor.

**Comment by MaartenBent** [comment]
I created the PRs: https://github.com/wxWidgets/libexpat/pull/1 https://github.com/wxWidgets/libpng/pull/2 https://github.com/wxWidgets/libtiff/pull/1 https://github.com/wxWidgets/Catch/pull/1

When merged I will update this PR with the correct modules and hashes.
And I still have to add the new tiff files to the build system (even though they are not used).

**Comment by vadz** [comment]
I've merged all the PRs to submodules now, thanks.

**Comment by MaartenBent** [comment]
Thanks. This PR is ready as well.

**Comment by vadz** [comment]
Merged, thanks again for taking care of this!

Just one question: should `build/msw/wx_wxtiff.vcxproj{,.vcxproj}` be updated to include the new (but unused, IIUC) files as well for consistency?

**Comment by MaartenBent** [comment]
Yes. I'll create a PR for this.

**Pull request merged**
