### PR TITLE
Document missing overridden methods in wxFileSystemHandler subclasses

### PR DESCRIPTION
**Pull request by swt2c**
This is part of resolving a Phoenix issue, see:
https://github.com/wxWidgets/Phoenix/issues/175

### CODE REVIEW

**Comment by swt2c** [comment]
Please cherry-pick to 3.0 also.

**Comment by vadz** [comment]
Sorry but I'd really like to avoid duplicating (or rather quintiplicating) documentation of these methods. We can't afford manually re-documenting all inherited virtual methods (just think of what this would mean for `wxWindow`-derived classes) and it doesn't make sense to do it just here, but not elsewhere.

I don't understand what problem does this create for Phoenix, but it should be fixed in some other way.

**Comment by swt2c** [comment]
Sigh.

OK, I'll have to see what was done for the wxWindow subclasses.

**Comment by swt2c** [comment]
Just FYI, the interface headers represent "truth" to Phoenix.  If something doesn't exist in the interface headers, it doesn't exist as far as Phoenix is concerned.  In this case, the subclass isn't documented so Phoenix is calling the superclass method when it should be calling the subclass.

In the cases where things aren't listed in the interface headers, they have to be shoe-horned in manually in Phoenix (and the other wrappers).  IMO, it makes more sense to do this work once in the interface headers, rather than duplicating the work in each of the wrappers.

In the future, it would be appreciated to have a response sooner than a month and a half, especially if the answer is "no."

**Comment by vadz** [comment]
The interface headers are supposed to reliably represent the API, so if there is a problem with this, it should, of course, be fixed, but I just don't see it here. Why are you saying that the subclass is not documented when it (e.g. `wxMemoryFSHandler` to take an example) is? Without knowing the details it's hard to say more, but this just looks like a bug in Phoenix interface headers parsing code to me.

> In the future, it would be appreciated to have a response sooner than a month and a half, especially if the answer is "no."

I was very busy during exactly the last month and a half and didn't have time for anything non work-related at all, sorry. I do try to review PRs/patches a.s.a.p. but I can't unfortunately guarantee being always able to do it. I'm afraid I can only promise best effort, not best result.

**Comment by swt2c** [comment]
> The interface headers are supposed to reliably represent the API, so if there is a problem with this, it should, of course, be fixed, but I just don't see it here. Why are you saying that the subclass is not documented when it (e.g. wxMemoryFSHandler to take an example) is? Without knowing the details it's hard to say more, but this just looks like a bug in Phoenix interface headers parsing code to me.

Consider, say, if you compiled the interface headers as C++.  How would the compiler know to call `wxMemoryFSHandler::FindNext()` instead of `wxFilesystemHandler::FindNext()`, for example?

**Comment by vadz** [comment]
But the compiler doesn't rely on these headers. And the thing is, it really shouldn't matter to Phoenix because if you perform a virtual call to `fshandler->FindNext()` from Phoenix wrappers, where `fshandler` is of type `wxFileSystemHandler*`, it will be dispatched to the correct `wxMemoryFSHandler::FindNext()` version via C++ virtual function call mechanism.

I have no idea why it doesn't work for these classes when it clearly should work for other classes, e.g. everything derived from `wxWindow` because we definitely don't repeat all the base class methods whenever they're overridden in a derived class.  Yet calls to them still do the right thing, don't they?

So, again, what's the difference between this class hierarchy and all the other ones (because there is `wxWindow`, but also `wxSizer` and others)?

**Pull request closed without merging**
