### PR TITLE
Add wxString::utf8_string()

### PR DESCRIPTION
**Pull request by vadz**
Adding yet another conversion function is not ideal, but I think we really need this one.

As typical, I've agonized a long time over the name, but finally I think this one is not too bad. There might be some confusion with C++20 `std::u8string`, but I don't know what to do about it. Also, I don't think we need `ToStdUtf8String()`, but we could add it too if people disagree.

### CODE REVIEW

**Comment by paulcor** [comment]
Seems easily confused with the existing `utf8_str()`.

**Comment by vadz** [comment]
> Seems easily confused with the existing `utf8_str()`.

Yes, but they _are_ similar. And I just don't see a better name, do you?

Please notice that it really shouldn't be longer than that (and ideally shorter), both because it's used a lot and because if it's longer than `ToStdString(wxConvUTF8)` it wouldn't be very useful.

**Comment by vadz** [comment]
Does anybody else have a better suggestion for the name? If not, I'd like to merge it soon because I'm tired of using `ToStdString(wxConvUTF8)` everywhere in my code..

**Comment by rcane** [comment]
It is unfortunate that `utf8_str()` already exists. But I did not know about it until now. I always used `ToUTF8()` instead.
So for me `utf8_string()` would be an acceptable name for the new method.
If one actually confuses those methods at least the compiler will complain because `wxScopedCharBuffer` is not implicitly convertible to `std::string` and vice versa.

On the other hand, I could also live with:
* `utf8_std_string()`
* `to_utf8_string()`
* `string_utf8()`

But those are quite different compared to the existing style and except for the last one they are also longer.

**Comment by vadz** [comment]
`ToUTF8()` and `utf8_str()` could be used but are less efficient in `wxUSE_STL_BASED_WXSTRING` case and, maybe more importantly, don't really make it clear that we're converting to `std::string` which may be nice and makes the code more readable IMHO. Maybe `utf8_string()` isn't perfectly clear about it neither, but at least it does contain `string`...

From the others, I think only `to_utf8_string()` is acceptable, but we don't use `to_` prefix anywhere. I did consider `ToUTF8String()` but I prefer `utf8_string()` to it because it's (one character, yes) shorter and snake case naming convention is more evocative of std stuff. Also, `ToUTF8String()` seems like an alternative rather than a special case of `ToStdString()`. And `ToUTF8StdString()` is too long.

But I could live with `ToUTF8String()` or even `ToUTF8StdString()` too if nobody likes `utf8_string()`. I just want to have _something_.

**Pull request merged**
