### PR TITLE
wxAUI's FrameManager: redundant Repaint removed; Late repaint of deco…

### PR DESCRIPTION
**Pull request by valid-ptr**
…rations fixed by freezing managed window (win32, non live update only)

### CODE REVIEW

**Comment by vadz** [comment]
Sorry, here again I have no idea why are these changes needed.

Moreover, they seem to change the behaviour for Linux, where the net effect of this change seem to be to remove `Repaint(NULL)` calls without replacing them with anything else. Have you tested these changes there?

Finally, I really think we should make `wxAUI_MGR_LIVE_RESIZE` the default and only supported mode anyhow because neither Mac nor modern GTK support anything else anyhow, so modifying the code in only non-live resizing case doesn't seem to be very useful.

**Comment by valid-ptr** [comment]
> Sorry, here again I have no idea why are these changes needed.
> 
> Moreover, they seem to change the behaviour for Linux, where the net effect of this change seem to be to remove `Repaint(NULL)` calls without replacing them with anything else. Have you tested these changes there?

**Repaint** method called inside **Update** method, so it's just called twice.

> Finally, I really think we should make `wxAUI_MGR_LIVE_RESIZE` the default and only supported mode anyhow because neither Mac nor modern GTK support anything else anyhow, so modifying the code in only non-live resizing case doesn't seem to be very useful.

It's just applied under
`#ifdef __WXMSW__` => fixes windows port only

**Comment by vadz** [comment]
Hmm, indeed, after looking at the code more closely, `Repaint(NULL)` calls seem redundant. It would be better to make this change in a separate commit as this doesn't really seem related to the other change, but I agree that it makes sense, thanks.

The fact that freeze/thaw is done only for MSW is part of what bothers me. Why shouldn't we also do it under the other platforms? Any platform checks here are suspicious, as they probably indicate some difference between the platforms which it would be better to fix... Under Mac this code wouldn't do anything anyhow, as it always does live resizing, so is there a problem under Linux that led you to use `#ifdef __WXMSW__` here or did you just do it because you didn't test the behaviour under Linux at all?

**Comment by valid-ptr** [comment]
Indeed! I can test it on Win and macOS only!

**Comment by vadz** [comment]
OK, I've tested and under GTK this makes things clearly worse because the entire frame is visibly refreshed when `Thaw()` is called, so it really looks like a bad idea to do it there.

But for me wxGTK should always use live resizing anyhow, as I don't see the sash there at all...

**Comment by vadz** [comment]
Also, I couldn't see any difference between having and not having these `Freeze/Thaw()` calls in the aui sample. I wonder what exactly are you doing, so that they help? AFAICS nothing should be really repainted while drag-resizing with live resizing off.

**Comment by valid-ptr** [comment]
> Also, I couldn't see any difference between having and not having these `Freeze/Thaw()` calls in the aui sample. I wonder what exactly are you doing, so that they help?

This become visible on Windows when there are many "heavy" controls in AUI-panes. Without this patch you will see "one frame" delay AUI decorations painting (captions, sashes, tabs and others)

> AFAICS nothing should be really repainted while drag-resizing with live resizing off.

**Update** method called once on mouse release (with live resizing off)

**Comment by vadz** [comment]
I've opened #1869 which contains the changes done here and more, please let me know if that PR works for you or if you see any problems. Thanks!

**Pull request closed without merging**
