### PR TITLE
Empty list control column resizing

### PR DESCRIPTION
**Pull request by oneeyeman1**
This PR will take care of the ticket 9926.
The behaviour will be the same for both MSW and generic version (GTK/OSX).

If the control does not have any items (rows) and the user double click the column divider, the column will be resized according to AUTOSIZE_USEHEADER.

Please review and apply.

### CODE REVIEW

**Comment by vadz** [comment]
I don't understand why does this need to be done in a completely different way from the normal case, i.e. when the control does have some items. Shouldn't it be as simple as using `wxLIST_AUTOSIZE_USEHEADER` instead of `wxLIST_AUTOSIZE` wherever this happens?

**Comment by oneeyeman1** [comment]
@vadz,
> 
> I don't understand why does this need to be done in a completely different way from the normal case, i.e. when the control does have some items. Shouldn't it be as simple as using `wxLIST_AUTOSIZE_USEHEADER` instead of `wxLIST_AUTOSIZE` wherever this happens?

Because if column was creatrd with wxLIST_AUTOSIZE, and it does have some items, then double-clicking the column divider should resize it for the maximum string size.

That's the difference between wxLIST_AUTOSIZE_USEHEADER vs wxLIST_AUTOSIZE.

**Comment by vadz** [comment]
You're missing my point. I'm saying that the generic control must handle auto-sizing colukn by double clicking the divider in both cases of empty and non-empty control, it doesn't really make much sense to only do it in the former case.

**Comment by oneeyeman1** [comment]
@vadz 
> You're missing my point. I'm saying that the generic control must handle auto-sizing colukn by double clicking the divider in both cases of empty and non-empty control, it doesn't really make much sense to only do it in the former case.

Just to clarify: you suggest for generic list control to handle double click on the column divider to size the column with the wxLIST_AUTOSIZE_USEHEADER always?

**Comment by vadz** [comment]
No, it should be resized to fit the items, if any. If there are no items, then it should be resized to fit the header.

**Comment by oneeyeman1** [comment]
@vadz ,
> No, it should be resized to fit the items, if any. If there are no items, then it should be resized to fit the header.

This should probably be discussed somewhere.
The thing is that generic wxListCtrl, AFAIU, does not keep the AUTOSIZE parameter anywhere.
The SetColumnWidth() set the m_width to the actual width of the column.

The least intrusive way will probably be to have another member (something like m_autoWidth) which will be 0 by default, and which will be set inside SetColumnWidth if this call have wxLIST_AUTOSIZE constant.

Any objection to do that?
Or you see a better way?

**Comment by vadz** [comment]
I don't understand at all what are you saying... Double clicking the divider should just autosize the column immediately, there is no need to keep anything anywhere.

**Comment by oneeyeman1** [comment]
@vadz,
> I don't understand at all what are you saying... Double clicking the divider should just autosize the column immediately, there is no need to keep anything anywhere.

Generic list control does not keep the wxLIST_AUTOSIZE{_USEHEADER} option anywhere.
So in order to implement autosizing this needs to be stored at the time SetColumnWidth() is called.

When I tried to modify my code as follows:

``      else if( event.LeftDClick() && hit_border )
        {
            if( dynamic_cast<wxGenericListCtrl *>( GetParent() )->GetItemCount() == 0 )
                dynamic_cast<wxGenericListCtrl *>( GetParent() )->SetColumnWidth( m_column, wxLIST_AUTOSIZE_USEHEADER );
            else
            {
                int width = 0;
                dynamic_cast<wxGenericListCtrl *>( GetParent() )->GetColumnWidth( width );
                if( width == wxLIST_AUTOSIZE )
                    dynamic_cast<wxGenericListCtrl *>( GetParent() )->SetColumnWidth( m_column, wxLIST_AUTOSIZE_USEHEADER );
            }
        }
``

the width variable does not become wxLIST_AUTOSIZE. Its value is  an actual width.

So unless I misunderstood you again - I should store this constant (wxLIST_AUTOSIZE(XXX} somewhere.

**Comment by vadz** [comment]
I just don't know why do you think you need to store anything. Do you realize that double clicking the column divider resizes the column to fit **unconditionally**? It doesn't matter what width was used, as long as the column is resizeable (and yes, you do need to check for this), it should be resized to fit its contents (if any) or header (otherwise).

Please think about what are you trying to achieve here.

**Comment by oneeyeman1** [comment]
@vadz ,
I'm sorry for arguing.
I slept it over and fixed it.

Is there anything left here to do?

**Comment by vadz** [comment]
Thanks, looks good to me, will merge soon, after the usual style fixes.

**Pull request closed without merging**
