### PR TITLE
Add MSVS 2019 solution file

### PR DESCRIPTION
**Pull request by vadz**
The only potentially questionable commit here is the last one. I don't know why was this directory dependency added in the first place, but it results in spurious rebuilds with VC16 and removing it doesn't seem to do any harm -- but please let me know if I'm missing anything.

### CODE REVIEW

**Comment by PBfordev** [comment]
MSVS version should be probably updated also in readme.md:
> - Microsoft Visual C++ 2003 or later (up to 2017)

I wonder if just the range instead of the list of versions would be simpler in release.md, the list has grown quite large...

**Comment by vadz** [comment]
> MSVS version should be probably updated also in readme.md:
> 
> > * Microsoft Visual C++ 2003 or later (up to 2017)

Sorry, where is this? I can't find it and neither can `git grep 'up to 2017'`...
 
> I wonder if just the range instead of the list of versions would be simpler in release.md, the list has grown quite large... 

I also thought about this, but it's a bit tricky because the range of IDE versions is not contiguous (i.e. we can't say 7-16 because 13 is missing) and the range of marketing versions is even more irregular. I think it's more reassuring to see the version you use explicitly in this list. But OTOH we clearly will have to do something about its length sooner or later... For now I'm tempted to leave it as is.

> Also the list in this file will not match the actual download list on the website, but I guess it's OK...

I hope to have 2019 binaries for the next release.

**Comment by PBfordev** [comment]
MSVC 2017 in [readme.md](https://raw.githubusercontent.com/wxWidgets/wxWidgets/master/README.md) is mentioned on line 33.

Regarding the MSVS version range: sorry, I did not realize there was a version missing.

**Comment by vadz** [comment]
> MSVC 2017 in [readme.md](https://raw.githubusercontent.com/wxWidgets/wxWidgets/master/README.md) is mentioned on line 33.

Sorry, no idea how did I miss this. Will fix, thanks!

**Comment by confusedsushi** [comment]
I think project dependencies should be done inside the vcxproj files rather than in the sln files.

**Comment by vadz** [comment]
> I think project dependencies should be done inside the vcxproj files rather than in the sln files.

What do you mean? AFAIK vcxproj files can't have any dependencies.

**Comment by confusedsushi** [comment]
In my local copy I already have made these changes, here for example a snippet of `wx_base.vcxproj`

```
  <ItemGroup>
    <ProjectReference Include="wx_wxexpat.vcxproj">
      <Project>{a1a8355b-0988-528e-9cc2-b971d6266669}</Project>
    </ProjectReference>
    <ProjectReference Include="wx_wxjpeg.vcxproj">
      <Project>{6053cc38-cdee-584c-8bc8-4b000d800fc7}</Project>
    </ProjectReference>
    <ProjectReference Include="wx_wxpng.vcxproj">
      <Project>{8acc122a-ca6a-5aa6-9c97-9cdd2e533db0}</Project>
    </ProjectReference>
    <ProjectReference Include="wx_wxregex.vcxproj">
      <Project>{56a4b526-bb81-5d01-aaa9-16d23bbb169d}</Project>
    </ProjectReference>
    <ProjectReference Include="wx_wxscintilla.vcxproj">
      <Project>{74827ebd-93dc-5110-ba95-3f2ab029b6b0}</Project>
    </ProjectReference>
    <ProjectReference Include="wx_wxtiff.vcxproj">
      <Project>{75596ce6-5ae7-55c9-b890-c07b0a657a83}</Project>
    </ProjectReference>
    <ProjectReference Include="wx_wxzlib.vcxproj">
      <Project>{8b867186-a0b5-5479-b824-e176edd27c40}</Project>
    </ProjectReference>
  </ItemGroup>
```

I should prepare a pull request for that, there I can also describe my motivation for that.

**Comment by vadz** [comment]
I've added `docs/contributing/how-to-add-new-msvs-version.md`, any comments about it would be appreciated, notably please let me know if I forgot anything. If not, I'm going to merge this and #1384 soon.

TIA!

**Review by doscott — COMMENTED** [review]
Add at the end:
Update 'build/tools/msvs/officialbuild.bat', which is used to build the official binaries for a specific compiler.

**Comment by vadz** [comment]
> Add at the end:
> Update 'build/tools/msvs/officialbuild.bat', which is used to build the official binaries for a specific compiler.

Oops, thanks, I definitely was going to write this, but somehow missed it.

**Pull request closed without merging**
