### PR TITLE
CMake: Download SDK when wxUSE_WEBVIEW_EDGE=ON

### PR DESCRIPTION
**Pull request by TcT2k**
Automatically download the WebView2 SDK from nuget (official repo for the SDK)
when enabling wxUSE_WEBVIEW_EDGE to simplify usage.
Copying to 3rdparty/webview2 is still supported optionally.

### CODE REVIEW

**Comment by PBfordev** [comment]
I thought the reason for not doing this before was to make people aware of webview2 license?

**Comment by TcT2k** [comment]
> I thought the reason for not doing this before was to make people aware of webview2 license?

Im a past version I had the SDK included in the repository and enabled by default, this just makes it more convenient and license requirements are documented

**Comment by vadz** [comment]
I think that as long as this is not included in the repository itself and can be disabled, it should be fine, so I don't really have any objections to this.

To be _perfectly_ above board we could turn this off by default and output a message saying that you need to use some option (or define some variable, this being CMake...) if you agree with the licence terms. This might be slightly better but I won't insist on changing this if @TcT2k doesn't agree.

**Comment by TcT2k** [comment]
> I think that as long as this is not included in the repository itself and can be disabled, it should be fine, so I don't really have any objections to this.
> 
> To be _perfectly_ above board we could turn this off by default and output a message saying that you need to use some option (or define some variable, this being CMake...) if you agree with the licence terms. This might be slightly better but I won't insist on changing this if @TcT2k doesn't agree.

I think as it's not enabled by default we really don't need another option for a license agreement.

**Pull request merged**
