### PR TITLE
Add wxFileDialog::AddShortcut()

### PR DESCRIPTION
**Pull request by vadz**
See #22543.

### CODE REVIEW

**Comment by imciner2** [comment]
Can you expand on the reason it doesn't work with the extra control creator? Reading the documentation for the IFileDialog in MSW, it doesn't say it is an incompatibility, so I am curious if it was an issue you observed or if you found a different documentation page that explains this. (it would be good to clarify that in a comment above the if check also).

**Comment by imciner2** [comment]
> It doesn't work with the old-style control creator because it forces the use of common dialog, in which this functionality is unavailable. It works perfectly fine with the new customization hook API.

Ah, I had misread the text and thought it didn't work with any additional controls (both newer and older style), not just the old style of adding the controls. Now that I read the API docs again, I see it says to use the newer customize hook with the function and it should work.

**Comment by marekr** [comment]
I'm not setup to test this currently but it looks about what I expect.

The only thing I can think of for documentation is on Windows, the shortcuts will appear under an "Application Links" group in the  dialog, unless the user defines a VERSIONINFO section in their manifest which will cause it to use FileDescription and the app icon instead of "Application Links".

**Comment by vadz** [comment]
Yes, good point, thanks, I'll add this:
```
        @note In wxMSW, the shortcuts appear in a separate section called
            "Application Links" by default. To change the title of this
            section, the application can specify a value of the @c
            FileDescription field of the version information structure in its
            resource file -- if present, this string will be used as the
            section title.
```
to the documentation.

**Pull request merged**
