### PR TITLE
Implement wxSYS_COLOUR_HOTLIGHT on macOS

### PR DESCRIPTION
**Pull request by obfuscated**
* There is linkColor avaiable since 10.10. Just use it.
* https://developer.apple.com/documentation/appkit/nscolor/2998828-linkcolor
* https://developer.apple.com/design/human-interface-guidelines/macos/visual-design/color/

### CODE REVIEW

**Comment by vadz** [comment]
Thanks, I'll merge this unless @csomor has any objections.

**Comment by obfuscated** [comment]
I was hoping for travis to build 10.9 to see if this compiles on older versions, but I didn't have that luck :)

**Comment by csomor** [comment]
I had to dig out a xcode 8 and a system, under which it still runs first ;-) 

not using `#if MAC_OS_X_VERSION_MAX_ALLOWED ...`. gives a warning unter Xcode < 9 but the build continues 

@vadz what do you think ? I'd prefer bracketing this with the macros as elsewhere to get a warning free build, but if this seems too picky, I won't insist

**Comment by vadz** [comment]
Thanks for testing, Stefan! I definitely prefer warning-free build, I just somehow thought that using `WX_IS_MACOS_AVAILABLE` would avoid the warning, but this is not the case, of course... I've pushed a blind fix now, please let me know if this is what you meant.

Speaking of fixing things blindly, would you prefer restoring testing under older macOS versions on Travis? Currently we test under 10.10, 10.13 and 10.14, should we replace 10.13 with 10.8 or 10.9 perhaps?

**Comment by csomor** [comment]
`WX_IS_MACOS_AVAILABLE` works from Xcode 9+ exactly the way we'd need it here, but since we support lower compilers still, where it resolves to a simple runtime-os version test, we must guard for these compilers.

**Comment by obfuscated** [comment]
I saw those and wondered if they are needed. It seems they are.

On min version: I think you should test at least if it compiles correctly on the lowest version you could get on travis and it is still supported. Getting access to such old releases is pretty hard.

**Comment by csomor** [comment]
> Speaking of fixing things blindly, would you prefer restoring testing under older macOS versions on Travis? Currently we test under 10.10, 10.13 and 10.14, should we replace 10.13 with 10.8 or 10.9 perhaps?
I don't think we have a 10.9 vm on travis or earlier, do we ?

**Comment by vadz** [comment]
Oops, yes, sorry, I forgot, 10.10 is indeed the oldest they still have. They do provide Xcode as far back as 6.4, so we could try using an older version with `--with-macosx-version-min=10.8` or something like that. Should we do this?

BTW, if you ever feel like adding an entry to `.travis.yml` running the wxiOS build, it would be great as I'd really like to have it tested for the changes under `src/osx` too, but I keep not managing to find any time to do this myself...

**Comment by csomor** [comment]
> Oops, yes, sorry, I forgot, 10.10 is indeed the oldest they still have. They do provide Xcode as far back as 6.4, so we could try using an older version with `--with-macosx-version-min=10.8` or something like that. Should we do this?

yes, that's a good idea, I think we should add `--with-cxx=11` as well, I'm raising the topic of the minimum system on the list

> BTW, if you ever feel like adding an entry to `.travis.yml` running the wxiOS build, it would be great as I'd really like to have it tested for the changes under `src/osx` too, but I keep not managing to find any time to do this myself...

I'll try, I have never configured a travis build :-)

**Pull request merged**
