### PR TITLE
Remove WXSTRINGCAST and other unused macros

### PR DESCRIPTION
**Pull request by vvs31415**
These macros are not used anywhere in WX and not documented. Should be safe to remove them. If they are still used somewhere, they can be replaced with const_cast.

### CODE REVIEW

**Comment by vadz** [comment]
Sorry, we're not going to apply this. It costs absolutely nothing to keep these macro definitions and they do seem to be used by [some existing code](https://github.com/search?q=WXSTRINGCAST&type=Code).

**Comment by vvs31415** [comment]
What about rewriting them using `const_cast` ?

**Comment by vadz** [comment]
> What about rewriting them using `const_cast` ?

In Motif/X11 code -- sure, why not (but then why would anyone care about wxMotif in the first place is beyond me). In the headers -- no, this is still incompatible (think about casting from `unsigned char*`) and, again, it just isn't worth worrying about. The only useful thing to do I see here is to add a comment clearly stating that these macros shouldn't be used in the new code and only exist for compatibility.

**Comment by vvs31415** [comment]
Yes, a comment would do great. Thanks!

**Pull request closed without merging**
