### PR TITLE
Run GUI tests under Travis using xvfb-run

### PR DESCRIPTION
**Pull request by swt2c**

### CODE REVIEW

**Comment by swt2c** [comment]
Don't merge yet - let's see if this works.  :-)

**Comment by swt2c** [comment]
It seems like it is mostly working.  Some of the failures I also see when running locally, e.g, the wxPersistDVC ones.

**Comment by vadz** [comment]
Thanks for this, I hadn't realized it would be as simple as that, great!

We need to run `xvfb-run` only if it's available (i.e. not under macOS currently...) and I need to look at the test failures (some of them could be due to lack of a WM, but not all), so I won't merge it immediately but will definitely do it later, thanks again!

**Comment by swt2c** [comment]
OK.  I did find that there's a way to use xvfb on macOS, but you have to do it differently.  I'll try to update the PR.

**Comment by vadz** [comment]
@a-wi Would you have any idea about the graphics tests failures by chance? I'll probably just disable them (as well as the persistent controls ones) when running under Travis for now, but if they could be fixed, this would be even better, of course.

**Comment by a-wi** [comment]
@vadz I couldn't reproduce issues with transformation matrix tests with gcc 4.9.2 (also executed with xvfb-run) under Linux and with MinGW gcc 4.9.3 under Win. I don't know why they fail here.

**Comment by vadz** [comment]
@a-wi Thanks for looking! This looks rather mysterious and I hate mysteries, but for now we'll just have to disable them as there are just too many more higher priority things to do...

**Comment by vadz** [comment]
I ran out of time for fixing the tests failures before 3.1.2. If we still don't find the problem, we probably should just disable these tests when running under Travis, it's better than not running any other GUI tests there at all.

**Comment by swt2c** [comment]
Repushed to get a fresh test run.

**Pull request closed without merging**
