### PR TITLE
use different clipboard targets for text on Wayland

### LINKED ISSUE #24391: Pasting text from Telegram Desktop not working under Wayland
far2l (Linux port of Windows console file manager called Far Manager or FAR) is using wxWidgets for interface rendering and system clipboard interaction. Unfortunately, on Wayland systems (like Ubuntu 23.10) clipboard copy-paste is not working between far2l and Telegram Desktop.

Steps to reproduce:
1. Install Ubuntu 23.10
2. Install far2l-gui from ppa
3. Run far2l
4. Download, unpack and run Telegram Desktop
5. Copy any string from Telegram Desktop to clipboard
6. Try to paste to far2l
7. Try to copy text from any other app (for example, Firefox)
8. Try to paste to far2l

Workaround:
```
GDK_BACKEND=x11 far2l
```

Corresponding far2l issue:
https://github.com/elfmz/far2l/issues/2053

### PR DESCRIPTION
**Pull request by unxed**
Fixes #24391 (and probably #23544).

### CODE REVIEW

**Comment by unxed** [comment]
Still need some debug

**Comment by vadz** [comment]
Sorry, I didn't have time to finish my changes yet, but while I did plan to to something like this, I don't think it's the right approach for 2 reasons:

1. Checking the environment variable is not the right way to test for Wayland, this would fail in too many cases (GTK2 app running in Wayland environment, GTK3 one running with `GDK_BACKEND=x11`, GTK3 one running in `env -i`, and probably more). We have `wxGTKImpl::IsWayland()` which does it correctly, but it needs a display pointer.
2. It's not really obvious to me that we need to test for Wayland at all and, in fact, I don't think we should. Instead, we should just always accept all known text formats, I don't see any possible harm in doing this.

I wanted to do this soon, but other things came up and so I wasn't able to do it yet. If you plan to do it like this, please let me know and I'll wait until you do, otherwise I'll try to do it myself a.s.a.p., hopefully this weekend. Thanks!

**Comment by unxed** [comment]
Already fixed on our side, so you are welcome to implement this the best way possible! Thanks a lot.

**Comment by vadz** [comment]
Replaced with #24423.

**Pull request closed without merging**
