### PR TITLE
Assorted wxOSX fixes

### PR DESCRIPTION
**Pull request by vadz**
I'm sorry for the amount of non-trivial changes in this PR and very short delay before 3.1.3, but I've realized that if we were not going to change some of these things now, we're probably not going to change them for 3.2.0 neither and I just didn't want to leave them broken for basically ever. So I intend to merge this in 3.1.3 (i.e. tomorrow), unless someone objects very strenuously.

I realize that this risks breaking things, but OTOH they're broken now as well and if it turns out that the new breakage is worse, we can always revert the changes later. But I'm afraid that my usual careful approach just doesn't work for wxOSX, as I'm never going to feel qualified enough to be certain that the changes are correct anyhow.

So let's try something different...

### CODE REVIEW

**Comment by csomor** [comment]
I'll go through things, what I'm most afraid of are focus changes, could we put them into a different commit / PR ?

**Comment by vadz** [comment]
I could split the focus changes off, of course, but I'd still very much like to merge them anyhow today. Again, I realize that they can break something, but at least we'll know about it soon enough if they are part of 3.1.3 and, in the worst case, could just revert them. And in the meanwhile they do fix important bugs.

So, again, yes, I could do it, but unless you veto including them in 3.1.3, is there really any point in doing this?

**Comment by csomor** [comment]
If we have them in a separate commit, it would be easier to tell people to revert, it problems arise, and still have everything else in there, wouldn't it ?

**Comment by vadz** [comment]
But all changes already are in separate commits. Each commit is atomic, there are just several of them trying to fix different problems. And they're all part of the same PR.

**Comment by csomor** [comment]
I see, so there's no easy way to tell people to undo a certain commit, if focus problems arise, to find out whether it's a regression, they'd have to revert them individually anyway?

**Review by csomor — COMMENTED** [review]
Actually mac by default uses the wxStatusBarMac class anyway

**Review by csomor — APPROVED** [review]
I'm fine with the changes. I've tried to tackle the focus problems we had with wxPopupWindow in a different way with a flag that gets anded to subclass CanBeFocused(), we've had a discussion about that at the time. But I'm fine with anything that solves these problems hopefully without causing regressions.

**Comment by vadz** [comment]
> I see, so there's no easy way to tell people to undo a certain focus-bundle-commit,

Sorry, I'm unsure why do you say this? If the commit changing the accelerators handling (as an aside, we really need Mac-wx dictionary, if I knew that "key equivalents" were just "accelerators" earlier, so many things would have been clearer) turns out to break something, you could just `git revert 
87bba02 `, for example. How could it be any easier?

> if focus problems arise, to find out whether it's a regression, they'd have to revert them individually anyway?

Well, yes, it wouldn't make sense to revert all of these commits just because one of them breaks something.

> Actually mac by default uses the wxStatusBarMac class anyway

`wxStatusBarMac` inherits from `wxStatusBarGeneric`, so it's affected by this change (I've actually tested it but was too lazy to add a unit test, although I should have done this... OTOH with Mac GUI tests not passing, and hence not running, anyhow, there is not much motivation in doing this).

> I'm fine with the changes. I've tried to tackle the focus problems we had with wxPopupWindow in a different way with a flag that gets anded to subclass CanBeFocused(), we've had a discussion about that at the time. But I'm fine with anything that solves these problems hopefully without causing regressions.

I think `wxPopupWindow` is a whole other can of worms. I'll try to find some energy to look at it again, but I spent hours on it about a year ago without much success :-(

As for regressions, I'd be very surprised if there were none, but this is why I'm so eager to merge this now and not just before 3.2.0 -- hopefully they will be found and we'll have an opportunity to fix them like this.

Thanks for the review!

**Pull request merged**
