### PR TITLE
Fixing word wrap on OS X El Capitan with wxTextCtrl

### PR DESCRIPTION
**Pull request by ghost**
Neither of the two available flags (wxTE_DONTWRAP or wxHSCROLL) were functioning properly on OS X El Capitan.  I did not test on older versions of OS X.  These options now work to disable word wrap and enable horizontal scrolling when used along with the wxTextCtrl.

### CODE REVIEW

**Comment by vadz** [comment]
Looks good to me, thanks! The only question I have is about the use of `FLT_MAX`, it seems a bit ugly but if this is the normal/usual way of doing things under Cocoa, why not.

Could someone please test on at least one older OS X version? TIA!

**Comment by textualize** [comment]
@vadz The FLT_MAX was taken from Apple's documentation on setting up an NSTextView to scroll horizontally (bottom of this page https://developer.apple.com/library/mac/documentation/Cocoa/Conceptual/TextUILayer/Tasks/TextInScrollView.html), so I'm assuming it's correct.

I'll see if I can scrounge up an older version of OS X to test with.

**Comment by textualize** [comment]
@vadz Tested & working under OS X 10.10 (Yosemite).

**Comment by vadz** [comment]
I'm looking at the code again and I just can't convince myself that `[tv setAutoresizingMask:(NSViewWidthSizable | NSViewHeightSizable)]` is the right thing to do, especially if the existing code setting just `NSViewWidthSizable` is also correct. Why should we enable automatic _height_ resizing because `wxHSCROLL` is specified?

**Comment by discnl** [comment]
That does seem odd even though the Apple dev docs mention it (which you probably already noticed). It's also what ticket [#4022](http://trac.wxwidgets.org/ticket/4022) does, though both this PR and the patch may be inspired by the same source. I'll check if using both or only one flag makes a difference in the text sample (under at least 10.7 and 10.10) once I get rid of some of the problems on my way towards doing that.
Note that this PR is for the stable branch. It might be better if it first went into master.

**Comment by corey112358** [comment]
I think that in the original code, the NSViewWidthSizable wasn't really doing anything at all since setHorizontallyResizable was set to NO.  The vertical scrolling/resizing was working since setVerticallyResizable was set to YES.  Unfortunately the apple code seems to be about finding the correct set of options that work together, regardless of what the docs say that each option does on it's own.

**Comment by vadz** [comment]
I can't actually see any difference in behaviour with or without `NSViewHeightSizable` in the auto-resizing mask, so let me avoid adding it now, we can always do it in the future, but right now let's test just the minimal changes, backport them to 3.0 and then maybe change this more in the master later.

**Comment by corey112358** [comment]
@vadz @discnl 
I'm a little bit confused here, maybe you can clear things up for me.  It looks like in the commit that was merged, support for the wxTE_DONTWRAP flag was yanked in favor of ONLY using the wxHSCROLL flag.  If both flags are show and described on the documentation it seems like they should both be implemented in the code.

I understand refactoring the code that I submitted, and I'm fine with that, but pulling support for one of the documented flags that was in the proposed code seems like a less than optimal decision which will cause many other users future frustrations.

One of the frustrations that I am having using wxWidgets for my project is lack of implementation of features across operating systems (which I am more than willing to help fix on features that I am using), and failing silently instead of throwing some kind of "not implemented" exception, like with trying to use PositionToXY or XYToPosition with the wxTextCtrl on os x, (which i have also sent another pull request for).  It was driving me crazy not returning the correct values, or even anything close, until i dug into the code and saw that it was not implemented at all, and the documentation did not reflect this (whereas some documentation states "not implemented on whatever os").

**Comment by vadz** [comment]
I've got to run now, so very quickly: `wxTE_DONTWRAP` is just a synonym for `wxHSCROLL` so there is no need to test for both.

Unimplemented features: this definitely should be documented and, in cases when doing nothing is not an acceptable substitute (e.g. `PositionToXY()` definitely falls into this category) should even assert that it's not implemented. Unfortunately things are not always as they should be :-(

**Comment by corey112358** [comment]
@vadz, thanks for the quick reply.  I have found where/how to update the documentation that shows on the site, so I'll send PR's for updating that as well.

In the future I'll try to have the documentation & code in the same PR.

**Pull request closed without merging**
