### PR TITLE
Creating co.po localization file for Corsican

### PR DESCRIPTION
**Pull request by Patriccollu**
Hello,

I would like to contribute to this very interesting project!

That's why I translated the `wxstd.pot` template file to **Corsican (co)**.

Do I need to modify something else?

Best regards,
Patriccollu.

### CODE REVIEW

**Comment by vadz** [comment]
Thank you for your contribution!

You don't need to do anything else, I'll merge this soon (it will take some time because I need to do some post-release changes first). And I'll your name as Corsican translator to [the translations page](https://www.wxwidgets.org/about/translations/), if you don't mind.

**Comment by Patriccollu** [comment]
Hello @vadz,

Thanks a lot for your - very fast - answer!

Do you know **when** this brand new language will be distributed? With which _wxWidgets_ **version**?

Kind regards,
Patriccollu.

**Comment by vadz** [comment]
It will be included in the next wx release which should normally be 3.2.0. As for "when", this is a bit more delicate, currently we aim at releasing it on 2022-06-06 but our release dates have been known to slip in the past, so please take it with a grain of salt...

**Comment by Patriccollu** [comment]
@vadz Thanks a lot for your answer. I just noticed the 3.2.0 [Milestone](https://github.com/wxWidgets/wxWidgets/milestones).

**Pull request closed without merging**
