### PR TITLE
Wxosx staticbox fg color

### PR DESCRIPTION
**Pull request by artur-so**
The fix is ugly but succinct.
This could have been done more elegantly, but IMO would require too many changes for such a minor need.

### CODE REVIEW

**Comment by vadz** [comment]
Sorry, I'm very confused by this:

1. The PR speaks of the box _colour_, but the code changes affect its _font_. Is there a typo in the PR title?
2. More importantly, _why_ do we want to avoid changing the colour (or font) of the box? This is supposed to work, if you do it.

Could you please explain?

**Comment by artur-so** [comment]
1. No, it's not a typo, although could be poorly phrased.
2. According to the code comments in `wxStaticBox::SetFont()` (declaration and definition), the intention is to disallow changing the static box's font. I agree, the native system font looks neater. It is smaller than the default/custom font inherited from the parent window. If this behavior has been established already, I think it is still legitimate to change the label's colour.
But the colour cannot be changed separately, the operation is performed by trying to keep the font and changing colour.
Callstack:
```
#0	0x000000010b2edbf7 in wxWidgetCocoaImpl::SetFont(wxFont const&, wxColour const&, long, bool) at src/osx/cocoa/window.mm:4541
#1	0x000000010b19bca5 in wxWindow::MacUpdateControlFont() at src/osx/window_osx.cpp:496
#2	0x000000010b19bdff in wxWindow::SetForegroundColour(wxColour const&) at src/osx/window_osx.cpp:517
```
So  changing the (foreground) colour means to take the font from the wx peer (the inherited one) and apply the new colour to it. But the wx peer's font is different than the attempted native one, which is unexpected behaviour.
The PR ensures that "protect native font of box" is obeyed.
Illustration of the problem. The lower static box has its colour changed to blue. Notice the bigger font applied.
Screenshot 2020-10-17 at 23 43 11

**Comment by vadz** [comment]
Thanks for the explanations, I see the problem better now. I'm still not sure we should ignore the attempts to change the font (we could apply the new font but keep the same standard size), but I now see that this is the existing behaviour, so I won't discuss it in this PR.

But I'd still like to ask (although maybe it's more of a question for @csomor) why do we need to even try to change the font when we're only interested in setting the colour. IMO we should just overwrite `SetForegroundColour()` in `wxStaticBox` to do the right thing. Why wouldn't this work?

**Comment by artur-so** [comment]
> IMO we should just overwrite SetForegroundColour() in wxStaticBox to do the right thing.

Implemented this in a new branch [commit](https://github.com/artur-so/wxWidgets/commit/690d21b83c29af7ba0c3a7b09a337d94e09e4c8f) in my fork.
I took a conservative/minimalist approach to avoid changing the wx Cocoa interfaces by using a dummy font to avoid replacing it.
Could you have a look, please?

**Comment by vadz** [comment]
Thanks, this is better than the current PR, but I'd go further, personally. Looking at the code, the current
```
virtual void SetFont(const wxFont& font, const wxColour& foreground, long windowStyle, bool ignoreBlack = true);
```
really doesn't make any sense to me: first, nobody uses the last 2 parameters at all, so why do they even exist (I suppose they might have been used in Carbon, but this is still not a reason to keep them). And second, why combine the font and the colour? I'd add a separate `SetForegroundColour()` instead.

@csomor I could try to do this when I finally get to work under Mac, but please let me know if this approach is doomed to fail in advance for some profoundly Mac-ish reason that I ignore. TIA!

**Comment by csomor** [comment]
> Thanks, this is better than the current PR, but I'd go further, personally. Looking at the code, the current
> 
> ```
> virtual void SetFont(const wxFont& font, const wxColour& foreground, long windowStyle, bool ignoreBlack = true);
> ```
> 
> really doesn't make any sense to me: first, nobody uses the last 2 parameters at all, so why do they even exist (I suppose they might have been used in Carbon, but this is still not a reason to keep them). And second, why combine the font and the colour? I'd add a separate `SetForegroundColour()` instead.

This is a remnant from macOS Classic and Carbon, where I had to avoid common wx code interfering with the native colors which might have been different than black, and setting them to black interfered with the system default handling of disabling controls etc. Currently this is not used anymore. I'll do a PR with the removal.

**Comment by vadz** [comment]
I think this shouldn't be needed any longer, now that #2103 was merged in 4aafab47e717ea18623b1f8c978e8cb3b35d1b06, but please let me know if I'm wrong (ideally with a way of demonstrating the problem, so I could check for it myself). TIA!

**Comment by artur-so** [comment]
Hi @vadz!
The problem is still present.
It can be reproduced with the following patch to the wrapsizer sample.
```
@@ -124,8 +124,9 @@ WrapSizerFrame::WrapSizerFrame() 
     // A shaped item inside a box sizer
-    wxSizer *sizerBottom = new wxStaticBoxSizer(wxVERTICAL, m_panel,
+    wxStaticBoxSizer *sizerBottom = new wxStaticBoxSizer(wxVERTICAL, m_panel,
                                                 "With wxSHAPED item");
+    sizerBottom->GetStaticBox()->SetForegroundColour(*wxBLUE);
     wxSizer *sizerBottomBox = new wxBoxSizer(wxHORIZONTAL);
     sizerBottom->Add(sizerBottomBox, wxSizerFlags(100).Expand());
```

**Comment by vadz** [comment]
FWIW I've just tested this with the latest master under macOS 11 and it works for me, i.e. the box label is blue.

**Comment by artur-so** [comment]
@vadz, the label colour was never the problem here.
The problem is that when the colour is changed, the font also changes as noticeable in the screenshot above (bigger non-system font).

**Comment by vadz** [comment]
Sorry, you're absolutely right, of course, and I did test the wrong thing. I've now created a PR fixing the remaining problem, please see #2278.

**Pull request closed without merging**
