### PR TITLE
po: Georgian translation: update

### PR DESCRIPTION
**Pull request by NorwayFun**
Remaining strings will follow shortly

### CODE REVIEW

**Comment by vadz** [comment]
Thanks for the update, but it would probably be better to wait until you finish translating the rest of the strings and then apply all the changes at once. Please let me know if you really prefer to merge this change immediately, but if not, I'll wait until you push more changes to your branch and let me know when you're done, so that I could merge it then.

Thanks again!

**Comment by NorwayFun** [comment]
ok, will do.

**Comment by vadz** [comment]
Let's keep it open, you can just push more changes to the same branch later and I will merge all of them at once. And if you can't/don't have time to make them, I'll merge what is there now by the time of the next release.

**Comment by vadz** [comment]
@NorwayFun Is this ready to be merged now, i.e. do you plan any more changes? Thanks!

**Comment by NorwayFun** [comment]
@vadz Yep. at least, for now. You're welcome!

**Comment by vadz** [comment]
Thanks, merged now and I've also added you to the [translators list](https://www.wxwidgets.org/about/translations/), please let me know if I shouldn't have done that.

**Pull request closed without merging**
