### PR TITLE
Improve wxValidators

### PR DESCRIPTION
**Pull request by AliKet**
Will replace  #1501 and #1423

- [X] Add `wxTextEntryValidator` base class
- [X] Handle `wxEVT_TEXT_PASTE` event
- [x] Add wxValidationStatusEvent event type
- [x] Implement `wxNumValidators::IsValid()`
- [x] Update test
- [x] Update sample
- [x] Update documentation

Here is a summarization of what was done in this PR, which hopefully will help on the review process.

### 1) What type of problems/features this PR tries to address/add ?

- `wxNumValidator` may end up not accepting any value at all if ranges are involved.
see [this](https://trac.wxwidgets.org/ticket/12968#comment:27).
- Pasting invalid values shouldn't be allowed.
- It may be desirable to choose a validation method other than the default one (i.e. **interactive** or **on focus lost**). the default method is to validate only if the OK button was pressed.
- Changing, customizing or even suppressing the error message (and how they should be displayed to end user) was not possible. 

### 2) Do the changes on this PR break anything ?
Fortunately **no** (as far as I can see).

### 3) What to change to make your validators generate error events ?
Nothing, as the library takes care of generating the events for you internally. but still it's a good idea to just call `SendErrorEvent(errormsg)` in your overridden `Validate()` instead of trying to show the error message from the validator itself.

### 4) How to Bind validator events ?
With something like this:
```
    Bind(wxEVT_VALIDATE_OK, ...);
    Bind(wxEVT_VALIDATE_ERROR, ...);
```

### 5) How to make your validators interactive ?
By this call: `wxValidator::ValidateInteractively();`

### 6) How to make your validators do validation on focus lost ?
By this call: `wxValidator::ValidateOnFocusLost();`

TIA!

### CODE REVIEW

**Comment by AliKet** [comment]
@vadz sorry to bother you with this, but your comments on this helps a lot for making this PR better. thanks.

**Comment by Kvaz1r** [comment]
I tested this a bit and changes are look good to me.
Only sample under Interactive mode behave incorrectly(or at least unexpectedly) - if validation failed it is disabled "OK" button and I don't found a way to enable it back. Does it should be so?

**Comment by AliKet** [comment]
> I tested this a bit and changes are look good to me.

Thanks for testing this.

> Only sample under Interactive mode behave incorrectly(or at least unexpectedly) - if validation failed it is disabled "OK" button and I don't found a way to enable it back. Does it should be so?

Yes (either the validation is interactive or is done on focus lost) it should behave like that.
and this is how it works: while there is invalid input, the **OK** button should remain disabled.
so that the user is forced to supply valid input or just dismiss the dialog if not.
and this is just a commit I've added to validate sample in 967162d as a demonstration only.
not in the core implementation.

Thank you.

**Comment by Kvaz1r** [comment]
> while there is invalid input, the **OK** button should remain disabled.
> so that the user is forced to supply valid input or just dismiss the dialog if not.

Right. But there isn't any sense to have this dialog shown after validation if after validation there isn't way to unblock button when change from incorrect value to correct one. It's really confused.

> and this is just a commit I've added to validate sample in 967162d as a demonstration only.
> not in the core implementation.

I understand that, but sample also important. In any case thanks for fixing [12968](https://trac.wxwidgets.org/ticket/12968) and I hope this PR will be merged before next release.

**Comment by AliKet** [comment]
> Edit:
> It seems that I not clearly expressed my thought.
> 

Thank you for noticing this bug!
The thing is that `MyComboBoxValidator ` should _now_ derive from `wxTextEntryValidator`
(which makes more sense to me) instead of `wxValidator` to make the sample works correctly when not using the default validation mode.

```
diff --git a/samples/validate/validate.cpp b/samples/validate/validate.cpp
index f0ed044995..80caac4974 100644
--- a/samples/validate/validate.cpp
+++ b/samples/validate/validate.cpp
@@ -70,18 +70,25 @@ MyData::MyData()
 // MyComboBoxValidator
 // ----------------------------------------------------------------------------
 
+wxString MyComboBoxValidator::IsValid(const wxString& str) const
+{
+    // we accept any string != g_combobox_choices[1|2] !
+    if ( str == g_combobox_choices[1] ||
+         str == g_combobox_choices[2] )
+        return wxString("Invalid combo box text!");
+
+    return wxString();
+}
+
 bool MyComboBoxValidator::Validate(wxWindow *WXUNUSED(parent))
 {
     wxASSERT(GetWindow()->IsKindOf(CLASSINFO(wxComboBox)));
 
     wxComboBox* cb = (wxComboBox*)GetWindow();
-    if (cb->GetValue() == g_combobox_choices[1] ||
-        cb->GetValue() == g_combobox_choices[2])
+    const wxString errmsg = IsValid(cb->GetValue());
+    if ( !errmsg.empty() )
     {
-        // we accept any string != g_combobox_choices[1|2] !
-
-        // N.B. SendErrorEvent() could be used here instead of wxLogError()
-        wxLogError("Invalid combo box text!");
+        SendErrorEvent(errmsg);
         return false;
     }
 
diff --git a/samples/validate/validate.h b/samples/validate/validate.h
index 8a82ef6922..1c74fbcaec 100644
--- a/samples/validate/validate.h
+++ b/samples/validate/validate.h
@@ -168,7 +168,7 @@ public:
     int m_radiobox_choice;
 };
 
-class MyComboBoxValidator : public wxValidator
+class MyComboBoxValidator : public wxTextEntryValidator
 {
 public:
     MyComboBoxValidator(wxString* var) { m_var=var; }
@@ -182,6 +182,9 @@ public:
     // Called to transfer data from the window
     virtual bool TransferFromWindow() wxOVERRIDE;
 
+    // Override base class method
+    virtual wxString IsValid(const wxString& str) const wxOVERRIDE;
+
 protected:
     wxString* m_var;
 };
```
I'll update the sample with these changes (which you can apply to see the diffrence)

Again, thank you for your feedback.

**Comment by AliKet** [comment]
Replaced with #2380

**Pull request closed without merging**
