### PR TITLE
Fix for wxDatePickerCtrl focus events under GTK

### PR DESCRIPTION
**Pull request by vadz**
See the [corresponding ticket](https://trac.wxwidgets.org/ticket/18120)

### CODE REVIEW

**Comment by vadz** [comment]
@pcor Could you please have a look at fa63b7d559fcd1eade9d031bcbfce1a87424ec9d ? It seems crazy that something like this could lurk in wxGTK code for so long, but it looks like we always generated completely wrong focus loss events for a window that had gained focus due to an explicit `SetFocus()` call as they had this window itself as the window losing focus...

**Comment by vadz** [comment]
FWIW I do think the event was always wrong: when setting the focus using `SetFocus()`, pending focus was always set to this window and it was never reset. So when the window eventually lost focus, the generated event had this window itself as the "window to be focused", which _was_ wrong. It's just that most of the handlers for `wxEVT_KILL_FOCUS` ignore this event field and were not affected by this -- but `wxCompositeWindow` was.

As an aside, I have no idea what's going on with the tests on AppVeyor, they pass locally, but somehow the existing tests started to fail there after adding a new one in this PR. I'll probably have to disable the new test in the CI builds, but it's just a complete mystery to me why does this need to be done :-(

**Comment by paulcor** [comment]
> FWIW I do think the event was always wrong: when setting the focus using SetFocus(), pending focus was always set to this window and it was never reset.

Pending focus gets reset by the focus-in event handler. Which should normally happen. In fact, it's now unclear to me how a window could get a focus-out event without first getting a focus-in event. Unless it's caused by that "deferred focus" crap. Probably is. Anyway, I strengthen my assertion: _definitely not_ always wrong.

**Comment by vadz** [comment]
AFAICS calling `gtk_widget_grab_focus()` does _not_ generate `focus-in-event`. Is it supposed to?

FWIW this can be easily reproduced by running `WXTRACE=focus ./samples/widgets/widgets`, going to the date picker control page, clicking on the arrow (important!) of the control, then clicking on the main (text) part of the control itself. This should result in the messages like the following

```
13:30:55: Trace: (focus) SetFocus on wxPanel 0x0x9c3600.
13:30:55: Trace: (focus) SetFocusToChild() => first child (0x0x9a3540).
13:30:55: Trace: (focus) Setting focus to wxTextCtrl(0x7e4200)
13:30:55: Trace: (focus) handling focus_out event for wxTreeCtrl(0x882010)
13:30:55: Trace: (focus) handling focus_in event for wxTextCtrl(0x7e4200)
13:30:55: Trace: (focus) Resetting pending focus wxTextCtrl(0x7e4200) on focus set
13:30:55: Trace: (focus) Setting focus to wxGtkCalendarCtrl(0x7f17f0)
13:30:55: Trace: (focus) Setting focus to wxGtkCalendarCtrl(0x7f17f0)
13:30:58: Trace: (focus) SetFocus on wxPanel 0x0x9c3600.
13:30:58: Trace: (focus) SetFocusToChild() => first child (0x0x9a3540).
13:30:58: Trace: (focus) Setting focus to wxTextCtrl(0x7e4200)
```

Note that there is no `focus_in` event for `wxTextCtrl`. And now if you click somewhere else (or press TAB), you get

```
13:31:02: Trace: (focus) Resetting pending focus wxTextCtrl(0x7e4200) on focus loss
13:31:02: Trace: (focus) handling focus_out event for wxTextCtrl(0x7e4200)
13:31:02: Trace: (focus) handling focus_in event for wxListBox(0x8d3800)
```

Maybe there is another problem here?

**Comment by paulcor** [comment]
> Note that there is no focus_in event for wxTextCtrl.

Umm... the 5th line in your trace? Maybe you mean after clicking on it. Well, yeah, no event because it already has focus.

I think I see the problem. `SetFocus()` sets pending focus even if it already has focus.

**Comment by vadz** [comment]
Yes, I meant that there is no "focus_in" *after* setting the focus to the control, not before, of course. And I don't think it's because it already has focus: it doesn't, the focus is at calendar drop down widget instead.

Anyhow, I think I'll merge this one because it clearly improves things and I don't see any problems right now, but it doesn't mean there are none left, of course...

**Pull request merged**
