### PR TITLE
Implement wxEVT_DATAVIEW_ITEM_START_EDITING event

### PR DESCRIPTION
**Pull request by mtangoo**
Fixes #17859

### CODE REVIEW

**Comment by vadz** [comment]
Could we call `wxDataViewRendererBase::StartEditing()` here instead? This would not only send the event, but also set up things to allow `{Cancel,Finish}Editing()` to work (I didn't test it, but I think that currently they don't work under Mac neither). It would need to be tested carefully though as I'm not at all sure if it's not going to break the existing editing mechanism... Perhaps we actually need to catch [windowWillReturnFieldEditor:toObject:](https://developer.apple.com/reference/appkit/nswindowdelegate/1419416-windowwillreturnfieldeditor?language=objc) for this?

If it's too complicated, we can apply the PR in its current form, because sending event is still better than not sending it, but if we could also make the rest of the editing functionality to work as designed, it would be really great.

**Comment by vadz** [comment]
Could we call `wxDataViewRendererBase::StartEditing()` here instead? This would not only send the event, but also set up things to allow `{Cancel,Finish}Editing()` to work (I didn't test it, but I think that currently they don't work under Mac neither). It would need to be tested carefully though as I'm not at all sure if it's not going to break the existing editing mechanism... Perhaps we actually need to catch [windowWillReturnFieldEditor:toObject:](https://developer.apple.com/reference/appkit/nswindowdelegate/1419416-windowwillreturnfieldeditor?language=objc) for this?

If it's too complicated, we can apply the PR in its current form, because sending event is still better than not sending it, but if we could also make the rest of the editing functionality to work as designed, it would be really great.

P.S. Note to self: don't forget to close [the ticket](http://trac.wxwidgets.org/ticket/17859) after applying this.

**Comment by mtangoo** [comment]
>  if we could also make the rest of the editing functionality to work as designed, it would be really great.

I would love to implement but my knowledge of DVC internals is rather dim. I have tried to do what you explained but I don't know how to get base renderer. I will post my attempt which does not work so that someone who knows better can correct me. 

```cpp
-(BOOL) textShouldBeginEditing:(NSText*)textEditor
{
	wxDataViewColumn const *column = implementation->GetCurrentColumn();
	wxDataViewItem item = implementation->GetCurrentItem();
	
	//get rectangle
	wxRect rect = implementation->GetRectangle(item, column);
	
	//get renderer
	wxDataViewRenderer *renderer = column->GetRenderer(); 
	
    return renderer->StartEditing(item, rect);
}
```
>If it's too complicated, we can apply the PR in its current form, because sending event is still better than not sending it,

I have tested and it vetoes the event just fine. The issues I see with current PR is that the icons get lost after an attempt to edit the fields.  Am not sure if this is expected behavior but I expected the editor now to show up at all (see attached images)

screen shot 2017-05-14 at 8 00 07 pm
screen shot 2017-05-14 at 8 00 31 pm
screen shot 2017-05-14 at 8 00 47 pm

**Comment by mtangoo** [comment]
I have played around ObjectiveC as well as wxWidgets related code and now I have better understanding of it. I have come up with the code below where I have some things that needs review. It is working fine except for the loss of Icon when edit is vetoed.

Am not sure if it is OSX default behaviour or not.
If this code is ok, I will close this PR and make another one

```
-(BOOL) textShouldBeginEditing:(NSText*)textEditor
{	 
    currentlyEditedColumn = [self editedColumn];
    currentlyEditedRow = [self editedRow];
    
    wxDataViewItem item = wxDataViewItemFromItem([self itemAtRow:currentlyEditedRow]);

    NSTableColumn* tableColumn = [[self tableColumns] objectAtIndex:currentlyEditedColumn];
    wxDataViewColumn* const col([static_cast<wxDVCNSTableColumn*>(tableColumn) getColumnPointer]);

    wxDataViewCtrl* const dvc = implementation->GetDataViewCtrl(); 

    wxDataViewRenderer* const renderer = col->GetRenderer();

	wxRect rect = implementation->GetRectangle(item, col);
	
    if (renderer)
    {
        return renderer->StartEditing(item, rect);
    }
    return false;
}
```

**Comment by vadz** [comment]
The loss of icon is definitely not expected. I don't have time to debug this now, but this can hardly be the native behaviour...

**Comment by mtangoo** [comment]
Ok, I will find time to debug why.

**Comment by mtangoo** [comment]
>Ok, I will find time to debug why.

I believed I have invested my best but could not find the issue. My limited knowledge of ObjC just betrayed me. May be someone knowledgeable on OSX like @vadz @vslavik @csomor  et al can take a look at this issue or help point me to the right direction.

As far as my understanding of ObjC I cannot go further than this without assistance and if no one have time for that right now, you can merge this and I will update the ticket on what is fixed and what is not.

Thanks

**Comment by mtangoo** [comment]
@vslavik  @vadz  @csomor  can anyone take a look and suggest what I can do next?
Loosing Icon is really annoying and makes the app behave ugly.

I really want to solve this but as I said my knowledge of ObjC is limited

**Comment by csomor** [comment]
I'm looking at the vanishing icon problem, I see what's happening, but not yet why :-)

**Comment by csomor** [comment]
The problem to me seems to be in, `wxDataViewTreeStore::SetValue`, datavcmn.cpp line 2494 ff

```
    wxDataViewIconText data;

    data << variant;

    node->SetText( data.GetText() );
    node->SetIcon( data.GetIcon() );
```

`variant` is only containing the string, so the icon will always be null ..

**Comment by csomor** [comment]
To be precise: the loss of the icon happens anyway with the current state of dataview, even with these changes.

**Comment by mtangoo** [comment]
I will have a look at that. Do you have proposed solution right now?

**Comment by csomor** [comment]
The handler of the changed cell in osx has to be done along the lines of `wxDataViewIconTextRenderer::GetValueFromEditorCtrl` in datavgen.cpp, line 1454, there the icon value is retrieved from the old value and only the text is changed, but I'm not sure which instance types come along the handler in osx, so it'll take some time for me

**Comment by mtangoo** [comment]
I will try to check it out. Thanks for willingness to fix this one.
I will post the progress

**Comment by mtangoo** [comment]
can you post the commit so that I can update the ticket?
I will be testing right now. Thanks

**Comment by mtangoo** [comment]
#8d78887

**Comment by csomor** [comment]
sorry, yes, the icon fix is in 12d8f6919099a2c781ad022a3e93dbdb25369395

**Comment by mtangoo** [comment]
Ah thanks, am recompiling. I will report results in few minutes

**Comment by mtangoo** [comment]
So far sample works fine. Am testing my app before I close this ine

**Comment by mtangoo** [comment]
I can confirm that the icon problem is gone.
Can you review this PR to fix the event that is not being sent (the basic problem this PR was addressing before hitting this other issue)?

**Comment by csomor** [comment]
In the dataview sample for me now the editing in the fourth tab (tree) is always vetoed unless there's a custom editor, this is because the base class `wxDataViewRendererBase::StartEditing` returns false if `CreateEditorCtrl`returns NULL which is the case in OSX. If I just send the event and return NO upon vetoing, YES otherwise, all events are sent properly

**Comment by mtangoo** [comment]
>In the dataview sample for me now the editing in the fourth tab (tree) is always vetoed unless there's a custom editor

I can edit all tabs contents and none is vetoed. That is because START_EDITING event was not being sent. That was the basic issue that this PR was addressing. It's strange that your dataview sample behaves like that. Are you sure you didn't change anything yet?

**Comment by csomor** [comment]
Sorry, I meant with the changes in this PR applied

**Comment by mtangoo** [comment]
oh, I see.
Can you review it and see if you can apply it to the development version?
AFAIR, the only thing that was not working was icon issue.

**Comment by mtangoo** [comment]
Thanks @csomor  for fixing this.
This is closed by  326e8b3

**Pull request closed without merging**
