### PR TITLE
wxOSX Retina fixes: wxPropertyGrid::OnResize()

### PR DESCRIPTION
**Pull request by yenw**
Bug fix.

### CODE REVIEW

**Comment by vadz** [comment]
Thanks for the patch, but unfortunately I don't see how can this change be correct. We already have the `#ifdef __WXOSX_COCOA__` around the `scaleFactor` definition above, so, purely formally, instead of doing the change you did, we could just divide by `scaleFactor` without any platform checks. But calling `GetScaledXXX()` and dividing by scaled factor doesn't make sense neither because this applies scale factor twice: `GetScaledXXX()` is itself `GetXXX()` divided by scale factor already.

Ideally I'd like to get rid of the existing `#ifdef` here (@a-wi  any comments about this?) and we definitely shouldn't be adding more of them... So I'm closing this for now because I definitely don't want to apply it in its current state, but if you could please explain what exactly is wrong currently, we could perhaps find a better fix together. Thanks!

**Comment by yenw** [comment]
Thanks for your replay.
I think something was wrong with the wxWidgets3.1.0/samples/auidome.
I don't know how to fix it better, but the patch is work.

without_patch

**Comment by a-wi** [comment]
Your sample documenting the issue and your commit refer to the different versions of wxPG. In the sample the bitmap size is obtained through the calls to wxBitmap::GetWidth()/GetHeight() (older wxPG version) but in the commit this is done through the calls to GetScaledWidth()/GetScaledHeight() (current wxPG version).
The latter version, introduced in 3d8f9517f31f0134af8a86ee01c039fbb18281bb, should work fine.

**Comment by yenw** [comment]
I compiled the wxWidgets(Master)/samples/propgrid and find out the bug always was fixed.
Sorry for wasting a-wi's and vadz's time.

**Pull request closed without merging**
