### PR TITLE
Fix incorrect alpha rendering in wxToolBar (MSW)

### PR DESCRIPTION
**Pull request by vslavik**
`wxToolBar::Realize()` code for handling bitmaps with alpha channel was incorrectly blending them with the toolbar’s background color, resulting in much lighter appearance and broken antialiasing.

To illustrate, here’s a test image with the left half 50% gray and the right half black with 50% transparency (should be identical or almost identical):

testimage

When rendered by wxMSW on a toolbar with white background (for illustration purposes, bg color doesn’t matter), though, it’s quite different:

xbefore

That’s fixed by automatically setting the `Remap_TransparentBg` mode if bitmaps with alpha channel are used and thus not clearing the bitmap’s background. `Remap_TransparentBg` isn’t documented, but seems to be meant for this situation, so I reused it.

That’s better, but produces *another* rendering artifact that you can see well on the first icon (black smudges behind translucent pixels on antialiased edges):

after_broken

That’s typical for premultiplied vs. not premultiplied confusion, hence the rest of the commit:

after_full

### CODE REVIEW

**Comment by vadz** [comment]
Sorry, I'm quite confused by all this. First of all, I have no idea what is `Remap_TransparentBg` supposed to do (in fact, of all these options only `Remap_None` is completely clear to me), but how can not clearing the total bitmap be right? Its contents is initially undefined, so I think we do need to clear it. Perhaps we just need to make it fully transparent, i.e. zero initialize it, in case alpha is used?

I'm also not sure about reusing `Remap_TransparentBg` as a flag for using non-premultiplied alpha, in principle people could set `msw.remap` system option to it and this would change the behaviour for them.

Finally, I may be blind but I just don't see any difference between the last two screenshots. What am I missing?

**Comment by vslavik** [comment]
> First of all, I have no idea what is Remap_TransparentBg supposed to do (in fact, of all these options only Remap_None is completely clear to me),

It seems quite obvious that the purpose is to have, well, *transparent background* (judging from its name and what it does, not clearing the background, which happens to be exactly what I need too to get a transparent background)? 

But you are right that the 2nd check at line 897 of the match is wrong, if that's what you meant -- it should check for presence of alpha channel instead. Thanks!

> , but how can not clearing the total bitmap be right? Its contents is initially undefined,

Are you sure about that? The existing code clearly assumes it is initialized somehow and it was always zero-initialized in all runs I did... I would expect uninitialized data to show in such a relatively larger block of memory.

If you think it needs to be explicitly cleared, I'll do it. Means adding a `wxRawBitmap` (or worse, `wxGC`) dependency though, doesn't it, because `wxDC` can't handle colors with alpha. 

> Finally, I may be blind but I just don't see any difference between the last two screenshots. What am I missing?

See the PR's description: look at the *first* (left-most) icon. Zoom it up, see how black color is mixed in under semitransparent pixels around the edges: 

pastedgraphic-14

**Comment by vadz** [comment]
> It seems quite obvious that the purpose is to have, well, transparent background (judging from its name and what it does, not clearing the background, which happens to be exactly what I need too to get a transparent background)?

It was not really transparent though, even if the bitmap is 0-initialized, because it wasn't using alpha anyhow. I do agree that it describes your use case, but not how could it be useful before.

>> Its contents is initially undefined,
>
> Are you sure about that? 

I'm pretty sure I saw uninitialized bitmaps with "random" initial contents when debugging something or other under MSW before. I am not sure if I saw it under Windows 7 or newer version, it could have been only under XP, and I'm not sure if happened with 32bpp bitmaps or 24bpp ones. But AFAIK there is no guarantee that a new bitmap is 0-initialized and, again, it definitely did happen to not be in at least some cases... So I'd indeed use raw bitmap access to do it, for safety.

> See the PR's description: look at the first (left-most) icon

Ah, thanks, I was indeed not looking on the right icon. It's indeed very clear looking at it, thanks.

**Comment by vslavik** [comment]
Updated per your comments.

**Review by vadz — APPROVED** [review]
Thanks!

**Pull request merged**
