### PR TITLE
Reduce M1 CI builds number and add a universal build

### PR DESCRIPTION
**Pull request by vadz**
As discussed in #2336, here is an attempt to run fewer CI builds on our Mac.

### CODE REVIEW

**Comment by vadz** [comment]
Hmm, this doesn't work for 2 reasons:

1. Tests build is broken with `--disable-debug`: I'll fix this.
2. Universal executables crash when running them from configure when using `arm64e` arch. Using just `arm64` works though, so I'm going to use this, but I don't understand what is the difference between them?

**Comment by csomor** [comment]
The build from

2021-08-21 12:43:44Z: Running job: ARM C++11
2021-08-21 12:46:16Z: Job ARM C++11 completed with result: Failed

had this in the worker log

```
[2021-08-21 12:46:13Z INFO StepsRunner] Step result: Failed
[2021-08-21 12:46:13Z INFO StepsRunner] Update job result with current step result 'Failed'.
[2021-08-21 12:46:13Z INFO StepsRunner] Current state: job state = 'Failed'
[2021-08-21 12:46:13Z INFO StepsRunner] Processing step: DisplayName='Testing'
[2021-08-21 12:46:13Z INFO StepsRunner] Evaluating: (success() && (matrix.skip_testing != true))
[2021-08-21 12:46:13Z INFO StepsRunner] Expanded: (false && (matrix['skip_testing'] != true))
[2021-08-21 12:46:13Z INFO StepsRunner] Result: false
[2021-08-21 12:46:13Z INFO StepsRunner] Skipping step due to condition evaluation.
[2021-08-21 12:46:13Z INFO StepsRunner] No need for updating job result with current step result 'Skipped'.
[2021-08-21 12:46:13Z INFO StepsRunner] Current state: job state = 'Failed'
[2021-08-21 12:46:13Z INFO StepsRunner] Processing step: DisplayName='Building samples'
[2021-08-21 12:46:13Z INFO StepsRunner] Evaluating: (success() && (matrix.skip_testing != true) && (matrix.skip_gui != true) && (matrix.skip_samples != true))
[2021-08-21 12:46:13Z INFO StepsRunner] Expanded: (false && (matrix['skip_testing'] != true) && (matrix['skip_gui'] != true) && (matrix['skip_samples'] != true))
[2021-08-21 12:46:13Z INFO StepsRunner] Result: false
[2021-08-21 12:46:13Z INFO StepsRunner] Skipping step due to condition evaluation.
[2021-08-21 12:46:13Z INFO StepsRunner] No need for updating job result with current step result 'Skipped'.
[2021-08-21 12:46:13Z INFO StepsRunner] Current state: job state = 'Failed'
[2021-08-21 12:46:13Z INFO StepsRunner] Processing step: DisplayName='Installing'
[2021-08-21 12:46:13Z INFO StepsRunner] Evaluating: (success() && (matrix.skip_testing != true))
[2021-08-21 12:46:13Z INFO StepsRunner] Expanded: (false && (matrix['skip_testing'] != true))
[2021-08-21 12:46:13Z INFO StepsRunner] Result: false
[2021-08-21 12:46:13Z INFO StepsRunner] Skipping step due to condition evaluation.
[2021-08-21 12:46:13Z INFO StepsRunner] No need for updating job result with current step result 'Skipped'.
[2021-08-21 12:46:13Z INFO StepsRunner] Current state: job state = 'Failed'
[2021-08-21 12:46:13Z INFO StepsRunner] Processing step: DisplayName='Testing installation'
[2021-08-21 12:46:13Z INFO StepsRunner] Evaluating: (success() && (matrix.skip_testing != true))
[2021-08-21 12:46:13Z INFO StepsRunner] Expanded: (false && (matrix['skip_testing'] != true))
[2021-08-21 12:46:13Z INFO StepsRunner] Result: false
[2021-08-21 12:46:13Z INFO StepsRunner] Skipping step due to condition evaluation.
[2021-08-21 12:46:13Z INFO StepsRunner] No need for updating job result with current step result 'Skipped'.
[2021-08-21 12:46:13Z INFO StepsRunner] Current state: job state = 'Failed'
[2021-08-21 12:46:13Z INFO StepsRunner] Processing step: DisplayName='Post Checkout'
[2021-08-21 12:46:13Z INFO StepsRunner] Evaluating: always()
[2021-08-21 12:46:13Z INFO StepsRunner] Result: true

```

**Comment by vadz** [comment]
Sorry, I don't understand: is there something specifically wrong in this log? I.e. I understand that the job failed, but this is due to the errors when building the tests (which should hopefully be fixed now), is there anything more?

Note that using `arm64` instead of `arm64e` did fix configure failures in the universal build. I still don't understand why doesn't `arm64e` work, but I guess it's not that important...

**Comment by csomor** [comment]
> 2. Universal executables crash when running them from configure when using `arm64e` arch. Using just `arm64` works though, so I'm going to use this, but I don't understand what is the difference between them?

https://developer.apple.com/documentation/apple-silicon/building-a-universal-macos-binary

has only listed arm64, so perhaps there's some internal tool that is looking for arm64 precisely ?

**Comment by csomor** [comment]
> Sorry, I don't understand: is there something specifically wrong in this log? I.e. I understand that the job failed, but this is due to the errors when building the tests (which should hopefully be fixed now), is there anything more?

so, sorry, I thought this might help you with comparing the timestamps from the runner with the ones from the log, but I guess that was not necessary anyway ...

**Comment by vadz** [comment]
OK, this finally seems to work, but now I'd like to add the use of ASAN, while I'm at it.

**Comment by vadz** [comment]
Hmm, I wonder why ignoring `.github/workflows/ci_mac_selfhosted.yml` in the other workflows doesn't seem to work: pushing the latest commit still triggered the reruns of the other workflows. Could it be because it uses the master version of those? I hope this is the case because otherwise I don't understand how to avoid the unnecessary rebuilds...

**Comment by csomor** [comment]
> Hmm, I wonder why ignoring `.github/workflows/ci_mac_selfhosted.yml` in the other workflows doesn't seem to work: pushing the latest commit still triggered the reruns of the other workflows. Could it be because it uses the master version of those? I hope this is the case because otherwise I don't understand how to avoid the unnecessary rebuilds...

I'd think you'll have to push those changes to master, not ? otherwise the 'old' ci.yml still has every right to trigger .. at least for the PR sync situation ?

**Comment by vadz** [comment]
Let's see if it works now that I've merged this branch.

**Comment by csomor** [comment]
@vadz I've switched the runners to be a service as instructed in the docs, and now one test fails, I have no idea whiy ...

```
DirTestCase
  DirExists
-------------------------------------------------------------------------------
./file/dir.cpp:37
...............................................................................

./file/dir.cpp:229: FAILED:
  REQUIRE( testData[n].shouldExist == d.IsOpened() )
with expansion:
  true == false
```

**Comment by vadz** [comment]
The problem is that the test doesn't even say for which directory it fails. I've created #2482 which should provide this information, but I don't know if the CI run for it will use the new setup with runners as a service.

**Comment by csomor** [comment]
I can switch things manually on the MacStadium Mac. Right now it's running as service.

**Comment by vadz** [comment]
OK, it indeed failed with this error, but not we see that it's given for `/Users/xcodeserver/Documents` directory.

Does the service run as this user? It looks like it might not have the rights to open this directory?

**Comment by csomor** [comment]
according to the plist it should do so

**Comment by csomor** [comment]
we might have the nightmare of security rights under BigSur, I'll try to find out about this ...

**Comment by csomor** [comment]
Ok, it's like so indeed, the access to the Documents folder is restricted, I've given access to it manually to the Terminal, but I don't know exactly how to do so for the service runner

**Comment by csomor** [comment]
The Folders Documents, Desktop and Downloads are special folders which we don't seem to have proper access, perhaps GetUserDataDir would be better resolves to Home/Library/Application Support ?

**Comment by vadz** [comment]
> The Folders Documents, Desktop and Downloads are special folders which we don't seem to have proper access, perhaps GetUserDataDir would be better resolves to Home/Library/Application Support ?

I don't know if we really want to do this, as it might mean the existing applications wouldn't find/show their files any longer. OTOH if they can't have access to them anyhow (is this really correct?), then it still might be the right thing to do.

We could, of course, use a different directory in the test. Do we still have access to `GetUserConfigDir()` for example?

**Comment by csomor** [comment]
> > The Folders Documents, Desktop and Downloads are special folders which we don't seem to have proper access, perhaps GetUserDataDir would be better resolves to Home/Library/Application Support ?
> 
> I don't know if we really want to do this, as it might mean the existing applications wouldn't find/show their files any longer. OTOH if they can't have access to them anyhow (is this really correct?), then it still might be the right thing to do.

they can, but either they declare it in their entitlements that they need this access, or they will get a security message the first time they run it

> We could, of course, use a different directory in the test. Do we still have access to `GetUserConfigDir()` for example?

I think, both `GetUserConfigDir()` and `GetUserDataDir()` should be fine

**Comment by csomor** [comment]
I'll try whether I can give more rights to launchd

**Comment by csomor** [comment]
Ok, this seems to have worked ... thanks for helping me

**Comment by vadz** [comment]
Thanks for fixing it and I'll switch to using `.GetUserDataDir()` in the test.

**Comment by vadz** [comment]
> Thanks for fixing it and I'll switch to using `.GetUserDataDir()` in the test.

Oops, no, I won't, because this directory doesn't exist by default, so the test would fail.

**Pull request merged**
