### PR TITLE
Add word 'be' for consistency of error message

### PR DESCRIPTION
**Pull request by dvertx**
No real change, just a typo fix of latest edit.

### CODE REVIEW

**Comment by vadz** [comment]
Oops, sorry about this and thanks for noticing and fixing it!

**Comment by dvertx** [comment]
@vads I'm not sure why this PR removes `runstatedir` and related funtions

**Comment by vadz** [comment]
This is due to a difference in autoconf version. It doesn't really matter, but I rerun autoconf when merging changes to configure anyhow, to always use the same version for consistency.

**Comment by VADS** [comment]
I have no idea what this is but hello :D

**Comment by vadz** [comment]
> I have no idea what this is but hello :D

That was a typo, hello to you, my almost namesake :-)

**Pull request closed without merging**
