### PR TITLE
Fix Ticket #19023 and align wxSetlocale() with macOS (Big Sure)

### PR DESCRIPTION
**Pull request by KaiZin2018**
macOS is dealing LC_ALL as default by "C/UFT-8/C/C/C/C". Adapt wxSetlocale() and wxLocale::Init() to follow the macOS kind of LC_ALL setting.

This fix will solve ticket #19023.

### CODE REVIEW

**Comment by vadz** [comment]
Thanks, but I still have no idea what's going on here and I'd like to test this myself before merging.

Is there any way to test for the locale setting problem other than using your modified internat sample? Because I'm almost sure that radio/check menu item problem is something completely different, or at least something else and there should be a simpler way to check for the problem with `wxSetlocale()`...

**Comment by KaiZin2018** [comment]
I do not have any idea different than using adapted internat example. Should I check in this one as well? I recognized the problem by development of pwsafe, also to be found in github, but to complex to be used as test example.

**Comment by vadz** [comment]
OK, I'll try to debug this myself but it will take at least a few days.

By an interesting coincidence, I tried building pwsafe with wx 3.1 recently (in December I think) but didn't get far because it didn't have the projects for MSVS 2019 (I've created those....) and requires Xerces (why can't it use MS XML with wx?) and I ran out of time. How do you build it?

**Comment by KaiZin2018** [comment]
The pwSafe project allow usage of MS XML, by setting the parameter USE_XML_LIBRARY to  MSXML. I never have generated the windows version - only the Mac OS one is done by myself. In that way I do not know where to set the value. I have seen one vcxproj (src/core/core_wx-15.vcxproj) having set to XERCES while all other vcxproj is setting to MSXML, but I do not know the building process for windows version in detail.
Take the time you are needing. A different fixing is no problem for me - I only want to have the problem fixed.

**Comment by vadz** [comment]
Sorry, but this isn't really a fix. This just doesn't set the `LC_NUMERIC` component of the locale at all (leaving it as "C"), meaning that the numbers are not formatted correctly any longer, so it's not really a solution. Unfortunately I don't know how could we actually solve this, but this is not much better than simply not setting locale at all in the first place, basically, so we shouldn't apply it.

**Pull request closed without merging**
