### PR TITLE
Check for wx data view list store

### PR DESCRIPTION
**Pull request by Kvaz1r**
re-work for #685 and update documentation.

### CODE REVIEW

**Comment by vadz** [comment]
Hmm, I finally wonder if it's really a good idea. I decided to add a test for the new behaviour to the sample before merging it by applying this patch:

```diff
diff --git a/samples/dataview/dataview.cpp b/samples/dataview/dataview.cpp
index a53b1c7be3..81bede1340 100644
--- a/samples/dataview/dataview.cpp
+++ b/samples/dataview/dataview.cpp
@@ -762,7 +762,10 @@ void MyFrame::BuildDataViewCtrl(wxPanel* parent, unsigned int nPanel, unsigned l
                 data.clear();
                 data.push_back( (i%3) == 0 );
                 data.push_back( wxString::Format("row %d", i) );
-                data.push_back( long(5*i) );
+                // It is possible to specify fewer values then necessary, test
+                // that it works for the last column.
+                if ( i != 9 )
+                    data.push_back( long(5*i) );

                 lc->AppendItem( data );
             }
```

and, unfortunately, this results in an assert ("Could not convert to a long") and a crash on sample startup. So it is actually rather dangerous to allow doing this and I'm not sure if we still want to do it.

Any other opinions?

**Comment by vadz** [comment]
FWIW, my slightly updated version of this PR is [here](https://github.com/vadz/wxWidgets/tree/PR696-fewer-values-datalist).

**Comment by Kvaz1r** [comment]
@vadz,  interesting. I will try to understand reasons crash in this test and think about better solution(maybe expanding vector but with default value for column type, maybe condition for size, maybe exception, maybe something else because I really want everything except UB or at least the description in the documentation for the methods {Add,Insert,Insert}item in wxDataViewListCtrl), so please don't close this PR now. 

But it seems that this class has significantly more important problem, which incompletely describeв in ticket [17446](https://trac.wxwidgets.org/ticket/17446). Storage doesn't update when sorting at all. 
So not only [RowToItem/1](https://github.com/wxWidgets/wxWidgets/blob/9f4f075034061d3762ea48780a641fa4210ca0be/include/wx/dataview.h#L1095) return "old" value (but protected [GetRowByItem/1](https://github.com/wxWidgets/wxWidgets/blob/9f4f075034061d3762ea48780a641fa4210ca0be/include/wx/generic/dataview.h#L296) return "new"), but even {Get/Set}Value methods work with "old" value and ignoring sorting. 
I am not sure which indexation really true(that which is visible(dynamic?), or the sequence in which they were added(static) in storage) and why they different, but it really confused me and may be related to this issue.

**Comment by Kvaz1r** [comment]
@vadz , what about this way? 

```
bool AppendItem( const wxVector<wxVariant> &values, wxUIntPtr data = 0 )
{
    wxDataViewListStore *store = GetStore();
    if(values.size() != store->GetColumnCount())
        return false;

    store->AppendItem( values, data );
    return true;
}
```
and same for PrependItem and InsertItem. 

Or even make new private function for avoiding code duplication(although I am not sure about naming): 

```
bool CheckLen(const wxVector<wxVariant> &values)
{
    return values.size() == GetStore()->GetColumnCount();
}
```
and corresponding call 
```
bool PrependItem( const wxVector<wxVariant> &values, wxUIntPtr data = 0 )
{
    if(!CheckLen(values))
        return false;

    GetStore()->PrependItem( values, data );
    return true;
}
```

if this approach is suitable - I'll update the PR (code and documentation).

**Comment by vadz** [comment]
Well, this wouldn't implement the original purpose of allowing to specify fewer items at all, so from this point of view, it's not really a solution. But if we abandon this goal, then I agree that we need to add such checks, although I'd rather make them assertion failures to allow the programmer to find the problem easier:

    wxCHECK_RET( values.size() == GetColumnCount(), "wrong number of values" );

**Comment by Kvaz1r** [comment]
> Well, this wouldn't implement the original purpose of allowing to specify fewer items at all, so from this point of view, it's not really a solution.

Sorry, I guess it was misunderstanding my single goal - avoid hidden out of range when appending wrong values by any means :) 

Yes, it seems like the best solution - I just don't knew about this very useful macro. So, I need just add this lines in new commit or should reset old ?

**Comment by vadz** [comment]
The current changes don't seem to be useful, so it's probably best to create yet another PR instead. TIA!

**Pull request closed without merging**
