### PR TITLE
Update locale list and fix issue #23419

### PR DESCRIPTION
**Pull request by utelle**
The list of known languages/locales is updated to match the list of known locales in Windows 11. Additionally, the bugs mentioned in issue #23419 are fixed, except the native descriptions of Northern Luri (Luri translations of the territories are not known).

### CODE REVIEW

**Comment by vadz** [comment]
Great, thanks!

Would it be possible to add the (sources of the) program you used to regenerate these files somewhere to the repository too to allow someone else doing this later?

Also, in principle, this should be backported to 3.2, but the new constants would have to be inside `wxABI_VERSION` checks there and I'm not really sure it's worth adding them... Opinions?

**Comment by utelle** [comment]
> Would it be possible to add the (sources of the) program you used to regenerate these files somewhere to the repository too to allow someone else doing this later?

In principle, yes. However, at the moment the regeneration process consists of quite a number of steps with various tools on a Windows platform:

1. Generate a textfile with a list of locales supported by Windows 11. This is done with a small wxWidgets based program.
2. Retrieve data files from various sources (mainly from the Unicode CLDR repository), for example, ISO codes for languages and countries. This is curently done manually.
3. Convert the text based data files from step 1 and 2 to SQL. This is done by a number of Lua scripts.
4. Import the SQL generated in step 3 into a SQLite database. This is done with a SQLite shell.
5. Generate the files `langtabl.txt` and `scripttabl.txt`. This is done with a SQLite shell.
6. Update the wxWidgets source files with the Python script `genlang.py` using the files generated in step 5.

Steps 3, 4, and 5 are called from a Windows batch file. Especially in step 5 one can get errors - mainly due to name clashes with generated symbols (`wxLANGUAGE_*`). These have to be resolved manually by adjusting a Lua and/or SQL script (and sometimes the Python script `genlang.py` if new synonyms have to be created), before step 6 can be executed.

The whole process is quite complex, because we need to keep compatibility with prior wxWidgets versions.

> Also, in principle, this should be backported to 3.2, but the new constants would have to be inside `wxABI_VERSION` checks there and I'm not really sure it's worth adding them... Opinions?

Well, IMHO I would not backport these changes to 3.2 - at least not in full. The bugs discovered in #23419 are all minor and affect only rather exotic locales.

Nevertheless, I could provide an adjusted file `langtabl.txt` that does not add any new constants, but only fixes bugs like wrong layout direction. This file could then be used to regenerate the dependent source files for 3.2 with the Python script `genlang.py` of 3.2.

**Comment by vadz** [comment]
I think it would be nice to add the sources of (1) to the repository, as at least this can't (realistically) be done manually. As for the other steps, maybe just documenting them in (the existing) README would be enough? TIA!

Concerning 3.2, I'm fine with not backporting anything to it, but if anybody is motivated to make a PR applying some fixes to the files there, I'm also fine with merging it.

**Comment by utelle** [comment]
> I think it would be nice to add the sources of (1) to the repository, as at least this can't (realistically) be done manually. As for the other steps, maybe just documenting them in (the existing) README would be enough? TIA!

I will try to streamline the process. Actually, I currently use the process for more than just generating `langtabl.txt`. For some of my applications I need translations of language, country, and currency names, and I generate .po files from data gathered from Unicode CLDR data.

I agree that the process of regenerating `langtabl.txt` should be at least documented within the wxWidgets repository. I will do that, but it will take some time. However, that shouldn't be a problem, now that the files are updated.

> Concerning 3.2, I'm fine with not backporting anything to it, but if anybody is motivated to make a PR applying some fixes to the files there, I'm also fine with merging it.

I suppose _anybody_ will mean _me_. I will look into the issue, but I won't promise anything yet.

**Comment by vadz** [comment]
> > I think it would be nice to add the sources of (1) to the repository, as at least this can't (realistically) be done manually. As for the other steps, maybe just documenting them in (the existing) README would be enough? TIA!
> 
> I will try to streamline the process.

TIA!

> I agree that the process of regenerating `langtabl.txt` should be at least documented within the wxWidgets repository. I will do that, but it will take some time. However, that shouldn't be a problem, now that the files are updated.

Sure, I'll still merge this, of course.
 
> > Concerning 3.2, I'm fine with not backporting anything to it, but if anybody is motivated to make a PR applying some fixes to the files there, I'm also fine with merging it.
> 
> I suppose _anybody_ will mean _me_.

Not necessarily! It might be you or @BrianNixon who has reported the original problem or anybody actually using these languages (small chance of this happening, I think, but who knows...).

**Comment by utelle** [comment]
> > > Concerning 3.2, I'm fine with not backporting anything to it, but if anybody is motivated to make a PR applying some fixes to the files there, I'm also fine with merging it.
> > 
> > I suppose _anybody_ will mean _me_.
> 
> Not necessarily! It might be you or @BrianNixon who has reported the original problem or anybody actually using these languages (small chance of this happening, I think, but who knows...).

In the meantime I already updated the file `langtabl.txt` for 3.2 locally. I assume that changes should be applied to the branch `3.2`. My wxWidgets fork does not contain that branch, so I have to find out how to get that branch into my repository.

**Comment by utelle** [comment]
I created PR #23430 to backport the bug fixes without adding new language constants.

**Pull request closed without merging**
