### PR TITLE
[wxGtk] After a call to wxTextCtrl::WriteText() scroll to cursor was broken

### PR DESCRIPTION
**Pull request by AliKet**
See this ticket [#18864](https://trac.wxwidgets.org/ticket/18864#comment:10)

N.B. I tested this PR against GTK3 only !!

### CODE REVIEW

**Comment by paulcor** [comment]
The problem with this approach is it will override any positioning that is done following the `WriteText()`. Additionally, you can't just remove the code checking for the thumb position, it's there for a reason.

**Comment by AliKet** [comment]
> The problem with this approach is it will override any positioning that is done following the `WriteText()`.

Sorry i couldn't see a better approach to the problem other than deferring the scrolling until the calculation and incremental validation of the `GtkTextView`'s layout has finished.

So, unless someone come up with a better solution, how about making this PR less evil by cancelling the pending scrolling as soon as another function triggering scrolling is called right after a `WriteText()` call ? for ex.: calling `SetInsertionPoint(0)` right after `WriteText()` will behave expectedly, i.e. no scrolling will take place at all. what do you think ?

Please let me know if i'm missing something obvious or what i am just said is not clear enough.

TIA!

> Additionally, you can't just remove the code checking for the thumb position, it's there for a reason.

My fault, restored now. thank you.

**Comment by AliKet** [comment]
@paulcor @vadz  Okay, let's see if I got things right here!

TIA.

**Comment by paulcor** [comment]
Yes, I've already thought of all this. My opinion is it risks causing a worse problem than the one it's trying to solve. I can still see flaws in this patch, but I am reluctant to point them out, as I don't really want to encourage putting more work into this.

**Comment by vadz** [comment]
@paulcor Could we provide some way allowing to apply this workaround at the user (i.e. application) level? Or is it already possible somehow? If so, IMO it would be enough to document, or at least mention, it somewhere.

In any case, I guess this PR should be closed then, or do you intend to take anything from it?

**Comment by AliKet** [comment]
I forgot to mention that **if the written string is less than or equal to 2400 bytes in size then everything works correctly**. maybe we should document this as GTK limitation and close this PR ?

Regards.

**Comment by paulcor** [comment]
> if the written string is less than or equal to 2400 bytes in size then everything works correctly

As I have seen no evidence of such a specific limitation in the GTK sources, I suspect this is a manifestation of the behavior I described in #18864: the problem won't occur if you add fewer lines than twice what will fit in the window.

I'm working on a variation of the "delayed scroll" idea that might be acceptable, so I'm going to close this.

**Pull request closed without merging**
