### PR TITLE
Update libjpeg to version 9.0b

### PR DESCRIPTION
**Pull request by MaartenBent**
I had a go at updating libjpeg. 

I used the following steps:
* Replaced the content of the jpeg folder with the latest release (kept the config file).
* Rebaked the project files: three jpeg sources added, three removed.
* Reapplied custom changes to the libjpeg sources and committed them.

### CODE REVIEW

**Comment by vadz** [comment]
Thanks for this update (and that of libtiff too). I didn't have time to look at this yet, but, as with libpng, I wonder if we could switch to using git submodules to make future updates as simple as "git merge".

It would also be very useful to have the instructions to follow when upgrading these libraries, either in `docs/contributing/how-to-update-third-party-library.md` or in some `README_wx` file in the library directory itself.

**Comment by MaartenBent** [comment]
Yes, submodules would be ideal here. I guess also for expat, zlib and scintilla. Though not all seem to have official git repos.

I'll add the update instructions to the doc (same for tiff PR).

**Comment by MaartenBent** [comment]
Updated the doc. Most of the doc is very out of date and referencing svn. But this can be updated when using submodules (which I'm testing [here](https://github.com/MaartenBent/wxWidgets/tree/submodules)).

**Comment by vadz** [comment]
Thanks again, I've reused your commit changing bakefiles and project files as part of #602, so I think this one can be closed now.

**Pull request closed without merging**
