### PR TITLE
Avoid conversion to Tm struct and back when changing the time

### PR DESCRIPTION
**Pull request by stbrowne**
Avoid conversion to Tm struct and back when changing the time to fix issues with the wrong hour being used due to DST ambiguity for the hour. Modified Add(wxDateDiff) to keep the correct hour if current time is an ambiguous hour because of DST. Added unit tests for this.

Basically I ran into this issue with some code that was simply calling SetMinute(0) and SetSecond(0) the hour was originally the first 1am prior to DST and then after the calls it jumped to the second 1am after DST which is unexpected. So this pull request basically attempts to eliminate the ambiguity except in the case of SetHour(). If you call SetHour(1) when there are 2 1am's then there's not much we can do to guess what you intended.

I think the only questionable thing here is that you could technically call the Set functions with a value outside of the expected range (ie 0-60 for minutes/seconds and 1-whatever for days). I could definitely add checks in there to avoid this. I should probably see what converting to a Tm did in those cases and try to mimic that behavior.

### CODE REVIEW

**Comment by vadz** [comment]
Thanks, I'll try to look at this a.s.a.p. but I need to be more fresh than I'm now to think about DST.

I wonder if this has any bearing on [this bug](http://trac.wxwidgets.org/ticket/15370) or would this be too much to hope for?

**Comment by stbrowne** [comment]
I don't think the two are related. This particular issue only comes into play on dates that have 2 of the same hour because it can't be represented in a struct tm. So because of that converting to a struct tm and back to wxDateTime loses some precision. You do have me curious about that ticket though. Maybe I'll take a look when I get some time.

**Comment by stbrowne** [comment]
I switched my timezone to BST and as far as I can tell the TestTimeJDN and TestTimeTicks failures are due to the way MakeTimezone and MakeFromTimezone work. If secsDiff is 0 meaning the two timezones have the same offset then it doesn't account for DST. This is actually a change from 2.8 that caused us some issues on upgrade, but for different reasons. The problem is those tests are converting from BST to GMT which both have an offset of 0. However, BST observes DST and UTC obviously does not. Basically that logic only makes sense if both timezones either observe DST or not, but if only one does you end up with errors like this.

I'm not sure what the right solution is. I'm sure that logic changed for a reason and changing it back is going to break code relying on that behavior again now. It seems to me like there is a perfectly good bool passed in for this, that should have been used from the beginning though. Perhaps the only real right thing to do is handle this specifically in the FromUTC/GMT, ToUTC/GMT, etc functions.

**Comment by stbrowne** [comment]
So after testing the previous behavior with new behavior SetHour, SetMinute, SetSecond, etc previously would leave the wxDateTime invalid if you passed in an invalid value (ie SetSecond(120)). The new behavior matches the current behavior of SetMillisecond where if you called SetMillisecond(2000) it would advance the wxDateTime 2 seconds and still be valid. So the SetSecond example would advance it 2 minutes.

I could modify these to be more consistent with the current behavior by doing some basic range checking, asserting, and making it invalid. For seconds it would probably be safer to include 61 as a valid second value as is done elsewhere to account for leap seconds. Other places allow for 61, but I think this is a mistake and should really be 60?

**Comment by vadz** [comment]
It took me a long, long time to get back to this "a.s.a.p.", but I finally did and, surprisingly, I can't see the problem any more, i.e. the test (see the commit referencing this PR) passes without any other changes. I wonder what exactly is going on here, could this be accidentally fixed by f6d9d7962e? In any case, I'm not going to apply the other changes for now, but will definitely keep the test to ensure that it doesn't get broken again.

Please reopen if you think these changes still need to be done. TIA!

**Comment by vadz** [comment]
Oops, the tests do [fall on buildbot](http://buildbot.tt-solutions.com/wx/builders/wxGTK-STL-Linux-i686/builds/1498/steps/test/logs/stdio) even if they pass locally.

**Comment by vadz** [comment]
These failures are due to `IsDST()` returning false for the DST end date itself, which definitely looks like a bug (but why does it only happen on buildbot machines and not here?), but doesn't seem directly relevant to this change, so I'm closing this again, sorry for all the notifications.

**Pull request closed without merging**
