### PR TITLE
Build more toolkits with Travis CI

### PR DESCRIPTION
**Pull request by MaartenBent**
Use Travis CI to build the `wxX11`, `wxDFB`, `wxMotif` and `wxQT` toolkits, `gtk1` toolkit is not available.

This could be cherry-picked into https://github.com/wxWidgets/wxWidgets/pull/919 to simplify testing. But first see if it passes `configure` stage.

### CODE REVIEW

**Comment by vadz** [comment]
Thanks, will do (cherry pick it, that is)!

**Comment by vadz** [comment]
All ports seem to pass configure, but if you still have time for this (while I'm stuck with the other PR, whose TODO list grows much faster than I check off items from it...), could you please also build just `core` (and base, of course) for the 3rd tier ports (i.e. DirectFB, Motif and maybe X11 too, unless we consider it 2nd tier) and, for all of them, build just the minimal sample, i.e. skip `make samples`?

This is just because I don't think it's worth rebuilding all the generic code in the other libraries and samples with these ports as it almost surely doesn't build anyhow (due to missing functionality) and it would be a waste of time to rebuild it even if it did.

OTOH it would be great to also add wxQt build to Appveyor (especially once #867 gets merged too).

Thanks again!

**Comment by MaartenBent** [comment]
Like this, or are there better configure options? I also enabled pch, maybe it speeds things up.

I can have a look at QT (and maybe GTK) in AppVeyor once that PR is merged.

**Comment by vadz** [comment]
Thank you! I think these options are fine, but I also thought doing `make wxcore` instead of just `make`. Not sure if there is really going to be a big difference with most of the rest turned off though.

Anyhow, I really need to fix the build of all these ports before going further. Thanks again for your help!

**Comment by vadz** [comment]
If you could please look again at this one now that #919 is merged, it would be great, TIA!

**Comment by MaartenBent** [comment]
@vadz Still some font errors. Can you fix these? You can push to this PR if you like.
DFB: https://travis-ci.org/wxWidgets/wxWidgets/jobs/429938225#L1481
QT: https://travis-ci.org/wxWidgets/wxWidgets/jobs/429938227#L1694

**Comment by vadz** [comment]
For QT it's apparently a version problem as these constants definitely exist in QT 5 (see [the docs](http://doc.qt.io/qt-5/qfont.html#Weight-enum)). Do you know which version of QT is used on Travis (we really should output this in our configure log...)?

For DFB it's a real bug, sorry. Fixed in d355af3420.

**Comment by vadz** [comment]
I've just used the brute force approach instead. Let's see if it works...

**Comment by MaartenBent** [comment]
Thanks. I'll fix building the tests later (looks like it is missing `wxHAS_RAW_BITMAP` guard). I doubt all tests will pass, so I'll probably allow failures on these tests, or not run them at all.

I also noticed that `BitmapTestCase::Mask` has no checks or asserts.

**Comment by vadz** [comment]
I think `BitmapTestCase::Mask()` just checks that it doesn't crash. I.e. we could put it inside `REQUIRE_NOTHROW()` to let CATCH count it as a test.

And yes, I'm pretty sure that not all GUI tests will pass. It's probably useless to even run them for DFB, but we arguably should do it for Qt to let people who want to work on it see the result of their improvements.

**Comment by MaartenBent** [comment]
@vadz would you be able to regenerate the buildfiles after the `files.bkl` modification?
After this I managed to build and link minimal without errors in `wxDFB`.

**Comment by vadz** [comment]
I've done this now (I'm leaving it to you to squash the last 2 commits as I didn't want to force push into your branch), but from Travis logs it looks like there are a few errors due to missing `wxRegion` and `wxColour` ctors in wxDFB. I'm not at all implying that you should fix them, but we probably should skip building the tests for it then?

**Comment by MaartenBent** [comment]
Thanks, but shouldn't it update `Makefile.in`?
I updated it manually for now, but I don't know if other files have to be updated as well.

**Comment by vadz** [comment]
Oops, sorry, as `./build/upmake` didn't update `files.bkl` (because it had already been updated manually...), I forgot to rerun bakefile. Done now.

Should I merge this (after squashing the commits)?

**Comment by MaartenBent** [comment]
I will squash and revert some temporary commits. After that, you can merge.

**Comment by vadz** [comment]
I have no idea about what's going on with `samples/dialogs/Makefile.in` and why does bakefile decide to always include this file :-(

I'll merge this one nevertheless as it doesn't seem to be related, but we need to fix the other problem as otherwise the build will be broken the next time all the makefiles are rebaked...

Anyhow, thanks again for your work on this!

**Pull request merged**
