### PR TITLE
Fix AUI Themed Sash

### PR DESCRIPTION
**Pull request by alilie**
The adornment doesn't get applied to dark theme. Fixed by using proper theme flag. With this flag the sash follows OS theme and the
adornment is drawn.

### CODE REVIEW

**Comment by vadz** [comment]
Thanks, from my point of view using `kHIThemeSplitterAdornmentMetal` definitely looks like a better idea than what c6523f016e (Dark Mode Patches, 2018-06-21) did here, but the latter was applied by @csomor who knows infinitely more than I do about Cocoa API, so I wonder if there could have been some reason to avoid it here. Notably, is this fine to use on pre 10.14 systems that we still support?

**Comment by csomor** [comment]
Thanks, interesting idea, I wouldn't have thought that metal could have this meaning under Dark Mode, on pre 10.14 we'd have to test whether the window is metal as we do in renderer.cpp I guess... I'll have a look at this...

**Comment by csomor** [comment]
Under 12.4 `kHIThemeSplitterAdornmentNone` gives the correct white divider when drawn horizontally, but a grey divider with an incorrectly oriented knob when drawn vertically. Under Dark Mode the horizontal divider still is white, while the vertical one is black, but still with the wrong knob. Actually I like the white divider better, it also conforms to the 'wide' divider from the GUI guidelines, but since it does not really work for anything than light mode and horizontally, I'd prefer `kHIThemeSplitterAdornmentMetal` to this, and it gives us the knob for free, with a simpler code. I'll check on earlier systems know to see whether the findings match.

**Comment by csomor** [comment]
@alilie Thanks a lot, I've tested under 10.11 and 10.14 as well, it is the better solution everywhere, and since these are AUI windows, the metal grey version fits perfectly anyway.

**Pull request merged**
