### PR TITLE
32 bit compilation with c++14 fails on Mac because of implicit double…

### PR DESCRIPTION
**Pull request by warniaha**
… narrowing to float - explicit narrowing added

### CODE REVIEW

**Comment by warniaha** [comment]
I have a component that interacts with a hardware device that’s 32 bit only.  It’s a real pain.  Hope to eliminate it soon…

**Comment by vadz** [comment]
Sorry, I wanted to make sure that the problem is fixed after applying it, but realized I can't because I can't reproduce the original problem at all, even with unmodified code. What is the exact command line used when compiling, do you use any non-default options?

With default configure (except for `--with-cxx=14 --disable-shared`) options, my command line is

```
/Users/zeitlin/build/wx/static/bk-deps g++ -std=gnu++14 -mmacosx-version-min=10.7 -stdlib=libc++ -c -o corelib_carbon_graphics.o  -D__WXOSX_COCOA__      -DWXBUILDING -I/Users/zeitlin/build/wx/static/src/tiff/libtiff -I/Users/zeitlin/src/3rdparty/wx/master/src/tiff/libtiff -I/Users/zeitlin/src/3rdparty/wx/master/src/jpeg -I/Users/zeitlin/src/3rdparty/wx/master/src/png -I/Users/zeitlin/src/3rdparty/wx/master/src/zlib -I/Users/zeitlin/src/3rdparty/wx/master/src/regex -I/Users/zeitlin/src/3rdparty/wx/master/src/expat/expat/lib -DwxUSE_BASE=0 -Wall -Wundef -Wunused-parameter -Wno-ctor-dtor-privacy -Woverloaded-virtual -Wno-deprecated-declarations -D_FILE_OFFSET_BITS=64 -I/Users/zeitlin/build/wx/static/lib/wx/include/osx_cocoa-unicode-static-3.1 -I/Users/zeitlin/src/3rdparty/wx/master/include -I/sw/include -O2 -fno-common  /Users/zeitlin/src/3rdparty/wx/master/src/osx/carbon/graphics.cpp
```

which doesn't result in any errors, but this might be unsurprising because it's a 64 bit build. However adding `-arch i386` and/or replacing `gnu++14` with `c++14` still doesn't make them appear. What is the crucial difference here, i.e. how can I reproduce the current problem? My compiler is:

```
% g++ -v
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/c++/4.2.1
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by warniaha** [comment]
configure --enable-debug  --enable-debug_flag --enable-debug_info --enable-debug_gdb --enable-debug_cntxt --enable-shared=yes --enable-monolithic CFLAGS="-arch i386" CXXFLAGS="-arch i386" CPPFLAGS="-arch i386" LDFLAGS="-arch i386" OBJCFLAGS="-arch i386" OBJCXXFLAGS="-arch i386" --target=i686-apple-darwin10.10.0 --with-macosx-sdk=/Developer/SDKs/MacOSX10.10.sdk --with-macosx-version-min=10.10 --with-osx_cocoa --enable-visibility --enable-unicode --with-expat --with-cxx=14

 

Since fixing the issue, I’ve upgraded the minimum OS/SDK/Target from 10.7.  I don’t think it will have any effect on reproducing the error.  I have not tried building it without the CGFloat patch for 10.10.  My build process automatically applies patches for the changes I’ve made to my local copy of the library

**Comment by vadz** [comment]
Really weird, I just don't understand why I don't see it (FWIW I agree that I should, I thought exactly what you wrote above when I looked at this initially -- but the fact is that I don't). Anyhow, let me commit a slightly less ugly (IMHO) fix for this, please retest it to check that it fixes the issue for you -- as I can't test this myself. Thanks!

**Pull request closed without merging**
