### PR TITLE
No real changes. Added const-qualifier to local variables that not ch…

### PR DESCRIPTION
**Pull request by orbitcowboy**
…anged.

### CODE REVIEW

**Comment by vadz** [comment]
Thanks, but I'm not sure whether we want to merge this. While I, personally, do like making local variables const as much as possible, this is not done in 90% of wx code and most of the benefits of doing this are in large(r) functions, when the entire function is 2-3 lines long, it's quite clear that the variable value doesn't change even without the `const` and yet many of the changes in this PR are in such very short functions.

What do the others think?

**Comment by orbitcowboy** [comment]
Thank for your feedback. This PR fixes warnings from VS2017, issued when some c++-core rules are activated. As you already mentioned, the real benefit of const-correctness, is given on large functions. Non the less, it does not harm when local variables are qualified as const. In addition, less compiler warnings are also good.

**Comment by vadz** [comment]
I had no idea MSVS could warn about this. Which warning is this and how can it be enabled?

**Comment by orbitcowboy** [comment]
Go to Properties->Code Analysis -> General and select "C++ Core Check Const Rules".

**Comment by orbitcowboy** [comment]
Ping! Shall we close this PR?

**Comment by vadz** [comment]
No, sorry, I didn't have time to return to it yet.

**Comment by orbitcowboy** [comment]
Ok. No worries...

**Comment by vadz** [comment]
Is it possible to either set up our existing AppVeyor build or add a new one that would fail if the analysis doesn't pass? Because without this, I'm afraid keeping wx headers free of these warnings won't last for very long and so I'm not sure how useful would it be...

**Comment by vadz** [comment]
Returning to this PR, I still think it's not going to be very useful in the long term if we don't check for this analyser warning in the CI builds, but let's apply it nevertheless, it shouldn't do any harm neither. But if you could please modify `appveyor.yml` to enable the warning, it would still be very useful.

**Comment by orbitcowboy** [comment]
Thank you for applying this PR.
Are you willing to accept similar const correctness improvements as pull request?

**Comment by orbitcowboy** [comment]
Ok, thanks.

**Pull request closed without merging**
