### PR TITLE
stick with compile settings detected at configure time (#18034)

### PR DESCRIPTION
**Pull request by e9925248**

### CODE REVIEW

**Comment by vadz** [comment]
Oops, it turns out we don't actually define `HAVE_TYPE_TRAITS` in configure when using C++11 (because it's useless...), so the tests compilation is indeed broken under Unix in this case.

We could either just continue defining `HAVE_TYPE_TRAITS` in `wx/defs.h` because this one doesn't affect ABI, AFAICS, or define it from configure unconditionally.

**Comment by e9925248** [comment]
configure checks & defines HAVE_TYPE_TRAITS:
~~~
AC_CHECK_HEADERS([type_traits tr1/type_traits], break, [], [AC_INCLUDES_DEFAULT()])
~~~

**Comment by vadz** [comment]
This check is inside `if test "$HAVE_CXX11" != "1" ; then`, that's the problem.

**Comment by vadz** [comment]
Let's try fixing it like this...

**Comment by vadz** [comment]
@TcT2k any idea why are we getting [this error](https://travis-ci.org/wxWidgets/wxWidgets/jobs/323380464) in CMake build? It looks like `HAVE_TYPE_TRAITS` is not defined in it any more after the commit above which stops defining it in `wx/defs.h` when using configure (and CMake masquerades as configure by defining `__WX_SETUP_H__`), but I don't see why: there is a test for it in `build/cmake/setup.cmake` which looks like it ought to work. Is the stuff in this file used when targeting Xcode generator? If not, can we detect this generator in `wx/defs.h` and just keep using the old logic in this case?

TIA!

**Comment by TcT2k** [comment]
@vadz  `setup.cmake` is always used regardless of the generator. The checks for `HAVE_TR1_TYPE_TRAITS` and `HAVE_TYPE_TRAITS` are guarded with an if in line 583 `NOT MSVC_VERSION LESS 1600`:

    if(NOT MSVC_VERSION LESS 1600)
        check_include_file_cxx(tr1/type_traits HAVE_TR1_TYPE_TRAITS)
        check_include_file_cxx(type_traits HAVE_TYPE_TRAITS)
    endif()

From the output in the log I assume that the check is FALSE for non MSVC compilers (as MSVC_VERSION is unset) and therefore the tests are not run. This is clearly not correct and was probably masked before the changes here. I would suggest changing the if to:

    if(NOT MSVC OR NOT MSVC_VERSION LESS 1600)

**Comment by vadz** [comment]
OK, thanks, let's try doing it like this.

FWIW I still don't understand why does it work for (CMake) Unix builds though, if this test really fails for not-MSVC compilers (I wasn't sure about this), they should have the same problem.

Also, if we want to handle MSVC specially (why? i.e. why not just always run these checks?), can we avoid them for MSVC versions new enough to have `std::type_traits` in some way, i.e. can we somehow shortcircuit `check_include_file_cxx()` evaluation in this case?

**Comment by TcT2k** [comment]
I assume it works in the Unix builds because they don't run as C++11.
If I remember correctly, I excluded older MSVC versions because of compile issues when they were included (probably because of incomplete C++11 support).
We could probably skip `check_include_file_cxx()` with a version check, but in my opinion we should keep as much CMake checks the same across compilers and platforms as possible.

**Comment by vadz** [comment]
Ah, yes, of course, I somehow confused our C++11 Unix build using configure and Unix build using CMake which indeed doesn't use C++11 at all, thanks for setting me straight.

And I don't mind doing the checks for all toolsets, I just thought that the MSVC condition was an optimization and then it made at least as much sense to optimize for the newer compilers as for the old ones to me. But if it was a workaround for some problem, I'll just add a comment mentioning this but won't change anything else.

Thanks again!

**Comment by vadz** [comment]
Unfortunately this still didn't work: the checks are done now, but it doesn't find `type_traits` (while finding `tr1/type_traits`) during the configure stage. Any help with this would be very much appreciated. TIA!

**Comment by MaartenBent** [comment]
Maybe enable policy [`CMP0067`](https://cmake.org/cmake/help/v3.8/policy/CMP0067.html).

It looks like `check_include_file_cxx()`, which [internally](https://github.com/Kitware/CMake/blob/master/Modules/CheckIncludeFileCXX.cmake#L59) uses `try_compile()`, does not specify the language options explicitly. From [here](https://cmake.org/cmake/help/v3.9/command/try_compile.html#other-behavior-settings) I understand that you either have to specify `<LANG>_STANDARD <std>` or enable the policy.

**Comment by vadz** [comment]
Thanks Maarten! Could anybody please check the suggested fix locally? Travis Mac builds seem to be broken currently as none of them even starts... (although perhaps the problem can be reproduced with C++11 build using CMake even under Linux?).

**Comment by MaartenBent** [comment]
Didn't work for me at first. CMake finds `tr1/type_traits` and tries to use `std::tr1::is_base_of` instead of `std::is_base_of` (and similar functions).

When using `export CXXFLAGS=-stdlib=libc++` before calling `cmake`, it finds `type_traits` and everything compiles.
 (instead of using export, maybe this option can be provided with `CMAKE_CXX_FLAGS` argument as well).

This is however with the `Unix Makefiles` generator, not the `Xcode` generator used by Travis.

**Comment by vadz** [comment]
If I understand correctly, what works with Unix makefiles should work with Xcode too. But there must be a way to avoid setting any other flags/arguments and just use the existing `-DCMAKE_CXX_STANDARD=11`, shouldn't there? If you can find it, it would be really great. Thanks again!

**Comment by TcT2k** [comment]
First of all it would make sense to me to enable the policy my adding the following to `policies.cmake`
```
if(POLICY CMP0067)
    # Honor language standard in try_compile() source-file signature.
    cmake_policy(SET CMP0067 NEW)
endif()
```

But unfortunately that's not enough (probably why I added the Xcode specific option @MaartenBent found.

I agree with @vadz that setting `CMAKE_CXX_STANDARD` should be enough. But that does not seem to set the required runtime library type for macOS. Maybe that should be a defect/ticket in CMake?

The best solution I could think of would be to add `-stdlib=libc++` automatically in the wxWidgets cmake files when C++11 or up are specified. This could also enforce the required deployment target of 10.9 for using `libc++`.

But just for my (and maybe general understanding) before these changes the tests where not required (or didn't matter) because the results were not used with C++11?

**Comment by MaartenBent** [comment]
Before these changes it used to work because the defines in `defs.h` would override the defines set by CMake. It checks for `__cplusplus >= 201103L` and when true, it defines `HAVE_TYPE_TRAITS`.
After `defs.h` was removed, CMake sets `HAVE_TR1_TYPE_TRAITS` which results in wrong include files. This should all be fixed with the policy change.

Fix acdd0ef0 is not really needed, the CMake output shows that the type_traits checks were performed before as well.

The two `Xcode` workarounds in `functions.cmake` (`libc++` problem, and the problem of `wxscintilla` in combination with `cotire`), should also be applied when using `Unix Makefiles` and probably all other generators as well. Your proposed solution seems to address this. I wonder if it is also needed when using `gcc` instead of `clang`. IMO these changes can be part of a different PR or ticket so this one can be merged.

**Comment by vadz** [comment]
Thanks @MaartenBent for the analysis, I think I've done the changes that you proposed (please correct me if I'm wrong), let's see if they work now.

**Comment by vadz** [comment]
Well, no, it didn't work :-(

```
-- Looking for C++ include tr1/type_traits
-- Looking for C++ include tr1/type_traits - found
-- Looking for C++ include type_traits
-- Looking for C++ include type_traits - not found
```

Any ideas about how could we make this work?

**Comment by MaartenBent** [comment]
You can try to use `export CXXFLAGS=-stdlib=libc++` before calling CMake, or `-DCMAKE_CXX_FLAGS="-stdlib=libc++"` as CMake argument.

Currently libc++ is only enabled via `XCODE_ATTRIBUTE_CLANG_CXX_LIBRARY`. I suspect this has only effect for the Xcode project, not for `try_complile` and`check_include_file_cxx`.

**Comment by TcT2k** [comment]
I think what @MaartenBent bent said is true. And locally that worked for me.

If I find time during the day I'll look into this and maybe add the libc++ flags for the tests and other build systems automatically.

But if this is the case it might be an error (or at least an oversight) in CMake as setting the `CMAKE_CXX_STANDARD` should free the user from knowing such details (aka automatically setting all required compiler flags).

**Comment by vadz** [comment]
Thanks, if this is correct, it definitely looks like a (bad) bug in CMake to me. Let's check if it works now...

**Comment by vadz** [comment]
Hallelujah, it has finally passed, so let's merge this. But CMake C++11 support really needs work...

**Pull request merged**
