### PR TITLE
Travis improvements

### PR DESCRIPTION
**Pull request by MaartenBent**
Test parallel builds and removing cppunit.

### CODE REVIEW

**Comment by vadz** [comment]
Could you please remove the "work needed" label when this should be merged? It's convenient to use this label to see the PRs that shouldn't be merged yet at a glance.

**Comment by MaartenBent** [comment]
I planned to trigger the Travis build multiple times to see if there are actual improvement or if it is just coincidence. In general it seems a bit faster. The macOS Xcode build is lot faster, probably because it is the only one running on an actual dual-core VM.

If you agree with the changes, go ahead and merge it. Thanks.

**Comment by vadz** [comment]
Should we perhaps use `nproc` or `sysctl -n hw.ncpu` to get the number of cores under Linux/macOS instead of hardcoding 3?

And if we do hardcode it, we probably should use 2, and not 3, at least this is what https://docs.travis-ci.com/user/speeding-up-the-build/ does. What do you think?

**Comment by MaartenBent** [comment]
Using 3 jobs is faster than 2. If one of the jobs is performing I/O, the extra job can keep the CPU busy.
I used `getconf _NPROCESSORS_ONLN` as a cross-platform check for getting the number of cores, and increment with one.

There were some issues when building the samples ([1](https://travis-ci.org/wxWidgets/wxWidgets/jobs/334354131#L2328), [2](https://travis-ci.org/wxWidgets/wxWidgets/jobs/334372068#L2195)), so I disabled parallel jobs there.

**Pull request merged**
