### PR TITLE
Deprecate `wxScreenDC` even more and remove macOS implementation

### PR DESCRIPTION
**Pull request by vadz**
@csomor This is a bit brutal, but I don't know how to do compile/run-time tests there and it just doesn't seem worth it, so if you don't terribly mind, I'd like to merge this to at least fix compilation, as this is certainly going to affect more and more people.

### CODE REVIEW

**Comment by vadz** [comment]
Stefan, I'll merge this soon as I think more and more people risk running into this.

**Comment by csomor** [comment]
> Stefan, I'll merge this soon as I think more and more people risk running into this.

sorry, I missed this, the reason for this change are the compile erorrs ?

**Comment by csomor** [comment]
ok, as usual there's a screenshot kit now ... is the intention to remove wxScreenDC throughout wx ? otherwise I'd like to make it compile again, and then add a screenshot implementation later for macOS 15

**Comment by vadz** [comment]
> is the intention to remove wxScreenDC throughout wx ?

Of course it would be better to keep it if we can. It still works under MSW, AFAIK, and there might be a way to use some (optional) Wayland protocol to make it work there, I think, but it probably wouldn't be trivial.

> otherwise I'd like to make it compile again, and then add a screenshot implementation later for macOS 15

The trouble is that I have no idea how to make it compile again. But if you could do this, it would be great, of course, especially for 3.2, where removing it would be even more problematic. TIA!

**Comment by csomor** [comment]
ok, thanks, I'll do a PR right now

**Comment by SpareSimian** [comment]
I grepped my code for instances of wxScreenDC and see one usage: Measuring the font size in a wxGrid to set the label sizes. It's based on the Python code here: https://wiki.wxpython.org/wxGrid#Autosizing_labels

**Comment by vadz** [comment]
> I grepped my code for instances of wxScreenDC and see one usage: Measuring the font size in a wxGrid to set the label sizes.

FWIW nowadays you'd use `wxInfoDC` for this.

**Comment by vadz** [comment]
I've merged this branch without the last commit, which is not needed any more after Stefan's changes.

When/if we implement `wxScreenDC` for macOS 15+ (and Wayland?), we could revert some of the commits here, but for now I think they describe the situation accurately.

**Comment by SpareSimian** [comment]
wxInfoDC doesn't appear in my copy of 3.2.5. I surmise that this is a fairly recent addition?

**Comment by vadz** [comment]
Yes, it's 3.3-only.

**Pull request closed without merging**
