### PR TITLE
Cmake options

### PR DESCRIPTION
**Pull request by MaartenBent**
Another round of CMake improvements.

I refactored the expat code so it matches to other third-party libraries.
I fixed building with `wxUSE_GUI 0`. And moved the declaration of the windows libraries so they are always available.
I improved the options. Some used the wrong name. There were some duplicates. Some were missing, causing the wrong default value in setup.h (e.g. native statusbar and progress dialog). Some were overruled in setup.cmake or init.cmake.
And I added the option to enable the  Direct2D graphics context so it can be used in MinGW versions that support it. And add required libraries as well.

### CODE REVIEW

**Comment by vadz** [comment]
As usual, I'd like to ask @TcT2k for review, TIA!

**Review by TcT2k — APPROVED** [review]
Looks good to me.
Seems to fix many copy&paste errors I made when bringing over stuff from `configure`. Some of the previously missing options I definitely didn't omit on purpose. 

In the future we could maybe make more use of `wx_dependent_option()` for options that depend on others.

I was wondering about the remove d`wxUSE_PROTOCOL...` options ?

**Comment by MaartenBent** [comment]
Duplicates, they are still [there](https://github.com/wxWidgets/wxWidgets/pull/694/files#diff-cacf264752b5e90ad7b7d4e70a6e06f6L135).

**Comment by LegalizeAdulthood** [comment]
Looks good to me!  I also wondered about the missing `wxUSE_PROTOCOL...` and suspected it was duplication.

**Pull request merged**
