### PR TITLE
Handle wxToolBars created with wxTB_HORIZONTAL | wxTB_BOTTOM style

### PR DESCRIPTION
**Pull request by PBfordev**
wxToolBar created with wxTB_HORIZONTAL | wxTB_BOTTOM had two issues:
(1) There was a toolbar-high gap below the menu bar.
(2) The status bar was not positioned correctly.

Fix both issues by taking into account that wxTB_TOP is an alias for wxTB_HORIZONTAL
and so a wxToolBar can have quite counter-intuitively set both wxTB_TOP and wxTB_BOTTOM.

In such cases it means that the toolbar is horizontal and on the frame bottom,
this needs to be accounted for when computing the origin of the frame client
area as well as the status bar position.

Closes #18760

### CODE REVIEW

**Comment by vadz** [comment]
Thanks a lot for fixing this, the changes seem correct to me and I clearly must not have realized that `wxTB_TOP | wxTB_BOTTOM` was a valid flag. I'm going to merge this in a moment, but I think that perhaps having some `wxToolBar::GetDirection()` function returning exactly _one_ of `wxTB_{LEFT,TOP,RIGHT,BOTTOM}` could be worth it, as I feel myself perfectly capable of making the same mistake again.

**Comment by vadz** [comment]
In fact, there seems to be the same error when testing for `wxTB_LEFT` in `GetClientAreaOrigin()`, as it's also the same as `wxTB_VERTICAL` and so could be usedtogether with `wxTB_RIGHT`... I'll fix it too, blindly, please let me know if I did something stupid.

**Comment by vadz** [comment]
Oh, and there are also similar problems in Mac code (but not GTK, small blessings...).

I've pushed my changes to your branch to retest the build again with them and see if anybody has any comments. But I wonder if it wouldn't have been better to just forbid such "impossible" combinations, finally... it's not like they ever worked, so maybe we should just assert and say that this is not supported?

If not, we should at least document that it's not necessary to specify horizontal/vertical styles with right/bottom ones.

**Comment by PBfordev** [comment]
I [responded](https://trac.wxwidgets.org/ticket/18760#comment:4) in the ticket.

Sorry for not realizing that there is the same issue for toolbars placed right. I knew that `wxTB_LEFT` was the same as` wxTB_VERTICAL`, the code for those looked odd but it just did not click.

**Comment by PBfordev** [comment]
@vadz 
I tried simplifying the code dealing with toolbar placement. The helper function must be public so a frame can access it. I have not documented it yet, because (1) You wrote you will make some documentation changes and (2) I do not know if you agree with this solution.

**Comment by vadz** [comment]
Thanks for your changes!

I'm going to merge them because even though I'm still not sure it's the best thing to do, it's clearly an improvement and I don't want to leave this pending forever. Of course, future documentation enhancements would be very welcome, as always.

Finally, I'm going to squash together the last 3 commits and force-push here before merging, as I don't think it's worth having typo fixes as separate commits, hopefully this doesn't create any problems (if you have any more unpublished changes, you should be able to rebase them on master without conflicts after the merge).

And thanks again!

**Pull request merged**
