### PR TITLE
Added support for wxBORDER_NONE to wxQT

### PR DESCRIPTION
**Pull request by ffa-grahamdawes**
Previously, the flag wxBORDER_NONE was ignored for wxQT.  This changes add support for this flag.

Unfortunately,  there's no direct mapping from the wx flag into a QT flag.  Instead, the border needs to be controlled using CSS in QT.

### CODE REVIEW

**Comment by vadz** [comment]
@catalinr I remember discussing using style sheets for wxQt widgets previously and you had some reservations about doing it. Unfortunately I don't remember any more what they were and don't know if they apply to this patch (which looks fine to me, but then I don't know anything about the use of CSS in Qt). Could you please check this one and let us know if you think it's ok? TIA!

**Comment by catalinr** [comment]
> @catalinr I remember discussing using style sheets for wxQt widgets previously and you had some reservations about doing it.

@vadz, the use of style sheets itself is ok, and most likely unavoidable for some customisations (and IIRC "no border" is one of them). The problem is that there can be only one style sheet per widget thus when it is set it has to be complete, because it will replace any previously set style sheet.

What is ok about this patch (not ideal though):
- it replaces the only call to `setStyleSheet()` with another; ideally there should be a mechanism that would build the stylesheet with all needed properties and eventually set it only once.

What looks less ok in this patch:
- beside the claimed support for "no border", it changes the implementation for supporting "transparent background", so it should probably have had 2 parts: 1) change implementation for the latter; 2) add support for the former.
- it makes use of "dynamic properties", by calling `setProperty()` foar an already set style sheet. This is documented as having some limitations (see `Limitations` paragraph at https://wiki.qt.io/Dynamic_Properties_and_Stylesheets). So have the changes been tested? Even the ones regarding the "transparent background"?
- it has a second commit that removes some comments. They do not seem related to all this, and while they look like unused code, they might be there to suggest future improvements or better use of certain options or just to make people aware of them. Was that really needed [to be part of this]?

**Comment by ffa-grahamdawes** [comment]
After further investigation I can't find a satisfactory way of getting the wxBORDER_NONE flag to work so I think I'll close this PR.

**Comment by catalinr** [comment]
Yes, AFAIR using the style sheet was the only way to make `wxBORDER_NONE` work, but unfortunately there is no quick & easy way to correctly implement support for it.

**Comment by vadz** [comment]
It's not a huge problem if this style is not implemented for arbitrary windows, but it's pretty useful for `wxTextCtrl` when it's used as any kind of "in place" editor. Would there be any possibility to add support for it at least for this class by chance?

**Comment by catalinr** [comment]
How about all pieces of a style sheet are added to a structure (a vector of strings should work for now, or even a plain string for only these 2 properties), i.e. when appropriate,
- `wxWindowQt::QtSetBackgroundStyle()` would call `AddToStyleSheet("background:transparent;")`
- `wxWindowQt::PostCreation()` would call `AddToStyleSheet("border: none;")`
- a call to `CallAfter(&wxWindowQt::ApplyStyleSheet)` would build the style sheet and apply it to the current widget - (no idea where the right place for such a call would be).
The drawback here is that some properties can be dynamically changed so making the call to build and apply the style sheet should be done for every change to any of the contained properties.

Or, just for text control, setting transparent background could be ignored and use the style sheet just for no-border style.

**Pull request closed without merging**
