### PR TITLE
github actions:  use node20 instead of deprecated node16

### PR DESCRIPTION
**Pull request by wsu-cb**
This is a PR to test fixing the node16 deprecation warnings when building with Microsoft Visual Studio and CMake.

See https://groups.google.com/g/wx-dev/c/O_wpfSMEj1E/m/OJNscdB5AQAJ

### CODE REVIEW

**Comment by wsu-cb** [comment]
Since the first commit removed the node16 deprecation warning for `gha-setup-vsdevenv`, but there were still a couple of others, I added another commit to remove the remaining warnings.  I think they are all gone now from the builds triggered by `ci_cmake.yaml`.

**Comment by wsu-cb** [comment]
> Since the first commit removed the node16 deprecation warning for `gha-setup-vsdevenv`, but there were still a couple of others, I added another commit to remove the remaining warnings. I think they are all gone now from the builds triggered by `ci_cmake.yaml`.

Wait, now I see new warnings?!  But I need to go to bed; I will look at this some another day.

**Comment by wsu-cb** [comment]
I think this is ready for review.

This PR now has changes to update all uses of node16 to node20 for (I hope) all of the github builds except for the Ubuntu 18.04 ones.  (Based on #24270, I assume node20 is incompatible with Ubuntu 18.04.)

However, some of the changes use my personal fork https://github.com/wsu-cb/gha-setup-vsdevenv/tree/use-node20, so before merging this PR, I would prefer to see https://github.com/wxWidgets/gha-setup-vsdevenv/pull/1 merged, and then change this PR to point to an updated https://github.com/wxWidgets/gha-setup-vsdevenv.

**Comment by vadz** [comment]
Thanks for your work on this! I'll merge this (and the gha-setup-vsdevenv one) soon.

**Pull request closed without merging**
