### PR TITLE
Add GstPlayer 1.7.2.1+ based GStreamer backend

### PR DESCRIPTION
**Pull request by sdroege**
On top of https://github.com/wxWidgets/wxWidgets/pull/225

Not completely finished yet but it seems to work at least as good as the other one already.

### CODE REVIEW

**Comment by sdroege** [comment]
Main question here is how errors are supposed to be handled and reported. You could return false from the different methods, but that would a) only work for things that fail in the very beginning and b) requires to do synchronous operations which is not ideal for anything IO related.
What should happen if something goes wrong?


The other question is what the download methods are supposed to return, what the actual meaning of that is. Is it just for distinguishing between the filesize in bytes and the duration in time? Or for buffering (i.e. buffer of 2MB for network streams)? Or ...?

**Comment by vadz** [comment]
I can't even test this myself and I'm not sure about the questions above (it would probably be better to post them to wx-dev but I suspect you might know more about this code than anybody else right now).

At the code level I'm not sure if it makes sense to put this new code in the same file as the existing code if they don't seem to share much (if anything?). Maybe a new `media_gst_player.cpp` (or whatever) would be better?

Also, much more minor, but I don't think we need to _warn_ about 1.7.2 not being found in configure as it's pretty rare right now. Maybe ideal would be to have a separate `--with-gst-player` option. By default it would use it if it's available and (silently) fall back to the older API otherwise, but if it's explicitly specified it would give an error and stop.

**Comment by sdroege** [comment]
I'll take some further look at the code then, and also the other backends. Maybe I find an answer there. Otherwise, what this patch does is in behaviour the same as the old GStreamer backend. Which seems not ideal but also not a problem in the last years it seems.

For putting it in a separate file, how does that work with your build system? AFAIU it always builds all the files listed in the bakefile stuff, so the old and new file would need an #ifdef / #ifndef to make sure only one of the two is compiled in?

For the configure part you mention, that's indeed a good point. I'll fix that

**Comment by vadz** [comment]
Yes, all files are always compiled, so they should have an `#if` around their contents, unfortunately.

**Comment by sdroege** [comment]
Ok, I'll do it like that then :) Thanks!

**Comment by sdroege** [comment]
This is updated now. I think the only way how to report errors here is to convert the asynchronous API to a synchronous one, possible blocking the UI for a while (like in the other backends) when trying to play network streams. I think the way it is right now in the GstPlayer backend is a better user experience then until the MediaCtrl API allows for asynchronous error reporting.

**Comment by vadz** [comment]
I still can't test this myself, but I'm merging this in the hope that others will.

Thanks again for all your changes!

**Comment by sdroege** [comment]
Thanks, for merging!

**Comment by Hanmac** [comment]
while trying to test it, and wondering where can i get it from, i only got news from thats deprecated from 2005 ... i thought it was dead, because i cant find anything about it.

but its cool if you say that it might included in newest gstreamer.

**Comment by sdroege** [comment]
It's included in GStreamer 1.7.2 and newer (but we actually need a feature that was added only in 1.7.2.1). You can find the docs here: https://gstreamer.freedesktop.org/data/doc/gstreamer/head/gst-plugins-bad-libs/html/gst-plugins-bad-libs-gstplayer.html

**Comment by sdroege** [comment]
@vadz btw, if/when there are any GStreamer related bug reports please let me know

**Comment by vadz** [comment]
Thanks, will definitely do! Could you please drop me a note with your (preferred) email address at `vadim at wxwidgets dot org`?

**Pull request closed without merging**
