### PR TITLE
Fix copy to clipboard by flushing the updated data.

### PR DESCRIPTION
**Pull request by pkulchenko**

### CODE REVIEW

**Comment by vadz** [comment]
Hmm, this doesn't compile (see [Travis CI](https://travis-ci.org/wxWidgets/wxWidgets/jobs/605113344)), but the idea is probably correct, thanks. It would be nice if Stefan could please confirm it.

**Comment by pkulchenko** [comment]
@vadz, pushed an update; I did confirm that it compiles and works.

**Comment by csomor** [comment]
Thanks, I'll take this

**Comment by pkulchenko** [comment]
Thanks @csomor for merging; can confirm the fix! I'll close https://trac.wxwidgets.org/ticket/18553.

**Pull request merged**
