### PR TITLE
Fix WebView tests with WebKitGTK 2.43+

### PR DESCRIPTION
**Pull request by swt2c**
Plus a fix for the WebView sample I ran into while troubleshooting this.

### CODE REVIEW

**Comment by vadz** [comment]
Thanks for fixing this!

I couldn't prevent myself from doing some minor cleanup here, please let me know if you see anything wrong with it, otherwise I'll merge it soon.

**Comment by swt2c** [comment]
Your updates look good.  I'm assuming they are not backportable though?

**Comment by vadz** [comment]
No, they aren't, I hadn't realized you wanted to apply this to 3.2 too.

I'll merge this in master and will just apply your original changes to 3.2 then.

**Comment by swt2c** [comment]
The first commit definitely should go to 3.2 as I'm running into that problem on both Fedora & Debian.  The second one is a nice-to-have as I'll be less annoyed the next time I go to play with the webview sample.  :-)

**Pull request merged**
