### PR TITLE
CMake: Fix library directory when using MinGW

### PR DESCRIPTION
**Pull request by MaartenBent**
This was broken in b102afc316 (CMake: Don't include generator expression in wxPLATFORM_LIB_DIR, 2021-10-17).
And for clarity, always add a '/' after directories.

Closes [#19305](https://trac.wxwidgets.org/ticket/19305)

### CODE REVIEW

**Comment by PBfordev** [comment]
@MaartenBent , I just tried to build "INSTALL" in CMakePredefinedTargets in wxWidgets MSVS 2019 solution generated by CMake. However, I ended with error MSB3073:

> The command "setlocal
> "C:\Program Files\CMake\bin\cmake.exe" -DBUILD_TYPE=Release -P cmake_install.cmake
> if %errorlevel% neq 0 goto :cmEnd
> :cmEnd
> endlocal & call :cmErrorLevel %errorlevel% & goto :cmDone
> :cmErrorLevel
> exit /b %1
> :cmDone
> if %errorlevel% neq 0 goto :VCEnd
> :VCEnd" exited with code 1.	INSTALL	C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets	155	
> 

The install worked when I started MSVS as Administrator. Does the install have the same permission issue as there was with the symlink or is this something different (and expected and unavoidable)?

**Comment by MaartenBent** [comment]
The default install target that CMake uses is `C:/Program Files (x86)/wxWidgets`, you'll need elevated rights to write to this location.
There is nothing to do about this, except for defining `CMAKE_INSTALL_PREFIX` yourself to a location that you have write access to.

**Comment by vadz** [comment]
I have no idea if it's a good thing to do, but could we use `%LOCALAPPDATA%\wxWidgets` or something like this by default instead?

Does anybody know what do the other libraries using CMake do under MSW by default?

**Comment by MaartenBent** [comment]
These are default CMake things for any project you create, I don't think we should modify this.

**Comment by PBfordev** [comment]
FWIW, I just checked unmodified OpenCV CMake, its `CMAKE_INSTALL_PREFIX` points to
`D:/Dev/Desktop/!Lib/opencv-GIT-build-vc16_x64_DLL/install` where `D:/Dev/Desktop/!Lib/opencv-GIT-build-vc16_x64_DLL` is the build folder.

OTOH, Poco's also points to ProgramFiles(x86).

**Pull request merged**
