### PR TITLE
Some long outstanding miscellaneous fixes to wxDVC and others

### PR DESCRIPTION
**Pull request by vadz**

### CODE REVIEW

**Comment by mtangoo** [comment]
Do you intend to fix someday showing horizontal scroll instead of dotted names in Windows?
error

**Comment by vadz** [comment]
I'm not sure what exactly is there to fix, I'm not aware of any bugs with this (the screenshot shows the expected behaviour if the column is not wide enough and, obviously, you just need to make it wide enough to avoid it), but it's certainly possible there are some. Please open tickets for them with the instructions about how to reproduce them, as usual.

**Comment by mtangoo** [comment]
In Linux if column is not winder enough it shows a scroll windows, with code `GetColumn(0)->SetWidth(wxCOL_WIDTH_AUTOSIZE);` but in Windows it does not show up. I was not sure if its a bug or not and I lived with it but now its annoying. So Is it a bug that I need to open a ticket for?
Thanks for super quick response!

**Comment by vadz** [comment]
I am really not sure what are you seeing here, please reproduce the behaviour you're seeing in the dataview sample, this should make things much more clear.

**Comment by mtangoo** [comment]
Its very simple. When you have an item with long text label (like **bower_components** in the attached image) it truncates the text and adds dots. In Linux it shows horizontal scrollbar so that you can scroll to see the text. Am not sure if this is Windows native behaviour for this control or a bug.

If its a bug I want to open the ticket but if it is a native behavior then I have to live with it :)

**Comment by heinemml** [comment]
Building with clang on OS X is broken with this pull Request. See comment on 5591a20 for details.

**Pull request closed without merging**
