### PR TITLE
 Use wxString instead of const char* for string constants

### PR DESCRIPTION
**Pull request by jhasse**
This avoids calling the implicit conversion constructor every time they are used.

### CODE REVIEW

**Comment by vadz** [comment]
No comments about the first commit (I could apply it already, but I don't know if it would make things more or less convenient for you -- please let me know), but I'm not sure if the second one is optimal as this now means that all these global `wxString` objects need to be constructed on program startup. I don't know if it's noticeable, but it looks unnecessary when we could just add `wxString(...)` around these constants wherever they're used -- which would also be more backwards-compatible (again, I'm not sure if this creates any compatibility problems, but if we do _not_ change the type of all those `wxXXXNameStr` constants and just put `wxString(...)` around them, it surely wouldn't create any).

I realize that it's a lot of not very fun work for you, but I'd prefer if it could be done like this, then we wouldn't even have to think about whether there is a problem or not with doing it as there obviously wouldn't be any. TIA!

**Comment by jhasse** [comment]
> I could apply it already, but I don't know if it would make things more or less convenient for you -- please let me know

Would help, I would just rebase my PR then :)

>  I'm not sure if the second one is optimal as this now means that all these global wxString objects need to be constructed on program startup.

I've thought about this, too. Would you be willing to merge this if I set up a benchmark and the difference turns out to be negligible? The time until the window shows could actually be faster at it doesn't need to create the temporaries.

**Comment by vadz** [comment]
> Would you be willing to merge this if I set up a benchmark and the difference turns out to be negligible?

Yes. Extra bonus if you could use a tool like VTune or perf to look at the number of instructions executed and not just the time, which risks being difficult to measure accurately.

> The time until the window shows could actually be faster at it doesn't need to create the temporaries.

I don't see how it could be possible, we'd be creating a ~hundred objects on startup instead of creating a dozen (or even fewer) temporaries. I do expect it to be negligible though, I'm just not sure about it (and this is why I'd prefer to not even have to think about it).

OTOH benchmarking results are almost always surprising, so who knows what will you find...

**Comment by jhasse** [comment]
I've measured the time it took for a simple application of mine to create a window and immediately exit after that with `time --format=%e`. Without my commit 0.09 seconds and with my commit 0.09 seconds, so no (measurable) difference.

I haven't worked with VTune or perf at all, so I don't know how to measure the executed instructions, sorry.

**Comment by vadz** [comment]
Again, looking at this anew after a break, I don't think we should apply this: the benefits are negligible (the overhead of constructing a `wxString` is tiny compared to the window creation operation, which takes millions of cycles, involves dozens of memory allocations and, in X11 case, can even require a couple of network trips) and just don't seem to be worth worrying about compatibility concerns due to type changes.

Sorry for discarding this, but I prefer to err on the side of caution. In the future, please discuss any big/time-consuming changes on wx-dev before making them to avoid such problems. TIA!

**Comment by jhasse** [comment]
While the benefits are very small, aren't the disadvantages, too?

(Should I start a thread on the wx-dev mailing list instead?)

**Comment by vadz** [comment]
The disadvantages are _probably_ small, but we could break some existing code by this change and, frankly, I just don't think it's worth spending time on this.

Generally speaking, a change, and especially a global change like this, must really bring something positive to the table and I have really no idea what do we actually gain from this one. I'm sorry for wasting your time, I should have realized it from the very beginning.

Finally, posting to wx-dev is always welcome, but I don't expect this PR to provoke much enthusiasm there (if there were a lot of support for it, it would have already manifested itself, I think). I do recommend posting there before making any wide-reaching/time-consuming changes in the future however. TIA!

**Pull request closed without merging**
