### PR TITLE
Revert art ids changes and make them `char*` literals again

### PR DESCRIPTION
**Pull request by vadz**
@ardovm any comments are welcome

### CODE REVIEW

**Comment by ardovm** [comment]
Unfortunately, we seem to have a problem with include file `wx/xrc/xmlreshandler.h`

For example (excerpt):
```cpp
class wxXmlResourceHandlerImplBase {
    virtual wxBitmap GetBitmap(const wxString& param = wxT("bitmap"),
                           const wxArtClient& defaultArtClient = wxART_OTHER,
//                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                           wxSize size = wxDefaultSize) = 0;
};
```
Where `wxART_OTHER` is defined in `wx/artprov.h` (excerpt):

```cpp
typedef wxString wxArtClient;
#define wxART_MAKE_CLIENT_ID(id)           (#id "_C")
#define wxART_OTHER                wxART_MAKE_CLIENT_ID(wxART_OTHER)
```

So we have a hard-coded implicit cast from const char* to wxString.

**Comment by vadz** [comment]
Hmm, how did the unit tests manage to pass? Is this header not included by the "allheaders" test?

Anyhow, the fix is to use `= wxASCII_STR(wxART_OTHER)` here, just as in `wx/artprov.h` itself, isn't it?

**Comment by ardovm** [comment]
> Hmm, how did the unit tests manage to pass? Is this header not included by the "allheaders" test?

No... sorry... I forgot to include header files from subdirectories.

It fails to compile (i.e. reveals the problem) if you just add ```#include <wx/xrc/xmlres.h>``` to `tests/allheaders.h`.

> Anyhow, the fix is to use `= wxASCII_STR(wxART_OTHER)` here, just as in `wx/artprov.h` itself, isn't it?

Yes, I think so!

I would be glad to help, but I am not sure I can push to your branch.

**Comment by vadz** [comment]
I've changed it now, please let me know if you see any other problems. Thanks!

Also, @StefanBruens if you could please check whether this allows wxPython to compile, it would be very welcome. TIA!

**Comment by StefanBruens** [comment]
At least `interface/artprov.h` is now lying again ...

**Comment by vadz** [comment]
> At least `interface/artprov.h` is now lying again ...

I hesitated to change it because I thought it would break wxPython wrapper code. It's not really a huge problem, IMHO, but we could definitely use `const char*` in the interface file if it's ok with wxPython.

**Comment by swt2c** [comment]
In general, the less lies the interface files tell, the better.  :-)  `const char*` should be fine for wxPython, and would probably even enable getting rid of this code:
https://github.com/wxWidgets/Phoenix/blob/master/etg/artprov.py#L55

**Comment by vadz** [comment]
OK, I'll change the type to `const char*` in the interface file and merge, if there are no objections.

**Comment by ardovm** [comment]
Works for me!

**Pull request merged**
