### PR TITLE
Add CMake build system

### PR DESCRIPTION
**Pull request by TcT2k**
This is just the beginning to bring CMake support to wxWidgets and is not yet complete.

This is what I could already test successfully:
- MSW Visual Studio 2008-2015 with all libs and samples
- MSW with cygwin, msys2 and mingw32
- osx_cocoa Xcode 6.2 and 8.0
- GTK Makefiles and Ninja (Ubuntu trusty 14.04 and precise 12.04)

Have a look at the added [documentation page](/TcT2k/wxWidgets/blob/build_cmake/docs/doxygen/overviews/cmake.md) and the [contributor reference](/TcT2k/wxWidgets/blob/build_cmake/build/cmake/README.md).

Any **feedback** is welcome! Give it a try on your preferred platform.

I'm planning to include some work from a previous wxWidgets-cmake project by @tibogens available at https://github.com/tibogens/wxWidgets-cmake where it makes sense.

See todo list below for progress and known open issues.
### Screenshots

Screenshot of the CMake GUI on windows with loaded wxWidgets folder and a screen shot of the created project in VS 2015 (click to enlarge):
 
## Progress
- [x] Build targets for base/net/xml library
  - [x] Build targets for builtin zlib/regex (using included cmake support for expat)
  - [x] Build target for base tests
- [x] Build targets for GUI libs
  - [x] Build targets for builtin png/jpeg/tiff libs
  - [x] Build target for GUI tests
  - [x] Build targets for some samples
  - [x] Build targets for all samples
- [x] Support all generators/platform/toolkit combinations
  - [x] Visual Studio MSW
  - [x] MinGW
  - [x] Linux GTK
  - [x] Xcode OS X Cocoa
- [ ] Complete setup.h creation
  - [ ] Port all tests from configure.in
  - [x] Implement more configure options as CMake options
- [ ] Complete install target
  - [ ] Add wx-config creation
- [x] Add uninstall target
- [x] Precompiled headers for clang and gcc
- [x] Precompiled headers for MSVC
- [ ] Build targets for other _utils_ (currently only _wxrc_)
- [x] Build targets for _demos_
- [x] Allow creation of monolithic lib build
- [x] add documentation page on building with cmake

### CODE REVIEW

**Comment by LiPengfei19820619** [comment]
Good job!

**Comment by termi3** [comment]
Great, I was missing this feature already 2-3 years, but was not so familiar with the wxwidgets and cmake to start doing it. 
THANK YOU!

**Comment by vadz** [comment]
@TcT2k should we wait for all the checkboxes to be checked or merge this already? I'm not sure what is meant by "Complete setup.h creation" exactly, but this seems important...

FWIW I think CMake will be mostly useful for Windows users, under Unix people rarely have troubles with `configure && make install` anyhow, so install target is lower priority IMHO.

**Comment by termi3** [comment]
We use wxWidgets to have our projects portable. Having CMake for wxWidgets for Unix users as well is great advantage for all users, then than we can set it as subproject (library) and can play with the versions 32/64, static/shared library etc etc. at once. Now I spend few days per year re-compiling all my and thrird party wx-based libraries and organising in places, when a new version of complier or wx comes. Thank you @TcT2k and @vadz for developing and supporting this!

**Comment by NeroBurner** [comment]
does this also install a generated `wxWidgetsConfig.cmake` file?

**Comment by undisputed-seraphim** [comment]
I look forward to seeing this PR approved. Having CMake support will be greatly beneficial.
Are there any more things that needs to be done for this?

**Comment by NeroBurner** [comment]
checked out the current pull request. compiled fine under Ubuntu 16.04, but no `wxWidgetsConfig.cmake` file at the install location is genereated

**Comment by TcT2k** [comment]
@NeroBurner thanks for testing. Right now `wxWidgetsConfig.cmake` is not generated. My first goal is to create the "traditional" wx-confg shell script for compatibility with existing build scripts (it is also used by CMake's `FindwxWidgets` module. But it's obviously on my todo list to create and install a proper `wxWidgetsConfig.cmake`

@undisputed-seraphim Thank you for testing

@vadz I'll probably rebase this on the current master (primarily for the .travis.yml changes) this week. After that I think it should be merged (as it's more or less parallel to anything else) which should generate more feedback. I'll create an additional PR to track current open todos and potential issues from user feedback.

**Comment by ligfx** [comment]
This is great, thanks so much! If I could, I'd like to add a request: prefix the various targets (`base`, `core`, etc. could be `wxbase`, `wxcore`, etc.?) so this can be included directly into other CMake projects without clashes.

**Comment by emersont1** [comment]
@TcT2k Do you need any help filling the remaining Checkboxes?

**Comment by vadz** [comment]
I assume merging this in its current state still makes sense, but I'd like to receive confirmation of somebody who is actually on friendly terms with CMake, unlike me.

Could people please retest that this works as expected, ideally in at least a couple of different environments? TIA!

**Comment by LegalizeAdulthood** [comment]
I see it hasn't yet been tested with VS2017, I'll give that a go and review the CMake as best I can.  Exciting!

**Comment by csomor** [comment]
Xcode 9.0 under 10.12.6:
In order to build the libs with current master, I had to rebuild `setup.h.in` and `files.cmake`, hardwire `wxUSE_CRASHREPORT` and `wxUSE_STC` to 0 (lexer and crashreport files were missing) and `wxUSE_WEBVIEW_WEBKIT` and `wxUSE_GRAPHICS_CONTEXT` to 1 because of build errors (`__WXOSX__` didn't seem to be defined when setup.h was processed), did a ` cmake -G Xcode -DCMAKE_OSX_SYSROOT=macosx10.11` in order to avoid linker errors with arclite / objective-c runtime lib

**Comment by csomor** [comment]
I'm trying to understand the processes when generating `setup.h` and I'd think that the platform options like eg for MSW ie `/* --- start MSW options --- */` should be within a conditional `#ifdef __WXMSW__` otherwise these will always be defined

**Comment by TcT2k** [comment]
@csomor `setup.h`is generated via CMakes [configure_file](https://cmake.org/cmake/help/v3.9/command/configure_file.html) where CMake variables define what get's written to the target file. The CMake specific `setup.h.in` is generated by the same python script as the other setup.h files.

**Comment by csomor** [comment]
Thanks Tobias, I see that `update-setup-h is` producing the .in files, but since the master cmake setup.h.in file includes msw options without bracketing things, osx ends with unconditionally having msw specific options defined, I'm now breaking the osx `setup0.h` into two parts, so that the osx options can also be included that way, but I still think that .in should bracket these platform specific options with the platform `#ifdef ...`

**Comment by csomor** [comment]
in `cmake/setup.h.in` there are a few `#defines` instead of `#cmakedefine`.  Since they are not part of the _inc .. / options part they don't get replaced with `#cmakedefine` by `update-setup-h`. So I think this is a source of errors, certainly in the case of wxUSE_WEBKIT which gets forced to 0 that way.

**Comment by LegalizeAdulthood** [comment]
VS 2017 32-bit build debug/release completed without errors, with everything enabled.

**Comment by termi3** [comment]
VS2017 64 bit on Win 8.1 64 bit, gives CMAKE error at cotire during the cofnguration  if "MONOLITHIC" AND "Not shared" selected; but this is not bad, as AFIK this configuration is not recommended.

Debug and Release as monolitic, static, build successfull without errors :-) THANKS !!!

**Comment by LegalizeAdulthood** [comment]
Is this supporting cross-compilation?  I haven't played with that in cmake before, but I'm wondering if anything special is needed to support that scenario properly.

**Comment by TcT2k** [comment]
@LegalizeAdulthood as far as I know there is nothing preventing cross compilation, but I have not tested it.

@termi3 Thanks for testing, if you test any more please just comment here and specify which compiler,cmake,IDE versions you used

I'm not currently working on this, but any information posted here will be taken into consideration when I find the time to work on this. So please test and report your findings, regardless of success or failure. Next step should probably rebasing this on a more current master version.

**Comment by vadz** [comment]
I've finally had a first more or less detailed look at these changes and I'm very impressed (although not surprised, considering your other contributions in the past) by the excellent work you've done, thanks a lot @TcT2k for not only making this work, but also organizing everything so nicely, updating the CI tests, providing the documentation and all the rest!

I've merged your branch with the latest master, updated the files list and tested the build under Linux and MSW and it worked without problems under both, so I think we should merge this for 3.1.1 and deal with any problems as they're found.

In the meanwhile, I did notice a couple of things which don't seem ideal, but are not really blockers neither, so I'll just list them here in case they can be addressed easily:

- MSVC (14, a.k.a. MSVS 2015, if it matters) projects don't seem to use parallel build, i.e. only one CPU core is busy during (most of?) the build. Needless to say, this makes the build take much longer than using the existing projects. With the Unix build I could use `cmake --build . -- -j8`, but I don't know what to do for MSVC.
- Build directory under Unix is enormous and weights at 1.6GB without building any samples. This is compared to ~600MB for the autoconf-based build. It might be due to the use of cotire? If so, I wonder if it's really worth it under Unix. Also, funny enough, somehow cmake build directory is much *smaller* than current one with MSVC projects (~400MB against ~2.3GB!). I can't quite explain this...
- Samples binaries are generated under `lib` directory which is a bit weird.
- `HAVE_X11_XKBLIB_H` doesn't seem to be detected by cmake, even though it is by configure, resulting in deprecated `XKeycodeToKeysym()` being used in `src/gtk/window.cpp` and, hence, an extra warning, compared to the normal build (which is how I noticed this, so I can't help wondering if there might not be similar problems with other symbols).

Anyhow, thanks once again and I'll merge this soon if the CI builds pass and you don't have any objections.

**Comment by vadz** [comment]
I've (hopefully) fixed building the tests now, but this discovered two more problems:

- The data files (everything inside `wx-data` tags in `tests/test.bkl`) don't seem to get copied to the build directory (at least under Unix), so several tests fail because they can't find them.
- Potentially more worrisome, `XLocaleTestCase::TestCtor` crashes while freeing an invalid locale in `wxXLocale::Free()` when the test is built with CMake but not when it's built using configure+make. I didn't have time to look at what is going on here and I don't see anything wrong in the CMake compilation command line (it's surprising that it doesn't use neither `-g` nor any `-On` switches by default, BTW, is it normal?), but clearly something is different between the two builds...

**Comment by vadz** [comment]
The CI builds finally pass and so for me this is in a good enough state to merge it and improve it later. Tobias, please let me know if I should (or not) merge this branch in its current state. TIA!

**Comment by TcT2k** [comment]
I also think it's in a good state with the changes you did in the past few days. Smaller remaining issues can always be fixed later on. With the CMake support merged to master (and especially a 3.1.1 release later on) the chance for more feedback are much better than leaving the PR open.

**Comment by PBfordev** [comment]
@vadz wrote 

> MSVC (14, a.k.a. MSVS 2015, if it matters) projects don't seem to use parallel build \<_snipped_\> I don't know what to do for MSVC.

(I apologize if I am stating the obvious) It seems that you just need to expose the /MP compiler switch when generating for MSVC, this is how [VTK does it](https://www.vtk.org/gitweb?p=VTK.git;a=blob;f=CMake/vtkDetermineCompilerFlags.cmake;h=1398050afb34ff8c0a74137d847c19a6f63b12e9;hb=HEAD#l126):
```
## Enable /MP flag for Visual Studio 2008 and greator
IF(MSVC_VERSION GREATER 1400)
  SET(CMAKE_CXX_MP_FLAG OFF CACHE BOOL "Build with /MP flag enabled")
  SET(PROCESSOR_COUNT "$ENV{NUMBER_OF_PROCESSORS}")
  SET(CMAKE_CXX_MP_NUM_PROCESSORS CACHE ${PROCESSOR_COUNT} "The maximum number of processes for the /MP flag")
  IF (CMAKE_CXX_MP_FLAG)
    SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /MP${CMAKE_CXX_MP_NUM_PROCESSORS}")
    SET(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} /MP${CMAKE_CXX_MP_NUM_PROCESSORS}")
  ENDIF ()
ENDIF()
```
Unfortunately, it seems parallel building is (truly) available only for MSVC projects and not nmake makefiles.

Disclaimer: I know nothing about VTK and very little about CMake.

**Comment by NikitaFeodonit** [comment]
CMake has the module "ProcessorCount" to determine the number of processors/cores:
```
# Enable /MP flag for Visual Studio 2008 and greater
if(MSVC_VERSION GREATER 1400)
  include(ProcessorCount)
  ProcessorCount(CPU_CNT)
  if(CPU_CNT GREATER 0)
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /MP${CPU_CNT}")
    set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} /MP${CPU_CNT}")
  endif()
endif()
```

**Comment by tambry** [comment]
Why not just specify `/MP` by itself and have VS's build system automatically select how many threads to compile on (which usually is the maximum number of threads available)? AFAIK, there's no reason not to.

**Comment by TcT2k** [comment]
I've also used just /MP and that should be enough

**Comment by NikitaFeodonit** [comment]
It would be possible to set the necessary flags at the command line without changing the CMake scripts:
```
cmake ..\ -DCMAKE_CXX_FLAGS="/MP" -DCMAKE_C_FLAGS="/MP" -DCMAKE_BUILD_TYPE=Release && cmake --build . --config Release
```

**Comment by vadz** [comment]
I'll let people who know more about this than me add the appropriate CMake-ism to enable `/MP` (why doesn't it do it by default??), but it's not a blocker, so let me merge this already and we can improve it later with other PRs.

Thanks again Tobias for all your work!

**Comment by NikitaFeodonit** [comment]
> It would be possible to set the necessary flags at the command line without changing the CMake scripts:
> ```
> cmake ..\ -DCMAKE_CXX_FLAGS="/MP" -DCMAKE_C_FLAGS="/MP" -DCMAKE_BUILD_TYPE=Release && cmake --build . --config Release
> ```

Only as a note to my previous post for those who will read in the future.

Giving the compilation flags to the command line with CMAKE_C_FLAGS and CMAKE_CXX_FLAGS for MSVC is a bad idea. On another project I found the following.

If the flag "/MP" is set in CMake file like so:
```
if(wxBUILD_MSVC_MULTIPROC)
    set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} /MP")
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /MP")
endif()
```
then all is well and CMake passes, among other equal, such flags:
```
 /MP
 /W3
 /D WIN32 /D _WINDOWS
 /EHsc
 /GR
```

If the flag "/MP" is set in command line like so:
```
cmake ..\ -DCMAKE_CXX_FLAGS="/MP" -DCMAKE_C_FLAGS="/MP" .......
```
then all is bad and CMake passes, among other equal, such flags:
```
 /MP
 /W1
```
That is, in particular, such flags are not passed:
```
 /D WIN32 /D _WINDOWS
```
аnd all checks IF(WIN32) do not pass.

**Pull request merged**
