### PR TITLE
Croatian translation - initial release, complete

### PR DESCRIPTION
**Pull request by milotype**

### CODE REVIEW

**Comment by vadz** [comment]
Thanks for your contribution! I've merged it and added you as Croatian translator at [this page](http://www.wxwidgets.org/about/translations/), hopefully you don't mind -- but please let me know if you do, of course.

**Comment by vadz** [comment]
Oops, I made a typo (pasto?) in 7a5e649b9e090850b61dc71ef25f2876e3de49eb commit message, so this didn't get closed automatically.

**Comment by milotype** [comment]
Your welcome, and no, I don't mind ... you only need to update the page maybe at some pont => "Last Updated: Sat, 08 Sep 2018 08:00:46 GMT" ;-)

**Comment by milotype** [comment]
Or did you mean this page:
https://docs.wxwidgets.org/3.0/page_translations.html#page_translations_howtohelp

**Comment by milotype** [comment]
Will you also update the status of the laguages on the following websites? Presently you don't have infos on the croatian language.
http://www.wxwidgets.org/about/translations/
https://docs.wxwidgets.org/3.0/page_translations.html#page_translations_howtohelp

**Comment by vadz** [comment]
The page on wxwidgets.org is supposed to update automatically, but it obviously got broken... I'll look into this, but it might not happen a.s.a.p.

**Comment by tierra** [comment]
Looks like you just missed adding it to:
https://github.com/wxWidgets/website/blob/master/about/translations/translations.js#L12-L54

**Comment by vadz** [comment]
Oops, thanks, for some reason I thought all the existing translations were picked up automatically.

**Pull request closed without merging**
