### PR TITLE
Force D2DRenderTarget's DPI to 96

### PR DESCRIPTION
**Pull request by Kumazuma**
See #23486

### CODE REVIEW

**Comment by Kumazuma** [comment]
In https://learn.microsoft.com/en-us/windows/win32/api/d2d1/nf-d2d1-id2d1rendertarget-setdpi,

> For [ID2D1HwndRenderTarget](https://learn.microsoft.com/en-us/windows/win32/api/d2d1/nn-d2d1-id2d1hwndrendertarget), the DPI defaults to the most recently factory-read system DPI. The default value for all other render targets is 96 DPI.

it seems that that DPI occurs auto scaling like the issue, so I forces DPI to 96 then resulting output become same.

**Comment by vadz** [comment]
Sorry, I still don't understand how could hardcoding 96 DPI here could possibly be correct.

Have you seen Maarten's comment in #23486? Doesn't it help to fix the problem?

**Comment by Kumazuma** [comment]
The maarten's solution works well. However it is bypass as avoiding using ID2DHwndRenderTarget.
D2D is seems that logical pixels is not same as physical pixels because D2DHwndRenderTarget's DPI is not 96(100% scale)
I think that reason is other D2DRenderTarget's DPI set to 96 that the maarten's solution works well.
So Output differ between GDIPlusRenderer and Direct2DRenderer targeting to wxWindow.

**Comment by Kumazuma** [comment]
This show effect about D2DHwndRenderTarget's DPI

```cpp
#include <wx/wx.h>
#include <wx/graphics.h>
#include <d2d1.h>
#include <wrl.h>

template<typename T>
using ComPtr = Microsoft::WRL::ComPtr<T>;

#pragma comment(lib, "d2d1.lib")

class App: public wxApp
{
public:
    bool OnInit() override;
};

constexpr wxWindowID ID_DPI_COMBOBOX = 1001;

class Dialog: public wxDialog
{
public:
    Dialog(wxWindow* parent);
    wxComboBox* m_pComoBox;
};

Dialog::Dialog(wxWindow* parent)
    : wxDialog(parent, wxID_ANY, wxS("DPI"))
{
    m_pComoBox = new wxComboBox(this, ID_DPI_COMBOBOX);
    m_pComoBox->AppendString("96");
    m_pComoBox->AppendString("120");
    m_pComoBox->AppendString("168");
    m_pComoBox->AppendString("192");
    wxDialog::Layout();
}

class Frame: public wxFrame
{
    DECLARE_EVENT_TABLE();
public:
    Frame();
protected:
    void OnPaint(wxPaintEvent& evt);
    
private:
    Dialog* m_pDialog;
    ComPtr<ID2D1Factory> m_factory;
    int m_dpi;
};

bool App::OnInit()
{
    if (!wxApp::OnInit())
        return false;

    auto pFrame = new Frame{};
    pFrame->SetClientSize(800, 800);
    pFrame->Show();
    
    return true;
}

Frame::Frame()
    : wxFrame(nullptr, wxID_ANY,wxS("Transform"), wxDefaultPosition, wxSize{800, 800})
{
    m_pDialog = new Dialog{ this };
    m_pDialog->Show();

    D2D1CreateFactory(D2D1_FACTORY_TYPE_SINGLE_THREADED, __uuidof(ID2D1Factory), &m_factory);
    auto clientRect = GetClientSize();
    ComPtr<ID2D1HwndRenderTarget> hwndRenderTarget;
    m_factory->CreateHwndRenderTarget(
        D2D1::RenderTargetProperties(),
        D2D1::HwndRenderTargetProperties(
            GetHWND(),
            D2D1::SizeU(clientRect.GetWidth(), clientRect.GetHeight())
        ), &hwndRenderTarget);
    float dpiX = 0.f;
    float dpiY = 0.f;
    hwndRenderTarget->GetDpi(&dpiX, &dpiY);
    m_dpi = static_cast<int>(dpiY);
    wxString text;
    text.sprintf(wxS("%d"), m_dpi);
    m_pDialog->m_pComoBox->ChangeValue(text);
    m_pDialog->m_pComoBox->Bind(wxEVT_COMBOBOX, 
        [this](wxCommandEvent&)
        {
            int dpi;
            wxString value = m_pDialog->m_pComoBox->GetValue();
            if(value.ToInt(&dpi))
            {
                m_dpi = dpi;
                this->Refresh();
            }
        });
}

wxBEGIN_EVENT_TABLE(Frame, wxFrame)
EVT_PAINT(Frame::OnPaint)
wxEND_EVENT_TABLE()

void Frame::OnPaint(wxPaintEvent& evt)
{
    wxPaintDC dc{ this };
    auto clientRect = GetClientSize();
    ComPtr<ID2D1HwndRenderTarget> hwndRenderTarget;
    m_factory->CreateHwndRenderTarget(
        D2D1::RenderTargetProperties(),
        D2D1::HwndRenderTargetProperties(
            GetHWND(),
            D2D1::SizeU(clientRect.GetWidth(), clientRect.GetHeight())
        ), &hwndRenderTarget);
    float dpi = static_cast<float>(m_dpi);
    hwndRenderTarget->SetDpi(dpi, dpi);
    ComPtr<ID2D1SolidColorBrush> whiteBrush;
    ComPtr<ID2D1SolidColorBrush> blackBrush;
    ComPtr<ID2D1StrokeStyle> strokeStyle;
    hwndRenderTarget->CreateSolidColorBrush(D2D1::ColorF{ D2D1::ColorF::White }, &whiteBrush);
    hwndRenderTarget->CreateSolidColorBrush(D2D1::ColorF{ D2D1::ColorF::Black }, &blackBrush);
    m_factory->CreateStrokeStyle(D2D1::StrokeStyleProperties(), nullptr, 0, &strokeStyle);
    hwndRenderTarget->BeginDraw();
    hwndRenderTarget->Clear(D2D1::ColorF(D2D1::ColorF::Gray));
    hwndRenderTarget->FillRectangle(D2D1::RectF(0, 0, 200, 200), whiteBrush.Get());
    hwndRenderTarget->SetDpi(96.f, 96.f);
    hwndRenderTarget->DrawRectangle(D2D1::RectF(0, 0, 200, 200), blackBrush.Get());
    hwndRenderTarget->EndDraw();
}

wxIMPLEMENT_APP(App);
```
[wxTransforms.zip](https://github.com/wxWidgets/wxWidgets/files/11323571/wxTransforms.zip)

**Comment by vadz** [comment]
I'm sorry but I'm totally lost here and don't understand what does this code is trying to do/demonstrate. Could you please try to explain it in words?

**Comment by Kumazuma** [comment]
1.  The GraphicsContext created by Direct2DRenderer::createContext(wxWindow*)  is use ID2D1HwndRenderTarget.
2. ID2D1HwndRenderTarget has Window's DPI initally.
3. When ID2D1RenderTarget's DPI is not 96, the logical pixels is not same as physical pixels.
4. So I try ID2D1HwndRenderTarget'DPI hardcode to 96

**Comment by Kumazuma** [comment]
And I want to show rescaling as HwndRenderTarget's DPI.
```
    hwndRenderTarget->FillRectangle(D2D1::RectF(0, 0, 200, 200), whiteBrush.Get());
    hwndRenderTarget->SetDpi(96.f, 96.f);
    hwndRenderTarget->DrawRectangle(D2D1::RectF(0, 0, 200, 200), blackBrush.Get());
```
Rectangle's rect is same but actual size is not.

When it's DPI is 96
image
And when it's DPI is 120
image

**Comment by vadz** [comment]
Thanks, I'll try to look at it. I hadn't realized that `ID2D1RenderTarget` used logical pixels different from physical pixels -- which seems to be unique among Windows APIs. I wonder if there is a way to disable this...

Also, can you confirm that you don't observe pixel doubling when using this change at 200% DPI?

P.S. Wait, why did you close it?

**Pull request closed without merging**
