### PR TITLE
wxDVC on Mac: revert performance breaking commits

### PR DESCRIPTION
**Pull request by vslavik**
I give up on untangling the performance-affecting changes and fixing remaining issues with #2381.

I think it is the best course of action now. Revert the issues, revert the introduced inconsistency (row height adjustment). Release 3.2, and then re-introduces fixes for whatever else these patches were addressing, in a more considered manner. For example, it surely does make sense to keep the freeze/thaw optimization 4a0f6c4a6c34c261085c67698eefd0f6d7085b8e from #2381, but it is too entangled with d2fc88c03dcba3f2d533030d3fa83438dac016af to apply (and its version for after-this-PR tree would be considerably simpler, as most of it was dealing with the heights). 

Thus, this PR mostly reverts the problematic commits.

---

Reverts performance regressions:
- c9221fd538540bd6d105853d0f41620ed25102a5 Fix sizing of temporarily last columns in macOS wxDataViewCtrl
- 36ea7ff4d61e174a2d116819f98e66f22a7f5b8a Autosize the right columns in macOS wxDataViewCtrl
- 7555d1b2459949c128d6ee3a473669a1a134f124 Fix expansion of the last column in macOS wxDataViewCtrl

Reverts incorrect change that triggered lot of this and that shouldn't have been made in the first place, because it is inconsistent with other platforms (autosizing heights):
- d2fc88c03dcba3f2d533030d3fa83438dac016af Mac: Fix truncation of images in wxDataViewCtrl

Does **NOT** revert changes that seem good:
- b2675d6a60a398d8681d0bc47655a2d9c2411239 Fix sending event when cancelling editing in wxDVC under Mac 
- e89e76bb82f6d4bd96d1e6943099cd8bfd4e8292 Make wxCOL_WIDTH_AUTOSIZE work correctly in Mac wxDataViewCtrl (aka "account for expander width in width calculations")
- 9ee866551f98a994a241aa61d87bc8acf94cd2f5 Mac: Update column width when expanding/collapsing
- ...plus some other minor refactorings etc. from the same branches

And finally adds:
- 8d4ab94 Use -1 as uninitialized value for m_expanderWidth  — optimizes e89e76b, which is kept, in an edge case

### CODE REVIEW

**Comment by vadz** [comment]
Thanks Vaclav!

I'm going to have a look at it a.s.a.p. but I want to finally finish my locale-related changes first and I won't be able to work tomorrow, so this might have to wait until the week-end/Monday.

**Comment by discnl** [comment]
Thanks a lot Václav. I agree that it's actually best to first have the described state with this PR (3.1.4 with some improvements remaining) and then see from there (which should not be here, in this PR).

I have tested the dataview sample (with sample changes d04dfd6f2205d51bbf8224a29448b354843970ab) against 3.1.4, master, and this PR. Built and tested with macOS 11.5 using configure-based builds (Xcode 12.4) targeting x86-64. Also tested the same executables under 10.13.

> Reverts performance regressions:
> Reverts incorrect change

The reverts seem to work as intended: undesired row height adjustments and performance degradation appear only in master.

> Does **NOT** revert changes that seem good:

Likewise, these do not work in 3.1.4 but do in master and still function the same with this PR. For `wxCOL_WIDTH_AUTOSIZE` testing I used additional sample [changes](https://trac.wxwidgets.org/ticket/14939#comment:5).

> And finally adds:
> 
>  * [8d4ab94](https://github.com/wxWidgets/wxWidgets/commit/8d4ab945002c78e4f37ca5e10c89df1ec7c61c8e)

This, like f2324d53ecad8dc88240376225ea1d0969e3384c before, looks good.

I went through related tickets and PRs taking some notes and examples along the way. All master commits that are mentioned are also mentioned in the OP (or otherwise small and likely falling under "plus some other minor refactorings"). I also noticed your related branches since I tried one of your *dvc* ones, should have just fetched this PR or look for *dvd* ;). I really appreciate the effort this eventual PR also must have been, thanks again!

**Comment by vadz** [comment]
Thanks again! I'm merging this and reopening Trac 14939 and 19003 that had been fixed by the now reverted commits.

**Pull request merged**
