### PR TITLE
MSW: Link with imm32.dll

### PR DESCRIPTION
**Pull request by minoki**
Linking with imm32.dll will eventually be needed if we are going to support IME on Windows in future.

For the time being, the merit of this PR is, less conflicts between the master and [my IME branch](https://github.com/minoki/wxWidgets/commits/experimental-ime-support) when there is a build-system-related change in the master.  (i.e. working with my IME branch will be easier for me)

What's in this commit:
- Update build/bakefiles/common.bkl (and re-bake); for Makefiles and Visual C++ 200x project files.
- Update build/msw/wx_setup.props; for Visual C++ 201x project files.
- Update build/bakefiles/wxpresets/presets/wx_win32.bkl.
- Update include/msvc/wx/setup.h.

Once https://github.com/wxWidgets/wxWidgets/pull/330 is merged, the CMake files will also need updating.

### CODE REVIEW

**Comment by vadz** [comment]
We try avoiding adding new DLL dependencies if possible because this requires modifying all *user* make/project files too. If there is no other choice, we will still have to do this, of course, but we prefer to use MSVC-specific pragma to at least avoid breaking linking for MSVC users.

Also, how many functions from `imm32.dll` are we going to use? Could it be realistic to just load them dynamically?

**Comment by minoki** [comment]
## 1. Affected user projects
Am I right in assuming that, the projects that will be affected are ones that
- Link wxWidgets statically (i.e. projects that use wxWidgets as DLLs are not affected), and
- Don't use MSVC (because MSVC has `#pragma comment(lib,...)`), and
- Don't use `wx-config` script.

Well, maybe I need to send a PR to CMake to update [FindwxWidgets.cmake](https://github.com/Kitware/CMake/blob/master/Modules/FindwxWidgets.cmake).

## 2. Dynamically loading `imm32.dll`
The number of IMM32 functions that would be used is not so large, so writing stubs is feasible.  But I want to avoid writing stubs for a DLL that existed at least for two decades...

Can't we just merge this PR and postpone this discussion until when we are actually supporting IME?  It should be harmless for user projects until IMM32 API is actually used in wx.

## 3. MSVC `#pragma`
I noticed there are two places to add `#pragma comment`: `include/msvc/wx/setup.h` and `include/wx/msw/libraries.h`.  Which is more appropriate?

In this PR, `#pragma comment` is already added to `include/msvc/wx/setup.h`.

**Comment by a-wi** [comment]
Please don't forget about potentially troublesome MinGW ecosystem.
I think that imm32 should be coupled with technique already used to couple msimg32 - see [src\msw\dc.cpp](https://github.com/wxWidgets/wxWidgets/blob/master/src/msw/dc.cpp#L54).

**Comment by vadz** [comment]
@minoki You're right, this basically only affects MinGW users using static libraries and it's true that loading functions dynamically is painful, especially as MinGW also doesn't have delay loading support (AFAIK). I don't know if it's worth it here...

Concerning the header to use for the pragma: if you also add `imm32.dll` to the bakefiles, it is enough to put this one in `msvc/wx/setup.h`, but if you don't include it at bakefile level, it wouldn't be enough as this header is not included when building wxWidgets, so it doesn't take care of linking wx DLLs with `imm32.dll`. IOW what you did is just fine, but another possibility could be to put the pragma directly in the code using it and then avoid modifying the bakefiles for MSVC at all (they still need to be modified for MinGW, of course).

Finally, it seems a bit strange to me to apply this PR immediately, even if we don't need it yet. Why would this be useful? It will still apply once the rest of your changes is done and it would make more sense to merge them together.

**Comment by minoki** [comment]
@vadz The reason why I make this PR now is, to avoid merge conflict in the future.
Among the commits in the IME branch, this one is the most likely to cause merge conflict.
Therefore, I thought it a good idea to make a separate PR for this commit, but apparently I wasn't careful enough to pay attention to user projects that link to wx statically.

@a-wi Of course, I'm not going to forget MinGW ecosystem.

**Comment by vadz** [comment]
Sorry, but I don't think it's useful to keep this open any more. We'll merge this together with the real IME changes when they're ready.

**Pull request closed without merging**
