### PR TITLE
Fix reading GIF images where the encoder has chosen not to emit a CLE…

### PR DESCRIPTION
**Pull request by Carnildo**
…AR code when the alphabet is full

Fixes bug #22799.

### CODE REVIEW

**Comment by vadz** [comment]
Thanks! We should apply this, of course, but it would be really nice to add a (small, if possible) GIF showing the problem and a test checking that loading it now succeeds to `tests/image/image.cpp` to ensure that the problem stays fixed in the future. Could you please do it?

Thanks again!

**Comment by Carnildo** [comment]
I don't know how to create a GIF that shows the issue, I can only test on found images.  The ones I'm aware of are dkulp's turkey, at 250kb and an unknown license, and the 600kb image I discovered it with which has a CC-BY-SA 4.0 license.  Is either of these suitable?

**Comment by vadz** [comment]
It's a bit bigger than I'd like, but we have ~150KB images in `tests/image`, so I guess 250KB is not a big deal.

@dkulp Can your image be included in wx test suite, licence-wise?

**Comment by vadz** [comment]
Without response about the turkey image licence we can't include it, so I'm going to apply the patch without the test case, which is not ideal, but better than not resolving the bug at all.

Thanks once again for the fix!

**Pull request closed without merging**
