### PR TITLE
Fix missing initialization of member variables in constructor.

### PR DESCRIPTION
**Pull request by orbitcowboy**

### CODE REVIEW

**Comment by vadz** [comment]
Thanks, will merge.

**Comment by orbitcowboy** [comment]
> Thanks, will merge.

Thanks. The CI failure looks unrelated.

**Comment by imciner2** [comment]
@vadz can this be backported to 3.2? It is nicely contained and it tripped the Coverity checker we run (it identified the missing initialization in 3.2.1).

**Comment by vadz** [comment]
Sure, done now.

**Pull request closed without merging**
