### PR TITLE
Add compatibility support for wxIconBundle to wxBitmapBundle

### PR DESCRIPTION
**Pull request by Runtemund**

### CODE REVIEW

**Comment by vadz** [comment]
This seems useful, thanks. Could you please

- Fix the build errors due to missing includes.
- Rebase on master to get rid of all the extra merges.
- Add `@since 3.1.7` to the new function documentation.

? TIA!

**Comment by Runtemund** [comment]
Can you please explain what exactly to do here: `Rebase on master to get rid of all the extra merges.` ? I have not yet completely understood the logic of git.

**Comment by vadz** [comment]
> Can you please explain what exactly to do here: `Rebase on master to get rid of all the extra merges.` ? I have not yet completely understood the logic of git.

Just run `git rebase master` while being on your branch: this will replay all the commits on your branch from the tip of the (latest) master. If this results in any difficult to resolve conflicts, you can always abandon with `git rebase --abort` and use an alternative approach by creating a new branch from master (i.e. `git checkout -b bmpbndl-iconbndl-new`) and then cherry picking just the commits you need from your old branch and finally, after checking that the branch contents is identical (`git diff add_icobdl_to_bmpbdl bmpbndl-iconbndl-new` should show nothing), remove the old branch (`git branch -D add_icobdl_to_bmpbdl`) and rename the new branch to the old name (`git branch -m bmpbndl-iconbndl-new add_icobdl_to_bmpbdl`).

Note that you will need to "force push", i.e. use `git push --force-with-lease`, after doing either rebasing or cherry-picking.

**Comment by Runtemund** [comment]
Thank you, that helped a lot. But I am not sure if I can omit all commits. The first PR were erroneously done from master.., maybe this has an impact...

The error messages of the builds are not very help full to me. I have included "wx/iconbndl.h" as a precaution. Everything is compiling fine here. I also have no idea what's missing.

Although I can also work under linux, I don't understand where else the error could lie. I have the feeling that the build breaks at another point, but the automatic builds here are new to me, so maybe I missed something.

**Comment by Runtemund** [comment]
Hm, one job (Unix builds / Ubuntu 20.04 wxGTK with ASAN (pull_request) ) if failing. I have no idea what 

`ERROR: jinja2 3.1.1 has requirement MarkupSafe>=2.0, but you'll have markupsafe 1.1.0 which is incompatible.`

in the log means. And above all, how could I fix it...?

**Comment by vadz** [comment]
The remaining error is due to a [bug in ASAN](https://github.com/google/sanitizers/issues/1353) that we can't do anything about, unfortunately. I believe it's the first time it crashed twice in a row, let's hope it's just bad luck... I'll rerun it once again to check.

As for commits, you don't have to omit all of them, of course, you can combine them in as many or as few commits as needed with `git rebase -i`. But I'll just do a (squash) merge myself for this one.

**Pull request closed without merging**
