### PR TITLE
Print preview layout and appearance fixes

### PR DESCRIPTION
**Pull request by vadz**

### CODE REVIEW

**Comment by vadz** [comment]
> I think the [example code in the documentation](https://github.com/wxWidgets/wxWidgets/blob/f43efa6b46caf091bb9f354080a12ee6aec3002e/docs/doxygen/overviews/printing.h#L60) should also be adapted to these changes, not only the printing sample.

Absolutely, thanks for noticing this, I've removed the size (and position) from the docs too.

**Comment by taler21** [comment]
Since f0de5a93f8c, the size passed to the `wxPreviewFrame` constructor no longer has any effect.
I am wondering if this size should matter if specified explicitly. What do you think?

**Comment by vadz** [comment]
> Since [f0de5a9](https://github.com/wxWidgets/wxWidgets/commit/f0de5a93f8cca76a0a073fc4900e7f37b0b6d624), the size passed to the `wxPreviewFrame` constructor no longer has any effect. I am wondering if this size should matter if specified explicitly. What do you think?

You're right once again, we should take the user-specified size into account. I've done this now, even though this was a bit cumbersome due to the unusual API of this class.

Please let me know if you see any other problems.

**Comment by taler21** [comment]
Works fine now. Thanks.

Just a final note or question.
In commit 4925550 you only applied two changes of the three I [suggested](https://github.com/wxWidgets/wxWidgets/issues/22439#issuecomment-1133547699).
Was that intentional or is it a mistake?

**Pull request merged**
