### PR TITLE
Replace -1 with wxCOL_WIDTH_DEFAULT in wxDataViewColumn widths

### PR DESCRIPTION
**Pull request by wh11204**
Also mention wxCOL_WIDTH_AUTOSIZE

### CODE REVIEW

**Comment by vadz** [comment]
Thanks, will (squash) merge soon. Ideal would be to also explain the difference between `wxDVC_DEFAULT_WIDTH` and `wxCOL_WIDTH_DEFAULT` but I don't even know what it is myself without looking...

**Comment by wh11204** [comment]
`wxDVC_DEFAULT_WIDTH` is a fixed positive number (80) used for text columns.

**Comment by vadz** [comment]
Yes, sorry, I know/see that much. But it's not clear at all why and when would you use it instead of `wxCOL_WIDTH_DEFAULT` which should, I think, result in roughly the same width.

In fact the real question is whether we shouldn't just make `wxDVC_DEFAULT_WIDTH` a (deprecated) synonym for `wxCOL_WIDTH_DEFAULT`. I'd like to do it because `wxDVC_DEFAULT_WIDTH` doesn't even use logical pixels and so works differently depending on the current DPI which is clearly a bug.

**Comment by vadz** [comment]
I still think we need to do something about `wxDVC_DEFAULT_WIDTH`, but for now I've merged these changes, as they're already an improvement, thanks!

**Pull request closed without merging**
