### PR TITLE
Remove TravisCI badge from readme

### PR DESCRIPTION
**Pull request by PBfordev**
Also for consideration:
1. Remove the Travis CI related scripts from the code repository.
2. Remove Travis badge and mention from http://wxwidgets.org/develop/

### CODE REVIEW

**Comment by vadz** [comment]
Yes, I think we should remove `.travis.yml` and all mentions of it. They've never answered my follow up email, so it doesn't seem like we should expect anything else from them, unfortunately. Would you consider doing this, as part of this PR or should I already merge this change? TIA!

**Comment by PBfordev** [comment]
I push a commit removing the two travis files from the codebase.

I will also prepare one for the website. I am going to remove it from the developers page but I am not sure about removing it from the Thanks page, it was very helpful for years. But it is in the section for the current sponsors. What do you think about this, @vadz?

**Comment by vadz** [comment]
Thanks, but, looking at `git grep -il travis`, there are more mentions of Travis in our sources. Most seem trivial to remove, so I'll do it if you don't, but, of course, if you can do it too, it would be great.

Concerning the web site, I agree that we should keep them somewhere, but separate from the services that we currently use.

**Comment by PBfordev** [comment]
Sorry, I did not realize there may be those mentions. I will look into this tomorrow.

**Comment by PBfordev** [comment]
Now the only remaining Travis mentions I found (aside from the 3rd party code) are those in tests. They come in two forms (each occurs twice).
https://github.com/wxWidgets/wxWidgets/blob/d3eafa4d185d8c98d4178a4f4937d3b800d8128d/tests/controls/gridtest.cpp#L618-L622
The one above seems to apply to [more ](https://github.com/wxWidgets/wxWidgets/blob/d3eafa4d185d8c98d4178a4f4937d3b800d8128d/tests/test.cpp#L399)than just Travis, while those like the one below look Travis-only and could be safely removed
https://github.com/wxWidgets/wxWidgets/blob/d3eafa4d185d8c98d4178a4f4937d3b800d8128d/tests/test.cpp#L368-L376

However, I know little about tests code so I'd rather not touch it at all.

**Comment by vadz** [comment]
Thanks! I've removed the mentions of Travis from the tests too now, but the last commit here is speculative, as the checks might still be necessary for AppVeyor and/or GitHub CI, let's see if they are -- if the CI builds fail, I'll undo this commit and merge all the rest.

**Comment by vadz** [comment]
They did fail, so not merging the last commit.

**Pull request closed without merging**
