### PR TITLE
Performance updates and fixes for OSX DataView

### PR DESCRIPTION
**Pull request by dkulp**
1) If the view is frozen, don't calculate the autosize columns for each change
2) On Thaw, calculate the autosize columns
3) If last column is set for AUTOSIZE, use the autosize
4) Set a minimum size for the last column to avoid it being set to 0 by osx if the width of all the columns is wider than the view

### CODE REVIEW

**Comment by softwarefailure** [comment]
Thanks, but it doesn't seem to be working correctly with the dataview sample. The "Artist" column is much too small. See this screenshot:

Bildschirmfoto 2021-04-29 um 19 50 00

**Comment by dkulp** [comment]
Pushed an additional commit that fixes that artist column size issue.

**Comment by softwarefailure** [comment]
Thanks, seems to be working nicely now.

On another note, I think we should get rid of the `sizeLastColumnToFit` stuff because this breaks consistency with MSW and GTK. With the current implementation on macOS, because of `sizeLastColumnToFit` the text in the last column will always be ellipsized in case it exceeds the available space in the last column. On MSW and GTK this doesn't happen. Instead, the last column's size is increased so that the text fits into it. On macOS the text will always get ellipsized if it doesn't fit because the last column is hard-coded to never exceed the remaining space because we're using `sizeLastColumnToFit`.

**Comment by dkulp** [comment]
I'm not a fan of the sizeLastColumnToFit either... Not sure why it was added.  However, I believe you can easily work around it by setting minimum size for the last column or making the last column be AUTOSIZE.

**Comment by softwarefailure** [comment]
Actually, my last column is an AUTOSIZE one but it's still getting ellipsized. Presumably because of `sizeLastColumnToFit`...

**Comment by dkulp** [comment]
If the last column is autosize, then sizeLastColumnToFit is not called so it's not that.

**Comment by softwarefailure** [comment]
Right, it's the `NSTableColumnAutoresizingMask` flag that's causing the ellipsis. Removing that flag from the `setResizingMask` call in `CreateNativeColumn` solves the issue so probably that flag should only be set for AUTOSIZE columns.

**Comment by softwarefailure** [comment]
Found another problem with this patch: When the last column is AUTOSIZE and the window is resized, the last column suddenly receives all of the remaining space. Probably related to the `sizeLastColumnToFit` call in `OnSize`. I'm attaching a modified minimal sample created by @discnl that shows the issue. Just click "Set Col 0 Text" and then "Send Size Event" to see it. [minimal.cpp](https://github.com/wxWidgets/wxWidgets/files/6405801/minimal.txt)

In order to fix this you'd probably need some input from @vadz as to how AUTOSIZE should behave when used on the last column, i.e. should it make the column as wide as the largest entry or should it always expand the column to occupy all of the remaining space? AFAIR people said that when AUTOSIZE is used on the last column it should always make the last column as wide as the remaining space (or wider if necessary, to avoid ellipsation) for consistency with MSW and GTK but I'm not sure.

**Comment by vadz** [comment]
AFAIR GTK widget always extends the last column to fill the available space, even when it's auto-sized, and I don't see anything wrong with doing the same thing under Mac too, especially as I don't remember seeing any space being left empty under Mac, I believe only MSW programs do this (sometimes). But if more Mac-savvy people think it should fit its exact size, this would be fine too, we don't _have_ to be consistent across platforms, even if it's nice to do it by default.

But it's much more important to follow the current platform conventions, so we should do the same thing other Mac programs do.

**Comment by softwarefailure** [comment]
> AFAIR GTK widget always extends the last column to fill the available space, even when it's auto-sized, and I don't see anything wrong with doing the same thing under Mac too, especially as I don't remember seeing any space being left empty under Mac

The problem is the case when the column's text is wider than the remaining space. When using `NSTableColumnAutoresizingMask` or `sizeLastColumnToFit` (as it is currently the case) the text will be truncated instead of horizontal scrollbars being added. This looks rather ugly. Currently, it will look like this on macOS: (all three columns are AUTOSIZE)

Bildschirmfoto 2021-05-01 um 13 02 42

Whereas on GTK it looks like this which is much better IMHO:

Bildschirmfoto vom 2021-05-01 12:50:57

On Windows the behavior is also like on GTK, i.e. a scrollbar is added instead of truncating the last column's text.

**Comment by vadz** [comment]
Yes, I'd prefer GTK behaviour too personally. But, again, how common are horizontal scrollbars in the lists/tables under macOS? If they're never used, perhaps we shouldn't use them neither...

Anyhow, the real question is what to do with this PR, i.e. does it make things better, worse or roughly the same?

Also, why are there some row-height-related changes here, are they somehow linked to the column widths?

**Comment by softwarefailure** [comment]
> Yes, I'd prefer GTK behaviour too personally. But, again, how common are horizontal scrollbars in the lists/tables under macOS? If they're never used, perhaps we shouldn't use them neither...

Well, but it's also a matter of common sense. `wxCOL_WIDTH_AUTOSIZE` is defined as "size the column to automatically fit all values". Currently, it doesn't do that on macOS for the last column because it truncates the text.

> Anyhow, the real question is what to do with this PR, i.e. does it make things better, worse or roughly the same?

I think the idea of disabling autosize calculations while the widget is frozen is very useful because otherwise it really becomes unusably slow. There's one regression in this PR, though: See here: https://github.com/wxWidgets/wxWidgets/pull/2352#issuecomment-830117240 This used to work with 3.1.5 but this PR breaks it.

> 
> Also, why are there some row-height-related changes here, are they somehow linked to the column widths?

The code that calculates the maximum row width is also used to calculate the maximum row height. That's why I was calling `FitColumnWidthToContent` for non-autosize columns as well. This caused the horrible slowdown @dkulp experienced.

**Comment by dkulp** [comment]
I'm pretty sure that what we need to do is on the LAST column, if it's autofit, set the minWidth to the autofit size.   That would allow the scroll bar to appear if needed instead of shrinking down to almost nothing.   The problem with that is that users then cannot make the column smaller.  I don't know what would happen if we set the Min, call sizeLastColumnToFit, and then reset the min back to 0.   I can experiment a bit with that, but I cannot today.

**Comment by softwarefailure** [comment]
Why not just set the column width to the auto fit size instead of the column minWidth? That would make the appearance correct while still allowing the user to make the column smaller.

**Comment by dkulp** [comment]
That's exactly what my patch currently does.   But it then isn't sizeLastColumnToFit so it doesn't take up the entire space.

**Comment by softwarefailure** [comment]
Ok, so maybe the remaining space could be computed to avoid using `sizeLastColumnToFit`? And then use something like `[column setWidth:max(remainingSpace, autofitSize)];` so that the column width is made to fill the remaining space in case the autofit size is less than the remaining space and if the auto fit size is more than the remaining space, the auto fit size is used...

**Comment by dkulp** [comment]
Pushed a fix for the resize.   I THINK this now should cover all the cases we mentioned above.  It seems to work find for the dataview sample and the modified minimal sample as well as for my own app where the last column is almost always scrolled off to the side (and thus sizeLastColumnToFit would set it to 0).

**Comment by softwarefailure** [comment]
Yes, it fixes all but one case: In case the text doesn't fit, it is still ellipsized although the column is set to autosize. 
See this sample: [minimal.txt](https://github.com/wxWidgets/wxWidgets/files/6409837/minimal.txt)

Bildschirmfoto 2021-05-01 um 17 36 47

I think it is caused by the `NSTableColumnAutoresizingMask` flag. According to the docs, this will autoresize the last column to fit the remaining space AFAIU.

**Comment by vslavik** [comment]
Another problem with `sizeLastColumnToFit:` is that it is a performance hog (hopefully the last one in the recent regressions).  It causes the view to repaint even when it's a no-op and doesn't really change the width. IOW, right now every time anything changes in wxDVC, the entire control is redrawn.

**Comment by softwarefailure** [comment]
> Another problem with `sizeLastColumnToFit:` is that it is a performance hog (hopefully the last one in the recent regressions). It causes the view to repaint even when it's a no-op and doesn't really change the width. IOW, right now every time anything changes in wxDVC, the entire control is redrawn.

Yes, I think this should be fixed before applying the PR. As I said, this PR works nicely with all my tests except this one: https://github.com/wxWidgets/wxWidgets/pull/2352#issuecomment-830651726 (which is directly related to `sizeLastColumnToFit`). I think we should get rid of `sizeLastColumnToFit` completely or use it only in case the last column's contents aren't wider than the remaining space so that text doesn't get ellipsized. Note that, as mentioned above, just removing `sizeLastColumnToFit` might not be enough since `NSTableColumnAutoresizingMask` also seems to do something very similar to `sizeLastColumnToFit`.

**Comment by vslavik** [comment]
This avoids excessive calculations if the expander column happens to be hidden: https://github.com/vslavik/wxWidgets/commit/f2324d53ecad8dc88240376225ea1d0969e3384c — this takes care of the worst of it for me, together with your fixes.

@dkulp Do you want me to push it to your branch?

**Comment by vslavik** [comment]
An obvious related optimization would be to do 
```cpp
    if (GetColumn(pos)->IsHidden())
        return;
```
at the top of `wxCocoaDataViewControl::FitColumnWidthToContent()` but I am unsure about the consequences for when the column would be un-hidden — I'm almost sure some recalculation logic for that is missing, but am unsure where it would go...

**Comment by softwarefailure** [comment]
I think I have found a way to get rid of `sizeLastColumnToFit` now and I think I've also fixed the ellipsation issue. Now someone needs to tell me how I can get my changes into this PR. I have done this to check out this PR:

```
git clone --recurse-submodules https://github.com/wxWidgets/wxWidgets.git
cd wxWidgets
git checkout -b mylocalbranch
git pull origin pull/2352/head
```

After checking out this PR like shown above I have added my fixes to `dataview.mm`. How to proceed now? I don't know anything about git so the best idea is probably if someone can post what I have to enter in terminal to post my changes here just like @vslavik has done above with his changes.

**Comment by vadz** [comment]
I don't think you can update this PR, as it wasn't created by you, so please create a new one.

Just make sure to leave a comment there explaining that it _replaces_ this one. TIA!

**Comment by softwarefailure** [comment]
Sorry, don't really know how to do that. Here is the patch:

```
diff -uNr wxWidgets-dkulp/src/osx/cocoa/dataview.mm wxWidgets/src/osx/cocoa/dataview.mm
--- wxWidgets-dkulp/src/osx/cocoa/dataview.mm	2021-05-01 17:24:22.000000000 +0200
+++ wxWidgets/src/osx/cocoa/dataview.mm	2021-05-23 17:20:54.000000000 +0200
@@ -364,7 +364,7 @@
     int resizingMask;
     if (column->IsResizeable())
     {
-        resizingMask = NSTableColumnUserResizingMask | NSTableColumnAutoresizingMask;
+        resizingMask = NSTableColumnUserResizingMask;
         [nativeColumn setMinWidth:column->GetMinWidth()];
         [nativeColumn setMaxWidth:column->GetMaxWidth()];
     }
@@ -2246,7 +2246,7 @@
     wxDataViewColumnNativeData *nativeData = GetColumn(pos)->GetNativeData();
     NSTableColumn *column = nativeData->GetNativeColumnPtr();
     UInt32 const noOfColumns = [[m_OutlineView tableColumns] count];
-
+   
     class MaxWidthCalculator
     {
     public:
@@ -2400,33 +2400,28 @@
         // previous width in that case because it must not get lost.
         nativeData->SetPrevWidth(GetColumn(pos)->GetWidth());
 
-        if ( GetColumn(pos)->GetWidthVariable() == wxCOL_WIDTH_AUTOSIZE )
-        {
-            [column setMinWidth:autoWidth];
-            [m_OutlineView sizeLastColumnToFit];
-            int minW = GetColumn(pos)->GetMinWidth();
-            [column setMinWidth:minW];
-        }
-        else
-        {
-            int minW = GetColumn(pos)->GetMinWidth();
-            if (minW == 0) {
-                [column setMinWidth:10];
-            } else {
-                [column setMinWidth:minW];
-            }
-            [column setMinWidth:minW];
-            [m_OutlineView sizeLastColumnToFit];
-            if (minW == 0) {
-                [column setMinWidth:0];
-            }
-        }
+        // Compute the remaining space for the last column; note that we
+        // deliberately don't use sizeLastColumnToFit() because it causes a
+        // refresh of the NSTableView; using sizeLastColumnToFit() would also
+        // require us to temporarily enable NSTableColumnAutoresizingMask on
+        // the NSTableColumn because it doesn't seem to work without it
+        NSSize size = [[m_OutlineView superview] bounds].size;
+        size.width -= (noOfColumns * [m_OutlineView intercellSpacing].width);
+        for ( UInt32 k = 0; k < noOfColumns - 1; k++ ) {
+            NSTableColumn *c = GetColumn(k)->GetNativeData()->GetNativeColumnPtr();
+            size.width -= [c width];
+        }
+        
+        int lastColWidth = ceil(size.width);
+           
+        if ( GetColumn(pos)->GetWidthVariable() == wxCOL_WIDTH_AUTOSIZE && autoWidth > lastColWidth ) lastColWidth = autoWidth;
+
+        if ( lastColWidth > 0 )
+            [column setWidth:lastColWidth];
     }
     else if ( GetColumn(pos)->GetWidthVariable() == wxCOL_WIDTH_AUTOSIZE )
     {
         [column setWidth:autoWidth];
-        int minW = GetColumn(pos)->GetMinWidth();
-        [column setMinWidth:minW];
     }
     else if ( nativeData->GetIsLast() )
     {
@@ -3911,7 +3906,7 @@
 {
     wxDataViewColumnBase::SetResizeable(resizable);
     if (resizable)
-        [m_NativeDataPtr->GetNativeColumnPtr() setResizingMask:NSTableColumnUserResizingMask | NSTableColumnAutoresizingMask];
+        [m_NativeDataPtr->GetNativeColumnPtr() setResizingMask:NSTableColumnUserResizingMask];
     else
         [m_NativeDataPtr->GetNativeColumnPtr() setResizingMask:NSTableColumnNoResizing];
 }

```

**Comment by vadz** [comment]
> Sorry, don't really know how to do that. Here is the patch:

Please create a branch with your changes, push it to GitHub and follow the URL that is output when you do `git push`. It's really not difficult and would be very helpful as I'm really not sure what is this patch relative to (i.e. which tree should it be applied to) and we've had multiple problems in the past due to confusion about your patches. Of course, please free to ask if you have any questions or run into any problems but it's really much simpler, faster and less difficult to create a PR rather than juggle with patches.

TIA!

**Comment by softwarefailure** [comment]
So I tried `git push` and got this:

> fatal: The current branch mylocalbranch has no upstream branch.
> To push the current branch and set the remote as upstream, use
> 
>     git push --set-upstream origin mylocalbranch

Then I tried `git push --set-upstream origin mylocalbranch` and got this:

> Username for 'https://github.com': softwarefailure
> Password for 'https://softwarefailure@github.com': 
> remote: Permission to wxWidgets/wxWidgets.git denied to softwarefailure.
> fatal: unable to access 'https://github.com/wxWidgets/wxWidgets.git/': The requested URL returned error: 403

How to proceed from here?

**Comment by vslavik** [comment]
> How to proceed from here?

Again, you need to create a PR - i.e. have a branch *on your fork* (based on the branch of this PR, with my commit above cherry-picked into it, then your applied), submit as PR.

**Comment by softwarefailure** [comment]
How can I create a fork based on #2352? When I click on "Fork" I seem to be forking wxWidgets master and not #2352...

**Comment by vadz** [comment]
I assume you already have your fork, i.e. softwarefailure/wxWidgets repository. If you don't have it yet, please create it first. Also make sure you have a local remote configured for it, e.g. `my_fork`. If you didn't configure a remote yet, do it using `git remote add my_fork git@github.com:softwarefailure/wxWidgets`.

Next:

1. Fetch the current changes from this PR using `git fetch https://github.com/dkulp/wxWidgets.git TICKET_19166` command.
2. Create a new local branch for your work based on them with `git checkout -b osx-dataview-columns FETCH_HEAD` (the name of the branch is up to you, but `FETCH_HEAD` refers to the result of the previous git-fetch and must be used as is).
3. Make more more commits on this branch. Please try to describe them in a useful way to help with understanding what do they do.
4. Push your local branch to your fork: `git push my_fork HEAD`.
5. Follow the URL shown in your terminal to create the new PR (or just open GitHub in your browser and use the button that will be shown there).
6. If you need to update the PR later, add more commits to the same branch and push again, the PR will be updated automatically.

Good luck!

**Comment by softwarefailure** [comment]
Thanks for the instructions! I've created #2381 with my changes.

**Pull request closed without merging**
