### PR TITLE
Fix inert wxDVC toggle cells being editable under macOS

### PR DESCRIPTION
**Pull request by vadz**
I'm not sure if we should include the first commit (change to the sample), but I've included it at least for in case you'd like to test it yourself. The real change is in the second one and, somewhat surprisingly, this seems to work in all ports without any port-specific changes being necessary: for the generic port it's because `wxDataViewToggleRenderer::Render()` already checks for `GetMode() != wxDATAVIEW_CELL_ACTIVATABLE` in addition to `GetEnabled()` and for wxGTK `wxDataViewToggleRenderer` ctor also already checks for `wxDATAVIEW_CELL_ACTIVATABLE`.

cc: @bigjohnr

### CODE REVIEW

**Comment by vadz** [comment]
@vslavik, @bigjohnr I'm going to merge this tomorrow, before 3.1.1-rc1, so if you have any comments/objections, please let me know until then.

**Review by vslavik — APPROVED** [review]
Sorry for late response. Thanks a lot for doing this! 

Looks good to me — no comments about the code, except that I share your surprise. I take it as a confirmation that this was a reasonable change to make.

**Comment by vadz** [comment]
I've finally left out the sample change and committed just 3a1625030314f501effb9620f5b39b470b2435c3

Thanks for the review!

**Comment by bigjohnr** [comment]
There doesn't seem to be an easy way to have both inert and enabled so I think this is a good option.

**Pull request closed without merging**
