### PR TITLE
Fix to build wxGTK under Win32

### PR DESCRIPTION
**Pull request by stahta01**
I have gotten wxGTK to build on windows using MSys2 GCC (Rev1, Built by MSYS2 project) 6.3.0

mkdir -p build_wxGTK-gtk3 && cd build_wxGTK-gtk3 && \
  ../configure --target=i686-w64-mingw32 --with-gtk=3 && \
  make
cd ..

I have NOT tested if the libraries that are built are usable.

Tim S.

### CODE REVIEW

**Comment by vadz** [comment]
Thanks! I thought wxGTK was supposed to be already compilable under Windows thanks to the work done by @kosenko, but apparently this was only when using `makefile.gcc`, not with configure, thanks for fixing this!

I don't see any real problems here, but it would be nice if somebody could check that at least the minimal sample can be built and run now before merging this.

Also, an update to the README explaining where to get the GTK+ libraries for Windows would probably be useful.

**Comment by stahta01** [comment]
@vadz : I will work on testing the minimal sample; but, the readme will be beyond me except for how to do it under MSys2. I am already working on a MSys2 package (They use ArchLinux packages) to build wxWidgets from git repo source. Tim S.

**Comment by stahta01** [comment]
The minimal sample failed for me using the MSys2 package build method.
Will try the more normal way in a few days. The sample built; but, did not respond after running.
Tim S.

**Comment by kosenko** [comment]
Actually wxGTK/Win32 makefile compilation was disabled because of (MinGW) makefiles generate a lot of warnings because of bakefile build system defects. wxGTK/Win32 Visual C++ project files wasn't enabled because additional build configurations can annoy developers. So wxGTK/Win32 can be build only using bakefiles generator as described in wxWidgets/docs/msw/gtk.txt.

This patch looks like designed for wxGTK/X11/Windows, but not wxGTK/Win32 and it could broke wxGTK/Win32.

wxGTK build works fine with X11 GDK-backend under Linux and Win32 GDK-backend under Windows. I think you should explain what is wrong with Cygwin/MSYS/MSYS2 and why you disable features.

Note that under wxGTK/Win32 `__UNIX__` is **NOT** defined, but `__WINDOWS__` is defined. But under Cygwin and probably MSYS/MSYS2 both `__UNIX__` and `__WINDOWS__` are defined. So you should exclude case when both `__UNIX__` and `__WINDOWS__` are defined to fix wxGTK/X11/Windows build.

**Pull request closed without merging**
