### PR TITLE
Implement wxSYS_COLOUR_HOTLIGHT for GTK2 (requires GTK+ >= 2.10)

### PR DESCRIPTION
**Pull request by obfuscated**

### CODE REVIEW

**Comment by vadz** [comment]
I've blindly added GTK 2.10 checks and merged this, thanks!

**Comment by obfuscated** [comment]
Would it be possible to backport this to 3.0?

**Comment by vadz** [comment]
@doscott Is it too late for 3.0.5 or can this still be cherry-picked in time for it?

**Comment by doscott** [comment]
It’s not too late.

**Comment by vadz** [comment]
I've now cherry-picked this one as well as a previous commit changing the same code (to avoid conflicts), thanks.

**Pull request merged**
