### PR TITLE
Add workflow for cross-building wxMSW on GitHub Actions

### PR DESCRIPTION
**Pull request by vadz**
Use MinGW to build and Wine to run the GUI tests.

### CODE REVIEW

**Comment by adiantek** [comment]
Using https://github.com/mstorsjo/llvm-mingw we could compile it to windows arm64 (devices like surface pro x)

**Comment by vadz** [comment]
The correct option to use to disable OpenGL support is `--without-opengl`. PRs adding ARM support would be, of course, welcome, but I still need to fix (and merge) this one first...

**Comment by adiantek** [comment]
Thanks, I compiled it for arm64, but wxWidgets/samples/widgets won't:
```
root@cb0f2559de4e:/build/wxWidgets/samples/widgets# make
aarch64-w64-mingw32-windres -i../sample.rc -owidgets_sample_rc.o    --define __WXMSW__        --include-dir . --define WXUSINGDLL --define wxUSE_DPI_AWARE_MANIFEST=2 --include-dir ./../../samples --include-dir /build/wxWidgets/lib/wx/include/aarch64-w64-mingw32-msw-unicode-3.1 --include-dir ../../include
llvm-rc: Error in 24 statement (ID 1): 
Is a directory
aarch64-w64-mingw32-windres: error: llvm-rc failed
Makefile:319: recipe for target 'widgets_sample_rc.o' failed
make: *** [widgets_sample_rc.o] Error 1

root@cb0f2559de4e:/build/wxWidgets/samples/widgets# aarch64-w64-mingw32-windres -i../../samples/sample.rc -oaccesstest_sample_rc.o    --define __WXMSW__        --include-dir . --define WXUSINGDLL --define wxUSE_DPI_AWARE_MANIFEST=2 --include-dir ./../../samples --include-dir /build/wxWidgets/lib/wx/include/aarch64-w64-mingw32-msw-unicode-3.1 --include-dir ../../include -v
aarch64-w64-mingw32-clang -E -xc -DRC_INVOKED=1 -D__WXMSW__ -DWXUSINGDLL -DwxUSE_DPI_AWARE_MANIFEST=2 -I. -I./../../samples -I/build/wxWidgets/lib/wx/include/aarch64-w64-mingw32-msw-unicode-3.1 -I../../include ../../samples/sample.rc -o accesstest_sample_rc.o.preproc.rc 
llvm-rc -I . -I ./../../samples -I /build/wxWidgets/lib/wx/include/aarch64-w64-mingw32-msw-unicode-3.1 -I ../../include -I ../../samples accesstest_sample_rc.o.preproc.rc -c 1252 -fo accesstest_sample_rc.o.out.res 
llvm-rc: Error in 24 statement (ID 1): 
Is a directory
aarch64-w64-mingw32-windres: error: llvm-rc failed
root@cb0f2559de4e:/build/wxWidgets/samples/widgets# llvm-rc -I . -I ./../../samples -I /build/wxWidgets/lib/wx/include/aarch64-w64-mingw32-msw-unicode-3.1 -I ../../include -I ../../samples accesstest_sample_rc.o.preproc.rc -c 1252 -fo accesstest_sample_rc.o.out.res -v
Identifier: aaaaaaaa
Identifier: ICON
String: "sample.ico"
Identifier: sample
Identifier: ICON
...
Icon (wxICON_SMALL_REMOVEABLE): "wx/msw/removble.ico"
Bitmap (csquery): "wx/msw/csquery.bmp"
Bitmap (wxBITMAP_STD_COLOURS): "wx/msw/colours.bmp"
User-defined (type: 24, name: 1): "wx/msw/"
llvm-rc: Error in 24 statement (ID 1): 
Is a directory

root@cb0f2559de4e:/build/wxWidgets# grep -R "wx/msw/\""
samples/widgets/accesstest_sample_rc.o.preproc.rc:1 24 "wx/msw/" "arm64" "_dpi_aware_pmv2.manifest"
include/wx/msw/wx.rc:    #define wxMANIFEST_FILE "wx/msw/" wxRC_STR(wxMANIFEST_CPU) wxRC_STR(wxMANIFEST_DPI)
```

**Comment by vadz** [comment]
The macros in `include/wx/msw/wx.rc` don't seem to be expanded as expected, although I don't really see why, please try looking at the preprocessed output (if `llvm-rc` has `-E` or similar option). This is not really the best place to discuss it though, as it's not really related to the changes in this PR...

**Pull request merged**
