### PR TITLE
Document updating docs.wxwidgets.org for the releases

### PR DESCRIPTION
**Pull request by vadz**
Ideal would be to make it possible to override Doxygen options without modifying the files (e.g. do it on the fly in `regen.sh`), but for now I've just documented the steps that I use -- please let me know if you see something wrong, TIA!

### CODE REVIEW

**Comment by doscott** [comment]
I gave this a try (not the uploading part).

I had an error in the cherry-pick, but I don't think its a problem:

dos@DOS5:~/wxWidgets$ git cherry-pick master
error: could not apply 9f3ad89ba9... Update some documentation to reflect change of default GTK version for configure
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'

What is not clear to me is:
 - after ssh into docs.wxwidgets.org am I in the public_html/trunk folder or do I need to change to it?
 - is that the folder that I would scp the html files generated locally, or a subfolder from there?
 - after running the script and copying the files to the public_html/x.y.z folder, do I delete the files from the html/trunk folder (or wherever the answers to the previous 2 questions takes us)?
 - where are the files contaiing the links that need to be switched?

**Comment by vadz** [comment]
Something went very wrong here :-( The last master commit should always be "Custom changes needed for docs.wxwidgets.org.", not "Update some documentation to reflect change of default GTK version for configure". I don't understand if you did this on wxdocs?

When you ssh into this machine you're in the home directory, I think things will be more clear if you run `ls -l` once you're there. It contains `public_html` and `wxWidgets` subdirectories, with the former containing all the files visible on the web and the latter the Git checkout.

**Comment by doscott** [comment]
I just started from scratch:

dos@DOS5:~$ git clone https://github.com/wxWidgets/wxWidgets.git
Cloning into 'wxWidgets'...
remote: Enumerating objects: 9, done.
remote: Counting objects: 100% (9/9), done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 805298 (delta 0), reused 2 (delta 0), pack-reused 805289
Receiving objects: 100% (805298/805298), 316.99 MiB | 11.60 MiB/s, done.
Resolving deltas: 100% (671296/671296), done.
dos@DOS5:~$ cd wxWidgets
dos@DOS5:~/wxWidgets$ git fetch --tags
dos@DOS5:~/wxWidgets$ git checkout -b temp v3.0.5
Switched to a new branch 'temp'
dos@DOS5:~/wxWidgets$ git config merge.renamelimit 15000
dos@DOS5:~/wxWidgets$ git cherry-pick master
error: could not apply 9f3ad89ba9... Update some documentation to reflect change of default GTK version for configure
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'

**Comment by tierra** [comment]
That's actually because the top commit with custom changes for docs.wxwidgets.org is just a local commit on the server. It's not pushed up anywhere, so you wouldn't have that commit.

These instructions look correct to me. I'd just add one more thing, and that's updating the symlinks for the dynamic paths (i.e. updating `public_html/3.0` to point to `public_html/3.0.5`):

```
cd public_html
ln -sfn 3.0.5 3.0
```

**Comment by doscott** [comment]
I see now that the docs are being generated on the server, not being transferred to the server.

**Comment by vadz** [comment]
Thanks, I've added `ln -sfn` command (TIL about `ln -n`, I always did `rm 3.1; ln -s` before...).

**Pull request closed without merging**
