### PR TITLE
config.cmake fix for macOS

### PR DESCRIPTION
**Pull request by valid-ptr**
See #2359

### CODE REVIEW

**Comment by vadz** [comment]
Thanks, looks good to me (although I can't help wondering if there is no better abstraction in CMake to take care of this...), so I'll merge it if @MaartenBent doesn't have any objections.

**Review by MaartenBent — APPROVED** [review]
Looks good, I didn't consider macOS in my previous fix.

Just a remark about the comment behind it, maybe add `-l` too, since that is what is was originally intended for.

**Comment by MaartenBent** [comment]
I checked macOS and it also has `libz.tbd` and `libiconv.tbd`. Maybe add `.tbd` too?

**Comment by vadz** [comment]
FWIW I don't think you should ever use `.tbd` files directly, so I don't think we should be checking for them neither.

**Pull request merged**
