### PR TITLE
Fix wrong wxMenuItem::GetBitmap return type documentation

### PR DESCRIPTION
**Pull request by MaartenBent**
This API changed after adding wxBitmapBundle support.

### CODE REVIEW

**Comment by MaartenBent** [comment]
This API change became apparent when `erlang` bindings did not work with wxWidgets 3.1.6 in macOS homebrew (see https://github.com/Homebrew/homebrew-core/pull/99206 and https://github.com/erlang/otp/issues/5893).

**Comment by vadz** [comment]
Thanks, I'll apply this in a moment with minor changes (I'll remove the top-level `const` too).

**Comment by MaartenBent** [comment]
Oh indeed, I missed that one somehow.

**Comment by dgud** [comment]
Do the API really need to change here?

It makes it really hard for me to be able to generate code that compiles against wxWidgets-3.0.* and wxWidgets-3.1.6  (and everything in between)  and I do require that  **--enable-compat-3.0**  is enabled.

**Comment by MaartenBent** [comment]
To keep the API the same, the `wxMenuItem` `wxBitmap` member(s) have to be restored. Then we can assign the value of `wxBitmapBundle` to these bitmaps and return those.

The disadvantage is having both a `wxBitmapBundle` and `wxBitmap` that contain basically the same bitmap.

I don't see a problem doing this, either always or only for `WXWIN_COMPATIBILITY_3_0`. What do you think @vadz ?

**Comment by vadz** [comment]
There are many places where we replaced `wxBitmap` with `wxBitmapBundle` and had to replace the accessors returning `const wxBitmap&` to return `wxBitmap`. I naively thought that this wouldn't result in (m)any compatibility problems and I still don't understand what exactly is the problem, doing as if `wxBitmap` were always returned should work in any case.

I'd strongly prefer not to do anything here, but if we really have to preserve the compatibility, the only reasonable way to do it would be to add `const wxBitmap& GetBitmap()` to `wxBitmapBundle` itself, as this would allow us to add this `m_bitmap` in one place instead of a dozen ones or more.

@dgud Could you please explain what the problem is here, preferably on wx-dev? TIA!

**Comment by MaartenBent** [comment]
The problem is in the linked issue (https://github.com/erlang/otp/issues/5893). This gives an error now, while it used to work:
```c++
    wxMenuItem* item = new wxMenuItem();
    const wxBitmap* bmp = &item->GetBitmap();
```
`error: taking the address of a temporary object of type 'wxBitmap' [-Waddress-of-temporary]`

**Comment by vadz** [comment]
I had no idea people wrote (or generated) code like this :-( FWIW the right thing to do is to just
```cpp
const wxBitmap& bmp = item->GetBitmap();
```
and this works with all versions.

Is it feasible to change the code to do this instead or do we really need to add the compatibility hack?

**Comment by dgud** [comment]
That would be me and my patched C skills, I can patch the generator and test after the weekend, I'm currently AFK.
Not on mac though and I didn't see the warnings when I tested on windows,  but I'll take another look. I need to patch anyway since windows.h can't be included before the wx headers.

**Comment by dgud** [comment]
I send the pointer to the object to erlang (i.e. another thread), now I need clone the object if I understand things
correctly and then the erlang programs will start to leak memory since the users have never needed destroy that bitmap 
object before.

**Comment by MaartenBent** [comment]
When I look at the `wxe_wrapper` files, you already do something similar for `wxStaticBitmap::GetBitmap`.
Instead of this for `wxMenuItem`
```c++
const wxBitmap * Result = &This->GetBitmap();
```
it generates
```c++
wxBitmap * Result = new wxBitmap(This->GetBitmap()); app->newPtr((void *) Result,3, memenv);;
```

Could you use the same approach?

**Comment by dgud** [comment]
Oh, I thought this was a general change that would change a lot of code, but this was the only place that affected me.
I patched my branch of the interface file for menuitem as you suggested and it works fine.
Thanks @MaartenBent for all the help.

PS: Not ready to rebase all the interface files to wxWidgets master, since I suspect that will take a lot of time that I don't have right now.

**Comment by MaartenBent** [comment]
Thanks for your fast work.

Do you mean it still works fine with your current wxWidgets version, or did you also test if the generated code works with `wx3.1.6`? I'm trying to prevent any new surprises when wxWidgets gets updated in homebrew.

**Comment by dgud** [comment]
It works ( the generated code compiles :-) ) with default ubuntu-20, i,e, ~3.0.4  and 3.1.6.
Will run it in our nightly builds and see that it works on all platforms we have, before merging.
And it will be included in the next patch release whenever that happens.
PR at erlang/otp#5912

**Comment by MaartenBent** [comment]
Sounds good, thanks again.

**Pull request closed without merging**
