### PR TITLE
Don't call GetBestSize() from DoGetSizeFromTextSize() in wxOSX

### PR DESCRIPTION
**Pull request by vadz**
This could easily result in infinite recursion, as it is very natural to
implement DoGetBestSize() in terms of GetSizeFromTextSize() and, in
fact, our own implementation of the generic wxSpinCtrl did exactly this.

Avoid such problems by only calling GetSizeFromTextSize() from
DoGetBestSize(), but not in the other direction.

This shouldn't have any effect on the returned size values.

---

@wangqr Please let me know if I broke your recent fixes with this.

### CODE REVIEW

**Comment by wangqr** [comment]
It seems that multiline wxTextCtrl now defaults to 1 line high in ed2141d7d7f2ffe9bd6fc97fa0425f44c4ad5a7a.

**Comment by vadz** [comment]
Oops, thanks for testing. I guess this is because the size from `GetTextPeer()->GetBestSize()` is returned directly, without passing via `DoGetSizeFromTextSize()` at all. I convinced myself this wouldn't actually happen because in this case the width would be completely wrong too, but actually testing this under Mac myself right now, I see that it does happen and that the best size is indeed wrong, i.e. creating a multiline `wxTextCtrl` without specifying its width explicitly actually gives it tiny width, which is definitely a bug and I just don't understand why nobody has reported it until now.

But wait, there are more problems here... in fact, the initial control contents is not taken into account at all when determining its best size because it's only set later, after the best size is cached, due to the changes of 63bcc669d81774a91f39054e8ec44f8d7ac6f760. So this doesn't work at all as it's supposed to and I thought... I'm afraid this needs many more changes and while I'm, as usual, very afraid of breaking something in wxMac, I think I'm going to make them because this is just too wrong.

**Comment by csomor** [comment]
I'll look at the sequence as well, since we are not supporting Carbon anymore, there might also be other options for rearranging things

**Comment by vadz** [comment]
Hi, I'm testing some changes here, key me show them to you first (hopefully today).

**Comment by vadz** [comment]
OK, I think this is the best I can do for now: the changes so far shouldn't change the actual behaviour of the code, except for fixing the initial width for multiline text controls created with `wxDefaultSize`, which is now correctly 100 and not 10 (!) as before.

This change also implements `DoGetBestSize()` in terms of `DoGetSizeFromTextSize()`, as in the other ports, so that we don't need special workarounds to avoid infinite recursion under Mac as discussed in 39d586421ba3fdfa095e4392a857c3be602b9fe7.

Please let me know if this still breaks anything -- and I'll post to wx-dev about the remaining problem with the inconsistent default size among ports.

**Comment by wangqr** [comment]
Looks good to me for e5ce18f0cbfe60ba8ff6419ca092da418a8647ca.

**Comment by vadz** [comment]
Thanks again for testing! @csomor Please let me know if you have any objections to me vandalising your code. If not, I'll merge this relatively soon as I'd also like to fix the default number of lines issue about which I [posted to the list](https://groups.google.com/d/msg/wx-dev/yQsUNeiFp1E/ej4wWlQvAwAJ).

**Comment by csomor** [comment]
I'm going through the steps of changes now, I'll come back with questions to understand ...

**Review by csomor — APPROVED** [review]
(sorry, this was meant regarding the `SetStringValue` changes)

Unfortunately I don't have any recollection, nor have I found any pointer to the original bug which my change apparently solved. The value is now still set before MacPostControlCreate. But since the latter does not do any embedding now, this is done earlier. The crash would not occur anymore anyway.

**Pull request merged**
