### PR TITLE
gtk: map GDK_KEY_Launch1/2 to WXK_LAUNCH_APP1/2

### PR DESCRIPTION
**Pull request by martinetd**
Hello,

For context, I have a button mapped to KEY_PROG1 (linux input-event-code.h code) which maps to Xf86launch1/GDK_KEY_Launch1 and cannot use it in wxwidget.
The key could eventually be remapped with a bit of work (either xkb config or at driver/evdev level), but I'm probably not the only one with that problem and would like to discuss some possible way forward.

Here's the commit message of my initial suggestion to work on:
```
gtk: map Xf86Launch1/2 to WXK_LAUNCH_APP1/2

X11 defines Xf86Launch[0-9a-f], which are then also defined as
GDK_KEY_Launch[0-9A-F].

Unfortunately, keys which are not mapped are just plain ignored and the
application is then not able to receive these keyboard events at all.

The original PR https://github.com/wxWidgets/wxWidgets/pull/157 mapped
only LaunchA/B to WXK_LAUNCH_APP1/2, this patch also maps Launch1/2 to
these.
It would probably be better to add more LAUNCH_APPx to correspond to all
the available keys, but that might be difficult to map all of these to
other platforms so reuse the symbols here.
```

Note it might also make sense to just map all of the Xf86launchX bindings e.g. odd -> APP1, even -> APP2 or something like that?
As written in the commit message I'm not sure it'd make sense to just add more symbols, but I'd like some sort of event to be able to act on even if it's a bit difficult to grasp -- the current gtk code just ignores all keys it doesn't know about (e.g. ascii or hard coded list) but it's not really practical in the case a button is mapped to some weird key... So another possibility would perhaps be a "RAW" key that just exposes underlying keycode? Application portability is not a concern in my case, so I would have little qualm of hardcoding GDK_KEY_xyz in my application if I could.

Thanks!

### CODE REVIEW

**Comment by vadz** [comment]
Thanks, I agree that doing what this PR does is better than ignoring the keys completely, but it's not a very high bar and it seems rather strange to map 2 different GDK key codes to the same key, so I'd like to propose adding `WXK_LAUNCH_APP_n` for `n` in `0..F` range and map the GDK key codes to them. For compatibility, we'd define `WXK_LAUNCH_APP{1,2}` (note the lack of underscore), as `WXK_LAUNCH_APP_{A,B}`. Do you think you could modify the code to do it like this instead? AFAICS it should be simple enough and would seem to be cleaner than generating the same event for the different keys.

As for a more general, albeit less portable, solution, I think it would also be a good idea toallow generating key events with unknown (to wx) key codes, i.e. generate an event object whose `GetKeyCode()` and `GetUnicodeKey()` would both return `WXK_NONE` but which provide access to the low-level key via `GetRawKeyCode()`, as this would at least allow to handle them in the application code using platform-specific tests -- and would seem to be enough for your use case. If you'd like to include the changes necessary to do this in this PR (or maybe create another PR later), this would be very welcome as well.

TIA!

**Comment by martinetd** [comment]
> Adding WXK_LAUNCH_APP_n

It's pretty easy to add more for gtk, but I honestly wouldn't know what to do with msw... although now I'm looking at it osx/cocoa does not have any such binding at all so portability might not be as important as I'm thinking it is for these keys?
In that case I can just add the new enum values to gtk + common headers + richtext/samples and leave msw out.

> generic way

Oh, I didn't know about GetRawKeyCode -- I think it'd make sense to bubble up an event with WXK_NONE in this case and let the apps deal with it, most of the code seems already there for that. I'd assume most applications just ignore keys they don't recognize so if GetKeyCode starts returning WXK_NONE it probably won't break too much but that might require more testing, so will do that in another PR when I can find time.
I think it makes sense to do both if having more WXK_LAUNCH_APP_x symbols are welcome.

**Comment by vadz** [comment]
> > Adding WXK_LAUNCH_APP_n
> 
> It's pretty easy to add more for gtk, but I honestly wouldn't know what to do with msw... 

If there are no corresponding `VK_XXX` available, there is not much we can do.

> although now I'm looking at it osx/cocoa does not have any such binding at all so portability might not be as important as I'm thinking it is for these keys? In that case I can just add the new enum values to gtk + common headers + richtext/samples and leave msw out.

Yes, I think this should be fine (and the only sample I'd update would actually be `samples/keyboard`, see `GetVirtualKeyCodeName()` there).

Perhaps it would make sense to use the same names as GDK, i.e. just `WXK_LAUNCH_n` for those, and keep `WXK_LAUNCH_APP{1,2}` as (non-deprecated) synonyms for `WXK_LAUNCH_{A,B}`. Please also update `interface/wx/defs.h` and use `@since 3.1.6` for the new symbols (this should have been done for the existing ones too, but was forgotten).

> > generic way
> 
> Oh, I didn't know about GetRawKeyCode -- I think it'd make sense to bubble up an event with WXK_NONE in this case and let the apps deal with it, most of the code seems already there for that. I'd assume most applications just ignore keys they don't recognize so if GetKeyCode starts returning WXK_NONE it probably won't break too much but that might require more testing, so will do that in another PR when I can find time. I think it makes sense to do both if having more WXK_LAUNCH_APP_x symbols are welcome.

Yes, they are.

Thanks!

**Comment by vadz** [comment]
Looks great, thanks! I wouldn't have even bothered to preserve the numeric values of `WXK_LAUNCH_APP{1,2}`, but if you've taken the trouble to do it, let's do it like this -- I'll merge this in a moment.

Thanks again!

**Comment by vadz** [comment]
Sorry, after looking at this a bit more, I finally decided to tweak this to avoid the complications due to preserving the constants values. Please let me know if you have any objections to my changes, that I've pushed now or see anything wrong. TIA!

**Comment by martinetd** [comment]
> Sorry, after looking at this a bit more, I finally decided to tweak this to avoid the complications due to preserving the constants values. Please let me know if you have any objections to my changes, that I've pushed now or see anything wrong. TIA!

Thanks for the extra comments.

As for the enum reordering, I don't personally mind but I have a couple of warnings:

- preserving value would allow ABI compatibility (changing value like you did means that a wxWidgets update requires recompiling any child application that expects to see these keys), so I assumed it'd be important, but if you're fine with this I don't have any problem either. (As far as I know distros normally require a soname bump (e.g. libwx_gtk3u_core-3.1.so.6 -> .so.7) to help applications act on this kind of changes....)
- whoever adds new keys next will need to explicitly set it as WXK_LAUNCH_F +1 or a new offset bigger than this, because enums are kind of dumb and will just increment from last value, so if leaving whatever new key at default value it'll equal to WXK_LAUNCH_C. They should notice this when they add the keys to the keyboard sample and compile it though (multiple identical case statements error in the switch), so I guess this is also probably fine?

If this is ok with you I'm happy either way.

**Comment by vadz** [comment]
> As for the enum reordering, I don't personally mind but I have a couple of warnings:
> 
>     * preserving value would allow ABI compatibility (changing value like you did means that a wxWidgets update requires recompiling any child application that expects to see these keys), so I assumed it'd be important, but if you're fine with this I don't have any problem either. (As far as I know distros normally require a soname bump (e.g. libwx_gtk3u_core-3.1.so.6 -> .so.7) to help applications act on this kind of changes....)

You're absolutely right and it would be important in the stable (with even-valued minor version component) branch, but we can allow to not preserve the ABI in 3.1.x.

>     * whoever adds new keys next will need to explicitly set it as WXK_LAUNCH_F +1 or a new offset bigger than this, because enums are kind of dumb and will just increment from last value, so if leaving whatever new key at default value it'll equal to WXK_LAUNCH_C. They should notice this when they add the keys to the keyboard sample and compile it though (multiple identical case statements error in the switch), so I guess this is also probably fine?

I hope it is, people should be able to add the new values before the aliases and if they don't, it would hopefully be caught by the review...

**Comment by martinetd** [comment]
All good with me then :)

One last question for my culture: interface/wx/defs.h is only there for documentation purpose and it's OK if values there don't match with include/wx/defs.h as no actual code should be using it?

**Comment by vadz** [comment]
> One last question for my culture: interface/wx/defs.h is only there for documentation purpose and it's OK if values there don't match with include/wx/defs.h as no actual code should be using it?

Yes, absolutely. This is one of the advantages of keeping the documentation separate from the code itself: we can pretend that things are nicer than they really are, e.g. by omitting the implementation details, and hide all the mess in the real headers.

**Pull request merged**
