### PR TITLE
Add DPI Awareness option to .vc and msvc files

### PR DESCRIPTION
**Pull request by MaartenBent**
Follow-up of #1622.

### CODE REVIEW

**Comment by vadz** [comment]
Thanks a lot!

Just a question: do you think we should include ARM CPU targets in the makefiles too or do you think that nobody will build the ARM binaries using nmake anyhow?

**Comment by MaartenBent** [comment]
There are no dpi-aware ARM manifests, so for now I don't think it is necessary.

**Comment by vadz** [comment]
The CI problems seem to be real for once. I guess we just can't use these options with MSVS 2008 (and surely earlier), but the failure to launch the test in MSVS 2015 build is even worse... I didn't have time to test it locally yet to see if I can reproduce it.

**Comment by MaartenBent** [comment]
> MSVS 2015

It uses the x32 manifest for an x64 application. I think because [`CPU=X64`](https://github.com/wxWidgets/wxWidgets/blob/master/build/msw/config.vc#L57) is not given as argument.

Also the msbuild-build does not use the manifest for the test projects. I have to update those `vcxproj` files as well.

**Comment by vadz** [comment]
Thanks again, this is certainly going to make life much more convenient!

**Pull request merged**
