### PR TITLE
Allow zero scroll pixels per line for wxGrid

### PR DESCRIPTION
**Pull request by gvcallen**
This commit allows for m_xScrollPixelsPerLine and m_yScrollPixelsPerLine to be set to zero by adding an explicit check for division by zero.

By setting the pixel scroll size to 0, the effect is that the scrollbar is not displayed when otherwise needed. This is desirable and allows for the user to toggle off the scrollbar when necessary using the functions wxGrid::SetScrollLineX and wxGrid::SetScrollLineY.

### CODE REVIEW

**Comment by vadz** [comment]
Should we still close `Scroll()` and `AdjustScrollbars()` in this case? I.e. shouldn't we just add the check for `m_xScrollPixelsPerLine` and `m_yScrollPixelsPerLine` to the check above, like this:
```diff
diff --git a/src/generic/grid.cpp b/src/generic/grid.cpp
index 41fd4524cf..ff1ae1994c 100644
--- a/src/generic/grid.cpp
+++ b/src/generic/grid.cpp
@@ -8205,7 +8205,9 @@ void wxGrid::MakeCellVisible( int row, int col )
         }
     }
 
-    if ( xpos == -1 && ypos == -1 )
+    // Check that scrolling is actually enabled in at least one direction.
+    if ( (xpos == -1 || !m_xScrollPixelsPerLine) &&
+            (ypos == -1 || !m_yScrollPixelsPerLine) )
         return;
 
     if ( xpos != -1 )
```

?

Also, I think `ShowScrollbars(wxSHOW_SB_NEVER , wxSHOW_SB_NEVER )` might be a better way to hide the scrollbars, but we should still avoid crashing here, of course.

**Comment by gvcallen** [comment]
Thanks for the reply.

In this case I believe we will still crash if only one of m_xScrollPixelsPerLine or m_yScrollPixelsPerLine is 0. I do agree that we do not need to call Scroll() and AdjustScrollBars() however.

Would it work to rather have a separate check after the check for -1 to check if either is 0, and then simply return from there?

I am not sure how to attach a diff but will change it to that if all sounds good.

**Comment by vadz** [comment]
> In this case I believe we will still crash if only one of m_xScrollPixelsPerLine or m_yScrollPixelsPerLine is 0. I do agree that we do not need to call Scroll() and AdjustScrollBars() however.

Yes, sorry, you're rihht, of course. 

> Would it work to rather have a separate check after the check for -1 to check if either is 0, and then simply return from there?

I've pushed the commit with the simplest change (if you look at the diff with master) I see that should still actually work, unlike my suggestion above. If you don't see anything wrong with it, I'm going to (squash) merge it. Thanks!

**Comment by gvcallen** [comment]
This looks like it will work, however will behave as if m_xScrollPixelsPerLine or m_yScrollPixelsPerLine equals 1, when I believe "0" should warrant the behaviour of no scrollbar being displayed.

Should we not just set xpos and/or ypos to -1 if either variable is 0 respectively? Or do you not think it should behave that way?

**Comment by vadz** [comment]
Sorry, I just can't get this right, apparently :-( What about this, finally (diff with master):
```diff
diff --git a/src/generic/grid.cpp b/src/generic/grid.cpp
index 53f982f6e6..16492ec141 100644
--- a/src/generic/grid.cpp
+++ b/src/generic/grid.cpp
@@ -8064,8 +8064,9 @@ void wxGrid::MakeCellVisible( int row, int col )
          col < -1 || col >= m_numCols )
         return;

-    const bool processRow = row != -1;
-    const bool processCol = col != -1;
+    // We don't scroll in the corresponding direction if "pixels per line" is 0.
+    const bool processRow = row != -1 && m_yScrollPixelsPerLine != 0;
+    const bool processCol = col != -1 && m_xScrollPixelsPerLine != 0;

     // Get the cell rectangle in logical coords.
     wxRect r;
```
? It look like this should avoid doing even more unnecessary work when scrolling is disabled, as well as fixing the actual problem.

Please let me know if I'm missing something again, TIA!

**Comment by vadz** [comment]
I'm going to commit the patch above as it works (I've actually tested it now) and seems like the simplest solution.

**Comment by gvcallen** [comment]
Sorry for the late reply. Yes, seems like it will work! Where can I see once you've committed? Will it be on this branch?

**Pull request closed without merging**
