### PR TITLE
Notify clients of initial selection change in wxNotebook for wxQT

### PR DESCRIPTION
**Pull request by ffa-grahamdawes**
As a follow on from #1182.   wxNotebook now generates an event when the selection changes due to an initial page being added.  This makes the behaviour more consistent with the other ports.

### CODE REVIEW

**Review by vadz — CHANGES_REQUESTED** [review]
Sorry, I should have realized this when reviewing the previous change, but actually it was wrong and you shouldn't set `m_selection` directly but rather always call `SetSelection()` when adding the first page because it will already send the expected event. Could you please change the code to do it like this, for simplicity and clarity?

Also, do we already have a unit test checking that an event is sent on adding the first page? I don't see it immediately and if we don't have it, it would be great if you could please add one, to ensure that this is done consistently in all ports, including wxQt.

TIA!

**Comment by ffa-grahamdawes** [comment]
No problem,   I'll make the change and add the test.

**Comment by vadz** [comment]
Ah, looking at the code I see that wxQt doesn't send the event from `SetSelection()` itself, unlike wxMSW, but relies on getting it from Qt. In fact its `wxNotebook` implementation is rather weird and incomplete (doesn't send `PAGE_CHANGING` events at all AFAICS).

Let me try cleaning it up a little...

**Comment by vadz** [comment]
Thanks but from looking at the code it seems that wxMSW will _not_ send the events for selecting the initial page as `wxBookCtrlBase::DoSetSelectionAfterInsertion()`, which it uses in its `wxNotebook::InsertPage()`, explicitly uses `ChangeSelection()` and not `SetSelection()` in this case. And wxGTK doesn't seem to have any code for doing this neither.

Please let me test this and establish, using your new test, how the code actually behaves as we almost certainly want wxQt behave as wxMSW and wxGTK.

**Comment by vadz** [comment]
Curiousier and curiousier... wxMSW indeed doesn't send the event, but wxGTK does do it.

Time to test wxOSX.

**Comment by vadz** [comment]
I've replaced the first and last commits with #1192 and will commit the middle one separately in a moment.

Thanks for your work on this, it was useful even if I finally did something a bit different.

**Pull request closed without merging**
