### PR TITLE
CMake: change target names, check PCH support

### PR DESCRIPTION
**Pull request by MaartenBent**
Fix some CMake issues reported in wx-dev.

https://groups.google.com/forum/#!topic/wx-dev/HbZlxDxNqWw
Add a `wx` prefix to the library target names (resulting in `wxbase`, `wxcore`, etc). Using generic names as `core` and `base` could interfere with projects that include the wxWidgets project. Also add aliases using `wx::` prefix (resulting in `wx::base`, `wx::core`, etc).

This change should probably be mentioned in the changelog because it could break projects that depend on the current names.

https://groups.google.com/forum/#!topic/wx-dev/G4tFAqWUt0k
Use a test project to test if the used compiler supports precomiled headers. Also check if the output does not contain `had text segment at different address` warnings.

And fix some other issues I encountered.

### CODE REVIEW

**Review by TcT2k — APPROVED** [review]
When I see how many lines had to be changed I know why I felt this was too much work back than :)
The changes look good to me and it makes usage as submodule much easier.

**Comment by vadz** [comment]
Thanks a lot for your work on this!

Just one question: I saw some mention of aliases in the patch, does it mean that the existing user cmakefiles using the current library names will continue to work? If so, are the old names going to continue to be supported in the future or should we mention that they're deprecated in the docs?

**Comment by MaartenBent** [comment]
No, users that include the wxWidgets project using `add_subdirectory` cannot use the old library names anymore. They have to use `wx::base` or ` wxbase` instead of just `base`.

This only affects users that build the wxWidgets library themselves. This has nothing to do with CMake's own [FindwxWidgets](https://cmake.org/cmake/help/latest/module/FindwxWidgets.html) that is normally used to find the prebuild libraries and include dirs.

**Comment by vadz** [comment]
I'm fine with breaking compatibility for the projects using `add_subdirectory()` (which, BTW, I'd expect to be a popular way to consume wx, as it can be pretty useful to keep it in a submodule of the main repository), but shouldn't we at least document this in the "incompatible changes" section of the change log? Or is my expectation completely wrong and do you have some reasons to believe that nobody is doing this anyhow?

**Comment by MaartenBent** [comment]
I agree, I also mention this in the first message.

But since this uses `git notes`, I did not update `changes.txt`. I don't know if I have permissions to do this myself, but I would prefer if you could take care of this.

**Comment by vadz** [comment]
Oops, sorry, I've completely missed this part of your initial message.

We use notes for "small" changes that are all listed together, but incompatible changes still go to `docs/changes.txt` directly. I could do it myself as part of the merge, but I'm afraid of writing something stupid because of CMake-ignorance, so if you could do it, or write this paragraph here for me, it'd be great. TIA!

**Comment by MaartenBent** [comment]
That should cover it. If it is in the wrong tense, or in the wrong position, please correct it.

**Pull request merged**
