### PR TITLE
wxGenericValidator rewritten 2

### PR DESCRIPTION
**Pull request by AliKet**
(Notice that this is a WIP)

Unlike #752, this PR tries to make `wxGenericValidator` more flexible and more type-safe, i hope so.

### Things to be remarked:

1. This is **a breaking changes** rewrite (which is sad but unavoidable) i.e. both **ABI** and **API** compatibilities couldn't be preserved by these changes, unfortunately.

2. `wxGenericValidator` is no longer an ordinary class with a bunch of ctors. rather it is now a function template which does create an appropriate `wxGenericValidatorType` based on the window type (passed as template argument) and the deduced data type.

3. For a given wxWindow-derived class that should support generic validators, the current design imposes that the window in question or any of its bases should implement the `wxDataTransfer` interface (via template specialization) or just forward to the base that already implement it using this macro: `wxDECLARE_DATA_TRANSFER_FWD(Window, WindowBase);`
_____________________________________________________________________________________

### How it works:

Say you have a window `MyWindow` which can transfer `wxString`s and `CustomData`.
to make `MyWindow` able to transfer those data, then you have to specialize `wxDataTransfer<>` for `MyWindow` and implement the data transfer logic:

```
template<>
struct wxDataTransfer<MyWindow>
{
    static bool To(MyWindow* win, wxString* data)
    { /*implementation*/ }
    static bool From(MyWindow* win, wxString* data)
    { /*implementation*/ }

    static bool To(MyWindow* win, CustomData* data)
    { /*implementation*/ }
    static bool From(MyWindow* win, CustomData* data)
    { /*implementation*/ }
};
```
Then:
```
wxString str;
MyWindow* mywin = new MyWindow(...);
wxSetGenericValidator(mywin, &str);
```
will set a generic validator for `mywin` that can transfer `wxStrings` by means of `str` variable.

If, for ex. `MyWindow` derives from, say, `MyWindowBase` which itself already implements `wxDataTransfer<>` then you don't have to do anything but add this decl. `wxDECLARE_DATA_TRANSFER_FWD(MyWindow, MyWindowBase);` to make `wxGenericValidatorType` knows how to create validators for `MyWindow`.

### CODE REVIEW

**Comment by AliKet** [comment]
@vadz  can you help me with this annoying error (which happens with wxSpinCtrl in some configurations only !?)

Travis output:

In file included from ./dialogs.cpp:109:0:
../../include/wx/valgen.h: In static member function ‘static bool wxPrivate::wxDataTransferHelper<W, T>::To(wxWindow*, void*) [with W = wxSpinCtrl, T = int]’:
../../include/wx/valgen.h:126:83:   instantiated from ‘bool wxGenericValidatorType<W, T>::TransferToWindow() [with W = wxSpinCtrl, T = int]’
./dialogs.cpp:3975:1:   instantiated from here
../../include/wx/valgen.h:47:34: error: creating pointer to member of non-class type ‘wxIf<true, void, wxSpinCtrl>::value {aka void}’

**Comment by vadz** [comment]
On Sat, 16 Jun 2018 17:30:04 -0700 AliKet wrote:

A> @vadz  can you help me with this annoying error (which happens with wxSpinCtrl in some configurations only !?)
A> 
A> Travis output:
A> 
A> In file included from ./dialogs.cpp:109:0:
A> ../../include/wx/valgen.h: In static member function ‘static bool wxPrivate::wxDataTransferHelper<W, T>::To(wxWindow*, void*) [with W = wxSpinCtrl, T = int]’:
A> ../../include/wx/valgen.h:126:83:   instantiated from ‘bool wxGenericValidatorType<W, T>::TransferToWindow() [with W = wxSpinCtrl, T = int]’
A> ./dialogs.cpp:3975:1:   instantiated from here
A> ../../include/wx/valgen.h:47:34: error: creating pointer to member of non-class type ‘wxIf<true, void, wxSpinCtrl>::value {aka void}’

 Did this get resolved already? I don't see this comment on the web any
more...

 Regards,
VZ

**Comment by AliKet** [comment]
Yes, the last commit 6c9176636303ca0c7c691c4fff24dea1bd041a2c solved the problem. thank you.
    Le mardi 19 juin 2018 à 10:45:44 UTC+1, VZ <notifications@github.com> a écrit :  
 
 On Sat, 16 Jun 2018 17:30:04 -0700 AliKet wrote:

A> @vadz can you help me with this annoying error (which happens with wxSpinCtrl in some configurations only !?)
A> 
A> Travis output:
A> 
A> In file included from ./dialogs.cpp:109:0:
A> ../../include/wx/valgen.h: In static member function ‘static bool wxPrivate::wxDataTransferHelper<W, T>::To(wxWindow*, void*) [with W = wxSpinCtrl, T = int]’:
A> ../../include/wx/valgen.h:126:83: instantiated from ‘bool wxGenericValidatorType<W, T>::TransferToWindow() [with W = wxSpinCtrl, T = int]’
A> ./dialogs.cpp:3975:1: instantiated from here
A> ../../include/wx/valgen.h:47:34: error: creating pointer to member of non-class type ‘wxIf<true, void, wxSpinCtrl>::value {aka void}’

 Did this get resolved already? I don't see this comment on the web any
more...

 Regards,
VZ

**Comment by vadz** [comment]
I'm not sure if this is already finished or not, but I have to say that I have a lot of reservations about the changes here. There is, of course, the usual concern about breaking compatibility, especially because I don't really see any good reason for doing it. There is also the fact that it it doesn't seem right to me to have to add macros to all wxWidgets controls. But most of all, I don't think the end result is as good and flexible as I'd like it to be because it seems to inherit the main design problem of the current validator classes: lack of composability.

E.g. I don't see how does it make it simple(r) writing validators for variables of type `std::optional<T>`, assuming you have a validator for `T`. Or, more generally, a validator for `std::variant<T, U, V>`. Stuff like this really needs to be easy to do, and it shouldn't be bound to these particular types (although it would be nice to provide support for them out of the box), but be easy to implement on top of the basic validator API.

Is it possible with your approach and am I just missing how to do it? If not, I'm afraid it's a very serious limitation.

**Comment by AliKet** [comment]
Thank you for looking into this @vadz 

Well, i think coming with a satisfactory API (flexible - extensible - type-safe and backward compatible) is more challenging now and i definitely need some help and guidance to achieve these requirements.
And thank you btw for drawing my attention to these types: std::optional, std::variant and likewise std::shared_ptr and std::unique_ptr and the like.

I'll do my best and see how it goes.

Regards.

**Comment by vadz** [comment]
I think we need to discuss this ideal API for the validators first and only then implement it and think about providing backwards-compatible wrappers/bridge. I'll try to think about this myself, as I've been working with validators recently and it's indeed much less pleasant than I think it could be.

BTW, some other wishlist items:

- Validators should have flexible error reporting, i.e. it should be possible to define a function that will be called in case of validation error with the error text and a pointer to the window which generated it. Speaking of which, it would be nice to have a way to display a window in an "invalid" state.
- Validators should maintain "dirty" (i.e. modified by user) state of the control. Maybe they should even allow reverting to the original (or last saved) value.
- It should be possible to define validation behaviour for several controls at once, as sometimes the value of each individual control can be valid, but not the combination of their values.
- Maybe validators should also handle dependencies between controls, i.e. the fact that some control should only be enabled if another control is checked or not-empty.

Some of these items can't be done per individual control, so we probably should have some new `DataTransferManager` class that would be associated with an entire panel/dialog at once.

**Comment by PBfordev** [comment]
One more thing for improving validators would be to allow easy opt-out of validate-as-you-type behaviour. This can get very annoying for the user or be [downright wrong](http://trac.wxwidgets.org/ticket/12968).

**Comment by vadz** [comment]
> One more thing for improving validators would be to allow easy opt-out of validate-as-you-type behaviour.

I actually think it might even be not supported at all. Filtering out the keys that can never appear in the control (e.g. letters in a control for integer entry) is enough IMO.

**Comment by vadz** [comment]
AFAIU this is replaced by #926, so closing this one. Please let me know if I misunderstood.

**Pull request closed without merging**
