### PR TITLE
CMake: fixes for wxBUILD_USE_STATIC_RUNTIME, wx_get_dependencies and wx_set_target_properties

### PR DESCRIPTION
**Pull request by NikitaFeodonit**
1. The comment to fix for wxBUILD_USE_STATIC_RUNTIME in build/cmake/init.cmake

wxWidgets has C++ and C files, so there need to add processing the CMAKE_C_FLAGS_[CONFIG].

Now the compiler gets /MT for C ++ files and /MD for C files when using the option wxBUILD_USE_STATIC_RUNTIME.

As a result, the linker produces the following error:
```
"E:\Dev\Temp\LibCMaker_WX_msvc\build_wxwidgets\ALL_BUILD.vcxproj" (default target) (1) ->
"E:\Dev\Temp\LibCMaker_WX_msvc\build_wxwidgets\wxWidgets-3.1.1\utils\wxrc.vcxproj" (default target) (23) ->
(Link target) ->
  wxexpatd.lib(xmlparse.obj) : error LNK2019: unresolved external symbol __imp___wassert referenced in function _XML_GetParsingStatus [E:\Dev\Temp\LibCMaker_WX_msvc\build_wxwidgets\wxWidgets-3.1.1\utils\wxrc.vcxproj]
  MSVCRTD.lib(_chandler4gs_.obj) : error LNK2019: unresolved external symbol __except_handler4_common referenced in function __except_handler4 [E:\Dev\Temp\LibCMaker_WX_msvc\build_wxwidgets\wxWidgets-3.1.1\utils\wxrc.vcxproj]
  E:\Dev\Temp\LibCMaker_WX_msvc\build_wxwidgets\lib\vc_lib\wxrc.exe : fatal error LNK1120: 2 unresolved externals [E:\Dev\Temp\LibCMaker_WX_msvc\build_wxwidgets\wxWidgets-3.1.1\utils\wxrc.vcxproj]

    30 Warning(s)
    3 Error(s)
```

After adding the processing the CMAKE_C_FLAGS_[CONFIG], the problem was resolved.

As described [here](https://stackoverflow.com/a/20804336), it is necessary also to change the variables in the cache:
```
      set(${flag_var} ${${flag_var}} CACHE STRING "Flags used by the CXX compiler during ${cfg_upper} builds." FORCE)
...
      set(${flag_var} ${${flag_var}} CACHE STRING "Flags used by the C compiler during ${cfg_upper} builds." FORCE)
```

2. The comment to fix for wx_get_dependencies in build/cmake/config.cmake

If build in UNIX with the options
```
wxUSE_REGEX=builtin
wxUSE_ZLIB=builtin
wxUSE_LIBJPEG=builtin
wxUSE_LIBPNG=builtin
```
then
```
get_target_property(deps ${lib} LINK_LIBRARIES)
```
returns only the targets names, not libraries file path. 

Therefore, need to use the target property LOCATION.

3.  The comment to fix for wx_set_target_properties in build/cmake/functions.cmake

wx-config can not be used to connect the libraries with the debug suffix. Therefore, need to remove 'd' suffix for the UNIX build in wx_set_target_properties.

### CODE REVIEW

**Comment by NikitaFeodonit** [comment]
> 3. The comment to fix for wx_set_target_properties in build/cmake/functions.cmake
> 
> wx-config can not be used to connect the libraries with the debug suffix. Therefore, need to remove 'd' suffix for the UNIX build in wx_set_target_properties.

This is relevant for the building with the option
```
CMAKE_BUILD_TYPE="Debug"
```
and with the further use of the installed debug library in UNIX with wx-config.

**Comment by MaartenBent** [comment]
About 2), does configure also use the full path?

**Comment by NikitaFeodonit** [comment]
> 
> 
> About 2), does configure also use the full path?

https://github.com/wxWidgets/wxWidgets/pull/1154/commits/1bc43c8d7a58103123e2c38631b3deebed916519#diff-04cdee09012ba9f2611f5f25e07c3ed4R40
``` CMake
get_target_property(dep_path ${dep} LOCATION)
<...>
get_filename_component(name ${dep_path} NAME)
```
Here, in the end, only the file name is used, not full path.

**Comment by NikitaFeodonit** [comment]
> 
> 
> About 2), does configure also use the full path?

https://github.com/wxWidgets/wxWidgets/blob/e4198c149be40062f2889317e417ec04f2d310f5/configure.in#L8030
https://github.com/wxWidgets/wxWidgets/blob/e4198c149be40062f2889317e417ec04f2d310f5/configure#L39210

No, configure does not use the full path.

**Comment by MaartenBent** [comment]
Ah, I misread the commit. It still uses only the library name.

But you shouldn't use `LOCATION`, it generates a lot of warnings, see the [Travis CI build](https://travis-ci.org/wxWidgets/wxWidgets/jobs/482367659#L1490). And it seems [deprecated](https://cmake.org/cmake/help/v3.13/prop_tgt/LOCATION.html).

I think using `get_target_property(dep_path ${dep} OUTPUT_NAME)` should work as wel. Can you test this?

**Comment by NikitaFeodonit** [comment]
> I think using get_target_property(dep_path ${dep} OUTPUT_NAME) should work as wel. Can you test this?

I made the new commit, please see. And tested it, it's okay.

**Comment by vadz** [comment]
Thanks for the fixes, Nikita!

@MaartenBent please let me know when it's ok to merge this.

**Comment by MaartenBent** [comment]
Looks good. The correct library names are now used in `wx-config`. I haven't tested the `wxBUILD_USE_STATIC_RUNTIME` related changes, but these seem logical.

Go ahead and merge.

**Pull request merged**
