### PR TITLE
Removal of unused code

### PR DESCRIPTION
**Pull request by hwiesmann**
The code seems to be unused since 2008.

### CODE REVIEW

**Comment by vadz** [comment]
Sorry but I don't think we can just remove this function, it [seems to be used](https://github.com/search?q=MacGetWindowMenuHMenu&type=Code) outside of wxWidgets. The usual procedure should be followed, i.e. we should deprecate it first and then remove it later.

Also, please avoid making whitespace-only and significant changes together in the same commits. TIA!

**Comment by hwiesmann** [comment]
Hi Vadim,

OK, though I do not have any problems to remove an undocumented and protected method that is clearly used for internal purposes only.

I will submit another similar patch because in the previous commit unused code exists that has been commented out 10 years ago.

**Comment by hwiesmann** [comment]
All the references I checked under "seems to be used" are referencing the old code that is commented out - and therefore not at all active - since 10 years!

**Comment by vadz** [comment]
I admit I haven't checked the code referencing the symbol in details. But just the sheer number of references scares me a little. Again, I don't see any huge urgency with removing it. Deprecating it would be perfectly fine if it's really useless (I admit I have no idea about that neither...).

**Pull request closed without merging**
