### PR TITLE
CMake: use a common function for adding samples, tests and demos

### PR DESCRIPTION
**Pull request by MaartenBent**
Fix running CMake tests on Travis CI.
Specify tests to exclude instead of tests to include.

### CODE REVIEW

**Comment by TcT2k** [comment]
In CMake maybe it would make sense to automatically enable `wxUSE_WEBVIEW_EDGE` if the header exists?

**Comment by MaartenBent** [comment]
> In CMake maybe it would make sense to automatically enable `wxUSE_WEBVIEW_EDGE` if the header exists?

Added.
It will be enabled for `MSVC_VERSION GREATER 1800` (greater than VS 2013 / vc120) and when `webview2` folder is detected.

**Comment by vadz** [comment]
@MaartenBent is this ok to merge now or do you plan any more changes here (FWIW I don't have any comments whatsoever, other than to say thanks to you for these cleanups and improvements!).

**Comment by MaartenBent** [comment]
You can merge it.

**Pull request merged**
