### PR TITLE
More wxWebView improvements

### PR DESCRIPTION
**Pull request by TcT2k**
* Implement a fix to trac ticket [18851](https://trac.wxwidgets.org/ticket/18851#comment:11) suggested by @PBfordev 
* Notify the edge API when minimizing/restoring parent window
* Implement `wxWebView::GetVersionInfo()` for macOS and iOS

@PBfordev I tested your suggested fix and it seems to work for me in various scenarios, thanks for the fix.

### CODE REVIEW

**Comment by TcT2k** [comment]
Added missing `wxOVERRIDE`  in `wxWebViewFactoryWebKit`. I'm not really sure why they weren't a problem previously.

**Comment by MaartenBent** [comment]
A small comment, but related to your previous PR. It introduced some mixed EOL around `GetVersionInfo` in the following files:
./src/msw/webview_edge.cpp
./src/msw/webview_ie.cpp
I also detected it in this file (line 60) but it is already there since caf92856
./include/wx/private/json.h

I'm working on detecting this in the Code Checks CI.

**Comment by TcT2k** [comment]
@MaartenBent 
> A small comment, but related to your previous PR. It introduced some mixed EOL around `GetVersionInfo` in the following files:
> ./src/msw/webview_edge.cpp
> ./src/msw/webview_ie.cpp
> I also detected it in this file (line 60) but it is already there since [caf9285](https://github.com/wxWidgets/wxWidgets/commit/caf92856098ecfc9594deb597c4bef11f9277e96)
> ./include/wx/private/json.h
> 
Added a commit to fix those.

> I'm working on detecting this in the Code Checks CI.

This would definitely helpful. As with the check for tab/spaces. It's just something that can easily happen when working with various platforms/editors and would be nice to catch early.

**Comment by vadz** [comment]
Thanks again for the fixes, will merge once the AppVeyor build finishes.

**Pull request merged**
