### PR TITLE
Simplify wxKeyEvent generation in wxGTK a bit

### PR DESCRIPTION
**Pull request by vadz**
Try to make the code generating key events a bit more clear and also avoid duplicating the checks in AdjustCharEventKeyCodes() by returning true from this function if the key code passed them.

This shouldn't result in any real changes in behaviour.

---

@unxed I've seen your (apparently deleted now?) comment in #23379 and while trying to understand it, I've realized that the logic here could be simplified a bit, so I've tried doing it in this PR. Do you see any problems with doing it like this? The new version looks more comprehensible to me, so I'd like to merge this if it still works for you. TIA!

### CODE REVIEW

**Comment by unxed** [comment]
My comment was written due to a mistake. I've forgotten that zero keycode in OnChar is ok. On Windows we have character code in Windows ANSI 8-bit code page as Key Code in OnChar event, and it makes no sence reproducing this behavior on Unix platforms.

I compiled the code from your pull request, ran some tests on the keyboard demo app. The difference is that now when you press Alt+RussianLetter, the key code in the OnChar event is not 0, as it was before, but contains the corresponding Latin letter in uppercase. There is some inconsistency in this: if you press a Russian letter without Alt, then the key code in OnChar will still be zero, and if you press the same button in the Latin layout, the key code will contain a lowercase letter.

I think we need to globally rethink the meaning of the KeyCode field in the OnChar event.

If you were to ask me how to do it, I would suggest the following. Currently on Windows there is a character code in Windows ANSI encoding (8 bits) in KeyCode field of OnChar events, and on GTK there is zero there. I don’t see any point in this: no one uses the ANSI encoding today, and zero does not carry any information at all. Moreover, if we need to get both the key code and the character code at the same time, we have to listen to the KeyDown event, remember the key code, and then listen to the OnChar event and match the key code and character code. This is how it works in far2l now. Pretty weird, isn't it? I suggest setting the OnChar event to the same key code value as the KeyDown event on all platforms for all keys and key combinations (except for Ctrl+letters). Unfortunately, I can't offer a proper PR since I don't have Windows to test the changes under it, but the changes are very simple, I think you can easily make them yourself if you think it's reasonable.

**Comment by unxed** [comment]
The suggested change will break the assumption that Unicode key value should be always equal to keycode for latin-1 keys, so this keyboard event test should also be rewritten:
```
    if ( desc.m_keycode < WXK_START )
    {
        // For Latin-1 our key code is the same as Unicode character value.
        CPPUNIT_ASSERT_EQUAL_MESSAGE( "wrong Unicode key in " + msg,
                                      (char)desc.m_keycode,
                                      (char)ev.GetUnicodeKey() );
    }
    else // Special key
    {
        // Key codes above WXK_START don't correspond to printable characters.
        CPPUNIT_ASSERT_EQUAL_MESSAGE( "wrong non-zero Unicode key in " + msg,
                                      0,
                                      (int)ev.GetUnicodeKey() );
    }
```

**Comment by vadz** [comment]
> My comment was written due to a mistake. I've forgotten that zero keycode in OnChar is ok. On Windows we have character code in Windows ANSI 8-bit code page as Key Code in OnChar event, and it makes no sence reproducing this behavior on Unix platforms.

Thanks for the explanation, but I actually disagree here: I think that the behaviour should be the same on all platforms unless there are some really good reasons to diverge from it.
 
> I compiled the code from your pull request, and ran some tests on the keyboard demo app. The difference is that now when you press Alt+RussianLetter, the key code in the OnChar event is not 0, as it was before, but contains the corresponding Latin letter in uppercase. There is some inconsistency in this: if you press a Russian letter without Alt, then the key code in OnChar will still be zero, and if you press the same button in the Latin layout, the key code will contain a lowercase letter.

Yes, this is wrong :-(
 
> I think we need to globally rethink the meaning of the KeyCode field in the OnChar event.

I'm not so sure. It seems to work correctly for me under MSW, AFAICS we just need to make wxGTK work in the same way.

> If you were to ask me how to do it, I would suggest the following. Currently on Windows there is a character code in Windows ANSI encoding (8 bits) in KeyCode field of OnChar events, and on GTK there is zero there (if we are talking about master branch behavior). I don’t see any point in this: no one uses the ANSI encoding today, and zero does not carry any information at all. 

Nobody uses ANSI encoding but plenty of people use US English keyboards and it makes sense to keep providing the key code in `m_keyCode` for them. We should, ideally, do it on all platforms, however.

> Moreover, if we need to get both the key code and the character code at the same time, we have to listen to the KeyDown event, remember the key code, and then listen to the OnChar event and match the key code and character code.

Why does far2l need to do this? The idea is that you need to use `wxEVT_KEY_DOWN` if you care about actual key presses and `wxEVT_CHAR` if you care about text entry. In which situation do you need to handle both?

> I suggest setting the OnChar event to the same key code value as the KeyDown event on all platforms for all keys and key combinations.

This would silently break existing applications currently working correctly under MSW (and probably Mac too), so this is not really a good idea, we try to avoid breaking compatibility unless it's really necessary and try to avoid silent breakages really hard.

> Unfortunately, I can't offer a proper PR since I don't have Windows to test the changes under it, but the changes are very simple, I think you can easily make them yourself if you think it's reasonable.

I can test the changes under MSW (or, if you add more tests to `tests/events/keyboard.cpp`, they could get tested by the CI), but I'm not sure how to make wxGTK behave in the same way as wxMSW...

**Comment by unxed** [comment]
> Nobody uses ANSI encoding but plenty of people use US English keyboards and it makes sense to keep providing the key code in m_keyCode for them. We should, ideally, do it on all platforms, however.

So I just propose to pass the corresponding Latin character in the m_keyCode for character keys, even if non-Latin layout is selected, just as is done now in KeyUp/Down events. Just do the same for OnChar. Also it should always be in upper case, just as it is in KeyUp/Down events.

> Why does far2l need to do this? The idea is that you need to use wxEVT_KEY_DOWN if you care about actual key presses and wxEVT_CHAR if you care about text entry. In which situation do you need to handle both?

far2l is ported from Windows, and uses a kind of compatibility layer to emulate some part of the Windows API. So input events coming from wx are translated into equivalent of Windows WM_KEYDOWN/UP events, which are further processed by existing Far Manager code. I don't know Winodws console API well enough to explain why I had to be done this way. Maybe @elfmz could explain it better.

**Comment by unxed** [comment]
>> I compiled the code from your pull request, and ran some tests on the keyboard demo app. The difference is that now when you press Alt+RussianLetter, the key code in the OnChar event is not 0, as it was before, but contains the corresponding Latin letter in uppercase. There is some inconsistency in this: if you press a Russian letter without Alt, then the key code in OnChar will still be zero, and if you press the same button in the Latin layout, the key code will contain a lowercase letter.

> Yes, this is wrong :-(

First of all, let us fix the first part of the problem: with the patch below, OnChar events:
1) from the press of Russian letter key alone and
2) from the press of the same key with Alt
both have Latin equivalent in Key Code field. This is unlikely to break anything, since the zero keycodes that were there before are probably not used by anyone.

Let's first agree that this is a good solution before discussing anything else — just to avoid mess and misunderstanding.

```
diff --git a/src/gtk/window.cpp b/src/gtk/window.cpp
index 85f01f2a71..77f6e56a4e 100644
--- a/src/gtk/window.cpp
+++ b/src/gtk/window.cpp
@@ -1485,8 +1485,29 @@ bool wxWindowGTK::GTKDoInsertTextFromIM(const char* str)
     for( wxString::const_iterator pstr = data.begin(); pstr != data.end(); ++pstr )
     {
         event.m_uniChar = *pstr;
+        event.m_keyCode = 0;
+
+#ifdef wxHAS_XKB
+        char key_code_str[64];
+        xkb_state_key_get_utf8(gs_xkbData.GetState(),
+                               m_imKeyEvent->hardware_keycode,
+                               key_code_str,
+                               sizeof(key_code_str));
+        if ( strlen(key_code_str) == 1 )
+        {
+            event.m_keyCode = key_code_str[0];
+
+            // If key_code is a Latin char, it should be in upper register to
+            // match the other ports.
+            if (islower(event.m_keyCode))
+            {
+                event.m_keyCode = toupper(event.m_keyCode);
+            }
+        }
+#endif // wxHAS_XKB
+        
         // Backward compatible for ISO-8859-1
-        event.m_keyCode = *pstr < 256 ? event.m_uniChar : 0;
+        event.m_keyCode = *pstr < 256 ? event.m_uniChar : event.m_keyCode;
         wxLogTrace(TRACE_KEYS, wxT("IM sent character '%c'"), event.m_uniChar);
 
         AdjustCharEventKeyCodes(event);

```

**Comment by unxed** [comment]
English/Russian one

**Comment by vadz** [comment]
> First of all, let us fix the first part of the problem: with the patch below, OnChar events:
> 
>     1. from the press of Russian letter key alone and
>     2. from the press of the same key with Alt
> 
> both have Latin equivalent in Key Code field. This is unlikely to break anything, since the zero keycodes that were there before are probably not used by anyone.
> 
> Let's first agree that this is a good solution before discussing anything else — just to avoid mess and misunderstanding.

I'm sorry, I know that I wrote that I agreed with this previously, but I've actually retested this now and the current behaviour is consistent for all 3 platforms: key code is set to 0 when unicode char is a non-ASCII letter (whether Alt is pressed or not).

Knowing this, I think I prefer to keep it like this to avoid introducing new platform differences.

Sorry again for the confusion, but I somehow thought that you wrote that GTK behaviour differed from MSW, when actually they're the same (and Mac behaves like this too).

**Comment by unxed** [comment]
In this case, it is better to reject this PR, because after it, the key code is set to a capital Latin letter in OnChar events in some cases. We can just leave master it as is, that's completely acceptable.

**Comment by vadz** [comment]
I'd still like to avoid duplicating the checks from `AdjustCharEventKeyCodes()` here, so I've updated the PR to do just this (in fact, this was always my intention, but I just misunderstood what the code did and so updated it incorrectly -- which, I guess, proves my point that the code is not that easy to understand...).

AFAICS the latest version should work in the same way as the current master, doesn't it?

**Comment by unxed** [comment]
Retested. Yes, it looks like behavior now is like in master.

**Comment by vadz** [comment]
Thanks for testing! Merged now.

**Pull request closed without merging**
