### PR TITLE
Add wxBitmapBundle

### PR DESCRIPTION
**Pull request by vadz**
This is a _very_ draft version of this class. So far it basically only works in wxMSW and maybe wxGTK (I think it does, but I didn't have time to test it fully) when using wxToolbar and breaks the build everywhere else.

Many things remain to be done, see the check-list below, but I won't be able to work on this until the next week, so I wanted to put it here to see if there are already any comments -- please don't hesitate to leave them. TIA!

- [x] Update all the other ports in some trivial way, i.e. so that they keep comping and working as before -- this is required to even consider merging this, so it's the highest priority.
- [x] Implement this class for Mac.
- [x] Add `wxBitmapBundle::FromSVG()`.
- [x] Implement caching of the bitmaps generated from SVG: cache all or only the last one?
- [x] Remove `wxEVT_DPI_CHANGED` handler in the sample, make the toolbar update itself instead in wxMSW.
- [x] Add unit tests for the new class.
- [ ] Update the rest of the API to take `wxBitmapBundle` instead of `wxBitmap` too.
- [ ] Add `wxBitmapBundle::FromFiles()` which can be implemented natively under Mac.
- [ ] Consider providing `wxBitmapBundle::GetBestMatchingSize(size, options)` for selecting the closest (smaller or larger, as determined by the options) bitmap size that can be used without rescaling.
- [ ] Add `wxBitmapType` parameter to `FromResources()` to allow loading something other than PNGs (low priority).

### CODE REVIEW

**Comment by csomor** [comment]
> Many things remain to be done, see the check-list below, but I won't be able to work on this until the next week, so I wanted to put it here to see if there are already any comments -- please don't hesitate to leave them. TIA!
> 
> * [ ]  Update all the other ports in some trivial way, i.e. so that they keep comping and working as before -- this is required to even consider merging this, so it's the highest priority.
> * [ ]  Implement this class for Mac.

Hi @vadz , thanks a lot, if it's ok, I'll try to make things compile and build - if possible also work correctly - under macOS, if that's ok for you, I'll probably have to add the GetNSImage or OSXGetNSImage to the bundle header, but the rest should remain in osx waters ...

**Comment by csomor** [comment]
@vadz ok, I've something that builds and shows bitmaps, but unfortunately to really get the best situation, I should be able to iterate over the bitmaps, somehow, from wxBitmapBundle::OSXGetImage, either get a way to retrieve all currently available sizes, or get direct access to the bitmaps 

Another thing that came up is the reversed situation, I have a native NSImage and should be able to build a wxBitmapBundle of it, I should be able to store that NSImage in the bitmap bundle, because it may be a dynamic image, that get rendered by the OS on the fly depending on appearance, time etc ...

**Comment by vadz** [comment]
@csomor If all this extra functionality is only needed in wxMac code itself, ideal would be to define Mac-specific Impl class in `include/wx/osx/private/bmpbndl.h` and add whatever you need there (this class may or not derive from `wxBitmapBundleImplSet`, but if it does need to derive from it, this class itself should be extracted into `include/wx/private/bmpbndl.h` first).

For creating the bundle from platform-specific representation (i.e. `NSImage`), we could either add Mac-specific `FromXXX()` to do it, or just add `FromExistingImpl(wxBitmapBundleImpl* impl)` that could be used by any code in wx itself.

**Comment by csomor** [comment]
> @csomor If all this extra functionality is only needed in wxMac code itself, ideal would be to define Mac-specific Impl class in `include/wx/osx/private/bmpbndl.h` and add whatever you need there (this class may or not derive from `wxBitmapBundleImplSet`, but if it does need to derive from it, this class itself should be extracted into `include/wx/private/bmpbndl.h` first).

Thanks

since it will always be used on macOS, and I didn't want to expose the bitmap vector of set to the outside, I've now added in my current attempt a

```
class wxBitmapBundleImpl : public wxRefCounter
{
public:
 (...)
 #ifdef __WXOSX__
    // returns the native representation of the bitmap bundle
    virtual WXImage OSXGetImage() const { return NULL; }
#endif
};

class WXDLLIMPEXP_CORE wxBitmapBundle
{
public:
(....)
#ifdef __WXOSX__
        // returns nil for invalid bitmap
    WXImage OSXGetImage() const;
#endif
};
```

Having a OSX specific SetImpl that is a subclass would be possible as well, we'd just need another indirection for indicating which set-class should be used in this. 

```
wxBitmapBundle::wxBitmapBundle(const wxBitmap& bitmap)
    : m_impl(bitmap.IsOk() ? new wxBitmapBundleImplSet(bitmap) : NULL)
{
```

But since it is only a getter method that would be added, adding it to the existing SetImpl would be ok as well ?

> For creating the bundle from platform-specific representation (i.e. `NSImage`), we could either add Mac-specific `FromXXX()` to do it, or just add `FromExistingImpl(wxBitmapBundleImpl* impl)` that could be used by any code in wx itself.

So this would be ok, then

```
class WXDLLIMPEXP_CORE wxBitmapBundle
{
public:
(....)
#ifdef __WXOSX__
    // Create from the native OSX platform image
    static wxBitmapBundle FromOSXImage(WXImage image);
#endif
};
```

For creating from a WXImage of course I created a specific impl subclass

**Comment by vadz** [comment]
@csomor All this should be fine, but if we really wanted to keep all this private (which might be a good idea to allow us changing it during 3.2 lifetime without worrying about the ABI -- and this whole class design is supposed to allow modifying it later without affecting the ABI), then we probably should have just the following in the public `wx/bmpbndl.h`:

1. The already mentioned ctor from `Impl`: `wxBitmapBundle(wxBitmapBundleImpl* impl);`.
2. Accessor for impl: `wxBitmapBundleImpl* GetImpl() const;`.

Then all the rest could be done in the private headers only, e.g. you could add `OSXGetImage()` that you already wrote to `include/wx/private/bmpbndl.h` and use it as `bundle.GetImpl()->OSXGetImage()` (of course, after checking that the bundle is valid...). This is a bit more verbose than `bundle.OSXGetImage()`, but leaves us completely free to change this function later as we see fit, or add more functions, without affecting the public API at all, so I think it's probably worth it.

**Comment by vadz** [comment]
@csomor Just FYI, I've pushed a few more commits that should fix the build for the other ports, but I didn't touch Mac files to avoid conflicts with your changes, if any.

As of right now, the sample still works correctly under MSW, i.e. uses either 32 or 64px bitmaps depending on the DPI and also updates itself when it's moved between the monitors using different resolutions and if we could make this work under Mac too, it would be great. TIA!

**Comment by csomor** [comment]
> @csomor All this should be fine, but if we really wanted to keep all this private (which might be a good idea to allow us changing it during 3.2 lifetime without worrying about the ABI -- and this whole class design is supposed to allow modifying it later without affecting the ABI), then we probably should have just the following in the public `wx/bmpbndl.h`:
> 
> 1. The already mentioned ctor from `Impl`: `wxBitmapBundle(wxBitmapBundleImpl* impl);`.
> 2. Accessor for impl: `wxBitmapBundleImpl* GetImpl() const;`.

so would you prefer to make the impl constructor public or have the aforementioned
```
   // Create from existing implementation
    static wxBitmapBundle FromExistingImpl(wxBitmapBundleImpl* impl);
```

**Comment by vadz** [comment]
Whatever you prefer, if using the ctor makes the code significantly simpler/shorter, I don't see any particular problems with making it public (but please let's leave it explicit). But `FromImpl()` is _definitely_ safe, so there just can't be any problems with having it at all.

**Comment by csomor** [comment]
> Whatever you prefer, if using the ctor makes the code significantly simpler/shorter, I don't see any particular problems with making it public (but please let's leave it explicit). But `FromImpl()` is _definitely_ safe, so there just can't be any problems with having it at all.

Ok, I've started with the FromImpl then I'll stick with that, gives us more freedom ...

**Comment by csomor** [comment]
@vadz Ok, I've only pushed the bitmapbundle headers an a first implementation file, I didn't want to add all things in one commit, only to revert them after, so I'd be grateful if you could glance over the header changes. Thanks.

**Comment by vadz** [comment]
I've added minimal docs for the new `wxArtProvider` methods, but any improvements to them would be welcome, e.g.:

1. We probably should explain the difference between bitmaps and bitmap bundles better in some overview.
2. It's not totally clear to me how is `size` parameter of `{Get,Create}BitmapBundle()` is used, notably what happens when it's `wxDefaultSize`.

**Comment by vadz** [comment]
I've made `wxBitmapBundleImpl` public now (it doesn't look like it's really useful to have separate public `CustomImpl` and internal `Impl` classes) and I think this could be merged now and the remaining checkboxes implemented in later PRs.

@csomor Please let me know if you disagree, i.e. if there is anything crucial still missing here. If not, I'll rebase this (to avoid having fixup commits and the like) and merge it.

**Comment by csomor** [comment]
> @csomor Please let me know if you disagree, i.e. if there is anything crucial still missing here. If not, I'll rebase this (to avoid having fixup commits and the like) and merge it.

I think it's ok to move this, to get broad testing, and solve the rest in PRs. Right now wxBitmap still carries the full multi-res capabilities on macOS, I'll then try to switch this off conditionally so that we can easily isolate newly created problems

**Comment by vadz** [comment]
I've rebased and combined commits to avoid having all the "fixup" ones in history and added `wxHAS_SVG`.

If there are no last-minute objections, I'll merge this one once the CI builds pass so that we could continue with the rest.

**Pull request merged**
