### PR TITLE
Fix Cygwin 64 bit build issues for wxGTK

### PR DESCRIPTION
**Pull request by stahta01**
Fixes #18456

### CODE REVIEW

**Comment by stahta01** [comment]
@oneeyeman1 

I see no reason why my changes would fix  [bug 10569](https://trac.wxwidgets.org/ticket/10569)

**Comment by vadz** [comment]
I don't understand what's going on with AppVeyor MinGW build, but it's probably unrelated to this PR.

**Comment by stahta01** [comment]
> I don't understand what's going on with AppVeyor MinGW build, but it's probably unrelated to this PR.

I think the MSys2 Mingw GCC compiler has a new bug.

Tim S.

**Comment by vadz** [comment]
I think `_GNU_SOURCE` should rather be defined by configure/in `setup.h`, but let's merge it like this for now. Thanks for the fixes!

**Pull request merged**
