### PR TITLE
macOS wxFileDialog improvements

### PR DESCRIPTION
**Pull request by discnl**
This PR mainly consists of two fixes:

5cc2f6ce9f - Fix width of file type wxChoice in open dialogs on macOS
f048a03ea6 - Fix parent of extra control not being a wxFileDialogBase on macOS

and one enhancement:

40422db37d - Add wxMac wxFileDialog::GetCurrentlySelectedFilterIndex() support

Tested on 10.10, 10.12 and 11.0.

### CODE REVIEW

**Comment by vadz** [comment]
Thanks! This looks good to me and I'll merge this if Stefan doesn't have any objections in a few days.

**Comment by vadz** [comment]
I'll merge this soon if @csomor doesn't see anything wrong with it.

**Comment by csomor** [comment]
@vadz thanks, I'll check this out and come back

**Comment by csomor** [comment]
@discnl nice :-) thanks a lot 
@vadz nothing wrong from my side
(a small wish for the future, now that the filetype is centered, the extrapanel with its left alignement looks rather off, but I'm not sizer-fluent enough to make SetupExtraControls wrap it so that it is centered - I failed and made the file dialog a lot broader than it should be)

**Comment by discnl** [comment]
> @discnl nice :-) thanks a lot

No problem, and thanks for checking!

> (a small wish for the future, now that the filetype is centered, the extrapanel with its left alignement looks rather off, but I'm not sizer-fluent enough to make SetupExtraControls wrap it so that it is centered - I failed and made the file dialog a lot broader than it should be)

What is the problem after this PR exactly? I thought the dialog is so wide (before/after PR) because that's what the extra controls want size-wise. Also if I make the dialog wider the extra controls start offsetting so they already appear horizontally centred (just like the filetype before this PR actually: it was already being centred by the OS and the width that wx receives is not related to the dialog's width).
Note that the extra controls reserves some space on the right for displaying text: the label with "Nothing selected" has the same sizer proportion as the `wxTextCtrl`, which perhaps make extra controls seem left aligned but it is not the case.

**Comment by csomor** [comment]
@discnl I know it was not related to this PR, it just became better visible to me, as before both lines were 'left' aligned, with respect to each other, so I didn't see that the entire container was centred on the dialog, because there was about 40 % empty space for the static text at the right. With your change the center became better visible ... so sorry for the noise and thanks again :-)

**Comment by vadz** [comment]
Thanks again for the fixes/improvements!

**Pull request merged**
