### PR TITLE
Expose what causes the wxSTC test to fail under Xvfb.

### PR DESCRIPTION
**Pull request by AliKet**
[Not to be merged]

Finally, I managed to identify what causes the `wxSTC` test to fail under `Xvfb`:
it is the [ListBaseTestCase::ItemClick()](https://github.com/wxWidgets/wxWidgets/blob/master/tests/controls/listbasetest.cpp#L180) with `wxListView` as list.

Apparently, it's not the test per se which causes the failure, but rather the wxListView. because the same test is effectively used by ListCtrlTestCase (with `wxListCtrl` as list) and no such failure is perceived.

At the moment, I don't know how to fix this problem nor how to debug it, unfortunately.

### CODE REVIEW

**Comment by vadz** [comment]
The only difference I see between `ListCtrlTestCase` and `ListViewTestCase` is that the former uses `DeleteTestWindow()` and the latter does not. Could this be the explanation? If we delete the window while it has capture, it might explain it...

**Comment by AliKet** [comment]
> The only difference I see between `ListCtrlTestCase` and `ListViewTestCase` is that the former uses `DeleteTestWindow()` and the latter does not. Could this be the explanation? If we delete the window while it has capture, it might explain it...

Me too, i thought just adding DeleteTestWindow() would make the failure gone, but it didn't help unfortunately!

**Comment by AliKet** [comment]
Hi @vadz 

Working on this **PR** #2016, I discovered that `ListCtrlTestCase` can also affect the `wxSTC` test in the same way as the `ListViewTestCase`, but just interacting with the column hides the problem there!

I'm still don't know way? because calling `DeleteTestWindow()` should release any existing capture!

By the way, do you know the rational behind this [comment](https://github.com/wxWidgets/wxWidgets/blob/master/tests/controls/listctrltest.cpp#L59):

>     // Column events are only supported in wxListCtrl currently so we test them
>     // here rather than in ListBaseTest

because as you can see in this PR #2016, it is no longer valid !?

Thank you!

**Comment by AliKet** [comment]
@vadz just ignore my previous message as i just spot this copy-past error
in the [ListViewTestCase](https://github.com/wxWidgets/wxWidgets/blob/master/tests/controls/listviewtest.cpp#L55):
```
void ListViewTestCase::setUp()
{
    m_list = new wxListView(wxTheApp->GetTopWindow());
    m_list->SetWindowStyle(wxLC_REPORT);
    m_list->SetSize(400, 200);
}
```

which should be:
`    m_list->SetWindowStyle(wxLC_LIST);`

Am i missing something fondamental here ?

**Comment by AliKet** [comment]
@vadz sorry to bother you again, and please ignore what i wrote above!
 
but before closing this I should tell you what...
My main misunderstanding comes from this **misleading** [comment](https://github.com/wxWidgets/wxWidgets/blob/master/tests/controls/listctrltest.cpp#L59):
> Column events are only supported in wxListCtrl currently so we test them
> here rather than in ListBaseTest

Because for one hand (unless i'm missing something) `wxListView` is just a façade for the `wxListCtrl`, and thus the test can be shared with both. and for the other hand `ListBaseTest` doesn't work with a listctrl having `wxLC_LIST` style anyhow. So i just moved those tests (i.e **ColumnClick** & **ColumnDrag**) to the `ListBaseTest` and everything should work now with no problem (including the problem this PR tries to resolve).

Thank you.

**Comment by vadz** [comment]
Yes, `wxListView` is indeed just a façade for `wxListCtrl` with `wxLC_REPORT` style, but I think the comment just says that `wxListCtrl` doesn't always have columns, because it can be used with other styles too, so this shouldn't be tested in the base class.

I'm still not sure what the actual problem was here...

**Comment by AliKet** [comment]
> Yes, `wxListView` is indeed just a façade for `wxListCtrl` with `wxLC_REPORT` style, but I think the comment just says that `wxListCtrl` doesn't always have columns, because it can be used with other styles too, so this shouldn't be tested in the base class.

Ok, so, what do you prefer?
- Move `ColumnClick()` and `ColumnDrag()` tests back to `ListCtrlTestCase`, Or...
- Keep them in `ListBaseTestCase` but using `wxLC_REPORT` style explicitly, i.e. by adding  `list->SetWindowStyle(wxLC_REPORT);` ?
 
> 
> I'm still not sure what the actual problem was here...

The problem is that the `List{Ctrl, View}TestCase` have inexplicable influence on how the focus behave in the `wxSTC` test when running the whole test suite. this quirk can be seen only:

1. When running under **Xvfb** server.
2. The `wxList{Ctrl, View}` **main window** handles mouse event (even if only a `wxEVT_MOTION`).
3. The `wxList{Ctrl, View}` **main window** is the last window which handles mouse events.

Now, the problem is not observable with the `ListCtrlTestCase` (but only with the `ListViewTestCase`) because of (**3**), i.e. the last window which handles mouse events **is not the main window**.

FYI, I tried to see and release any mouse capture before destroying the wxListCtrl but with no luck!
(debugging this is somewhat hard for me, especially when it comes to mouse events under Xvfb)

As a last resort, I ended up adding this:
```
void ListBaseTestCase::ItemClick()
{
    ⋮
    CPPUNIT_ASSERT_EQUAL(1, rclick.GetCount());

    // For some unfathomable reason this test case prevents wxSTC test
    // from running properly under Xvfb when we run the whole test suite.
    // Adding this ugly workaround to make the wxSTC test pass successfully
    // is better than nothing.
    if ( IsRunningUnderXVFB() )
    {
        list->Hide();

        wxScopedPtr<wxTextCtrl> text(new wxTextCtrl(wxTheApp->GetTopWindow(), wxID_ANY));
        
        const wxPoint pt = text->ClientToScreen(wxPoint(5, 5));
        sim.MouseMove(pt);
        wxYield();

        sim.MouseClick();
        wxYield();
    }
```
to [ListBaseTestCase](https://github.com/wxWidgets/wxWidgets/blob/master/tests/controls/listbasetest.cpp#L180), and everything goes well!

Do you have any better ideas or suggestions that I can try?

TIA!

**Comment by vadz** [comment]
The answer to the first question seems simple, but perhaps I'm missing something simple, so let me ask: what benefit exactly is there to moving these methods like you did? Does it help working around the second problem? AFAICS it doesn't, so why should we do this? I.e. it seems to me that we should just keep these tests where they're now, as it doesn't seem to be worth moving them (I realize that you've already done it, but it should hopefully be simple enough to just revert this change and return to the master version).

The second one is much more "interesting"... Normally I'd say to just add your workaround and forget about it because it's not that important in the grand scheme of things, but this is so weird, that I have to wonder if we could be doing something very wrong in `wxGenericListCtrl` code. But I assume you've already tested with `WXTRACE=mousecapture` and didn't see anything that could explain it -- and I have no other ideas, so let's just apply your workaround.

**Comment by AliKet** [comment]
> The answer to the first question seems simple, but perhaps I'm missing something simple, so let me ask: what benefit exactly is there to moving these methods like you did? Does it help working around the second problem? AFAICS it doesn't, so why should we do this? I.e. it seems to me that we should just keep these tests where they're now, as it doesn't seem to be worth moving them (I realize that you've already done it, but it should hopefully be simple enough to just revert this change and return to the master version).

No much benefit other than getting rid of the hackish workaround shown above.
Now reverted to master with the workaround applied!

> 
> The second one is much more "interesting"... Normally I'd say to just add your workaround and forget about it because it's not that important in the grand scheme of things, but this is so weird, that I have to wonder if we could be doing something very wrong in `wxGenericListCtrl` code. But I assume you've already tested with `WXTRACE=mousecapture` and didn't see anything that could explain it -- and I have no other ideas, so let's just apply your workaround.

Nothing helps, `WXTRACE=mousecapture` nor `WXTRACE=focus`.
I even have tried a lot of things like adding some more logging and hacks here and there and nothing helps at all!

**Pull request closed without merging**
