### PR TITLE
Changes for wxSTC based on recent discussions elsewhere

### PR DESCRIPTION
**Pull request by NPDevelopmentCode**
This is a collection of 5 small changes for wxSTC and its documentation based on recent discussions on trac and the dev/user lists.

1) Remove the 2 recently added methods for setting colors of the popup list control. As discussed on the dev list, a more thorough method is needed for setting the appearance of the list and getting information about the appearance.

2) Add the wxEVT_STC_AUTOCOMP_SELECTION event generated when a new item is selected in a popup list. Also as discussed on the dev list, this notification was added in later versions of Scintilla, but for now is generated completely in the wxWidgets portion of wxSTC. 
That’s a pretty horrible name, but its what were stuck with if we want to remain consistent with the mapping of names used for other notifications:
SCN_AUTOCCANCELLED   -> wxEVT_STC_AUTOCOMP_CANCELLED
SCN_AUTOCCHARDELETED -> wxEVT_STC_AUTOCOMP_CHAR_DELETED
SCN_AUTOCCOMPLETED   -> wxEVT_STC_AUTOCOMP_COMPLETED
SCN_AUTOCSELECTION   -> wxEVT_STC_AUTOCOMP_SELECTION
so following that pattern:
SCN_AUTOCSELECTIONCHANGE -> wxEVT_STC_AUTOCOMP_SELECTION_CHANGE

3) Fix a crash due to a dangling pointer with the autocompletion popup on macOS. This should address track ticket [#18434](https://trac.wxwidgets.org/ticket/18434).

4) A recent post on the user list felt the documentation for the the wxEVT_STC_CHANGE event type was incomplete, so make a small addition.

5) Remove the bare list of event types from the wxSTC documentation page and replace it with a referal to the wxStyledTextEvent page where the event types are documented. This is consistent with how other large classes such as wxGrid and wxRichTextCtrl separate the documentation for their methods and events.

### CODE REVIEW

**Comment by vadz** [comment]
Thanks! The only somewhat questionable part of the change is adding more arguments to `wxSTCListBox` ctor, which is arguably already not very clear, but I don't know the code and so can't really propose any better way of doing this, so if you think this is the best we can do, I'll merge it as is.

**Comment by NewPagodi** [comment]
Not that you mention it, that is really ugly.  I've pushed a new commit that restores the original constructor for `wxSTCListBox` and stores the data needed for the event in the `wxSTCListBoxVisualData` class instead. Conceptually that's a better home for the data anyway.

Feel free to merge the last commit with the second one if you want to keep the commit history simpler or ignore it completely if you don't feel like doing additional review. Or I can merge the second and sixth if you want.  Whatever's easiest.

**Comment by a-wi** [comment]
BTW, Maybe it would good to fix some minor issues with wxSTC documentation:
wxWidgets/interface/wx/stc/stc.h:7719: warning: argument 'lineNo' of command @param is not found in the argument list of wxStyledTextCtrl::GetLineLength(long n) const
wxWidgets/interface/wx/stc/stc.h:7727: warning: The following parameters of wxStyledTextCtrl::GetLineLength(long n) const are not documented:
  parameter 'n'
wxWidgets/interface/wx/stc/stc.h:7731: warning: argument 'lineNo' of command @param is not found in the argument list of wxStyledTextCtrl::GetLineText(long n) const
wxWidgets/interface/wx/stc/stc.h:7739: warning: The following parameters of wxStyledTextCtrl::GetLineText(long n) const are not documented:
  parameter 'n'
wxWidgets/interface/wx/stc/stc.h:7582: warning: argument 'value' of command @param is not found in the argument list of wxStyledTextCtrl::Replace(long from, long to, const wxString &text)
wxWidgets/interface/wx/stc/stc.h:7594: warning: The following parameters of wxStyledTextCtrl::Replace(long from, long to, const wxString &text) are not documented:
  parameter 'text'

**Comment by NewPagodi** [comment]
f18699c should fix those warnings.

**Comment by vadz** [comment]
Thanks again!

**Pull request merged**
