### PR TITLE
Fix issue #23437, streamline regeneration process

### PR DESCRIPTION
**Pull request by utelle**
- A few glitches (like duplicate language symbols, wrong Windows language ids etc) were fixed
- Scripts were added to allow to regenerate the list of supported locales from the list of known Windows locales
- Version info when language symbols became available was added to the documentation of the language symbol enum
- Synonyms are no longer hard-coded in the script genlang.py

### CODE REVIEW

**Comment by vadz** [comment]
Thanks Ulrich!

I didn't have time to look at it yet, but I'd just like to ask: what should we do with #23438 now? Does this one replace it or ...?

**Comment by utelle** [comment]
> I didn't have time to look at it yet, but I'd just like to ask: what should we do with #23438 now? Does this one replace it or ...?

Yes, this one replaces it. I integrated all changes you made to `genlang.py` into the new version provided by this PR.

The wx version `since` is now an additional column in `langtabl.txt` and `synonymtabl.txt`. I updated the version info to mark all languages/locales that were added in version 3.1.6 accordingly.

Additionally, I added the version info to the synonyms, too. However, I didn't check how the generated documentation will look like and how useful this information really is. Actually, the meaning is when the language symbol was introduced the first time (as a normal language symbol, not as a synonym).

In the `README` file I described the regeneration process in some detail.

**Comment by utelle** [comment]
One of the checks, namely the one for C++11 features, fails, because the source of the utility `showlocales` (`showlocales.c`) uses `NULL` for null pointers. Well, the utility is a simple C application, and C doesn't know `nullptr`. Of course, I can replace `NULL` by `0`, to silence the check, if you prefer.

**Comment by vadz** [comment]
Thanks for the changes! I didn't have time to actually run the scripts, but they look good to me, so I'll merge this soon unless somebody has any comments about it.

As for the `NULL` problem, I think we can restrict the check to `*.h` and `*.cpp` files only, which would avoid triggering it in a `*.c` file, see #23459.

**Comment by vadz** [comment]
Thanks again, I've merged this now (and so closing the PR), but I had some changes after rerunning `genlang.py`:
```diff
diff --git a/src/common/languageinfo.cpp b/src/common/languageinfo.cpp
index 0661be5906..e345760402 100644
--- a/src/common/languageinfo.cpp
+++ b/src/common/languageinfo.cpp
@@ -1034,6 +1034,7 @@
     { "Cher", "cherokee" },
     { "Chrs", "chorasmian" },
     { "Copt", "coptic" },
+    { "Cpmn", "cypro_minoan" },
     { "Cprt", "cypriot" },
     { "Cyrl", "cyrillic" },
     { "Deva", "devanagari" },
@@ -1114,6 +1115,7 @@
     { "Orya", "oriya" },
     { "Osge", "osage" },
     { "Osma", "osmanya" },
+    { "Ougr", "old_uyghur" },
     { "Palm", "palmyrene" },
     { "Pauc", "pau_cin_hau" },
     { "Perm", "old_permic" },
@@ -1156,8 +1158,11 @@
     { "Thai", "thai" },
     { "Tibt", "tibetan" },
     { "Tirh", "tirhuta" },
+    { "Tnsa", "tangsa" },
+    { "Toto", "toto" },
     { "Ugar", "ugaritic" },
     { "Vaii", "vai" },
+    { "Vith", "vithkuqi" },
     { "Wara", "warang_citi" },
     { "Wcho", "wancho" },
     { "Xpeo", "old_persian" },
```

They look correct (i.e. correspond to `misc/languages/scripttabl.txt` contents) to me, so I've just added them to the commit, but I wonder why they hadn't been included originally.

**Comment by vadz** [comment]
Yes, I think it would be better to add these files to Git because it doesn't make much sense to have some, but not all, generated files there -- it should be either all or none and we tend to err on the side of "all" in wx. And it is convenient if only because you can see the changes easily with `git diff` after regenerating them... TIA!

**Comment by utelle** [comment]
I added the missing data files and adjusted the local `.gitignore` file (see PR #23465).

The data files downloaded from Unicode, the generated list of known Windows locales, and the current  version of  the files `langtabl.txt`, `scripttabl.txt`, and `synonymtabl.txt` form the basis for the regeneration process.

**Pull request closed without merging**
