### PR TITLE
Fix generic wxSearchCtrl drawings.

### PR DESCRIPTION
**Pull request by tomay3000**
The generic wxSearchCtrl drawings are messy and has the followings Bugs:
* The Search button size and position are not calculated correctly.
* The Cancel button size and position are not calculated correctly.
* The Cancel button background is not cleared.
* The background for both Search and Cancel buttons is not cleared when a custom user image with alpha channel is in use.
* There should not be a margin if any of the Search or Cancel buttons is not shown (visible).
* Replace the regular DC with a buffered one (to avoid flickering).
* Many incorrect comments in the code.

This fix do also beautify the entire code by removing unnecessary curly brackets "{" and "}" (except for scope purpose ones) and formats it using proper spacing for readability.

### CODE REVIEW

**Comment by tomay3000** [comment]
**These are some screenshots before the fix:** 
untitled 3
untitled 4

**And these are one after the fix:**
untitled 5
untitled 6

NB: I accidentally included a fix from another commit: **src/msw/window.cpp** does not count here.
Thank you for your understanding.

**Comment by vadz** [comment]
I'm sorry but this is just too hard to review. Could you please submit the significant changes, i.e. without the reformatting part, as a separate commit? FWIW I'm against removing the braces at all, they don't really harm anybody and it doesn't make sense to remove them in one particular file and I'm not really willing to spend time on doing this change globally.

If possible, please also try to split your different changes in different commits. TIA!

**Comment by tomay3000** [comment]
> I'm sorry but this is just too hard to review. Could you please submit the significant changes, i.e. without the reformatting part, as a separate commit?
Sure, I am going to do it ;)

> FWIW I'm against removing the braces at all, they don't really harm anybody and it doesn't make sense to remove them in one particular file and I'm not really willing to spend time on doing this change globally.
OK, I'll leave the braces. It because the habit of a coder style, varies from one to another.

> If possible, please also try to split your different changes in different commits. TIA!
That's what I am gonna do.

**Comment by tomay3000** [comment]
I have created a new clean pull request as you suggested: #1111

**Comment by vadz** [comment]
OK, thanks, will look at this one a.s.a.p. Closing this one in the meanwhile.

**Pull request closed without merging**
