### PR TITLE
Test more Linux architectures on Travis

### PR DESCRIPTION
**Pull request by vadz**
[skip appveyor]

### CODE REVIEW

**Comment by vadz** [comment]
So our built-in libpng doesn't work on arm and ppc archs because we don't include the corresponding files in our build.

We need to either do this or disable hardware optimizations.

BTW, it doesn't look like we're using SSE optimizations neither, which surely must be a noticeable loss...

**Comment by swt2c** [comment]
Actually it looks like an environment variable `container` may already be defined?  Indications are that this might be defined for LXC too, but I haven't tested.

```
<mock-chroot> sh-5.0# echo $container
systemd-nspawn
```

**Comment by MaartenBent** [comment]
> BTW, it doesn't look like we're using SSE optimizations neither, which surely must be a noticeable loss...

I don't mind creating a PR to enable this (and fix the missing files).

If SSE2 is enabled and wxWidgets is built on a CPU with SSE2, this could break running applications on older CPUs without SSE2. If this matters, maybe only enable it for 64-bit which has SSE2 for sure?

**Comment by vadz** [comment]
@MaartenBent Sorry, I've somehow missed this reply but, of course, it'd be great if you could please do this. As for SSE2 support, I guess we can just enable it and see if anybody complains. MSW 7 requires it, so it could only be an issue for people still running XP and I think that this must be really vanishingly rare by now.

TIA!

**Comment by obfuscated** [comment]
SSE2 is available starting with Pentium 4 - 2000 and AMD64 - 2003. It is a bit odd to not enable it 17 years later. For 64bit you don't have to enable it, it is always enabled, because it is part of the AMD64/x86-64 ISA and all CPUs support it.

**Comment by MaartenBent** [comment]
It still has to be enabled when building libpng, so it will actually use those instructions.
I created https://github.com/wxWidgets/wxWidgets/pull/1806 to fix the issues.

**Comment by MaartenBent** [comment]
You left all the other jobs in `.travis.yml` disabled in the merge.

**Comment by vadz** [comment]
TIL that making changes in a merge commit (where I reenabled the other jobs) and then using `git rebase --preserve-merges` because I had forgot to update to the latest master before merging loses these changes.

Thanks for pointing this out!

**Pull request merged**
