### PR TITLE
Also disable thread-safe statics with VS17 toolset

### PR DESCRIPTION
**Pull request by mirh**
Tbh I haven't tested it (haven't yet installed vs17) but it should just be a pretty [basic](https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-conditions) change.

### CODE REVIEW

**Comment by mirh** [comment]
And of course I broke it

**Comment by mirh** [comment]
I.. *Hopes github will pick up amended commit*

**Comment by vadz** [comment]
You don't seem to have pushed anything, actually.

**Comment by mirh** [comment]
Previous commit doesn't exist anymore in my repo, but whatever. 
I was just waiting for everything to build here before pulling new one.

**Pull request closed without merging**
