### PR TITLE
Fixed some typos

### PR DESCRIPTION
**Pull request by IlyaBizyaev**
Addition to [PR by orbitcowboy](https://github.com/wxWidgets/wxWidgets/pull/28) (accept that one first).
Replaced all the occurences of _"hilight"_ with _"highlight"_.

### CODE REVIEW

**Comment by vadz** [comment]
Could you please squash all these commits together and use a more informative commit message?

**Comment by IlyaBizyaev** [comment]
I don't know how to squash them...

**Comment by IlyaBizyaev** [comment]
Oh, no, it got even worse...

**Comment by IlyaBizyaev** [comment]
**Closed.** All the changes of pull requests [28](https://github.com/wxWidgets/wxWidgets/pull/28) and this one will be pulled later together.

**Pull request closed without merging**
