### PR TITLE
Fix wxSecretStore for linux

### LINKED ISSUE #24351: wxSecretStore is broken for binary secrets with WXGTK (probably any Linux platform).
#### Bug description:

The current gtk specific implementation of the wxSecretValueImpl class is broken for secrets containing  non-textual, binary data.
In case such a secret is used to store a secret the returned data after loading the secret will contain altered binary sequences in place of the original.

For instance; a secret containing "secret\x01\x86\x02\x99\x03" (size 11) was returned with 4 extra bytes (total size 15) inserted in the binary sequence following the 'secret' part.

The problem is caused by the content type 'text/plain' specified for the secret at line 79 of src/unix/secretstore.cpp.
The comment describing the reason for this:

```
    // Notice that we have to use text/plain as content type and not
    // application/octet-stream which would have been more logical because
    // libsecret accepts only valid UTF-8 strings for the latter, while our
    // data is not necessarily UTF-8 (nor even text at all...).
```

may have held truth at some point in the past but is does not now.

#### Expected vs observed behaviour:

Identical secret returned vs stored.

#### To Reproduce:

The attached extended secretstore sample can be used to reproduce the problem. This sample recognizes two additional optional switches for the 'selftest' operation:

- '-b' to specify running the selftest with binary secrets
- '-v' to specify verbose output on selftest errors (will print the stored and loaded secrets)

[secretstore.tar.gz](https://github.com/wxWidgets/wxWidgets/files/14392961/secretstore.tar.gz)

Replace the standard sample with the file from the attached archive, build and run.

### Platform and version information

- wxWidgets version  you use: master
- wxWidgets port  you use: wxGTK
- OS  and its version: OpenSuSE Leap 15.5
  
  + GTK version:  3.24.5
  + Which GDK  backend is used: X11
  + Desktop environment : KDE

### PR DESCRIPTION
**Pull request by mcorino**
Fixes #24351

### CODE REVIEW

**Comment by vadz** [comment]
Thanks, using text/plain is clearly a bad idea for binary data, but I wonder if using application/octet-stream for text data doesn't have some drawbacks too?

[Official documentation](https://gnome.pages.gitlab.gnome.org/libsecret/ctor.Value.new.html) is useless, but there are some specific checks for text/plain in libsecret code, so maybe it would be better to keep using it for non-binary (== not containing zero bytes) data?

**Comment by mcorino** [comment]
According to my tests it doesn't as far as I can tell.On 24 Feb 2024 19:30, VZ ***@***.***> wrote:
Thanks, using text/plain is clearly a bad idea for binary data, but I wonder if using application/octet-stream for text data doesn't have some drawbacks too?
Official documentation is useless, but there are some specific checks for text/plain in libsecret code, so maybe it would be better to keep using it for non-binary (== not containing zero bytes) data?

**Comment by vadz** [comment]
I'd still rather keep using text/plain for passwords because this comment

https://github.com/GNOME/libsecret/blob/a86c93d6f9ec4b4476eff1bbb4fe01ef50f03430/libsecret/secret-value.c#L35

clearly says that this is the right thing to do.

Would there be any problem with using application/octet-stream only if the data contains NUL bytes?

**Comment by mcorino** [comment]
Not really, but the code needs to be more structurally changed than since currently passwords and binary secrets are identically handled as far as the libsecret level are concerned.It will also impact all other platforms than.On 24 Feb 2024 20:54, VZ ***@***.***> wrote:
I'd still rather keep using text/plain for passwords because this comment
https://github.com/GNOME/libsecret/blob/a86c93d6f9ec4b4476eff1bbb4fe01ef50f03430/libsecret/secret-value.c#L35
clearly says that this is the right thing to do.
Would there be any problem with using application/octet-stream only if the data contains NUL bytes?

**Comment by vadz** [comment]
> Not really, but the code needs to be more structurally changed

Sorry, I may be missing something here, but I don't understand why. All I propose is to just do `memchr(data, 0, size) ? "application/octet-stream" : "text/plain"`, why not?

**Comment by mcorino** [comment]
On 2/24/24 23:28, VZ wrote:
>     Not really, but the code needs to be more structurally changed
> 
> Sorry, I may be missing something here, but I don't understand why. All 
> I propose is to just do |memchr(data, 0, size) ? 
> "application/octet-stream" : "text/plain"|, why not?

Because this won't work. My example binary secret in the issue for 
example was "secret\x1\x86\x2\x99\x3" (size 11) which does not contain
any NUL character but still is a binary secret that gets thrashed by
using "text/plain".
Binary secrets are not merely characterized by containing NUL characters 
but rather by any combination of byte values that are not recognized as 
proper text (printable ASCII or unicode characters) somehow.

So if you want to separate content types for those you will have to 
separate the interface into 2 paths for 'wxString' and for 'size_t, void*'.

**Comment by mcorino** [comment]
I added the required changes to keep the distinction between text and binary secrets.
Although this affects all platform implementations the changes themselves are rather trivial and do **not** affect the public API.

**Comment by vadz** [comment]
> Because this won't work. My example binary secret in the issue for instance was "secret\x1\x86\x2\x99\x3" (size 11) which does not contain any NUL character but still is a binary secret that gets thrashed by using "text/plain". Binary secrets are not merely characterized by containing NUL characters but rather by any combination of byte values that are not recognized as proper text (printable ASCII or unicode characters) somehow.

I'd really like to understand this "somehow" because now I have no idea what the problem actually is any more. I can understand the problem with not handling data with embedded NULs, but not this. Just in case, are you sure the distinction isn't between valid UTF-8 data and everything else? I.e. if you encode your test case in UTF-8, does it work?

> So if you want to separate content types for those you will have to separate the interface into 2 paths for 'wxString' and for 'size_t, void*'.

If the real distinction is indeed between UTF-8 and non-UTF-8 data, we could still do the simpler change but replacing `memchr()` with a check for UTF-8-well-formedness.

**Comment by mcorino** [comment]
On 2/25/24 15:00, VZ wrote:
>     Because this won't work. My example binary secret in the issue for
>     instance was "secret\x1\x86\x2\x99\x3" (size 11) which does not
>     contain any NUL character but still is a binary secret that gets
>     thrashed by using "text/plain". Binary secrets are not merely
>     characterized by containing NUL characters but rather by any
>     combination of byte values that are not recognized as proper text
>     (printable ASCII or unicode characters) somehow.
> 
> I'd really like to understand this "somehow" because now I have no idea 
> what the problem actually is any more. I can understand the problem with 
> not handling data with embedded NULs, but not this. Just in case, are 
> you sure the distinction isn't between valid UTF-8 data and everything 
> else? I.e. if you encode your test case in UTF-8, does it work?

I'm not quite sure what you do not understand here. The "somehow" refers 
to whatever the GNOME libsecret service storage process does with 
text/plain data. That's where the thrashing occurs.

Please inspect the extended secretstore sample code I attached with the 
issue and include in the PR.
That sample can be run to selftest with binary secrets where I make it 
create a secret like `wxSecretValue(11, "secret\x1\x86\x2\x99\x3")` 
which should be completely valid and no string encoding involved at all.

With the original libsecret based implementation this will get stored 
with content type "text/plain" and results in the thrashed secret being
returned after reloading from the store (you can see for your self if 
you run the extended sample with the current library code).

A complete check for UTF-8-well-formedness might work as well but I do 
not see how that is better than the last update to the PR I submitted
and it damn well won't be better performant.
Also I do not see why you would want to overrule the intent of the user 
who clearly indicates he/she/they want's to store a binary secret by 
using the wxSecretValue  'size_t, void*' ctor which might happen if you 
start to test any data for UTF-8 well-formedness.

**Comment by vadz** [comment]
> I'm not quite sure what you do not understand here. The "somehow" refers to whatever the GNOME libsecret service storage process does with text/plain data.

Well, this "whatever" is not clear to me. I thought you might already know what this "whatever" was, which is why I asked.

> That's where the thrashing occurs. Please inspect the extended secretstore sample code I attached with the issue and include in the PR.

I did see this code, but I don't know what does it return. I'll try to run it and check for myself.

> A complete check for UTF-8-well-formedness might work as well but I do not see how that is better than the last update to the PR I submitted and it damn well won't be better performant. 

I don't think we care that much about performance there, but, in principle, checking for this could avoid making an extra copy.

> Also I do not see why you would want to overrule the intent of the user who clearly indicates he/she/they want's to store a binary secret by using the wxSecretValue 'size_t, void*' ctor which might happen if you start to test any data for UTF-8 well-formedness.

This is a good point, thanks.

To summarize, determining which content type to use depending on `wxSecretValue` ctor selection is right (because of the argument above). But using different `NewImpl()` overloads for doing it seems a bit strange to me, especially considering that their implementation is exactly identical in MSW and Mac versions and almost the same in the Unix one. Could we just pass different content types to `NewImpl()` instead? Then MSW and Mac would still ignore it, but this doesn't seem too bad...

**Comment by mcorino** [comment]
> > I'm not quite sure what you do not understand here. The "somehow" refers to whatever the GNOME libsecret service storage process does with text/plain data.
> 
> Well, this "whatever" is not clear to me. I thought you might already know what this "whatever" was, which is why I asked.

No, I do not really know. I browsed the libsecret code shortly but could not immediately locate it. However I'm not really interested although I assume it's some sort of encoding issue. I do feel it is a really **BAD THING** that a secret store service should even consider touching the content of a secret I store.

> 
> To summarize, determining which content type to use depending on `wxSecretValue` ctor selection is right (because of the argument above). But using different `NewImpl()` overloads for doing it seems a bit strange to me, especially considering that their implementation is exactly identical in MSW and Mac versions and almost the same in the Unix one. Could we just pass different content types to `NewImpl()` instead? Then MSW and Mac would still ignore it, but this doesn't seem too bad...

Done.

**Comment by vadz** [comment]
Thanks for improving/simplifying this! Will merge soon.

**Comment by mcorino** [comment]
Will you backport this for 3.2.5 as well?

**Comment by vadz** [comment]
@mcorino Not sure if you've seen this, but I've added the label to look into backporting this. I'm not quite sure if it's ok to change the signature of (even a private) function, so I'd need to test it, but if not we can always add another overload instead, which is definitely fine.

**Comment by mcorino** [comment]
Thanks for looking into this.On 2 Mar 2024 17:05, VZ ***@***.***> wrote:
@mcorino Not sure if you've seen this, but I've added the label to look into backporting this. I'm not quite sure if it's ok to change the signature of (even a private) function, so I'd need to test it, but if not we can always add another overload instead, which is definitely fine.

**Comment by vadz** [comment]
Included in #24375.

**Pull request closed without merging**
