### PR TITLE
Use the original image to check for a mask

### PR DESCRIPTION
**Pull request by RobinD42**
Use the original image to check for a mask, not the one that may have had the mask converted to alpha.

In the OSX version of `wxBitmap::wxBitmap(const wxImage& image, int depth, double scale)` it is checking for a mask in `img` which may have been copied from the original and had the mask converted to an alpha channel. This PR changes it to look in the original image object instead.

### CODE REVIEW

**Comment by RobinD42** [comment]
See also: https://trac.wxwidgets.org/ticket/18944

**Comment by csomor** [comment]
What would be the minimal c++ sample code and file to test this ?

**Comment by RobinD42** [comment]
Adding the equivalent C++ code to the minimal sample should show the issue:

```python
        img = wx.Image('bluebox.png')
        if img.HasAlpha():
            img.ConvertAlphaToMask()
        print('image mask:', (img.GetMaskRed(), img.GetMaskGreen(), img.GetMaskBlue()))
        bmp = wx.Bitmap(img)
        print('bmp mask:', bmp.GetMask())
```

Here is the `bluebox.png` image:

bluebox

I'm getting a return value of `None` from `bmp.GetMask()`.

**Comment by csomor** [comment]
@RobinD42 is it ok if I commit my suggestion into this PR ?

**Comment by RobinD42** [comment]
Yes, go ahead and do whatever you need with it.

**Comment by csomor** [comment]
> Yes, go ahead and do whatever you need with it.

@RobinD42 ok, committed, I'd be glad if you could test, thanks

**Comment by RobinD42** [comment]
@csomor, everything is working as expected in my tests.

**Comment by csomor** [comment]
thanks

**Comment by RobinD42** [comment]
@csomor, is this ready to merge?

**Comment by csomor** [comment]
> @csomor, is this ready to merge?

@RobinD42 yes, if it works in your tests, then I think we should merge it and tell people to test master, it's very simple to rollback

**Pull request merged**
