### PR TITLE
 listBuilding wxGTK/Win32 using MSys2 fixed option "--disable-wxdib"

### PR DESCRIPTION
**Pull request by stahta01**
I have fixed the sample run-time issues when using configure option "--disable-wxdib".

Tim S.

### CODE REVIEW

**Comment by stahta01** [comment]
@vadz: Do you want me to change the default value for wxUSE_DIB to zero in configure/configure.in?

Tim S.

**Comment by vadz** [comment]
Sorry, I may have forgotten something, but why should `wxUSE_DIB` be set to 0 by default? AFAICS it should definitely be 1 for wxMSW and, arguably, for wxGTK under MSW too, but I don't really have any strong opinion about this port.

I'm merging the changes anyhow as they do make sense if `wxUSE_DIB` was actually set to 0, for whatever reason, thanks! Just one small request for the future PRs: could you please write your commit messages according to the [usual guidelines](https://chris.beams.io/posts/git-commit/)? TIA!

**Comment by stahta01** [comment]
@vadz I will try to follow the rules for commit messages in the link you posted. I did NOT know about the rules or I forgot about them.

In my past wxGTK/Win32 commits you was on the side of wxUSE_DIB be set to 0 by default.
I and the other person was on the other side. My changes allow the code to build if someone decide to make wxUSE_DIB=0 via a config option. Thank you for merging the changes.

Tim S.

**Comment by vadz** [comment]
> In my past wxGTK/Win32 commits you was on the side of wxUSE_DIB be set to 0 by default.

For wxGTK only, right? I was surprised because I thought you wanted to change its value to 0 for all ports for some reason, sorry. For wxGTK I can see arguments for both sides, and, as I said, personally I don't have any really strong opinion.

**Comment by stahta01** [comment]
Yes, you wanted wxUSE_DIB be set to 0 by default under wxGTK/Win32.

My next wxWidget work is to port the master branch wxGTK/Win32 configure work to the 3.0 branch.

Tim S.

**Pull request merged**
