### PR TITLE
Remove ole2.h check in configure

### PR DESCRIPTION
**Pull request by vadz**
Test AppVeyor Cygwin build.

### CODE REVIEW

**Comment by MaartenBent** [comment]
Now `wxUSE_OLE` and friends are never defined?

Also, if I look at the last successful cygwin build, it seems w32api is updated from 5.0 to 7.0. It is strange that it finds `w32api.h` but not `ole2.h` which should be [there](https://cygwin.com/cgi-bin2/package-grep.cgi?grep=w32api&arch=x86).
 Maybe try setting the include dir, same as is done for the [libraries](https://github.com/wxWidgets/wxWidgets/blob/master/build/tools/appveyor.bat#L52): add `CPPFLAGS=-I/usr/include/w32api`

**Comment by vadz** [comment]
Oops, I thought `wxUSE_OLE` would be defined by default but this is not the case.

I don't think we should have to add `/usr/include/w32api` explicitly, it worked without it before even though the headers were already in this directory. I suspect some error happens when including `ole2.h`, and I hoped to see it by allowing configure to finish and trying to actually compile the code using this header. Of course, there is also the fact that this configure test is useless and just wastes time unnecessarily when running it -- we should always have `ole2.h`, we're not in 1990 any longer...

**Comment by vadz** [comment]
OK, so the code including `ole2.h` compiles just fine. OTOH it doesn't link now. I feel like I'm missing something obvious here, but how did it work before without `-lole2` anywhere in sight?

**Comment by MaartenBent** [comment]
You removed `LIBS="-lrpcrt4 -loleaut32 -lole32 -luuid $LIBS"`, that might do it 😉

**Comment by vadz** [comment]
I _knew_ I was missing something obvious. Thanks for noticing what it was :-/

**Comment by vadz** [comment]
> 
> 
> OK, so the code including `ole2.h` compiles just fine. OTOH it doesn't link now. I feel like I'm missing something obvious here, but how did it work before without `-lole2` anywhere in sight?

Note to self: it's `-lole32`, of course, this is why my grep didn't find it.

**Comment by vadz** [comment]
OK, so I have no idea what was wrong with the configure test, but as just removing it works, let's simply do that.

**Pull request closed without merging**
