### PR TITLE
Qt build fixes

### PR DESCRIPTION
**Pull request by vadz**
I have these changes in a local branch since quite some time and, to be honest, I completely forgot about them and why hadn't they been merged before. @scottfurry Do you remember anything about this by chance?

### CODE REVIEW

**Comment by scottfurry** [comment]
Honestly, no. I recall submitting them. The commentary seems self explanatory. One thing I do vaguely recall is that there was deviations between the wxQT and other ports. The SetToolxxx and CreateTool function changes were addressing this deviation.

**Comment by vadz** [comment]
Do you remember how/where did you submit them by chance? I can't find the any matching PR, which might contain any explanation about why this hadn't been merged back then.

If we don't find any such explanation, I'm just going to merge them now.

**Comment by scottfurry** [comment]
What I do remember is that this wasn't submitted via wxTRAC and may have been an attachment to a message thread on the Google Groups page for wx-dev. I was able to search the archive history and came up with a link to the whole discussion - reason for change and original attachments.

https://groups.google.com/d/msg/wx-dev/IGcgvW5dVEo/67sdEIfCAwAJ

**Comment by vadz** [comment]
Thanks a lot for digging this up, it explains why I couldn't find it neither on Trac nor on Github. AFAICS I did just forget to merge these patches before, so I'm going to do it now. If you think more changes to `wxToolbar` are still needed, please don't hesitate to open new PRs. TIA!

**Pull request merged**
