### PR TITLE
Replace wxWidgets 1.xx compatibility functions

### PR DESCRIPTION
**Pull request by stahta01**
Reason: Length() is a wxWidgets 1.xx compatibility function.

### CODE REVIEW

**Comment by stahta01** [comment]
I am slowly fixing these problems a little at a time; you might wait till I finish to apply them.

**Comment by vadz** [comment]
Just FYI, you can mark the PR as being a draft until you finish it.

**Comment by stahta01** [comment]
I finished fixing them.

**Comment by vadz** [comment]
What about #22642, should it be closed?

**Comment by vadz** [comment]
Thanks, looks good to me, will merge soon.

**Pull request closed without merging**
