### PR TITLE
Remove support for Borland C++ compiler

### PR DESCRIPTION
**Pull request by PBfordev**
It seems that no one has been using recentish wxWidgets versions with Borland C++ compiler and it is unlikely that wxWidgets even still build with it (it did not when I tried). Therefore, in attempt to reduce the code rot, I propose removing its "support" from wxWidgets, see also [here](https://groups.google.com/d/topic/wx-users/jkGtwQirHBQ/discussion). However, I would fully understand if removing it would be considered time not well-spent and the PR rejected.

- [x] Remove BCC-specific `#pragma hdrstop` from all files
- [x] Remove clear-cut cases of BCC-specific conditionally compiled code
- [x] Remove BCC mentions from documentation
- [x] Remove BCC make and project files
- [x] Tell bakefile not to generate BCC config and make files anymore
- [x] Decide what to do with not-so-clear-cut cases of BCC-specific code and documentation, see below

I do not know how to tell bakefile to not generate BCC files: Do I just remove all those `<add-flags files= ... formats="borland">` blocks from `build/bakefiles/Bakefiles.bkgen`?

**Not-so-clear-cut cases of conditionally compiled code**
[include/wx/memory.h#L349](https://github.com/wxWidgets/wxWidgets/blob/master/include/wx/memory.h#L349)
The code now wrapped in ifdef 0 should now be safely used, but not sure replacing a macro with an inline function is not going to break something.

[include/wx/msw/init.h#L84](https://github.com/wxWidgets/wxWidgets/blob/master/include/wx/msw/init.h#L84)
There was BCC-specific version of `WinMain()` and the non-BCC version of `WinMain()` had to have the same parameters as BCC one. Not sure what to do here.

[src/common/fileconf.cpp#L2101](https://github.com/wxWidgets/wxWidgets/blob/master/src/common/fileconf.cpp#L2101)
The function is called three times, not only from the ctor initializer list. I would just remove the comment and kept the code as it is.

[src/generic/filectrlg.cpp#L1067](https://github.com/wxWidgets/wxWidgets/blob/master/src/generic/filectrlg.cpp#L1067)
Just as above, I would keep the code and remove the comment.

[interface/wx/app.h#L1183](https://github.com/wxWidgets/wxWidgets/blob/master/interface/wx/app.h#L1183)
Is MSVC still the only SEH-capable Windows compiler (stated also in setup.h), clang nor recent GCC still do not support this?

### CODE REVIEW

**Comment by vadz** [comment]
I really don't understand how is it possible, but this seems to have resulted in a reproducible (because it happened in 4 different builds) crash in wxGTK CI builds. Do you have any idea about how could this possibly happen?

**Comment by vadz** [comment]
Thanks for cleaning this up!

> I do not know how to tell bakefile to not generate BCC files: Do I just remove all those `<add-flags files= ... formats="borland">` blocks from `build/bakefiles/Bakefiles.bkgen`?

The simplest is probably to add "borland" to `<disable-formats>` line at the beginning of `build/bakefiles/Bakefiles.bkgen`.

> **Not-so-clear-cut cases of conditionally compiled code**
> [include/wx/memory.h#L349](https://github.com/wxWidgets/wxWidgets/blob/master/include/wx/memory.h#L349)
> The code now wrapped in ifdef 0 should now be safely used, but not sure replacing a macro with an inline function is not going to break something.

I don't see how it could, but OTOH we don't really care about these deprecarted macros anyhow, so please feel free to choose whichever branch of `#if` you prefer.

> [include/wx/msw/init.h#L84](https://github.com/wxWidgets/wxWidgets/blob/master/include/wx/msw/init.h#L84)
> There was BCC-specific version of `WinMain()` and the non-BCC version of `WinMain()` had to have the same parameters as BCC one. Not sure what to do here.

I'd just remove the "NB:" comment (because it doesn't make any sense now) and pass `lpCmdLine` to `wxEntry()`. It's unused there anyhow, but at least this would avoid the need for `WXUNUSED()` in `WinMain()`.

> [src/common/fileconf.cpp#L2101](https://github.com/wxWidgets/wxWidgets/blob/master/src/common/fileconf.cpp#L2101)
> The function is called three times, not only from the ctor initializer list. I would just remove the comment and kept the code as it is.

I don't think the function is called 3 times, I believe its 2 other occurrences refer to the member `wxConfigBase::GetAppName()` and not this function. This is definitely confusing and I'd rather get rid of this function, i.e. inline it into the ctor initializer list.

> [src/generic/filectrlg.cpp#L1067](https://github.com/wxWidgets/wxWidgets/blob/master/src/generic/filectrlg.cpp#L1067)
> Just as above, I would keep the code and remove the comment.

I'm ok to keep this one, it's harmless.

> [interface/wx/app.h#L1183](https://github.com/wxWidgets/wxWidgets/blob/master/interface/wx/app.h#L1183)
> Is MSVC still the only SEH-capable Windows compiler (stated also in setup.h), clang nor recent GCC still do not support this?

I think so, yes.

**Comment by PBfordev** [comment]
> I really don't understand how is it possible, but this seems to have resulted in a reproducible (because it happened in 4 different builds) crash in wxGTK CI builds. 

The explanation for this is quite simple: I made a stupid mistake. Hopefully it is properly [fixed](https://github.com/wxWidgets/wxWidgets/pull/2087/commits/6ba1b8c78cfb24c292371611e5b293b3036a9abf) now.

I have resolved the remaining issues based on your feedback, except I removed both util functions replacing them with a ternary operator call.

**Comment by vadz** [comment]
Thanks! All the changes look good to me, should I merge this now (I can fix the whitespace check failure myself)?

**Comment by PBfordev** [comment]
I'd rather not waste not your precious time fixing my sloppy mistakes, I was planning to commit the whitespace fix after Travis has finished. I had the builds open in a browser and they seemed to be going for hours, now I see they finished a long time ago.

BTW, I could not find a way to opt out of the e-mail notification about whitespace check failure: Is there any?

**Comment by vadz** [comment]
> I'd rather not waste not your precious time 

You're way too kind, but thank you.

> BTW, I could not find a way to opt out of the e-mail notification about whitespace check failure: Is there any?

Sorry, I have no idea where do these notifications come from, I didn't get any when I was testing this and introduced an intentional whitespace error in my PR adding them. Could this be some GitHub user account option perhaps? We don't have any non-default notification options in our workflow `.yml` file...

**Comment by vadz** [comment]
The failure in the AppVeyor build was bogus (another transient network error that we should really try to ignore somehow), so merged now.

Thanks again for your work on this!

**Pull request merged**
