### PR TITLE
Changed wxRichTextParagraph::m_cachedLines data type

### PR DESCRIPTION
**Pull request by mehmet-soyturk**
This is a follow-up to GH-2523.

With this PR the wxList version of cached lines is completely removed.

### CODE REVIEW

**Comment by vadz** [comment]
Thanks, this looks good to me, but we need to also update the documentation in `interface/wx/richtext/richtextbuffer.h` and mention that the incompatible change to the return type of `GetLines()` in the "INCOMPATIBLE CHANGES SINCE 3.0.x" section of `docs/changes.txt`.

**Comment by mehmet-soyturk** [comment]
Pushed a fix for a memory leak I had introduced.

In the mean time, I had tried to update interface/wx/richtext/richtextbuffer.h, but I had no idea how it should be updated.

**Comment by vadz** [comment]
> In the mean time, I had tried to update interface/wx/richtext/richtextbuffer.h, but I had no idea how it should be updated.

Sorry, what do you mean? There is currently
```cpp
    wxRichTextLineList& GetLines() { return m_cachedLines; }
```
there, which needs to be updated to use its actual return type now, that's all. What problem exactly do you have?

**Comment by mehmet-soyturk** [comment]
That was some time ago. I had rediscover what problem I had.

In the original header, `wxRichTextLineList` is defined like this:

```WX_DECLARE_LIST_WITH_DECL( wxRichTextLine, wxRichTextLineList , class WXDLLIMPEXP_RICHTEXT );```

Based on `WX_DECLARE_LIST_4`, I see that `wxRichTextLineList` ends up as a subclass of `wxListBase`.

In the interface header, `wxRichTextLineList` is only forward-declared, not defined (why?):

```class wxRichTextLineList;```

(It also fishy that `wxRichTextLineList` is actually used in that header file, which requires its definition, but the definition is missing. Another sign that I don't understand the purpose of that interface header).

Now, I have replaced `wxRichTextLineList` by `wxRichTextLineVector`. Now, `wxRichTextLineVector` is not a new class, but it is a typedef:

```typedef wxVector<wxRichTextLine*> wxRichTextLineVector;```

I was not sure what to put in the interface header in that case. You can't declare a typedef as a class. I could repeat the typedef there, but then I have to ensure that `wxVector` class is already accessible. Since I don't know in what context that interface header was used, I was not sure. Was it ok to add an include of `wx/vector.h` at the top? But no, as far as I can see, interface headers (this one at least) don't have any include. 

I know, I could have asked it at the time, but I was busy and lazy :)

**Comment by vadz** [comment]
> That was some time ago. I had rediscover what problem I had.
> 
> In the original header, `wxRichTextLineList` is defined like this:
> 
> `WX_DECLARE_LIST_WITH_DECL( wxRichTextLine, wxRichTextLineList , class WXDLLIMPEXP_RICHTEXT );`
> 
> Based on `WX_DECLARE_LIST_4`, I see that `wxRichTextLineList` ends up as a subclass of `wxListBase`.
> 
> In the interface header, `wxRichTextLineList` is only forward-declared, not defined (why?):
> 
> `class wxRichTextLineList;`

Because we don't want to use all these ugly macros in the documentation, so it just says that it's (some kind of) a list.
 
> (It is also fishy that `wxRichTextLineList` is actually used in that header file, which requires its definition, but the definition is missing. A sign that I don't understand the purpose of that interface header).

It's _only_ used for producing documentation. It shouldn't have any basic syntax mistakes, as this can confuse the tools parsing it (mainly Doxygen but not only), but it doesn't really matter if it doesn't compile.

To check that things work as expected, please run `docs/doxygen/regen.sh html` (or `.bat` if you don't have bash at hand). Feel free to set `WX_SKIP_DOXYGEN_VERSION_CHECK` environment variable to skip Doxygen version check.

> Now, I have replaced `wxRichTextLineList` by `wxRichTextLineVector`. Now, `wxRichTextLineVector` is not a new class, but it is a typedef:
> 
> `typedef wxVector<wxRichTextLine*> wxRichTextLineVector;`
> 
> I was not sure what to put in the interface header in that case. You can't forward-declare a typedef as a class. I could repeat the typedef there,

Yes, that's all you need to do.

> but then do I have to ensure that `wxVector` class is already defined?

No, this is not necessary. This class will be linked to `wxVector` in the generated documentation anyhow.

> I know, I could have asked it at the time, but I was busy and lazy :)

Hope this helps, but please let me know if you have any other questions.

**Comment by swt2c** [comment]
> Thank you for the information. I had wrongly suspected that the interface headers were used for bindings with scripting languages, and was not confident to update it without any knowledge.

The interface headers *are* used for bindings with scripting languages such as wxPython (possibly others: wxPerl?).

**Comment by vadz** [comment]
Thanks for the update, will merge in a moment.

**Pull request closed without merging**
