### PR TITLE
Added HTML Table Export to wxRichTextCtrl

### PR DESCRIPTION
**Pull request by ashishmore**
Added basic HTML table export to Richtext Table.

### CODE REVIEW

**Comment by tierra** [comment]
Thank you for your contribution but we don't actually use Github
pull requests for this mirror of wxWidgets repository.

Please submit your changes to [our Trac](http://trac.wxwidgets.org) as explained [here](http://trac.wxwidgets.org/wiki/HowToSubmitTicket) instead.

Thanks in advance!

**Comment by tierra** [comment]
Pinging @JulianSmart for this.

**Comment by JulianSmart** [comment]
Hi,

Sorry, I think this implementation is so simplistic as to have limited 
value. It strips out any formatting in cells. It might be worth be 
waiting for a proper implementation.

Regards,

Julian

**Comment by vadz** [comment]
I don't really think it's useful to keep this PR open if we're not going to apply it, as per [Julian's comment](https://github.com/wxWidgets/wxWidgets/pull/20#issuecomment-80742549).

**Pull request closed without merging**
