### PR TITLE
Simplify GetFileTypeFromExtension() function

### PR DESCRIPTION
**Pull request by IlyaBizyaev**

### CODE REVIEW

**Comment by vadz** [comment]
This code is basically not used at all, so while I don't really object to simplifying it, I'm not sure if there is any point in changing it...

**Comment by IlyaBizyaev** [comment]
I wonder then why it is preserved in the repository.
As far as the reasons are concerned, I think this would help to reduce the overall wxWidgets size.

**Comment by vadz** [comment]
It probably should be removed, I don't think anybody is still seriously thinking of doing anything under MS DOS. But it won't reduce overall wxWidgets size in any noticeable way (this is assuming you are speaking about the source code size, which I don't think anybody cares about anyhow -- removing this code will have 0 effect on the binary size as it's not compiled into it anyhow).

**Comment by IlyaBizyaev** [comment]
Honestly speaking, that was just a random contribution :smile: 
In fact, I do not see the purpose of this port at all, as most of its functions simply return `false`, and there is not much sense in porting a GUI framework to a console environment.
In my humble opinion, it can be simply removed.

**Comment by vadz** [comment]
Once upon a time there was a wxMGL port (based on SciTech MGL library, which doesn't seem to exist anywhere any more, not even on Wikipedia...) which worked under DOS. But yes, this was a long time ago...

**Comment by IlyaBizyaev** [comment]
I assume this code's existence now does not has any historical purpose, does it? So, what about removing it?

**Comment by vadz** [comment]
I'll try to do it next time I'm about to touch it but this is hardly high priority.

I'll close this PR though as it just doesn't make much sense to update this code, if anything it could create a mistaken impression that somebody is interested in it, which is not the case.

**Pull request closed without merging**
