### PR TITLE
Documentation for building under msys2 win32 wxGTK and wxQT

### PR DESCRIPTION
**Pull request by stahta01**
Added documentation to build wxQT/Win32 and edited wxGTK/Win32 to use GTK version 3.

### CODE REVIEW

**Comment by stahta01** [comment]
I did not realize that these files were added to documentation automatically. I will need to find out if these changes look good after the conversion. Can someone point me to the steps to do the   documentation conversion?

Tim S.

**Comment by stahta01** [comment]
After I installed the zip package, I was able to run "./release.sh 3.1.4" to verify the html docs was created correctly.

Tim S.

**Comment by vadz** [comment]
Sorry if I'm missing something but shouldn't `MINGW_PACKAGE_PREFIX` , `MSYSTEM_CARCH` etc be defined somewhere? I.e. AFAICS we don't tell people what to set them to, but we should, shouldn't we?

**Comment by stahta01** [comment]
> Sorry if I'm missing something but shouldn't `MINGW_PACKAGE_PREFIX` , `MSYSTEM_CARCH` etc be defined somewhere? I.e. AFAICS we don't tell people what to set them to, but we should, shouldn't we?

The MSys2 Mingw command prompts set them to different values depending on whether the mingw32 or mingw64 prompt is used. 

Tim S.

**Comment by vadz** [comment]
Sorry, I didn't realize this was specific to msys2 (I somehow misread it as being a general guide for building wxGTK and wxQt using MinGW).

I'll merge this in now, thanks!

**Pull request merged**
