### PR TITLE
wxNotificationMessage enhancements

### PR DESCRIPTION
**Pull request by TcT2k**
This is my initial effort to make **wxNotificationMessage** more usable across the current desktop OSs. 

This is what is already implemented and a few open ToDos:
- [X] Additional notification features
  - [X] SetIcon() to set a custom icon in the notification
  - [X] AddAction() to add actions to notifications
  - [X] Events for click, dismiss and actions
  - [X] Documentation of the new features
- [X] Additional test and demo facilities in dialogs sample
- [X] Refactor wxNotificationMessage to always use a wxNotificationMessageImpl
- [X] Generic toast notifications
- [X] OS X implementation using Notification Center
- [X] Windows 8+ toast notification support (Using basic WinRT support)

**Any input** on this especially for GTK are very welcome. I've looked into using [GNotification](https://wiki.gnome.org/HowDoI/GNotification) in addition to [libnotify](https://developer.gnome.org/libnotify/0.7/NotifyNotification.html) but I'm not sure of the benefits and what changes would be required in the rest of wxWidgets in order to be able to work with GNotification.

Possible Future Enhancements:
- OSX implementation
  - Support for second action (Also used by Apple implementation would be a little hackish and require a timer to check for active notifications)
  - Support for additional actions available since 10.10 (Public API does not seem to work on 10.10, private API available since 10.9 seems to work)
- Windows Implementation
  - Allow for more customization of the toast notifications

A few screen shots of generic Notifications on Windows 7:
wxnotification_generic wxnotification_generic_actions
windows 10 pro

### CODE REVIEW

**Comment by vadz** [comment]
Globally this looks great, thanks a lot for your work on this!

I'll try to find time to reread the first commit soon...

**Comment by TcT2k** [comment]
I've git rebased this on a current master, there where a few conflicts due to WinCE removal and pre XP cleanup. There where also some link errors for a DLL build that I fixed. AppVeyor build fails happen because of the 1 hour timeout and are unrelated to the changes.

**Comment by MaartenBent** [comment]
I tried it and found a few problems, especially when using the WinRT implementation (win10, vs2015):
- press show twice, then click on notification:
```Access violation in notifmsg.cpp r52```
- pressing show while a notification is shown, does not show the new notification
- always same icon (wxwidgets logo) in notification
- assert when selecting 'none' icon:
```src\common\artprov.cpp(359): assert ""Assert failure"" failed in wxArtProvider::GetMessageBoxIconId(): incorrect message box icon flags```


With ```wxUSE_WINRT 0```, win10, both vs2015 and GCC, I encounter ```Access violation in event.cpp r1838``` after the following:
- Show notification 2 times
- Close the dialogs sample (2nd notification is still shown).
No other problems, works great 👍.

With and without WinRT look the same, what is the advantage?

And some build warnings from GCC with wxUSE_WINRT 0:
```bash
../../src/msw/rt/notifmsgrt.cpp:494:59: warning: unused parameter 'shortcutPath' [-Wunused-parameter]
 bool wxToastNotificationHelper::UseToasts(const wxString& shortcutPath,
                                                           ^
../../src/msw/rt/notifmsgrt.cpp:495:21: warning: unused parameter 'appId' [-Wunused-parameter]
     const wxString& appId)
                     ^
../../src/msw/rt/notifmsgrt.cpp:513:97: warning: unused parameter 'notification' [-Wunused-parameter]
 wxNotificationMessageImpl* wxToastNotificationHelper::CreateInstance(wxNotificationMessageBase* notification)
                                                                                                 ^
../../src/msw/taskbar.cpp:207:42: warning: unused parameter 'icon' [-Wunused-parameter]
                            const wxIcon& icon)
                                          ^
```

**Comment by TcT2k** [comment]
Thanks for testing this on Windows.
I'll look into the issues you reported and fix the compiler warnings.

As for the difference for WinRT implementation and the standard "balloon notifications":
On Windows 10 they both show up as toast notifications. On Windows 8.x only the WinRT implementation shows up as Toast notifications. Further more the WinRT implementations notifications show up in the notification center and provide further possibility for customization (which is currently not used by the implementation).
It might make sense to rename `MSWEnableToastNotification` to something different like `MSWEnableShellIntegration` now that Win10 shows all notifications as toasts and to add this to the platform notes in the `wxNotificationMessage` notification.

**Comment by TcT2k** [comment]
I've updated this to address the issues reported by @MaartenBent .
This also includes more detailed platform notes in the documentation of `wxNotificationMessage`.

**Comment by MaartenBent** [comment]
I still have the same problems. Here are two fixes for ```src\msw\notifmsg.cpp```:

Close can be called 1 time to many, resulting in ```ms_refCountIcon``` becoming ```-1```. Fixed by modifying ```ReleaseIcon()```:
```c++
if ( ms_refCountIcon > 0 && !--ms_refCountIcon )
```

Access violation in ```event.cpp r1838``` when 2nd notification is shown while 1st one is still shown (i.e. press show twice and wait for timeout). Fixed by explicitly canceling existing notification when showing next one:
```c++
bool
wxBalloonNotifMsgImpl::Show(int timeout)
{
	// timout active event
	wxTaskBarIconEvent event(wxEVT_TASKBAR_BALLOON_TIMEOUT, ms_icon);
	OnTimeout(event);

    SetUpIcon(m_parent);
```

(I did not test the RT version).

**Comment by TcT2k** [comment]
@MaartenBent I've integrated your proposed changes and rebased on the latest master.

**Comment by Jun-T** [comment]
@TcT2k On OS X 10.8.5, build fails as
```
../src/osx/cocoa/notifmsg.mm:124:21: error: property 'contentImage' not found on object of type 'NSUserNotification *'
            m_notif.contentImage = icon.GetNSImage();
                    ^
```
Is 10.8 (Mountain Lion) still supported?

**Comment by TcT2k** [comment]
@Jun-T Yes building and running is still supported for OS X 10.7 and above. A runtime check for the property was already in place but a compile time guard was missing. See #220 for a fix.

**Comment by Jun-T** [comment]
@TcT2k Thanks!

**Pull request merged**
