### PR TITLE
Improve desktop environment detection under Wayland

### PR DESCRIPTION
**Pull request by joshua-stone**
This change should help address https://github.com/wxWidgets/wxWidgets/issues/24021

### CODE REVIEW

**Comment by imciner2** [comment]
I think these environment variables are actually independent of Wayland, so they would also possibly be present under X11.

For instance, I currently have X11 (`wxGetDisplayInfo().type` returns 1 for me), and I have the environment variable `XDG_SESSION_DESKTOP=mate` set. So it would be nice if the check for these variables were actually display-agnostic.

**Comment by paulcor** [comment]
I think checking for `XDG_CURRENT_DESKTOP` should be sufficient, anything old or oddball enough to not have it would likely be covered by the session manager code. I've done this now in 2d07dd25b4bf120a7c85baa44e09b17e611a2c08, please let me know if you find any problems with it.

**Comment by joshua-stone** [comment]
Hey @paulcor, thanks for adding that enhancement!

I think the one major enhancement left for addressing https://github.com/wxWidgets/wxWidgets/issues/24021 is getting monitor properties under Wayland. I was able to use some [Python GTK examples](https://stackoverflow.com/questions/65807310/how-to-get-total-screen-size-in-python-gtk-without-using-deprecated-gdk-screen) to get monitor dimensions, but I haven't successfully ported these over to wxWidgets.

**Comment by vadz** [comment]
AFAICS this should be backported to 3.2 too, so adding the label.

**Pull request closed without merging**
