### PR TITLE
Add support for WebKit2GTK+ in wxWebView

### PR DESCRIPTION
**Pull request by swt2c**
This is a backport of cbe0a1f04928963085c0056a63c4930a73829e05.

It would be great if this could make it into 3.0.3, but I can understand too if you want to hold off from introducing it at the last minute.

### CODE REVIEW

**Comment by vadz** [comment]
I'm sorry, I'm too afraid of merging this before 3.0.3. It can still be done for 3.0.4, which we'll almost certainly end up doing, but right now I don't want to take the risk.

**Comment by leio** [comment]
Can this be reviewed and merged to WX_3_0_BRANCH rather quickly afterwards (at least the review) at least then? I need this to remove dependence on security vulnerable webkit-gtk. All versions of WebKitGTK+ old API are vulnerable by over hundred of vulnerabilities. For 3.0.3 I will need to add the patches from here manually then, and rush to make all wxWebView consumers use the gtk3 parallel installed version, as webkit2gtk does not exist for gtk2.

**Comment by vadz** [comment]
Thanks, I've merged this now, but I haven't really tested nor even reviewed it, so more testing would definitely be welcome, I don't use 3.0 branch personally, so am unlikely to find and fix any problems myself.

One small thing I did notice is that we have a new `include/wx/gtk/webview_webkit2_extension.h` header which is private, i.e. only used by the library itself. It would be better to put it under `include/wx/gtk/private` to make this more clear (and avoid accidentally including it from public headers). This looks trivial to do, but I didn't dare doing this without testing. If you could please do this, for both master and 3.0, this would be great.

Thanks again!

**Comment by swt2c** [comment]
Thanks.  Of course, I am willing to address any bugs so feel free to direct them my way.

One thing I just noticed - it seems that the changes to `samples/webview/Makefile.in` were omitted from your commit.  Was this intentional?

Yes, I'll do another PR to move webview_webkit2_extension.h.

**Comment by vadz** [comment]
> it seems that the changes to `samples/webview/Makefile.in` were omitted from your commit. Was this intentional?

No, I cherry picked it (didn't want to make a merge for a single commit) after rebaking the makefiles after the version change, but that's all I did, i.e. no manual changes. And rebaking now I see no changes neither. I can't look at this any more today, so if you could check what's going on there, it would be great, thanks again!

**Comment by swt2c** [comment]
> No, I cherry picked it (didn't want to make a merge for a single commit) after rebaking the makefiles after the version change, but that's all I did, i.e. no manual changes. And rebaking now I see no changes neither. I can't look at this any more today, so if you could check what's going on there, it would be great, thanks again!

OK, I see what happened.  Your rebake for the version change incorporated the same changes to that file, so the changes in my PR were already in place.

**Pull request closed without merging**
