### PR TITLE
Allow to build libpng on more platforms, enable SSE2

### PR DESCRIPTION
**Pull request by MaartenBent**
Allow to build libpng on more platforms, enable SSE2.

### CODE REVIEW

**Comment by vadz** [comment]
Thanks, I think this should do the right thing on Intel, but it seems like we're still never going to enable SIMD support under other archs, right? I.e. we still don't define `PNG_ARM_NEON_OPT`?

FWIW there are fragments for doing it in `src/png/CMakeLists.txt` and `configure.ac` that we could probably steal...

Of course, this doesn't have to be done in this PR, I'd just like to check whether I understand it correctly.

Finally, I also wonder if you ran `LoadPNG` benchmark from `tests/benchmarks` before/after this change and if this had any noticeable result?

**Comment by MaartenBent** [comment]
All except `PNG_INTEL_SSE_OPT` are enabled by default in `pngpriv.h` if nothing is defined.

I haven't run any benchmarks, I'll check it later.

**Comment by vadz** [comment]
OK, so I was missing something, thanks for the explanation.

As for benchmarks, I was curious, so I ran `./bench_gui.exe -n 100 LoadPNG` myself a few times. The result show a definitive improvement, from 236ms to 207ms, so this is definitely welcome even if not life-changing. Thanks again!

**Comment by vadz** [comment]
I'm now getting the following
```
src/png/mips/filter_msa_intrinsics.c:20:5: warning: "PNG_MIPS_MSA_IMPLEMENTATION" is not defined, evaluates to 0 [-Wundef]
   20 | #if PNG_MIPS_MSA_IMPLEMENTATION == 1 /* intrinsics code from pngpriv.h */
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~
src/png/powerpc/filter_vsx_intrinsics.c:19:5: warning: "PNG_POWERPC_VSX_IMPLEMENTATION" is not defined, evaluates to 0 [-Wundef]
   19 | #if PNG_POWERPC_VSX_IMPLEMENTATION == 1 /* intrinsics code from pngpriv.h */
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

when cross-compiling from Linux to MSW. Do you already see a fix for this by chance or should I try to understand how this works or just apply something similar to https://github.com/wxWidgets/libpng/commit/8cb5f8f1587b95a0e86fa8c2becea0cef8ee0a8b without even trying to understand?

**Comment by MaartenBent** [comment]
The libpng build files only include these files when building on/for a mips/vsx processor. So when these files are built, those defines are also defined.
I just added all build files and rely on the checks in `pngpriv.h` to defines them. I think the best solution is indeed to do the same as for `PNG_ARM_NEON_IMPLEMENTATION`. And you've also done this for `PNG_INTEL_SSE_IMPLEMENTATION` https://github.com/wxWidgets/libpng/commit/d532334ef514e9625559e76c83119d317ca790f3 already.

**Pull request merged**
