### PR TITLE
Added missing implementation of wxScrollBar::SetThumbSize in wxGTK

### PR DESCRIPTION
**Pull request by temnyak**

### CODE REVIEW

**Comment by vadz** [comment]
Thanks! I'm applying this, but the really best thing to do would seem to be to move this (and the others, i.e.  `SetPageSize()` and `SetRange()`) to `wx/scrollbar.h` as they seem to be implemented in exactly the same way for wxGTK, wxOSX and wxMSW while the other ports don't have them at all.

If you could please make another patch doing this, it would be welcome. I guess we should also document these methods...

**Comment by temnyak** [comment]
Okay, I'll make another patch that moves those helper methods to
wx/scrollbar.h and adds some documentation as well.

**Comment by temnyak** [comment]
Hi,
is there a preffered way of documenting the code? I've seen different ways
in different files. Now I'm not sure which one I should use...

**Comment by vadz** [comment]
The documentation is in the files under `interface` directory (i.e. `interface/wx/scrollbar.h` in this case) and use Doxygen comments.

**Pull request closed without merging**
