### PR TITLE
 Removing last column in generic wxDataViewCtrl causes crash on MacOS

### PR DESCRIPTION
**Pull request by Anil8753**
On removal of the last column, m_hover still hold the index of the column which is already deleted. 
On Mouse hover, m_hover column index is trying to get refreshed, but this column is not present now.

```
   if ( col != m_hover )
    {
        const unsigned hoverOld = m_hover;
        m_hover = col;

        RefreshColIfNotNone(hoverOld);
        RefreshColIfNotNone(m_hover);
    }
```

Call to RefreshColIfNotNone(hoverOld); results in GetColumn(hoverOld) which returns nullptr result into crash.

### CODE REVIEW

**Comment by vadz** [comment]
Thanks for the fix! I agree with the fix itself, i.e. the second change in this diff, but I don't see any real reason to apply the first and the third ones, so I didn't do it. Please let me know if it should be done and why.

**Comment by Anil8753** [comment]
First change:
-const unsigned COL_NONE = (unsigned)-1;
+const int COL_NONE = -1;

Just take a hypothetical case:
(unsigned)-1; makes the COL_NONE a large positive number. In case if we check the condition like (col_index > COL_NONE) with the assumption that for a valid column, col_index will be greater than COL_NONE but this condition will fail as COL_NONE is a large positive number. 

Third change:
int wxHeaderCtrl::GetColStart(unsigned int idx) const
 {
     int pos = m_scrollOffset;
-    for ( unsigned n = 0; ; n++ )
+    for ( unsigned n = 0; n < m_colIndices.Count(); n++ )
     {
         const unsigned i = m_colIndices[n];
         if ( i == idx )

We do not need this change as we are taking care of m_colIndices will have idx always. 
I just kept a safety check, now it will not cause any crash in case the wrong idx is passed through the function.

**Comment by Anil8753** [comment]
@vadz I provided the explanation for first and third. Please check it.

**Comment by vadz** [comment]
Sorry, I disagree with these explanations. The first one would make sense if we use `int`s for column indices, but we don't -- we use `unsigned`. Whether it's a good or a bad thing is open to debate, but we're not going to change it, and when checking the validity of unsigned indices, it definitely makes sense to keep `COL_NONE` unsigned.

As for the other one, it would be wrong to silently ignore bad parameters passed to `GetColStart()`. If this happens, we should really assert instead of returning nonsensical values. What you added isn't really a safety check as sweep-unsafety-under-the-carpet hack and we don't want to do this.

**Comment by Anil8753** [comment]
Thank you @vadz , no issue.

**Pull request closed without merging**
