### PR TITLE
Add wxValidationStatusEvent event type

### PR DESCRIPTION
**Pull request by AliKet**
This will replace [PR](https://github.com/wxWidgets/wxWidgets/pull/1117)

### What problems this PR tries to address ?

- Brings a unified and customisable way to show validation errors.
- Ability to replace error messages coming from built-in validators with ours.
- Solves the problem with `wxNumValidators` when ranges are involved. that is, a control limited by values ​​in the ranges such as [0.5, 1.0] or [10, 20] should allow the values ​​0 and 1 to be entered instead of being discarded as values ​​out of range!
- Disable the **Ok** button if there is an invalid window was not possible. see [this commit](https://github.com/wxWidgets/wxWidgets/pull/1501/commits/cbcebf20f08a850cd2a292a595cad4b7fd1d6fbe) which shows how we could implement such functionality now.

### Cons:

This PR add a new (non-overridable) function `ReportValidation()` that should be called in new code instead of calling `Validate()` directly. In fact, even the call to `Validate()` was not mandatory either as it is always called automatically when the dialog containing the control is closed affirmatively.
Concerning `Validate()`, when overridden, it is advisable (but not required) to call `SendErrorEvent()` with the error message and process validation events elsewhere instead of displaying the error message from the `Validate()` itself. that is not to say that a direct call to `Validate()` is not possible, it is, but the new approach is to call `ReportValidation()` instead, or let the dialog do the automatic call for you.

One more thing is that validations now are done as soon as possible in this order:

1. Interactively (enabled by `wxValidator::SetInteractive()`, disabled by default).
2. On focus lost. (1&2 no popup by default)
3. On dialog close (might pop up an error message).

Notice that a validated control will not be validated again unless:
- The value in the control has changed.
- The previous validation failed.
- Explicit call to `Validate()` in a `wxEVT_KILL_FOCUS` handler defined by the caller.

### CODE REVIEW

**Comment by vadz** [comment]
Before getting into the details of the changes, could you please explain in a few words what is the scope of this PR exactly? I see that it adds the new event, but it's not immediately clear how does it change the existing validators (or does it?) and/or user code? TIA!

**Comment by AliKet** [comment]
> Before getting into the details of the changes, could you please explain in a few words what is the scope of this PR exactly? I see that it adds the new event, but it's not immediately clear how does it change the existing validators (or does it?) and/or user code? TIA!

Sure, I'll do that after updating this PR
Thank you.

**Comment by AliKet** [comment]
@vadz sorry for the delay...
can you take a quick look at this please ?
TIA!

**Comment by AliKet** [comment]
@vadz 

Does this PR have a chance to be part of the next release ?

BTW:
What this [PR](https://github.com/wxWidgets/wxWidgets/pull/1423) tries to do is fixed by this [commit](https://github.com/wxWidgets/wxWidgets/pull/1501/commits/31a557ed1c1f6679328dd00ece91e74f07144d9d)
My question is: is it okay to do it in this PR or should it be in another one?

**Comment by AliKet** [comment]
superseded by #1763

**Pull request closed without merging**
