### PR TITLE
Fix range checking issue (in wxNumValidator) causing the control to be locked down forever

### PR DESCRIPTION
**Pull request by AliKet**
The issue is that when you are required to work with a predefined set of values in the range `[m_min, m_max]` you may find that the control is not responding at all, as it was locked down for some good reason!

This is because we are enforcing that the entered value be in the specified range **while we are still typing**, which is clearly not going to work as expected. e.g.:

Say you have set `m_min` to `10` and you want to enter `12` or `99` in the control. regardless of the way you enter the value, just typing the first number will make the validation fail prematurely.

### CODE REVIEW

**Comment by vadz** [comment]
This problem (originally reported in [this ticket](http://trac.wxwidgets.org/ticket/12968)) definitely needs to be fixed, but I don't think disabling the checks for the valid range, as this PR does unless I'm missing something, is the best way to do it.

IMO we indeed need to accept the keys making the value temporarily invalid, but we must generate some event indicating the change in the validity status, e.g. to allow changing the background of the control to red or disabling the "Apply" button or whatever.

FWIW I intend to work on this and also look at your other PR in details a.s.a.p. and hopefully relatively soon now that the font changes are (almost) done.

**Comment by AliKet** [comment]
No, this PR does not ignore range checking entirely as you might think, just the minimum bound checking inside `IsCharOk()` hence inside `OnChar()` seemed to me not quite right and should be deferred till the user finish typing the whole value. 

Yet the range checking is still done when `TransferFromWindow()` is called, and by `OnKillFocus()` (with possibly resetting the control to its `m_min` or `m_max` if value is out of range)

So, i came up with an idea which let us type in the first digit and (with a sort of autocompletion) the control will put :
 - a viable number from the range `[m_min , m_max]` beginning with the entered digit(s) with the rest digits (if any) selected
 - nothing if it can't find such viable number

Exp. 1) range [20, 99]:
entered number              viable number            selection
1                                      nothing                      nothing
2                                      20                              0
26                                    26                              nothing
9                                      90                              0


Exp. 2) range [320, 750]:
entered number              viable number            selection
1                                      nothing                      nothing
2                                      nothing                      nothing
3                                      320                            20
5                                      500                            00
56                                    560                            0
8                                      nothing                      nothing

I've implemented this locally and it works for both validators.

**Comment by AliKet** [comment]
Hi @vadz 

would you review this PR again please?

**Comment by vadz** [comment]
I will, but unfortunately not any time soon -- we really need to make the next release first (and this PR won't be part of it).

**Pull request closed without merging**
