### PR TITLE
macOS wxBitmap scale factor experiments

### PR DESCRIPTION
**Pull request by csomor**
- Adding assertions so that scaled dimensions are never fractions
- Support auto-loading of @3 resources on platforms that have a scale factor of 3
- Experiment with different API options for scaled bitmaps on macOS and iOS

### CODE REVIEW

**Comment by vadz** [comment]
I've extracted `@3x` part into #1983, not sure if this one should be kept opened or not...

**Comment by csomor** [comment]
yes, I thought about doing the multi-res experiments with wxBitmap here, 

is there an easy way to get rid of the extracted changes in this PR, as I fear things will collide ?

**Comment by vadz** [comment]
Sorry, I'm still confused about what is this PR for exactly, I'd prefer to just close it, do you still think it's worth leaving it open?

**Comment by csomor** [comment]
> Sorry, I'm still confused about what is this PR for exactly, I'd prefer to just close it, do you still think it's worth leaving it open?

no, it been superseeded by the multi-res PR

**Pull request closed without merging**
