### PR TITLE
Make wxWindow::TransferData{To,From}Window and Validate working on self too

### PR DESCRIPTION
**Pull request by AliKet**
See this [ticket](https://trac.wxwidgets.org/ticket/9326)

It is unlikely that this PR would introduce any regression seeing that validation
was made recursive by default after this [changes](https://github.com/wxWidgets/wxWidgets/commit/d50abc2d3eb87e72d0f31a96ebc24bbaac567e4d).

### CODE REVIEW

**Comment by AliKet** [comment]
This patch:
```
diff --git a/samples/validate/validate.cpp b/samples/validate/validate.cpp
index 669c0909d0..065f3cfdf1 100644
--- a/samples/validate/validate.cpp
+++ b/samples/validate/validate.cpp
@@ -23,6 +23,7 @@
 
 #include "validate.h"
 
+#include "wx/notebook.h"
 #include "wx/sizer.h"
 #include "wx/valgen.h"
 #include "wx/valtext.h"
@@ -239,6 +240,14 @@ MyDialog::MyDialog( wxWindow *parent, const wxString& title,
                     const wxPoint& pos, const wxSize& size, const long WXUNUSED(style) ) :
     wxDialog(parent, VALIDATE_DIALOG_ID, title, pos, size, wxDEFAULT_DIALOG_STYLE|wxRESIZE_BORDER)
 {
+    auto topsizer = new wxBoxSizer(wxVERTICAL);
+
+    auto notebook = new wxNotebook(this, wxID_ANY);
+    topsizer->Add(notebook, 1, wxGROW);
+
+    auto panel = new wxPanel(notebook, wxID_ANY);
+    notebook->AddPage(panel, "Page");
+
     // setup the flex grid sizer
     // -------------------------
 
@@ -247,24 +256,24 @@ MyDialog::MyDialog( wxWindow *parent, const wxString& title,
     // Create and add controls to sizers.
     // Pointers to some of these controls are saved in member variables
     // so that we can use them elsewhere, like this one.
-    m_text = new wxTextCtrl(this, VALIDATE_TEXT);
+    m_text = new wxTextCtrl(panel, VALIDATE_TEXT);
     m_text->SetToolTip("wxTextValidator not set");
     m_text->SetHint("Enter some text here, please...");
     flexgridsizer->Add(m_text, 1, wxGROW);
 
     // Make it possible to change the wxTextValidator for m_text at runtime.
     wxButton* const button =
-        new wxButton(this, wxID_ANY, "Set new wxTextValidator...");
+        new wxButton(panel, wxID_ANY, "Set new wxTextValidator...");
     button->Bind(wxEVT_BUTTON, &MyDialog::OnChangeValidator, this);
     flexgridsizer->Add(button, wxSizerFlags().Center());
 
-    flexgridsizer->Add(new wxListBox((wxWindow*)this, VALIDATE_LIST,
+    flexgridsizer->Add(new wxListBox((wxWindow*)panel, VALIDATE_LIST,
                         wxDefaultPosition, wxDefaultSize,
                         3, g_listbox_choices, wxLB_MULTIPLE,
                         wxGenericValidator(&g_data.m_listbox_choices)),
                        1, wxGROW);
 
-    m_combobox = new wxComboBox(this, VALIDATE_COMBO, wxEmptyString,
+    m_combobox = new wxComboBox(panel, VALIDATE_COMBO, wxEmptyString,
                                 wxDefaultPosition, wxDefaultSize,
                                 3, g_combobox_choices, 0L,
                                 MyComboBoxValidator(&g_data.m_combobox_choice));
@@ -275,7 +284,7 @@ MyDialog::MyDialog( wxWindow *parent, const wxString& title,
     // because we don't use it elsewhere--it can be anonymous.
     // We don't need any such pointer to query its state, which
     // can be gotten directly from g_data.
-    flexgridsizer->Add(new wxCheckBox(this, VALIDATE_CHECK, "Sample checkbox",
+    flexgridsizer->Add(new wxCheckBox(panel, VALIDATE_CHECK, "Sample checkbox",
                         wxDefaultPosition, wxDefaultSize, 0,
                         wxGenericValidator(&g_data.m_checkbox_state)),
                        1, wxALIGN_CENTER|wxALL, 15);
@@ -300,7 +309,7 @@ MyDialog::MyDialog( wxWindow *parent, const wxString& title,
 
     m_numericTextInt = new wxTextCtrl
                            (
-                                this,
+                                panel,
                                 wxID_ANY,
                                 "",
                                 wxDefaultPosition,
@@ -308,7 +317,7 @@ MyDialog::MyDialog( wxWindow *parent, const wxString& title,
                                 wxTE_RIGHT,
                                 valInt
                             );
-    numSizer->Add(new wxStaticText(this, wxID_ANY, "Positive integer:"),
+    numSizer->Add(new wxStaticText(panel, wxID_ANY, "Positive integer:"),
                   center);
     numSizer->Add(m_numericTextInt, wxSizerFlags(center).Expand());
 
@@ -316,7 +325,7 @@ MyDialog::MyDialog( wxWindow *parent, const wxString& title,
 
     m_numericTextDouble = new wxTextCtrl
                               (
-                                this,
+                                panel,
                                 wxID_ANY,
                                 "",
                                 wxDefaultPosition,
@@ -330,15 +339,15 @@ MyDialog::MyDialog( wxWindow *parent, const wxString& title,
                                     wxNUM_VAL_NO_TRAILING_ZEROES
                                 )
                               );
-    numSizer->Add(new wxStaticText(this, wxID_ANY, "Up to 3 decimals:"),
+    numSizer->Add(new wxStaticText(panel, wxID_ANY, "Up to 3 decimals:"),
                   center);
     numSizer->Add(m_numericTextDouble, wxSizerFlags(center).Expand());
 
     wxIntegerValidator<unsigned short> smallIntVal(&g_data.m_smallIntValue);
     smallIntVal.SetRange(1, 5);
-    numSizer->Add(new wxStaticText(this, wxID_ANY, "Int between 1 and 5:"),
+    numSizer->Add(new wxStaticText(panel, wxID_ANY, "Int between 1 and 5:"),
                   center);
-    numSizer->Add(new wxTextCtrl(this, wxID_ANY, "",
+    numSizer->Add(new wxTextCtrl(panel, wxID_ANY, "",
                                  wxDefaultPosition, wxDefaultSize, wxTE_RIGHT,
                                  smallIntVal),
                   wxSizerFlags(center).Expand());
@@ -349,9 +358,9 @@ MyDialog::MyDialog( wxWindow *parent, const wxString& title,
     percentVal.SetPrecision(2);
     percentVal.SetFactor(100.0);
 
-    numSizer->Add(new wxStaticText(this, wxID_ANY, "Value displayed in %:"),
+    numSizer->Add(new wxStaticText(panel, wxID_ANY, "Value displayed in %:"),
                   center);
-    numSizer->Add(new wxTextCtrl(this, wxID_ANY, "",
+    numSizer->Add(new wxTextCtrl(panel, wxID_ANY, "",
                                  wxDefaultPosition, wxDefaultSize, wxTE_RIGHT,
                                  percentVal),
                   wxSizerFlags(center).Expand());
@@ -363,7 +372,7 @@ MyDialog::MyDialog( wxWindow *parent, const wxString& title,
 
     mainsizer->Add(flexgridsizer, 1, wxGROW | wxALL, 10);
 
-    mainsizer->Add(new wxRadioBox((wxWindow*)this, VALIDATE_RADIO, "Pick a color",
+    mainsizer->Add(new wxRadioBox((wxWindow*)panel, VALIDATE_RADIO, "Pick a color",
                                     wxDefaultPosition, wxDefaultSize,
                                     3, g_radiobox_choices, 1, wxRA_SPECIFY_ROWS,
                                     wxGenericValidator(&g_data.m_radiobox_choice)),
@@ -371,14 +380,14 @@ MyDialog::MyDialog( wxWindow *parent, const wxString& title,
 
     mainsizer->Add( numSizer, wxSizerFlags().Expand().DoubleBorder() );
 
-    mainsizer->Add(CreateButtonSizer(wxOK | wxCANCEL),
-                   wxSizerFlags().Expand().DoubleBorder());
+    topsizer->Add(CreateButtonSizer(wxOK | wxCANCEL),
+                  wxSizerFlags().Expand().DoubleBorder());
 
-    SetSizer(mainsizer);
-    mainsizer->SetSizeHints(this);
+    panel->SetSizer(mainsizer);
+    SetSizerAndFit(topsizer);
 
-    // make the dialog a bit bigger than its minimal size:
-    SetSize(GetBestSize()*1.5);
+     // make the dialog a bit bigger than its minimal size:
+//    SetSize(GetBestSize()*1.5);
 
     // Now sets the focus to m_text
     m_text->SetFocus();
```

still works correctly with these changes!

**Comment by vadz** [comment]
Thanks, I think this is fine to merge, but just a question: are the changes to the test required? I don't really understand why were they done (and the commit message doesn't say), but I'd rather avoid applying them, at least for now, because they will conflict with #2244. 

Please let me know if it's ok if I merge just the first 2 commits here, TIA!

**Comment by vadz** [comment]
P.S. OTOH it probably would be useful to add a test explicitly checking that validation now applies to the window itself and its children, unlike before.

**Comment by AliKet** [comment]
> P.S. OTOH it probably would be useful to add a test explicitly checking that validation now applies to the window itself and its children, unlike before.

Yes i am for this option. and I'll add seperate test for it soon.

**Pull request merged**
