### PR TITLE
Don't attempt to uncheck menu radio item (wxGTK).

### PR DESCRIPTION
**Pull request by a-wi**
Unchecking radio item makes no sense.
Similar mechanism of preventing from unchecking radio item is already implemented in wxMSW.

### CODE REVIEW

**Comment by a-wi** [comment]
See http://trac.wxwidgets.org/ticket/17318

**Comment by vadz** [comment]
I'm a bit worried about inverting the order of `gtk_check_menu_item_set_active()` and `wxMenuItemBase::Check()` calls, don't we have some callback executing when the former is called? If we do, the item state would be opposite to what it was before now...

**Comment by a-wi** [comment]
Fortunately, in wxMenuItemBase::Check() there is only set respective internal flag.
In wxMSW implementation wxMenuItemBase::Check() is called at the end of wxMenuItem::Check() when all native controls are already updated.

**Comment by vadz** [comment]
Thanks for checking this, committed as dbd98a107887b568faf0ef8bb930042f1941e10b

**Comment by a-wi** [comment]
@vadz: You were right, for wxGTK the order of calling gtk_check_menu_item_set_active() and wxMenuItemBase::Check() matters. When wxMenuItemBase::Check() is called after gtk_check... then spurious wxEVT_MENU is generated when menu item is checked.
Regression fixed in 13783d87.

**Pull request closed without merging**
