### PR TITLE
Handle window message WM_APPCOMMAND

### PR DESCRIPTION
**Pull request by jensgoe**
I wanted to handle the special events "browser forward" and "browser backward" to realize navigation in my own wxPanel. Therefore the windows message WM_APPCOMMAND exists. I handled this message and transfered the data via a wxKeyEvent. Now i can react to special key events for instance open the calculater, adjust volume etc. and of course the navigation buttons forward and backward (mouse and keyboard).

Maybe it is useful to add all the APP_COMMAND constants to wxWdgedts (https://msdn.microsoft.com/de-de/library/windows/desktop/ms646247%28v=vs.85%29.aspx).

Maybe you can check if this feature is usefull for wxWidgets so i can continue developing this branch. Comments are welcome.

### CODE REVIEW

**Comment by vadz** [comment]
It would be nice to know if there is anything equivalent to `WM_APPCOMMAND` on the other platforms. I think there should be, but it would be great to have a confirmation and to look at the API to check if it's reasonable to represent this by `wxKeyEvent` or if we should be using something else.

If it's really completely MSW-specific, I don't see any big advantage in adding it to wxWidgets as it's simple enough to just override its `MSWHandleMessage()` or use `MSWRegisterMessageHandler()`.

**Comment by jensgoe** [comment]
Thanks for your quick response. You are absolutly right so i checked at least GTK. GTK has already defined key codes for those special keys. And GTK handles these as keyboard events which is somehow clear because these are keyboard keys ;-). So i decided to add keycodes in wxWidgets as well. Maybe you can check if this fits better into wxWidgets.
I don't know how to treat other platforms. I never used motif, osx, x11 and so on. I can at least get QT to work.

**Comment by MaartenBent** [comment]
can't you use the `VK_name` keys directly instead of using appcommand?
From `WinUser.h`:
```
#define VK_BROWSER_BACK        0xA6
#define VK_BROWSER_FORWARD     0xA7
#define VK_BROWSER_REFRESH     0xA8
#define VK_BROWSER_STOP        0xA9
#define VK_BROWSER_SEARCH      0xAA
#define VK_BROWSER_FAVORITES   0xAB
#define VK_BROWSER_HOME        0xAC

#define VK_VOLUME_MUTE         0xAD
#define VK_VOLUME_DOWN         0xAE
#define VK_VOLUME_UP           0xAF
#define VK_MEDIA_NEXT_TRACK    0xB0
#define VK_MEDIA_PREV_TRACK    0xB1
#define VK_MEDIA_STOP          0xB2
#define VK_MEDIA_PLAY_PAUSE    0xB3
#define VK_LAUNCH_MAIL         0xB4
#define VK_LAUNCH_MEDIA_SELECT 0xB5
#define VK_LAUNCH_APP1         0xB6
#define VK_LAUNCH_APP2         0xB7
```

**Comment by jensgoe** [comment]
Good question. I recently used WM_APPCOMMAND to handle these events. Probably it will work by using theses key codes in the WM_KEYDOWN as well. The good thing right now is, that the BACK and FORWARD commands works when hitting the mouse buttons (thumb) as well. But maybe this is not intuitive because it is not really a key down event.

**Comment by MaartenBent** [comment]
If I use the `keyboard` sample, media keys already generate events. (Though they probably need an explicit mapping in `gs_specialKeys` to a `WXK_*`, like your GTK implementation.)

Back and forward on the mouse generate `EVT_MOUSE_AUX1` and `EVT_MOUSE_AUX2` events. I don't know about other (extra) mouse buttons.

**Comment by jensgoe** [comment]
Ok, i updated my branch. The overall change are just the new wx-key constants and the mapping from platform specific key codes to the new wx-key constants. The branch name/pull request name is outdated because WM_APPCOMMAND is not handled anymore. If you think these changes are worthy to merge i could rebase the changes to a new branch and close this pull request.

**Comment by vadz** [comment]
I've merged it after squashing the commits, thanks!

**Comment by MaartenBent** [comment]
Small comment from my side. The media keys don't have any special handling, so
```c++

    { VK_BROWSER_BACK,        WXK_BROWSER_BACK },
    { VK_BROWSER_FORWARD,     WXK_BROWSER_FORWARD },
    { VK_BROWSER_REFRESH,     WXK_BROWSER_REFRESH },
    { VK_BROWSER_STOP,        WXK_BROWSER_STOP },
    { VK_BROWSER_SEARCH,      WXK_BROWSER_SEARCH },
    { VK_BROWSER_FAVORITES,   WXK_BROWSER_FAVORITES },
    { VK_BROWSER_HOME,        WXK_BROWSER_HOME },

    { VK_VOLUME_MUTE,         WXK_VOLUME_MUTE },
    { VK_VOLUME_DOWN,         WXK_VOLUME_DOWN },
    { VK_VOLUME_UP,           WXK_VOLUME_UP },
    { VK_MEDIA_NEXT_TRACK,    WXK_MEDIA_NEXT_TRACK },
    { VK_MEDIA_PREV_TRACK,    WXK_MEDIA_PREV_TRACK },
    { VK_MEDIA_STOP,          WXK_MEDIA_STOP },
    { VK_MEDIA_PLAY_PAUSE,    WXK_MEDIA_PLAY_PAUSE },
    { VK_LAUNCH_MAIL,         WXK_LAUNCH_MAIL },
    { VK_LAUNCH_APP1,         WXK_LAUNCH_APP1 },
    { VK_LAUNCH_APP2,         WXK_LAUNCH_APP2 },
```
in `gs_specialKeys` will also work.
Also, the keyboard sample could be updated to show actual key names by updating `GetVirtualKeyCodeName` fuction with
```c++
WXK_(BROWSER_BACK)
WXK_(BROWSER_FORWARD)
WXK_(BROWSER_REFRESH)
...
```

**Comment by vadz** [comment]
Thanks, I agree with your remarks. I also realize that `src/common/accelcmn.cpp` should be updated as well if we want to allow having accelerators for these keys. Any patches/PRs doing this would be welcome, but I'll just fix the typo for now.

**Pull request closed without merging**
