### PR TITLE
Enable automatic tests using wxUIActionSimulator under wxQt

### PR DESCRIPTION
**Pull request by AliKet**

### CODE REVIEW

**Comment by AliKet** [comment]
CC @vadz

**Comment by AliKet** [comment]
@vadz I really want to apply this patch against this PR
```
diff --git a/src/qt/window.cpp b/src/qt/window.cpp
index 4a94d5082c..715681e801 100644
--- a/src/qt/window.cpp
+++ b/src/qt/window.cpp
@@ -978,17 +978,25 @@ void wxWindowQt::SetExtraStyle( long exStyle )
 
 void wxWindowQt::DoClientToScreen( int *x, int *y ) const
 {
-    QPoint screenPosition = GetHandle()->mapToGlobal( QPoint( *x, *y ));
+    // Notice that mapToParent() is same as mapToGlobal() if this widget has no parent.
+    QPoint screenPosition = GetHandle()->mapToParent(QPoint(*x, *y));
     *x = screenPosition.x();
     *y = screenPosition.y();
+
+    if ( GetParent() )
+        GetParent()->ClientToScreen(x, y);
 }
 
 
 void wxWindowQt::DoScreenToClient( int *x, int *y ) const
 {
-    QPoint clientPosition = GetHandle()->mapFromGlobal( QPoint( *x, *y ));
+    // Notice that mapFromParent() is same as mapFromGlobal() if this widget has no parent.
+    QPoint clientPosition = GetHandle()->mapFromParent(QPoint(*x, *y));
     *x = clientPosition.x();
     *y = clientPosition.y();
+
+    if ( GetParent() )
+        GetParent()->ScreenToClient(x, y);
 }
 
 
diff --git a/tests/controls/gridtest.cpp b/tests/controls/gridtest.cpp
index 82cce352dc..f96b2d8928 100644
--- a/tests/controls/gridtest.cpp
+++ b/tests/controls/gridtest.cpp
@@ -640,9 +640,6 @@ TEST_CASE_METHOD(GridTestCase, "Grid::Size", "[grid]")
 
     wxPoint pt = m_grid->ClientToScreen(wxPoint(m_grid->GetRowLabelSize() +
                                                 m_grid->GetColSize(0), 5));
-#ifdef __WXQT__
-    pt += wxPoint(1, 0); // FIXME: why this is needed?
-#endif
 
     sim.MouseMove(pt);
     wxYield();
@@ -663,10 +660,6 @@ TEST_CASE_METHOD(GridTestCase, "Grid::Size", "[grid]")
     pt = m_grid->ClientToScreen(wxPoint(5, m_grid->GetColLabelSize() +
                                         m_grid->GetRowSize(0)));
 
-#ifdef __WXQT__
-    pt += wxPoint(0, 1); // FIXME: why this is needed?
-#endif
-
     sim.MouseDragDrop(pt.x, pt.y, pt.x, pt.y + 50);
 
     WaitFor("mouse drag to be processed", [&]() {
@@ -1520,10 +1513,6 @@ TEST_CASE_METHOD(GridTestCase, "Grid::ResizeScrolledHeader", "[grid]")
                                              m_grid->GetColLabelSize())
                                    - wxPoint(0, 5));
 
-#ifdef __WXQT__
-    point += wxPoint(1, 0); // FIXME: why this is needed?
-#endif
-
     wxUIActionSimulator sim;
 
     wxYield();
@@ -1579,10 +1568,6 @@ TEST_CASE_METHOD(GridTestCase, "Grid::ColumnMinWidth", "[grid]")
                                              m_grid->GetColLabelSize())
                                    - wxPoint(0, 5));
 
-#ifdef __WXQT__
-    point += wxPoint(1, 0); // FIXME: why this is needed?
-#endif
-
     wxUIActionSimulator sim;
 
     // Drag to reach the minimal width.

```

to fix the off-by-one error in ClientToScreen() and ScreenToClient() functions, what do you think ?

**Comment by vadz** [comment]
This looks a bit weird, but if it makes the function(s) behave correctly, why not.

If possible, I'd try to check if calling `map{To,From}Global()` also produces different results from calling `map{To,From}Parent()` twice for a child window in a pure Qt application. If it does, it would be a Qt bug IMO, but if it doesn't, there must be something wrong in wxQt...

**Comment by vadz** [comment]
@AliKet should this be merged as is or do you plan to make more changes here?

**Comment by AliKet** [comment]
> @AliKet should this be merged as is or do you plan to make more changes here?

Sorry, I'm busy doing other things at the moment. but of course this can be merged as is for now. and improve/correct (what should be improved or corrected) later.

TIA!

**Comment by vadz** [comment]
Sorry for the delay, finally merging it now.

**Pull request merged**
