### PR TITLE
wxGetCursor Implementation 

### PR DESCRIPTION
**Pull request by smasherprog**
wxGetCursor Implementation Suggestion

### CODE REVIEW

**Comment by vadz** [comment]
Thanks for the PR, but this will break linking under non-MSW platforms, the function should be at least implemented as returning `wxNullCursor` there, although, unless there is a possibility of getting the current cursor on a platform other than MSW, I'm not sure if it's really useful to have it at all.

Any new function also needs to be documented in `interface/wx/utils.h`.

**Comment by smasherprog** [comment]
I'll add the additional functions for the other platforms. Then, we can go from there.

**Comment by smasherprog** [comment]
Added the additional functions which were required for each platform. 
Removed two function declarations which were already defined in in the gdicmn.h

**Comment by smasherprog** [comment]
Added other implenetations, but I cannot verify if they are correct because I dont have the platforms. I have completed all that I can for this PR. Let me know if you need additional changes.

**Comment by vadz** [comment]
Did you close it because you found some problem with it or for some other reason?

**Pull request closed without merging**
