### PR TITLE
WebKit2 extension loading: cleanup, relocability, security

### PR DESCRIPTION
**Pull request by vslavik**
This is a bit of a a mismatch of loosely related fixes that started by fixing an annoying but inconsequential (for my use) warning (dbe2ce4). That led to realizing this part of the code makes wx non-relocatable, fixing it, simplifying the build and discovering a difference in CMake in the process. Testing *that* led to discovering a bug in `WXPREFIX` handling and fixing a crash there (94d4625) and eventually also realizing that there's a security issue in the convenience code meant for wx developers only (0efefef). 

So it *is* all related, by process if not by subject, just doesn't look like that at first glance (301e5ec9fe3719fac8a2786e8675b19e2242183e and 633165fd13d2fdb0a530affdd5c78873d84d4023 were involved too, but sufficiently independent of the rest to go to `master` separately).

I'm not too happy about 0efefef, but as I say in the commit message, *something* needs to be done. My preference would be to remove this code altogether or have a dedicated environment variable (`WXWEBKITEXTENSIONS` seems most consistent with other env. vars) to point to the location for debugging etc.

### CODE REVIEW

**Comment by vadz** [comment]
Thanks for the fixes, but I'm not happy about 0efefef (congratulations for such a nice commit SHA-1) neither. AFAIK nobody uses max debug mode, so we could just as well remove this completely if we do it like this.

I wonder what exactly is the threat model here. If the attacker has write access to the program directory, surely it's game over anyhow and we don't need to worry about anything. So AFAICS using `lib`, or any other subdirectory, should be perfectly fine. Of course, in our own sample and tests we need to use `..` or `../..` which is different. But we need to handle this somehow -- otherwise the tests just fail, as it happens right now in the Travis CI build.

The simplest solution is, as usual, using an environment variable (again, no security concerns, because if the attacker has access to the process environment, they can do anything they could do by loading a shared library into it directly anyhow), but this is not very convenient for the tests and the sample, which wouldn't run out of the box. Although I guess we could add some logic for finding the extension shared library to them, instead of doing it inside the library? Or maybe we could have some `AddWebExtensionPath()` that they could call to add more elements to the array of directories? This looks like the best solution, doesn't it?

Unfortunately I'm also not sure about suppressing the warning if it can't be found. Without it a lot of important functionality doesn't work and it can be quite non obvious why it doesn't (BTW, I think adding a couple of `wxLogTrace()`s to this code wouldn't hurt). I think that here the best would be to have a way for the application to suppress this warning (of course, it's already possible with `wxLogNull`, but something more selective would be nice), but still give it by default.

**Comment by vslavik** [comment]
> but I'm not happy about 0efefef

I figured you won't be...

> I wonder what exactly is the threat model here. If the attacker has write access to the program directory, surely it's game over anyhow and we don't need to worry about anything. So AFAICS using lib, or any other subdirectory, should be perfectly fine.

It would be, if you only make the distinction root/other user and  *if they were relative to the executable path* ("program directory"). But they are not. They are relative to *the current working directory* at the time of program's launch. For GUI programs under Unix DEs, that's IIRC often `$HOME`. If you have a wx application in `/opt/foo/bin/bar`, this code is looking in `./lib`, i.e. typically `~/lib` but possibly anything else, and *not* in `/opt/foo/bin/lib`. This opens the possibility of the user being manipulated into downloading something and putting it in a bad location (which appears safe: they don't run anything, they don't touch environment variables or dotfiles, they reasonably assume it is safe as long as they don't *run* anything) -- and then this code being unexpectedly executed later when they run something trusted (installed in the system where modification is impossible).

BTW, it is also not quite accurate that it is game over if you get access to `/opt/foo/bin`, difficulty of attack and attack without modifying the targeted binary still both matter (see DLL Hijacking on Windows), but my primary concern is loading executable code from a location not under application's control, without user's explicit instruction.

> Although I guess we could add some logic for finding the extension shared library to them, instead of doing it inside the library? Or maybe we could have some AddWebExtensionPath() that they could call to add more elements to the array of directories? This looks like the best solution, doesn't it?

I think you're overcomplicating it for something that is really *only* relevant to the handful of wx devs. Just setting the environment variable in the affected samples and tests (do you know them off-hand?) would work and not introduce any new API, no?

> Unfortunately I'm also not sure about suppressing the warning if it can't be found. Without it a lot of important functionality doesn't work and it can be quite non obvious why it doesn't

I wouldn't characterize any of the affected stuff (mostly selection handling) as "important", but that's just my optics being different from yours. More importantly, *the user* cannot do anything about it; it isn't a runtime error, it is a bug in compilation/packaging/deployment —  a matter relevant to the developer only, not the user. It shouldn't be shown to the end user, it shouldn't be localized, and it shouldn't show up if the application doesn't need selection handling. 

`wxLogNull` is a blunt instrument, good as a kludge to hide wx bugs, but not as a proper solution, and introducing another dedicated API just to hide what the user doesn't care about to begin with? That's not good and I can see some better ways:

1. Log with `g_warning`, then. The rest of this file already uses it extensively for similar kind of serious failures (e.g. "Failed to start web extension server"), it seems reasonable. The difference is that `g_warning` outputs only to the console (but noticeably so, colors and all), but does not interrupt the user. And if something goes wrong, users are accustomed to checking console output for clues (I was surprised by this, but empirically even non-technical ones do report suspicious console output). This is the least amount of work, which is why I like it very much, but it still spams console output with irrelevant stuff (I don't *need* to ship the extension with Poedit for example, and would still get this output).

2. If this is serious enough problem than a mere verbose logging won't do, then it should *assert* — it is a matter of packaging, i.e. development, after all. Or log as error. But, crucially, report the error only when the application *actually*  tries to use functionality that relies on the extension.

3. Do 2., but still report the failure with `g_warning` as in 1., because that's how native GTK+ applications seem to handle such things.

Having written all that, I agree dbe2ce4 was lazy — any of 1/2/3 above is IMHO better. 3 has the advantage that it won't spam the GUI repeatedly (could be gated to only show once, of course) while still indicating the severity, i.e. # of occurences.

**Comment by vadz** [comment]
> > I wonder what exactly is the threat model here. If the attacker has write access to the program directory, surely it's game over anyhow and we don't need to worry about anything. So AFAICS using lib, or any other subdirectory, should be perfectly fine.
> 
> It would be, if you only make the distinction root/other user and _if they were relative to the executable path_ ("program directory"). But they are not. 

I actually meant to ask about this, because I wasn't sure, so thanks for answering my question in spite of me forgetting to ask it in the first place. However now I have another question: would any security concerns be left if we searched for the library relative to the executable path instead of the current directory?

> > Although I guess we could add some logic for finding the extension shared library to them, instead of doing it inside the library? Or maybe we could have some AddWebExtensionPath() that they could call to add more elements to the array of directories? This looks like the best solution, doesn't it?
> 
> I think you're overcomplicating it for something that is really _only_ relevant to the handful of wx devs. 

I don't think this is true. We really want people to be able to run the sample without doing anything special and I'd definitely like to encourage more people to do `make test` and for this the tests should pass out of the box.

> Just setting the environment variable in the affected samples and tests (do you know them off-hand?) would work and not introduce any new API, no?

Yes, setting environment variable in the `tests/controls/webtest.cpp` and `samples/webview/webview.cpp` should work. Whether it's better than adding `wxWebView::AddWebExtSearchPath()` or not is less clear, but I don't feel strongly enough about it to discuss it if you think it is.
 
> > Unfortunately I'm also not sure about suppressing the warning if it can't be found. Without it a lot of important functionality doesn't work and it can be quite non obvious why it doesn't
> 
> I wouldn't characterize any of the affected stuff (mostly selection handling) as "important", but that's just my optics being different from yours. 

Just to explain where does my point of view come from: I've already lost tons of times trying to understand why something didn't work only to track it down to the extension not being loaded (because I forgot to rebuild it...). And then, of course, a few months later I forgot all about it and exactly the same thing happened again. I really don't want to run into the same problem the third time.

> More importantly, _the user_ cannot do anything about it; it isn't a runtime error, it is a bug in compilation/packaging/deployment — a matter relevant to the developer only, not the user. It shouldn't be shown to the end user, it shouldn't be localized, and it shouldn't show up if the application doesn't need selection handling.

Yes, I agree with all this. Maybe we should show a message from the affected methods instead, so that at least an attempt to do something would show it, instead of failing silently?
 
> `wxLogNull` is a blunt instrument, good as a kludge to hide wx bugs, but not as a proper solution, and introducing another dedicated API just to hide what the user doesn't care about to begin with? That's not good and I can see some better ways:
> 
>     1. Log with `g_warning`, then.

I think this is indeed a good idea.

>     2. If this is serious enough problem than a mere verbose logging won't do, then it should _assert_ — it is a matter of packaging, i.e. development, after all. Or log as error. But, crucially, report the error only when the application _actually_  tries to use functionality that relies on the extension.

Yes, I agree with this too.
 
>     3. Do 2., but still report the failure with `g_warning` as in 1., because that's how native GTK+ applications seem to handle such things.

Yes, again, I think this would be good.
 
> Having written all that, I agree [dbe2ce4](https://github.com/wxWidgets/wxWidgets/commit/dbe2ce44e119f291c539916b80ade48d4cadaa69) was lazy — any of 1/2/3 above is IMHO better.

Yes, absolutely. I can live with either of them and agree that (3) looks best.

I'd still like to see if we can load the extension from `../..` by default using the executable directory as the base, instead of `pwd`, because avoiding the problem in the first place is still better than improving error reporting, but the latter is worth doing nevertheless, of course.

**Comment by vslavik** [comment]
> I don't think this is true. We really want people to be able to run the sample without doing anything special and I'd definitely like to encourage more people to do make test and for this the tests should pass out of the box.

To be clear, I do agree that samples+tests should work out of the box.

I do feel, somewhat strongly, that support code for these two very limited situations, shouldn't be in release builds of the library potentially causing trouble. 

> However now I have another question: would any security concerns be left if we searched for the library relative to the executable path instead of the current directory?

Loading from `../..` still seems dangerous to me - it is still unexpected location with unknown content (e.g. on macOS < 10.15 you could create user-owned folders in `/`). But it's definitely better than being relative to CWD, and I'm OK with doing that.

> Yes, setting environment variable in the tests/controls/webtest.cpp and samples/webview/webview.cpp should work. Whether it's better than adding wxWebView::AddWebExtSearchPath() or not is less clear, but I don't feel strongly enough about it to discuss it if you think it is.

You do have a point. One advantage of an environment variable is that it could be used for packaging as a simpler alternative to preserving installation root and adjusting `WXPREFIX`, but I'm unsure about practical usefulness of that.

Will push updated version tomorrow, thanks!

**Comment by vadz** [comment]
> To be clear, I do agree that samples+tests should work out of the box.

I'm very reassured to hear this, thanks, I was a bit afraid you thought this was something only relevant to a few developers, but as long as we agree about this, we surely can reach an agreement about all the rest.

> I do feel, somewhat strongly, that support code for these two very limited situations, shouldn't be in release builds of the library potentially causing trouble.

But there is no dichotomy between debug and release builds nowadays, for all practical purposes there is just a single build, the one with default configure options, i.e. the one _not_ using `--disable-debug`.

> Will push updated version tomorrow, thanks!

TIA!

**Comment by vslavik** [comment]
> I'm very reassured to hear this, thanks, I was a bit afraid you thought this was something only relevant to a few developers

The API for tweaking this, yes, but I wasn't thinking straight about the people running the code and once you clarified this for me, I fully agree.

I now force-pushed update to both log lazily (with `g_warning`) and use executable-relative lookup.

**Comment by vadz** [comment]
Thanks for the updates!

**Pull request merged**
