### PR TITLE
Change wxHtmlWindow to use system colors

### PR DESCRIPTION
**Pull request by mimi89999**
I know that this might be controversial. I think that most apps aren't setting custom colors. The white background is burning my eyes. I think that it would be better to automatically set colors.
Some users might not like this because they expect that if they don't set colors, background will always be white, text black and links blue.

### CODE REVIEW

**Comment by vadz** [comment]
Sorry, I don't think we can do this, this will almost surely result in unreadable text for some existing code which uses its own custom colours for 1 or 2 out of these 3 colours but not all of them.

Unless someone else enthusiastically supports this change, I'm going to reject it.

**Comment by mimi89999** [comment]
I think you are taking the wrong approach to this. Now users who didn't change any colors will have to apply a workaround to make their apps look good in other themes and set the same colors I set, but manually in CSS.

The same also applies to other UI elements. Window, button, etc. color can also change and if one only sets one text color regardless of the theme or other colors, then it can result in unreadable text. It did for parts of AUI where somebody just put `wxBLACK` and didn't expect backgrounds to change color.

**Comment by vadz** [comment]
The difference is that native controls always behaved like this, i.e. it was never right to change just the fore- or background without changing the other one. For wxHTML this did work since ~20 years and I'm pretty sure there is some code out there doing it, so I'd need to have a very good if not excellent reason to be convinced to silently break it.

**Comment by mimi89999** [comment]
So wxHTML will be deemed to need workarounds for dark themes forever because 20 years ago nobody predicted that dark themes will be a thing now and some users are relying on this? Sometimes APIs could change and I think that's the case. On top of that, AFAIK you never guaranteed those colors will always be the same.

**Comment by vadz** [comment]
I really don't think it's a workaround, nothing says that HTML window, commonly used for displaying documents, should use dark background even in dark mode. I actually wonder, do all PDF viewers/word processors/drawing programs/whatever really use dark background for their canvas (and not just the other UI elements)?

Maybe we should add something like `UseSystemTheme()` to `wxHtmlWindow` but I still don't think it's a good idea to change it by default.

**Comment by mimi89999** [comment]
> I actually wonder, do all PDF viewers/word processors/drawing programs/whatever really use dark background for their canvas (and not just the other UI elements)?

They don't, but Evince has a night mode where they do some color inversion and Firefox has `browser.display.use_system_colors` set to `false` by default.

The difference is that `wxHtmlWindow` is used to display rich text and is not a full feature engine. The doc even says:
> The purpose of this class is to display rich content pages
> If you want complete HTML/CSS support as well as a Javascript engine, consider using wxWebView instead.

The purpose of this doesn't seem to be to display HTML pages or documents. I think that rich text in the UI should still use system colors. I run GTK Hypertext and Markup demos and they are using system colors.

**Comment by vadz** [comment]
It's definitely used for both purposes (and then some). I agree that for some kinds of use, adopting dark mode makes sense. But not all.

**Comment by mimi89999** [comment]
OK, but I think that wxWidgets should make it possible for rich text to look good in other themes without requiring the crazy workaround of setting system colors manually in a CSS.

> Maybe we should add something like `UseSystemTheme()` to `wxHtmlWindow`

I` think that the only place where such setting could be added is the constructor.

**Comment by vadz** [comment]
> > Maybe we should add something like `UseSystemTheme()` to `wxHtmlWindow`
> 
> I` think that the only place where such setting could be added is the constructor.

Why do you say this? Surely it should be possible to set the background colour(s) later?

Anyhow, I don't think we're going to merge this one, sorry. BTW, I understand that you're frustrated by several of your PRs being rejected, but this could probably be avoided if you discussed plans for your changes and explained them _before_ making them. TIA!

**Comment by mimi89999** [comment]
> Why do you say this? Surely it should be possible to set the background colour(s) later?

How would that be handled? It would override custom colors? It would check what colors were set and what weren't?

**Comment by vadz** [comment]
I think you're vastly overthinking this: if you explicitly call `UseSystemTheme()` , it should just set the system colour for the background and the text, overriding any previously set colours and there would be no problem with this if, again, it's *explicitly* requested.

**Pull request closed without merging**
