### PR TITLE
Various fixes regarding OS version checks

### PR DESCRIPTION
**Pull request by TcT2k**
I did some small code and documentation fixes regards OS version checks.
I've also implemented wxGetOsVersion based on NSProcessInfo as recommended by Apple.

Furthermore I've implemented a new function called wxCheckOsVersion() which is just a simple >= check in unix, but uses platform implementations on MSW and OS X.

### CODE REVIEW

**Comment by vadz** [comment]
Thanks a lot for this cleanup and improvements! I'm merging this as I have only minor comments/questions which can be improved later.

Thanks again!

**Comment by vadz** [comment]
Hmm, this seems to have [broken the build](http://buildbot.tt-solutions.com/wx/builders/wxOSX-Cocoa/builds/211/steps/build%20libraries/logs/stdio). Is it just a buildbot issue, i.e. something not rebuilt correctly or a real problem?

Also, it would be nice to use `wxGCC_WARNING_SUPPRESS(deprecated-declarations)`/`wxGCC_WARNING_RESTORE()` around the deprecated Gestalt functions use as we do the right thing now and so the warnings are just noise.

**Comment by TcT2k** [comment]
I did a successful static build with Xcode. I'd assume the duplicate wxGetOsVersion and wxGetOsDescription are from  src/osx/core/utilsexc_base.cpp src/osx/cocoa/utils.mm probably because #if ( !wxUSE_GUI && !wxOSX_USE_IPHONE ) || wxOSX_USE_CARBON
Is still true in the cocoa build. I'll probably have to modify that to work for the dynamic build (but I would be happy for any hint why it might be wrong).

**Comment by vadz** [comment]
I think you just need to test for `!__WXOSX_COCOA__` in `src/osx/core/utilsexc_base.cpp`... Let me try fixing this blindly.

**Comment by vadz** [comment]
Unfortunately this still broke something, see [this thread](http://thread.gmane.org/gmane.comp.lib.wxwidgets.general/83831).

**Pull request merged**
