### PR TITLE
Cygwin build fixes

### PR DESCRIPTION
**Pull request by stahta01**
Cygwin build fixes including #18456.

Tim S.

### CODE REVIEW

**Comment by oneeyeman1** [comment]
@stahta01 ,
Does, this include a fix for [this](https://trac.wxwidgets.org/ticket/10569l)

**Comment by stahta01** [comment]
> @stahta01 ,
> Does, this include a fix for [this](https://trac.wxwidgets.org/ticket/10569)?

No idea, I will test it and see.

Tim S.

**Comment by stahta01** [comment]
Looks like my change broke building of wxMSW 64 bit under Cygwin.

Tim S.

**Comment by stahta01** [comment]
Change PR

**Pull request closed without merging**
