### PR TITLE
Wine fixes

### PR DESCRIPTION
**Pull request by vadz**
Enable more functionality when using Wine, e.g. use native hyper link and command button controls with it too, as it supports them.

Also enable more tests when using Wine.

### CODE REVIEW

**Comment by vadz** [comment]
I have really no idea what's going on with Direct2D tests here and why does `GetObject()` fail to retrieve information about the font. For the reference, the test failures are all similar to this:
```
-------------------------------------------------------------------------------
CoordinatesGCDCDirect2D::DeviceOriginChangedEx
-------------------------------------------------------------------------------
./graphics/coords.cpp:1219
...............................................................................

./graphics/coords.cpp:1219: FAILED:
  {Unknown expression after the reported line}
due to unexpected exception with message:
  Failed to obtain font info for MS Shell Dlg-400-regular-8.25-33 (HFONT
  00000000060a0064): 0 in wxD2DFontData() at ./src/msw/graphicsd2d.cpp:3236
```
and both the font and its handle look fine here and, worse, none of the commits in this PR is supposed to affect them in any way.

Ah, and I can't reproduce this locally, with exactly the same Wine version, neither, of course.

**Comment by a-wi** [comment]
Maybe it has something to do with the fact that "MS Shell Dlg" is a logical font? Perhaps installing corefonts with winetricks would help?

**Comment by vadz** [comment]
> Maybe it has something to do with the fact that "MS Shell Dlg" is a logical font? Perhaps installing corefonts with winetricks would help?

Thanks for the suggestion! Do you know if this can be done from the command line by chance? I'm ready to try just about everything at this stage... But I still have no idea how/why could it change due to any of the commits in this PR. I'm going to try to set up tmate and bisect it in the GHA environment when I have time.

**Comment by a-wi** [comment]
"sh winetricks corefonts" should work.
https://wiki.winehq.org/Winetricks#Using_winetricks

**Comment by vadz** [comment]
Bisecting shows that running `HyperlinkCtrlTestCase` before `CoordinatesGCDCDirect2D::*` tests breaks the latter on the CI machine, and this is related to the commits here because they enable the use of the native control rather than the generic one in wxMSW, so reverting this change and switching back to using the generic control with Wine fixes the tests, but I'd rather not do this because the native control seems to work fine (I've tested it interactively).

Unfortunately I still don't know what else to do about it, using `winetricks corefonts` didn't help.

**Comment by a-wi** [comment]
Is creating `wxHyperlinkCtrl` enough to disturb further tests or is it necessary to execute some tests, Colour, Url, CLick?

**Comment by vadz** [comment]
Just creating it is enough. But I can't reproduce it in a simple example, e.g. this:
```diff
diff --git a/samples/minimal/minimal.cpp b/samples/minimal/minimal.cpp
index 501caf9096..2d275e4f42 100644
--- a/samples/minimal/minimal.cpp
+++ b/samples/minimal/minimal.cpp
@@ -26,6 +26,9 @@
     #include "wx/wx.h"
 #endif

+#include "wx/hyperlink.h"
+#include "wx/msw/private.h"
+
 // ----------------------------------------------------------------------------
 // resources
 // ----------------------------------------------------------------------------
@@ -123,6 +126,20 @@ bool MyApp::OnInit()
     // create the main application window
     MyFrame *frame = new MyFrame("Minimal wxWidgets App");

+    new wxHyperlinkCtrl(frame, wxID_ANY, "wxWidgets", "http://wxwidgets.org");
+    LOGFONTW logfont;
+    if ( !GetObjectW(GetHfontOf(frame->GetFont()), sizeof(logfont), &logfont) )
+    {
+       wxPrintf("ERROR!\n");
+    }
+    else
+    {
+       wxPrintf("Face name: %s\n", logfont.lfFaceName);
+    }
+    frame->Destroy();
+    return false;
+
+
     // and show it (the frames, unlike simple controls, are not shown when
     // created initially)
     frame->Show(true);
```
works.

**Comment by vadz** [comment]
Apparently it's _destroying_ `wxHyperlinkCtrl` and not creating it which breaks things because the following is enough to reproduce the problem too:
```diff
diff --git a/tests/graphics/coords.cpp b/tests/graphics/coords.cpp
index bec0c53101..30b5eed07d 100644
--- a/tests/graphics/coords.cpp
+++ b/tests/graphics/coords.cpp
@@ -17,6 +17,9 @@
 #include "wx/dcgraph.h"
 #include "wx/dcmemory.h"

+#include "wx/app.h"
+#include "wx/hyperlink.h"
+

 // ----------------------------------------------------------------------------
 // test class
@@ -35,6 +38,8 @@ class CoordinatesDCTestCaseBase
 public:
     CoordinatesDCTestCaseBase()
     {
+       auto h = new wxHyperlinkCtrl(wxTheApp->GetTopWindow(), wxID_ANY, "wxWidgets", "http://wxwidgets.org");
+       delete h;
         m_bmp.Create(s_dcSize);
         m_dc = nullptr;
     }
```
i.e. with this patch just running `CoordinatesGCDCDirect2D::DeviceOriginChangedE` on its own fails.

I still can't reproduce the problem in the minimal sample however, which is crazy.

**Comment by a-wi** [comment]
Maybe the reason it cannot be reproduced in the minimal sample is that font obtained from the frame is not MS Shell Dlg?

Another idea to help isolating the issue would be to check what would happen if parent of created `wxHyperlinkCtrl' was not top window of the app but some its child? Maybe parent window is somehow impacted by this control and this change interferes with the test because top level windows is shared?

**Comment by vadz** [comment]
I think there is a real bug in Wine as it shouldn't do this:

https://github.com/wine-mirror/wine/blob/0fe562b4ae3f66f9c0e29ab8f27a4abf2ac78501/dlls/comctl32/syslink.c#L1712

I.e. I don't think this control should take ownership of the font.

**Pull request merged**
