### PR TITLE
Update build/bakefiles/version.blk for 3.0.5

### PR DESCRIPTION
**Pull request by doscott**
I used a C:R:A setting of 4:0:4. If this is wrong, let me now and I will redo all.

bakefile_gen ran without error from the bakefiles folder. I sued the latest version.

autoconf ran without reporting anything from the wxWidgets folder, so perhaps there is a problem there?

If I've really messed up, tell me where and I will start over.

### CODE REVIEW

**Comment by vadz** [comment]
Previously we updated C:R:A to the next value, i.e. 5:0:5, directly after the previous release, but I think it's fine to keep 4:0:4 for now -- perhaps we'll need to update it only to 4:1:4 for 3.0.5, if no new APIs are added, which doesn't seem impossible.

OTOH you do need to rerun `autoconf -B build/autoconf_prepend-include` to fix the CI errors.

**Comment by doscott** [comment]
I reran autoconf, still no output at all but it did generate utils/execmon/execmon.dsw which I have pushed.
Have patience with me, should I do a reset on my repo, and then try again?

**Comment by vadz** [comment]
It's normal that there is no output, but you should now have `0.2.11` in your `configure` instead of `0.2.9` in both bakefile-related variables (run grep to check for it to be sure).

Also, it does generate new files but please do _not_ add them, we don't keep them in the repository intentionally. TIA!

**Comment by doscott** [comment]
This is what I have in configure:

    BAKEFILE_BAKEFILE_M4_VERSION="0.2.9"


BAKEFILE_AUTOCONF_INC_M4_VERSION="0.2.11"

**Comment by vadz** [comment]
Sorry, I forgot that we never updated `build/aclocal/bakefile.m4` in 3.0 branch. We probably ought to do this, let me do it...

**Comment by vadz** [comment]
... Finally, I'm going to do the version changes too, otherwise you're going to get tons of conflicts, so I'm closing this one and will commit my changes soon.

Sorry for the confusion.

**Pull request closed without merging**
