### PR TITLE
Changed the Mac font implementation to use full font names instead of…

### PR DESCRIPTION
**Pull request by warniaha**
… family names; Added all fonts in the enumerator instead of just font families

### CODE REVIEW

**Review by vadz — COMMENTED** [review]
Thanks for the fixes! I don't really have any really important comments, but it would be nice to split this commit into at least 2: one switching to using the full font name and the other one adding ATSU font iteration, as these changes seem unrelated (I say "at least" because perhaps there should be another commit just adding the checks for `xxxref.get()` if it's really independent from the other ones too).

**Comment by warniaha** [comment]
Hi Vadim,

 

ATS != ATSU

 

ATSU uses FMFont which is deprecated

 

ATS is the underlying font API for CTFontRef.  CTFontGetPlatformFont returns an ATSFontRef

 

The enumeration is needed because of the change in the way the fonts are created.  If you leave that enumeration change out, the enumerations will pick up the family but not the full font name for each font.  I believe they are directly related.

 

Walter

**Comment by vadz** [comment]
> ATS != ATSU

Oops, shows how much I know about this. Thanks for the explanation!

Concerning the enumeration: do we still need the existing loop? I.e. shouldn't it be replaced with the new code then?

**Comment by warniaha** [comment]
Hi Vadim,

 

In order to not break existing applications that expect a family name, I think it should keep both.  The way the code currently works, if you specify a family name and supply the weight & style, it should still work the same as before.

 

Walter

**Comment by vadz** [comment]
I don't think existing code relies on `EnumerateFacenames()` returning something specific, this function is mostly supposed to be used to let the user choose a font. So AFAICS it should be safe to replace the existing code with the new version if it's a strict superset of it (this could be easily checked by running the font sample and choosing "Enumerate font families" from its menu).

**Comment by warniaha** [comment]
What about iPhone development?  I don’t run my application on iPhone, so I can’t test it.

 

I’d be ok with replacing it if you feel it should be.

**Comment by vadz** [comment]
I have even less of idea about iOS development than about macOS... What is different about iOS? If in doubt, perhaps we should keep the old code for it, but use the new code (only) on the desktop? OTOH it's true that I don't see any problem with using the new code under iOS too (provided it at least compiles there -- are these functions available on that platform?).

**Comment by warniaha** [comment]
I believe it already has ifdefs to exclude IOS.  I’m not sure, but I think ATS is not available on the iPhone.  Since the iPhone appears to use the full font name instead of the family name, the fix is exclusively for the Mac.

There may be a way to code it for both with the same code, but I’m not aware of how to do it.

**Comment by warniaha** [comment]
I made a dumb mistake on the assertion, it should be ==

**Comment by csomor** [comment]
I'm currently on the road on vacation, but I'll look at it when I get back by Thursday

**Comment by csomor** [comment]
First of all thank you for your work in isolating the problem and diving into the solution.

I've looked at the behaviour of the font sample when running under this modification and I think I'll have to modify and expand a few things from this PR. So perhaps we can separate the issues and compare behaviours first, and decide what is the best behaviour.
The original problem was the fact of the inexact generation of font info when certain NSFont variants were given from the native font selector, no question that this has to be fixed, but the question is how. 

As an example I've tested a Frutiger Neue LT Pro with 6 variants 
Regular, Italic, Heavy, Heavy-Italic, Thin and Thin-Italic

When using the PR the assertion expression as indicated above triggers when selecting Frutiger Neue LT Pro Italic with `Frutiger Neue LT Pro Italic != Helvetica Oblique`, because `CTFontCreateCopyWithSymbolicTraits` tries to apply a symbolic trait italic to an already italic font **Frutiger Neue LT Pro Italic**, which results in ... **Helvetica** - what else ... So I guess I'll have to combine the approaches, I'll have to think about this a little more, perhaps add the style name, store the full name in addition to the family name.

Then there's command to the enumerate font families in the font sample - _families_ but the internal API says to `EnumerateFacenames`:
Without the PR I receive 1 entry in macOS, **Frutiger Neue LT Pro** - the family, in MSW I receive 2 entries **Frutiger Neue LT Pro Regular** and **Frutiger Neue LT Pro Thin**, with the PR in macOS I get 6 entries, one for every variant ... so real font names, on Pango I think font families are used but I couldn't test this. 
I'd prefer to reduce this on macOS to the ones that cannot be created using font name, italic and weight parameters alone. Another Idea to keep strictly the font family name, and to enumerate the variants on a font family name (along `pango_font_family_list_faces`).
BTW regarding ATS: If we decide to enumerate on the full font name, I'll adapt the code to use the newer `CTFontCollectionCreateFromAvailableFonts` because that one is also available on iOS.

**Comment by vadz** [comment]
@csomor Sorry, I'm not sure I follow everything here, but I'd just like to ask: do you think it's worth keeping this one open or should it be closed if it's not going to be applied in its current state anyhow? TIA!

**Comment by csomor** [comment]
Hi @vadz, yes, I'd like to keep it open until solved - not necessarily applied as it is
I keep a sandbox with the changes, and some additions I've written. I'd like to discuss the best approach first:
I think we should stick - both because of backwards compatibility as well as cross-platform portability -  to enumerating only **Font Families**, althought it's called **EnumerateFacenames** (perhaps we could add the name **EnumerateFamilies** as an synonym, getting rid of the other name slowly) and if needed we could enumerate all **Font Faces** of a **Family** in a separate API, otherwise the list gets huge and not really user friendly. That's the reason the font select on macOS has two separate lists, the first for the families, the second one for its faces. 
On the other hand both the native font selector and the font creator on macOS, must be able to deal with full face names in a proper way, roundtrip fidelity, while maintaining backwards compatibility.

**Comment by vadz** [comment]
I think we need to discuss this on wx-dev as I'm rather confused, i.e. I don't even know what do we mean by "font family": this isn't the same thing as `wxFONTFAMILY_XXX` in wx API, is it?

For now let me just tag this as "work needed"...

**Comment by vadz** [comment]
This is clearly not going to make it into 3.1.2. @csomor Is it useful to keep it open at all? I'm not going to apply it on my own anyhow...

**Comment by warniaha** [comment]
Is it still being worked on?  I thought it was reproduced and someone else was working on it.

Please let me know if there is something more expected from me.

 

Walter

**Comment by csomor** [comment]
I've fixed round-trip problems with the new implementation, but I'll go through the other issues next week to summarize what's still on the To-Do list

**Comment by vadz** [comment]
@csomor Is there still anything useful remaining in this PR? I'm trying to do some cleanup and while it's not a problem to leave it opened, of course, I don't think it's useful to keep PRs that we're basically sure are not going to be applied neither. TIA!

**Comment by warniaha** [comment]
Is there something I should do to make this change acceptable?

I require it for my application and need to apply this patch for every upgrade I perform.

Without the changes, wxWidgets loads the wrong fonts on the Mac.

**Comment by csomor** [comment]
I have corresponding changes in a separate sandbox, I'll check and come back

**Comment by csomor** [comment]
Ok, we've changed quite a few things in master when supporting arbitrary widths and fractional point sizes. Creating and storing CTFontDescriptorRefs within native font infos. So internally the round trips from dialogs to rendering should be working fine. What are you doing right now, are you using the toString / fromString methods of wxFontInfo ?

**Comment by csomor** [comment]
I've opened a new PR which works against the new API

https://github.com/wxWidgets/wxWidgets/pull/1416

**Comment by warniaha** [comment]
Hi Stefan,

 

I was bypassing the font creation through wxWidgets, creating it natively and then filling in the font information.  In all cases, the font name was set from the native font.  Attempting to restore a font from the wxFontInfo didn’t work with all fonts on the Mac (but seems to work fine on Windows).

 

From the font selection dialogs, it would create the correct font.  When attempting to recreate the font from the wxFontInfo, it would return the wrong font.  In my case, I need to present the user with the exact font name that is being used, not the information in wxFontInfo.

 

Walter

**Comment by csomor** [comment]
Is using wxNativeFontInfo ToString and FromString not an option for you ?

**Comment by warniaha** [comment]
If it worked with all fonts it would be fine

**Comment by csomor** [comment]
yes, that's what I'm aiming at in https://github.com/wxWidgets/wxWidgets/pull/1416

**Comment by csomor** [comment]
alternative PR committed

**Pull request closed without merging**
