### PR TITLE
Fixed issues found by PVS-Studio

### PR DESCRIPTION
**Pull request by IlyaPVS**
We have found and fixed some bugs using PVS-Studio tool. PVS-Studio is a static code analyzer for C, C++ and C#: https://www.viva64.com/en/pvs-studio/
We suggests having a look at the emails, sent from @pvs-studio.com.
V581 The conditional expressions of the 'if' operators situated alongside each other are identical. Check lines: 2037, 2040. core access.cpp 2040
V721 The VARIANT_BOOL type is utilized incorrectly. The true value (VARIANT_TRUE) is defined as -1. core activex.cpp 271
V595 The 'buffer' pointer was utilized before it was verified against nullptr. Check lines: 9936, 9938. richtext richtextbuffer.cpp 9936
V519 The 'sm_showMinMaxSizeControls' variable is assigned values twice successively. Perhaps this is a mistake. Check lines: 118, 119. richtext richtextsizepage.cpp 119

### CODE REVIEW

**Comment by MaartenBent** [comment]
The first line of each is modified. Did you accidentally change the encoding and add a BOM?

**Comment by IlyaPVS** [comment]
Yes, I have changed encoding accidentally, sorry. Changed it back.

**Comment by vadz** [comment]
Thanks for the fixes! I'm not sure about the bit about the emails, did you send any to us?

In any case, all the changes look good to me and I'm committing them, but after splitting in independent commits, could you please do it like this if you find/submit fixes for any other issues in the future? TIA!

**Comment by leio** [comment]
Someone from PVS was mailing to me for some reason. The first e-mail was generic and claimed my company (no idea which, I don't have any that have stuff on github) has repositories on GH and advertised PVS usage or something, the second one pointed at this PR here. No idea why they thought I'm actively involved. As a PR existed anyways to be noticed, I didn't look into forwarding any e-mails, they seemed borderline spam.

**Pull request closed without merging**
