### PR TITLE
CMake: Fix monolithic build

### PR DESCRIPTION
**Pull request by jbfove**
Monolithic build regressed with commit 815d288c4fedba044a9863c883d6dd9f53526668
"Set wx-config base, gui and built libraries"

The code queries each possible target name and creates lists of the valid targets.
In the monolithic build, none of the normal target names exist, so the list is empty.
The empty list is then passed to STRIP, causing cmake to fail due to not having enough arguments.

By quoting the STRIP params we can pass an empty argument and thus prevent the error of not-enough arguments.

The monolithic target (mono) is also added to the target search list for completeness.

The other option would simply be to remove the block of code here that computes BUILT_WX_LIBS, STD_BASE_LIBS, and STD_GUI_LIBS. I tested this and it appears to work fine. I can't find the uses of these variables at all, other than they mirror similar variables in the autotools stuff. That said, this code modified here was updated recently so I figure it's safer to update it rather than remove it.

### CODE REVIEW

**Comment by vadz** [comment]
Thanks for the fix!

@MaartenBent Please let me know if you have any objections, this seems reasonable to me but I don't really know what's going on here, e.g. why do we have `BUILT_WX_LIBS` etc if they're really not used.

**Comment by MaartenBent** [comment]
Those variables are used in `wx-config.in` to generate `wx-config`.

Adding quotes to fix the bug is fine, but adding `mono` to the list is incorrect. If I use configure to create a monolithic library, `wx-config` returns
```
  Available libraries in this build are:
  xrc webview stc richtext ribbon propgrid aui gl html qa adv core xml net base
```
It does not contain `mono`.  Unfortunately the CMake build returns an empty list because all the targets do not exist. This has to be fixed in another way.

**Comment by vadz** [comment]
Oops, so much for looking reasonable. I'm going to close this one then, thanks.

**Comment by MaartenBent** [comment]
If you could still cherry-pick the added quotes, it would be great. Otherwise the monolithic is unusable.

**Comment by vadz** [comment]
Thanks again to both of you, I've applied the good part of the initial PR now.

**Pull request closed without merging**
