### PR TITLE
Layout controls to make the wxInfoBar behave the same across platforms

### PR DESCRIPTION
**Pull request by oneeyeman1**
This one line patch makes GTK (native) and generic wxInfoBar behaves the same. Following patch was used for testing:

```
diff --git a/samples/dialogs/dialogs.cpp b/samples/dialogs/dialogs.cpp
index 6b9ef63ec8..5b177f9928 100644
--- a/samples/dialogs/dialogs.cpp
+++ b/samples/dialogs/dialogs.cpp
@@ -672,10 +672,6 @@ MyFrame::MyFrame(const wxString& title)
     // or it can also be customized by
     m_infoBarAdvanced = new wxInfoBar(this);
 
-    // ... adding extra buttons (but more than two will usually be too many)
-    m_infoBarAdvanced->AddButton(wxID_UNDO);
-    m_infoBarAdvanced->AddButton(wxID_REDO);
-
     m_infoBarAdvanced->Bind(wxEVT_BUTTON, &MyFrame::OnInfoBarRedo, this,
                             wxID_REDO);
 
@@ -888,6 +884,7 @@ void MyFrame::InfoBarSimple(wxCommandEvent& WXUNUSED(event))
                      (
                       wxString::Format("Message #%d in the info bar.", ++s_count)
                      );
+    m_infoBarSimple->AddButton( wxID_OK, "OK" );
 }
 
 void MyFrame::InfoBarAdvanced(wxCommandEvent& WXUNUSED(event))

```

As explained in ticket #14120 GTK (native version) supports it.

### CODE REVIEW

**Comment by vadz** [comment]
We already call `Layout()` in `ShowMessage()`, so why not just do it unconditionally there?

**Comment by oneeyeman1** [comment]
@vadz 
> 
> We already call `Layout()` in `ShowMessage()`, so why not just do it unconditionally there?

Because the idea of the change is to be able to add button whether control (message) is already shown or not.

Just look at the patch I used for testing.

**Comment by vadz** [comment]
OK, then it needs to be done only if it's shown. It's just inconsistent to do it both here, unconditionally, and in `ShowMessage()` conditionally.

**Comment by oneeyeman1** [comment]
@vadz 
> 
> OK, then it needs to be done only if it's shown. It's just inconsistent to do it both here, unconditionally, and in `ShowMessage()` conditionally.

Done now.
Lets wait for the builds to finish and apply.

**Comment by vadz** [comment]
Merging, thanks!

**Pull request closed without merging**
