### PR TITLE
Make wxNewId() and others return/take wxWindowID rather than int

### PR DESCRIPTION
**Pull request by lanurmi**
wxWindowID is a typedef of int, so nothing should really change.

(This looks simple and harmless, but are there some implications I cannot think of?)

### CODE REVIEW

**Comment by vadz** [comment]
Thanks and sorry for the delay with applying it.

**Comment by ardovm** [comment]
Hello,

apparently this change breaks Audacity's build. One of its files (`src/MemoryX.h`) includes `wx/utils.h` from this project. It fails to compile, because the first included file by `wx/utils.h` is `wx/windowid.h` following your edit. In order to work, it needs `wx/types.h` to be included previously, but this does not happen.

Compilation error from Audacity:

```
In file included from /home/arrigo/wxtest-nostl/include/wx-3.1/wx/utils.h:18:0, 
                 from ../../src/MemoryX.h:388,                                  
                 from ../../src/SampleFormat.h:16,                              
                 from ../../src/BlockFile.h:15,                                 
                 from ../../src/BlockFile.cpp:43:                               
/home/arrigo/wxtest-nostl/include/wx-3.1/wx/windowid.h:28:24: error: variable ‘WXDLLIMPEXP_CORE wxWindowIDRef’ has initializer but incomplete type
 class WXDLLIMPEXP_CORE wxWindowIDRef
                        ^~~~~~~~~~~~~
/home/arrigo/wxtest-nostl/include/wx-3.1/wx/windowid.h:30:1: error: expected primary-expression before ‘public’
 public:
[...]
```
In practice, the keyword `WXDLLIMPEXP_CORE` is not recognized.

Is this a problem for wxWidgets or for Audacity?

**Comment by ardovm** [comment]
Sorry, the missing header seems not to be exactly `wx/types.h` but I hope you get the point nevertheless.

**Comment by lanurmi** [comment]
Looks like it is a wxWidgets problem.

It can be fixed by adding `#include "wx/defs.h"` right before `#include "wx/windowid.h"` in `wx/utils.h`. The fundamental issue is that `wx/windowid.h` cannot be included on its own, `wx/defs.h` must always come first. But this is often not apparent, which is went unnoticed in this PR.

**Comment by ardovm** [comment]
Thank you @lanurmi ! I am proposing your fix in the above PR.

**Pull request closed without merging**
