### PR TITLE
Update mailmap

### PR DESCRIPTION
**Pull request by a-wi**
@Anil8753 , @catalinr , @HasheeLeo , @oneeyeman1 , @joseeloren , @jensgoe , @lanurmi , @orbitcowboy , @lioncash , @pavelxdd , @pavel-t , @prashantkn94 , @iwbnwif, @kosenko , @Kijewski , @rmpowell77  - please check your records.

### CODE REVIEW

**Comment by catalinr** [comment]
What exactly is this file for? What is the expected format?
I see I have there the address used to get github notifications, which I guess is fine, but also another one `@users.noreply.github.com` which I don't remember anything about. Maybe it was automatically created by github, but I don't know if it's valid or not.

**Comment by vadz** [comment]
> What exactly is this file for? What is the expected format?

See the "mapping authors" section of [git shortlog docs](https://git-scm.com/docs/git-shortlog) for all the details but, in brief, it's for using the correct (and same) author name for all commits done by the same person in `git log`, `git shortlog` etc output.

> I see I have there the address used to get github notifications, which I guess is fine, but also another one `@users.noreply.github.com` which I don't remember anything about. Maybe it was automatically created by github, but I don't know if it's valid or not.

It doesn't have to be valid, it just has to be present, as a committer address, in our Git history. FWIW I use invalid addresses of the form `trac-user-name@trac.wxwidgets.org` for people submitting patches via Trac without specifying their real email addresses all the time.

**Comment by Kijewski** [comment]
My entry looks good. :+1:

**Comment by vadz** [comment]
@a-wi I think this should be committed, should I do it or will you?

**Comment by rmpowell77** [comment]
👍

**Pull request merged**
