### PR TITLE
3.2.5 proposed backports

### PR DESCRIPTION
**Pull request by vadz**

### CODE REVIEW

**Comment by imciner2** [comment]
Based on the last comment in https://github.com/wxWidgets/wxWidgets/issues/24151, I am guessing something in master still needs to be backported to 3.2 to fix the macOS scrollbars. Any idea which commit that should be?

**Comment by vadz** [comment]
> Based on the last comment in #24151, I am guessing something in master still needs to be backported to 3.2 to fix the macOS scrollbars. Any idea which commit that should be?

Sorry, no idea: both obvious candidates (991a74caad48078ba7d420eca8b0d126b3532b1a and bcbc31e97f246564e4b19ea2d060ae859c302b44) have been already cherry-picked.

**Comment by swt2c** [comment]
@vadz, can you please add https://github.com/wxWidgets/wxWidgets/commit/00dff6e3bce72cc444c0602e13cf346a3340746b to the backport queue as well?

**Comment by asmwarrior** [comment]
Hi, can you backport this feature: [Use wxOverlay to show sash feedback in wxAUI and in wxSplitterWindow by AliKet · Pull Request #24193 · wxWidgets/wxWidgets](https://github.com/wxWidgets/wxWidgets/pull/24193)?

Thanks.

**Comment by MaartenBent** [comment]
You considered #24196 (and c72f4efc9c024419bba37aa31983489481302b6c) for backporting too.

**Comment by mcorino** [comment]
@vadz Would you consider backporting "Fix wxSecretStore for linux" #24352 too? I do not think it pulls in any ABI changes does it?

**Pull request merged**
