### PR TITLE
Show more than 13 wxComboBox popup items (Cocoa):

### PR DESCRIPTION
**Pull request by Dan-Korn**
Add style flag wxCB_SHOWALLITEMS, for Mac only.
In wxWidgetImpl::CreateComboBox(), if this flag is set, call
[v setNumberOfVisibleItems:99] to override the previous call
[v setNumberOfVisibleItems:13].

The problem this fixes is that, on later versions of macOS, by
default, scroll bars are not shown in the pop-up of an NSComboBox,
so if there actually are more than 13 items in the list, it’s not
at all obvious to the user that they can scroll to see more.

### CODE REVIEW

**Comment by vadz** [comment]
Sorry, I have no idea about how does it work, but are there any drawbacks of calling `setNumberOfVisibleItems:99`? Or `setNumberOfVisibleItems:9999` for that matter? If not, let's just always do it. If there are, i.e. if the combobox will really show blank items in this case, I think we need to call it dynamically, i.e. when the number of the items in the combobox changes.

But I'd really prefer to avoid adding a new flag for something that you'd expect to work out of the box. Showing all the items when we previously didn't show them wouldn't be a compatibility breakage, but just a bug fix, so if you're worried about this, please don't be.

I.e. I'm pretty much opposed to merging this, unless, for some unbeknown to me reason, there is really no other possibility to fix this.

**Comment by Dan-Korn** [comment]
> Sorry, I have no idea about how does it work, but are there any drawbacks of calling `setNumberOfVisibleItems:99`? Or `setNumberOfVisibleItems:9999` for that matter?

I don't think there are any drawbacks.  It doesn't show more items than are actually there, no matter what that number is set to.

As for the number itself, I suppose 9999 is as good as any other number.  Maybe we should just set it to NSIntegerMax.  (Not sure why Apple doesn't just have a simple way to "show all".)

> If not, let's just always do it.

I was trying to maintain backward compatibility.  But I'm fine with always showing all items.

> If there are, i.e. if the combobox will really show blank items in this case, I think we need to call it dynamically, i.e. when the number of the items in the combobox changes.

No, it doesn't show blank items.  Well, technically, it will show truly blank items, which exist with empty strings, but it won't show items that aren't there at all.

> But I'd really prefer to avoid adding a new flag for something that you'd expect to work out of the box. Showing all the items when we previously didn't show them wouldn't be a compatibility breakage, but just a bug fix, so if you're worried about this, please don't be.

Fine with me.  Should I rework it to always show all items?

> I.e. I'm pretty much opposed to merging this, unless, for some unbeknown to me reason, there is really no other possibility to fix this.

Are you opposed only because of the new flag?  If simply changing that 13 to 99 or 9999 or NSIntegerMax is acceptable, that's fine with me.

But I maintain that a fix is needed.  I'm not sure why Stefan chose 13 as the number, but that was 6 years ago, and the way things work in macOS has changed a lot since then.

**Comment by vadz** [comment]
> > Sorry, I have no idea about how does it work, but are there any drawbacks of calling `setNumberOfVisibleItems:99`? Or `setNumberOfVisibleItems:9999` for that matter?
> 
> I don't think there are any drawbacks. It doesn't show more items than are actually there, no matter what that number is set to.
> 
> As for the number itself, I suppose 9999 is as good as any other number. Maybe we should just set it to NSIntegerMax. (Not sure why Apple doesn't just have a simple way to "show all".)

Sure, let's use `NSIntegerMax` if it works, this is better than any hardcoded manifest constant.

> > If not, let's just always do it.
> 
> I was trying to maintain backward compatibility.

I don't think cutting off the items that don't fit could reasonably be considered as a feature to be preserved, rather than a bug to be fixed.

> Fine with me. Should I rework it to always show all items?

Yes, please, I can't easily check if using `NSIntegerMax` works right now. Please just force-push your branch after updating the code.

> > I.e. I'm pretty much opposed to merging this, unless, for some unbeknown to me reason, there is really no other possibility to fix this.
> 
> Are you opposed only because of the new flag? If simply changing that 13 to 99 or 9999 or NSIntegerMax is acceptable, that's fine with me.
> 
> But I maintain that a fix is needed. I'm not sure why Stefan chose 13 as the number, but that was 6 years ago, and the way things work in macOS has changed a lot since then.

Of course a fix is needed, I'm only opposed to requiring a flag to enable the obviously correct behaviour.

I have a very simple method for deciding whether an API is good or not: imagine yourself defending the API from some irate user complaining about the library being hot garbage. In this particular case, if someone decided to lambaste wx because it cuts off combobox items by default and requires using some obscure flag (not needed under the other platforms) to show them, I wouldn't be personally able to defend this API at all. Hence for me it's a bad idea.

But fixing the bug is good, of course, nobody argues about this.

**Comment by vadz** [comment]
Thanks for the update, this looks good to me, except that I'd remove the commented out line before committing. I'll wait for a couple of days to see if @csomor has any comments and merge it if he doesn't.

BTW, just out of curiosity, what happens if we omit this call entirely? Would combobox still be truncated? Maybe all we need to do to avoid truncating the list of items is to not do anything at all?

**Comment by csomor** [comment]
We're caught between a rock and a hard place here. macOS keeps sacrificing its own HIG standards that have been valid for decades in the name of 'design', form now cripples function. The best UI IMHO would be to have the scrollbar and not spread options all over the screen. But since there's apparently no way to enforce the scrollbars I'd vote for the showing everything

**Comment by Dan-Korn** [comment]
> BTW, just out of curiosity, what happens if we omit this call entirely? Would combobox still be truncated? Maybe all we need to do to avoid truncating the list of items is to not do anything at all?

If you don't set the number of visible items, it defaults to five.

**Comment by vadz** [comment]
> If you don't set the number of visible items, it defaults to five.

This doesn't sound like a useful behaviour at all... I wonder what do all the native Mac/Cocoa programmers do?

Anyhow, I'm still fine with applying this as is, but then I know I'm insufficiently impressed by macOS HIG standards. Perhaps we could do this only under 10.14, assuming scrollbar still worked under the older systems? @csomor what do you think?

**Comment by Dan-Korn** [comment]
> This doesn't sound like a useful behaviour at all... I wonder what do all the native Mac/Cocoa programmers do?

Not to be flippant, but presumably they call setNumberOfVisibleItems, or just set the property in the nib file, if they want something other than the default.

But I don't think most Cocoa programmers use combo boxes in the first place.  A bit of historical context might help here: AFAIK, the idea of a "combo box" was not really a thing on Mac before HIView, and there wasn't really an equivalent pre-Carbon.  (You used to have to "roll your own" with a combination of a pop-up menu and an edit box.)  The combo box that we know was added (I suspect somewhat reluctantly) by Apple as a native control because of its ubiquity not just on Windows, but on the web.  So most people porting older Mac apps to Cocoa wouldn't really have this kind of control, and I think it's still not a very commonly-used control in native Mac apps.

> Anyhow, I'm still fine with applying this as is, but then I know I'm insufficiently impressed by macOS HIG standards.

They are full of contradictions.  But I kind of think of the HIG as just that, guidelines, kind of like the Pirate Code.  They're not really rules that can't ever be broken.  And yeah, Apple's efforts to "iOS-ify" Mac have muddied the waters quite a bit.

> Perhaps we could do this only under 10.14, assuming scrollbar still worked under the older systems? @csomor what do you think?

I'm pretty sure that "Show scroll bars" System Preferences setting has been there for a while, all the way back to 10.7.  It's hasn't been an issue for us until now because we haven't used wxComboBox like this (in editable mode) until just recently, when we ported our app from Carbon to wx/Cocoa.

**Comment by csomor** [comment]
Yes, you are right, a combobox had to be programmed by hand on MacOS versions (you can follow it's implementation in wx since 7.5.3 Rev 2 ;-), but OpenStep always had one. The idea that this behaviour is violating is actually not a even a guideline, but a principle 'discoverability'. Bruce Tognazzi and Don Norman have been very thoughtful on these issues way back when. But now appearance is more important, thus scrollbars indicating that there's more ... are banned by default.

**Comment by csomor** [comment]
I'll check on older macOS versions.

**Comment by csomor** [comment]
ok, on 10.8 up to 10.12, the scrollbar is always shown if there are more items than visible, on 10.13 the default setting does not show scrollbars anymore, but if the system settings are on 'always visible' then they are for a combobox as well, on 10.14 (.6) the scrollbar is never shown, on 10.15 (B6) they've fixed things again

**Comment by csomor** [comment]
So I'd suggest only using this workaround when running under 10.13 and 10.14 ...

**Comment by Dan-Korn** [comment]
> on 10.15 (B6) they've fixed things again

I'm not seeing this on my 10.15.6 Mac.  With the "Show scroll bars" setting set to "Automatically based on mouse or trackpad" or "When scrolling," I don't see any scroll bars in the pop-up for the combo box.  At least, I don't see them until I start scrolling, which is the point.

**Comment by csomor** [comment]
that's definitely the point, we want it to be discoverable, are you running this on a laptop with a trackpad or a desktop with a mouse ?

**Comment by Dan-Korn** [comment]
I'm on a MacBook Pro with a trackpad, but the behavior is the same when I have a mouse plugged in.

**Comment by csomor** [comment]
Ok, I've tested again, I've to correct: it's beta 7, build number 546d on a mac mini (2018)

Starting with prefs on 'automatically', both opening by clicking on the arrow and by typing the arrow down key, open with scrollbars visible, both in builds against 10.12 SDK and 10.15 SDK

Starting with prefs on 'when scrolling', both actions show no visible scrollbar unless when scrolling 
(actually I'm fine with this behavior because it's consistent throughout the system and it's not the default, so people are asking for this kind of behaviour by explicitly selecting it)

I'll have to look for a spare external disk to get Catalina running on my MBP ...

**Comment by csomor** [comment]
Bingo, I can see the problem on my MBP running 10.15 546d ... I'll try to find out whether there's something that would indicate which behavior is happening on a machine ... as I'd really prefer the scrollbar version instead of a huge drop down list ... in order to apply it only when necessary

**Comment by vadz** [comment]
I didn't want to apply this for 3.1.1 without Stefan's say so, but we really ought to fix it one way or the other.

**Comment by csomor** [comment]
yes, thanks for the ping, I'll test with the current catalina version and do a search wether there is some kind of docs that says when the scrollbar is visible or not ...

**Comment by csomor** [comment]
one possible idea would be to track at the right moment the NSComboBoxWindow that contains the list to be displayed and force the NSScroller visible. But at the moment of the willPopUp notification it has not been created yet.

**Comment by csomor** [comment]
adapted fix committed in 014f04b4

**Comment by csomor** [comment]
Thanks a lot @Dan-Korn

**Pull request closed without merging**
