### PR TITLE
CMake: Use info.plist with NSPrincipalClass set to wxNSApplcation

### PR DESCRIPTION
**Pull request by TcT2k**
This setting is important for some functionality provided by
wxNSApplcation and most importantly without the setting all samples
where only shown scaled on high dpi displays.

### CODE REVIEW

**Comment by vadz** [comment]
We really need to document this somewhere. Is there any way to check for missing `NSPrincipalClass` key at run-time? If so, I think we should do it and show at least a debug warning if it's not set.

**Comment by TcT2k** [comment]
It's probably possible to check it during runtime with some flag set by wxNSApplication and checked by wxApp (or a lookup in the plist file). But I'm not sure about the implications. In my own applications it was never an issue as I set another key in the info plist to indicate that it supports hipdpi. I just realized the difference in the samples between cmake and autoconf builds and was looking for a reason.

**Comment by TcT2k** [comment]
I've just debugged this, and startup seems to be identical (everything starts with `main()`) whether or not the entry is there. OSX just seems to assume `NSHighResolutionCapable` when `NSPrincipalClass` is set.

**Comment by vadz** [comment]
Yet there is no mention of this in [the documentation](https://developer.apple.com/library/content/documentation/General/Reference/InfoPlistKeyReference/Articles/CocoaKeys.html#//apple_ref/doc/uid/TP40009251-SW11)... Can we check for `NSHighResolutionCapable` directly by chance?

Anyhow, I'm fine with applying this patch, but it seems that there is now a mismatch for all the samples except the minimal one between CMake and autoconf builds as they use the plist file in the former, but not the latter. This doesn't seem ideal neither.

**Comment by TcT2k** [comment]
I don't think there is a mismatch. All samples use `samples/Info.plist`. I
think the `samples/minimal/Info_*.plist` are just used by the xcodeproject
files for minimal.

2018-02-23 16:23 GMT+01:00 VZ <notifications@github.com>:

**Comment by vadz** [comment]
But `samples/Info.plist` doesn't define `NSPrincipalClass`... In fact, I'm totally lost here, it looks like the samples actually use `src/osx/carbon/Info.plist.in` and `samples/Info.plist` is not used at all?

**Comment by TcT2k** [comment]
You are probably right, I just checked in the resulting .app bundles of samples from a autoconf build. You created the `samples/Info.plist` in 4af1a3931e8916fea076caed900060a3c8e1b983 and @csomor added `NSPrincipalClass` to `src/osx/carbon/Info.plist.in` in 475f991da54f0cdc4449fdfab0618e5ae26fced9 with explicitly mentioning High Resolution support.

**Comment by LegalizeAdulthood** [comment]
CMake bits look good to me.  I'm no macOS expert however :)

**Comment by vadz** [comment]
I've finally merged this, sorry for the delay.

I also removed the apparently unused `samples/Info.plist`. It would still be nice to use the new `samplse/Info.plist.in` in autoconf builds too...

**Pull request closed without merging**
