### PR TITLE
Using native checkbox for dataview on macOS

### PR DESCRIPTION
**Pull request by csomor**
But no image support (yet)..

see [trac](https://trac.wxwidgets.org/ticket/17473)

Thanks for testing ...

### CODE REVIEW

**Comment by dkulp** [comment]
I updated my code to handle the different order so don't worry about that.  Really should have been using GetOldCheckedState in my code all along instead of assuming anything.

**Comment by vadz** [comment]
FWIW I don't think we should guarantee the same order under all platforms: if the native UI does it like this under Mac, ours should follow it.

OTOH getting `CHECKLISTBOX_TOGGLED` is indeed problematic...

Thanks for testing!

**Comment by vadz** [comment]
What is going to happen to this PR? Should it be rebased on master and applied?

**Comment by csomor** [comment]
the problem is that it doesn't support images yet, so I'll have to write custom code, and fix the event, so we'll have to leave it for the moment

**Comment by vadz** [comment]
So I've applied this PR to the latest master, after merging the conflict due to "adv" disappearance in the meanwhile, and I do see that it improves the checkbox appearance and allows to actually toggle it, so IMO it's already better than the current implementation.

I do agree that toggling the checkbox when clicking on the text feels wrong, but, again, it's still better than not being able to toggle it at all. The really problematic part is that I don't see how can this be fixed, even in the future, because it seems that if we implement checkboxes support using `NSSwitchButton`, as this PR does, there is just no way around it (BTW, the other limitation, i.e. not supporting images, is much less important, but I also don't see how could it be lifted while continuing to use the button cell, which doesn't support having more than one image).

IMO ideal would be if we could fix the bug with [ActivateCell() not working at all](http://trac.wxwidgets.org/ticket/17746) for custom renderers under Mac and update `[wxImageTextCell drawWithFrame:inView:]` to respect dark mode, so that the common implementation would work under Mac too. But as I have no idea about how to do this, I'd apply this patch to at least make `wxTreeListCtrl` usable.

Stefan, what do you think?

**Pull request closed without merging**
