### PR TITLE
Relax wxPaintDC assertion which fails on macOS 10.14

### PR DESCRIPTION
**Pull request by ojwb**
Implement the fix I suggested in #846, and which @vadz was OK with.

### CODE REVIEW

**Comment by vadz** [comment]
Thanks! If @csomor doesn't have any objections, let's apply this.

**Comment by vadz** [comment]
We also need to add `#include "wx/glcanvas.h"` to fix the CI failure.

**Comment by ojwb** [comment]
> We also need to add `#include "wx/glcanvas.h"` to fix the CI failure.

Sorry about that (I don't have a Mac to test on).

I amended the commit and force-pushed it, as that seemed better overall for a one line addition to two line patch.  Hope that was a sensible choice.

https://github.com/wxWidgets/wxWidgets/compare/a02d60ff7967ca59f05c8dd1819f31eb2a74f5d8..80cf506bda704ff09e29a9c3763207b886045295 shows the additional change (it looks like `glcanvas.h` isn't included by the pre-compiled headers).

**Comment by csomor** [comment]
don't we have a link dependency inversion here because of the rtti info of wxGlCanvas ? using native rtti ? I'd also be fine with removing this assert in 3.0, if there's no other options ..

**Comment by ojwb** [comment]
And the CI failure agrees with you...

In terms of native RTTI, `dynamic_cast<wxGLCanvas*>(window)` and `std:is_convertible<decltype(window), wxGLCanvas*>::value` seem the obvious options (the second requiring C++11).  Both need `wxGLCanvas` to be a complete type, but I'm not at all clear what that actually means in terms of run-time dependencies on symbols from the wxgl library.  It seems quite likely both would need RTTI which will be in that library.

I could test on Linux, but things might be different on macOS.

Just removing the assertion does seem the simpler option.

@vadz Thoughts?

**Comment by csomor** [comment]
You are absolutely right. How about using a `wxClassInfo::FindClass("wxGlCanvas")` and if this returns not `NULL`, we can ask the window wether it `IsKindOf( returned classinfo ) ` =

**Comment by vadz** [comment]
Unfortunately we still support C++98 builds in 3.0 (actually we support them in 3.1 too, but considering the supported macOS versions there, we could use C++11 features in Mac-specific code there -- but not 3.0). And I'm not really sure how does standard RTTI work with types from other shared libraries in any case.

I _think_ that Stefan's idea, i.e. doing
```cpp
static const wxClassInfo* const ciGLCanvas = wxClassInfo::FindClass("wxGLCanvas");
wxASSERT( ... (ciGLCanvas && win->IsKindOf(ciGLCanvas)) ... );
```
should work fine, but I'd feel better if somebody could test it.

**Comment by ojwb** [comment]
I've pushed a new version using that approach (except I split it out into a helper function since that seemed clearer and cleaner).

The CI will test it to some extent at least.

**Comment by vadz** [comment]
Thanks, I'm merging this with just a minor fix to the commit message to fix a recurring typo: I'm pretty sure it should be "10.14" and not "10.4".

**Comment by ojwb** [comment]
It should indeed say 10.14.  Thanks for catching that.

**Comment by vadz** [comment]
Not sure why it didn't get closed automatically even though it did notice the commit in which it was applied but, anyhow, it is in 3.0 branch now, thanks again.

**Comment by ojwb** [comment]
I think github doesn't understand "Closes" followed by a URL, which is a bit of a silly limitation.

You'd have to say `Closes #1414` (which is ambiguous in the wx content where trac is also used) or `Closes wxWidgets/wxWidgets#1414` (trac still picks up the `#1414` part there, and it's nearly as verbose as the full URL but won't get turned into a clickable link by most things).

**Comment by vadz** [comment]
No, I use full URLs all the time (we can't use just the PR number because, as you noted, this is also understood by Trac and results in bogus notifications), including several times today and they work just fine. Perhaps GitHub only considers commits to master as really closing the issues/PRs now?

**Pull request closed without merging**
