### PR TITLE
Change AUI to draw transparent top and left borders

### PR DESCRIPTION
**Pull request by mimi89999**

### CODE REVIEW

**Comment by vadz** [comment]
Sorry, but I just still don't understand why is this a good idea... What is your objection to the proposal in [my comment](https://github.com/wxWidgets/wxWidgets/pull/1790#issuecomment-612634006)?

**Comment by mimi89999** [comment]
Well, I think that even old apps could benefit from this change. Currently in light themes top and left borders are almost not visible or not visible at all and in dark themes the white top left border looks strange.

**Comment by vadz** [comment]
Replacing hardcoded white with some appropriate system colour would be fine, of course. But just removing it still seems strange to me, as this just changes the appearance and while you clearly prefer it like this, it's perfectly possible that other don't...

Any AUI users here, what do you think of this change?

**Comment by mimi89999** [comment]
What color should it be then on dark themes? Light? That wouldn't make much sense. Dark? That would remove the 3D-ish effect as you called it or shadow as I call it.

**Comment by vadz** [comment]
Sorry but with transparent pen it just doesn't look right, there is a visible "hole" filled with darker grey, see this zoomed in picture: auibar

I'm not sure what would look good, but certainly we could find something for the dark theme without breaking appearance in the light theme. In the meanwhile I'm afraid we can't apply this one as is, sorry.

**Pull request closed without merging**
