### PR TITLE
macOS wxRichTextXXX fixes

### PR DESCRIPTION
**Pull request by csomor**
Bug Reports

https://trac.wxwidgets.org/ticket/18797

### CODE REVIEW

**Comment by vadz** [comment]
Sorry but I'm almost sure that this is not 100% correct (putting aside wrong `#if`, instead of `#ifdef`, check, which broke the CI builds): if we need to do this for Mac, we almost certainly need to do it for GTK 3 too which uses the same pixel/scaling model. And if this is true then we should use `#ifdef wxHAVE_DPI_INDEPENDENT_PIXELS` instead.

Of course, it would be even better to avoid preprocessor checks entirely and use some higher level function (i.e. maybe we need something similar to the recently added `wxGLCanvas::GetOpenGLScaleFactor()` for non-OpenGL windows too?), but I don't know anything about this code and have no idea what is it trying to do, so I'm less sure about this...

**Comment by csomor** [comment]
I cannot test the sample given in the bug report with a wxGTK3 high resolution, but I'm all for encapsulating this behavior at least in such a macro, but it's definitely a repeat of the old point vs pixel problem, on mac we are - unless on OpenGL - on points ...

**Comment by vadz** [comment]
Testing GTK in high DPI is simple: just do `$ GDK_SCALE=2 ./sample-or-whatever-to-run`.

The problem is that I don't understand why does wxRTC code need to deal with logical/physical pixel difference, this is supposed to be abstracted by the API... but I don't have time to learn this right now neither :-(

**Comment by csomor** [comment]
there are measurements in richtextctrl given in tenths of a mm like the left indent of a paragraph, these are then translated into pixels, to calculate where to start drawing the text, which on mac is wrong because dc drawing is based on points not on pixels, so on my retina laptop, the sample of the bug report had the text started at 51.2 mm instead of 25.6 mm

Perhaps the macro might use the word `POINT` ? or is this too precise or introducing more questions than answers ? it's the graphic system ... `wxGRAPHICS_POSITIONING_DPI_INDEPENDENT` .... ?

**Comment by vadz** [comment]
I'd really like to avoid adding even more macros, I think `wxHAVE_DPI_INDEPENDENT_PIXELS` should be enough. But we definitely should also have some clear way of converting physical measurements to pixels and/or points in the API and I'm surprised we don't have anything yet.

Also, just to be sure, what you call "points" is what I call logical pixels, right? I.e. a "point" consists of 4 (physical) pixels when using high DPI Mac?

**Comment by csomor** [comment]
I wasn't advocating for more macros ;-) just thinking about names

we already can convert mm to true pixels, but the drawing API's "points in user space do not have any relation to measurements in the physical world." 

I'm using the term in the mac sense:

https://developer.apple.com/library/archive/documentation/GraphicsAnimation/Conceptual/HighResolutionOSX/Explained/Explained.html

**Comment by vadz** [comment]
I start thinking that the implementation of `GetContentScaleFactor()` for wxMSW (which comes from `wxWindowBase`) is just wrong. It really ought to simply return 1, just as `GetOpenGLScaleFactor()` does.

This risks breaking things if we change it now, but OTOH if we're really sure that it's wrong, it's better to do it now rather than later.

**Comment by vadz** [comment]
AFAICS this should be redone once #1985 is merged, so it's not going to be applied in the current state and I'm temporarily closing it, please reopen if/when it's updated. TIA!

**Pull request closed without merging**
