### PR TITLE
compilable under Visual Studio conformance mode

### PR DESCRIPTION
**Pull request by exprosic**
to make it compilable with /permissive-, which is on by default in VS2017

### CODE REVIEW

**Comment by vadz** [comment]
Thanks, I'm going to apply this as soon as the CI builds finish. I wonder if it might be nicer to use `this->` here instead of `BaseApp::`, but the important thing is to fix it, of course.

**Comment by vadz** [comment]
See also https://trac.wxwidgets.org/ticket/18363

**Comment by exprosic** [comment]
I would also suggest to put "/permissive-" into the Makefile wherever possible.

**Comment by vadz** [comment]
> I would also suggest to put "/permissive-" into the Makefile wherever possible.

We can't do this without breaking the build using all the previous MSVS versions, unfortunately.

**Pull request closed without merging**
