### PR TITLE
Try iOS build using CMake in Travis

### PR DESCRIPTION
**Pull request by MaartenBent**
Just a test (unless it works).

### CODE REVIEW

**Comment by vadz** [comment]
Should we merge this? AFAICS the changes to `appveyor.yml` need to be reverted, but otherwise it looks ok to me, am I missing anything?

**Comment by MaartenBent** [comment]
I want to split it into separate commits, then it can be merged.

**Comment by MaartenBent** [comment]
This is ready to be merged, fyi.

**Comment by vadz** [comment]
Thanks a lot for adding this!

**Pull request merged**
