### PR TITLE
Remove QTKit support from wxMediaCtrl for OS X

### PR DESCRIPTION
**Pull request by TcT2k**
QTKit has been removed from OS X 10.12 SDK.
QTKit has been superseded by AVFoundation since OS X 10.7.
Since wxWidgets >= 3.1 requires 10.7 anyway there is no reason to support the old API.

Additionally the AVFoundation implementation may use AVKit (available since 10.9). It will be used when available and the deployment target is met.

See #336

### CODE REVIEW

**Comment by vadz** [comment]
Thanks!

**Comment by mojca** [comment]
Does this mean that trunk now only supports OS X 10.9 and newer and that support for < 10.9 will be dropped?

**Comment by TcT2k** [comment]
No 10.7 is still the supported. Only if you build with a deployment target >= 10.9 AVKit will additionally be used.

**Comment by mojca** [comment]
OK, but I'm confused about one thing then. In b98cbab46 hundreds of lines were removed that were there to support QTKit. Does AVFOUNDATION without AVKit provide all the functionality that was there in QTKit then?

**Comment by mojca** [comment]
I would like to backport some of your patches to version 3.0 (which is supposed to work on 10.5+). I guess I can cherry-pick some of your commits and apply them on top of the 3.0 branch. But given that you've been working on this code for the past few days, perhaps you would be willing to look into backporting your patches to the 3.0 branch (without removal of QTKit)? I need to provide a working version of wxWidgets 3.0.x to MacPorts users and wouldn't mind "outsourcing" some effort :)

**Comment by TcT2k** [comment]
I'll try to look into the backport in the next few days (but no promises).
The base for the backport should be 281610142b675d4f96928f443ae37821b723c2be as it still contains the QTKit support, but is buildable on the 10.12 SDK.

**Comment by TcT2k** [comment]
@mojca see #341

**Comment by mojca** [comment]
I don't want to highjack pull requests, I can open a new ticket, but just to mention here that the build of the latest master (c70abf2) on 10.7 fails for me with: `ld: framework not found AVKit`.

**Comment by TcT2k** [comment]
That should have been fixed by 7684f9208324dd7b91669e5bc426a26a21fecfb2
I tested with 10.12 SDK and 10.7 deployment target. Maybe you could post the configure.log somewhere.

**Comment by mojca** [comment]
The relevant line is
```
checking if AVKit is availble... checking CXXWARNINGS for gcc -Woverloaded-virtual... -Woverloaded-virtual
```
Maybe there's a minor bug in `configure.in` and the grouping is not right?

**Comment by TcT2k** [comment]
I think I figured out the issue, please see #370 for a fix.
Please test this with 10.7 SDK, but I'm pretty certain that the issue should be fixed with the additional check.

**Pull request merged**
