### PR TITLE
Added some scripts for almost automatic releases.

### PR DESCRIPTION
**Pull request by catalinr**
This is an attempt to automate the steps described in `docs/contributing/how-to-release.md`.

- `build/tools/step1-pre-release.sh` automates the bullet list in **`## Pre-Release Steps`**;
- `build/tools/step2-commits.sh` automates tag creation described under the same subtitle; it uses `new_release` branch to commit the changes (the name could be changed later);
- `build/tools/step3a-nix-release.sh` is a rename of the old file in order to have sequential stepping;
- `build/tools/step3b-copy-files.txt` only describes copying `.zip` package to `Windows`;
- `build/tools/step3c-win-release.bat` is a rename of the old file in order to have sequential stepping;
- `build/tools/step4-copy-files.txt` only describes copying `.exe` and `.chm` packages to `Linux` or `OSX`;
- `build/tools/step5-sha1sums.sh` will update sha1sums in `docs/release.md` for files listed under **`## Download Verification`** and commit changes.

This stops at **`## Uploading`** tag.
Another feature added to the last step might be to automatically push `new_release` branch to the default github account and remind the user to create the PR.
It would be good to know if the user should wait for the PR to be merged before creating a new release on GitHub. BTW, can anyone create a new release there? I have no idea how that works.

Actions under `## Announcement` look like they should be performed by a maintainer.

Actions under `## Version Updates` could be mostly done by a contributor, except `Trac` changes.
Running `inc_release`, `bakefile_gen`, `autoconf`, changing buildbot config file could be added to a[-nother] step in the list above.

It might be useful to separate maintainer-only steps, and emphasize points where a contributor needs to wait for maintainer action, if any.

### CODE REVIEW

**Review by tierra — COMMENTED** [review]
These are some helpful changes, just a couple suggestions for these scripts:

* It'd help to provide shebangs on all .sh scripts for explicit shell environments required (are they sh, or do they require bash?)
* Consider using `set -e` much like the existing release script does in order to fail early on errors.
* Try to test for the existence of gpg before using it, it's often not installed by default (and neither is git, but it's probably less likely you're using these scripts without it installed). Something similar to the checks in the Windows batch script.

**Comment by catalinr** [comment]
- Added shebangs. Though I think the scripts will run under any shell.
- Added `set -e` to step 1, 3 and 5.
- gpg is only used to list keys. If the call to it fails, it will continue without signing tags (just like if it was installed but no keys were set up). It would not be a fatal error. And current instructions do say "tag" and "commit" in a few places, shouldn't that imply git?

**Comment by vadz** [comment]
Note to self: don't forget to close http://trac.wxwidgets.org/ticket/17859 after merging this in.

**Comment by vadz** [comment]
Just an update: I'm not merging this yet because I'd like to test it with 3.1.1-rc1 first, but I've integrated (some of) your changes into [this branch](https://github.com/vadz/wxWidgets/tree/release-scripts).

As you can see, I've done some renaming as I found the "stepN" names really not very intuitive and would prefer to keep things simple with just {pre-,,post-}release scripts. I also don't really like scripts doing automatic commits, so I've dropped the one doing this and signing and I didn't see any real use in having text files which are redundant with `docs/contributing/how-to-update-third-party-library.md`. I also had to make some minor changes to the scripts to make them work for me.

But the 2 remaining script are genuinely useful, thanks for writing them!

**Pull request closed without merging**
