### PR TITLE
Add GTK+ 3 build to Travis CI

### PR DESCRIPTION
**Pull request by vadz**

### CODE REVIEW

**Comment by swt2c** [comment]
👍 too bad Travis has such an ancient version of GTK 3 though.

**Comment by tierra** [comment]
It might not have to be, but would likely slow the build down a bit if it can be updated to a more recent version. That said, I tend to think it's better to choose the older platforms for CI than newer, assuming you can't add a second build to cover both.

**Comment by tierra** [comment]
Well, more importantly, this is using the exact version that ships with Ubuntu 14.04 (Trusty), which makes it a preferred target version since it covers one of the largest groups of users.

**Comment by swt2c** [comment]
14.04 is pretty old at this point, I would expect 16.04 is more widely used.

**Comment by tierra** [comment]
Travis has supported Docker for a while now, we might be able to switch all the builds over to that for a wider range of platforms to test on. I'm not sure how fast that might be in comparison though.

**Comment by swt2c** [comment]
Yeah, I saw that docker was supported.  I suspect that builds would be slower using docker, but perhaps that is something to look into.

**Pull request merged**
