### PR TITLE
Improve documentation for convenience input functions and wxDirDialog

### PR DESCRIPTION
**Pull request by PBfordev**
Regarding the `wxDirDialog` commit:
1. Does `wxRESIZE_BORDER` still have to be used at all there?
2. The description of `wxDD_DIR_MUST_EXIST` is IMO still inaccurate. E.g., AFAICT, on Windows presence/absence of this flag has zero effect on the (`IFileDialog`-based) dialog appearance.

### CODE REVIEW

**Comment by vadz** [comment]
> Regarding the `wxDirDialog` commit:
> 
>     1. Does `wxRESIZE_BORDER` still have to be used at all there?

Apparently it triggers the use of `BIF_NEWDIALOGSTYLE` in wxMSW. I think it's also used by the generic implementation.
 
>     2. The description of `wxDD_DIR_MUST_EXIST` is IMO still inaccurate. E.g., AFAICT, on Windows presence/absence of this flag has zero effect on the (`IFileDialog`-based) dialog appearance.

Do you mean that `BIF_NEWDIALOGSTYLE` (or its absence) has no effect any more?

**Comment by PBfordev** [comment]
To be honest, I think the user should never see the old style dialog (`::SHBrowseForFolder()`). Am I missing something (aside from catastrophic `IFileDialog` API failure)?

**Comment by vadz** [comment]
> To be honest, I think the user should never see the old style dialog (`::SHBrowseForFolder()`). Am I missing something (aside from catastrophic `IFileDialog` API failure)?

Well, there is the check done in `wxIFileDialog::CanBeUsedWithAnOwner()`... I don't think this has been fixed, but I didn't test.

**Comment by PBfordev** [comment]
> Well, there is the check done in `wxIFileDialog::CanBeUsedWithAnOwner()`... I don't think this has been fixed, but I didn't test.

Sorry, forgot about that one; however, that should still be an edge case.

**Pull request merged**
