### PR TITLE
Don't rely on IsShownOnScreen to determine if things need to draw/refresh

### PR DESCRIPTION
**Pull request by dkulp**
Fixes a bunch of display issues on Mojave

### CODE REVIEW

**Comment by vadz** [comment]
Thanks! These changes seem fine to me but then I have no idea why have we ever called `IsShownOnScreen()` in the first place in this code, so I'd feel much more comfortable if Stefan could approve this.

**Comment by csomor** [comment]
Sure, IIRC it was to avoid premature refreshes of semi-constructed controls. I'll check, perhaps I'll brace the old code with a check whether we are not in a layer-backed view.

**Comment by csomor** [comment]
@dkulp thanks for looking into this. I can see the two different issues, (a) the fact that we get paint events at an unusual moment, ie. for an invisible view, (b) that a refresh might have to invalidate an invisible view, because we won't get another chance to do so later. 
(a) might also be a problem for user code which would be a lazy construction/update of the content of a hidden tab pane, so just painting it earlier is not really the complete solution there. I'll see whether there is some other way to indicate that we MUST get a refresh upon unveiling a view.

**Comment by csomor** [comment]
ok, I've just run the nonAUI-notebook sample under 10.14.1, added a subclass with its own paint event, and there I see the paint event happen every time the panel gets shown, and one when it's hidden, so there's no harm done by cutting short the paint event if the panel is not shown, things work without a change. I'll now look at the AUI-notebook.

**Comment by dkulp** [comment]
OpenGL panels on the panes of the AUINotebook do no get PAINT events when shown.

**Comment by csomor** [comment]
thanks

**Comment by dkulp** [comment]
Actually, I don't think it's JUST OpenGL.   We have a splitter window inside another splitter (out one splits horizontally, inner splits vertical on the left of the outer) and the inner splitter also does not display correctly.   On a separate page, we have a wxListCtrl that doesn't display correctly either if we change it's contents when it's page is not the visible page.

**Comment by csomor** [comment]
yes, in the AUI sample I get redraws out of order for some panels, so the native tab view does things differently (ie better) than aui, maybe I'll have to add things when a window get shown

**Comment by csomor** [comment]
@vadz could you please enlighten me ? what is the contract on `wxWindow::Show(bool show)` ? is the fact that a window gets shown connected with an implicit refresh ? I guess our wx-paint-model is not a assuming that windows might be buffered in that sense, so that calling hide and show on a panel would never trigger a paint, unless a refresh has been called on the window.

**Comment by vadz** [comment]
I don't think we ever really guaranteed anything about getting the paint events on show, but I think most (all?) of the existing code does expect that a window gets one after being shown, so it would be definitely more compatible to emulate this behaviour even under Mojave, if possible.

**Comment by csomor** [comment]
@vslavik, in 81ef669 you have added a recursive invalidation of children. In the AUI sample I see that I get therefore quite a lot of paint events for invisible tab panes, I'd like to change in `SetSubviewsNeedDisplay` the skipping condition from `!sub.layer` to `sub.isHidden || !sub.layer` . Would this create any regression in the preference panel bug you were solving with this method ? Thanks,

**Comment by dkulp** [comment]
While I would definite prefer whatever "works and displays correctly", I must say that after using my app for the last few days with the changes, I am really impressed by the "pre-paint" stuff in Mojave. Flipping pages and other operations are noticeably more snappy without the repaints going on.  Panels and such appear immediately.

**Comment by vslavik** [comment]
>  I'd like to change in SetSubviewsNeedDisplay the skipping condition from !sub.layer to sub.isHidden || !sub.layer . Would this create any regression in the preference panel bug you were solving with this method ? 

I tried that change and it's OK.

**Comment by csomor** [comment]
@vslavik thanks for the quick reply

**Comment by csomor** [comment]
I've committed b77aa4782d

**Comment by vadz** [comment]
I'm a bit lost, are the changes in this PR still needed? I.e. should it be merged, closed or something else?

**Comment by dkulp** [comment]
This doesn't seem to work, at least not completely.  I'm still getting "black" splitter windows and such when flipping to different AUINotebook tabs.   They are getting paint events when hidden, but not when being revealed.

**Comment by csomor** [comment]
is the problem reproducible with the aui sample (I've modified the suitability panes so that I can log paint events) ? or could you give me a patch ?

**Comment by dkulp** [comment]
I cannot get the problem to reproduce in the AUI sample.  I've tried to duplicate the control structure as close as possible, but it doesn't seem to appear.    In my app, I'm still seeing black windows as well as a wxListCtrl that doesn't display correctly on tab changes.   I cannot duplicate either with the aui sample.   :(

My app is completely open source ( https://github.com/smeighan/xLights/ ) so I can definitely provide that as a test case, but it will likely require a bit of an initial walk through to get it up and running enough to show it.    It's not the most intuitive app for a new user at all.

**Comment by csomor** [comment]
@dkulp if we don't find another way I'll have to use your sources, just to make sure before I dive into that: you are 100 % sure that in the library you were using to test, my two patches were present ?

**Comment by dkulp** [comment]
Yes.   I have a fork of wxWidgets with a specific branch setup:  https://github.com/dkulp/wxWidgets/commits/xlights_fixes

I rebased on master just a few minutes ago.  If I go back to the latest master commit (190601c47fb97e58dcd155818d8d22820931219b) then I see the black windows and list box draw issues.   If I advance to include my patches, I don't see the issue, if I go back, I see the issues again.

**Comment by dkulp** [comment]
I stuck a quick screen capture to show what I'm seeing:  https://www.dropbox.com/sh/m4ip1uc1xxwdo90/AACESPEBmuhL9q6SlIvm4rO7a?dl=0

Basically, on the "Setup" page, I can select something, then go to the Layout page and you can see (where I wiggle the mouse) the black section of one of the splitters.  I move a splitter sash and you can see it refresh to not be black.  I then flip back to the first page and the area of the selection is not drawn at all until I click on something again.

**Comment by csomor** [comment]
thanks, I'll try to build things tomorrow

**Comment by dkulp** [comment]
If you try to build things (there is a README.osx for some basic info) and get it started, it should immediately ask for a "Show Directory".  I've also included a "TestLayout.zip" file in my dropbox.  Extract that someplace and select the "Halloween" directory out of it.

**Comment by csomor** [comment]
ok, apparently even on Mojave Dark Mode some NSViews don't have their own layer, I have not yet found out, but commenting all checks which are done through checking whether `view.layer` returns non-null makes things work again. We'd have to make this 10.14 SDK and RT only of course. But before that I try to find out whether I can discover the reasons behind this difference somewhere.

**Comment by csomor** [comment]
ok, according to the docs, not all views are layer-backed, but some are sharing a layer with their others, therefore view.layer is nil, but their children still may be layer-backed and not getting redrawn when their parent is. [10.14 Release Notes](https://developer.apple.com/documentation/macos_release_notes/macos_mojave_10_14_release_notes/appkit_release_notes_for_macos_10_14)

**Comment by csomor** [comment]
I've changed the refresh code not to look at the fact whether a view itself is layer-backed, because there are views that are not, and still their children are layer-backed and need an explicit redraw, e484a2db , also I'm suppression spurious redraws for non visible views that are not shown, this new behavior of layer-backed views lead to crashes because the wxWindows we're not yet fully constructed, or already during destruction)

**Comment by vadz** [comment]
Do we still need this in 3.1.2 or has this been made obsolete by @csomor's changes?

**Pull request closed without merging**
