### PR TITLE
wxDataViewCtrl dnd improvements

### PR DESCRIPTION
**Pull request by vadz**
See #1881

### CODE REVIEW

**Comment by vadz** [comment]
@laptabrok FYI there are CI build errors here. Some of them are trivial (use `NULL` instead of `nullptr`), but others are less so (wxQt build fails).

**Comment by MaartenBent** [comment]
Its the `dataview` sample that fails to build. You shouldn't put the `EnableDropTarget(const wxDataFormat& format)` implementation in the base class.

Also, what are the guidelines about using `wxVector` instead of `WX_DEFINE_ARRAY`?

**Comment by vadz** [comment]
> Also, what are the guidelines about using `wxVector` instead of `WX_DEFINE_ARRAY`?

We definitely should use `wxVector` for any new code (unless, maybe, for the reasons of consistency with the immediately neighbouring existing variables, e.g. if we have `wxArrayInt foo`, it might be better to add `wxArrayInt bar` near it, but otherwise it absolutely should be `wxVector<int>`).

**Comment by vadz** [comment]
This was applied to #1881.

**Pull request closed without merging**
