### PR TITLE
Mojave colors

### PR DESCRIPTION
**Pull request by dkulp**
Bunch of updates to get various things looking OK in Mojave.   

settings.mm also contains some stuff I had printed out to determine various colors in light and dark mode.

### CODE REVIEW

**Comment by vadz** [comment]
Is there anything still remaining to commit here or should this be closed after recent @csomor changes?

**Comment by csomor** [comment]
sorry, I looked at the file in the trac report, missed that one, I'll double check, but I'm definitely not done yet, the AUI parts are missing, and I often find some other places to change as well. 
BTW I've also dumped a colour table (including alpha channel) for my tests, to see what native colours we have in NSColour but also in HITheme colors. Should I add these to settings.mm just in case we later want to check/compare things ?

**Comment by dkulp** [comment]
There are still a BUNCH of issues with Majave and Dark mode that this covers.   The AUI notebook tabs, wxPropertyGrid, AUI toolbars, etc...   I've started merging his updates and mine on the master branch of my fork.

**Comment by vadz** [comment]
@dkulp Could you please make a new PR with the changes from your fork? I don't think I can do it.

I'm closing this one as there are too many conflicts here by now.

**Pull request closed without merging**
