### PR TITLE
iOS menu support

### PR DESCRIPTION
**Pull request by csomor**
iOS does support menus since iOS 13, and even more in iOS 14 where they become a prominent element for different situations. But there is no menubar in iOS, therefore `wxUSE_MENUBAR` was introduced, to differentiate against `wxUSE_MENUS`, and will be used throughout wx for parts that depend on `wxMenuBar` being available.

### CODE REVIEW

**Comment by vadz** [comment]
I'm really not sure what has been changed in the project files (some files seemingly got simply removed?), but this doesn't seem to be related to the menu support at all, what am I missing here?

**Comment by csomor** [comment]
> what am I missing here?

nothing, I'm still rewriting, iOS 13 has gotten a new API for menus, so I'm rewriting things and only commit after

**Comment by vadz** [comment]
I wonder if this should be merged before 3.1.4 too? I.e. should we wait until this one is merged before freezing 3.1.4?

**Comment by csomor** [comment]
I'll have a look at it over the weekend

**Comment by csomor** [comment]
@vadz, a working connection to the wxButton is only there under iOS 14, adding the implementation for iOS 13 is to much work at the moment, but I still think it is worthwhile to have all the changes already in there being merged back ..

**Comment by vadz** [comment]
> @vadz, a working connection to the wxButton is only there under iOS 14, adding the implementation for iOS 13 is to much work at the moment, but I still think it is worthwhile to have all the changes already in there being merged back ..

Sorry, not sure if this was a question for me, but if it was, I can't really answer it -- I don't know anything about iOS. And, in fact, I'm not even sure what does a "working connection to wxButton" means, is this something like `wxToolBarTool::SetDropdownMenu()`?

**Comment by csomor** [comment]
yes, exactly, a button can have its own menu under iOS 14, to make this work under iOS 13, needs more code written, so the question was whether it's still ok to merge even with no functionality under previous systems, I think it's still worth it ..

**Comment by vadz** [comment]
The problem here is that there doesn't seem to be any reasonable fallback for the case when setting menu doesn't work. I.e. if the program UI relies on being able to associate a menu with the commands with a button, what can it do if this fails? AFAICS nothing, really...

So I guess ideal would be to only provide the new functionality at _compile_-time if the target is iOS 14+. This is rather unusual (maybe even unique) for wx API, but IMO would be better in this particular case than just returning an error during run-time.

Of course, in any case, this would need to be clearly documented.

**Comment by csomor** [comment]
I'd suggest I'll remove the few lines of API and impl I've added on `wxButton`, and the part in the minimal sample, so new new API here, we commit the rest with the `wxUSE_MENUBAR` and the native iOS menu implementation, and I'll do a new PR for iOS for contextual menus on controls, more native controls etc.

**Comment by csomor** [comment]
@vadz for this PR as well: is it ok when I squash and merge ?

**Comment by vadz** [comment]
I think it would be slightly preferable to keep `wxUSE_MENUBAR` additions in separate commits, if you'd like, and if you've finished with the changes here, I could rebase and merge this branch keeping these commits as they are and squashing all the rest.

**Comment by csomor** [comment]
That would be perfect, thanks a lot

**Comment by vadz** [comment]
As I don't have the permissions to push to this (org) branch, I've created #1965 replacing this one.

**Pull request closed without merging**
