### PR TITLE
Fix newlines in Doxygen ALIASES

### PR DESCRIPTION
**Pull request by StefanBruens**
According to https://www.doxygen.nl/manual/custcmd.html, newlines which
should appear in the output have to be written as "Physical newlines",
i.e. "^^". Otherwise, line-commands like '\ingroup' and '\image' are not
terminated properly.

This fixes output with doxygen 1.8.20 (likely effects any version since
1.8.16).

### CODE REVIEW

**Comment by vadz** [comment]
The problem is we're still using Doxygen 1.8.8 on docs.wxwidgets.org and I'm not sure if this is going to work correctly with that ancient version. I wonder if anybody still has it at hand and can check how things work with it?

@tierra I don't know if we can update Doxygen easily, although even if we could, it's going to be tricky to ensure that the new version works correctly with the old wx versions...

**Comment by StefanBruens** [comment]
Support for '^^' added here:

**Comment by vadz** [comment]
So we can't apply this right now... We already use variables in `Doxyfile`, I wonder if we could define some `ALIAS_NL` variable in `regen.sh` as either `"\n"` or `"^^"` depending on Doxygen version and then use it here?

**Comment by vadz** [comment]
I still have no idea what to do about this one. If somebody could try to find a solution that would work with docs.wxwidgets.org and the new versions, it would be really great... Right now I can only think of having a script preprocessing this depending on the Doxygen version.

**Comment by tierra** [comment]
I've always built Doxygen from source on docs.wxwidgets.org (see "doxygen" folder on server) since we've historically landed on odd versions that don't always match the version that ships with the distro version in use on the server. Also, the version on the server is only used to generate the master/trunk branch. The rest are generated and uploaded manually. So as long as the version you want to move head to can be compiled successfully on the server, I can upgrade that at the same time head merges any/all changes necessary to the docs to be compatible with that version.

Of course, new 3.0.x releases would still likely need to be generated with 1.8.8 (unless Doxygen has started maintaining backwards compatibility in these releases for a change).

**Pull request closed without merging**
