### PR TITLE
wxDropTarget fix [gtk port]: GdkDragContext must be set in target_dra…

### PR DESCRIPTION
**Pull request by valid-ptr**
…g_data_received, thus wxDataFormat will be correct when OnData callback is called

### CODE REVIEW

**Comment by vadz** [comment]
Thanks, I don't see anything wrong with it, but it's not totally clear what problem exactly does this fix, could you please explain? Looking at `wxDropTarget::GetData()`, it doesn't seem to be using `m_dragContext`, so why does setting it matter?

**Comment by valid-ptr** [comment]
This comes from DVC's `wxEVT_DATAVIEW_ITEM_DROP` event.
Event's `GetDataFormat() `returns bad values (`fmt->GetType() `and `fmt->GetId() `as instance) without this PR

NOTE: D'n'D from different processes

**Comment by vadz** [comment]
I still don't understand where is the drag context used exactly (do you?), but let's merge this if it fixes a real problem, thanks.

**Comment by valid-ptr** [comment]
correct :)

**Pull request closed without merging**
