### PR TITLE
Add the check for emptiness

### PR DESCRIPTION
**Pull request by Kvaz1r**

### CODE REVIEW

**Comment by vadz** [comment]
Sorry, this doesn't really make sense, especially without any explanations.

I'm almost sure that this shouldn't be done, but if you believe differently, please at least try to explain why is it so.

**Comment by Kvaz1r** [comment]
@vadz , if someone will try add an empty wxVector as value then application will be "locked"(that is a behaviour which I watched). And although it - completely problem of caller side I guess would be better add this check. 

Please correct me If I wrong.

**Comment by vadz** [comment]
I don't understand why would it lock up (it'd be worth debugging this) but if it already doesn't work, it is another argument _against_ this change: we shouldn't just silently accept wrong data. We should add a `wxCHECK` verifying that `values` is not empty or, probably, that it contains the correct number of elements (i.e. `GetColumnCount()`).

**Comment by Kvaz1r** [comment]
Good,thanks, it is reasonable for me - adding the check is better solution.

**Comment by Kvaz1r** [comment]
So...I should open new PR, edit this one, someone else  will change it by right way or just let it be as it is?

**Comment by vadz** [comment]
Ideal would be to

1. Understand why does it lock up now, because it bothers me that we don't know why does something bad like this happen.
2. Assuming (and this could be confirmed or denied by debugging (1) above) that `wxDataViewListStoreLine::m_values` really must always contain exactly `GetColumnCount()` items, it would make sense to make a reusable function checking for this and creating a new `wxDataViewListStoreLine` if this is the case or returning `NULL` otherwise.
3. Then this function should be used in all of `{Append,Prepend,Insert}Item()`.

This is relatively low priority as I don't think `wxDataViewListStore` is a very useful class in general, so I don't plan on doing this myself but if you can do the above, your changes would, of course, be gratefully accepted, as always -- feel free to reopen this PR or create a new one, whichever is more convenient for you. TIA!

**Pull request closed without merging**
