### PR TITLE
Remove unused variable and consistent usage of NULL

### PR DESCRIPTION
**Pull request by dvertx**
Variable m_pictCreated was only initialised in Init and Clear methods, but never used anywhere else.
The other change is about consistency of NULL as initialisation value to cgImageRef variable.

### CODE REVIEW

**Comment by vadz** [comment]
Thanks, the change definitely looks correct, but I'm not sure if it's not going to conflict with the changes being done by @csomor -- Stefan, could you please let me know if it's ok to merge this?

Also, and sorry for nitpicking, but it would be really preferable to avoid unrelated whitespace changes in your commits. I can apply this one without them (which is why I'd rather merge it myself), but could you please configure your editor to avoid making them in the future? TIA!

**Comment by csomor** [comment]
It's fine, it's after my change

**Comment by dvertx** [comment]
Sorry, for unintended whitespace removal.
Updated dataobj.cpp with new editor setting

**Comment by vadz** [comment]
Thanks for the update! Applied now.

**Pull request closed without merging**
