### PR TITLE
Dequeue and dispatch events in modal event loops.

### PR DESCRIPTION
**Pull request by jpd236**
This should be a no-op, as runModalSession's documentation states that
it will handle dispatch event for the modal's window. However, in
practice, it does not seem to be doing so frequently enough for modal
UI to keep up with two-finger scroll events. Dequeuing and manually
dispatching the next event seems to mitigate this.

Note that we only dispatch events that are associated with the modal
dialog's window, or with no window at all, to prevent other windows
from responding to inputs while the modal is present.

Fixes #17737

### CODE REVIEW

**Comment by vadz** [comment]
This seems to solve a real user-visible problem, so even though I don't understand what does this change do/why does work, I'm still ready to merge it if there are no objections from Mac-knowledgeable people. Please let me know if you think this shouldn't be merged or find any problems during testing it!

**Comment by vslavik** [comment]
This may cause loss of events, no? I'd feel uneasy about that part -- it removes events from the queue and discards them. I don't know enough about Cocoa's event processing to be 100% sure some events  aren't sent to non-modal window too (and the existence of the `if` statement to check for this seems to indicate there indeed are such events).

It's one thing that other windows should be non-responsive (correct) and another if *they never receive events sent to them* because they were silently discarded.

**Comment by jpd236** [comment]
I did find this in the [documentation](https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/WinPanel/Concepts/UsingModalWindows.html):

> The normal behavior of a modal window or session is to exclude all other windows and panels from receiving events. 

So I think it is indeed (arguably) correct that other windows shouldn't receive events sent to them. I initially just called sendEvent unconditionally, but found this broke the modal contract as other windows began handling clicks and other input while the modal was present. It was indeed the case that events for other windows were showing up in the queue. (FWIW, I tried calling `nextEventMatchingMask:untilDate:inMode:dequeue` on the NSWindow for the modal rather than the NSApp, but that didn't appear to restrict the queue to window events as I'd hoped).

Note that events with _no_ window associated will continue to be delivered.

That's how I landed here. I do acknowledge that something smells off about it and would welcome a better approach from someone more knowledgable than I.

**Comment by vslavik** [comment]
> So I think it is indeed (arguably) correct that other windows shouldn't receive events sent to them.

Yes, but does that mean that should be *lost* or that they should be delivered after the modal window ends? Some like clicks clearly shouldn't be delivered after the fact, so hopefully it should indeed be fine.

>  would welcome a better approach from someone more knowledgable than I.

That's not me either I'm afraid. The only thing I'd try is using `NSModalPanelRunLoopMode` instead of `NSDefaultRunLoopMode` to see if it filters out other windows' events.

**Comment by jpd236** [comment]
I gave NSModalPanelRunLoopMode a try, but still saw events for other windows.

**Comment by vslavik** [comment]
Then I’m with @vadz on this, merge and see if it causes any issues (hopefully not). Thanks!

**Comment by vadz** [comment]
This is done now, thanks for investigating and (hopefully) fixing this!

**Comment by vslavik** [comment]
Bad news: this patch breaks things.

My test case (which I can’t reduce to something small right now) is this: create a modal dialog with a Browse… button in it. When the user presses the button, a file open dialog opens as *window modal* (with the modal dialog being its window):

```cxx
    pathButton->Bind(wxEVT_BUTTON, [=](wxCommandEvent&){
        wxWindowPtr<wxDirDialog> dirdlg(new wxDirDialog(this,
                        _("Select folder"),
                        "",
                        wxDD_DEFAULT_STYLE | wxDD_DIR_MUST_EXIST));
        dirdlg->ShowWindowModalThenDo([=](int retval){
            if (retval == wxID_OK)
                { /* do something */ }
        });
    });
```

 This is a reasonable way to stack window opening on macOS and worked fine before this change (I verified by reverting it). With this PR applied, the `NSOpenPanel` is unresponsive to any input. After killing it, execution is in this loop (on the `nextEventMatchingMask:` line when I tried).

**Comment by jpd236** [comment]
Without having tested this, it seems the distinction here is between `ShowModal()` (which restricts input to the rest of the program) and `ShowWindowModal()` (which restricts input to the parent frame but not the rest of the application).

I wonder if the portion of the patch which filters events by NSWindow could be adjusted to handle this case without having to revert the whole thing.

If you're able to put together a small repro case, that would be helpful; otherwise I can give it a try this weekend.

**Comment by vslavik** [comment]
This goes back to my worry about *just throwing events away* above. If it breaks something as not unusual as this what *else* may be silently discarded? Whitelist of preserved events, as is done here, sounds like a bad solution in light of this — as opposed to a blacklist of events you *know* you can safely discard.

Plus of course it’s unclear why this change fixes the original problem in the first place, and I think that warrants understanding, instead of just patching this one known problem (because again, more may be waiting).

**Comment by jpd236** [comment]
Again, I'm coming at this from a pretty inexperienced angle here, so take what I have to say with an appropriately-sized grain of salt. I'm not sure I agree that the example you gave is "not unusual" - the wxDialog docs say:

> There are two kinds of dialog, modal and modeless. A modal dialog blocks program flow and user input on other windows until it is dismissed, whereas a modeless dialog behaves more like a frame in that program flow continues, and input in other windows is still possible.

So this "window modal" is actually a third kind of dialog, one that "is only fully implemented in wxOSX ports". That seems like a pretty unusual case to me. And I don't think whitelist vs. blacklist solves the problem. The issue is not "mouse clicks should be blacklisted", it's "mouse clicks to this set of windows should be blacklisted", and the bug here seems like it's in the "set of windows" portion, if that makes sense.

I echo your concern that it's unclear why this is a fix and still would love to understand what's going wrong better. But failing any new insights there, I think what I proposed above might still be a reasonable fix for the issue you observed.

**Comment by vslavik** [comment]
> That seems like a pretty unusual case to me.

Window modal sheets are *standard* on macOS and are actually far more common than application-modal windows. wx has full cross-platform support for them (mapping to app-modal on other platforms). It's definitely not an edge case.

You could argue that the the case I described sort of is, but that's due to there being an application-modal window in the first place. BTW, while my description is a far cry from a diff against a sample, it is enough to quickly reproduce: just run a code snippet like the above one in a modal dialog. I'm leaving for a few days in half an hour and can't do a proper diff, sorry :(

**Comment by jpd236** [comment]
OK, I've reproduced the issue you described and taken a closer look. Unfortunately, I continue to lean towards this not actually being "a reasonable way to stack window opening" at least as wxWidgets is currently implemented atop Cocoa. The point of ShowWindowModal vs. ShowModal is that it allows input to other windows while open - but if you already have a modal dialog open beneath it, that modal is blocking input to other windows, so what's the point of using ShowWindowModal at that point, vs. ShowModal?

Now, a user-visible difference is that in the Mac implementation, ShowWindowModal is using a "sheet" which is more visibly tied to its parent window than a modal dialog. But there's at least [some evidence](https://bugzilla.mozilla.org/show_bug.cgi?id=478073) I can find that suggests that putting a sheet on a modal is not okay:

> For obvious reasons, sheets can't be nested over app-modal dialogs.

(Not so obvious to me, but there it is...)

So it seems to me that "ShowWindowModal" may not be the right abstraction to be putting atop sheets, nor are sheets the right user interface to use on top of a modal.

But, here we are. One possible fix for the particular scenario you mention is to add `|| event.window == modalWindow.attachedSheet` to the if-statement that gates whether we send the event, and that seems to resolve things here for my simple test case. The [cocoa documentation](https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/Sheets/Tasks/UsingCascadingSheets.html) says "Cocoa does not support the notion of cascading, or nested sheets." So I'm not sure that further checks beyond that would be necessary... but we've already seemingly entering unsupported territory.

As the above Mozilla bug alludes to, it seems like it's generally difficult to come up with a single modal dialog abstraction that works cross-platform (as wxWidgets tries to do), because there are fundamental differences between how native dialogs work on each platform. If we need a general abstraction, some unfortunate ugliness may be involved...

Counterarguments and proposals are more than welcome! :)

**Comment by jpd236** [comment]
We missed each other there by a few minutes, but to reply specifically (and more succinctly) to your point - yes, I retract my earlier comment that ShowWindowModal is uncommon / quirky on Mac specifically, but I do think there is evidence that a window modal (sheet) on a dialog is indeed uncommon from a functional perspective because its point is to allow input in other windows, but that input is already being blocked by the parent modal. Perhaps what should be happening under the covers here is that a sheet shown from a modal [should itself be made modal](https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/Sheets/Tasks/UsingAppModalDialogs.html)?

**Comment by jpd236** [comment]
OK. I looked at this more and feel like I have a better fix based on an [old cocoa-dev@ post](http://www.mail-archive.com/cocoa-dev@lists.apple.com/msg16300.html). No more manual event sending. LMK what you think.

**Comment by vadz** [comment]
Thanks a lot for continuing to look into this (even though it turned out to be even more complicated than I thought)!

FWIW I think it wouldn't be a problem to make window-modal sheet in a modal dialog app-modal itself, as you say, it's not like you can use any other windows in the application in this case anyhow. It just needs to happen transparently from wxWidgets API point of view.

Of course, if the latest version works, it's even better (because it's so simple), but I admit I don't understand why/how does it work exactly...

**Comment by vslavik** [comment]
> FWIW I think it wouldn't be a problem to make window-modal sheet in a modal dialog app-modal itself, as you say, it's not like you can use any other windows in the application in this case anyhow. 

Hopefully it doesn't matter anymore (I'll look at the new patch when I'm back and will try to test it (more) extensively), but I beg to differ with this. Stacking modal windows atop each other is horrible idea, it's just not done on macOS. Sheets in modal windows are something native Cocoa has no problem. It's hard enough to make decent Mac apps in wx, it would be better not to intentionally sabotage it like that. I like @jpd236's idea of extending the filter to the sheets better -- but again, it seems all of this is moot now anyway (let me add my thanks for that too).

**Comment by vslavik** [comment]
I agree with your commit message that this looks like a much cleaner fix (and the explanation of what caused the original problem sounds plausible too). Everything seems to work in my testing so far as well.

@vadz any objection to me merging 5d85c2e?

**Comment by vadz** [comment]
Yes, I agree as well. But while looking at it, I realized that reformatting the latest commit a little yields a much nicer diff with the original version which is just:

```diff
diff --git a/src/osx/cocoa/evtloop.mm b/src/osx/cocoa/evtloop.mm
index cf9f46e..976a973 100644
--- a/src/osx/cocoa/evtloop.mm
+++ b/src/osx/cocoa/evtloop.mm
@@ -216,9 +216,12 @@ int wxGUIEventLoop::DoDispatchTimeout(unsigned long timeout)
         {
             case NSRunContinuesResponse:
             {
+                [[NSRunLoop currentRunLoop]
+                        runMode:NSDefaultRunLoopMode
+                        beforeDate:[NSDate dateWithTimeIntervalSinceNow: timeout/1000.0]];
                 if ( [[NSApplication sharedApplication]
                         nextEventMatchingMask: NSAnyEventMask
-                        untilDate: [NSDate dateWithTimeIntervalSinceNow: timeout/1000.0]
+                        untilDate: nil
                         inMode: NSDefaultRunLoopMode
                         dequeue: NO] != nil )
                     return 1;
```

so I'm going to commit it myself like this.

Thanks again Jeff for your work on this!

**Pull request closed without merging**
