### PR TITLE
macOS 10.7 build fixes

### PR DESCRIPTION
**Pull request by vadz**
See https://trac.wxwidgets.org/ticket/18726

### CODE REVIEW

**Comment by mimi89999** [comment]
OX 10.7? That's lion released 8 years ago.

**Comment by vadz** [comment]
As the ticket shows, some people still use it apparently, so as long as it's not too burdensome to continue to support it, why not.

**Comment by vadz** [comment]
Note to self: AppVeyor test failure is bogus, it's a network timeout in one of the tests again.

**Comment by obfuscated** [comment]
If the 10.7 build is supported then shouldn't you make travis-ci explicitly request it? At the moment it seems it is requesting 10.9.

**Comment by vadz** [comment]
According to [the docs](https://docs.travis-ci.com/user/reference/osx/#macos-version) the oldest support macOS version on Travis is 10.10.

**Comment by obfuscated** [comment]
I think this is different. You can build for older OSes using new OSes by passing the min-macos version flag. The 10.10 in travis docs is about the version used to run the VM (or whatever they use to run the jobs).

**Comment by vadz** [comment]
In general, you're right, but I'm pretty sure 10.10/Xcode 6.4 SDK doesn't include 10.7 support any more. And AFAIR you really need to build using 10.7 compiler when targeting 10.7.

**Comment by rtwruck** [comment]
Support for 10.7 is stated in the [README](https://github.com/wxWidgets/wxWidgets/blob/v3.1.3/docs/readme.txt).
There are still a few old Macs out there (including one of our build servers) but the installation base slowly converges to 0.
If you want to keep that minimum supported version, I'll open another PR - the new wxpng version won't build there either.

**Comment by vadz** [comment]
@rtwruck If this PR fixes the problems I reported, I'm fine with merging it, could you please confirm if it does? And, of course, if you want to submit a PR to fix libpng build, please do, too.

As I said, I'm fine with maintaining 10.7 compatibility as long as it doesn't cost us too much.

**Comment by vadz** [comment]
We've taken the decision to require 10.10 or maybe 10.11 for the next release, so this is not finally going to be applied, especially as there doesn't really seem to be any real interest in it.

**Pull request closed without merging**
