### PR TITLE
Dynamic offsetting

### PR DESCRIPTION
**Pull request by csomor**
To allow for very thin lines being drawn correctly as well, make offsetting dependent not only from the pen width, but also of the pixel resolution.

### CODE REVIEW

**Comment by csomor** [comment]
too many conflicts with current master, let's start again ...

**Comment by vadz** [comment]
I can rebase this on master if you'd like, but I'm not sure if you're going to address [this message](https://groups.google.com/g/wx-dev/c/gU2VKW7yXxQ/m/uhAOwtDaCAAJ) or not, so I won't do it unless you tell me that I should.

**Comment by csomor** [comment]
Thanks, I'll wait.

**Comment by vadz** [comment]
Stefan, sorry, I'm not sure what do you mean. Will you wait for me to rebase it? If so, you need to recreate your branch as I don't have access to it any longer after you've deleted it.

**Comment by csomor** [comment]
No, sorry, no need to rebase. I'll look at how to pixel align with wxGraphicsContext explicitly later and perhaps do so in the drawing sample.

**Pull request closed without merging**
