### PR TITLE
Really fix Mac wxGLCanvas resize under macOS 10.14.5

### PR DESCRIPTION
**Pull request by vadz**
@csomor Your review would, as always, be appreciated. TIA!

### CODE REVIEW

**Comment by valid-ptr** [comment]
Tested! Everything is fine :)

**Comment by csomor** [comment]
Thanks, I'm still looking at the original bug report, and running the sample on different macOS versions, I'll come back

**Comment by csomor** [comment]
I only can reproduce the problem when linking against 10.14 SDK, when linking against 10.13 SDK the problem does not happen on 10.14.6

**Comment by csomor** [comment]
The problem does not happen under current 10.15 Beta either

**Pull request merged**
