### PR TITLE
Handle EVT_TEXT_PASTE event in wxValidators

### PR DESCRIPTION
**Pull request by AliKet**
Continuing from this [PR](https://github.com/wxWidgets/wxWidgets/pull/1117)
I did some code refactoring to eliminate code duplication between `wxTextValidator` and `wxNumValidator`. And implement `wxRegexTextValidator`.

I did it as a separate PR just to know if those changes are seen as positive and would be accepted.

TIA!

### CODE REVIEW

**Comment by AliKet** [comment]
@vadz do you have time to review this PR?

TIA!

**Comment by vadz** [comment]
Sorry, I don't see what exactly is new here, compared to the previous PR? Perhaps you could make a PR against the other branch?

**Comment by vadz** [comment]
I'll try to merge #1117 a.s.a.p.

**Comment by AliKet** [comment]
Thank you.

BTW how about making wxTextValidator send validation status on focus lost ?
something like this :

```
void wxTextValidator::OnKillFocus(wxFocusEvent& event)
{
    event.Skip();

    wxTextEntry * const control = GetTextEntry();
    if ( !control )
        return;

    IsValid(control->GetValue()).empty() ?
        SendOkEvent() : SendErrorEvent();
}
```

**Pull request closed without merging**
