### PR TITLE
Libexpat 2.2.1

### PR DESCRIPTION
**Pull request by catalinr**

### CODE REVIEW

**Comment by catalinr** [comment]
Note: The only files needed by the build system are the `.c` ones in `lib/` subdir that **_do not_** contain `/* This file is included! */ ` comment.
There could probably be a script somewhere to validate libexpat upgrades.

**Comment by hartwork** [comment]
It sounds like `siphash.h` and `winconfig.h` would not be included with that. Those file are needed as well.

**Comment by hartwork** [comment]
About [missing `stdint.h`](https://ci.appveyor.com/project/wxWidgets/wxwidgets/build/1805/job/hdi51sg9l9rg72gg), does it have `inttypes.h`?

**Comment by catalinr** [comment]
Right, headers and other include files are needed too.

Attempt at disambiguation :)  : wxW includes only the minimal set of .c files in its project files and makefiles. Included files are also distributed and used in compilation (otherwise it would fail), just that they are ignored by the build files generated by wxW. That is what I meant in the previous note.

Thanks for following this!

**Comment by catalinr** [comment]
The compilation error might be a problem. That build uses Microsoft Visual Studio 2008, while `stdint.h` was apparently introduced [starting with VS 2012 or 2013](https://stackoverflow.com/questions/12970293/why-microsoft-visual-studio-cannot-find-stdint-h).

**Comment by hartwork** [comment]
After reading https://github.com/chemeris/msinttypes/blob/master/stdint.h a bit, I have this fix in mind:

```
#if defined(_WIN32) && defined(_MSC_VER) && _MSC_VER < 1600  /* 1600 is vs2010/10.0 */
  /* For vs2003/7.1 up to vs2008/9.0 */
  typedef unsigned __int8   uint8_t;
  typedef unsigned __int32 uint32_t;
  typedef unsigned __int64 uint64_t;
#else
# include <stdint.h>
#endif
```
Please note [their checks against `_MSC_VER`](https://github.com/chemeris/msinttypes/blob/master/stdint.h) and that Visual Studio 6.0 is not meant to be supported by Expat any more.

Could you give that a spin?

**Comment by hartwork** [comment]
Looks good to me. I [applied that upstream](https://github.com/libexpat/libexpat/commit/c74d380b8f0b5215153d840d2af9455d9c53b960) now. If you need further changes, please let me know.

**Comment by hartwork** [comment]
Any news?

**Comment by vadz** [comment]
@hartwork Sorry, I was away for a few days and still haven't totally cleared the backlog since getting back, but this is one of the items near the top of my TODO heap and I definitely will get to it soon (probably not before the end of the month though).

**Comment by hartwork** [comment]
Thanks for the update!

**Comment by vadz** [comment]
Sorry again for taking so long. I've finally looked at it and there are 2 warnings when building with MSVC 14 (a.k.a. MSVS 2015): the first one

    src\expat\lib\siphash.h(324): warning C4267: '=': conversion from 'size_t' to 'unsigned char', possible loss of data (compiling source file ..\..\src\expat\lib\xmlparse.c)

is just annoying but harmless (because `i` is never going to be greater than 64, in spite of being `size_t`). It would still be nice to fix it and there are several ways to do it (add a cast, change the type of `i`, ...), so I don't know which one to choose.

The second one is worse though:

    src\expat\lib\xmlparse.c(752): warning C4133: 'function': incompatible types - from 'char [13]' to 'LPCWSTR'

This code is just wrong in Unicode build and won't work correctly, i.e. loading the DLL will always fail. Here you need to either do `LoadLibraryA("ADVAPI32.DLL")` or, tiny bit more efficiently, `LoadLibrary(_T("ADVAPI32.DLL"))`. But this really ought to be fixed.

**Comment by hartwork** [comment]
For `conversion from 'size_t' to 'unsigned char'` please see https://github.com/libexpat/libexpat/commit/788bff7a3baad1983b15b17c29e19e1a1a795c48.

For the `LoadLibrary` one please check https://github.com/libexpat/libexpat/commit/73a5a2e9c081f49f2d775cf7ced864158b68dc80.

**Comment by vadz** [comment]
@catalinr Should I take this PR and cherry pick the commits mentioned in the [comment above](https://github.com/wxWidgets/wxWidgets/pull/503#issuecomment-314601826) or do we want to make another merge with the latest libexpat master?

**Comment by catalinr** [comment]
@vadz I see revision 2.2.2 is out. I'll try to make a new PR with it a bit later.

**Comment by hartwork** [comment]
Post-2.2.2 pull request https://github.com/libexpat/libexpat/pull/83 may also be of interest to you.

**Comment by catalinr** [comment]
Right, thanks!

@vadz should I get the latest master of libexpat or wait for 2.2.3 ? The problem with undefined "WIN32" symbol when using c++11 & gcc on Windows is still present in wxW master, which would be an argument in favor of applying a change sooner. But then again, I don't think a new wxW 3.1.x is scheduled any time soon.

**Comment by vadz** [comment]
@catalinr I'm still not sure how exactly do you do it (please excuse me if I'm forgetting something again, I'm pretty sure I had asked about this already, but I don't seem to be able to find the answer anywhere and `docs/contributing/how-to-update-third-party-library.md` is still hopelessly out of date), but if it's relatively straightforward, let's use 2.2.2+patch(es?) now, even if I still don't promise anything, I'd like to release 3.1.1 soon. TIA!

**Comment by catalinr** [comment]
At the end of that file there are 2 detailed examples. The last one is about libexpat. Note that it could still be simplified by only copying the files in `lib/` subdir, as somewhat described in the comments above.

BTW, I think that file should just contain only examples for upgrading each third party library, like the 2 already present at its end, and have the old contents removed.

**Comment by catalinr** [comment]
Replaced with #524

**Comment by vadz** [comment]
I knew I was forgetting something :-( FWIW I completely agree that we should remove outdated information about this file, it's more confusing than helpful (just look at how it confused me).

Concerning the procedure itself, I wonder what would it take to make `src/expat` a submodule. It looks like it would make it much simpler to track its development (which is much more relevant now that it's back from dead...).

**Pull request closed without merging**
