### PR TITLE
Improve wxQtDCImpl to better match Cairo rendering + enable anti-aliasing.

### PR DESCRIPTION
**Pull request by dsa-t**
Test case (replaces "bombs" demo): [dctest.zip](https://github.com/wxWidgets/wxWidgets/files/14302935/dctest.zip)

Reference (GTK3 after https://github.com/wxWidgets/wxWidgets/pull/24327):

gtk_after

wxQt, with this PR:
qt_after

wxQt, current master (shrinking non-stroked rectangles caused "holes" in UI, and arcs were incorrect):
qt_before

### CODE REVIEW

**Comment by dsa-t** [comment]
The test
```
./graphics/bitmap.cpp:434: FAILED:
  CHECK( unmaskedPixelsCount == numUnmaskedPixels )
with expansion:
  60 == 64
```

fails because of the anti-aliased mask rectangle corners:

Screenshot_2024-02-16_02-16-15

This code doesn't work because it doesn't use wxGraphicsContext.
```cpp
#if wxUSE_GRAPHICS_CONTEXT
            wxGraphicsContext* gc = dc.GetGraphicsContext();
            if (gc)
            {
                gc->SetAntialiasMode(wxANTIALIAS_NONE);
            }
#endif // wxUSE_GRAPHICS_CONTEXT
```

Antialiasing should be disabled for 1bpp images

qt_after_1bpp_black

(1bpp, no AA, with wxGREY_BRUSH -> wxBLACK_BRUSH)

**Comment by vadz** [comment]
> The test [...] fails because of the anti-aliased mask rectangle corners:

Thanks for looking into this, but what would be the solution for this?
 
> This code doesn't work because it doesn't use wxGraphicsContext.
> 
> ```c++
> #if wxUSE_GRAPHICS_CONTEXT
>             wxGraphicsContext* gc = dc.GetGraphicsContext();
>             if (gc)
>             {
>                 gc->SetAntialiasMode(wxANTIALIAS_NONE);
>             }
> #endif // wxUSE_GRAPHICS_CONTEXT
> ```

Err, sorry, why doesn't it use when it looks like it does? 

> Antialiasing should be disabled for 1bpp images

This seems logical, but, as always, I wonder if there is any possibility of breaking something by doing it?

**Comment by dsa-t** [comment]
> Thanks for looking into this, but what would be the solution for this?

I've already disabled AA for 1bpp paint devices in latest commits. But the other test also seems to fail because AA needs to be disabled in `wxQtDCImpl` somehow. 

```
./graphics/clippingbox.cpp:2109
...............................................................................

./graphics/clippingbox.cpp:262: FAILED:
explicitly with message:
  Invalid shape of the clipping region
```

> Err, sorry, why doesn't it use when it looks like it does?

`wxQtDCImpl` does not inherit from `wxGCDCImpl`, so `GetGraphicsContext()` always returns nulllptr.

I'm not sure why it doesn't though, and `src/qt/graphics.cpp` that provides `wxQtGraphicsRenderer` instead of Cairo is only built on Windows for some reason.

>This seems logical, but, as always, I wonder if there is any possibility of breaking something by doing it?

Antialiasing doesn't look right anyway in 1bpp mode, so should be fine.

**Comment by vadz** [comment]
Apparently the plan was to use this code for all platforms, see #1139, but somehow this has never happened. If it works under the other platforms, I think we should indeed enable it -- have you been able to check if this is the case already, by chance?

**Comment by dsa-t** [comment]
It works on my Linux distro, Qt prints some asserts though.

**Comment by dsa-t** [comment]
Looks like the tests passed.

**Comment by vadz** [comment]
Thanks for the update!

@AliKet Please let me know if you have any comments about changes here.

**Comment by AliKet** [comment]
> I'm not sure why it doesn't though, and `src/qt/graphics.cpp` that provides `wxQtGraphicsRenderer` instead of Cairo is only built on Windows for some reason.
> 

You have to remove the `defined(__WIN32__)` check here https://github.com/wxWidgets/wxWidgets/blob/f24b3d54833a1c15ae3bba87dead83bf9a90c41d/src/generic/graphicc.cpp#L3695-L3702
to get `wxQtGraphicsRenderer` instead of Cairo.

I worked on this last year, but lost that work due to a hardware malfunction unfortunately. But one issue I noticed at the time (with other minor issues) was the clipping that needed to be fixed for the tests to pass.

**Comment by AliKet** [comment]
> @AliKet Please let me know if you have any comments about changes here.

No comment.

**Comment by AliKet** [comment]
@dsa-t Let me know if you have any plan to work on making `wxQtGraphicsRenderer` available under non-Windows too ?

**Comment by dsa-t** [comment]
> @dsa-t Let me know if you have any plan to work on making `wxQtGraphicsRenderer` available under non-Windows too ?

Not in the near future.

**Comment by vadz** [comment]
Sorry, one more question: why do we enable `Antialiasing` here but not both it and `TextAntialiasing`, as in `wxQtGraphicsContext::SetAntialiasMode()`?

Would it make sense to extract this into a (private) function to make it easier to change this later, if necessary?

**Comment by dsa-t** [comment]
TextAntialiasing is already enabled by default.

**Comment by dsa-t** [comment]
>Would it make sense to extract this into a (private) function to make it easier to change this later, if necessary?

Not sure what would be the right place to put this function.

**Comment by vadz** [comment]
> > Would it make sense to extract this into a (private) function to make it easier to change this later, if necessary?
> 
> Not sure what would be the right place to put this function.

After looking more at wxQt code, I think I would add some (inline) `namespace wxQtImpl { QPainter* CreatePaint(); }` to `include/wx/qt/private/painter.h` and use it instead of `new QPainter()` to ensure that all painters we use are initialized in a consistent way. What do you think?

**Comment by dsa-t** [comment]
Sounds ok to me, I probably won't have time to tackle it though.

**Comment by vadz** [comment]
OK, let's merge it as is then and leave this as a possible future enhancement.

Thanks again!

**Pull request merged**
