### PR TITLE
Fix e not working in Unicode wxDateTime::ParseFormat

### PR DESCRIPTION
**Pull request by ghost**
'e' specifier wasn't working for wxDateTime::ParseFormat in Unicode builds because it was not wrapped in a wxT macro. Fixed now.

### CODE REVIEW

**Comment by vadz** [comment]
This is really surprising, the value of `L'e'` and just `'e'` is the same, so even though we should probably add `wxT()` for consistency (or maybe remove them for consistency from all the other cases...), there must be some different bug here which prevented it from working for you.

Do you have a reproducible test case for the error? If you can include this change as a new test in `tests/datetime/datetimetest.cpp`, it would be great, as it would also test `%e`, which doesn't seem to be done at all currently.

TIA!

**Comment by Blake-Eryx** [comment]
Added a simple unit test.  Yeah, it's weird because I would think that wouldn't be an issue, but for some reason I get an error about an unknown specifier when I use %e in MSW. When I stepped through the code I noted that 'e' was the only one not wrapped in a wxT().

**Comment by paulcor** [comment]
The unit test does not compile, which makes it pretty clear you did not actually run it.

**Comment by vadz** [comment]
Moreover, if I add the test correctly, it not only compiles, but passes, so I think we really need some way of reproducing the problem to understand what's going on here. For now I'm closing this, please reopen if you can reproduce the problem, thanks.

**Pull request closed without merging**
