### PR TITLE
Prevent access beyond end of array at filename[1] by checking length,

### PR DESCRIPTION
**Pull request by owenwengerd-octave**

### CODE REVIEW

**Comment by vadz** [comment]
Sorry, I don't think this is correct as this makes `wxIsAbsolutePath("\\")` false under MSW.

There is definitely a bug here, but it needs to be fixed slightly differently and, ideally, with a unit test checking for the fix. Could you please update this PR to do it? TIA!

**Comment by owenwengerd-hexagon** [comment]
I thought that "\\" should return false, otherwise it would have been included in the preceding condition. Sorry, I do not have time to add a unit test or clean it up.

**Comment by vadz** [comment]
`\` is an absolute path under MSW and the current code does handle it correctly in
```
        if (filename[0] == wxT('\\') || (wxIsalpha (filename[0]) && filename[1] == wxT(':')))
            return true;
```
block, so applying this as is would introduce a regression and so can't be done, sorry.

**Comment by owenwengerd-hexagon** [comment]
You are correct.

**Pull request closed without merging**
