### PR TITLE
Implement retrieval of wxVariant based on the index value

### PR DESCRIPTION
**Pull request by oneeyeman1**
This PR should take care of the trac ticket 9904.

I added the documentation, got rid of the extra function as Vadim suggested and fix the case sensitivity.

Please review and apply (given that the build passes).

Also, please check the documentation - for English grammar and spelling before applying.

### CODE REVIEW

**Comment by PBfordev** [comment]
Hi, my two cents:
What are the assumptions of this operator: must there be exactly one `wxVariant` with `name` in the list? This limit is not documented, the proposed code implementation (a) returns the first one if there are several `wxVariant`s with `name` or (b) asserts if there is none.

I believe that proposed code for the operator could be optimized and simplified e.g. by doing the (case-insensitive as suggested in the ticket) name comparison inside the loop (still slow though)
```cpp
    for ( size_t n = 0; n < GetCount(); ++n )
    {
        if ( name.IsSameAs(this[n].GetName(), false) )
            return operator[](n);            
    }
```
TBH, I do not find such operator very useful: I would guess that `wxVariant` is usually not used similarly to e.g. `std::map`. IMO, if this is found useful perhaps it would be better implemented as some kind of `Find()` method instead of the `operator[]` but there is not even a find method searching for value...

**Comment by oneeyeman1** [comment]
@PBfordev 
> 
> 
> Hi, my two cents:
> What are the assumptions of this operator: must there be exactly one `wxVariant` with `name` in the list? This limit is not documented, the proposed code implementation (a) returns the first one if there are several `wxVariant`s with `name` or (b) asserts if there is none.
> 
> I believe that proposed code for the operator could be optimized and simplified e.g. by doing the (case-insensitive as suggested in the ticket) name comparison inside the loop (still slow though)
> 
> ```c++
>     for ( size_t n = 0; n < GetCount(); ++n )
>     {
>         if ( name.IsSameAs(this[n].GetName(), false) )
>             return operator[](n);            
>     }
> ```
> 
> TBH, I do not find such operator very useful: I would guess that `wxVariant` is usually not used similarly to e.g. `std::map`. IMO, if this is found useful perhaps it would be better implemented as some kind of `Find()` method instead of the `operator[]` but there is not even a find method searching for value...

To tell you the truth, I didn't try to use either wxVariant or this patch/ticket.

But I would be curious what Vadim has to say about it.
Maybe there some cases to use such function?

But thinking more about that - I'd also implement this functionality in terms of Find(). At least this way we can differentiate between case sensitivity.

So lets wait and see if/when Vadim will chime in...

**Comment by vadz** [comment]
I don't really know why do we need this and the implementation looks weird: why would we want to construct a temporary array instead of scanning the list directly?

Please reopen if anybody has any good use case for this, otherwise this doesn't seem useful.

**Comment by oneeyeman1** [comment]
@vadz,
> 
> 
> I don't really know why do we need this and the implementation looks weird: why would we want to construct a temporary array instead of scanning the list directly?
> 
> Please reopen if anybody has any good use case for this, otherwise this doesn't seem useful.

I presume that the ticket should be closed as well?

**Pull request closed without merging**
