### PR TITLE
3.2 proposed backports

### PR DESCRIPTION
**Pull request by vadz**

### CODE REVIEW

**Comment by MaartenBent** [comment]
what about
4f6aa5aee9dc9388b5591b5b05fbe1da4f459991 Merge branch 'print-preview-hidpi'
451772530c670b91f06c77e84198898700645091 Fix typo in wxDEFINE_EVENT macro name in the documentation
8e604926c3a726c93b2df2c162be57b94a10cb61 Fix wrongly recreating wxComboBox in disabled state in wxMSW
0ccf6813d2154b68622a12664fef588145fee208 Avoid expanding the window size by too much on DPI change
94d738dda9ab6dbaabd7f2ed30f561d648494e29 Improve web view Edge error handling
1fef34d71c0f46c6584c502a31d444ca3b4b6063 Fix web view Edge handler crash
70667fc8ab012fc4ab63d187062e5a28834dc5fc Include wxrc.exe in the 64-bit wxMSW MSVC binary package

**Comment by vadz** [comment]
> what about

Thanks, some of those have been already applied to 3.2:

> [4517725](https://github.com/wxWidgets/wxWidgets/commit/451772530c670b91f06c77e84198898700645091) Fix typo in wxDEFINE_EVENT macro name in the documentation 

1d32868d3646fcd16d6d0159d381b3f7bef8ff1b

> [70667fc](https://github.com/wxWidgets/wxWidgets/commit/70667fc8ab012fc4ab63d187062e5a28834dc5fc) Include wxrc.exe in the 64-bit wxMSW MSVC binary package

4cef9529db9f1d9b1d61631369d580244f4b03e2

> [8e60492](https://github.com/wxWidgets/wxWidgets/commit/8e604926c3a726c93b2df2c162be57b94a10cb61) Fix wrongly recreating wxComboBox in disabled state in wxMSW 

ac29c30b8af9c15a6ca55c826fc7b34c632f7385

Others should be applied (they have/had the backport-3.2 label), but wanted to wait for a bit longer to see if any new problems are found before doing it, this includes

> [0ccf681](https://github.com/wxWidgets/wxWidgets/commit/0ccf6813d2154b68622a12664fef588145fee208) Avoid expanding the window size by too much on DPI change 
> [4f6aa5a](https://github.com/wxWidgets/wxWidgets/commit/4f6aa5aee9dc9388b5591b5b05fbe1da4f459991) Merge branch 'print-preview-hidpi'

But maybe I should be more daring and apply them already...

Finally, I don't know if it's worth maintaining Edge backend in 3.2 or if it's not going to be able to follow the evolution of Edge itself there anyhow.

> [94d738d](https://github.com/wxWidgets/wxWidgets/commit/94d738dda9ab6dbaabd7f2ed30f561d648494e29) Improve web view Edge error handling
> [1fef34d](https://github.com/wxWidgets/wxWidgets/commit/1fef34d71c0f46c6584c502a31d444ca3b4b6063) Fix web view Edge handler crash

@TcT2k Should I backport them too?

**Comment by TcT2k** [comment]
> Finally, I don't know if it's worth maintaining Edge backend in 3.2 or if it's not going to be able to follow the evolution of Edge itself there anyhow.
> 
> > [94d738d](https://github.com/wxWidgets/wxWidgets/commit/94d738dda9ab6dbaabd7f2ed30f561d648494e29) Improve web view Edge error handling
> > [1fef34d](https://github.com/wxWidgets/wxWidgets/commit/1fef34d71c0f46c6584c502a31d444ca3b4b6063) Fix web view Edge handler crash
> 
> @TcT2k Should I backport them too?

As the 3.2 doesn't include web handler support for edge these fixes wouldn't apply. Handler support in Edge is tied to the addition of `wxWebViewHandler::StartRequest()` and related classes, so backporting this would introduce quite a few changes to 3.2.

**Comment by vadz** [comment]
I've backported all the other fixes marked as such in this branch now, with the exception of #23128 for which I'd like to get at least some testing in master first.

**Pull request merged**
