### PR TITLE
CMake: Add GTK Printing support

### PR DESCRIPTION
**Pull request by MaartenBent**
See #22745

And show the extra toolkit options in the CMake summary, fix using libnotify and gnomevfs with gtk3 and fix some unused parameter warnings when using gtk2 or gtk3 on Windows.

### CODE REVIEW

**Comment by vadz** [comment]
Thanks!

This should be fine to backport to 3.2 too, shouldn't it?

**Comment by MaartenBent** [comment]
Yes, I guess it is fine to backport.

Or can this cause ABI issues if suddenly the library has GTK printing support (or when it starts using libnotify)? If so, maybe there should be a note in the changelog that these options should be disabled to keep compatibility.

**Comment by MaartenBent** [comment]
Do you still want to backport this? And close #22745?

**Comment by vadz** [comment]
I'm not sure... It looks like GTK print support doesn't even affect the ABI, but libnotify does and, in theory, it could indeed be unexpected that rebuilding 3.2.1 libraries using the same commands as 3.2.0 results in an incompatible binary. OTOH I don't even know if our ABI guarantee covers anything other than the binaries that we produce ourselves, so maybe it's not really a problem?

**Comment by MaartenBent** [comment]
Yes, if the ABI is only for our libraries than we can backport this.
We could still add a note to the changelog so other packagers are aware of it (CMake GTK3 build on Linux now correctly searches for, and enables, libnotify. For 3.2.0 behaviour, build with `-DwxUSE_LIBNOTIFY=0`.

**Pull request merged**
