### PR TITLE
Fixes for display information refreshing under MSW

### PR DESCRIPTION
**Pull request by vadz**
This replaces and extends https://github.com/wxWidgets/wxWidgets/pull/1281

### CODE REVIEW

**Comment by dasimx** [comment]
> However, at the risk of missing something else again, why do we need to attach the factory pointer to the window when we can just call (static) wxDisplay::InvalidateCache() from there, as we already do?

Sure, you can do that, if you feel it's simpler.

> I've just tested under MSW 10.0.16299.785 

Looks like an older Win 10 version? I'm getting "Version	10.0.17763 Build 17763" with the system information app.

> and don't get any WM_SETTINGSCHANGE messages there when a UAC prompt is shown neither (I just try to run cmd.exe as administrator from the start menu to trigger it). I have no idea why do you get it and I don't, would you have any ideas?

Yes, I had a look at the "lParam" parameter, which is documented to be a "pointer to a string that indicates the area containing the system parameter that was changed". I'm getting:
`(wchar_t*)lParam	0x000000c9878ff128 L"ImmersiveColorSet"`

And indeed the WM_SETTINGSCHANGE is related to the "automatic background color" option that is set for my desktop theme: https://support.microsoft.com/en-us/help/17144/windows-10-change-desktop-background

When I disable the automatic color picking, I'm also not getting any WM_SETTINGSCHANGE anymore during UAC and log off.

**Comment by vadz** [comment]
OK, thanks for debugging this, at least this mystery is explained now. The only remaining problem is that I think that if you disconnect a display while the UAC prompt is being shown, we're still going to keep the old and out of date cached information, as enumerating displays will fail. It would be great to find a way to make it work and I wonder what would happen if we used `WindowHDC` instead of `ScreenHDC ` here? Of course, we need a window for the former and I'm not sure if `m_hiddenHwnd` would work (because it's, well, hidden). Could you please check if it works for you? And if it doesn't, could the (hopefully visible) `wxTheApp->GetTopWindow()` be used here?

**Comment by dasimx** [comment]
A DC for a particular window doesn't work during UAC (== returns 0 displays) at least with all the windows I've tried:

> WindowHDC dc(m_hiddenHwnd);
=> 0 displays

> WindowHDC dc(::GetDesktopWindow());
=> 0 monitors

> WindowHDC dc(wxTheApp->GetTopWindow()->GetHWND());
=> 1 monitor (??? but I have 2 monitors set up)

The only code that works reliably in all cases is
`EnumDisplayMonitors(NULL, NULL, MyInfoEnumProc, 0);`

So we chould just redetermine the HDC for each monitor. At least this is documented to work:
> https://docs.microsoft.com/en-us/windows/desktop/gdi/hmonitor-and-the-device-context
Or, you can use the device name from the GetMonitorInfo function to create a DC with CreateDC.

The following patch works for me in all cases including UAC + log off screen:
https://github.com/vadz/wxWidgets/compare/msw-display-refresh...dasimx:patch-3

**Comment by vadz** [comment]
Thanks for your fix! I've applied it with some very minor changes and also reverted the previous work around which shouldn't be necessary any more.

I've also made another change which is supposed to avoid refreshing the display cache unnecessarily, please see the last commit (3959810d42fd3d0cd8d3a8bafa346fcfa5ed8e23). AFAICS this should still work for any real changes, but, as always, I'd be grateful if you could please test this too and let me know if you see any problems with it.

If not, I'll merge this PR soon. Thanks again!

**Comment by dasimx** [comment]
Looks good, and also works in my tests. Also good idea with SPI_SETWORKAREA! Just one minor detail: 

The ` ::CreateDC(NULL, monInfo.szDevice, NULL, NULL); ` call seems to work for me, but after reading the docs (https://docs.microsoft.com/en-us/windows/desktop/api/wingdi/nf-wingdi-createdcw) more closely it seems this should be ` ::CreateDC(monInfo.szDevice, NULL, NULL, NULL); ` instead. The function parameter names are certainly confusing, but their descriptions are relatively unambiguous:

```
pwszDriver
[...] or the name of a specific display device

````

````
pwszDevice

If lpszDriver is DISPLAY or the device name of a specific display device, 
then lpszDevice must be NULL or that same device name.
````

In my tests this type of calling CreateDC() works the same, but it is probably more conformant. A cursory Google search found two uses of CreateDC() of the latter form. What do you think?

**Comment by vadz** [comment]
I think `CreateDC()` is fine as written: `NULL` driver means "DISPLAY" by default and device argument selects a particular display in this case. I.e. it looks more logical to do it like this to me, while the effect should be exactly the same in practice, so I'll just merge it like this.

Thanks for the fixes and testing!

**Pull request merged**
