### PR TITLE
Use current wxTranslations instance instead of wxLocale in msw/msgdlg.cpp

### PR DESCRIPTION
**Pull request by utelle**
> [...] but to answer the question about the message box labels, I think that we should check if we have an active (i.e. non-null) `wxTranslations` object and use it if we do instead of checking for the locale at all, what do you think?

IMHO this is a very reasonable approach. Therefore I used the current `wxTranslations` instance  via `wxTranslations::Get()` insteade of `wxLocale` in `msw/msgdlg.cpp`. If the current `wxTranslations` instance is defined, its translations will be used for the default buttons.

### CODE REVIEW

**Comment by vadz** [comment]
Thanks! I'm applying this, but AFAICS only the last commit here is needed, so I've just cherry-picked that one, please let me know if I'm missing something.

**Comment by utelle** [comment]
> Thanks! I'm applying this, but AFAICS only the last commit here is needed, so I've just cherry-picked that one, please let me know if I'm missing something.

Yes, only the last commit was new and needed.

GitHub attributed the PR https://github.com/wxWidgets/wxWidgets/pull/22375 with "Closed with unmerged commits" (and retained the already merged commits), and I see now the same message for this PR (and again I see all commits as unmerged). Probably I should have synced the branch with master _before_ applying my last commit.

**Comment by vadz** [comment]
Just FYI, this is because I squash merged the other PR, i.e. applied both of the commits as one to master. The changes are exactly the same, but the commits are not, which is why the branch was closed with unmerged commits. Generally speaking, you should always rebase your working branch on master if part of its changes had been already merged there.

**Comment by utelle** [comment]
Thanks for the clarifications.

**Pull request closed without merging**
