### PR TITLE
Remove wxT() and _() macros from dialog sample.

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by Blake-Eryx** [comment]
There are 5 wxT() that I had to keep because they get assigned to wxChar* variables.  Those get mapped to wchar_t* and thus need the 'L' that wxT gets expanded to in this case. So I guess wxT() isn't entirely without use.

**Comment by vadz** [comment]
Those `wxChar*`s should be changed to either `wxString` or just `char*` (if we had anything but ASCII text in them, they should have been changed to `wchar_t*` instead). And `wxT()` is really useless/confusing, for wide char constants `L` prefix should be used (as in `L"Hello world"`).

**Comment by Blake-Eryx** [comment]
Got it. I changed the wxChar* stuff to wxString, so all all wxT() are gone.

I also changed mentions of "wxWindows license" to "wxWidgets license", I assume that's the correct thing to do, right?

Finally, I removed all _() macros also. I'll try to do that to the other samples as time permits (except for "internat").

**Comment by vadz** [comment]
> I also changed mentions of "wxWindows license" to "wxWidgets license", I assume that's the correct thing to do, right?

No, sorry. The licence is called "wxWindows licence" and can't be just renamed (as with any legalese). This needs to be left alone.

**Comment by Blake-Eryx** [comment]
Got it, thanks. Changed back to wxWindows licence.

**Comment by vadz** [comment]
Applied, thanks!

BTW, is it normal that there is no email address associated with your commits? Consider using `git config --global user.email <whatever>` to set it.

**Pull request closed without merging**
