### PR TITLE
CMake: wxBUILD_USE_STATIC_RUNTIME is available for GCC now

### PR DESCRIPTION
**Pull request by Deamhan**
partial fix of https://trac.wxwidgets.org/ticket/18436

### CODE REVIEW

**Comment by PBfordev** [comment]
I am not really using GCC/MinGW but I was curious about this. What are the expectations for this patch: the executables should not need any GCC DLL at all?

I tried this patch with `mingw-w64 i686-8.1.0-posix-dwarf-rt_v6-rev0 ` (`CMAKE_BUILD_TYPE=Release`, `wxBUILD_SHARED=OFF`) and `libwinpthread-1.dll` was still required to run samples. So I googled a bit and found [this](https://stackoverflow.com/questions/13768515/how-to-do-static-linking-of-libwinpthread-1-dll-in-mingw). 

When I just added `-static` to `CMAKE_CXX_FLAGS` in cmake-gui (CMake v3.14.3) with the unmodified trunk CMakefile, the library and samples built and I was able to run samples without copying any DLLs. However, I know next to nothing about GCC and CMake, so I have no idea what are the downsides of this...

**Comment by Deamhan** [comment]
I don't use mingw or clang on windows (generated code much slower then msc++ if exceptions is enabled) so I don't know much about it. But about gcc it is easy: all used code from _libstdc++_ will be built inside you executable, so you will be free from limitation of installed _libstdc++_ version. In my practice it is good to inline all that you can, so my executables depends on _glibc/pthread_ only. It is real hell to support different versions of linux based systems, especially _CentOS_ (I hate it, the most outdated package versions and very long life). So static linking with _libstdc++_ will really simplify support of such systems.

**Comment by MaartenBent** [comment]
With msys2/mingw64 I need to use `-static -Wl,--allow-multiple-definition`.
Maybe you can modify it to:
```cmake
if (MINGW)
    set(STATIC_LINKER_FLAGS " -static -Wl,--allow-multiple-definition")
else
    set(STATIC_LINKER_FLAGS " -static-libgcc -static-libstdc++")
endif()
```

**Comment by Deamhan** [comment]
> " -static -Wl,--allow-multiple-definition"
multiple-definition is almost always an error, may be symbol should be marked as _static_? How it is related with static linking?

**Comment by Deamhan** [comment]
I have reproduced migw building problem and found https://stackoverflow.com/questions/11267877/mingw-multiple-definition-of-unwind-resume . This hack resolved the issue. I will apply it.

**Comment by Deamhan** [comment]
Here all is done

**Comment by Deamhan** [comment]
All recommendations was applied.

**Review by MaartenBent — APPROVED** [review]

**Comment by vadz** [comment]
Sorry, I feel pretty uncomfortable about using `--allow-multiple-definition`, this could hide real problems too.

Could we perhaps use it for only the affected MinGW versions? Or do all of them suffer from this problem?

**Comment by MaartenBent** [comment]
> Could we perhaps use it for only the affected MinGW versions? Or do all of them suffer from this problem?

I don't think CMake has or exposes information about the MinGW version. And only some distributions seem to have this problem, @PBfordev does not seem to need it. I only got the warning when using shared libraries with static runtime, not when using static libraries.

I'm fine with removing it here, and call CMake with the required linker flags myself.

**Comment by vadz** [comment]
> I don't think CMake has or exposes information about the MinGW version.

I thought we could do just about anything with CMake at configure-time?

> And only some distributions seem to have this problem, @PBfordev does not seem to need it. I only got the warning when using shared libraries with static runtime, not when using static libraries.
> 
> I'm fine with removing it here, and call CMake with the required linker flags myself.

I'd be fine too, perhaps with a warning/note saying that if you get link errors you should add it. I'd also be fine enabling it only for MinGW/gcc versions known to need it. But I'd prefer not to enable it by default.

**Comment by Deamhan** [comment]
@vadz, I will add checking if we really need it.

**Comment by Deamhan** [comment]
We have some problems with al least _wxbase_ export. In mingw case _wxbase_ depends from _libgcc_ and after linking it starts exporting _libgcc_ symbols, that is not normal - we should suppress it. If we print _wxbase_ mingw dll export we will see pthread symbols that is not normal too (we export all symbols from imported static libraries).  It causes issue with multiple symbol definition.

```
In function 'Unwind_Resume':
C:/mingw810/src/gcc-8.1.0/libgcc/unwind.inc:230: multiple definition of '_Unwind_Resume'
../../lib/gcc_dll/libwxbase31u.a(d001619.o):(.text+0x0): first defined here
collect2.exe: error: ld returned 1 exit status
mingw32-make.exe[2]: *** [libs\xml\CMakeFiles\xml.dir\build.make:127: lib/gcc_dll/wxbase313u_xml_gcc_custom.dll] Error 1
```
```

Microsoft (R) COFF/PE Dumper Version 14.16.27032.1
Copyright (C) Microsoft Corporation.  All rights reserved.


Dump of file C:\wxWidgets\mingw64-32\lib\gcc_dll\d001619.o

File Type: COFF OBJECT

COFF SYMBOL TABLE
...
006 00000000 SECT1  notype       External     | __Unwind_Resume
007 00000000 SECT3  notype       External     | __imp___Unwind_Resume
...

```
```
PS C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\bin\Hostx86\x86> .\dumpbin.exe /EXPORTS "C:\wxWidgets\mingw64-32\lib\gcc_dll\wxbase313u_gcc_custom.dll" | Where {$_ -like "*Unwind*"}
       ...
       1619  652 000F2290 _Unwind_Resume
       ...
```
I would like to hear your opinion on this issue.

**Comment by Deamhan** [comment]
I excluded libgcc_eh.a from export, but we should exclude all known runtime libraries from it. Tomorrow I will see export on linux.

**Comment by Deamhan** [comment]
I have excluded _pthread_ symbols too. I haven't seen other libs for unexpected exports, but maybe we should exclude more static  libs. And I tested only one _MinGW_ installation - I don't know is it enough excluded libs in general.

**Comment by Deamhan** [comment]
As I see all issues has been fixed. Please review.

**Comment by vadz** [comment]
Thanks for your work on this, I'm absolutely fine with applying this as is, but I wonder about how do we end up exporting `libgcc` and friends symbols automatically -- do we use auto-exporting with CMake? Normally, we should be only exporting the explicitly exported (using `WXDLLIMPEXP_XXX`) symbols. I.e. I wonder if we shouldn't be using `--exclude-libs ALL`? Or maybe there is some way to disable auto-export with CMake?

It would be really better to avoid exporting tons of private functions and classes from wx DLLs, this should make smaller and linking/loading them faster.

**Comment by Deamhan** [comment]
About `--exclude-libs ALL` - I tested it before excluding explicit libraries and I had a linker failure (may be my mingw is broken - I don't know). With explicit libs all was fine. As I read from man it is normal to LD to export all public symbols, but on linux we don't have such problem. I will update my mingw to the latest version and try to test it again.

**Comment by Deamhan** [comment]
Just a fragment of build log:
```
CMakeFiles\net.dir/objects.a(sckaddr.cpp.obj):sckaddr.cpp:(.text$_ZN15wxArgNormalizerItEC2EtPK14wxFormatStringj[__ZN15wxArgNormalizerItEC2EtPK14wxFormatStringj]+0x79): undefined reference to `wxTrapInAssert'
CMakeFiles\net.dir/objects.a(sckaddr.cpp.obj):sckaddr.cpp:(.text$_ZN15wxArgNormalizerItEC2EtPK14wxFormatStringj[__ZN15wxArgNormalizerItEC2EtPK14wxFormatStringj]+0x93): undefined reference to `wxTrapInAssert'
CMakeFiles\net.dir/objects.a(sckaddr.cpp.obj):sckaddr.cpp:(.rdata$_ZTV13wxIPV6address[__ZTV13wxIPV6address]+0x14): undefined reference to `wxObject::CreateRefData() const'
CMakeFiles\net.dir/objects.a(sckaddr.cpp.obj):sckaddr.cpp:(.rdata$_ZTV13wxIPV6address[__ZTV13wxIPV6address]+0x18): undefined reference to `wxObject::CloneRefData(wxRefCounter const*) const'
CMakeFiles\net.dir/objects.a(sckaddr.cpp.obj):sckaddr.cpp:(.rdata$_ZTV13wxIPV4address[__ZTV13wxIPV4address]+0x14): undefined reference to `wxObject::CreateRefData() const'
CMakeFiles\net.dir/objects.a(sckaddr.cpp.obj):sckaddr.cpp:(.rdata$_ZTV13wxIPV4address[__ZTV13wxIPV4address]+0x18): undefined reference to `wxObject::CloneRefData(wxRefCounter const*) const'
CMakeFiles\net.dir/objects.a(sckaddr.cpp.obj):sckaddr.cpp:(.rdata$_ZTV13wxSockAddress[__ZTV13wxSockAddress]+0x14): undefined reference to `wxObject::CreateRefData() const'
CMakeFiles\net.dir/objects.a(sckaddr.cpp.obj):sckaddr.cpp:(.rdata$_ZTV13wxSockAddress[__ZTV13wxSockAddress]+0x18): undefined reference to `wxObject::CloneRefData(wxRefCounter const*) const'
CMakeFiles\net.dir/objects.a(sckaddr.cpp.obj):sckaddr.cpp:(.rdata$_ZTV11wxIPaddress[__ZTV11wxIPaddress]+0x14): undefined reference to `wxObject::CreateRefData() const'
CMakeFiles\net.dir/objects.a(sckaddr.cpp.obj):sckaddr.cpp:(.rdata$_ZTV11wxIPaddress[__ZTV11wxIPaddress]+0x18): undefined reference to `wxObject::CloneRefData(wxRefCounter const*) const'
CMakeFiles\net.dir/objects.a(sckaddr.cpp.obj):sckaddr.cpp:(.text$_ZN12wxMBConvUTF8D1Ev[__ZN12wxMBConvUTF8D1Ev]+0xa): undefined reference to `vtable for wxMBConvUTF8'
CMakeFiles\net.dir/objects.a(sckfile.cpp.obj):sckfile.cpp:(.text+0xd5): undefined reference to `wxURI::Unescape(wxString const&)'
CMakeFiles\net.dir/objects.a(sckfile.cpp.obj):sckfile.cpp:(.text+0xf0): undefined reference to `wxFileInputStream::wxFileInputStream(wxString const&)'
CMakeFiles\net.dir/objects.a(sckfile.cpp.obj):sckfile.cpp:(.text+0x197): undefined reference to `wxClassInfo::~wxClassInfo()'
```
excluding ALL totally breaks linking process, at least on my machine. "White list" is the best I has found.

**Comment by Deamhan** [comment]
I think it would be the best option to add all as is and check project for such auto exports in future because of it is not directly related with original static linkage feature.

**Comment by vadz** [comment]
I really don't have to look at this in the details right now, but something definitely seems wrong with the CMake build as wxNet DLL should reference `__imp_XXX` symbols and not just `XXX`. Are the various `WXMAKINGDLL_XXX` and `WXUSINGDLL` defined correctly in this build?

Also, I still think either CMake (by default) or we (explicitly) must be doing something to auto-export everything because this is definitely _not_ the default under MSW (it is under Linux/ELF systems, where the default visibility is "visible", and you need to explicitly use `-fvisibility=hidden`, as we do there).

**Comment by Deamhan** [comment]
about __imp_XXX: I will see what we have in Visual Studio case. If symbols is exported by something like `__declspec(dllexport)` it would be mangled (I don't know gcc mangling rules, but its definitely don't match visual studio one), but by using _.def_ file we can export symbols as we name it. But we will have trubles with function overloading and other things.

**Comment by vadz** [comment]
gcc still uses `__imp_` prefix for the symbols in import libraries, this is orthogonal to mangling (e.g. it applies to extern "C" functions also).

We definitely don't want to use `.def` files, this is unmaintainable for any C++ project and especially one of this size. But our DLL export declaration macros should work (see `include/wx/dlimpexp.h`).

**Comment by Deamhan** [comment]
For now I don't cleary understand what goes wrong in -Wl,--exclude-libs ALL case, but it looks like functions like `wxObject::CreateRefData() const` belongs some static library...

**Comment by vadz** [comment]
`wxObject::CreateRefData()` is in wxBase, and should be declared as DLL-exported when building it and as DLL-imported when consuming wxBase in the other code (including the other wx DLLs). It looks like this doesn't happen in CMake build, however.

**Comment by Deamhan** [comment]
Maybe I'm wrong but from lib/gcc_dll/mswu/wx/setup.h:
`#define HAVE_VISIBILITY 1`

and from include/wx/dlimpexp.h:
```
#if defined(HAVE_VISIBILITY)
#    define WXEXPORT __attribute__ ((visibility("default")))
#    define WXIMPORT __attribute__ ((visibility("default")))
#elif defined(__WINDOWS__)
    /*
       __declspec works in BC++ 5 and later as well as VC++.
     */
#    if defined(__VISUALC__) || defined(__BORLANDC__)
#        define WXEXPORT __declspec(dllexport)
#        define WXIMPORT __declspec(dllimport)
    /*
        While gcc also supports __declspec(dllexport), it created unusably huge
        DLL files in gcc 4.[56] (while taking horribly long amounts of time),
        see http://gcc.gnu.org/bugzilla/show_bug.cgi?id=43601. Because of this
        we rely on binutils auto export/import support which seems to work
        quite well for 4.5+. However the problem was fixed in 4.7 and later and
        not exporting everything creates smaller DLLs (~8% size difference), so
        do use the explicit attributes again for the newer versions.
     */
#    elif defined(__GNUC__) && \
        (!wxCHECK_GCC_VERSION(4, 5) || wxCHECK_GCC_VERSION(4, 7))
        /*
            __declspec could be used here too but let's use the native
            __attribute__ instead for clarity.
        */
#       define WXEXPORT __attribute__((dllexport))
#       define WXIMPORT __attribute__((dllimport))
#    endif
#elif defined(__CYGWIN__)
#    define WXEXPORT __declspec(dllexport)
#    define WXIMPORT __declspec(dllimport)
#endif
```

and according to https://gcc.gnu.org/wiki/Visibility HAVE_VISIBILITY should be 0 for mingw. May be I have seen wrong _setup.h_? Visibility attribute is not supported under windows, may be we should swap `#if` and `#elif` ? From article:
```
    #ifdef __GNUC__
      #define DLL_PUBLIC __attribute__ ((dllexport))
    #else
      #define DLL_PUBLIC __declspec(dllexport) // Note: actually gcc seems to also supports this syntax.
    #endif
```
so `__attribute__ ((dllexport))` should be used on MinGW (I didn't find using such attributes in wxWidgets code).

**Comment by MaartenBent** [comment]
> HAVE_VISIBILITY should be 0 for mingw

Looks like it is incorrectly initialized [here](https://github.com/wxWidgets/wxWidgets/blob/master/build/cmake/setup.cmake#L82).

I think it should get `set(HAVE_VISIBILITY FALSE)` before the checks. And maybe set `wxUSE_VISIBILITY` to `OFF` for mingw? I'm not able to test this myself today.

**Comment by Deamhan** [comment]
@MaartenBent, if I'm correct and it is setup.h used in building process. But if we modify _dlimpexp.h_ we will solve this problem maybe in better way.  There is no `#ifndef HAVE_VISIBILITY` in setup.h and `wx_option(wxUSE_VISIBILITY "use of ELF symbols visibility")` sounds strange for systems that doesn't support ELF. It would be great to hear @vadz's opinion...

**Comment by Deamhan** [comment]
Done! `--exclude-libs=ALL` works fine now (and visibility option was disabled on windows). Please review and merge.

**Comment by MaartenBent** [comment]
Works great with GCC and Clang on Windows now. For me, `--exclude-libs=ALL` isn't even needed anymore after disabling `wxUSE_VISIBILITY`.

It also exposes some new `-Wignored-attributes` warnings during compiling, that seem quite harmless, like:
`wx/unichar.h:325:19: warning: 'wxUniChar::wxUniChar' redeclared inline; 'dllimport' attribute ignored [-Wignored-attributes]`

**Comment by Deamhan** [comment]
Yes, you are right, done. Export of dlls looks good even without additional attribute. So exporting all symbols was just a gcc reaction to missing "normal" export... About warnings: it is not a good idea to fix it in CMake related PR, but this warnings is indirect indication that all works as expected.

**Comment by vadz** [comment]
Thanks for your work and the fixes, I'm going to merge this already, even if there are perhaps still some improvements remaining.

**Pull request merged**
