### PR TITLE
wxDropTarget::GetMatchingPair() implemented for macOS

### PR DESCRIPTION
**Pull request by valid-ptr**

### CODE REVIEW

**Comment by vadz** [comment]
Thanks, AFAICS this is needed to make dnd work in wxDVC which seems to be the only place where this confusingly named and undocumented function is used, so making it work is definitely nice.

But the patch seems to duplicate the code of the existing `CurrentDragHasSupportedFormat()`, which is less nice. Ideal would be to either:

1. Refactor the current code so that `CurrentDragHasSupportedFormat()` is simply implemented as `GetMatchingPair() != wxDF_INVALID`.
2. Or even, and arguably better , make `CurrentDragHasSupportedFormat()` public, implement it in the other ports too, and use it in wxDVC.

It would be really nice to do at least (1) to avoid code duplication. Could you please do it? TIA!

**Comment by valid-ptr** [comment]
Thanks, Vadim!

What do you think about:

```
bool wxDropTarget::CurrentDragHasSupportedFormat()
{
    return (GetMatchingPair() != wxDF_INVALID) || m_dataObject->CanReadFromSource(m_currentDragPasteboard);
}
```
_OR_

Should we check `m_currentDragPasteboard` in the **GetMatchingPair()** function?

**NOTE**:
See `bool wxDataObject::CanReadFromSource( wxOSXDataSource * source ) const` in `src/osx/carbon/dataobj.cpp`

**Comment by vadz** [comment]
It looks like we should definitely be using `CanReadFromSource()` in `GetMatchingPair()` as, if I'm reading the code correctly, otherwise we'd never return anything valid from there for the drags from outside the application. I could be wrong because I don't know this code at all and I'd really appreciate if @csomor could correct me in this case, but it seems like `wxDropSource::GetCurrentDropSource()` only returns something non-null if it's called from inside our own `wxDropSource::DoDragDrop()`, as this is the only place where `gCurrentSource` is set.

So, if we want to be consistent with the other ports, in which `GetMatchingPair()` returns something valid for the outside drops too, we indeed need to check `m_currentDragPasteboard` in it.

Also, looking at the code duplication between `wxDropTarget::CurrentDragHasSupportedFormat()` and `wxDataObject::CanReadFromSource()`,  it could be nice to make the latter a template, so it would be usable with both `wxOSXDataSource` and `wxDataObject`, and make the former just use `m_dataObject->CanReadFromSource(data)` instead of rewriting the same loop there.

**Comment by csomor** [comment]
Thanks, I'll look at that

**Comment by csomor** [comment]
@vadz yes you are right, `wxDropSource::GetCurrentDropSource()` is used for 'our own' datasources, a wxDropSource* we can access. A drag from outside has this at NULL, and its native datasource is set using `wxDropTarget::SetCurrentDragSource`

The code loops in both look similar, but they are not really the same, the direction of data access is different, when having a wxDataSource we ask its content what we can GET from it and test whether we can support that, when having the native datasource we ask the target what can be SET and look whether that format is available on the native datasource. 

What could be done is move more code into wxDataObject, add an overload` CanReadFromSource( wxDataObject* )` . But I fear going one step further and templating both direction and source type might make things even less obvious.

**Comment by csomor** [comment]
@vadz

Ok, I've changed the source a little bit, and I now have the following methods in `wxDataObject`

```
    bool CanReadFromSource(wxOSXDataSource *source) const;
    bool CanReadFromSource(wxDataObject *source) const;
```

in order to support also `GetMatchingPair`, I've moved the true implementation into

```
    wxDataFormat GetSupportedFormatInSource(wxOSXDataSource *source) const;
    wxDataFormat GetSupportedFormatInSource(wxDataObject *source) const;
```

and `CanReadFromSource` returns true if `GetSupportedFormatInSource` is not returning wxDF_INVALID

Now my question is whether these two `GetSupportedFormatInSource` should be named `GetMatchingPair` as well, for consistency, although I never understood why the method is called that way without returning a pair ...

Thanks

**Comment by vadz** [comment]
I don't think being consistent with `GetMatchingPair()` is important, as you say, its name doesn't really make sense (I think this is related to some old X/GTK terminology, but I'm not even sure) and it's not documented. But unfortunately wxOSX still has to provide it just to let the code in the generic wxDVC work.

We could add a public, documented function doing the same thing if you think it could be useful, however. `GetSupportedFormatInSource()` looks like a good name (I thought about `GetCommonSupportedFormat()`, but I like your idea of using "source" explicitly in the name and `GetCommonSupportedFormatWithSource()` would be too long, I think), so we could add it to `wxDataObjectBase` itself.

Of course, this won't help with reusing the same code for `wxOSXDataSource` :-( The only solution I see for this is to add a separate `wxDataObjectSourceBase` with just a single `IsSupported()` pure virtual method and derive both `wxDataObjectBase` and `wxOSXDataSource` from it to allow taking `wxDataObjectSourceBase` as argument in the new function. But it would require more work...

**Comment by csomor** [comment]
Thank you, I'll proceed then, another thing that came to my mind, when shuffling code around, was to move code from `wxDropTarget::GetData` as well into a `wxDataObject::ReadFromSource(wxDataObject * source)` would this be ok, or do you see a disadvantage ?

**Comment by vadz** [comment]
No, I don't see any problems with this, thanks!

**Comment by vadz** [comment]
I think Stefan's commit above replaces this PR, so I'm closing it, please let us know if there are still any problems. Thanks!

**Pull request closed without merging**
