### PR TITLE
More CMake build fixes

### PR DESCRIPTION
**Pull request by MaartenBent**
Another round of CMake fixes. 

- Fixed adding samples after some typos in a342582e.

- Support building with GTK3 on Windows (and probably Linux as well). Use the correct source files, and include wxWidgets headers before the toolkit headers. Otherwise the default png headers included in `wxTOOLKIT_INCLUDE_DIRS` are used, resulting in undefined references when linking.
This also requires the GTK fixes from https://github.com/wxWidgets/wxWidgets/pull/750.

- Remove duplicate `wxUSE_IMAGE` option. It is also in `options.cmake`, where all options should be defined.

- Don't enable the dialup sample and `wxUSE_DIALUP_MANAGER` in macOS, `wxDialUpManager` is not implemented.

### CODE REVIEW

**Comment by vadz** [comment]
Thanks! I'm fine with merging this, if @TcT2k doesn't have any objections, I'll do it soon.

**Comment by vadz** [comment]
Also, what's the relationship of this with #750? I.e. should the other one still be applied too or not?

**Comment by MaartenBent** [comment]
#750 should also be applied. It has fixes for GTK2 on Windows, I extended it to GTK3.

**Comment by TcT2k** [comment]
Looks good to me

**Pull request merged**
