### PR TITLE
Update Czech translations

### PR DESCRIPTION
**Pull request by PBfordev**
Just as I did before in 2011 and 2012, I sent my changes to the official wxWidgets Czech translator (Zbyněk Schwarz) to review and submit them. 

I got a reply saying he would do that but four months have passed since then and as I do not want to bother him again I am submitting the changes as I made them.

### CODE REVIEW

**Comment by vadz** [comment]
Thanks for the update, do you know why are there conflicts?

@vslavik Would you like to have a look at this or should I merge it relying just on my own Czech knowledge?

**Comment by pbfordev** [comment]
I have no idea how why the conflict was there but my knowledge of GIT is unfortunaly abysmall. Hopefully it's OK now...

**Comment by vslavik** [comment]
> @vslavik Would you like to have a look at this or should I merge it relying just on my own Czech knowledge?

I'm on Crete now with little time for dev stuff, so I only scanned through it briefly, but from what I could see (most of the diff is `#:` noise) it seems OK to me -- certainly better than not having them in the first place, translations can always be improved upon.

**Comment by vadz** [comment]
Sorry for bothering you during your vacation and thanks for taking a look nevertheless.

And thanks to @pbfordev for the translations, of course!

**Pull request merged**
