### PR TITLE
SoC14 wxWebViewChromium improvements and merge

### PR DESCRIPTION
**Pull request by TcT2k**
I've rebased the work from @hokein and @sjlamerton in #15 to the current master.

Please first try building using **CMake**  it will automatically download the required CEF libraries. Just configure with `wxUSE_WEBVIEW_CHROMIUM=ON` and you should be able to build `webviewsample_chromium`.

The current implementation has a few missing features documented [here](https://github.com/TcT2k/wxWidgets/blob/chromium/interface/wx/webview_chromium.h) in the documentation.

I've tested the following compile platform combinations successfully with [CEF 3.3282.1733.g9091548](http://opensource.spotify.com/cefbuilds/index.html):
* Visual Studio 2017 on Windows 10
  * With CMake (by enabling `wxUSE_WEBVIEW_CHROMIUM` build setting)
  * vc15 solution file and `samples/webview/webview.vcxproj` enabled `wxUSE_WEBVIEW_CHROMIUM` in header
* XCode 9 on macOS 10.12
  * With CMake
  * Via configure
* Ubuntu 14.04 with CMake an Ninja (builds but see open ToDos)

Open Issues:
- Open ToDos I wont be able to fix/**need help** with
  - [ ] Fix Linux GTK build (need correct handle when calling CEF `SetAsChild()` [here](https://github.com/TcT2k/wxWidgets/blob/4ee5b50401a37867530b1d94ce4fd820802c700a/src/common/webview_chromium.cpp#L267))
  - [ ] Figure out bake file issues (running `bakefile_gen` creates additional and unneeded project files `build/msw/wx_vc[7|8|9]_webview[dll|lib].vcproj`)
  - [ ] Figure out correct `install_name_tool` calls for the autoconf built `webviewchromium_sample` on macOS
  - [ ] Fix doc.zip loading path in _webview_ sample for all build tools. It currently only works with autoconf based builds. (This is not wxWebViewChromium specific)
- [x] Unify _webview_chromium_ and _webview_ sample source code
- [x] Remove CEF headers from _cef_chromium.h_
- [x] Update documentation
- [x] Update macOS helper process creation
- [x] Cleanup interface where possible
  - [x] Unify startup function accross platforms
  - [x] Integrated CEF message loop into implementation to not required _DoCEFWork_ calls
  - [x] Move startup/shutdown to _wxModule_
- [x] Include sample manifest to mark sample as Win10 compatible
- [x] Integrate with CMake
- [x] Investigate automatic build of _cef_dll_wrapper_ from CMake. The CEF client library is now CMake based anyway

### CODE REVIEW

**Comment by TcT2k** [comment]
@PBfordev Thanks for testing. I've had the same issue and marking the application as Win8 and Win10 compatible (with the correct GUIDs) fixed `FATAL:dwrite_font_proxy_init_impl_win.cc` and allowed it to start the GPU process. I'll include a suitable manifest in sample.

**Comment by PBfordev** [comment]
Thanks for looking into this.

I tried to run the the same debug sample as in my previous post on Windows 7 and it seemed to work (aside from the Find issue). But when I closed the app, it crashed somewhere in the libcef.dll. I could not get the .PDB file for the library, but there is this entry in the file log with a timestamp closely matching the exit time.
`[0214/164402.890:FATAL:server_shared_bitmap_manager.cc(72)] Check failed: handle_map_.empty(). `

BTW, I noticed that the CEF project in the CMake-generated MSVC solution has its character set set to MBCS.

**Comment by MaartenBent** [comment]
Nice job getting this up-to-date.

I tried it with Visual Studio 2017, static libs, Windows 10, CMake 3.10.2.
There is a problem with the Visual Studio project of `libcef_dll_wrapper`, see properties -> c/c++ -> Command Line -> additional options. The spaces between the arguments are missing. It is caused by the REGEX REPLACE in the webview_chromium CMake file. It removes all `;` from the list and glues all commands together. I could fix it by parsing it as a string:
```cmake
    get_target_property(cef_compile_options libcef_dll_wrapper COMPILE_OPTIONS)
    string(REGEX REPLACE "/MTd?" "" cef_compile_options "${cef_compile_options}")
    set_target_properties(libcef_dll_wrapper PROPERTIES COMPILE_OPTIONS "${cef_compile_options}")
```

The sample seems to works fine in Debug and Release build. I did not (yet) try all the supported options exposed by the wxWidgets API.

MinGW does not seem supported, For example  the file `cef_variables.cmake` in `cef-source` is targeted only on MSVC.

**Comment by TcT2k** [comment]
@MaartenBent I've included your fix. Seems to me there is only support for MSVC in CEF for Windows.

**Comment by TcT2k** [comment]
@MaartenBent thanks for noticing, I've removed the tabs. Unfortunately my Xcode is set to tabs for other projects.

**Comment by PBfordev** [comment]
Just few observations based on comparing the wxWebView sample using Chromium and IE backends.

As of now, `RunScript()` cannot return a value. It is a known limitation, but perhaps it could be added to the task list in the original post, assuming it is going to be implemented before merging?

Find from the sample menu does not find any word.
`GetSelectionText()` is not implemented. A bit of searching revealed that the selected text could be obtained by `CEFDOMDocument::GetSelectionAsText()` but I did not look into it (using `CefFrame::VisitDOM()` ?) any further for now. Similarly, `Find()` is not implemented (see `CefBrowserHost::Find()` ?)

`SetPage() `does not work. According to the message in the debug log, the `url `parameter for `CefFrame::LoadString(`) cannot be empty. The docs for the method reads

> Load the contents of |string_val| with the specified dummy |url|. |url| should have a standard scheme (for example, http scheme) or behaviors like link clicks and web security restrictions may not behave as expected.

Using `"http://localhost"` as the `url` in the sample was enough to make it work while still working with the IE backend, not sure if this change would affect other backends…

Last but not least, I'm a bit concerned by the numerous error messages in the log, particularly those labeled FATAL, such as 

> [0221/195943.498:FATAL:scoped_com_initializer.h(52)] Check failed: ((HRESULT)0x80010106L) != hr_ (-2147417850 vs. -2147417850)Invalid COM thread model change 

wxWidgets built using CMake as debug shared 32-bit with MSVC 2017 (15.5.7) and tested on 64-bit Windows 10.0.16299.192

**Comment by TcT2k** [comment]
@PBfordev 
Thanks for testing. A few comments on your findings:
* I'm not sure about `RunScript()` return result. According to the documentation this currently also not implemented in the GTK WebKit backend. But if anybody points me in the right direction I might implement it myself. Otherwise I would leave this to somebody else.
* Find is already documented as not implemented in the documentation page for `wxWebViewChromium` I think I'll leave that to somebody else.
* I've fixed `SetPage()`  with an empty baseURL in the backend. (By using `file://` in case the URL is empty)
* As for the COM warnings (I don't know why they are marked as fatal) they seem harmless to me it's just that wxWidgets already calls `CoInitialize()` with a different threading model than CEF. As these calls happen wxApp and the D2D init module I'm not really sure if there would be any way to supress the calls before CEF starts up.
* I'll look into the path to the zip file in the sample making sure it works on various platforms and build systems

**Comment by PBfordev** [comment]
Sorry, I missed that the documentation has been already done and it lists the limitations I "found".

**Comment by mtangoo** [comment]
Thank you guys for good work. It will be great addition to the library. If there is a need to test things before  merging I'll volunteer to do it. Mac/Linux and **may be** Windows.
Safi!

**Comment by TcT2k** [comment]
@mtangoo Please feel free to test and report your results.

@vadz Maybe you can take a look in the `bakefile_gen` output issues described in the PRs open ToDos section

**Comment by TcT2k** [comment]
I think I'm done with this for now. Anybody interested please **test** and **report** back and have a look at the open ToDo items.

**Comment by PBfordev** [comment]
I believe that `RunScript()` not capable of returning the value should be documented, probably where the method limitations for other backends are listed, but mentioning it also in the `wxWebViewChromium`'s API Differences part may not be a bad idea.

Speaking of documentation, I wonder if the compatibility manifest should be also mentioned in the MSW part of the `wxWebViewChromium` docs...

I have also noticed a few typos in the docs, should I make a PR against the branch for these, it seems it would be easier than just reviewing the code...

**Comment by PBfordev** [comment]
I took the liberty of slightly changing the documentation, see https://github.com/TcT2k/wxWidgets/pull/1

**Comment by TcT2k** [comment]
@PBfordev thanks for the contribution, merged.

**Comment by PBfordev** [comment]
Just for the reference, the fourth open ToDo, _Fix doc.zip loading path in webview sample for all build tools_, should be fixed by  57f620e7.

**Comment by TcT2k** [comment]
> Guys, if you can't wait to use Chromium on Windows, you can try my full feature webview for wxWidgets: [wxWebViewBlink](https://github.com/imReker/wxWebViewBlink).
> It use a very small Chromium Blink core based on [MiniBlink](https://github.com/weolar/miniblink49) and do not rely on the huge monster CEF.

Very interesting, have you looked into linux and/or mac with MiniBlink?

**Comment by imReker** [comment]
> > Guys, if you can't wait to use Chromium on Windows, you can try my full feature webview for wxWidgets: [wxWebViewBlink](https://github.com/imReker/wxWebViewBlink).
> > It use a very small Chromium Blink core based on [MiniBlink](https://github.com/weolar/miniblink49) and do not rely on the huge monster CEF.
> 
> Very interesting, have you looked into linux and/or mac with MiniBlink?

Nope, MiniBlink does not support Linux/Mac. And it's android support is under development.
On Linux/Mac I think WebKit/Safari is good enough to use.

**Comment by Natulux** [comment]
Hey. Is this project still alive? I tried it but had difficulties setting it up. My webview (chromium) sample still complains about:
> "missing extern symbol: ""char const * const wxWebViewBackendChromium" C:\wxWidgets-chromium\samples\webview\webview.obj"

And as far as I could try, a static build (/MT) is not possible at all, is it? The modified wxWidgets couldn't build 7 of 127 projects, when in cmake GUI wxBUILD_USE_STATIC_RUNTIME was checked.

Using Win10x64, vs2015Essentials, merging the missing files from wx312, cmake 3.10.0 GUI and cef 3.3538.1852.gcb937fc.

Cheers
Natu

**Comment by starmate** [comment]
> Guys, if you can't wait to use Chromium on Windows, you can try my full feature webview for wxWidgets: [wxWebViewBlink](https://github.com/imReker/wxWebViewBlink).
> It use a very small Chromium Blink core based on [MiniBlink](https://github.com/weolar/miniblink49) and do not rely on the huge monster CEF.

Hello,

Seems to be great! I tried to include this to my project but I get LNK2001 issue sunresolved external symbol "char const * const wxWebViewBackendMiniBlink"

Could you give me any directions in order to fix this?

**Comment by starmate** [comment]
> > Guys, if you can't wait to use Chromium on Windows, you can try my full feature webview for wxWidgets: [wxWebViewBlink](https://github.com/imReker/wxWebViewBlink).
> > It use a very small Chromium Blink core based on [MiniBlink](https://github.com/weolar/miniblink49) and do not rely on the huge monster CEF.
> 
> Hello,
> 
> Seems to be great! I tried to include this to my project but I get LNK2001 issue sunresolved external symbol "char const * const wxWebViewBackendMiniBlink"
> 
> Could you give me any directions in order to fix this?

Found the way out. I just forgot to define USE_WEBVIEW_MINIBLINK=1.

However, I have another issue. using Chromium Blink is really slow compared to native webview. Not sure if this is normal. Do you confirm that it gives the same behaviour on your side?

**Comment by vadz** [comment]
Is this still relevant with the existence of #1700?

**Comment by PBfordev** [comment]
> Is this still relevant with the existence of #1700?

I thought Chromium-based MS Edge must be available on the system to be used? Will Microsoft be pushing it to pre-Win10 systems, which are now basically deemed unsupported yet still in use?

Perhaps people who program for multiple platforms may appreciate the exactly same browser being available on all their platforms?

OTOH, which year was the work (GSoC) started on this backend? This will probably be never merged...

**Comment by TcT2k** [comment]
@PBfordev 
> I thought Chromium-based MS Edge must be available on the system to be used? Will Microsoft be pushing it to pre-Win10 systems, which are now basically deemed unsupported yet still in use?
> 
Edge (Chromium) is available for Win7 and newer. An application may use the system wide installed version or can include it's own version.

@vadz 
> Is this still relevant with the existence of #1700?

I think it still might be. When just caring about having the latest system provided WebView it's probably enough to depend on Edge (Chromium) on Windows, Safari on macOS and WebKit on Linux.
But if an application want's to use the exact same browser or use `cef_query` for interaction with the webview, CEF provides a consistent environment on multiple platforms.

**Comment by imReker** [comment]
> > > Guys, if you can't wait to use Chromium on Windows, you can try my full feature webview for wxWidgets: [wxWebViewBlink](https://github.com/imReker/wxWebViewBlink).
> > > It use a very small Chromium Blink core based on [MiniBlink](https://github.com/weolar/miniblink49) and do not rely on the huge monster CEF.
> > 
> > 
> > Hello,
> > Seems to be great! I tried to include this to my project but I get LNK2001 issue sunresolved external symbol "char const * const wxWebViewBackendMiniBlink"
> > Could you give me any directions in order to fix this?
> 
> Found the way out. I just forgot to define USE_WEBVIEW_MINIBLINK=1.
> 
> However, I have another issue. using Chromium Blink is really slow compared to native webview. Not sure if this is normal. Do you confirm that it gives the same behaviour on your side?

Free version of MiniBlink does not support hardware accelerate, so it's a bit slow.

**Comment by nns52k** [comment]
The last CEF version I used is cef_binary_85.3.9+gb045a6e+chromium-85.0.4183.102_linux64, and it still didn't support input method on Linux, which is a big problem for CJK characters users. Maybe some document to warn the users about this would be helpful, or even better, to encourage people who are interested in fixing the bug in CEF. This bug has been around for years. See https://bitbucket.org/chromiumembedded/cef/issues/1813/cef-does-not-work-with-imes-on-linux for details.

**Comment by vadz** [comment]
I'm reopening this as I'm working on making this build again, using the latest CEF and current wx.

So far I've done the (few) changes to make it compile again and could build and run it for wxMSW. But there is indeed a problem with wxGTK build, or even two of them:

1. Current code doesn't work because there is no associated X11 window at this point yet. We're going to move `CefBrowser` creation to the "realized" callback, which is annoying as it will make wxGTK quite different from the other ports, but should work.
2. Worse, this code can only ever work when using X11 in the first place. For Wayland we apparently need a special ("ozone"?) build of CEF.

And I didn't test this under Mac at all yet, although this is clearly going to be the most problematic platform.

**Comment by vadz** [comment]
Add another problem: Chrome itself (not libcef) checks on startup that there are no other threads in helper processes, but we already have got 2 worker threads somehow: one running `glib_worker_main()` and another running `gdbus_shared_thread_func()`. We need to somehow get rid of them to allow Chrome to work -- or use a different helper process, which might actually be simpler because to prevent these threads from being created we'd need to initialize modules before initializing `wxApp` which is going to be difficult to change.

**Comment by vadz** [comment]
It finally works with wxGTK3/X11 now. Many thanks to @jiri-janousek whose work I reused to avoid crashing due to visual mismatch when creating the window, I would have never found this myself.

**Comment by mtangoo** [comment]
That is great VZ!
Reviving and merging this would be one of those best things to happen to wx for a long time

**Comment by vadz** [comment]
Surprisingly, I didn't have many problems with Mac version at all. Or, rather, I quickly gave up on the only major one I had: I don't know how to force calling `OnBeforeClose()` there synchronously, but it seems to be always called during the next idle loop iteration, so I just left it like this.

So now it works on the 3 platforms, but there are several build issues to resolve before I can push it:

1. Under Linux we **must** ensure `libcef.so` comes first. Currently I use `LD_PRELOAD` for it as without it the program simply hangs forever on startup due to reentrancy in `InitLibcLocaltimeFunctions()` called from `CefInitialize()`. Ideal would be to also detect this during run-time and give an error rather than hanging, but I'm not sure how to do it.
2. Under macOS we now need not one but 5 (_five_!) helper processes. Creating them from bakefile is horrible, so I'm going to write a shell script doing this instead.
3. I didn't touch CMake part at all. Any help with it would be much appreciated...

**Comment by mtangoo** [comment]
I hope to help at least testing the thing in MacOS if needed!

**Comment by vadz** [comment]
OK, the CI builds won't check much as none of them uses CEF currently and I don't know if anybody is going to review it (it would be very welcome if anybody did, of course!), but it seems to work for me under the 3 platforms now.

CMake is still broken/not updated for the current CEF version and to build all the new Mac helper apps. I don't know if I'm going to be able to update it, as I don't use it myself...

There are also still many limitations, of which the impossibility to get any results from `RunScript()` and/or missing `RunScriptAsync()` are probably the worst ones. I've looked at this briefly but there doesn't seem to be any simple way to make this work: Chrome *forbids* using V8 from the main (browser) process and so doing this must use IPC. Which means providing our own non-trivial renderer helper process and much else.

All in all I am still not sure what to do with this PR. Merging it into master would require at least:

1. Fixing CMake.
2. Adding CI builds at least compiling this code for all platforms.
3. Finding time to maintain this when it inevitably breaks because CEF is clearly a rather fast moving target and I don't know for how long can we remain at some old version of it.

Maybe the best we can do is to have a `webview-cef` branch in the main repository and tell people to use it if they're ready to deal with (3) themselves.

**Comment by mtangoo** [comment]
> 1. Fixing CMake.

Lately I have been busy, but I can slowly try to fix this. I hope there is a good documentation on setting up on mac. Never done CEF stuffs for years.

**Comment by mtangoo** [comment]
> 3\. Finding time to maintain this when it inevitably breaks because CEF is clearly a rather fast moving target and I don't know for how long can we remain at some old version of it.

I have not read yet how the whole library links and how hard to update. But if it works like other C++ libraries it should be possible. Adding it as separate branch IMHO will add maintenance burden, unless it is complex to setup that will cause issues in the future.

I will review  how the whole thing works and come with more factual opinion

**Comment by TcT2k** [comment]
> CMake is still broken/not updated for the current CEF version and to build all the new Mac helper apps. I don't know if I'm going to be able to update it, as I don't use it myself...
> 
I might be able to take a look at that. I hope the required changes aren't to many.

> There are also still many limitations, of which the impossibility to get any results from `RunScript()` and/or missing `RunScriptAsync()` are probably the worst ones. I've looked at this briefly but there doesn't seem to be any simple way to make this work: Chrome _forbids_ using V8 from the main (browser) process and so doing this must use IPC. Which means providing our own non-trivial renderer helper process and much else.
> 
Sounds like some work for something that's trivial with the other backends, where it was more work to get the non async `RunScript()` working than the other way around.

> 
> Maybe the best we can do is to have a `webview-cef` branch in the main repository and tell people to use it if they're ready to deal with (3) themselves.

I think a better way than a extra branch would be an additional repository something like: `wxWidgetsWebViewCEF`
- A wxWidgets branch would be more cumbersome to integrate in your own projects as development wxWidgets moves on. 
- The wxWidgets API for additional backends is very stable and doesn't require deep special integration where CEF has to be part of the main wxWidgets library code
- The main wxWidgets `wxWebView`documentation could link to that repository (and it's build instructions) to make potential users aware of it's existence
- The webviewsample could include the few ifdefs required (to reduce potential maintenance)
- As documentation a single README.md should be enough
- The readme/build instructions in that repository could state the current supported wxWidgets and CEF version(s)
- All CEF specific scripts/build files could be kept there
- Maybe even CEF specific CI builds could be done from there

This way when you build an app requiring CEF support the build steps could be:
1. Get the wxWidgets version you want to use (this could be a stable version in the future or even binaries)
2. Get the latest wxWidgetsWebViewCEF
3. Get the corresponding CEF
4. Follow the build instructions for wxWidgetsWebViewCEF

In an ideal scenario it would even be possible for all 3 components (wxWidgets, CEF and the wxWidgetsWebViewCEF) could be available via a package manager.

**Comment by vadz** [comment]
Sorry, I'm not sure how would a separate repository idea work. The problem is maintenance and if we're prepared to maintain it I'd rather do it in the main repository (or, possibly, its submodule), as this will be simpler. But if we can't keep it up to date with CEF development, then it doesn't really matter whether it gets stale in the same repository or another one...

Anyhow, for now I've finished the minimum work required to be able to use CEF-based web view and set the proxy for it, which, unlike the implementations in master, also works under Mac. I might work more on this slightly later but for now I'll stop here and see if there are any serious problems found during testing by people who are interested in using this.

Thanks in advance for your feedback!

**Comment by vadz** [comment]
I've been wondering if we really need a separate `webview_chromium` library. It seems that if you explicitly enable CEF, it shouldn't be a problem for `webview` library itself to depend on it (especially as long as it can still be used with the other backends if the CEF DLL is not available, which I think should be the case).

Am I missing something that really requires having a separate library for this? If we do merge this in master, I think it would be much simpler to have an extra file (or two) in the webview library than a whole optional library. @TcT2k please let me know if I don't see some obvious problem with doing this.

**Comment by TcT2k** [comment]
I also think it shouldn't be a problem to include it in the `webview` library. It seems the same as with Edge when you enable it it depends on the required libraries/SDK.

**Comment by vadz** [comment]
I've done this now and it seems to work fine for me, but CMake build is now totally broken... It probably shouldn't be that difficult to update but I have such a hard time forcing myself to do anything with CMake that for now I still hope someone else might be motivated to do it.

**Comment by vadz** [comment]
AFAICS this is sufficiently finished to be merged now, except for CMake support.

I'm going to try to fix it myself, but if any kind soul can help with this, it would be great, of course... (but please let me know in this case, so that we don't duplicate work).

**Comment by MaartenBent** [comment]
I can have a look at the CMake part.
From the documentation I understand that for configure/msvc you first build cef separately with CMake and put the files in `/3rdparty/cef`? I'll first get that to work with CMake. 
And after that I'll look at the files for automatically downloading and building it as part of wxWidgets.

I don't mind if you merge this in the mean time.

**Comment by vadz** [comment]
> I can have a look at the CMake part. From the documentation I understand that for configure/msvc you first build cef separately with CMake and put the files in `/3rdparty/cef`?

Yes, exactly. I thought of making this configurable, but it would things make even more complex and it's probably not such a great deal, knowing that you can always use symlinks/junctions if you really don't want to put the real CEF under this directory (e.g. because you don't have enough space there -- because it's big).

> I'll first get that to work with CMake. And after that I'll look at the files for automatically downloading and building it as part of wxWidgets.

The latter part is something I am especially worried about as I think it was supposed to "just work out of the box" for CMake users and I feel bad about breaking it.

> I don't mind if you merge this in the mean time.

I actually may have more changes to do here in order to expose more of CEF functionality to the application, so I'm not that in a hurry to merge this. But I definitely want to do it before 3.3.0.

TIA!

**Comment by MaartenBent** [comment]
I fixed downloading and building on Windows/msvc, see https://github.com/MaartenBent/wxWidgets/commits/chromium

I noticed Visual Studio reports memory leaks when exiting the webview sample using chromium.

**Comment by vadz** [comment]
> I fixed downloading and building on Windows/msvc, see https://github.com/MaartenBent/wxWidgets/commits/chromium

Wow, great, thanks a lot! Should I merge this into this branch and push it here?

One thing I noticed is that e82a4bf350c074f242e1a63c4497ebe26f64495b seems to change `build/cmake/lib/webview_chromium/cef_version_info.cmake` to use DOS EOLs, which is probably unintentional?
 
> I noticed Visual Studio reports memory leaks when exiting the webview sample using chromium.

I don't know if we can really do anything about them...

**Comment by MaartenBent** [comment]
> Wow, great, thanks a lot! Should I merge this into this branch and push it here?

Not yet, I'll try to have a look at Linux/macOS as well the coming days.
And I'll put some better commit messages in them.

> One thing I noticed is that https://github.com/wxWidgets/wxWidgets/commit/e82a4bf350c074f242e1a63c4497ebe26f64495b seems to change build/cmake/lib/webview_chromium/cef_version_info.cmake to use DOS EOLs, which is probably unintentional?

I noticed it too, but didn't bother fixing it yet. Should be easy enough by adding `NEWLINE_STYLE LF` to `configure_file`. Also Linux 32-bit is not available anymore, and should probably give an error.

**Comment by vadz** [comment]
> Not yet, I'll try to have a look at Linux/macOS as well the coming days. And I'll put some better commit messages in them.

TIA!
 
> Also Linux 32-bit is not available anymore, and should probably give an error.

Yes, nobody uses it on desktop anyhow any more, and I think we're fine with not running Chromium on a toaster.

**Comment by MaartenBent** [comment]
Building and running with CMake should work again on Windows, Linux and macOS. So you can merge my branch into this.

I modified a`.bkl` file so it matches the CMake build and the cefsimple example. I tested the sed command, but did not rebake.

I have one question about the `libcef_dll_wrapper` library name. Should we add the debug postfix `d` when building with msvc? Like is done for the other libraries.

**Comment by vadz** [comment]
> Building and running with CMake should work again on Windows, Linux and macOS. So you can merge my branch into this.

Great, thanks again!
 
> I modified a`.bkl` file so it matches the CMake build and the cefsimple example. I tested the sed command, but did not rebake.

OK, will do when merging.
 
> I have one question about the `libcef_dll_wrapper` library name. Should we add the debug postfix `d` when building with msvc? Like is done for the other libraries.

I guess it would make sense, but I'm not sure if it's worth the extra effort as it just makes it more obvious that they're different libraries but you can't really mix them up anyhow with MSVC because you'd get link errors. I.e. I'm fine either way, but please let me know if you plan to do it as I should probably postpone the merge until then.

BTW, ABI incompatibility between Linux (and Mac) versions built with and without `NDEBUG` is a real PITA, as you do _not_ get any link errors but the program just dies with weird errors if you mix them up. I tried [suggesting improving this](https://magpcss.org/ceforum/viewtopic.php?f=6&t=19666) but this was refused by the CEF maintainer.

**Comment by MaartenBent** [comment]
I added a commit adding the debug postfix.
I wanted to do this because msvc puts both debug and release libraries in the `vc_x64_lib` folder. But then the cef library files still have the same name, so maybe it is not as useful.
I'll leave it to you if you want to keep this or not.

**Comment by vadz** [comment]
@MaartenBent Thanks again for your work on CMake!

There is one missing piece: currently, if you build the library in debug, using `wxWebViewChromium` crashes because `wxHAVE_CEF_DEBUG` is not defined and hence there is an ABI mismatch (at least under Linux). I've "fixed" this but I had a lot of trouble and I'm pretty sure I didn't do it in the right way, so any corrections/improvements would be welcome:

1. I couldn't make it work with the generator expressions, if I did `set(wxHAVE_CEF_DEBUG $<$<CONFIG:Debug>:ON>)` it was somehow defined in release too.
2. I couldn't make it work in `lib/webview_chromium/CMakeLists.txt` and had to do it in `setup.cmake` itself as I couldn't figure out how to propagate the value of the variable from the former to the latter.

But at least it works now in the sense that the debug build of my application doesn't crash any more.

Another minor thing is that in my testing you can actually build CEF DLL wrapper with C++14, at least in v116 that I still use (even though C++17 is required for  compiling CEF itself since v105), so I've relaxed the check for C++ standard being used, which also makes CMake consistent with configure -- and the documentation.

Also, on an unrelated topic, where is `lib_rls` CMake variable being set? I only see it being used...

**Comment by MaartenBent** [comment]
You can't use generator expressions in `set()` because this is evaluated at configure time. Generator expressions are evaluated at build time. You can only use them in certain cmake functions.
I'll have a look at `wxHAVE_CEF_DEBUG` and see if it can be improved.

`lib_rls` is supposed to be empty. Similar code is used in multiple locations, so I did the same here.

The latest cef does need c++17, not when building the wrapper but when using it in `webview_chromium`:
```
1>webview_chromium.cpp
1>D:\dev\build\wxWidgets\msvc64\libs\webview_chromium\cef-source\include\base\cef_ref_counted.h(487,32): error C2061: syntax error: identifier 'in_place_t'
1>(compiling source file '../../../../../wxWidgets/src/common/webview_chromium.cpp')
1>D:\dev\build\wxWidgets\msvc64\libs\webview_chromium\cef-source\include\base\cef_ref_counted.h(487,32):
1>the template instantiation context (the oldest one first) is
1>	D:\dev\build\wxWidgets\msvc64\libs\webview_chromium\cef-source\include\base\cef_ref_counted.h(495,2):
1>	see reference to class template instantiation 'base::RefCountedData<T>' being compiled

```

**Comment by vadz** [comment]
> You can't use generator expressions in `set()` because this is evaluated at configure time. Generator expressions are evaluated at build time.

Yes, this is how I understood it too, but I see that CEF makefiles themselves use generators and so I hoped to do the same thing as they do, but couldn't. I think that for make/ninja build backends there is no real difference between using generators and checking `CMAKE_BUILD_TYPE` anyhow, unlike for MSVC, but I'm not 100% sure.

> I'll have a look at `wxHAVE_CEF_DEBUG` and see if it can be improved.

TIA!
 
> `lib_rls` is supposed to be empty. Similar code is used in multiple locations, so I did the same here.

OK, thanks, but shouldn't we remove it (from everywhere) then? I can create an issue to remind us to do it when this is merged.
 
> The latest cef does need c++17, not when building the wrapper but when using it in `webview_chromium`:

Oops, this is really weird because `in_place_t` is clearly C++17 and only defined inside `#if __cplusplus >= 201703L` checks in libstdc++ headers but somehow this is still getting compiled in C++14 mode.

Anyhow, I'll have to update configure/docs to use C++17 too then, I guess it's not worth trying to use C++14.

**Comment by vadz** [comment]
> I added a commit adding the debug postfix. I wanted to do this because msvc puts both debug and release libraries in the `vc_x64_lib` folder. But then the cef library files still have the same name, so maybe it is not as useful. I'll leave it to you if you want to keep this or not.

Sorry, I'm finally testing this on Windows and it looks like this is incompatible with the "native" CMake build of CEF, as it creates the libraries without the suffix. As I'd like to keep building wx using its project files rather than CMake under Windows, I'm finally going to revert 3d51977acf9e394d987473d40b22c63366a3a433 unless I'm missing something here...

**Comment by MaartenBent** [comment]
> I couldn't make it work in lib/webview_chromium/CMakeLists.txt and had to do it in setup.cmake itself as I couldn't figure out how to propagate the value of the variable from the former to the latter.

This seems like the best solution. It won't work with multi-config generators like msvc, because it uses `CMAKE_CONFIGURATION_TYPES` instead of `CMAKE_BUILD_TYPE`, but that shouldn't be a problem.

Is there a reason we can't add `NDEBUG` to the debug compile definitions and not use `wxHAVE_CEF_DEBUG` at all?

For future reference,  you can use `set(.. PARENT_SCOPE)` to propagate variables one directory up.

**Comment by vadz** [comment]
> Is there a reason we can't add `NDEBUG` to the release compile definitions and not use `wxHAVE_CEF_DEBUG` at all?

But we don't necessarily want `NDEBUG` to affect other headers. I.e. if some (3rd party?) header includes `<assert.h>`, we probably want the assertions to be enabled with debug. Although it's hard to be sure because our current (Unix-like) hybrid debug/release build doesn't map nicely to the Windows rigidly separated debug and release builds (which we also used to use).
 
> For future reference, you can use `set(.. PARENT_SCOPE)` to propagate variables one directory up.

Yes, thanks, I knew that, but this didn't work in this case, IIRC it was because I had to propagate the variable to a "cousin twice removed" file instead of just the parent one.

Anyhow, if you think it's fine like this I'm very tempted to just leave it be...

**Comment by MaartenBent** [comment]
> Yes, thanks, I knew that, but this didn't work in this case, IIRC it was because I had to propagate the variable to a "cousin twice removed" file instead of just the parent one.

Correct. You have to put in every file in-between. Like is done for `wxLIB_TARGETS`. The variable is updated in `build/cmake/lib/<name>/CMakeLists.txt` (using `wx_add_library` in `functions.cmake`) and then propagated back up to `build/cmake` scope in `build/cmake/lib/CMakeLists.txt`

> Anyhow, if you think it's fine like this I'm very tempted to just leave it be...

Yes, I think this is fine.

ps
Another way to make it work in `lib/webview_chromium/CMakeLists.txt` could be by internally caching it (not verified):
`set(wxHAVE_CEF_DEBUG ON CACHE INTERNAL "")`

**Comment by vadz** [comment]
I've added a few more changes allowing to customize CEF logging (I'm still unhappy about using our own `wxWebViewConfigurationChromium` as "native" configuration object, but as I wrote in [my post](https://groups.google.com/g/wx-dev/c/QzP7YxvcVVE/m/wpDK0ZH_AgAJ) I don't really see what else to do) and I think I'd like to merge this now.

Does anybody have any objections? There are certainly many other things that can be improved, but this can be done later, on master.

**Comment by vadz** [comment]
And it's done!

**Pull request merged**
