### PR TITLE
Allow usage of static loader with wxWebViewEdge

### PR DESCRIPTION
**Pull request by TcT2k**
Add a new build option `wxUSE_WEBVIEW_EDGE_STATIC`.
If it is set to `1` the WebView2 loader is static linked into the binary and removes the runtime dependency on `WebView2Loader.dll`.

In my experience the static library from the WebView2 SDK only links with VS2019 or newer. (It produced an unusable binary when I used it with VS2017).

### CODE REVIEW

**Comment by vadz** [comment]
If this is for MSVS only, we could use its `#pragma comment(lib, "xxx")` to link with this library.

To do this in any other way we'd need to add an option (i.e. something in `build/msw/config.*`) and even this wouldn't help with MSVS project files, so I think we should do this for MSVS in any case.

**Comment by TcT2k** [comment]
> If this is for MSVS only, we could use its `#pragma comment(lib, "xxx")` to link with this library.
> 
> To do this in any other way we'd need to add an option (i.e. something in `build/msw/config.*`) and even this wouldn't help with MSVS project files, so I think we should do this for MSVS in any case.

Sounds good, I'll look into that. I think this can only be MSVS as the `webloaderstatic.lib` is only provided for MSVS.

**Comment by TcT2k** [comment]
Now using `#pragma comment(lib, "xxx")` to work with all build systems supporting MSVC. Bakefiles and vcxproj files have been updated to include the required library search path.

**Comment by vadz** [comment]
Thanks, will merge soon!

**Pull request merged**
