### PR TITLE
Fixed compilation error

### PR DESCRIPTION
**Pull request by Zangetsu38**
Now compilation perfectly works

### CODE REVIEW

**Comment by vadz** [comment]
No, this is wrong, please see [the build instructions](https://github.com/wxWidgets/wxWidgets/blob/master/BuildGit.txt#L6)

**Comment by Zangetsu38** [comment]
@vadz No, it is not a mistake, I just fix the error, if not we doing this compilation does not work, as the "wx_custom_build", looking for a file that does not exist, so there a problem.
And it does not change anything at compile just it works, that's all.

**Comment by vadz** [comment]
Please read the link.

**Comment by Zangetsu38** [comment]
@vadz yes, I read, but it does not prevent there is a mistake, when compiling a project has not copied a file and the renamed ago no problem for that .
And I just solved that problem and it makes no difference at all to the rest of the project, so I do not see where is the problem.

**Comment by vadz** [comment]
Your change breaks the build for the releases (i.e. sources unpacked from an archive instead of being checked out from a VCS) in which the file `setup0.h` doesn't exist (but `setup.h` does). It breaks taking into account the local modifications in `setup.h` (this file is not kept in the VCS just to allow making them). It makes quite a lot of difference.

Why do people think that it's fine to just plainly *refuse* following the build instructions of a project is simply beyond me.

**Comment by Zangetsu38** [comment]
@vadz Then sorry but I understand nothing of it is completely illogical to me.
From the moment a peak or project file that does not exist, there is a problem, we can not use the p tell it on a project, as the compilation does not work, and if the compilation doesnt c is that there is a problem.
And not that I did not spanked nothing the rest of the project ca only concerns the visual studio version.

**Pull request closed without merging**
