### PR TITLE
Fix tests on ppc64le & s390x Linux architectures

### PR DESCRIPTION
**Pull request by swt2c**

### CODE REVIEW

**Comment by vadz** [comment]
Thanks, I'll merge this into #1783 and then merge the result into master.

**Comment by vadz** [comment]
I've integrated this into #1783 together with other tweaks to make the tests pass in Travis LXC containers for these archs (it looks like your build machines use some other environment?), so I'm closing this one.

**Comment by swt2c** [comment]
Yeah, my build environment is Fedora mock, which has some different limitations.  I had to disable a few other tests too, see: https://src.fedoraproject.org/rpms/wxGTK/blob/master/f/disable-tests-failing-mock.patch.  I'll maybe see if I can make a more general patch that can detect the mock environment and disable those.

**Comment by vadz** [comment]
BTW, my attempts to detect LXD automatically failed (although I have no idea why, everything seems to suggest that `/dev/lxd` should normally exist), so I'll probably just define some `wxCONTAINER` env var or something like this and disable these tests when it's defined. It probably could be used in your mock (if it's anything like a container?) too?

**Comment by swt2c** [comment]
Yes, mock uses 'systemd-nspawn', so it is like a lightweight container.

**Pull request closed without merging**
