### PR TITLE
Generic wxSpinStrlDouble: border mask fix

### PR DESCRIPTION
**Pull request by valid-ptr**

### CODE REVIEW

**Comment by vadz** [comment]
Could you please explain what does this actually fix? Do you want to create the text control without any border? If so, I'm not really sure it makes sense to do it here, I think it would be inconsistent with the native version.

But maybe I just misunderstand so, again, could you please explain what are you doing and what do you want to achieve? Thannks!

**Comment by valid-ptr** [comment]
> Could you please explain what does this actually fix? Do you want to create the text control without any border? If so, I'm not really sure it makes sense to do it here, I think it would be inconsistent with the native version.

Yes, this gives the opportunity to create wxTextCtrl inside wxSpinCtrlDouble with **any border style** you want. BORDER_NONE or any other...

Why not?

**Comment by vadz** [comment]
Because I don't think the native control supports this, so it introduces an inconsistency between controls/ports. Or does it work for the native versions too?

**Comment by valid-ptr** [comment]
This is generic version, I suppose it's used (mostly) when there is no native version of such control presented. Is wxSpinControlDouble used (mostly) on Windows only!? If so, I don't see the reason why we must prevent BORDER_STYLE for the internal wxTextCtrl. This will just tie hands of end developer.

**Comment by vadz** [comment]
To make it clear: the problem is that if you use `wxBORDER_NONE` with `wxSpinCtrlDouble` right now, it won't work on any platform. This is perhaps not ideal, but at least it's consistent. If this change makes it work under MSW (which uses the generic version) but not GTK (which uses native one), someone who develops under MSW would believe that it works only to discover that it doesn't when they test the program under Linux. This is not necessarily better than the current situation and at the very least we need to very explicitly document that border styles are respected only when using the generic version if we do this. But as nobody reads the documentation anyhow, it will still be seen as a bug...

**Comment by vadz** [comment]
Actually I've finally tested this under wxGTK and specifying `wxBORDER_NONE` for `wxSpinCtrlDouble` does work, so there is no problem here and we can apply this. Sorry for the confusion.

P.S. I've also added `.mailmap` entries for your names/emails in 64374fba59288c764669f05bd9cded3620a5464e, hopefully you don't mind, but please let me know if you do.

**Pull request closed without merging**
