### PR TITLE
Add MSWDoClientToScreen and MSWDoScreenToClient

### PR DESCRIPTION
**Pull request by Kvaz1r**
Patch for [18455 ticket](https://trac.wxwidgets.org/ticket/18455)

### CODE REVIEW

**Comment by vadz** [comment]
Great, thanks! Will merge once the CI builds finish.

**Comment by MaartenBent** [comment]
Will this work with RTL layout? Here the spin control is already on the left and the text control is on the right. See notes in `wxSpinCtrl::DoMoveWindow` and `wxSpinCtrl::DoGetPosition`.

**Comment by Kvaz1r** [comment]
It seems that won't. Is there any easy way to test RTL layout? Is will enough get HWND of window which has smaller x coordinate than other window as in DoGetPosition/2?

**Comment by MaartenBent** [comment]
Adding ` SetLayoutDirection(wxLayout_RightToLeft);` at the start of `MyFrame` constructor seems to work. But it looks like there are more problems with the text control.

**Comment by vadz** [comment]
Oops, this indeed won't work if ` GetParent()->GetLayoutDirection() != GetLayoutDirection()`, I didn't think about this case. I don't think this happens frequently, but it would probably indeed better to handle it if `wxSpinCtrl::DoMoveWindow()` does it.

**Comment by Kvaz1r** [comment]
It doesn't seems that even DoMoveWindow works correctly for RTL layout. Correct me if I am wrong, but spin button and text should swap their locations if parent frame was set RTL like it do for generic version of spin control?

**Comment by MaartenBent** [comment]
It looks like `wxSpinCtrl::GetOverlap()` is wrong for RTL. If I change it to the following it works fine.
```c++
int wxSpinCtrl::GetOverlap() const
{
    return FromDIP(2);
}
```

I don't know why it used `[m_hwndBuddy].right-[m_hWnd].left`, this will always return `2` after setting the initial overlap with `FromDIP(2)`.

`GetScreenPosition()` is still wrong, and I don't know how you can fix it. Both `GetBuddyHwnd()` and `GetHwnd()` return `497` when using `wxWindow::MSWDoClientToScreen()`. This is between the spin control and the text control. I would expect `595`.

spin

**Comment by vadz** [comment]
> I don't know why it used `[m_hwndBuddy].right-[m_hWnd].left`, this will always return `2` after setting the initial overlap with `FromDIP(2)`.

I _think_ this could be because of concerns about what happens before the controls are initially positioned.

> `GetScreenPosition()` is still wrong, and I don't know how you can fix it. Both `GetBuddyHwnd()` and `GetHwnd()` return `497` when using `wxWindow::MSWDoClientToScreen()`. This is between the spin control and the text control. I would expect `595`.

This is pretty strange, I can't believe that native Win32 API is broken for RTL, there must be hundreds of millions of people using it in this case. We must be doing something wrong somewhere... Unfortunately I can't test it myself right now.

**Comment by MaartenBent** [comment]
> I _think_ this could be because of concerns about what happens before the controls are initially positioned.

Yes, that's what happens. The first time the function is called `GetHwnd()` is `NULL` so it returns `FromDIP(2)`. This sets the overlap of the controls to `2`. All subsequent calls have  a valid `GetHwnd()` and will use `wxGetWindowRect(m_hwndBuddy).right - wxGetWindowRect(GetHwnd()).left`. This will now return the previously set `2`. So IMO this can be simplified and we can  always return `FromDIP(2)`. This will fix the wrong size of the text control with  `wxLayout_RightToLeft` and does not seem to have any other effects.

> This is pretty strange, I can't believe that native Win32 API is broken for RTL, there must be hundreds of millions of people using it in this case. We must be doing something wrong somewhere... Unfortunately I can't test it myself right now.

I checked the created controls with Spy++ and the buddy text control does not have the `WS_EX_LAYOUTRTL` style (only `WS_EX_RTLREADING`). I tried setting it when creating the control, with `wxUpdateLayoutDirection` and `wxUpdateEditLayoutDirection` but none of them seem to work.
Same for the big text control in the screenshots, so its not spin control related.

I have no experience with RTL, this is the first time I tried it, so I'm not going to look further into it. These are just some things I noticed after reading the RTL comment in the code. I did find that `MapWindowPoints` is preferred over `ClientToScreen` when using RTL: https://docs.microsoft.com/en-us/windows/win32/winmsg/window-features#window-layout-and-mirroring

**Comment by Kvaz1r** [comment]
> I did find that `MapWindowPoints` is preferred over `ClientToScreen` when using RTL:

I tried MapWindowPoints and it changed nothing, though I also seen that this function preferred for RTL.

**Comment by vadz** [comment]
I guess we should merge this fix, which at least corrects the bug for LTR case, and leave RTL for later.

Thanks again for fixing the original problem, @Kvaz1r

**Pull request closed without merging**
