### PR TITLE
Optimize PNGs Doxygen

### PR DESCRIPTION
**Pull request by Metallicow**
PNGs optimized with FileOptimizer.
249 files processed. 296,293 bytes saved (64%)

### CODE REVIEW

**Comment by vadz** [comment]
Thanks! It would be nice to update `docs/contributing/how-to-add-class-documentation.md` to mention what should be done to any new PNG files to keep them as optimized as the current ones.

**Comment by Metallicow** [comment]
@vadz I just process them thru [FileOptimizer](https://sourceforge.net/projects/nikkhokkho/files/FileOptimizer/) It takes various png optimizers and wraps them into one simple interface for maximum optimization. If you want to add a note for that, go ahead. Note: it takes a bit of time to process a lot of images, so it's a bedtime operation sometimes.

**Comment by tierra** [comment]
These are all generated by the screenshot-gen utility, and they will be overwritten on another run, so it really would have been nice to build this step into that workflow.

**Comment by Metallicow** [comment]
Most all the optimizers are commandline utilities called from the GUI so that is a possibility...
One would have to look at the source code then...

**Pull request merged**
