### PR TITLE
OSX adding composition do wxOSXDrawNSImage

### PR DESCRIPTION
**Pull request by csomor**
see #23240

### CODE REVIEW

**Comment by vadz** [comment]
Thanks! Applied to master, see the commit referenced above, and will backport to 3.2 a bit later.

**Comment by csomor** [comment]
> will backport to 3.2 a bit later.

@vadz I had to add an additional parameter, for backwards compatibility should add a default version with one parameter less ?

**Comment by vadz** [comment]
I thought `wxOSXDrawNSImage()` was a private function, but now I see that it's indeed exported... I guess we should indeed add an overload without the new parameter to be safe, thanks for noticing this.

But I also wonder if we shouldn't stop exporting it in master, or is it really useful in the application code?

**Comment by vadz** [comment]
Backported with the extra ABI fix to 3.2, thanks!

**Pull request closed without merging**
