### PR TITLE
[wxMSW] Removed old fix from wxTreeCtrl::DoInsertAfter()

### PR DESCRIPTION
**Pull request by artur-so**
Removed (apparently) outdated fix for MSW implementation of wxTreeCtrl::DoInsertAfter().
The old fix changes slow down the insertion of first child items in big trees.

### CODE REVIEW

**Comment by vadz** [comment]
We still support XP, actually, so I think it would be better to keep this code for now but just guard it by `wxGetWinVersion()`...

**Comment by artur-sochirca** [comment]
Not being familiar with git procedures, I seem to have messed it up.
Current "Files changed" status contains changes to check the OS version, as suggested.
But how to proceed?

**Comment by vadz** [comment]
I'm not sure what happened with Git branch here, but it's not a problem, I can just squash all this into a single commit when applying. Worse is that I think your check is reverted, so, AFAICS, inserting items under _modern_ MSW versions is still inefficient with this change, with the added benefit that it's now broken with the old ones :-/

Also, I'd do this check when defining `firstChild` to save on calling `TreeView_GetChild()` too unnecessarily.

**Comment by vadz** [comment]
Thanks, I've applied it with minor changes.

**Comment by artur-sochirca** [comment]
Thanks for your review and assistance. I had second thoughts identical to your changes.

**Pull request closed without merging**
