### PR TITLE
Fix problems with 3.0 compatibility in wxPG code

### PR DESCRIPTION
**Pull request by vadz**
See #23369.

Also enable 3.0 compatibility for one of the CI builds.

### CODE REVIEW

**Comment by vadz** [comment]
@a-wi I wanted to make minimal changes initially, but this was ugly (code had to be duplicated) and didn't allow the sample, using the new API, to compile when compatibility was enabled, so I finally went ahead and did a bigger, but IMO also much better, change in the last commit.

Generally speaking, we really should only add something to the API when compatibility with old version is enabled, but still provide all the new APIs. It's unfortunate that we can't do this for `DrawCaptionSelectionRect()`, the new virtual function really ought to have had a different name to allow it, but we still should do it like this for any new deprecations.

**Comment by vadz** [comment]
@a-wi Do you see anything you'd like to apply from this PR other than the last commit after your 35a8d0f9085f9c9b5aad6fde56bda66124132506 or should it be just closed?

**Comment by a-wi** [comment]
Essentials changes in wxPG headers are already done but adding a additional condition for `wxPG_DEPRECATED_MACRO_VALUE` in property.h would be useful.
Updates to CI are welcome.

**Comment by vadz** [comment]
Hmm, looking at the amount of the existing code overriding this function and seeing that this change is not even mentioned in the change log, I think we do need to keep this working.

**Comment by vadz** [comment]
Replaced by #23375.

**Pull request closed without merging**
