### PR TITLE
CMake: Improve adding external libraries to wx-config

### PR DESCRIPTION
**Pull request by MaartenBent**
Don't add `-l` to libraries already containing it (for example `-lpthread`).
Change libraries with format `libName.so` or `libName.a` to `-lName`, configure also uses `-l` for these libraries.
Account for possible invalid libraries (`Name-NOTFOUND`) which could happen with imported libraries (for example `OpenGL::OpenGL`).

@valid-ptr can you verify this fixes your build?

### CODE REVIEW

**Comment by valid-ptr** [comment]
> @valid-ptr can you verify this fixes your build?

Works as expected!

**Comment by vadz** [comment]
Thanks for fixing this (and also thanks to @valid-ptr for testing)!

**Comment by ancwrd1** [comment]
when building for wxGTK on Linux it still adds a raw "libc.so" as a dependency:

`/opt/wx/x86_64-unknown-linux-gnu/bin/wx-config --libs`

-L/opt/wx/x86_64-unknown-linux-gnu/lib -pthread /opt/wx/x86_64-unknown-linux-gnu/lib/libwx_gtk3u_xrc-3.1.a /opt/wx/x86_64-unknown-linux-gnu/lib/libwx_gtk3u_qa-3.1.a /opt/wx/x86_64-unknown-linux-gnu/lib/libwx_baseu_net-3.1.a /opt/wx/x86_64-unknown-linux-gnu/lib/libwx_gtk3u_html-3.1.a /opt/wx/x86_64-unknown-linux-gnu/lib/libwx_gtk3u_core-3.1.a /opt/wx/x86_64-unknown-linux-gnu/lib/libwx_baseu_xml-3.1.a /opt/wx/x86_64-unknown-linux-gnu/lib/libwx_baseu-3.1.a -lwx_gtk3u_core-3.1 -lmspack -ljpeg -lpng -ltiff -lSDL2main -lSDL2 -lwx_baseu-3.1 -lexpat -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -lharfbuzz -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lX11 -lXext -lXtst -lz -lwxregexu-3.1 -lsecret-1 -lgio-2.0 -lgobject-2.0 -lglib-2.0 **libc.so** -lpthread -ldl

**Comment by MaartenBent** [comment]
Yes, changing it to `-lc` like other libraries didn't work, so I just kept `libc.so`. Is that a problem?

**Comment by ancwrd1** [comment]
Yes, it doesn't link with an error `libc.so: No such file or directory`. I think `-lc ` is implied anyway by the linker unless "-nostdlib" is passed over.

**Pull request closed without merging**
