### PR TITLE
Updated sample icons using the new logo image

### PR DESCRIPTION
**Pull request by redtide**
I made the Windows icon with 16, 32, 48, 64, 128, 256 and 512 pixels (the original seems to have 16 and 32 pixels) with `icotool` from Linux `icoutils` package starting from a resized `blocks.png` image; I had to remove some border and make the size with the width matching the height.
EDIT: I noticed later that there is already a Windows icon in the website download section, if needed I'll replace mine with it with a force push.

Then I tried to create the  32x32 xpm icon using ImageMagick `convert` tool, but the result was not great, so in this case I edited the original one using colors to mimic the new one, hope it's OK for you.

### CODE REVIEW

**Comment by redtide** [comment]
OK, just tried on Windows and this is how it looks like when using bigger icons:
immagine

**Comment by tierra** [comment]
Out of curiosity, did you try the ICO already provided here?
https://www.wxwidgets.org/downloads/logos/blocks-icons-msw.ico

The favicon used on the website is intentionally only 16 and 32, but that MSW icon file contains 16, 32, 48, 64, 96, and 128. I'm sure real apps should also include 256, and maybe even 512, but I think for our samples, it's just fine with 128 max in there (otherwise we're just bloating the git repo for little reason).

**Comment by redtide** [comment]
the screenshot above shows a 512 px icon, and how it could appear using the 128px `blocks-icons-msw.ico` on the right, if that is fine I will remove mine and replace with the other, the bigger icon is about 1.5MB, the 128px is about 140KB.

**Comment by redtide** [comment]
OK, I replaced the Windows icon with the `blocks-icons-msw.ico` from the current download section. Thank you @tierra for the advice.

**Comment by vadz** [comment]
I don't think bloating the Git repo is really a concern, maybe it would have been if we had 100 copies of this file, but we have only one and even 1.5MiB is not much. Increasing the size of the samples binaries might be more of a concern, but I'm not really sure. I admit I'm a bit surprised it takes that much, it looks like this image should be very compressible.

**Comment by redtide** [comment]
> I admit I'm a bit surprised it takes that much, it looks like this image should be very compressible.

I have no idea why, the original images from where it comes from are not that much big, maybe I had to use a Windows tool instead `icotool` on Linux?
immagine

**Comment by redtide** [comment]
OK, Gimp did the trick, so now the icon containing up to 512px size is even 10K less than the `blocks-icons-msw.ico`.

**Comment by vadz** [comment]
Thanks again for the update!

**Pull request closed without merging**
