### PR TITLE
Support sort indicators in wxListCtrl header

### PR DESCRIPTION
**Pull request by MaartenBent**
See [#19329](https://trac.wxwidgets.org/ticket/19329)

### CODE REVIEW

**Comment by vadz** [comment]
Thanks!

Let's merge it if there are no comments in a couple of days.

**Comment by wh11204** [comment]
Just a suggestion to keep coherency with [wxHeaderCtrlSimple](https://docs.wxwidgets.org/trunk/classwx_header_ctrl_simple.html);

- SetSortIndicatorColumn() could be renamed as ShowSortIndicator(), both have the same parameters and usage. The latter is documented as accepting -1 for removing the indicator, the former is not,
- Create RemoveSortIndicator() calling for example ShowSortIndicator(-1, true), supposing -1 is a valid value for removing the indicator.

**Comment by vadz** [comment]
@MaartenBent please let me know if you think of following @wh11204's suggestions or if you think it's better to apply this as is?

**Comment by MaartenBent** [comment]
Yes, I can apply those suggestions.

**Comment by vadz** [comment]
Thanks for the update! I'll merge it once the CI builds finish -- unless you want to rebase the last commit?

**Comment by MaartenBent** [comment]
I think you can merge it like this. The last two commits are not directly related to sort indicators, but since they affect `wxListCtrl` I added them to this PR.

**Comment by vadz** [comment]
Oh, sorry, I didn't realize that this was for `MSWWindowProc` in the generic version, not the MSW one (where it's already present, so I thought it got removed accidentally by some of the earlier commits, which explains why I thought this could need to be rebased). I wonder why do we do this instead of just using `wxWANTS_CHARS`, but I guess this is a question for another day/PR.

**Pull request merged**
