### PR TITLE
Add wxStandardPaths::GetUserDir() to get Desktop,Download,… folders.

### PR DESCRIPTION
**Pull request by TcT2k**
All major supported platforms have well defined user folders to store Downloads, Music, Pictures, Videos and the Desktop files. The new method wxStandardPaths::GetUserDir() allows for a unified way to access these on MSW, OS X and Unix (if xdg user dirs specification is implemented).

### CODE REVIEW

**Comment by vadz** [comment]
Thanks, this is definitely useful, but I'd prefer to avoid hardcoding the strings for OS X (without speaking about fragility with respect to the future changes, I wonder if this works for non English users even right now?), could you please update the patch to do it? TIA!

**Comment by TcT2k** [comment]
I did change the enums from UserDir_ to Dir_.

I didn't realize that the hard coded values where used in the cocoa build. But as FSFindFolder is deprecated since 10.8 it certainly makes sense to use NSFileManager instead of bringing this CoreFoundation function into the cocoa build. Obviously this would require a new wxStandardPaths class implemented in an .mm file, but I will implement that. It would also get rid of the hardcoded values Library/Preferences and others.

The hard coded values don't seem to be a problem currently, as even localized OS X versions seem to translate the folder names on an UI level instead of the file system. But it is obviously the cleaner approach and probably more future proof to use the OS APIs if available.

**Comment by TcT2k** [comment]
I've now added a Cocoa implementation of wxStandardPaths which uses no hard coded values except for "Preferences" (appended to the /Library retrieved from the system).

If I've understood all #ifdefs correctly wxStandardPathsCF should now be used in Carbon and pure Darwin builds. The hard coded path values (added and existing ones) will only be used in pure darwin builds.

**Comment by vadz** [comment]
Thanks again!

**Comment by MaartenBent** [comment]
This introduces a problem when using gcc on windows:
```
g++ -c -o gcc_mswu\baselib_filename.o  -O2 -mthreads  -DHAVE_W32API_H -D__WXMSW__   -DNDEBUG    -D_UNICODE -I..\..\lib\gcc_lib\mswu -I..\..\include  -W -Wall -DWXBUILDING -I..\..\src\tiff\libtiff -I..\..\src\jpeg -I..\..\src\png -I..\..\src\zlib -I..\..\src\regex -I..\..\src\expat\lib -DwxUSE_GUI=0 -DwxUSE_BASE=1   -Wno-ctor-dtor-privacy -std=c++11 -m32 -march=i686 -Wno-deprecated-declarations  -MTgcc_mswu\baselib_filename.o -MFgcc_mswu\baselib_filename.o.d -MD -MP ../../src/common/filename.cpp
In file included from ..\..\include/wx/stdpaths.h:188:0,
                 from ../../src/common/fileconf.cpp:46:
..\..\include/wx/msw/stdpaths.h:75:44: error: 'GUID' does not name a type
     static wxString DoGetKnownFolder(const GUID& rfid);
                                            ^
makefile.gcc:11947: recipe for target 'gcc_mswu\baselib_fileconf.o' failed
```
This happens for every include of ```stdpaths.h```. The windows headers are included after stdpaths is included, or not included at all.
Adding
```c++
#include "wx/msw/private.h"
```
to ```include/wx/msw/stdpaths.h``` fixes it.

**Pull request closed without merging**
