### PR TITLE
Qt drag and drop - a partial, initial implementation.

### PR DESCRIPTION
**Pull request by jaynabonne**
This is an initial round of code aimed at getting drag and drop to work under wxQt. This implements "drag source" and "drop target", as well as some cleanup and enhancements to the data object.

The code evolved across a number of commits. The initial event hook for connecting the Qt events to the drop target was initially in the window, but it ended up migrating to the "dnd" file itself - that keeps all the DnD code self-contained.

Due to how Qt handles events (as virtual methods and event handlers on the object itself), the connection internally reverses from "window holds drop target" to "drop target connects to window". I don't know if a drop target can be set on more than one window at once, but if it can, then this will need to be revisited. (I just thought of this.)

At this point, drag and drop should work for user types as well as text. (This has been tested on Windows.) wxBitmapDataObject and wxFileDataObject are not yet implemented.

I attempted wxBitmapDataObject early on, and it drove me to nearly consider giving up writing software altogether - and that was just on Windows. Qt has its own thoughts about what the bitmap mime type is ("application-qt-image"), but it's unclear to me still what the actual data format is. Once that's determined, it might not be too bad to implement.

I have made several "clean up" passes over the code, including some directly after reading the coding guidelines. If there are any issues - especially if there are any classes of issues - please let me know. I appreciate you all having cleaned up my code in the past, but unless I do it (as they say) "I'll never learn." Hopefully this is in a better state than some of the previous submissions.

### CODE REVIEW

**Comment by jaynabonne** [comment]
The continuous integration failures don't seem to be related to my code changes, and they're occurring in other merged pull requests (not related to my code). How would I go about fixing this? Thanks.

**Comment by vadz** [comment]
The CI failures are indeed unrelated and have just appeared recently for unknown reasons, we'll do something about them soon (i.e. disable these tests under AppVeyor if no better solution can be found).

I've checked the changes quickly and they look good to me, thanks, even though I didn't really check them in details -- but this is clearly a big improvement, thanks again!

Concerning the code conventions and such, everything also looks mostly fine to me, the only couple of nitpicks I noticed were:

1. We don't indent the namespace contents to avoid having huge parts of code being indented.
1. There is an apparently unrelated removal of `<list>` inclusion which normally shouldn't be part of this PR.

I'll fix both of those myself and merge this soon, thanks again for your efforts!

**Comment by jaynabonne** [comment]
Excellent! Thanks very much. You made my weekend.

I'll remember about the namespaces. Additionally, is the formatting for switch/cases ok? Visual Studio tends to want to line the cases up with the braces, and I've seen it both ways (but I fight with VS to do it the other way).

**Comment by vadz** [comment]
Thank you for your work on this!

As for the switch statement, it's the same as anything else: braces on their own lines, spaces as in the other statements. E.g. (the most general form):
```
switch ( cond )
{
    case xxx:
        ...
        break;

    case yyy:
        ...
        wxFALLTHROUGH();

    case zzz:
        ...
        break;

    default:
        ...
}
```

**Comment by jaynabonne** [comment]
That sounds good - that's the form I've been using. Thanks for the confirmation. :)

**Pull request closed without merging**
