### PR TITLE
Show message box from wxSafeShowMessage() in the other ports too, if possible

### PR DESCRIPTION
**Pull request by vadz**
We probably ought to use `NSAlert` under Mac for this, I might extend this PR to do it if there if nobody tells me it's a bad idea.

### CODE REVIEW

**Comment by vadz** [comment]
I'm finally going to merge this without any Mac-specific changes because, as usual, things didn't turn out the way I thought under Mac: calling `wxMessageBox()` or even just doing
```objc
    NSAlert* alert = [[NSAlert alloc] init];
    [alert setMessageText: wxCFStringRef(title).AsNSString()];
    [alert setInformativeText: wxCFStringRef(text).AsNSString()];
    [alert setAlertStyle: NSWarningAlertStyle];
    [alert runModal];
    [alert release];
```
works fine for showing the message box, but if it's done before the initialization is done, calling `[NSApplication run]` later results in
```
2021-03-14 12:54:51.530509+0100 minimal[65920:1139669] *** Assertion failure in -[NSApplication run], NSApplication.m:3282
```
and I have no idea how to avoid it (and what is actually the condition which fails).

I've also tried using `CFUserNotificationDisplayAlert()` but this warns about blocking main thread (which would be fine) and then doesn't show anything at all.

So, unless @csomor or somebody else tells me how to _safely_ show a message box under Mac, I'm not going to be able to fix this.

**Comment by csomor** [comment]
@vadz I've added a 

`        CFOptionFlags exitButton;
        OSStatus err = CFUserNotificationDisplayAlert(
            0, kCFUserNotificationStopAlertLevel, NULL, NULL, NULL, CFSTR("Title"), CFSTR("Some Text"),
            CFSTR("Default"), CFSTR("Alternate"), CFSTR("Other"), &exitButton );
`

in bool MyApp::OnInit() of minimal sample before wxApp::Init is called, I get the blocking message in the log but also see the message and later the app is started correctly. Which place didn't work for you ?

**Comment by csomor** [comment]
ok, even before the initializers in wxEntryReal the box is shown, so I guess I'm doing something differently, for testing the same could you please use this in wxSafeMessage

```
#elif defined(__WXOSX__)
    (void) CFUserNotificationDisplayAlert(
            0, kCFUserNotificationCautionAlertLevel, NULL, NULL, NULL,
            wxCFStringRef(title), wxCFStringRef(text),
            NULL, NULL, NULL, NULL );
```

**Comment by vadz** [comment]
This is just weird, I have no idea about what is going on here, but now that I've done just:
```diff
diff --git a/samples/minimal/minimal.cpp b/samples/minimal/minimal.cpp
index 470e765423..876b863097 100644
--- a/samples/minimal/minimal.cpp
+++ b/samples/minimal/minimal.cpp
@@ -36,6 +36,23 @@
     #include "../sample.xpm"
 #endif

+#include "wx/osx/private.h"
+
+struct Alert
+{
+    Alert()
+    {
+        fprintf(stderr, "Calling CFUserNotificationDisplayAlert\n");
+        CFUserNotificationDisplayAlert
+        (
+            0, kCFUserNotificationCautionAlertLevel, NULL, NULL, NULL,
+            wxCFStringRef("Alert title"), wxCFStringRef("Alert text"),
+            NULL, NULL, NULL, NULL
+        );
+    }
+} s_alert;
+
+
 // ----------------------------------------------------------------------------
 // private classes
 // ----------------------------------------------------------------------------
```
I can see that it works fine under 10.14 (x64, if it matters), but it still doesn't work under 11.1 (arm64), even though I don't see the message that I saw previously. For the record, it was:
```
% ./samples/minimal/minimal.app/Contents/MacOS/minimal
2021-03-14 12:47:47.669 minimal[65822:1136364] CFUserNotificationDisplayAlert:  called from main application thread, will block waiting for a response.
2021-03-14 12:47:57.941 minimal[65822:1136364] CFUserNotificationDisplayAlert:  called from main application thread, will block waiting for a response.
```
By "doesn't work" I mean there is just no message box shown at all (but `fprintf()` message appears, so I know this code is executed). And it's not related to running the program from the command line, I've also tried `open samples/minimal/*.app` and even double clicking the app from Finder and the results are exactly the same.

This is not critical for me, but this is pretty mysterious, at least to me...

**Pull request merged**
