### PR TITLE
Explicitly mention build environments for Travis CI

### PR DESCRIPTION
**Pull request by MaartenBent**
Two build jobs in Travis are the same, both use gcc without arguments in the Trusty build environment. I suspect the original job was targeted at the Precise build environment. But without specifying the dist, the default will be used, which has been [changed ](https://blog.travis-ci.com/2017-07-11-trusty-as-default-linux-is-coming) to Trusty.

Prevent this by specifying the dist for each job.

Note that this will prevent jobs from automatically switching to Xenial, if Travis ever plans to support it.

### CODE REVIEW

**Comment by MaartenBent** [comment]
Ready for review & merge.

I had to add a workaround to fix checking out the submodules because git doesnt't support `update = checkout` in `.gitmodules` (see [this](https://travis-ci.org/wxWidgets/wxWidgets/jobs/335875708#L133) error), resulting in [missing](https://travis-ci.org/wxWidgets/wxWidgets/jobs/335875708#L1488) Catch headers.

**Comment by vadz** [comment]
Maybe we should just remove `update = checkout` from `.gitmodules`? I originally used it because it looked like the best choice to me, but is it really worth the trouble (both here and for the users stuck with old version of Git)? What do you think?

**Comment by MaartenBent** [comment]
According to the [docs](https://git-scm.com/docs/git-submodule#git-submodule-update--init--remote-N--no-fetch--no-recommend-shallow-f--force--checkout--rebase--merge--referenceltrepositorygt--depthltdepthgt--recursive--jobsltngt--ltpathgt82308203) checkout is the default action when nothing is specified. I will remove it.

**Comment by vadz** [comment]
Thanks, I've rebased this on master (as I didn't want to merge a branch containing 2 not really related commits and I also used this as an opportunity to reformat the commit messages to wrap at 72 text width, as per the unofficial git commit message standard).

**Pull request closed without merging**
