### PR TITLE
CMake: Improve finding  gstreamer, enable D2D

### PR DESCRIPTION
**Pull request by MaartenBent**
Improve finding gstreamer with CMake. And set the correct setup variables, include directories and link libraries.

Disable some debug messages when CMake is searching for packages. Move some `find_package` code to `init.cmake`.

Enable Direct2D graphics context when the `d2d1.h` header is available. Fix building Direct2D renderer with `wxD2D_DEVICE_CONTEXT_SUPPORTED` enabled.

### CODE REVIEW

**Comment by MaartenBent** [comment]
Any objections about installing additional packages on Travis?
For example `libsecret-1-dev`, `libwebkitgtk-dev` and `libgstreamermm-1.0-dev` (also for OpenGL).

**Comment by vadz** [comment]
No, no objections at all.

Would you prefer to make this change in this PR or should I merge it (assuming nobody has any comments about it?) and leave Travis changes to another one? TIA!

**Comment by MaartenBent** [comment]
I'll add it to this PR.

**Comment by MaartenBent** [comment]
What to do about the link error of `test_gui` with `webview`. It says it should not be added. Add `--disable-webview` for this build?
https://github.com/wxWidgets/wxWidgets/blob/master/tests/test.bkl#L279

**Comment by vadz** [comment]
Yes, as written the test clearly can't be linked with `--disable-shared` :-(

Of course, ideal would be to somehow solve the problem at bakefile level (and really ideal would be stop using bakefile 0.x completely...), but for now I think adding `--disable-webview` is the only realistic possibility.

**Comment by vadz** [comment]
Thank you!

**Pull request merged**
