### PR TITLE
Port OSX fixes from my 3.0 branch to master

### PR DESCRIPTION
**Pull request by dkulp**
My app doesn't run with 3.1 yet due to a bunch of incompatibilities so this isn't tested very well.

### CODE REVIEW

**Comment by vadz** [comment]
Any idea about the [Travis build failure](https://travis-ci.org/wxWidgets/wxWidgets/jobs/105884303)?

Also, I'm curious about the incompatibilities: what are they exactly? Maybe it's not too late to fix things in time for 3.1 yet -- but first we need to know what exactly has changed, please let us know (on wx-dev or in a Trac ticket, as you prefer).

**Comment by dkulp** [comment]
I think travis has an older XCode and SDK than I have.   Did a little research and changed the way the center is handled.   Hopefully this works.   

The main incompatibility is that the old CodeBlocks generated code with both wxEXPAND and wxALIGN_CENTRE_HORIZONTAL and then ignored the wxALIGN_CENTRE_HORIZONTAL.   3.1 now pops up an assert warning and then ignores the wxEXPAND.    Thus, things are not laid out correctly.  The new CodeBlocks generates better code, but I have a bunch of other places to fix this as well.

**Comment by dkulp** [comment]
I rebased this on master (as of last night) and have been testing my app (now updated to be usable with 3.1) and everything looks OK.   Any chance of making sure this is in 3.1?

**Comment by vadz** [comment]
I'll do my best to put this in 3.1.0 but I won't hide that this is not the highest priority item in the list of things remaining to do for this release...

**Comment by vadz** [comment]
I think I've applied everything here, but I had to do it manually because I had already applied some of your Trac patches (please use either Trac or PRs, both are fine, but not both at once), so please let me know if I missed anything.

Thanks again for your changes!

**Pull request closed without merging**
