### PR TITLE
MSW fixes after enabling WS_EX_COMPOSITED

### PR DESCRIPTION
**Pull request by vadz**
Fix some of the drawing/refresh problems after enabling double buffering, see #22876.

### CODE REVIEW

**Comment by AliKet** [comment]
I think the following
https://github.com/wxWidgets/wxWidgets/blob/bc07c9a309272b79a8ad5aa4af2b977e8b0c663d/src/msw/notebook.cpp#L183-L219
and the paint handler
https://github.com/wxWidgets/wxWidgets/blob/bc07c9a309272b79a8ad5aa4af2b977e8b0c663d/src/msw/notebook.cpp#L779-L859
can be safely removed after merging this ?

**Comment by vadz** [comment]
@AliKet have you already tested that it worked fine (i.e. without flickering) after setting `USE_NOTEBOOK_ANTIFLICKER` to 0?

Getting rid of this code would definitely be appealing but I'm afraid we may need to keep it for as long as we want to allow using `wxClientDC` with any of the windows in the notebook, as enabling composition for the notebook will probably prevent `wxClientDC` from working anywhere inside it. So we may actually need to still keep it, but only use it when `WS_EX_COMPOSITED` is not set.

**Comment by AliKet** [comment]
> @AliKet have you already tested that it worked fine (i.e. without flickering) after setting `USE_NOTEBOOK_ANTIFLICKER` to 0?
> 

Yes, I tested it and didn't notice any flicker except we would have to keep subclassing the updown button to make it flicker free.

> Getting rid of this code would definitely be appealing but I'm afraid we may need to keep it for as long as we want to allow using `wxClientDC` with any of the windows in the notebook, as enabling composition for the notebook will probably prevent `wxClientDC` from working anywhere inside it. So we may actually need to still keep it, but only use it when `WS_EX_COMPOSITED` is not set.

**Comment by AliKet** [comment]
> > @AliKet have you already tested that it worked fine (i.e. without flickering) after setting `USE_NOTEBOOK_ANTIFLICKER` to 0?
> 
> Yes, I tested it and didn't notice any flicker except we would have to keep subclassing the updown button to make it flicker free.
> 

let me correct myself: the notebook seems to work with no problems **only** when the tabs are in the default position (on top).

So yes the code above should stay as you said and sorry to bother you with that.

**Pull request merged**
