### PR TITLE
macOS small extensions and fixes

### PR DESCRIPTION
**Pull request by csomor**
a collection of small fixes or extensions, instead of opening several PR with just one commit in each …

### CODE REVIEW

**Comment by vadz** [comment]
I guess this should be just disabled for iOS to fix the CI failures?

**Comment by csomor** [comment]
> I guess this should be just disabled for iOS to fix the CI failures?

yes, thanks

**Comment by vadz** [comment]
@csomor I'm going to merge this in a moment with some minor cleanup, please let me know if you have plans to add any more commits to this PR before I merge and close it. TIA!

**Comment by csomor** [comment]
no, that's fine, please go ahead and close it, we'll do a PR for the wxDC pixel accuracy

**Pull request closed without merging**
