### PR TITLE
wxHAS_GENERICDATAVIEWCTRL consistency

### PR DESCRIPTION
**Pull request by artur-so**
I also wonder whether `wxUSE_GENERICDATAVIEWCTRL` in wx/dataview.h is still needed.

```
#if !(defined(__WXGTK20__) || defined(__WXOSX__)) || defined(__WXUNIVERSAL__)
// #if !(defined(__WXOSX__)) || defined(__WXUNIVERSAL__)
    #define wxHAS_GENERIC_DATAVIEWCTRL
#endif

#ifdef wxHAS_GENERIC_DATAVIEWCTRL
    // this symbol doesn't follow the convention for wxUSE_XXX symbols which
    // are normally always defined as either 0 or 1, so its use is deprecated
    // and it only exists for backwards compatibility, don't use it any more
    // and use wxHAS_GENERIC_DATAVIEWCTRL instead
    #define wxUSE_GENERICDATAVIEWCTRL
#endif
```

### CODE REVIEW

**Comment by artur-sochirca** [comment]
Not very familiar with git.
I intended to make a PR with only d565b438707860aefe69df22ac83171f2450d099 commit.

**Comment by vadz** [comment]
As the comment says, this symbol is preserved for backwards compatibility and it doesn't cost much to keep it, so let's not remove it for now.

I'll apply your commit removing another occurrence of it however, thanks.

For your next PRs, the workflow normally is to:

1. Update your clone master from the upstream (this one) repository
1. Make a branch for your changes
1. Do commit your change there
1. Push the branch to GitHub and make a PR

**Comment by artur-sochirca** [comment]
Thank you!
So a branch makes sense even for minor changes. I suspected this.

Could you please advise: what is the canonical way of defining `wxHAS_GENERICDATAVIEWCTRL` in case generic implementation is desired for platforms where native is available?

**Comment by vadz** [comment]
I think you should be able to just predefine `wxHAS_GENERIC_DATAVIEWCTRL` in your makefile, but I haven't really tested this.

**Comment by artur-sochirca** [comment]
Will give it a try, thanks!

**Pull request closed without merging**
