### PR TITLE
Add missing data files for regenerating locale list

### PR DESCRIPTION
**Pull request by utelle**
1) Data files downloaded from Unicode
2) Unicode Data Files and Software license
3) List of known Windows locales (generated by showfiles utility)

### CODE REVIEW

**Comment by utelle** [comment]
The Whitespace Check fails for the data files downloaded from Unicode. The problem is that it wouldn't help to remove the whitespace manually, because the next download from Unicode would bring it back. Is it somehow possible to exclude those files from the check?

**Comment by vadz** [comment]
I think it's simpler to just remove the whitespace and then either do it again after the next update (which probably won't happen very soon) or remove it in the regeneration scripts (which shouldn't be difficult neither, but Lua is my 17th language so I'm not exactly sure how...).

So if you don't mind, I'll just push this as is (well, after removing whitespace) for now.

And thanks for the update, of course!

**Comment by utelle** [comment]
> I think it's simpler to just remove the whitespace and then either do it again after the next update (which probably won't happen very soon) or remove it in the regeneration scripts (which shouldn't be difficult neither,

You are absolutely right. After downloading the files trailing whitespace can be removed from them with a simple script. I will add that to the download step.

> but Lua is my 17th language

Mine, too (depending on in which order I count them). 😃 

> So if you don't mind, I'll just push this as is (well, after removing whitespace) for now.

Please wait a short time to allow me to add the automatic whitespace removal.

**Comment by vadz** [comment]
I'll merge this in a moment, thanks again!

**Pull request merged**
