### PR TITLE
Add version suffix to gettext catalog files

### PR DESCRIPTION
**Pull request by andriybyelikov**
Modify install script to install catalog files with version suffix
Modify translation.cpp to look for suffixed catalog first

See https://groups.google.com/g/wx-users/c/L9gC8UgrO6Y

You might want to check whether I generated something unwanted with bakefile_gen on Arch Linux. I don't think the samples' VS *.sln solutions should be there so you might want to add that to .gitignore. Also in Makefile.in some 'dll' occurences got replaced by 'lib'. It may be a Linux thing. I'll reach you out on the wx-users maling list soon for some updates and questions.

### CODE REVIEW

**Comment by vadz** [comment]
Thanks! There are/will be some minor conflicts with #2213 (I wanted to notify you about it after merging it, but probably should have done this sooner), but I can resolve those and this looks good otherwise.

@lanurmi @vslavik Just in case I'm missing something again, please let me know if you see anything wrong with using version-specific `.mo` files. TIA!

**Comment by lanurmi** [comment]
I didn't test this branch myself, but it is possible that the fallback to `"wxstd"` without version number will not work properly on MSW because of [#18227](https://trac.wxwidgets.org/ticket/18227).

**Comment by vslavik** [comment]
The fallback is presumably intended for deployment compatibility, so I think this should be OK -- it's unlikely you'd want to use *both* versioned and unversioned files, and a mix of them for different languages. As long as either `wxstd.mo` *or* `wxstd-x.y.mo` files are present, but not both, it will work correctly, no?

**Comment by vadz** [comment]
> As long as either `wxstd.mo` or `wxstd-x.y.mo` files are present, but not both, it will work correctly, no?

Yes, this is what I think too. But, @lanurmi, please let me know if I'm missing something here.

**Comment by andriybyelikov** [comment]
> As long as either `wxstd.mo` _or_ `wxstd-x.y.mo` files are present, but not both, it will work correctly, no?

I actually ended up implementing it as x.y.z and not just x.y using the wxVERSION_NUM_DOT_STRING_T macro. In case there are updates to the catalog between micro versions.

**Comment by vadz** [comment]
> > As long as either `wxstd.mo` _or_ `wxstd-x.y.mo` files are present, but not both, it will work correctly, no?
> 
> I actually ended up implementing it as x.y.z and not just x.y using the wxVERSION_NUM_DOT_STRING_T macro. In case there are updates to the catalog between micro versions.

I don't think we support installing 2 different micro versions alongside, so IMO we shouldn't use it here neither. I.e. I'd rather use `WX_RELEASE` in the makefile and `"wxstd-" wxSTRINGIZE(wxMAJOR_VERSION) "." wxSTRINGIZE(wxMINOR_VERSION)` in the code.

Any objections?

**Comment by andriybyelikov** [comment]
> I don't think we support installing 2 different micro versions alongside, so IMO we shouldn't use it here neither. I.e. I'd rather use `WX_RELEASE` in the makefile and `"wxstd-" wxSTRINGIZE(wxMAJOR_VERSION) "." wxSTRINGIZE(wxMINOR_VERSION)` in the code.
> 
> Any objections?

I think this would only be a problem if there are incompatible changes in the catalogs between micro versions, but if there aren't then it's completely fine to just use a MAJOR.MINOR suffix. Should I do another commit fixing this or will you do it?

**Comment by andriybyelikov** [comment]
> I don't think we support installing 2 different micro versions alongside, so IMO we shouldn't use it here neither. I.e. I'd rather use `WX_RELEASE` in the makefile and `"wxstd-" wxSTRINGIZE(wxMAJOR_VERSION) "." wxSTRINGIZE(wxMINOR_VERSION)` in the code.
> 
> Any objections?

I think this would only be a problem if there are incompatible changes in the catalogs between micro versions, but if there aren't then it's completely fine to just use a MAJOR.MINOR suffix. Should I do another commit fixing this or will you do it?

**Comment by vadz** [comment]
No, thanks, I can/will do this myself and will push this soon.

**Pull request closed without merging**
