### PR TITLE
Qt bitmap crash

### PR DESCRIPTION
**Pull request by ffa-grahamdawes**
Fixed for crashing bitmap test with wxQT. wxBitmap is now implemented using QImage rather QPixmap as QImage better aligns with the wxBitmap API

### CODE REVIEW

**Comment by ffa-grahamdawes** [comment]
Hi, 

Thanks for the feedback.  The crash was in BitmapTestCase::OverlappingBlit GetRawData.  Unfortunately wxPixmap doesn't provide access to the raw image data so the previous wxQT wxBitmap implementation created a temporary QImage and return a pointer to its data.    If the checks for bit depth and transparency where successfully the pointer returned would point to the buffer in temporary.

However, what was happening in the test was that the check for transparency was falling through as the generated QImage wasn't in a format that contained an alpha channel (presumably as the source QPixmap didn't have any transparency information).   This resulted in GetRawData returning NULL and the test crashing. 

I've added an additional assertion to the test so that the test fails gracefully if the wxAlphaPixelData is not valid.

**Comment by ffa-grahamdawes** [comment]
As a follow up to this,  I've also fixed wxMemoryDC for wxQT.  QPainter can draw to instances of QImage and not QPixmap so the previous implementation was drawing to an internal image and not the originally selected wxBitmap.

**Comment by vadz** [comment]
@catalinr, @reingart and any other people knowing anything about Qt, could you please have a look at this change and let me know what do you think of it? TIA!

**Comment by ffa-grahamdawes** [comment]
OK Fair point.  I'll re implement the wxGraphicsContext and wxMemoryDC changes on a new branch a leave wxBitmap as it stands.

**Comment by vadz** [comment]
Concerning raw pixels access: it's common to convert the internal representation into something that allows efficient pixel access in `GetRawData()` and convert it back in `UngetRawData()` -- this is what these functions are for, in fact. So perhaps the way to provide raw pixel access (which is not mandatory but pretty important nevertheless) would be to convert `QPixmap` to `QImage` in the former and convert it back in the latter?

**Comment by ffa-grahamdawes** [comment]
Would it be accept to keep this image around as a field?  This will fix one of the original issues with the image in that it's returning a temporary buffer.   The image would be "null" until GetRawData() is called then null'ed after UngetRawData().

I could also re-incorporate the changes that ensure that raw pix buffer is in the correct format (number of bytes per component, endianess etc).

**Comment by vadz** [comment]
I've finally looked at the code (sorry, I should have done this sooner) and it's indeed clearly wrong, we can't return a dangling pointer from `wxBitmap::GetRawData()` like this. And, indeed, the simplest fix would be to keep a `QImage *m_imageRaw` as a field in `wxBitmap` itself, allocate it in `GetRawData()` and destroy it in `UngetRawData()`. If you could please do it, it would be great. TIA!

**Comment by ffa-grahamdawes** [comment]
I'll make this change on a new branch and summit it as a new PR.

**Pull request closed without merging**
