### PR TITLE
Fix the issue with a last DVC column width on Mac

### PR DESCRIPTION
**Pull request by thesiv**
In Cocoa implementation of `wxDataViewControl`: call
`sizeLastColumnToFit` function of `NSTableView` in `OnSize` handler
(for any amount of columns, previously this function was called only
for a singe colunm DVCs).

`sizeLastColumnToFit` resizes the last column so the table view fits
exactly within its enclosing clip view.

This behavior is equivalent to `gtk` and `MSW` realizations.

### CODE REVIEW

**Comment by vadz** [comment]
Testing dataview sample under macOS 10.14.4 _without_ this patch, the last column seems to be already mostly resized correctly and I don't see any change in behaviour with this patch when I apply it. Could you please remind me what exactly the original problem was, i.e. how can it be reproduced? TIA!

**Comment by thesiv** [comment]
Currently the utit tests are not check width of the last column when there are more then one column. I add the test for the case with multiple columns: https://github.com/wxWidgets/wxWidgets/pull/1449

**Comment by thesiv** [comment]
Add the corresponding test (fixed) from the https://github.com/wxWidgets/wxWidgets/pull/1449 PR.

**Comment by vadz** [comment]
Thanks, I finally see the problem with this test case, so I'm merging it.

**Pull request merged**
