### PR TITLE
Fix problem with wxASSERT when using wxELLIPSIZE_NONE mode

### PR DESCRIPTION
**Pull request by wacekgocki**
This patch fixes problem caused by changes made with commit [44bcc3a723c082a825943953ee5f13c2fc6dff85](https://github.com/wxWidgets/wxWidgets/commit/44bcc3a723c082a825943953ee5f13c2fc6dff85)

An assert fires in DoEllipsizeSingleLine function when using wxELLIPSIZE_NONE mode. In the previous versions there was a check in the code, which did not execute ellipsize functions when user specified wxELLIPSIZE_NONE mode. The commit mentioned above removed this check, my patch brings it back.

### CODE REVIEW

**Comment by vadz** [comment]
AFAICS the only place where `Ellipsize()` can be called with `NONE` mode since 44bcc3a is from `wxRendererGeneric::DrawItemText()`, is this right? If so, I'd prefer to actually avoid calling it from there in this case, IMHO it's slightly preferable to avoid calling the function completely rather than dealing with this case inside it.

**Comment by wacekgocki** [comment]
There is also wxDataViewRenderer::DisableEllipsize.
And you can use wxELLIPSIZE_NONE in wxDataViewRenderer::EnableEllipsize().

**Comment by wacekgocki** [comment]
I suppose that you are right about the current usage of ``Ellipsize``. But it's a public method of ``wxControlBase`` and it can be used somewhere else in the future code, so I think it's better to deal with the case inside the ``Ellipsize``.

**Comment by vadz** [comment]
OK, let's do it like this, thanks.

**Pull request closed without merging**
