### PR TITLE
Fix GTK+ part of spinctrl problem

### PR DESCRIPTION
**Pull request by dvertx**
Related to ticket #18805 in wxTrac
Mitigate problem in GTK only

### CODE REVIEW

**Comment by vadz** [comment]
Sorry, but could you please explain what does this actually do? I.e. what behaviour does this patch implement and why is it desirable?

After looking at the Trac ticket, I think we really should just avoid negative values in hex spin controls completely, there doesn't seem to be any good reason to support them and MSW can't do it anyhow, so why bother?

**Comment by dvertx** [comment]
The patch for GTK above tries to resolve the need for spin control to accommodate negative hexadecimal values. I understand the code itself could be made somewhat simpler with better flow, with enough time.

I'm not sure about Windows, but other widgets toolkits such as GTK and Qt have numerous usage for spin control types:
- [https://gitlab.gnome.org/GNOME/gtk/-/blob/master/demos/gtk-demo/spinbutton.c](https://gitlab.gnome.org/GNOME/gtk/-/blob/master/demos/gtk-demo/spinbutton.c)
- [https://doc.qt.io/qt-5/qtwidgets-widgets-spinboxes-example.html](https://doc.qt.io/qt-5/qtwidgets-widgets-spinboxes-example.html)
Wouldn't there be a possibility to enhance wxSpinCtrl in a similar fashion?

**Comment by vadz** [comment]
I'm sorry, but I don't see any examples of using hexadecimal notation for negative numbers in neither GTK nor Qt link. Why would we want to support something that nobody uses? IMNSHO it's just not worth it.

Please let me know if you have a realistic use case important enough to justify spending time on this.

**Comment by dvertx** [comment]
You are right, there aren't any example of negative hexadecimal number handling in the link I provided.
Herewith my renewed and rebased commit. Waiting for your review. TIA

**Comment by vadz** [comment]
I'm sorry, I'm still not sure what problem does this fix exactly. Could you please give a scenario in which the control behaves incorrectly right now and for which this patch improves things?

FWIW I mean "forbid setting min < 0" by "not supporting" the use of negative numbers with hexadecimal base, but this patch does something very different.

Although, on a completely unrelated topic, have you actually tested GTK1 changes? It's perfectly fine to not change it, but as long as we keep it in the tree, it should still at least compile.

**Comment by dvertx** [comment]
> I'm sorry, I'm still not sure what problem does this fix exactly. Could you please give a scenario in which the control behaves incorrectly right now and for which this patch improves things?

Currently the problem is the same as what the original wxTrac ticket [#18805](https://trac.wxwidgets.org/ticket/18805) post mentioned, where under wxGTK the value in _wxSpinCtrl_ changes from 0x0000 to 0xffffffffffffffff to 0x0009. I assume the OP changes the **min** number to a negative value (such as -2) and left the **max** number at 10, which is why unexpectedly 0xffffffffffffffff later turns into 0x0009. 0xffffffffffffffff is regarded as > 10 by wxSpinCtrl.
The patch tries to maintain manual entry into _wxSpinCtrl_ and the display of _wxSpinCtrl_ to be between 0 and max value. The patch is for GTK version only.
 
> FWIW I mean "forbid setting min < 0" by "not supporting" the use of negative numbers with hexadecimal base, but this patch does something very different.

Even though using direct gtk function calls while trying to be not much different in functionality than the original, I agree it did ended up much too convoluted. In this new commit I’m using all of the original code.

> Although, on a completely unrelated topic, have you actually tested GTK1 changes? It's perfectly fine to not change it, but as long as we keep it in the tree, it should still at least compile.

No, I tested with GTK2 and GTK3 only. Sure, I won’t change the GTK1 original code.

**Pull request closed without merging**
