### PR TITLE
Update textctrl.cpp

### PR DESCRIPTION
**Pull request by Captain-FLAM**
Won't compile else if wxUSE_RICHEDIT = 0

### CODE REVIEW

**Comment by vadz** [comment]
What is the compilation problem exactly without the first change? I don't see anything wrong in the code but I believe we should have `#if wxUSE_RICHEDIT` around the method declaration too to avoid _link_ errors, is this what you mean? If so, I'll fix this, but please let us know if there was something else.

As for the second commit, it seems completely unrelated, so I assume it was just accidental, but, again, please let me know if it wasn't.

**Comment by Prince-David** [comment]
1 - look after the function called : MSW create context menu ...
2 - if you don't tell about the lib to the linker, it WON'T build ... it's not accidental
...
and 3 - this is what I NEEDED to obtain my custom dll ( i'm not a joker ;-) , I just corrected the bugs that my compiler gave me (Mingw64 on Win 7), using .gcc files)
Try the options I mentioned by yourself ...

**Comment by vadz** [comment]
I thought it was accidental because it didn't have anything to do with the subject of this PR (i.e. "build problems with `wxUSE_RICHEDIT==0`"). I still don't see why is it needed though, all D2D DLLs are supposed to be loaded dynamically. Could you please create another PR for this problem to not mix up everything?

Also, I don't think you're joking, but please try to make your PRs more useful, i.e. at the very least please explain the problem (in this case, compiler or linker error messages) before just giving the (not always right, as the example of the first commit showed) solution. Thanks in advance!

**Comment by Prince-David** [comment]
I will try to be more concise and I re-submit its.
I'm not used to GitHub, and I committed to 2 PR at the same time, but with different comments ;-)

**Pull request closed without merging**
