### PR TITLE
Update filedlg.cpp

### PR DESCRIPTION
**Pull request by charvey2718**
Fixes for issue #10924

### CODE REVIEW

**Comment by vadz** [comment]
Thanks, but could you please extract this into a trivial function in the beginning of this file, to make updating it later easier?

And, in fact, thinking more about it, I think we may want to amend this slightly by breaking from the loop after some big (1000? 10000?) number of iterations, just to be 100% sure that we don't get stuck forever if the user has a vibrating mouse generating events all the time or something other like this, which seems impossibly contrived and unrealistic until you run into it in practice...

**Comment by charvey2718** [comment]
No worries - I'll get onto this later.

**Comment by charvey2718** [comment]
@vadz I've done as you requested. Can you see the improvements as part of this PR or do I need to renew it somehow?

charvey2718 is fine for the change log, thanks.

**Comment by vadz** [comment]
Thanks! I'm going to merge this in master with some minor changes (mostly more comments to explain what's going on here and, also, a better commit message) soon and also apply it to 3.2 branch so that it is included in the upcoming 3.2.3 release.

**Comment by DRNadler** [comment]
Please note: This is a general problem for any dialog containing a wxListBox for example (probably any control that processes a double-click). If the handler dismisses the dialog, the left-up or move events may happen after the dialog is dismissed... See #25446

**Pull request closed without merging**
