### PR TITLE
Enable Retina (HiDPI) support on OSX wxGLCanvas

### PR DESCRIPTION
**Pull request by swt2c**
Fixes https://trac.wxwidgets.org/ticket/15700

### CODE REVIEW

**Comment by dkulp** [comment]
Note:  this will LIKELY break everyone's use of OpenGL canvases on OSX.    Once you do this, things like setting the viewport and such will need to be in actual pixel coordinates (taking the content scale factor into account) and not just the return of canvas->GetSize() or similar.   Any mouse events and such that need to associate mouse coordinates (in window positions) would also have to be adjusted.    

That said, I do think this is needed and long overdue.  :)     Just kind of wondering if it make sense to make it a style flag (and thus disable-able) or not for compatibility.

**Comment by swt2c** [comment]
@dkulp I don't have much interest in the OSX port so if you feel strongly about having a flag for this, feel free to propose an alternative patch.  IMO, it should at least default to on so that GTK and OSX ports act the same by default.

**Comment by vadz** [comment]
It looks like we already do this in wxGTK3, i.e. the cube OpenGL sample uses just 1/4 of the window as the viewport. So maybe we should indeed just do it for wxMac too, and not worry about adding a function to enable it, as I suggested in the bug 6 years ago?

Of course, it would break any currently working code, but I don't know how much code using OpenGL and high DPI displays is there, considering that Apple doesn't support OpenGL anyhow.

Any thoughts?

**Comment by swt2c** [comment]
Yeah, it seems to me it would be better to be consistent between platforms.

**Comment by vadz** [comment]
After thinking more about it, you're right and I'll apply this, as well as #1470 (thanks for fixing this!) and document this.

**Pull request closed without merging**
