### PR TITLE
wxOSX use Cocoa native insets

### PR DESCRIPTION
**Pull request by csomor**
For 3.2 we can use the meanwhile introduced API

### CODE REVIEW

**Comment by csomor** [comment]
Regarding the clipping of the buttons at least under macOSX : there the native layout rectangle only includes the 'white' area, but not the border line, so if we clip at the layout rectangle this will clip the delimiting line of the button.

**Comment by vadz** [comment]
Thanks a lot Stefan!

At the code level this is, of course, a very welcome change, but I didn't have time to check if this fixes both issues, so I'm not sure if it does or if something else/more is still needed?

In any case, I believe we should merge this before 3.1.7 to get more testing.

**Comment by csomor** [comment]
> At the code level this is, of course, a very welcome change, but I didn't have time to check if this fixes both issues, so I'm not sure if it does or if something else/more is still needed?

the clipping problem is still partially there, because - I don't know whether this started with 11 or 12 - the border does not count ...

> In any case, I believe we should merge this before 3.1.7 to get more testing.

yes, definitely

**Comment by vadz** [comment]
So should I merge this one already?

**Comment by csomor** [comment]
> So should I merge this one already?

I thought we might discuss a solution to the clipping problem as well, but it's not really worse with that patch than before ... then perhaps a merge would be wise and we continue about the clipping after ..

**Comment by csomor** [comment]
Ok, I've compared 10.14 layout to 12.3 layout. Under older systems indeed the 12 pt distance is applied between the borders, under 12.3 the inset is 1 pixel more at left, top and right, but not bottom ... thus measuring between the area, which is more in line with dark appearance or a default button (which have no frame under 12.3)

so basically right now under 12.3 a pushbutton would draw its frame in light appearance outside its wxRect = alignmentRect, while dark buttons and the default button stay inside. macOS - always ready to surprise you ...

**Comment by csomor** [comment]
Illustrating the things I wrote above:

macOS 10.14
macOS1014

macOS 12.3
macOS1203

**Comment by vadz** [comment]
> > So should I merge this one already?
> 
> I thought we might discuss a solution to the clipping problem as well, but it's not really worse with that patch than before ... then perhaps a merge would be wise and we continue about the clipping after ..

Whatever is more convenient for you, but personally I think that fixing one problem is already progress and so would merge this now. Especially because I have absolutely no idea what to do about the remaining clipping problem, so I don't risk solving it on my own in any case.

> macOS - always ready to surprise you

To you it's just a surprise, to me it looks like it's actively trying to work against me each time I look at it :-/

**Comment by csomor** [comment]
> Whatever is more convenient for you, but personally I think that fixing one problem is already progress and so would merge this now.

Ok, then please go ahead :-) Thanks

**Pull request closed without merging**
