### PR TITLE
Fix compilation on recent FreeBSDs by linking against epoll-shim

### PR DESCRIPTION
**Pull request by lanurmi**
On recent FreeBSDs, the "Linux-only" `<sys/epoll.h>` exists in the default
include path, and is thus detected by configure. However, on FreeBSD the
epoll API is implemented in a library, `epoll-shim`, which needs to be
linked along with the wx libraries to anything using wx.

(The epoll-shim library is available for other *BSD too, but at least on OpenBSD
it's not on the default include path, and doesn't get detected by configure
without adjusting `CFLAGS`, and for that reason there is no issue with compilation,
and this PR doesn't need to address other *BSD.)

### CODE REVIEW

**Comment by vadz** [comment]
Thanks, we can merge it to fix the build, but I'm not quite sure if this is the best solution: do you think there are any advantages to using `epoll` under FreeBSD? Presumably it's implemented as a wrapper for `poll` and/or `select` there anyhow, so why not just use them directly and avoid a dependency on an extra library?

I.e. maybe we should just restrict the check for `sys/epoll.h` to Linux only?

**Comment by lanurmi** [comment]
> Thanks, we can merge it to fix the build, but I'm not quite sure if this is the best solution: do you think there are any advantages to using `epoll` under FreeBSD? Presumably it's implemented as a wrapper for `poll` and/or `select` there anyhow, so why not just use them directly and avoid a dependency on an extra library?

TBH I was not familiar with `epoll` at all before this PR, but as far as I understand and the documentation states, FreeBSD's `epoll-shim` is implemented as a wrapper for `kqueue`, which is more efficient than using `poll`/`select`. Does make any difference the way wx uses `epoll`, though? No idea.

> I.e. maybe we should just restrict the check for `sys/epoll.h` to Linux only?

This is the other approach I had in mind. It would be safer; fewer surprises.

**Comment by vadz** [comment]
I admit I don't know neither, but it would make more sense for wx to use kqueue directly if it's worth it (we even already use it for wxFSWatcher, but not for this), so I think I'd prefer to not use epoll under FreeBSD.

Maybe the simplest would actually be to just add a link check? Like this, we'd only use it if we don't need any extra libraries to link with it, which would cover Linux but maybe also some other system if it implements it (but AFAIK currently it's only natively supported under Linux and this seems unlikely to change as now it's all about ioring anyhow...).

**Comment by lanurmi** [comment]
I now committed the safest solution, i.e. ignoring `sys/epoll.h`'s existence if the operating system is not Linux.

The latter commit essentially reverts the changes of the first one, so these two __should probably be squashed__ together, if the latter solution is chosen.

**Comment by vadz** [comment]
Thanks! I agree that this is the safest solution and will (squash) merge it soon.

**Pull request closed without merging**
