### PR TITLE
Let GTK itself handle key events

### PR DESCRIPTION
**Pull request by ghost**
Hello.
wxTextCtrl and wxTextEntry doesn't reset input method when mouse is clicked due to improper use of GTKIMContext.
So, the last character of Hangul is malfunctioning when mouse is clicked.
However, GtkEntry and GtkTextView reset the input method if necessary when the mouse is clicked.
GtkEntry and GtkTextView have no problem.
This patch allows the GTK itself to handle key events.
~~No side effects.~~
Do not test with ibus. The ibus itself has a bug.
Test with nimf or imhangul.

For information about nimf, visit https://nimf-i18n.gitlab.io/installation/

Related issues with the Hangul last character bugs:

https://bugs.chromium.org/p/chromium/issues/detail?id=966148
https://bugs.eclipse.org/bugs/show_bug.cgi?id=371397
https://bugs.documentfoundation.org/show_bug.cgi?id=117008
https://github.com/ibus/ibus/issues/1282

### CODE REVIEW

**Comment by cogniti** [comment]
This patch seems to have a slight problem in its behavior. I will test it again.

**Comment by vadz** [comment]
Thanks for the patch, but I have some doubts about it: I don't know much about IME, but I don't understand how does this work: if we don't call `gtk_entry_im_context_filter_keypress()`, we just ignore the key completely, so at the very least we shouldn't generate the key event correctly for it. Have you tested this change in the `keyboard` sample? Does it work correctly there?

And when you say "improper use of GTKIMContext", do you know what the "proper use" would be? What exactly are we doing wrong?

Also, where exactly does the problem happen? Chromium bug is about MSW, not GTK. Is this specific to GTK 2 or does it happen with 3 (also/only?)?

**Comment by cogniti** [comment]
Thank you for your reply.
I am sorry. I did not have enough explanation.

When we type CJK, the input method uses preedit.
So when we click the mouse button, input method should be reset if needed.
When the input method is reset, the input method determines whether to commit the preedit or not. `GtkIMContext` is the interface for input methods.

`GtkEntry` resets im_context when we click the mouse button.

```
static void
gtk_entry_move_cursor (GtkEntry       *entry,
		       GtkMovementStep step,
		       gint            count,
		       gboolean        extend_selection)
{
  GtkEntryPrivate *priv = entry->priv;
  gint new_pos = priv->current_pos;

  gtk_entry_reset_im_context (entry);
  ...
```

But, `GtkEntry` resets im_context only when "priv->need_im_reset == TRUE".

```
void
gtk_entry_reset_im_context (GtkEntry *entry)
{
  GtkEntryPrivate *priv = entry->priv;

  g_return_if_fail (GTK_IS_ENTRY (entry));

  if (priv->need_im_reset)
    {
      priv->need_im_reset = FALSE;
      gtk_im_context_reset (priv->im_context);
    }
}
```

```
static void
gtk_entry_class_init (GtkEntryClass *class)
{
...
  widget_class->key_press_event = gtk_entry_key_press;
...
```

GtkEntry has its own handler.

```
static gint
gtk_entry_key_press (GtkWidget   *widget,
		     GdkEventKey *event)
{
...
  if (priv->editable)
    {
      if (gtk_im_context_filter_keypress (priv->im_context, event))
	{
	  priv->need_im_reset = TRUE;
	  retval = TRUE;
          goto out;
	}
```

Using `gtk_entry_im_context_filter_keypress()` directly does not change `need_im_reset`.

```
gboolean
gtk_entry_im_context_filter_keypress (GtkEntry    *entry,
                                      GdkEventKey *event)
{
  GtkEntryPrivate *priv;

  g_return_val_if_fail (GTK_IS_ENTRY (entry), FALSE);

  priv = entry->priv;

  return gtk_im_context_filter_keypress (priv->im_context, event);
}
```

```
int wxTextEntry::GTKIMFilterKeypress(GdkEventKey* event) const
{
    int result;
#if GTK_CHECK_VERSION(2, 22, 0)
#ifndef __WXGTK3__
    result = false;
    if (gtk_check_version(2,22,0) == NULL)
#endif
    {
        result = gtk_entry_im_context_filter_keypress(GetEntry(), event);
    }
#else // GTK+ < 2.22
    wxUnusedVar(event);
    result = false;
#endif // GTK+ 2.22+

    return result;
}
```

```
void wxWindowGTK::ConnectWidget( GtkWidget *widget )
{
...
    g_signal_connect (widget, "key_press_event",
                      G_CALLBACK (gtk_window_key_press_callback), this);
```

```
static gboolean
gtk_window_key_press_callback( GtkWidget *WXUNUSED(widget),
                               GdkEventKey *gdk_event,
                               wxWindow *win )
{
...
        const int intercepted_by_IM = win->GTKIMFilterKeypress(gdk_event);
```

wxTextCtrl --> wxControl --> wxWindow

Forget about chromium bugs. It is just to introduce the last character bug when typing Hangul.
If `GTKIMFilterKeypress` returns false, this issue is solved immediately, but another issue may occur in "copy and paste" etc. I have not tested it yet. And I have not tested the keyboard sample yet.

**Comment by cogniti** [comment]
wxWidgets is an excellent toolkit that is widely used. Fixing this bug may cause other bugs. So let's fix it with enough time. I will help you.

**Comment by vadz** [comment]
Thanks for the detailed explanation!

So, if I understand you correctly, the actual problem is that `need_im_reset` is `FALSE` when `gtk_entry_move_cursor()` is called due to a mouse click, right? If so, I can indeed see that this is the case from the code and, unfortunately, I don't see how to fix this: we can't access `need_im_reset` itself and we can't call `gtk_im_context_reset()` ourselves neither because `_gtk_entry_get_im_context()` accessor for it is private and can't be used from outside the library.

IMO GTK itself is broken here as it exposes `gtk_entry_im_context_filter_keypress()` which it advises to use if you need to do any kind of key handling, but calling this public function puts `GtkEntry` into an inconsistent state because it doesn't set `need_im_reset` to `TRUE` as it's done when the equivalent of this function is called from inside GTK (both places calling `gtk_im_context_filter_keypress()` do `need_im_reset = TRUE` if it returns true). It would be nice to fix the problem there but, even if such patch were accepted, and I have no idea how realistic this is, it won't help with all the existing GTK versions, of course. As an aside, judging from the results of [searching for it](https://github.com/search?l=C%2B%2Bq=gtk_entry_im_context_filter_keypress&type=Code), we're the only ones to use this function and now I see why -- it's just unusable...

Returning to this PR, it should fix this particular problem, of course. But I'm still afraid it breaks `wxEVT_KEY/CHAR` event generation for non-ASCII symbols and I'm not sure it's a good trade off. I still didn't have time to test it, but we wouldn't have added all this IM-related code without need, see the commit b2c357747dd.

**Comment by cogniti** [comment]
> the actual problem is that `need_im_reset` is `FALSE` when `gtk_entry_move_cursor()` is called due to a mouse click, right?

Right.
I am testing wxWidgets 3.0.4 on Debian Linux Buster for convenience.
It is difficult to fix all at once.

```c
#include <gtk/gtk.h>

static gboolean
on_key_press_event_before (GtkWidget *widget,
                           GdkEvent  *event,
                           gpointer   user_data)
{
  g_message ("on_key_press_event_before");
  /* FALSE to propagate the event further */
  return FALSE;
}

static gboolean
on_key_press_event_after (GtkWidget *widget,
                          GdkEvent  *event,
                          gpointer   user_data)
{
  g_message ("on_key_press_event_after");
  /* This handler is not called if the GtkEntry's own handler returns TRUE. */
  return FALSE;
}

static void
activate (GtkApplication* app,
          gpointer        user_data)
{
  GtkWidget *window;
  GtkWidget *entry;
 
  window = gtk_application_window_new (app);
  gtk_window_set_title (GTK_WINDOW (window), "Test");
  gtk_window_set_default_size (GTK_WINDOW (window), 200, 200);
  entry = gtk_entry_new ();
  g_signal_connect (entry, "key-press-event",
                    G_CALLBACK (on_key_press_event_before), NULL);
  g_signal_connect_after (entry, "key-press-event",
                          G_CALLBACK (on_key_press_event_after), NULL);
  gtk_container_add (GTK_CONTAINER (window), entry);
  gtk_widget_show_all (window);
}
 
int
main (int    argc,
      char **argv)
{
  GtkApplication *app;
  int status;
 
  app = gtk_application_new ("org.gtk.example", G_APPLICATION_FLAGS_NONE);
  g_signal_connect (app, "activate", G_CALLBACK (activate), NULL);
  status = g_application_run (G_APPLICATION (app), argc, argv);
  g_object_unref (app);
 
  return status;
}
```

```
gcc -o event event.c `pkg-config --cflags --libs gtk+-3.0`
```

In src/gtk/window.cpp

How about changing this code

```
    g_signal_connect (widget, "key_press_event",
                      G_CALLBACK (gtk_window_key_press_callback), this);
```
to the following code?

```
    g_signal_connect (widget, "key_press_event",
                      G_CALLBACK (gtk_window_key_press_before_callback), this);
    g_signal_connect (widget, "key_press_event",
                      G_CALLBACK (gtk_window_key_press_after_callback), this);
```

**Comment by cogniti** [comment]
I am testing wxWidgets 3.0.4 on Debian Linux Buster for convenience.

```
static gboolean
gtk_window_key_press_callback_before( GtkWidget *WXUNUSED(widget),
                                      GdkEventKey *gdk_event,
                                      wxWindow *win )
{
    if (g_blockEventsOnDrag)
        return TRUE; /* TRUE to stop other handlers from being invoked for the event. */

    wxPROCESS_EVENT_ONCE(GdkEventKey, gdk_event);

    wxKeyEvent event( wxEVT_KEY_DOWN );
    bool ret = false;

    if( wxTranslateGTKKeyEventToWx(event, win, gdk_event) )
    {
        // Send the CHAR_HOOK event first
        if ( SendCharHookEvent(event, win) )
        {
            // Don't do anything at all with this event any more.
            return TRUE;
        }

        // Next check for accelerators.
#if wxUSE_ACCEL
        wxWindowGTK *ancestor = win;
        while (ancestor)
        {
            int command = ancestor->GetAcceleratorTable()->GetCommand( event );
            if (command != -1)
            {
                wxCommandEvent menu_event( wxEVT_MENU, command );
                ret = ancestor->HandleWindowEvent( menu_event );

                if ( !ret )
                {
                    // if the accelerator wasn't handled as menu event, try
                    // it as button click (for compatibility with other
                    // platforms):
                    wxCommandEvent button_event( wxEVT_BUTTON, command );
                    ret = ancestor->HandleWindowEvent( button_event );
                }

                break;
            }
            if (ancestor->IsTopLevel())
                break;
            ancestor = ancestor->GetParent();
        }
#endif // wxUSE_ACCEL

        // If not an accelerator, then emit KEY_DOWN event
        if ( !ret )
            ret = win->HandleWindowEvent( event );
    }

    return ret;
}

static gboolean
gtk_window_key_press_callback_after( GtkWidget *WXUNUSED(widget),
                                     GdkEventKey *gdk_event,
                                     wxWindow *win )
{
    wxPROCESS_EVENT_ONCE(GdkEventKey, gdk_event);

    wxKeyEvent event( wxEVT_KEY_DOWN );
    bool ret = false;

    // Only send wxEVT_CHAR event if not processed yet. Thus, ALT-x
    // will only be sent if it is not in an accelerator table.
    KeySym keysym = gdk_event->keyval;
    // Find key code for EVT_CHAR and EVT_CHAR_HOOK events
    long key_code = wxTranslateKeySymToWXKey(keysym, true /* isChar */);
    if ( !key_code )
    {
        if ( wxIsAsciiKeysym(keysym) )
        {
            // ASCII key
            key_code = (unsigned char)keysym;
        }
        // gdk_event->string is actually deprecated
        else if ( gdk_event->length == 1 )
        {
            key_code = (unsigned char)gdk_event->string[0];
        }
    }

    if ( key_code )
    {
        wxKeyEvent eventChar(wxEVT_CHAR, event);

        wxLogTrace(TRACE_KEYS, wxT("Char event: %ld"), key_code);

        eventChar.m_keyCode = key_code;
#if wxUSE_UNICODE
        eventChar.m_uniChar = gdk_keyval_to_unicode(key_code);
#endif // wxUSE_UNICODE

        AdjustCharEventKeyCodes(eventChar);

        ret = win->HandleWindowEvent(eventChar);
    }

    return ret;
}
```

I deleted the following code. GtkEntry(or GtkTextView)'s own handler handles the key event.
And `return_after_IM` variable is unnecessary because `wxTranslateGTKKeyEventToWx()` exists in both `gtk_window_key_press_callback_before()` and `gtk_window_key_press_callback_after()`.
And I think that `win->m_imKeyEvent` is unnecessary because the variable is not used in `wxTextEntry::GTKIMFilterKeypress()`, `wxTextCtrl::GTKIMFilterKeypress()` and `wxWindowGTK::GTKIMFilterKeypress()`. When `m_imKeyEvent` is referenced elsewhere it is likely to always point to a `NULL` value. It really needs confirmation.


```
    if ( !ret )
    {
        // Indicate that IM handling is in process by setting this pointer
        // (which will remain valid for all the code called during IM key
        // handling).
        win->m_imKeyEvent = gdk_event;

        // We should let GTK+ IM filter key event first. According to GTK+ 2.0 API
        // docs, if IM filter returns true, no further processing should be done.
        // we should send the key_down event anyway.
        const int intercepted_by_IM = win->GTKIMFilterKeypress(gdk_event);

        win->m_imKeyEvent = NULL;

        if ( intercepted_by_IM )
        {
            wxLogTrace(TRACE_KEYS, wxT("Key event intercepted by IM"));
            return TRUE;
        }
    }
```

**Comment by cogniti** [comment]
I think that this solution doesn't break `wxEVT_KEY/CHAR` event generation.

**Comment by vadz** [comment]
Could you please update the PR to do what you propose? TIA!

And, just to be clear, when you say that this solution doesn't break the events, have you tested them in the keyboard sample? The events are supposed to be the same whether the upper window is a plain `wxWindow` or a `wxTextCtrl` there.

**Comment by cogniti** [comment]
Okay. I will do so in my spare time.

**Comment by cogniti** [comment]
I don't know how to update PR. so I attach a patch file.

[im-patch.txt](https://github.com/wxWidgets/wxWidgets/files/3320635/im-patch.txt)

See https://github.com/cogniti/wxWidgets/commit/7aaa80316dc62e06947ea94050337b5b9a2f32b5

**Comment by cogniti** [comment]
Good!
After applying the path, the input method works when I focus on GtkEntry, GtkTextView.
The input method does not work when I focus on GtkWindow. But I can type. That's right.
The wxWidgets input function now works as expected.
Please test it. I have not tested GTK2 yet.
I have tested on Debian Linux Buster, lastest wxWidgets source, GTK 3.24.5-1

Screenshot from 2019-06-24 20-57-38

Right
Screenshot from 2019-06-24 21-09-12

combo box
Screenshot from 2019-06-24 21-11-40

**Comment by cogniti** [comment]
This patch has some problems because I deleted `wx_gtk_insert_text_callback ()`, `GTKIsUpperCase`, `SendMaxLenEvent`.
I will write again.

**Comment by vadz** [comment]
Thanks for your continued work on this!

To update a PR, you need to force-push to the existing branch. If you can't do this for whatever reason, please open a new PR when you have the final version of the changes. TIA!

**Comment by cogniti** [comment]
I opened a new PR. See https://github.com/wxWidgets/wxWidgets/pull/1367

**Pull request closed without merging**
