### PR TITLE
Avoid converting UTF-8 literals to wxString implicitly for wxGetTranslation

### PR DESCRIPTION
**Pull request by jhasse**
This is a continuation of #773, I've created a new PR so that the CI runs again.

### CODE REVIEW

**Comment by vadz** [comment]
I'm on the edge about this one. It complicates things and adds some string copies and I'm not sure it's worth it. In the vast majority of cases, msgids are in English, i.e. ASCII, and you can always use wide-string literals (`L"foo"`) or Unicode literals (`U"foo"`) when this is not the case.

Does anybody else think we really need this?

**Comment by jhasse** [comment]
> adds some string copies

Where?

> msgids are in English, i.e. ASCII

There's still non-ASCII stuff in English, e.g. …, €, µ, etc.

> and you can always use wide-string literals (L"foo") or Unicode literals (U"foo") when this is not the case.

Makes it a little harder to extract those using xgettext though.

**Comment by vadz** [comment]
I think the real question is how hard, exactly, is it to extract wide or Unicode literals with xgettext. I must admit that I don't even know how to do it, would you already know it by chance? If it's possible (in some not horribly complicated way) I'd rather do it like this...

**Comment by jhasse** [comment]
I just tried it and it seems that xgettext will notice a prefix like `L` and remove it automatically. So I must correct myself: It's just as easy.

**Pull request closed without merging**
