### PR TITLE
Fix OpenGL issues on Mojave

### PR DESCRIPTION
**Pull request by dkulp**

### CODE REVIEW

**Comment by csomor** [comment]
Excellent, thanks a lot for tracking this down, the funny thing is, that I turned off all related drawing and still had the problem, so it must be the GLView as well which is relevant.

**Comment by csomor** [comment]
Applied with thanks

**Comment by dgud** [comment]
Can this be backported to stable as well?

**Comment by mrjbq7** [comment]
What issues were you seeing?  We're having trouble in the Factor project and maybe it's a related bug?  Also, do you know where Apple documents the layer-based changes they made?

**Comment by csomor** [comment]
I've modified things due to a bug report slightly:

8ace56a84e4584ae259ec5b034e6b7292b40232d

**Comment by ojwb** [comment]
Was this ever backported to the WX_3_0_BRANCH branch?  I don't see any commits there with `10.14` in the commit message.

We're seeing a crash with wxGLCanvas and 3.0.4 (plus any patches homebrew apply) - it seems this assertion fails:

```
    wxASSERT_MSG( window->MacGetCGContextRef() != NULL, wxT("using wxPaintDC without being in a native paint event") );
```

We can't open a modal dialog at that point so we don't actually see the assertion message, but I added a check to my `wxPaintEvent` handler method:

```
if (MacGetCGContextRef() == NULL) return;
```

Doing that avoids the crash (but nothing gets drawn).

The changes here removed that assertion from master, and the user who's hitting the problem reports it started on upgrading to 10.14.4, so this seems a likely culprit.

There's a full backtrace in the ticket reporting the issue: https://trac.survex.com/ticket/101

**Comment by csomor** [comment]
Fixing this in 3.0 would mean binary incompatible changes. I think as long as you build under 10.13 you should be safe when running under 10.14 as backwards compatibility handling by the OS should kick in. Or am I wrong ?

**Comment by ojwb** [comment]
Thanks for the quick response.

> I think as long as you build under 10.13 you should be safe when running under 10.14 as backwards compatibility handling by the OS should kick in. 

As long as what's built on 10.13?  wxWidgets or the app (or both)?

With homebrew the build generally happens on the end user's machine when they install, but it looks like there are "bottles" for the wxmac package (which are prebuilt binary versions):

https://formulae.brew.sh/formula/wxmac

If it's just where wx is built which matters, then maybe installing the bottle from an older version would work (if that's possible).  If it's the app, I guess I need to find a way to build bottles of my app.

(I don't have a Mac myself, so I can't just try that.)

**Comment by ojwb** [comment]
It occurred to me to try just disabling assertions during the paint handler, and a user on 10.14.4 confirmed this makes my application work properly for them again.  Here's what I applied:

https://github.com/ojwb/survex/commit/7750c72ceb62e675e3f8be0fdd02a1d42d9b1712

We can't easily add the new `RequiresCGContextRef()` part of these changes without an ABI change and so can't add `!window->RequiresCGContextRef() ||` to the assertion check, but we could remove the assertion check entirely and it seems that would make wxGLCanvas in 3.0.x work on macOS 10.14.

Or if just removing the assertion seems too undesirable, perhaps there's a cruder check we can do so the assertion still fires in most of the cases where it is useful?  For example, if this only affects wxGLCanvas windows, we could use RTTI to check if `window` is a wxGLCanvas or a subclass.  That's probably a more costly check, but if we check RTTI after `window->MacGetCGContextRef() != NULL` then the RTTI should only get checked for wxGLCanvas windows on the most recent macOS.

**Comment by vadz** [comment]
FWIW I agree that using dynamic cast for windows without `CGContextRef` would be an improvement in 3.0, ugly as it is.

**Comment by ojwb** [comment]
> I agree that using dynamic cast for windows without CGContextRef would be an improvement in 3.0, ugly as it is.

I've opened #1414 with a patch implementing that.

**Pull request closed without merging**
