### PR TITLE
Fix mdi window menu label translation

### PR DESCRIPTION
**Pull request by utelle**
If an wxMDIParentFrame has open child windows, when the locale is changed, then one ends up with 2 entries in the menubar for the Window menu on closing all child windows and then opening new child windows, because the new translation is used to find the menubar entry. One entry (without submenu entries) is labelled with the previous translation and one entry (with submenu entries) is labelled with the new translation.

Now the translation that was active on adding the Window menu is remembered and used to locate the right menubar entry on removing the Window menu.

### CODE REVIEW

**Comment by vadz** [comment]
Thanks!

I wonder if using a global here is safe, i.e. are we sure we can't have any problems if we have 2 MDI TLWs, couldn't they somehow end up with conflicting values? This definitely seems unlikely, but I'm not sure if it's really impossible, which is why I had originally thought to keep the translated "Window" menu label as a member in `wxMDIParentFrame`. Are you sure this is not necessary?

**Comment by utelle** [comment]
The translation is now remembered in a member variable.

However, for my original problem this is still not the full solution, because I need to be able to force an update of the window menu label after a change of the locale.

In my local development environment I added an optional parameter (`bool force = false`) to method `SetWindowMenu` and modified the method to remove and re-add the window menu even if the window menu pointers are equal when the parameter `force` equals `true`. This works as expected.

Should I add this change to this pull request? Or should I create another pull request?

**Comment by vadz** [comment]
@utelle Sorry for the delay, I finally got back to this and created #909 replacing this one as I had to get rid of 2 (accidental?) merges in this one. Please let me know if you have any problems with that PR and if not I'll apply it soon. TIA!

**Comment by utelle** [comment]
I'm fine with #909. Thanks for taking care of this issue.

**Comment by vadz** [comment]
Oops, sorry for the confusion, #909 is this one, of course, I meant that I created #937.

**Pull request closed without merging**
