### PR TITLE
Fixed enabling debug help API for Linux build.

### PR DESCRIPTION
**Pull request by a-wi**
This is a fix for the issue [17451](http://trac.wxwidgets.org/ticket/17451).

### CODE REVIEW

**Comment by vadz** [comment]
Thanks for looking at this, clearly my changes were indeed wrong. However I don't think this PR is quite correct neither because this part of `setup.h.in` is autogenerated and so this would need to go in `include/wx/msw/setup_inc.h` and then modified to also work for the builds not using configure.

Also, as a cosmetic change, we should call the new symbol `wxHAVE_DEBUGHLP_API`.

**Comment by a-wi** [comment]
Commit has been updated.
It was necessary to use some additional hack with defining wxUSE_DBGHELP in the conditional statement:
`#define wxUSE_DBGHELP 1/0` statements are replaced with `#define wxUSE_DBGHELP (1==1)/(0==1)` because `update-setup-h` script replaces all `#define wxUSE_xxx 1` statements with `#define wxUSE_xxx 0` in the setup.h.in file

**Comment by a-wi** [comment]
I came to the conclusion that more intuitive and elegant way to fix the issue would be just to move conditional statement from setup files to wxMSW's `chkconf.h` file. In this case there is not necessary to introduce new helper macros and to modify `configure` scripts.
This alternative fix is implemented in #257.

**Comment by vadz** [comment]
The problem with this one is that configure really should be authoritative, so even if someone uses a version of MinGW not defining `__MINGW64_TOOLCHAIN__` but having the necessary declarations, the code should work instead of getting (silently) disabled, so I think 19819085f7ea5127496ca30e7f0d6a637bcf7189 is a better solution as it's more future-proof (even though I admit that it's quite unlikely that we're going to see any new compilers for MSW...).

**Pull request closed without merging**
