### PR TITLE
Fix Scintilla compilation on CentOS 6 (and others)

### PR DESCRIPTION
**Pull request by lanurmi**

### CODE REVIEW

**Comment by vadz** [comment]
Thanks! Should this be merged into 3.0 too?

**Comment by NewPagodi** [comment]
The set in question was only recently added (by me - sorry about that) to gen_iface.py to help with deprecating some macro values in wxWidgets that are no longer used in the Scintilla code.  So it doesn't exist in the gen_iface.py used with the 3.0 branch.

**Comment by NewPagodi** [comment]
Also, it looks like the copy of LexProgress.cxx included with Scintilla 3.21 (used with the 3.0 branch) does not have problematic line "#include "SparseState.h"", so it shouldn't be necessary to merge either change for the 3.0 branch.

**Comment by lanurmi** [comment]
Yes, both fixes were for relatively recent changes in master, and indeed the 3.0 branch compiles without trouble on CentOS 6 as it is.

**Comment by vadz** [comment]
Thanks to both of you for checking/confirming this!

**Pull request merged**
