### PR TITLE
Add Microsoft Visual Studio 2017 solution file for build wxMSW

### PR DESCRIPTION
**Pull request by TcT2k**
Allow building with VS15 out of the box

As you can see from the changes versioning with this VS version is unique:
* The toolset is called vs141/vs141_xp
* _MSC_VER is 1910
* Visual Studio Version is 15
* Product name is Visual Studio 2017

### CODE REVIEW

**Comment by dconnet** [comment]
> As you can see from the changes versioning with this VS version is unique:


Not really. :)  VC7.1 did the same thing.

Dave

**Comment by TcT2k** [comment]
Rebased and updated version check based on https://blogs.msdn.microsoft.com/vcblog/2016/10/05/visual-c-compiler-version/

**Comment by vadz** [comment]
Tobias, sorry, I don't remember any more: did we decide that this was the final versioning schema for MSVS 2017 or do we/you still plan to do anything else, notably about `wxVISUALC_VERSION` and `wxCHECK_VISUALC_VERSION` macros?

IOW, should this be already applied?

**Comment by TcT2k** [comment]
I think right now as there is no code checks dependent on `wxVISUALC_VERSION` or `wxCHECK_VISUALC_VERSION` so we do not need to decide right now.

I think this could be applied as is.
There is of course a slight inconsistency in the naming of the .sln files: Right now they are named `_vc15` which makes it easy for people thinking _"I have VS 15, I need to open that file"_, but technically correct it should be `_vc141` which might not be known to many people.

**Comment by vadz** [comment]
I actually think `wx_vc15.sln` is a more logical file name: the solution file should have the version of the Visual Studio (which is 15), not of the toolset (which is 14.1 and corresponds to the compiler version 19.1).

Anyhow, I'm going to apply this now, thanks!

**Comment by vadz** [comment]
What do you think of using `wxCOMPILER_PREFIX` of `vc140`, as for MSVS 2015, for 2017 too? This would seem to make sense, considering these compilers are ABI-compatible as it would make it easier to use 2017 for the application using the libs compiled with 2015. Any objections to my proposed patch in [this comment](https://trac.wxwidgets.org/ticket/18024#comment:4)?

**Comment by TcT2k** [comment]
Sounds good too me.
It should probably be documented somewhere user visible (readme,etc) to
prevent future confusion.

Am 16.12.2017 16:27 schrieb "VZ" <notifications@github.com>:

What do you think of using wxCOMPILER_PREFIX of vc140, as for MSVS 2015,
for 2017 too? This would seem to make sense, considering these compilers
are ABI-compatible as it would make it easier to use 2017 for the
application using the libs compiled with 2015. Any objections to my
proposed patch in this comment
<https://trac.wxwidgets.org/ticket/18024#comment:4>?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/wxWidgets/wxWidgets/pull/353#issuecomment-352189156>,
or mute the thread

**Pull request closed without merging**
