### PR TITLE
Set scale factor for icons loaded from resources

### PR DESCRIPTION
**Pull request by vadz**
Finally, it seems that we do need to use scale factor in wxMSW bitmaps too (i.e. @csomor was right) because otherwise using `wxGenericStaticBitmap` with an icon loaded from resources doesn't work correctly when the program runs on a high DPI system (and _not_ just moved to a monitor using high DPI, as in this case `LoadIcon()` didn't do any scaling).

I think the changes here are correct on their own, but they are _not_ enough to solve https://trac.wxwidgets.org/ticket/19331 so something is still missing here.

Of course, any review/testing is welcome as always, TIA!

### CODE REVIEW

**Comment by vadz** [comment]
@JulianSmart The latest commit reverts the changes you made a few years ago to wxAUI code. The commit message explains why I think these changes were wrong, but could you please re-check this and maybe explain why dud you make them in the first place? TIA!

**Comment by vadz** [comment]
@csomor Please have a look at this if you can, notably the change to `wxArtProvider`. TIA!

**Comment by csomor** [comment]
> @csomor Please have a look at this if you can, notably the change to `wxArtProvider`. TIA!

@vadz I'm checking it out now, I'll report, thanks

**Review by csomor — CHANGES_REQUESTED** [review]
On a retina display (lower screenshot), the dimensions of tabs etc. seem to be incorrectly doubled, the header 'tree pane' is sized correctly, but close icon is off

aui@1

aui@2

**Comment by csomor** [comment]
> @JulianSmart The latest commit reverts the changes you made a few years ago to wxAUI code. The commit message explains why I think these changes were wrong, but could you please re-check this and maybe explain why dud you make them in the first place? TIA!

@vadz your undoing breaks drawing under Retina on macOS. Drawing on a dc is using logical coordinates, always, on every platform, while on msw logical=pixel, and on mac logical=dip. So when using physical pixels we need to divide by the window's ContentScaleFactor to abstract from this. At least I'd think so ...

**Comment by vadz** [comment]
Thanks a lot for looking at this and setting me straight!

> @vadz your undoing breaks drawing under Retina on macOS. Drawing on a dc is using logical coordinates, always, on every platform,

Damn, I have no idea how did I manage to become confused with this once again :-( But somehow I was absolutely convinced that we needed physical coordinates here. I guess it was due to seeing all the `FromDIP()`s there because I thought of it as converting from logical to physical pixels, but actually this isn't right neither. I just can't formulate a good explanation of all this stuff.

> while on msw logical=pixel, and on mac logical=dip. So when using physical pixels we need to divide by the window's ContentScaleFactor to abstract from this. At least I'd think so ...

I think your commit might work (didn't have time to test it yet), but surely this is too complicated to ask all the user code to do it like this. We must find/provide a better API, IMO.

I guess I need to undo my changes and revert to never using scale factor for bitmaps under MSW and use only `wxBitmapBundle` in all code which must work correctly in high DPI. As I already wrote in the Trac ticket, I think it's the only way to do it, i.e. even if using `wxBitmap` worked in 3.1.5, I can't preserve this and make natural code using `wxBitmapBundle` work at the same time.

Or do you think using scale factor and then compensating for it with content scale factor is really the right thing to do?

**Comment by csomor** [comment]
@vadz when we had a ScaleFactor of 1 on msw, this meant we could use GetScaledWidth etc in the sense of GetLogicalWidth .... 

Since the ordinary GetWidth et al on a wxBitmap always return physical dimensions, using these directly is not working on non-msw platforms for drawing. 

So one way that came to my mind would be to have a GetScaled for the reason you needed it, but to have the 'old' semantics behind a GetLogical, dividing by scale on platforms that need it, and returning physical on msw ...

**Comment by vadz** [comment]
It's unclear if we still need scale factor in `wxBitmap` if we do this. I can only see that it could be useful for creating a `wxBitmapBundle` from it, but is it really worth it just for this? I'm not sure...

Unfortunately I have to stop here and put off this task until the next year.

**Comment by csomor** [comment]
> It's unclear if we still need scale factor in `wxBitmap` if we do this. I can only see that it could be useful for creating a `wxBitmapBundle` from it, but is it really worth it just for this? I'm not sure...

I think it is, it makes things more consistent. I've looked through the bug report and your fixes. My current view is:

I think it is correct, for any bitmap/icon to carry a scale factor with it -> size/scale = DIP size, this right now may only be useful for bundle creation, but there may be other situations as well ...

Up to now `GetScaledSize` was 'misused' as a kind of `GetLogicalSize`, because under MSW it always returned physical coordinates, and DIP on the others ...

If we now introduce a scale also under MSW we cannot just change the GetScaledSize contract there. For backwards compatibility I'd suggest we deprecate GetScaledSize and offer a GetLogicalSize with the same 'old' behaviour and add a GetDIPSize (or whatever name) which returns physicalSize/scale on every platform. This would be the method to call when creating a bundle.

> Unfortunately I have to stop here and put off this task until the next year.

sure, just write your feedback whenever you find the time to do so

**Comment by vadz** [comment]
@csomor Thanks for your explanations, things are (hopefully, but I know I said it before...) much clearer to me now. However I'm not sure about your backwards compatibility argument: IMO if we care about backwards compatibility (and we probably do, even if in principle we could break it in 3.2.0), we must preserve the old `GetScaledFoo()` behaviour and return just `GetFoo()` from them under MSW, rather than adding `GetLogicalFoo()` behaving like this. We do need new `GetDIFoo()` that would divide by the scaling factor even under MSW, but it seems to me that `GetScaledFoo()` should keep their old behaviour there.

The only problem I see with this is that `GetScaledFoo()` results will be inconsistent with `GetScaleFactor()` return value, i.e. we won't have `GetScaledFoo() === GetFoo() / GetScaleFactor()` on all platforms. But it's not like we ever guaranteed it anyhow.

So I suggest:

1. Reverting 214fbc6f1e and ac19e8bae1, i.e. just keep using `GetScaledFoo()` in wxAUI code.
2. Returning `GetFoo()` from `GetScaledFoo()` in wxMSW `wxBitmap`.
3. Adding a new set of functions `GetDIFoo()` ("DI" is really cryptic, but I think it's the least confusing choice, see below) to `wxBitmap` that would always return `GetFoo() / GetScaleFactor()` under all platforms.
4. Use `GetLogicalSize()` in `wxBitmapBundleImplArt::GetValidSize()`.

I've tried doing this locally and it works fine for me under MSW (and shouldn't change anything under Mac or GTK, as the changes don't affect their code). Any objections to doing it like this?

As for nomenclature, we seem to have

1. Device independent pixels (DIPs): this is what `FromDIP()` takes.
2. Logical pixels (LPs): used for window and DC coordinates.
3. Physical pixels (PPs): only used for the bitmap size and nowhere else, AFAICS.

The confusing thing is that `DIPs != LPs`, even though it might seem logical (pun definitely not intended!) to think that they're the same. Because of this we can't call the new `wxBitmap` methods `GetLogicalFoo()`: this would be nicer, but misleading.

Please correct me if I'm still wrong. If not, I'll document and push my changes soon. TIA!

**Comment by vadz** [comment]
I've done this now, please let me know if you (or anybody else) has any comments, otherwise I'd really like to merge it soon. TIA!

**Comment by csomor** [comment]
> I've done this now, please let me know if you (or anybody else) has any comments, otherwise I'd really like to merge it soon. TIA!

thanks, I'll do so over the weekend

**Comment by csomor** [comment]
The tabs like "Welcome to wxAUI" are twice as big on retina now, I'll try to isolate this

**Comment by csomor** [comment]
@vadz I've committed a fix for getting the tab size correct, but there are other situations which have the same setup, basically on macOS using `GetPreferredSizeFor` for anything drawing related will probably be wrong ...

I'm ok with keeping the `GetScaledFoo` behaviour as it was before, but I still think that adding a `GetLogicalFoo` synonym would be more intuitive. But that's just a wish not a request ;-)

The nomenclatura is correct and the naming on the Bitmap for the `GetDIFoo` methods consistent in my view.

**Comment by vadz** [comment]
@csomor Thanks!

We probably need some new API here because using `GetDefaultSize()` completely bypasses all the logic for finding the best (i.e. "preferred") size, which might not matter for macOS which only supports integer scaling factors, but should matter for GTK, where we'd want to use 1x bitmap in 125% scaling instead of using logical size that would result in scaling the bitmap by 1.25.

Or does all this preferred size stuff only matter for MSW?

**Comment by csomor** [comment]
`GetPreferredLogicalSizeFor` (win/dc) ? this then could be hiding the #ifdefs, use real sizes and scale down if appropriate ?

**Comment by vadz** [comment]
I've started adding it, but then I thought that maybe we should divide the value returned by `GetPreferredSizeFor()` by `GetContentScaleFactor()`? Because otherwise we'll basically need to have 2 copies of each and every function returning (or taking?) a `wxSize`...

**Comment by csomor** [comment]
> GetContentScaleFactor

Good point, I've switched at this place, works on mac as expected

**Comment by vadz** [comment]
Thanks! I'm going to merge this then, if you don't mind.

**Review by csomor — APPROVED** [review]

**Comment by csomor** [comment]
Please do so, we will probably have to replace a few places with this pattern, but we always do so later

**Comment by vadz** [comment]
I've indeed added `/ wnd->GetContentScaleFactor()` to the 2 other uses of `GetPreferredSizeFor()` in the same file. The commit 391080e77d (Use wxBitmapBundle for AUI tab pages bitmaps, 2021-11-13) where these calls were added also added it to `tabartmsw.cpp`, but this is MSW-specific, so I don't know if it's worth changing it there... Probably is, just for consistency, so let me do it too -- and then I'll merge.

Thanks again!

**Comment by vadz** [comment]
Hmm, looking at `wxStaticBitmapBase::DoGetBestSize()`, I've written this there:
```cpp
        // We have to round up the size to avoid truncating the bitmap.
        return wxSize(ceil(size.x/scale), ceil(size.y/scale));
```
instead of just using `size / scale`. I wonder if we really care about the difference between `ceil()` and `round()`, but if we do, we should do this in this code as well.

**Comment by vadz** [comment]
But let me merge this and deal with the ceil/round issue separately.

**Pull request merged**
