### PR TITLE
Misc mac fixes

### PR DESCRIPTION
**Pull request by vadz**
Some minor changes to get rid of a few warnings in Mac build using older SDK.

Stefan, do you agree with removing `bool clip`? I could just suppress the warning about it being unused, if you think it's useful to keep it, but as it doesn't do anything, I'd prefer to remove it to make things more clear.

### CODE REVIEW

**Review by csomor — COMMENTED** [review]
I don't understand this correctly, the new constants in the new SDKs **are** named differently starting from 11 in AvailabilityVersions.h , shouldn't we then change the place where they are used ?

```
#define  MAC_OS_X_VERSION_10_16                          __MAC_10_16
#define  MAC_OS_VERSION_11_0                             __MAC_11_0

```

**Review by csomor — APPROVED** [review]
I usually like having the bool param in a setter, but since we would probably never want to revert it after having set it, I agree that we can simplify things this way

**Comment by vadz** [comment]
> I don't understand this correctly, the new constants in the new SDKs **are** named differently starting from 11 in AvailabilityVersions.h , shouldn't we then change the place where they are used ?
> 
> ```
> #define  MAC_OS_X_VERSION_10_16                          __MAC_10_16
> #define  MAC_OS_VERSION_11_0                             __MAC_11_0
> ```

I didn't realize Apple renamed them. But in our code we only use `MAC_OS_X_VERSION_XXX`, and never `MAC_OS_VERSION_XXX`. IMHO it would be better to use consistent names, so if you prefer to drop the `_X` part, we'd need to remove it from all (27 at the last count) the existing tests. I could do it if you want, but I'm not sure it's worth it...

**Comment by csomor** [comment]
Why can't we just use the versions Apple defines ? starting from 11 the _X_ is dropped, before that it's there, so I think we don't have to change things, do we ? I have not found occurrences

**Pull request merged**
