### PR TITLE
Locale-related fixes for macOS and new calendar names localization functions

### PR DESCRIPTION
**Pull request by vadz**
@utelle I'd appreciate your thoughts about this, notably if we should change `FromTag()` to deal with strings of the form `zh_Hant_TW` directly and/or if you see any better way of handling this at `NSLocale` level.

### CODE REVIEW

**Comment by utelle** [comment]
> @utelle I'd appreciate your thoughts about this, notably if we should change `FromTag()` to deal with strings of the form `zh_Hant_TW` directly

Well, I'm a bit confused. According to the [macOS documentation](https://developer.apple.com/library/archive/documentation/MacOSX/Conceptual/BPInternational/LanguageandLocaleIDs/LanguageandLocaleIDs.html) locale identifiers which contain a script part should have a **hyphen** to separate the _script_ code from the _language_ code, **not** an **underscore**. Method `FromTag` already handles tags of the form `zh-Hant_TW` correctly.

So, where does the tag with **2** underscore delimiters come from? User input? If yes, the syntax is simply wrong. From the system? In that case I'd say it is a bug in the system.

> and/or if you see any better way of handling this at `NSLocale` level.

I will have to take a closer look whether there exists a better handling option.

**Comment by vadz** [comment]
> So, where does the tag with **2** underscore delimiters come from?

From `[NSLocale availableLocaleIdentifiers]`, which is what this code works with. You could say that it's a bug, or you could say that the documentation is incorrect, but we can't really change it, so we have to deal with it and the only possibilities I see is what I did, which is less disruptive, or changing `FromTag()` to deal with this format (which would involve at least preventing it from "recognizing" `Hant_TW` as Windows sort order...).

> > and/or if you see any better way of handling this at `NSLocale` level.
> 
> I will have to take a closer look whether there exists a better handling option.

TIA!

**Comment by vadz** [comment]
> Throughout all Apple documentation I haven't seen locale identifiers with 2 underscore delimiters.

Yes, I know, which is why I think it could be also a bug in their documentation. But we have to live with what we have...

> `availableLocaleIdentifiers` returns a **very** long list of locale tags with quite a number of exotic locales. The list is completely unsorted. I haven't checked **all** entries, but regarding _Chinese_ I found entries which will make it hard to determine the right entry: `zh`, `zh_Hans`, `zh_Hant`, `zh_Hans_CN`, `zh_Hant_CN` ...
> 
> IMHO the script part should be checked, too, if the tag to be checked contains a script part. I wonder which entry macOS selects if no script part is given.

I couldn't determine this, but I'm also worried by it, see the commit message. The trouble is that we can't really do much without more information than we currently have: if all we've got is `zh_CN`, how are we supposed to know that its default script should be `Hans`? Other than checking for "Simplified" in the description I don't think we can get this information from the current language database contents...

> What we could do, if we find more than one underscore delimiter, is to replace the underscores by hyphens. Then interpreting the tag would work as expected. As far as I can tell underscores are not allowed as a vaild character of a tag part.
> 
> In your code you do just that. It seems to be logical to integrate that approach in method `FromTag`.

I thought about this too but wasn't completely sure if it was safe to do it in general, which is why I preferred to do it in Mac-specific code only. If you think it's ok, I can change this or I can merge this PR as is (because I'd also like to backport it to 3.2) and then you could update it if you'd like. Please let me know, TIA!

**Comment by utelle** [comment]
> > Throughout all Apple documentation I haven't seen locale identifiers with 2 underscore delimiters.
> Yes, I know, which is why I think it could be also a bug in their documentation. But we have to live with what we have...

Yes, there is no other choice. Fortunately, macOS is the only platform using this locale tag representation with 2 underscores. Under Windows and Linux I haven't seen any tags with more than one underscore.

> The trouble is that we can't really do much without more information than we currently have: if all we've got is `zh_CN`, how are we supposed to know that its default script should be `Hans`? Other than checking for "Simplified" in the description I don't think we can get this information from the current language database contents...

If the user does not specify a script, we need to rely on `localeWithLocaleIdentifier` to return the most appropriate locale for the given language and country codes. And most likely that is the case.

I don't think it is worth the effort to extend the language database by the default script of the locales.

> > What we could do, if we find more than one underscore delimiter, is to replace the underscores by hyphens. [...]
> > In your code you do just that. It seems to be logical to integrate that approach in method `FromTag`.
> 
> I thought about this too but wasn't completely sure if it was safe to do it in general, which is why I preferred to do it in Mac-specific code only. If you think it's ok, I can change this or I can merge this PR as is (because I'd also like to backport it to 3.2) and then you could update it if you'd like. Please let me know, TIA!

IMHO it is safe to handle tags with 2 underscores within `FromTag`.

The change to `FromTag` should be rather simple. Only the part handling a Windows sort order needs to be modified. The current code is the following:

```C++
    // 1d. Check for sort order in Windows tag
    //
    // Make sure we don't extract the region identifier erroneously as a sortorder identifier
    {
        wxString tagTemp = tagMain.BeforeFirst('_', &tagRest);
        if (tagRest.length() > 4 && locId.m_modifier.empty() && locId.m_charset.empty())
        {
            // Windows sortorder found
            locId.SortOrder(tagRest);
            tagMain = tagTemp;
        }
    }
```

Changing the line determining `tagTemp` as follows should do the trick:

```C++
        wxString tagTemp = tagMain.BeforeLast('_', &tagRest);
```
If the part that potentially represents a sort order is not long enough, the `tagMain` remains unchanged, and in the next step all underscores are replaced by hyphens.

**Comment by utelle** [comment]
> IMHO it is safe to handle tags with 2 underscores within `FromTag`.

This definitely works ... after adjusting the code for detecting a Windows sort order attribute.

> The change to `FromTag` should be rather simple. Only the part handling a Windows sort order needs to be modified. The current code is the following:
> 
> ```c++
>     // 1d. Check for sort order in Windows tag
>     //
>     // Make sure we don't extract the region identifier erroneously as a sortorder identifier
>     {
>         wxString tagTemp = tagMain.BeforeFirst('_', &tagRest);
>         if (tagRest.length() > 4 && locId.m_modifier.empty() && locId.m_charset.empty())
>         {
>             // Windows sortorder found
>             locId.SortOrder(tagRest);
>             tagMain = tagTemp;
>         }
>     }
> ```
> 
> Changing the line determining `tagTemp` as follows should do the trick:
> 
> ```c++
>         wxString tagTemp = tagMain.BeforeLast('_', &tagRest);
> ```

Using `wxString::BeforeLast()` works, if one takes into account that `tagTemp` will be empty, if the search character (here: underscore) was not found at all. Therefore it is necessary to verify that `tagTemp` is **not** empty, before assuming a sort order attribute:

```c++
        if (tagTemp.length() > 0 && tagRest.length() > 4 &&
            locId.m_modifier.empty() && locId.m_charset.empty())
```

PR #23562 includes this adjustment.

**Review by utelle — CHANGES_REQUESTED** [review]
Unfortunately, I had 2 small glitches in my original PR. In case of falling back to English names the methods must be called with the parameter `form` (not `flags`). This only affects systems that don't have `HAVE_LANGINFO_H` defined.

**Comment by vadz** [comment]
@utelle Just to be sure: this is ok to merge now, right?

**Comment by utelle** [comment]
> @utelle Just to be sure: this is ok to merge now, right?

Yes, AFAICT all related issues are addressed and all checks are successful. So, it should be ok to merge.

**Comment by marekr** [comment]
Curious, is the changes to matching the locale in uilocale.mm going to be backported to 3.2?

We have issues in KiCad where users cannot switch their app language to zh_TW or zh_CN and I wonder if it's because the OS is returning the longer names i.e. zh_Hant_TW

**Comment by vadz** [comment]
@marekr The particular problem you're speaking of is #23209 which is a (strict) subset of the changes in this PR, so I won't backport all of the changes here, but I will indeed backport 6d849f8211977ab969f9fd4a503d6ad362f95e53 and a couple of related commits, thanks for the reminder.

I'll also backport the fix for #23557, i.e. PR #23603.

**Pull request merged**
