### PR TITLE
wxGrid crashes when dragging a header past the last column

### PR DESCRIPTION
**Pull request by jgehrig**
I found this while debugging a crash in KiCad.
image

## Repro Steps
1. Start with a wxGrid object that does not have enough columns to fill its entire width.
2. Click on any column header.
3. Drag the selected column header past the end of the last column (see blue box above).
4. App crashes due to an "array out of bounds" error.

You can find this specific repro in KiCad's "Eeschema" app. Look for the "Edit symbol fields" icon (it looks like a spreadsheet) on the toolbar.

## Fix Explanation
As far as I can tell, this is an error in wxWidgets code where an error case is not properly handled/expected. I inspected a crashing callstack in GDB, and see the errors occurring in routines outside of KiCad's control. I'm no expert in wxWidgets, so forgive me if I am missing something obvious :)

The following line can return COL_NONE, which is not a valid index.
`colNew = FindColumnAtPoint(xPhysical);`

When the cursor is outside of the valid columns, COL_NONE should be expected. However, we directly set a position index from this value, without handling the (possible) error case.
`const unsigned pos = GetColumnPos(colNew);`

A simple return-early guard against this invalid value should resolve the crash.

## Testing
I have done some limited manual testing. The patch is compiled and running system-wide on my Linux box, and I haven't seen crashes/odd behavior.

The repro steps above no longer result in a crash.

### CODE REVIEW

**Comment by vadz** [comment]
This is indeed a bug in `wxHeaderCtrl`, thanks for reporting it!

However I don't think the fix is entirely correct: it prevents the crash from happening, but it also doesn't drag the column to the correct place (i.e. last one). I think it would be better to check for `COL_NONE` and use the last column index in this case. Notice that the same thing should be done in `UpdateReorderingMarker()`, i.e. it should show the marker at the last position when `col == COL_NONE` instead of not showing it at all, so it probably makes sense adding some `FindColumnBeforePoint()` which would return the last column for the coordinates beyond the end of the last column and use it in both of these functions.

If you could update this PR to do this instead, it would be great! Otherwise, I'll try to find time to do it myself and if I don't manage to do it neither, we should at least apply the current fix to avoid the crash.

**Comment by jgehrig** [comment]
I agree.

I wrote it this way because the marker does not update, and goes away after dragging beyond the last column by more than the "fudge factor" (8px?). I figured this was the desired behavior.

I think the behavior you describe is more in line with what users would expect. I should be able to find some time to implement this over the next few days. I will post a new PR once I get everything written and tested.

**Comment by jgehrig** [comment]
I added a second commit to address @vadz's comments.

**Comment by vadz** [comment]
Thank you for the update! I'll merge it soon with some minor changes (I've tweaked formatting a little and renamed the new function to `FindColumnClosestToPoint()` which seems a bit more clear to me).

**Pull request closed without merging**
