### PR TITLE
Add wx logo art ID and use SVG to provide it in any size

### PR DESCRIPTION
**Pull request by vadz**
cc @PBfordev

### CODE REVIEW

**Comment by PBfordev** [comment]
I don't have any comments about the code.

I just wonder whether when using the logo this way, if we should not use its optimized version. It currently has 12 5 kB, when saved as optimized SVG by InkScape, I got it down to about 4 kB. It should be not only smaller, but also faster to parse as well?

BTW, I was considering creating a PR adding MSW only 
``` cpp
wxBitmapBundle::FromSVGResource(const wxString& resourceName, WXHINSTANCE module = NULL);
```

Do you think it would be useful or not?

**Comment by vadz** [comment]
> I just wonder whether when using the logo this way, if we should not use its optimized version. It currently has 12 5 kB, when saved as optimized SVG by InkScape, I got it down to about 4 kB. It should be not only smaller, but also faster to parse as well?

I thought about removing unnecessary stuff from it by hand, but decided it wasn't worth spending time on this because I'm not actually 100% sure what is unnecessary and what isn't, so I'd have to double check everything. If there is some way to do it automatically or if you can do it quickly (because you know SVG format well enough to do it), this would certainly be welcome. Please just attach the new SVG file here if you can make it -- or feel free to make another PR later, of course, if you prefer.

> The original logo also has quite a bit margin about it, not sure it that is suitable here.

I'm not sure about the margin, I preview SVFs in Firefox and it's not exactly a great image viewer... What do you use to view them, BTW?
 
> BTW, I was considering creating a PR adding MSW only (analogical to `wxIconBundle` ctor/method)
> 
> ```c++
> static wxBitmapBundle wxBitmapBundle::FromSVGResource(const wxString& resourceName, WXHINSTANCE module = NULL);
> ```
> 
> Do you think it would be useful or not?

Yes, I think it would be nice to have, I hesitated to do it for this PR but finally decided that there was no real advantage in using resources for MSW while we still needed to embed SVG in some other way for the other platforms. I just think that we'd need the size parameter here, as usual.

TIA!

**Comment by vadz** [comment]
I've merged this in its current state for now because I needed it to create #22051, but an optimized version of the SVG would still be welcome, TIA!

**Comment by PBfordev** [comment]
>> I thought about removing unnecessary stuff from it by hand, but decided it wasn't worth spending time on this because I'm not actually 100% sure what is unnecessary and what isn't, so I'd have to double check everything. If there is some way to do it automatically or if you can do it quickly (because you know SVG format well enough to do it)

I just use Inkscapes's Save Copy As and set the Type to "Optimized SVG". AFAIK, this does not modify anything related to drawing (unless you count optionally rounding coordinates), just the stuff that is not necessary, including whitespace.

wxlogo includes lots of unneeded stuff, e.g., all those sodipodi/Inscape private things.

For viewing SVG's I use Inkscape and Chrome. You can tell that the logo has a lot of margin around it for example from the webview sample  where it, unlike the ones I drawn, does not fill the toolbar button space.

**Pull request merged**
