### PR TITLE
Fix reusing smaller bitmaps in `wxBitmapBundle`

### LINKED ISSUE #24703: MSW Crash due to GDI objects exhaustion when getting resized images from wxBitmapBundle.
### Description

Using this code will lead to exhaustion of GDI objects on Windows, causing a crash:

```cpp
#ifdef __WINDOWS__
    ::AttachConsole(ATTACH_PARENT_PROCESS) || ::AllocConsole();

    if (::GetStdHandle(STD_INPUT_HANDLE) != INVALID_HANDLE_VALUE)
    {
        freopen("CONIN$", "r", stdin);
        setvbuf(stdin, NULL, _IONBF, 0);
    }

    if (::GetStdHandle(STD_OUTPUT_HANDLE) != INVALID_HANDLE_VALUE)
    {
        freopen("CONOUT$", "w", stdout);
        setvbuf(stdout, NULL, _IONBF, 0);
    }

    if (::GetStdHandle(STD_ERROR_HANDLE) != INVALID_HANDLE_VALUE)
    {
        freopen("CONOUT$", "w", stderr);
        setvbuf(stderr, NULL, _IONBF, 0);
    }
#endif

    wxBitmapBundle bb = wxBitmap(32, 32);

    for (int i = 0;; i++) {
        wxBitmap bmp = bb.GetBitmap(wxSize(24, 24));

        std::cout << i << " " << bmp.GetHandle() << std::endl;
    }
```

`minimal` sample stack trace:

```
 	vcruntime140d.dll!memcpy() Line 343	Unknown
>	wxmsw330ud_core_vc_x64_custom.dll!wxBitmapRefData::wxBitmapRefData(const wxBitmapRefData & data) Line 246	C++
 	wxmsw330ud_core_vc_x64_custom.dll!wxBitmap::CloneGDIRefData(const wxGDIRefData * data) Line 401	C++
 	wxmsw330ud_core_vc_x64_custom.dll!wxGDIObject::CloneRefData(const wxRefCounter * data) Line 83	C++
 	wxbase330ud_vc_x64_custom.dll!wxObject::AllocExclusive() Line 330	C++
 	wxmsw330ud_core_vc_x64_custom.dll!wxGDIImage::SetScaleFactor(double scale) Line 354	C++
 	wxmsw330ud_core_vc_x64_custom.dll!wxBitmapBundle::GetBitmap(const wxSize & size) Line 593	C++
 	minimal.exe!MyFrame::MyFrame(const wxString & title) Line 204	C++
 	minimal.exe!MyApp::OnInit() Line 124	C++
 	wxbase330ud_vc_x64_custom.dll!wxAppConsoleBase::CallOnInit() Line 92	C++
 	wxbase330ud_vc_x64_custom.dll!wxEntryReal(int & argc, wchar_t * * argv) Line 569	C++
 	wxbase330ud_vc_x64_custom.dll!wxEntry(int & argc, wchar_t * * argv) Line 171	C++
 	wxmsw330ud_core_vc_x64_custom.dll!wxEntry(HINSTANCE__ * hInstance, HINSTANCE__ * __formal, char * __formal, int nCmdShow) Line 232	C++
 	minimal.exe!WinMain(HINSTANCE__ * hInstance, HINSTANCE__ * hPrevInstance, char * lpCmdLine, int nCmdShow) Line 105	C++
 	minimal.exe!invoke_main() Line 107	C++
 	minimal.exe!__scrt_common_main_seh() Line 288	C++
 	minimal.exe!__scrt_common_main() Line 331	C++
 	minimal.exe!WinMainCRTStartup(void * __formal) Line 17	C++
 	kernel32.dll!BaseThreadInitThunk()	Unknown
 	ntdll.dll!RtlUserThreadStart()	Unknown

```

`memcpy` line:
https://github.com/wxWidgets/wxWidgets/blob/ba026c21d85a94e2e95034621b4c2b7b087decd6/src/msw/bitmap.cpp#L245

---

Stack trace in KiCad:

```
0   VCRUNTIME140.dll                0x7ff8171214f3      memcpy (memcpy.asm:338)
1   wxmsw32u_core_vc_custom.dll     0x7fff9eab5c0a      wxBitmapRefData::wxBitmapRefData (bitmap.cpp:246)
2   wxmsw32u_core_vc_custom.dll     0x7fff9eab64d7      wxBitmap::CloneGDIRefData (bitmap.cpp:402)
3   wxbase32u_vc_custom.dll         0x7fffe1687d4f      wxObject::AllocExclusive (object.cpp:386)
4   wxmsw32u_core_vc_custom.dll     0x7fff9eae5524      wxGDIImage::SetScaleFactor (gdiimage.cpp:351)
5   wxmsw32u_core_vc_custom.dll     0x7fff9eaa697a      wxBitmapBundle::GetBitmap (bmpbndl.cpp:561)
6   _pcbnew.dll                     0x7fff9cf7a77f      WX_AUI_TOOLBAR_ART::DrawButton (wx_aui_art_providers.cpp:111)
7   wxmsw32u_aui_vc_custom.dll      0x7ff831b70293      wxAuiToolBar::OnPaint (auibar.cpp:2472)
8   wxbase32u_vc_custom.dll         0x7fffe15f60f3      wxAppConsoleBase::CallEventHandler (appbase.cpp:673)
9   wxbase32u_vc_custom.dll         0x7fffe16edfde      wxEvtHandler::ProcessEventIfMatchesId (event.cpp:1431)
10  wxbase32u_vc_custom.dll         0x7fffe16edbbb      wxEventHashTable::HandleEvent (event.cpp:1039)
11  wxbase32u_vc_custom.dll         0x7fffe16eee5c      wxEvtHandler::TryHereOnly (event.cpp:1628)
12  wxbase32u_vc_custom.dll         0x7fffe16edf42      [inlined] wxEvtHandler::TryBeforeAndHere (event.h:4007)
13  wxbase32u_vc_custom.dll         0x7fffe16edf42      [inlined] wxEvtHandler::ProcessEventLocally (event.cpp:1561)
14  wxbase32u_vc_custom.dll         0x7fffe16edf42      wxEvtHandler::ProcessEvent (event.cpp:1534)
15  wxbase32u_vc_custom.dll         0x7fffe16eea59      wxEvtHandler::SafelyProcessEvent (event.cpp:1650)
16  wxmsw32u_core_vc_custom.dll     0x7fff9eb3d1f2      wxWindow::HandlePaint (window.cpp:5373)
17  wxmsw32u_core_vc_custom.dll     0x7fff9eb40807      wxWindow::MSWHandleMessage (window.cpp:3118)
18  wxmsw32u_core_vc_custom.dll     0x7fff9eb43ee7      wxWindow::MSWWindowProc (window.cpp:3906)
19  wxmsw32u_core_vc_custom.dll     0x7fff9eb48f15      wxWndProc (window.cpp:2948)
20  USER32.dll                      0x7ff837e18240      UserCallWinProcCheckWow
21  USER32.dll                      0x7ff837e17efb      DispatchClientMessage
22  USER32.dll                      0x7ff837e2302c      _fnDWORD
23  ntdll.dll                       0x7ff8396b33b3      KiUserCallbackDispatch
24  win32u.dll                      0x7ff83698c853      NtUserUpdateWindow
25  wxmsw32u_core_vc_custom.dll     0x7fff9eb46099      wxWindow::Update (window.cpp:1729)
26  wxmsw32u_aui_vc_custom.dll      0x7ff831b7151c      wxAuiToolBar::SetHoverItem (auibar.cpp:1485)
27  wxmsw32u_aui_vc_custom.dll      0x7ff831b70020      wxAuiToolBar::OnMotion (auibar.cpp:2887)
28  wxbase32u_vc_custom.dll         0x7fffe15f60f3      wxAppConsoleBase::CallEventHandler (appbase.cpp:673)
...
```

---

In KiCad, the plugin icons are drawn in the toolbar. Some plugins use 32x32 icons, which is scaled down to 24x24 via [`WX_AUI_TOOLBAR_ART`](https://gitlab.com/kicad/code/kicad/-/blob/d933a8d6a94aa0e93af51fea976f4de8d1357151/common/widgets/wx_aui_art_providers.cpp#L111).
The toolbar is redrawn at every mouse motion over it, so eventually the GDI object count exceeds the 10000 limit, and due to insufficient checking in https://github.com/wxWidgets/wxWidgets/blob/ba026c21d85a94e2e95034621b4c2b7b087decd6/src/msw/bitmap.cpp#L245, the program crashes.

---

This issue is the cause of 1.3k crash events with at least 215 affected users in the last 90 days.

Would be great to not leak GDI object when using `wxBitmapBundle::GetBitmap`, and even not allocate so much ref data for performance reasons also.

### Platform and version information

- wxWidgets version  you use: 3.2.5 / master
- wxWidgets port  you use: wxMSW
- OS  and its version: Windows 11

### PR DESCRIPTION
**Pull request by vadz**
This fixes #24703.

### CODE REVIEW

**Comment by dsa-t** [comment]
I get the "should use original bitmap" assert when doing something like this:

```cpp
    wxBitmapBundle bb = wxBitmap(32, 32);

    wxBitmap bmp = bb.GetBitmap(wxSize(24, 24));
    wxBitmap bmp2 = bb.GetBitmap(wxSize(48, 48));
```

**Comment by vadz** [comment]
Thanks, this is yet another bug, which wasn't correctly fixed in 538eafc78b (Fix bug with wrong GetIndexToUpscale() return value, 2022-06-03). Should be good now.

**Comment by dsa-t** [comment]
Thanks. Would be great to have the assert too, otherwise we'll never see if it happens again, potentially due to some other reason.

**Comment by vadz** [comment]
> Thanks. Would be great to have the assert too, otherwise we'll never see if it happens again, potentially due to some other reason.

Sorry, I don't understand this, is there perhaps a word missing somewhere here, i.e. "to have the assert" what?

**Comment by dsa-t** [comment]
See the added review comment above

**Comment by vadz** [comment]
Err, do you mean [this one](https://github.com/wxWidgets/wxWidgets/pull/24705#issuecomment-2229923556)? If so, did you see [my reply](https://github.com/wxWidgets/wxWidgets/pull/24705#issuecomment-2230818699) just below it?

**Comment by dsa-t** [comment]
No, this one:

image

**Comment by dsa-t** [comment]
We don't collect `wxLogDebug` messages, while we do collect assert failures. And most users don't run wxWidgets in Debug, so they won't see any dialogs.

I think the assert failure dialog comes from the OS and is not affected by drawing issues?

**Comment by vadz** [comment]
When debug is disabled, asserts are not shown neither, so this point is a bit moot... For diagnostic purposes I think it could be useful to expose `wxGetCurrentlyUsedResources()` in public API, as this would allow to include the amount of available resources in the crash report.

Assert dialogs, even when they're native, still dispatch paint events and so result in reentrancy.

But most of all I'm reluctant to use asserts for something that is not (necessarily) a programmer's error: we're only supposed to be using them to detect bugs, not resource exhaustion (which, in theory, may happen even without any bug in the program).

**Comment by dsa-t** [comment]
> When debug is disabled, asserts are not shown neither

They are not shown to the user, but we set a custom assert handler so they are collected in Sentry.

**Comment by vadz** [comment]
This is a good approach, but we have to think about all the other applications, that don't this, too...

**Pull request merged**
