### PR TITLE
Added wxApp::MacGetDockMenu()

### PR DESCRIPTION
**Pull request by joostn**
Override wxApp::MacGetDockMenu() to add custom menu items to the
context menu which appears when right-clicking on the application icon
in the Dock (while the application is running).

### CODE REVIEW

**Comment by TcT2k** [comment]
Apart from the interface what is the difference to using `wxTaskBarIcon` to add menu items to the dock icon?

**Comment by joostn** [comment]
It's totally different: if I understand correctly, wxTaskBarIcon creates an icon in the menu bar (at the top of the screen next to the clock). My code adds menu items to the context menu of the application icon in the Dock (at the bottom of the screen).

**Comment by joostn** [comment]
For example, right-click on the Safari Icon on mac:  you'll see options for 'New Window' and 'New Private Window'. I'd like to implement something similar for my own application.

**Comment by TcT2k** [comment]
`wxTaskbarIcon` can create an icon in the menu bar, but the default is to use the dock icon (and expand it's menu). Have a look at the taskbar sample to see what I mean.

**Comment by joostn** [comment]
I wasn't aware of this! 
You're right, this means there's no need for this patch, I'll close the pull request.

**Pull request closed without merging**
