### PR TITLE
Fixes for issues involving dialogs ending up behind their parent

### PR DESCRIPTION
**Pull request by lanurmi**
Dialogs with a wxFRAME_FLOAT_ON_PARENT frame as parent were left behind their parent when switching back to the application. Modal dialogs move with their parent, and the non-active parent could completely obscure the dialog behind it, leaving no way to close the dialog.

Also a fix dialogs showing behind their wxSTAY_ON_TOP parent.

### CODE REVIEW

**Comment by vadz** [comment]
Any comments from Mac-savvy people would be welcome, otherwise I'll just merge it in some relatively near future and we'll see what it breaks.

**Comment by discnl** [comment]
Confirmed the `wxSTAY_ON_TOP` and `wxFRAME_FLOAT_ON_PARENT` related fixes on 10.7, 10.11, and 10.12.

However one thing that now occurs and didn't before is what johnr mentioned in [ticket #4355](http://trac.wxwidgets.org/ticket/4355): "the frames and dialogs moved when their parent moved which is non-standard behaviour for wxWidgets."

I applied johnr's  minsample_framedlg_stack.diff​ from that ticket and then run the minimal sample. I click on "Show Dialog" and then use "click me again" which first shows either a `wxTextEntryDialog` or a `wxMessageDialog`. When it's a `wxMessageDialog` then that dialog doesn't move relative to movement of the initial frame (by dragging the frame's title bar), which to me seems correct behaviour. But when a `wxTextEntryDialog` is shown (by closing the `wxMessageDialog` and trying "click me again" once more) then that dialog does move along with the frame, which I don't expect.

In both cases the initial dialog (second TLW) moves along as well, which also seems unexpected to me.

**Comment by lanurmi** [comment]
> However one thing that now occurs and didn't before is what johnr mentioned in ticket #4355: "the frames and dialogs moved when their parent moved which is non-standard behaviour for wxWidgets."

Yes, I noticed this comment by johnr, but he was implying there is such a thing as "standard wxWidgets behaviour", while I consider the standard behaviour is to follow the platform's native behaviour. So moving frames and dialogs with their parent is not necessarily wrong, _if_ that is what is supposed to happen on OS X.

If you change johnr's diff to call `dlg->ShowModal();` instead, then the dialog also moves with its parent even in current master, without my fixes applied.

**Comment by discnl** [comment]
Agreed on following native behaviour. I thought the choice of window level might have been related, but you're right about a modal dialog already moving along with the parent frame in current master as well, so no problem there.

And with this PR when there's a frame + modeless dialog (with the frame as parent) + a modal dialog (with the modeless dialog as parent) all three TLWs now move when moving the frame, which also seems more consistent. With current master only the frame itself moves when dragging the frame, the two dialogs don't move.

The only discrepancy is that for example a (native) message box doesn't move along with the frame while a modal `wxDialog` does, however that's also the case with master and thus not a regression (and may actually be expected behaviour).

> otherwise I'll just merge it in some relatively near future and we'll see what it breaks.

+1. I also checked with the more exotic scenario where wx is used as a plug-in and the TLW of the plug-in is a `wxDialog` and found no problems (perhaps as expected as the changes might not affect that flow, I didn't follow code paths).

Regarding the code changes: maybe put all of the newly introduced opening curly brackets on their own line. Unfortunately wxOSX code often doesn't follow that guideline so it's easy to copy that style.

**Comment by bigjohnr** [comment]
> So moving frames and dialogs with their parent is not necessarily wrong, if that is what is supposed to happen on OS X.

No really checked the above and unless I have missed something, native dialogs, e.g. the message box and  other modal or non modal child dialogs in native programs, do not move with their parent unless they are shown using beginSheet:modalForWindow. 

While I think moving with the parent is a small price to pay for a fix with modal dialogs as they are usually centred on the parent, it will be a problem for non modal dialogs e.g. parent shown on left screen and child on right then moving the parent to the right pushes the child off screen. This might not be a problem for some of us but for novice users such as reception staff I think it will be very confusing.

**Pull request merged**
