### PR TITLE
Fix wxVariantDataSafeArray documentation

### PR DESCRIPTION
**Pull request by PBfordev**
Mention that one needs to call
wxAutomationObject::SetConvertVariantFlags(wxOleConvertVariant_ReturnSafeArrays)
to actually receive a wxVariant with SAFEARRAY (if possible).

Remove references to handy but undocumented wxSafeArray from code examples.

Make some minor language fixes.

### CODE REVIEW

**Comment by vadz** [comment]
Thanks! Not sure how I feel about removing `wxSafeArray<>`, the old code was showing a better example, even if it used a non-documented class. Could we just add the briefest possible documentation of this class saying that it's a RAII-based wrapper for `SAFEARRAY*` in the class description instead?

**Comment by PBfordev** [comment]
(I added both `wxVariantDataSafeArray` and `wxSafeArray` to **The old example had and issue that it did not include the header for `wxSafeArray`. For this revision  I originally considered adding the include, then I thought of displaying the SAFEARRAY accessed by Win32 API. 

In the end I decided to make the example simple, believing that working with SAFEARRAY was beyond the scope of the examples

**Comment by vadz** [comment]
Sorry, I forgot to answer this, but I think `wxSafeArray<>` is useful, i.e. I wouldn't consider writing the code without using it, so if you could please document it, it would be great. TIA!

**Comment by PBfordev** [comment]
TBH, I still think it is a bad precedent to expose such a private class, particularly when one is not forced to (because people were already using it), but I will provide a full documentation for the class and will use it in the `wxVariantDataSafeArray` docs examples.

**Comment by PBfordev** [comment]
Replaced by #1611 to make the commit history clean.

**Pull request closed without merging**
